### ISSUE TITLE
你好，有没有做文档搜索的计划

### ISSUE THREAD

**Issue by abowu** [star7th/showdoc#1]
你好，有没有做文档搜索的计划

**Comment by star7th** [comment]
文档搜索功能刚刚更新了

**Comment by abowu** [comment]
谢谢，这真是一个好项目，我向群里的朋友推荐了

**Comment by star7th** [comment]
新增了支持三级目录的功能；升级安装请参考部署手册中“升级安装”部分。http://blog.star7th.com/2016/05/2007.html
此外我新建了一个ShowDoc使用交流qq群（群号：564671853），欢迎探讨问题
