### ISSUE TITLE
权限控制不合理

### ISSUE THREAD

**Issue by CinderellaCiCi** [star7th/showdoc#10]
项目组成员都有权编辑和删除所有内容，删除的权限太大了。

建议只有项目创建者和页面创建者具备删除权限。

**Comment by star7th** [comment]
这个权限控制加上了

**Comment by CinderellaCiCi** [comment]
好赞。。我再试试。

**Comment by CinderellaCiCi** [comment]
嗯，还有删除目录的这个操作也得限制下。
这个我试了下，目录删掉了内容就全没了，看起来比页面操作的危险程度更高。

建议有两种处理方式：
1.删除目录时，将目录下的页面转移到根目录下；
2.权限控制；

个人倾向1，如果有勾选是否转移的选项就更好了。（因为方便一次性删除全部页面

**Comment by star7th** [comment]
我增加了一项限制："为了安全，不允许直接删除非空目录。请先删除或转移该目录下的所有页面"
