### ISSUE TITLE
php7.0环境下部署，所有的url少了index

### ISSUE THREAD

**Issue by joyme123** [star7th/showdoc#100]
出现的链接如下
http://xxx.xx.xxx.xx:8080/.php?s=/home/item/add
所有的链接都少了Index

**Comment by star7th** [comment]
试着安装这篇文章操作。如果不行我也不知道方法了，我没遇到过这种情况http://blog.csdn.net/diaosicodelife/article/details/50668405

**Comment by momopluto** [comment]
遇到相同的问题，最后解决了。

服务器用的是Nginx，配置有rewrite导致。

这里给个简单的可行基础配置：

`
# ******
# ******

http {

    # ******
    # ******

    # ShowDoc base config
    server {
        listen       8080;
        server_name  api.com;
        root   /usr/local/showdoc;

        access_log  logs/api.access.log;
        error_log   logs/api.error.log;

        location / {
            index  index.html index.htm index.php;
        }

        location ~ \.php$ {
            root        html;
            fastcgi_pass   127.0.0.1:9000;
            include        fastcgi_params;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  /usr/local/showdoc$fastcgi_script_name; 
        }
    }
}
`
