### ISSUE TITLE
runapi更新 "纯markdown文档" 左侧目录显示不正常

### ISSUE THREAD

**Issue by hsk-story** [star7th/showdoc#1002]
首先的问题是进行新增保存接口时, 新增的接口会跑到根目录去. 只能在左侧目录手动拖放到对应目录上
如果后续有修改"纯markdown文档"时, 修改的文档又会跑到根目录上. 又要重新手动拖放到对应的子目录中.
经测试如果是"带调试功能的API接口" 进行修改就不会有这个问题

**Comment by star7th** [comment]
已处理 .重启runapi即可
