### ISSUE TITLE
二次开发--更改前端页面不生效

### ISSUE THREAD

**Issue by RifeWang** [star7th/showdoc#1003]
尝试更改了 web_src 目录下的 vue 文件，比如删除一个 el-tooltip ，然后 npm run build ，Dockerfile 文件未更改，然后 docker build 打包，最后通过 docker 启动发现前端页面都没生效。
有关二次开发的内容可以详细说明一下吗，哪里有问题？

**Comment by star7th** [comment]
https://www.showdoc.cc/help?page_id=1385576954326448

RifeWang <notifications@github.com> 于2020年7月10日周五 下午3:56写道：

**Comment by star7th** [comment]
npm run build 就是打包.  然后如果刷新浏览器缓存后发现也还是没变的话,只能说自己没改对. 自己研究下吧

**Comment by RifeWang** [comment]
知道原因了，虽然改了文件，但是启动的时候挂载的位置没变，导致加载的仍然是原来的文件。
```
docker run -d --name showdoc --user=root --privileged=true -p 4999:80 \
-v /showdoc_data/html:/var/www/html/ star7th/showdoc
```

文档和样式都在同一个文件的吗？ 怎么重新挂载保持原来的文档？

**Comment by star7th** [comment]
把挂载目录清空. 它会自动从新镜像中提取代码来填充.

RifeWang <notifications@github.com> 于2020年7月10日周五 下午4:37写道：

**Comment by RifeWang** [comment]
但是原来的挂载目录不是还存了已经编写的文档吗

**Comment by star7th** [comment]
先备份, 然后清空挂载目录. 等它自动填充代码后, 再从备份中复制 Sqlite目录 过来 . 这个过程有点类似 服务器迁移
.只是你是迁移不同目录.   https://www.showdoc.cc/help?page_id=2511252204165611

RifeWang <notifications@github.com> 于2020年7月10日周五 下午4:41写道：

**Comment by RifeWang** [comment]
这种存储数据和代码部分能不能分开挂载，以后代码有变更，也不用迁移数据。

**Comment by star7th** [comment]
不会为了极少数的需求而增加复杂度. .实际上通常有二次开发能力的人他不会用docker ,他自身会搭建环境.

RifeWang <notifications@github.com> 于2020年7月10日周五 下午4:48写道：

**Comment by star7th** [comment]
还有就是, docker其实只是在这里充当一个运行环境. 可以不用重新构建 . 只要重新构建代码就行. 这里的代码指的是挂载的物理目录代码.

**Comment by RifeWang** [comment]
感谢
