### ISSUE TITLE
RunApi请求前和请求后执行脚本功能

### ISSUE THREAD

**Issue by zwd297040206** [star7th/showdoc#1004]
希望runapi可以在发送请求前和发送请求后能执行jq脚本 
接口的返回结果可以在请求后的脚本里保存数据到变量集合中
然后在下个接口直接可以使用变量
之前用过一款工具叫做APIpost
但是apipost无法本地化部署

**Comment by star7th** [comment]
说实话我觉得请求前和请求后执行脚本功能有点不友好 , 需要用户了解清楚语法才懂得使用.  但我目前似乎没有想到太方便的方式. 此功能暂时考虑中吧. 挂在这个看看有这个需求的人多不.

**Comment by zwd297040206** [comment]
主要是可以做成那种按照设定依次执行指定接口,做成开发可用的自动化冒烟测试
至于脚本的话直接使用jq脚本,上手简单

**Comment by star7th** [comment]
已增加执行前后脚本功能。可部分实现环境变量的自动赋值动作。并且可以将多个接口的后执行脚本串起来做流程测试。
重启runapi可自动更新。但showdoc服务端需要自行升级到最新版。

**Comment by test11qq** [comment]
在前执行脚本中获取body中json格式参数

   var queryParams =runapi.getAllParam();
   var appkey=runapi.getParam("appkey") ;
取不到对应的参数值

**Comment by star7th** [comment]
> 在前执行脚本中获取body中json格式参数
> 
> var queryParams =runapi.getAllParam(); var appkey=runapi.getParam("appkey") ; 取不到对应的参数值

文档里是这样的：

runapi.getParamJson() // 获取请求参数为json的json对象
runapi.setParamJson(json) //设置请求参数为json的json对象

**Comment by test11qq** [comment]
var parmJson=runapi.getParamJson();
runapi.alert("==parmJson==="+parmJson+"==appkey=="+parmJson.appkey);  这样的也取不到

**Comment by test11qq** [comment]
需要将body里面的json字符串全部取出来，然后参与签名。

**Comment by star7th** [comment]
> var parmJson=runapi.getParamJson(); runapi.alert("==parmJson==="+parmJson+"==appkey=="+parmJson.appkey); 这样的也取不到

parmJson是一个对象啊，为啥直接拼接进字符串。
runapi.alert(parmJson)  这样打印

**Comment by test11qq** [comment]
打印出来就一对尖括号 没有对应的body里面的值。 是我们body里面的值有问题吗？
{
  "xx":"xx1",
   "xx2":"xx2"
}

**Comment by star7th** [comment]
> 打印出来就一对尖括号 没有对应的body里面的值。 是我们body里面的值有问题吗？ { "xx":"xx1", "xx2":"xx2" }

大概率是。 请另开问题，把问题描述清楚，最好提供一个可重现例子我看看。
