### ISSUE TITLE
runapi返回友好阅读格式(json|html)问题建议

### ISSUE THREAD

**Issue by moobing** [star7th/showdoc#1006]
友好阅读格式建议：目前调试接口返回的json数据都是纯黑色，一旦数据多起来无法分辨，后续版本可以加上颜色区分吗？另外html友好阅读希望也支持一下（优先json）

**Comment by star7th** [comment]
这个考虑吧。如果要用颜色区分的话就不能用纯文本框了。可能需要用代码高亮插件。

gamedevil <notifications@github.com> 于2020年7月10日周五 下午9:24写道：

**Comment by moobing** [comment]
@star7th 是这样的，前端开发者想要根据颜色快速判断是number类型还是string类型，以及某些重复数组占用过长时，可以收缩起来，不影响他查看下面的字段数据
![image](https://user-images.githubusercontent.com/31676598/87161681-742c6a80-c2f7-11ea-89a7-d9dc82d506b9.png)

**Comment by wangyifani** [comment]
如果增加此功能，那就基本可以取替postman使用了

**Comment by star7th** [comment]
已更新。当返回内容是json的时候，将高亮颜色美化并且带有折叠功能。
![image](https://user-images.githubusercontent.com/2200494/97401035-131eb600-192b-11eb-8f2f-c69cdbefa1ef.png)
