### ISSUE TITLE
如何自定义或者修改文件的存储位置

### ISSUE THREAD

**Issue by shanyingzhe** [star7th/showdoc#1007]
作者你好，我目前在centos系统上执行自动安装，但是需要指定数据的存储位置请问如何操作

**Comment by star7th** [comment]
暂不支持自定义位置

shanyingzhe <notifications@github.com> 于2020年7月13日周一 上午11:34写道：

**Comment by star7th** [comment]
如果你懂docker , 要自己手动定义可以自行手动安装然后修改需要的参数
https://www.showdoc.cc/help?page_id=65610 如果你是小白用户则不建议操作.

Chen Xing <xing7th@gmail.com> 于2020年7月13日周一 上午11:40写道：
