### ISSUE TITLE
分享页面有密码的访问不了

### ISSUE THREAD

**Issue by imysm** [star7th/showdoc#1008]
昨天升级了下showdoc ，然后发现 分享的连接 输入密码 后页面刷新下 ，就又到了输入密码的界面 。
但是如果是登录状态就不用输密码 
这个需要打补丁么？

**Comment by star7th** [comment]
看了下，是几天前引入的bug 。现在修复了。 再更新下。

**Comment by imysm** [comment]
还是用 showdoc  update 来更新是么

**Comment by star7th** [comment]
是的

samyang <notifications@github.com> 于2020年7月16日周四 上午10:44写道：

**Comment by imysm** [comment]
可以了 ，谢谢 star7th
