### ISSUE TITLE
更换服务器之后所有附件的下载链接都变成同一个文件

### ISSUE THREAD

**Issue by cindygl** [star7th/showdoc#1009]
在server A上用Docker安装方式部署了showdoc，创建了项目新建了文档，并且文档里面上传了附件。

做以下操作：

在serverB上用同样的Docker安装方式部署了一套showdoc，拷贝serverA上的Sqlite/showdoc.db.php，以及Public/Uploads/下的所有文件到ServerB的对应路径下，并且修改了这些文件的属主和权限。
使用浏览器访问serverB的showdoc，进去后所有文档里面的下载链接，全部都指向了一个相同的文件。

![image](https://user-images.githubusercontent.com/13764902/87641248-686af900-c77a-11ea-8deb-6e0db72186b5.png)

请协助指导解决。

**Comment by star7th** [comment]
有根据这个 https://github.com/star7th/showdoc/issues/102 来改过吗。 如果再不行，请提供外网可访问链接。

**Comment by cindygl** [comment]
改过了，图片的链接都正常了，就附件不对。
部署在内网服务器的，外网访问不到额。

**Comment by star7th** [comment]
我刚刚更新多了一条评论  . 这是由于后来的数据库有变动。 
![image](https://user-images.githubusercontent.com/2200494/87642469-26db4d80-c77c-11ea-95f0-f2b3ca2a5931.png)

**Comment by cindygl** [comment]
多谢，upload_file里面的real_url也改了，数据库看着附件标题名称和文件名称对应关系是对的
![image](https://user-images.githubusercontent.com/13764902/87645351-eed60980-c77f-11ea-911b-b3e38c990794.png)

可是通过浏览器去点，它还是一样：
迁移过来的所有数据，附件都指向同一个文件
但是新上传的，都是对的。

**Comment by star7th** [comment]
对于旧版迁移，我重现不了。我这边只能保证新上传功能的没问题。

cindy <notifications@github.com> 于2020年7月16日周四 下午4:20写道：

**Comment by cindygl** [comment]
好的，感谢star7th，我再看下。

**Comment by cindygl** [comment]
@star7th 网页请求附件的时候看到附件的url有区别，这个地方方便提醒下是可以检查哪里
![image](https://user-images.githubusercontent.com/13764902/87653532-3a8cb100-c788-11ea-8e28-7ff482a8fe05.png)

谢谢！

**Comment by star7th** [comment]
这个url是不对的。可以登录sqlite数据库看看表内容

cindy <notifications@github.com> 于2020年7月16日周四 下午5:21写道：

**Comment by cindygl** [comment]
![image](https://user-images.githubusercontent.com/13764902/87657556-8ee65f80-c78d-11ea-9dfa-f008a65dfffd.png)

对比了upload_file表，除了update过real_url，没有其他不一样，困扰中

**Comment by star7th** [comment]
突然间明白了这个是个兼容问题。历史的附件机制和现在的不一样。我已经更新代码，你更新最新mater版本代码

cindy <notifications@github.com> 于2020年7月16日周四 下午5:58写道：

**Comment by cindygl** [comment]
使用最新master版本代码，安装步骤是？也是自动化脚本安装吗？多谢！

**Comment by star7th** [comment]
如果是用脚本的直接用脚本安装或者升级就行。

cindy <notifications@github.com>于2020年7月17日 周五上午10:02写道：

**Comment by cindygl** [comment]
可以了，非常感谢@start7th~
