### ISSUE TITLE
版本升级数据库字段出错，100%必现

### ISSUE THREAD

**Issue by tomWuDT** [star7th/showdoc#101]
:(
SQLSTATE[HY000]: General error: 1 no such column: member_group_id
错误位置
FILE: /var/www/html/showdoc/ThinkPHP/Library/Think/Db/Driver.class.php 　LINE: 156
TRACE
#0 /var/www/html/showdoc/ThinkPHP/Library/Think/Db/Driver.class.php(156): PDO->prepare('SELECT * FROM i...')
#1 /var/www/html/showdoc/ThinkPHP/Library/Think/Db/Driver.class.php(946): Think\Db\Driver->query('SELECT * FROM i...', false)
#2 /var/www/html/showdoc/ThinkPHP/Library/Think/Model.class.php(759): Think\Db\Driver->select(Array)
#3 /var/www/html/showdoc/Application/Home/Controller/BaseController.class.php(69): Think\Model->find()
#4 /var/www/html/showdoc/Application/Home/Controller/ItemController.class.php(205): Home\Controller\BaseController->checkItemPermn('3', '15')
#5 /var/www/html/showdoc/Application/Home/Controller/ItemController.class.php(155): Home\Controller\ItemController->_show_regular_item(Array)
#6 [internal function]: Home\Controller\ItemController->show()
#7 /var/www/html/showdoc/ThinkPHP/Library/Think/App.class.php(173): ReflectionMethod->invoke(Object(Home\Controller\ItemController))
#8 /var/www/html/showdoc/ThinkPHP/Library/Think/App.class.php(110): Think\App::invokeAction(Object(Home\Controller\ItemController), 'show')
#9 /var/www/html/showdoc/ThinkPHP/Library/Think/App.class.php(204): Think\App::exec()
#10 /var/www/html/showdoc/ThinkPHP/Library/Think/Think.class.php(120): Think\App::run()
#11 /var/www/html/showdoc/ThinkPHP/ThinkPHP.php(97): Think\Think::start()
#12 /var/www/html/showdoc/index.php(24): require('/var/www/html/s...')
#13 {main}
ThinkPHP3.2.3 { Fast & Simple OOP PHP Framework } -- [ WE CAN DO IT JUST THINK ]

**Comment by tomWuDT** [comment]
补充下，当项目的创建者把我拉到项目中，然后我点开这个项目的链接，就会出现上面的报错。
另外有一点是，这次给showdoc做了个升级安装，数据大概是2016年底的版本上的，现在拷贝到了2017/02/07的版本上。

**Comment by star7th** [comment]
大概是你升级的时候没有执行http://xxx.com/showdoc/index.php?s=/home/update/db

**Comment by tomWuDT** [comment]
是的，这个问题我已经关掉了。 谢谢。麻烦看下最新的那个问题，服务器修改后图片地址没更改过来。

-- Tom

发件人: star7th <notifications@github.com<mailto:notifications@github.com>>
答复: star7th/showdoc <reply@reply.github.com<mailto:reply@reply.github.com>>
日期: 2017年2月8日 星期三 上午10:09
至: star7th/showdoc <showdoc@noreply.github.com<mailto:showdoc@noreply.github.com>>
抄送: Tom Wu <tome.wu@dingtone.me<mailto:tome.wu@dingtone.me>>, State change <state_change@noreply.github.com<mailto:state_change@noreply.github.com>>
主题: Re: [star7th/showdoc] 版本升级数据库字段出错，100%必现 (#101)


大概是你升级的时候没有执行http://xxx.com/showdoc/index.php?s=/home/update/db
