### ISSUE TITLE
希望增加一个忽略文件夹的功能

### ISSUE THREAD

**Issue by shiyuanjieyi** [star7th/showdoc#1010]

**Comment by star7th** [comment]
详情说下使用场景？

ZhangXin <notifications@github.com> 于2020年7月16日周四 下午5:58写道：

**Comment by shiyuanjieyi** [comment]
目前我项目里面存在node_modules文件夹，如下：
![image](https://user-images.githubusercontent.com/29232912/88021008-4baa3900-cb5f-11ea-931c-18a594e0f508.png)
每次使用都会花很长时间遍历这个文件夹，
但是要生成文档的文件跟它是同级的，所以没办法通过文件夹的方式指定遍历目标，必须添加忽略文件夹才可以

**Comment by star7th** [comment]
或许你新建一个目录叫src ，然后把那个index.js放进去？

ZhangXin <notifications@github.com> 于2020年7月21日周二 下午2:37写道：

**Comment by shiyuanjieyi** [comment]
这样的话就很麻烦了。本身项目我不需要src文件夹的，每次更新文档都需要重新放在一个文件夹里面再去遍历实在有点不人性化，如果您不考虑出一个，我自己试着改改你的sh文件吧
