### ISSUE TITLE
希望参数前面增加多选选择（选中才发送该字段），因为有些字段不能传，有的字段要传，目前测试要删除字段，然后又得加回来，不太方便

### ISSUE THREAD

**Issue by moobing** [star7th/showdoc#1011]

**Comment by star7th** [comment]
考虑到这种需求极少，可能不被支持？
我建议你这样的情况可以新建两个接口，虽然url一样但传递的参数不一样。

gamedevil <notifications@github.com>于2020年7月16日 周四下午7:03写道：

**Comment by moobing** [comment]
这种需求不少吧？很多第三方接口都有非必传字段的，何况自己开发的。。。大部分时候就是想测试一下去掉勾选某字段会发生什么问题，也好测试某些必要字段未传服务器会发生什么响应，是否响应正确等等，这些测试都是临时性的，为此创建两个接口似乎不符合使用场景？

**Comment by moobing** [comment]
另外的解决方案就是不生成接口文档，因为仅仅是开发人员临时测试创建的接口，可以考虑提供勾选不生成接口文档的功能，仅仅保存到接口目录下（因为关闭软件后，未保存的接口无法在下次打开软件时自动恢复，也不想保存，因为保存会生成接口文档，postman是可以恢复未保存的接口的）

**Comment by star7th** [comment]
这种情况下，不生文档比不生成字段的功能设计更好一些。但是由于一开始的数据存储结构没考虑这方面，所以如果要改的话改动还蛮大。先看看其他人有没有这方面的需求吧。多人需要的话就改，没什么人需要的话不改。

gamedevil <notifications@github.com>于2020年7月17日 周五上午12:44写道：

**Comment by wangyifani** [comment]
这种需求应该属于刚需范围内

**Comment by star7th** [comment]
已在新版支持此功能。用户可以取消参数前面的框勾选来禁用。重启runapi便会自动更新完毕。
