### ISSUE TITLE
关于新注册用户建立项目的问题

### ISSUE THREAD

**Issue by diao2008** [star7th/showdoc#1012]
我的需求是新注册用户是否可以禁止建立项目或者用户的默认添加项目权限为0，以达到禁止添加项目的目的。

我的使用场景是建立一个私有平台，对指定的用户开放账号及私有项目，让用户可以阅读相关资料。如果他们可以新建项目，会让平台资源浪费。

**Comment by star7th** [comment]
showdoc比较关注团队协作，可能不会针对你的特殊需求进行改造。
权限项目都是隔离的，建议你不要在乎那点资源的浪费。或者干脆不让他们登录注册。

diao2008 <notifications@github.com>于2020年7月17日 周五上午1:45写道：
