### ISSUE TITLE
RunApi请求接口返回数据功能增强建议

### ISSUE THREAD

**Issue by gx0803** [star7th/showdoc#1013]
有一些接口，不仅仅responseBody有数据，responseHeader也有数据，比如常见的jwt登录，token是放在header中返回。希望runapi响应数据展示能增加header的返回值

**Comment by star7th** [comment]
后面规划下这方面

gx0803 <notifications@github.com>于2020年7月17日 周五上午8:37写道：

**Comment by star7th** [comment]
已增加响应头显示。重启runapi即可。
