### ISSUE TITLE
特性建议-增加api文档状态标记功能

### ISSUE THREAD

**Issue by lh83mail** [star7th/showdoc#1015]
为每个API文档提供状态标记功能(例如编写中，已发布， 文档更新，优先级等等),  在团队协作中会更实用。

**Comment by star7th** [comment]
后面会优化下这方面。当前建议你先在接口标题和描述处说明

lh83mail <notifications@github.com> 于2020年7月17日周五 上午11:26写道：

**Comment by star7th** [comment]
想了下，建议在接口标题和描述处说明。就不额外增加功能了。
