### ISSUE TITLE
no such table: file_flow

### ISSUE THREAD

**Issue by Lession711** [star7th/showdoc#1017]
Hi

我使用的docker版本, 从`2.8.2`升级到`2.8.5`后, 进入 `我的附件`, 弹出错误

```json
{
  "error_code": 999,
  "error_message": "SQLSTATE[HY000]: General error: 1 no such table: file_flow \u3002\u9519\u8bef\u4f4d\u7f6e\uff1a\/var\/www\/html\/server\/ThinkPHP\/Library\/Think\/Db\/Driver.class.php  156"
}
```

这像是没有`file_flow`这个表, 要怎么处理呢? 请帮忙看一下, 谢谢.

> docker 运行命令:
```bash
docker run -d \
        --name showdoc \
        -p 4999:80/tcp \
        --restart always \
        -v /data/docker/showdoc/Uploads:/var/www/html/Public/Uploads \
        -v /data/docker/showdoc/Sqlite:/var/www/html/Sqlite \
        star7th/showdoc:v2.8.5
```

**Comment by star7th** [comment]
文件有可写权限了吗。尝试新建一个页面来保存下。能保存成功才是有写权限。

Lession.Z.Li <notifications@github.com>于2020年7月20日 周一下午2:34写道：

**Comment by Lession711** [comment]
> 文件有可写权限了吗。尝试新建一个页面来保存下。能保存成功才是有写权限。

![image](https://user-images.githubusercontent.com/4253811/87907557-716c0b00-ca97-11ea-8934-ba01492f7812.png)


如上图, 我仅将`Sqlite`和`Uploads`两个文件夹配置到宿主机的目录上, 权限都挺大的呀

**Comment by star7th** [comment]
尝试新建一个页面，然后再保存看是否成功。

Lession.Z.Li <notifications@github.com>于2020年7月20日 周一下午2:46写道：

**Comment by Lession711** [comment]
我尝试新建一个文档, 并上传一张图片, 获得

> `![](http://127.0.0.1:4999/server/index.php?s=/api/attachment/visitFile/sign/c07f68174c4eab9f07fec8eb907b7c8d&showdoc=.jpg)`
>> 这个路径的问题啥时候能解决啊?
>
> 去除掉`http://127.0.0.1:4999`, 使得该url能正常访问

保存成功后

再次打开此新建文档页面, 图片无法展示, 浏览器F12,在Network里找到/server/index.php这个地址, 新窗口打开后,

```json
{
"error_code": 999,
"error_message": "SQLSTATE[HY000]: General error: 1 no such table: file_flow \u3002\u9519\u8bef\u4f4d\u7f6e\uff1a\/var\/www\/html\/server\/ThinkPHP\/Library\/Think\/Db\/Driver.class.php  156"
}
```

**Comment by star7th** [comment]
清空浏览器缓存后重登录看下。

Lession.Z.Li <notifications@github.com> 于2020年7月20日周一 下午2:58写道：

**Comment by star7th** [comment]
路径的问题看这个  https://github.com/star7th/showdoc/issues/573

Chen Xing <xing7th@gmail.com> 于2020年7月20日周一 下午3:26写道：

**Comment by Lession711** [comment]
操作步骤:

1. 清空浏览器缓存
2. 进入首页
3. 弹出语言选择页面, 选择后点击[确定]
4. 点击右上角登录, 输入账号密码
5. 进入[我的附件], `依然报错`
6. 重新添加新文档, 并上传图片(随便截图一张, 粘贴进编辑器的方式)
7. 保存后, 图片依然无法查看, 报和之前一样的错误

> ps: 点击`管理后台`-> `附件管理`, 可以看到新上传的图片, 但点击后依然报这个错误

**Comment by star7th** [comment]
我看了下你的docker命令， 你不是按照官方教程来做的。 官方教程在这里
https://www.showdoc.cc/help?page_id=65610
 你自己自定义操作的话，需要自己花时间去兼容官方。我暂时不花时间帮你找bug了，有点消耗时间。如果你想证明是官方的bug还是自身操作问题，只要根据官方教程来操作一遍就知道了。

Lession.Z.Li <notifications@github.com> 于2020年7月20日周一 下午3:39写道：

**Comment by Lession711** [comment]
花了点时间,经过以下尝试:

### 使用官方docker命令全新部署

```bash
docker run -d \
    --name showdoc2 \
    -p 4999:80/tcp \
    --restart always \
    /data/docker/showdoc/html:/var/www/html/ \
    star7th/showdoc:v2.8.5
```

结果: 
* 一切运行正常
* 检查showdoc.db.php文件, 包含`file_flow`表

### 使用官方docker命令,并使用老`showdoc.db.php`数据库
> * 删除之前的showdoc container后
> * 删除`/data/docker/showdoc`目录下的全部文件

```bash
docker run -d \
    --name showdoc2 \
    -p 4999:80/tcp \
    --restart always \
    /data/docker/showdoc/html:/var/www/html/ \
    star7th/showdoc:v2.8.5

docker stop showdoc2
```

* 将`v2.8.2`版本的`showdoc.db.php`放入`/data/docker/showdoc/html/Sqlite`文件夹内
* `docker start showdoc2` 重新将container跑起来
* 访问网站, 并进入`/install/index.php`页面
* 点[OK]后完成初始化
* **访问[我的附件]依然会报`no such table: file_flow`错误**
* **再将`showdoc.db.php`文件从服务器上scp下来后, 数据库中依然没有`file_flow`表

麻烦看一下这是什么原因? 谢谢

**Comment by star7th** [comment]
你这样倒提醒我了，这确实是官方的bug 。 是升级脚本漏更新了，导致程序不能自动升级数据库。我现在已经修正，你再更新下代码后试试。如此看来应该和你原来的docker安装方式无关。

**Comment by star7th** [comment]
如果是全新安装的话是可以正常使用的。但对于近期升级的版本，我引入了新的数据库升级机制。用数字来记录当前数据库版本来判断是否要更新数据库接口。上面的问题是由于我忘记更新版本数字，导致程序没有去更新数据库结构。所以解决方法是我改一下版本数字就好。

**Comment by Lession711** [comment]
好的, 我尝试一下v2.8.6, 感谢帮忙~
