### ISSUE TITLE
竖线怎么打 ：|  

### ISSUE THREAD

**Issue by 1205747671** [star7th/showdoc#1018]
请求参数中需要加一个 “|” ，但是渲染出来的表格就错位了

**Comment by star7th** [comment]
不支持在表格中输入这个字符

1205747671 <notifications@github.com> 于2020年7月20日周一 下午3:54写道：

**Comment by star7th** [comment]
这种特殊参数，就不在表格中说明了吧。另起一行专门说明

Chen Xing <xing7th@gmail.com> 于2020年7月20日周一 下午3:55写道：

**Comment by Lession711** [comment]
其实我不知道为什么会这样, 因为标准的md是支持在表格中配置`|`的

比如就github的issue回复

| 标题 | 条件 |
| ---- | ----- |
| 我是标题 | `status == 1` &#124;&#124; `status == 2` |

使用`&#124;`便可表示`|`字符   //`124`为`|`的`ascII码`

但这在showdoc行不通

所以我的做法是:

> ps: 由于表格中无法出现`|`字符, 所以使用`/`代替

| 标题 | 条件 |
| ---- | ----- |
| 我是标题 | `status == 1` // `status == 2` |

被逼的没办法....

当然, 如果写标准的`<table></table>`标签应该可以直接解决这个问题, 但...太麻烦

**Comment by star7th** [comment]
跟保存到后台的安全转义有关。不打算支持这个。

Lession.Z.Li <notifications@github.com> 于2020年7月21日周二 上午10:14写道：

**Comment by star7th** [comment]
已发布新版。使用转义字符 `&#124; `  即可
