### ISSUE TITLE
 header我试了不支持变量,是不支持吗?

### ISSUE THREAD

**Issue by gclsoft** [star7th/showdoc#1019]
![image](https://user-images.githubusercontent.com/1269898/87918097-84d3a200-caa8-11ea-9475-3e57fceb8de7.png)
![image](https://user-images.githubusercontent.com/1269898/87918106-87ce9280-caa8-11ea-82b5-61211c473988.png)

 header我试了不支持变量,是不支持吗?

**Comment by star7th** [comment]
引入变量的语法是{{ }} ，我从截图里没看到你哪里输入了这个语法

uuyimei <notifications@github.com> 于2020年7月20日周一 下午4:46写道：

**Comment by gclsoft** [comment]
![image](https://user-images.githubusercontent.com/1269898/87918594-3b378700-caa9-11ea-9b8c-cc9377344150.png)
![image](https://user-images.githubusercontent.com/1269898/87918614-425e9500-caa9-11ea-8b0d-a9ad57675aab.png)
 不起作用的

**Comment by gclsoft** [comment]
有字数限制吗? 
我的文本是:
bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X3R5cGUiOjMsInVzZXJfbmFtZSI6ImFkbWluMiIsInJlYWxfbmFtZSI6IjEiLCJhdmF0YXIiOiIiLCJhcmVhX2lkIjoxMDE3MjgsImF1dGhvcml0aWVzIjpbIueJh-WMuuinkuiJsiJdLCJjbGllbnRfaWQiOiJzd29yZCIsInJvbGVfbmFtZSI6IueJh-WMuuinkuiJsiIsInBvc3RfaWQiOiIxMjcwMjU1NTIwNDc2ODU2MzIxIiwidXNlcl9pZCI6IjEyNzAyNTc2MTEzNDU3NzI1NDUiLCJyb2xlX2lkIjoiMTI3MDI2NjM4Mjg2NDQyOTA1NyIsImdyb3VwX2lkIjoxMDE3MjgsIm9yZ19pZCI6LTEsInNjb3BlIjpbImFsbCJdLCJuaWNrX25hbWUiOiIiLCJleHAiOjE1OTYyMzMxOTIsImRlcHRfaWQiOiIxMjcwMjU1NDcwNzg2OTM2ODMzIiwianRpIjoiM2E3OWM2YzAtOWQ1Yi00MjNhLWI2M2ItMTc5MGRlYTJjZjNiIiwiYWNjb3VudCI6ImFkbWluMiJ9.kGhyIaEMhk6vJzSlpseK1NGKqyfDVlHMuv16R-9ol4U

但是获取的少了后面的部分字

**Comment by star7th** [comment]
经测试，能完整传递你写的这个字符串。请自己确保自己用法正确。

uuyimei <notifications@github.com> 于2020年7月20日周一 下午4:55写道：

**Comment by star7th** [comment]
我突然明发现是变量保存的时候就截断了，果然不支持那么长的字符呢。我看下怎么处理

Chen Xing <xing7th@gmail.com> 于2020年7月20日周一 下午4:57写道：

**Comment by star7th** [comment]
我改了，使用http://www.showdoc.cc/ 作为服务端应该是没问题了，数据库存储字段预留宽度不够。
另外开源showdoc使用sqlite应该不存在此问题的。

**Comment by gclsoft** [comment]
3q
