### ISSUE TITLE
更换服务器后之前界面的图片地址没改过来

### ISSUE THREAD

**Issue by tomWuDT** [star7th/showdoc#102]
比如以前在server A上部署了showdoc，然后创建了个界面，这上面有上传图片。

做以下操作：
1. 更换服务器到serverB上重新部署一套showdoc，然后把serverA上的数据都拷贝过来；
2. 在serverB上访问之前那个界面，会发现图片地址还是serverA上的。

请解决。

**Comment by star7th** [comment]
当时考虑到导出word后图片依然可用，所以使用了绝对地址。
如果你迁移了地址，建议自行写个小脚本把图片url批量更改。

其实我更建议图片存储到七牛或者其他云储存，这样就可以使用绝对地址了

**Comment by star7th** [comment]
配置文件那里可以配置七牛key

**Comment by tomWuDT** [comment]
针对迁移地址后，图片url批量更改的脚本。因为现在我对showdoc实现才刚刚接触，是否可以请帮忙实现个？ 这样放到git里，相信用途还是挺大的。

-- Tom

发件人: star7th <notifications@github.com<mailto:notifications@github.com>>
答复: star7th/showdoc <reply@reply.github.com<mailto:reply@reply.github.com>>
日期: 2017年2月8日 星期三 上午10:11
至: star7th/showdoc <showdoc@noreply.github.com<mailto:showdoc@noreply.github.com>>
抄送: Tom Wu <tome.wu@dingtone.me<mailto:tome.wu@dingtone.me>>, Author <author@noreply.github.com<mailto:author@noreply.github.com>>
主题: Re: [star7th/showdoc] 更换服务器后之前界面的图片地址没改过来 (#102)


当时考虑到导出word后图片依然可用，所以使用了绝对地址。
如果你迁移了地址，建议自行写个小脚本把图片url批量更改。

其实我更建议图片存储到七牛或者其他云储存，这样就可以使用绝对地址了

**Comment by star7th** [comment]
嗯，先记下来，我有空再写

**Comment by star7th** [comment]
如果你急用的话我可以告诉你思路让你去做。

主要是把page表的图片url的前面那部分字符串替换为新地址。
去搜索sqlite 替换字符串相关教程。

**Comment by tomWuDT** [comment]
登陆服务器使用sqlite命令行解决了。
比如把老的图片链接地址前缀“http://120.26.114.163:8000/doc”改为“http://10.88.0.35/showdoc“，方法如下：
[root@blog ~]# cd /var/www/html
[root@blog html]# cd showdoc
[root@blog showdoc]# cd Sqlite/
[root@blog Sqlite]# ls
showdoc.db.php
[root@blog Sqlite]# sqlite3 showdoc.db.php 
//查询当前需要替换的记录
sqlite> select page_id FROM page WHERE "page_content" LIKE  '%http://120.26.114.163:8000/doc%';

//如果有就直接替换
sqlite> update page set page_content=replace(page_content,'http://120.26.114.163:8000/doc','http://10.88.0.35/showdoc') WHERE "page_content" LIKE  '%http://120.26.114.163:8000/doc%';

**Comment by RobinsChens** [comment]
sqlite command not found , 我用docker的。。。

**Comment by sunny0826** [comment]
@RobinsChens `apk add sqlite` 装一下可以，但是好像新版表结构变了

**Comment by star7th** [comment]
留下一条评论方便后来者查阅。
现在更换服务器后，不仅page 表要replace ， upload_file表的real_url字段也需要
