### ISSUE TITLE
迁移数据的命令有问题

### ISSUE THREAD

**Issue by zhangshantest** [star7th/showdoc#1021]
升级的帮助文档有问题：
https://www.showdoc.cc/help?page_id=65610 这个页面的转移旧数据的命令有问题：
#转移旧附件数据
\cp -r -f /showdoc_data/html_bak/Public/Uploads  /showdoc_data/html/Public/Uploads
转移数据的命令应该改为
\cp -r -f /showdoc_data/html_bak/Public/Uploads/.  /showdoc_data/html/Public/Uploads

否则会出现，/showdoc_data/html/Public/Uploads/Uploads/

**Comment by star7th** [comment]
已修改
