### ISSUE TITLE
保存数据失败

### ISSUE THREAD

**Issue by weiyf16** [star7th/showdoc#1024]
复制已写好的文档 改变文件夹后 重新命名 书写内容 保存保 request fail

**Comment by weiyf16** [comment]
补充 虽然报request fail  但是文件已经保存在文件夹下 希望修复这个bug

**Comment by star7th** [comment]
你再试下，现在应该好了。今天特殊情况，应该短暂故障了下，恢复了大量并发进来导致主从数据库延迟比较厉害。

**Comment by weiyf16** [comment]
谢谢
