### ISSUE TITLE
创建数据字典--最后一行最后一列的单元格的边框显示不出

### ISSUE THREAD

**Issue by weiyf16** [star7th/showdoc#1026]
在利用数据字典模板，创建自己的数据字典 发现 最后一行最后一列的单元格必须添加内容后 边框可以显示 否则 边框消失 影像美观 希望可以修复这个bug 谢谢

**Comment by star7th** [comment]
你在最后增加个点号吧

weiyf16 <notifications@github.com> 于2020年7月22日周三 下午2:35写道：

**Comment by star7th** [comment]
这是已经知道的bug，但一直没怎么处理

Chen Xing <xing7th@gmail.com> 于2020年7月22日周三 下午2:57写道：

**Comment by weiyf16** [comment]
好的 谢谢
