### ISSUE TITLE
服务器挂了？

### ISSUE THREAD

**Issue by fucshitk** [star7th/showdoc#1027]
一天了，还没解决吗

**Comment by star7th** [comment]
早恢复了。你不能访问吗

xgf <notifications@github.com> 于2020年7月22日周三 下午3:59写道：

**Comment by fucshitk** [comment]
还是不行，访问就是空白

**Comment by star7th** [comment]
看下网络返回什么内容，另外提供下你访问的地址

xgf <notifications@github.com> 于2020年7月22日周三 下午4:03写道：

**Comment by fucshitk** [comment]
https://www.showdoc.cc/   200 但是页面就是空白， response是： 
`<!DOCTYPE html><html><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><meta name=renderer content=webkit><meta http-equiv=X-UA-Compatible content=edge><meta name=referrer content=no-referrer><title>ShowDoc</title><meta name=keywords content="在线API文档 技术文档 数据字典 在线手册"><meta name=description content=一个非常适合IT团队的在线API文档、技术文档工具。你可以使用Showdoc来编写在线API文档、技术文档、数据字典、在线手册><script type=text/javascript>//挂在window下的全局配置
    window.DocConfig = {
      //"server":'http://127.0.0.1/showdoc.cc/server/index.php?s=',
      "server": window.location.protocol +'//'+ window.location.host + '/server/index.php?s=',
      //"lang" :'en'
      "lang" :'zh-cn'
  }</script><script src=//cdn.staticfile.org/vue/2.6.10/vue.min.js></script><script src=//cdn.staticfile.org/element-ui/2.13.0/index.js></script><link href=//cdn.staticfile.org/element-ui/2.13.0/theme-chalk/index.css rel=stylesheet><script>!window.Vue && document.write(unescape('%3Cscript src="/static/vue/vue.min.js"%3E%3C/script%3E'))</script><script>!window.ELEMENT && document.write(unescape('%3Clink href="/static/element-ui/theme-chalk/index.css" rel="stylesheet"%3E%3C/link%3E'))</script><script>!window.ELEMENT && document.write(unescape('%3Cscript src="/static/element-ui/index.js"%3E%3C/script%3E'))</script><link href=/static/css/app.9348cebeaed832a7f092c5c8fdff8e87.css rel=stylesheet></head><body class=grey-bg><div id=app></div><script type=text/javascript src=/static/js/manifest.2ae2e69a05c33dfc65f8.js></script><script type=text/javascript src=/static/js/vendor.3b866d3c54d20c92cb2f.js></script><script type=text/javascript src=/static/js/app.4073d3046ab269acb38e.js></script></body></html><script language=JavaScript>var Wwidth = window.innerWidth ;
  window.addEventListener('resize', function() {
    ///宽度变化大于50像素的时候刷新整个窗口以适应新宽度
    if ( Math.abs(Wwidth - window.innerWidth) > 50 ) {
        //console.log(window.innerWidth + ' ' + window.innerHeight);
        //如果不在编辑页面，则在窗口变化后刷新窗口以适应宽度
        if(window.location.href.indexOf("/edit") === -1){
          window.location.reload();
        }

        
    };

  });


  //站长统计统计代码
  var _hmt = _hmt || [];
  setTimeout(function(){
      (function() {
          var hm = document.createElement("script");
          hm.src = "//s4.cnzz.com/stat.php?id=1259614235&web_id=1259614235";
          var s = document.getElementsByTagName("script")[0];
          s.parentNode.insertBefore(hm, s);
      })();

      //百度统计
    (function() {
      var hm = document.createElement("script");
      hm.src = "https://hm.baidu.com/hm.js?c3e57b51caf65f1513b108d7ddb97e6b";
      var s = document.getElementsByTagName("script")[0]; 
      s.parentNode.insertBefore(hm, s);
    })();


  },5000);</script>`

**Comment by star7th** [comment]
这不就是正常的响应吗。你用什么浏览器

xgf <notifications@github.com> 于2020年7月22日周三 下午4:09写道：

**Comment by star7th** [comment]
用谷歌火狐试下

Chen Xing <xing7th@gmail.com> 于2020年7月22日周三 下午4:10写道：

**Comment by fucshitk** [comment]
chrome

**Comment by fucshitk** [comment]
[看图片](https://bennet.xpcar.cn/159540557828261667532.png)

**Comment by fucshitk** [comment]
截图 https://bennet.xpcar.cn/159540557828261667532.png

**Comment by fucshitk** [comment]
https://bennet.xpcar.cn/159540571369332744533.png

**Comment by star7th** [comment]
你ping一下这个域名看指向什么ip

**Comment by fucshitk** [comment]
203.107.32.238

**Comment by star7th** [comment]
ip没错。你多刷新几次。可能恢复得还不够稳定。

xgf <notifications@github.com> 于2020年7月22日周三 下午4:18写道：

**Comment by fucshitk** [comment]
我已经刷了好多次了

**Comment by star7th** [comment]
我也不理解你为啥会这样子。我访问挺正常的
![image](https://user-images.githubusercontent.com/2200494/88153097-88496380-cc37-11ea-970f-5a1548b757c8.png)

**Comment by fucshitk** [comment]
为什么经常会挂啊，服务器压力太大了吗，还是cloudflare挂了的原因

**Comment by star7th** [comment]
早点时候受到网络攻击。然后就各种防护吧。现在至少最近一个小时内没有其他人跟我反应过访问不了。而我自己测试也正常。我不知道你为什么还访问不了

xgf <notifications@github.com> 于2020年7月22日周三 下午4:25写道：

**Comment by star7th** [comment]
由于showdoc用户蛮多的，如果大范围访问不了，一个小时内我应该会收到很多反馈

Chen Xing <xing7th@gmail.com> 于2020年7月22日周三 下午4:27写道：

**Comment by fucshitk** [comment]
还是访问不了啊，我们项目文档忘了备份了。完了

**Comment by star7th** [comment]
从你昨天提出这个问题开始，我没有收到过反馈说不能访问。各地ping测试也正常。
而且你是有response的 ，我倾向认为是你的浏览器解析网页的问题。尝试禁用所有浏览器扩展，换个浏览器尝试，换个电脑尝试

**Comment by star7th** [comment]
如果你指定过host ip ，也去掉host设置 。另外也不排除是你的路由器dns缓存到了无效机器上。 如果想知道是不是网络问题，用你的手机4G网络访问下网站就知道正常不正常。我觉得是正常的。

**Comment by fucshitk** [comment]
可以访问了

**Comment by fucshitk** [comment]
谢谢
