### ISSUE TITLE
字符串被转换成emoji了

### ISSUE THREAD

**Issue by xl7dev** [star7th/showdoc#103]
如
    |mac | 9c:d0:07:67:0e:0b| string | |

**Comment by star7th** [comment]
因为开启了表情转义。
如果你需要输入，不妨加个` `，把它变为代码行。这样就不被转义了

**Comment by xl7dev** [comment]
加了试过了还是不行，我是在一个表格里输入这些内容

**Comment by star7th** [comment]
没办法，它确实跟emoji的关键字冲突了。
鉴于你这个字符串只是作为示例给人看的，所以可以不那么严谨地把其中的冒号变为中文冒号，这样就不会转义了。
9c：d0：07：67：0e：0b

**Comment by xl7dev** [comment]
好吧，谢谢了
