### ISSUE TITLE
如何配置showdoc站点的访问根路径？

### ISSUE THREAD

**Issue by zty18494** [star7th/showdoc#1031]
因为公网端口资源有限，希望通过`http://ip:port/my_root_path/`访问私有化部署的 showdoc ，而不是原来的`http://ip:4999/`

请问是否支持配置？或者如何修改可支持？谢谢~

**Comment by star7th** [comment]
需要对showdoc做操作，请安装个nginx，配置端口映射到本机的4999端口。配置nginx转发的时候记得带上代理header等信息，否则上传的图片地址出错。参考这个：https://github.com/star7th/showdoc/issues/573

**Comment by star7th** [comment]
不需要对showdoc做操作，请安装个nginx，配置端口映射到本机的4999端口。配置nginx转发的时候记得带上代理header等信息，否则上传的图片地址出错。参考这个：https://github.com/star7th/showdoc/issues/573

**Comment by zty18494** [comment]
> 不需要对showdoc做操作，请安装个nginx，配置端口映射到本机的4999端口。配置nginx转发的时候记得带上代理header等信息，否则上传的图片地址出错。参考这个：#573

这样的话，只能做到自定义端口的映射，页面发起的请求地址还是`http://ip:port/server/xxx`。
我是希望前端页面地址变成`http://ip:port/my_root_path/my_root_path/web/xxx`，发起接口请求的地址变成`http://ip:port/my_root_path/server/xxx`，其中 `my_root_path` 是我的自定义项目根路径
这样可以做到吗？

**Comment by star7th** [comment]
跟showdoc没有关系的。你自己可以探索下nginx重写规则重定向到端口去。理论上nginx可以改写任意url规则

Elsie.Zhang <notifications@github.com> 于2020年7月24日周五 上午9:50写道：

**Comment by zty18494** [comment]
我找到解决办法了~

1. 修改本地的/web_src/index.html
```
window.DocConfig = {
      //"server":'http://127.0.0.1/showdoc/server/index.php?s=',
      "server": window.location.protocol +'//'+ window.location.host + window.location.pathname+ '../server/index.php?s=',
      //"lang" :'en'
      "lang" :'zh-cn'
  }

把 server 的赋值语句改为：
"server": window.location.protocol +'//'+ window.location.host + window.location.pathname+ '../showdoc/server/index.php?s=',

```

2. 修改本地的/web_src/index.html
```
    window.DocConfig = {
      //"server":'http://127.0.0.1/showdoc/server/index.php?s=',
      "server": window.location.protocol +'//'+ window.location.host + window.location.pathname+ '../server/index.php?s=',
      //"lang" :'en'
      "lang" :'zh-cn'
  }

把 server 的赋值语句改为：
"server": window.location.protocol +'//'+ window.location.host + window.location.pathname+ '../showdoc/server/index.php?s=',
```

3. 修改nginx配置/showdoc/的路由映射
```
    server {
        listen       80;
        location /showdoc/ {
            proxy_pass http://172.xx.xx.xx:4999/;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
        }
    }
```

然后就可以用 `http://www.xxx.com/showdoc/` 访问了~
这样适用于公网端口有限的团队，通过配置路由映射，可以把showdoc放在自己某个站点的子路径下
