### ISSUE TITLE
ldap同步ad域账号错误

### ISSUE THREAD

**Issue by 1141330133** [star7th/showdoc#1033]
![image](https://user-images.githubusercontent.com/58717677/88372724-1012a780-cdc9-11ea-8429-7cf628a5de10.png)
![image](https://user-images.githubusercontent.com/58717677/88372750-1bfe6980-cdc9-11ea-9729-ab848998e1e1.png)
如图做的配置，版本是2.6.7，原本是正常的一共20个左右的账号，同步ad账号以后，多出一堆混乱的账号，变成了100多个，这个该怎么解决

**Comment by star7th** [comment]
如果那20个账户同步过来了的话，那就不用解决。把多余账户删除或者留着它都不会影响使用。

1141330133 <notifications@github.com> 于2020年7月24日周五 下午4:20写道：

**Comment by 1141330133** [comment]
这个ou还好，就11页，还可以手动删除，但是我接下来要同步其他的ou，另外一个ou有几百个正常的账号，那到时候错误账号就可能有几千个，这就不好删除了吧

**Comment by star7th** [comment]
我没办法复现这个环境，所以无法调式。我自身利用开源版openladp搭建的时候是没问题的。你尝试搜索下历史issue看有没有解决问题的灵感。

1141330133 <notifications@github.com> 于2020年7月24日周五 下午4:26写道：
