### ISSUE TITLE
提交一个导出时的bug

### ISSUE THREAD

**Issue by a984751893** [star7th/showdoc#1034]
导出文件为word，如果项目名称带html源码，如 item表字段item_name  中带 &nbsp;   的时候导出报错。
可以在server/Application/Api/Controller/ExportController.class.php 143行调用output_word时进行html编码不转义操作
![image](https://user-images.githubusercontent.com/37542427/88527512-f626ce00-d02f-11ea-9a09-c55de1d6b416.png)

**Comment by star7th** [comment]
很久没动这块的代码了。不建议在项目里包含html标签。

a984751893 <notifications@github.com>于2020年7月27日 周一下午5:40写道：
