### ISSUE TITLE
上传图片后的链接是127的本地链接，可否配置

### ISSUE THREAD

**Issue by Minoyu** [star7th/showdoc#1037]
![image](https://user-images.githubusercontent.com/21097448/88936083-0e5b4f00-d2b5-11ea-9065-0f5d6de7f3bd.png)
如图所示，此地址无法访问，Showdoc使用了nginx做转发，能否设置域名呢

**Comment by star7th** [comment]
https://github.com/star7th/showdoc/issues/573

**Comment by Minoyu** [comment]
thanks！！！！
