### ISSUE TITLE
升级到最新版showdoc了  runapi 客户端无法连接

### ISSUE THREAD

**Issue by anjiacm** [star7th/showdoc#1038]
提示
连接失败，请确保网址正确或者showdoc服务端使用的是新版代码
一直提示这个

**Comment by anjiacm** [comment]
获取验证码的时候

**Comment by star7th** [comment]
截图看下，给出访问链接看下

**Comment by ityj1987** [comment]
<img width="429" alt="image" src="https://github.com/user-attachments/assets/aa153b6b-a71f-49d4-8b0a-91dc2c696e36">

**Comment by ityj1987** [comment]
http://my.showdoc.tyj/server/index.php?s=/api/common/version
{"error_code":0,"data":{"version":"v3.3.0"}}
