### ISSUE TITLE
七牛云存储不生效

### ISSUE THREAD

**Issue by fanbenhu** [star7th/showdoc#1039]
正确配置了七牛云存储，图片也可以正常上传到七牛云，但是图片同时会被上传到本地服务器，文章内的图片链接也是本地服务器的资源链接。

配置成功后，文章内的资源链接是云资源链接。使用另一台电脑上传时发现变成了本地链接，然后在所有的机器上再上传时都保存为本地链接。

**Comment by star7th** [comment]
生成的链接必须经过服务器脚本。有分享需要的，必须把showdoc安装到公用服务器上

fanbenhu <notifications@github.com> 于2020年8月1日周六 下午5:15写道：

**Comment by star7th** [comment]
还有问题的请提供外网可访问地址

Chen Xing <xing7th@gmail.com> 于2020年8月1日周六 下午5:17写道：

**Comment by fanbenhu** [comment]
对不起，给您带来麻烦了，已解决
