### ISSUE TITLE
提个小需求：文件存储到云的功能，是否可以支持AWS S3？

### ISSUE THREAD

**Issue by zty18494** [star7th/showdoc#1040]
AWS S3是目前最常用的开源的OSS方案，企业私有化部署的OSS通常使用AWS S3，阿里云、腾讯云等公有云也支持AWS S3 SDK。是否能在存储云服务中增加AWS的选择？ 谢谢~

**Comment by star7th** [comment]
世界范围内的话，确实是常用的。但就国内范围而言，其实用得比较少。我很少听用户反馈这个需求。所以先再过一段时间看看吧，看需要的用户多不多。我预感会很少。甚至可以说，showdoc用户里使用服务器本地空间的更多，连用oss的都少。

Elsie.Zhang <notifications@github.com>于2020年8月3日 周一下午10:55写道：

**Comment by star7th** [comment]
已经发布新版，支持了s3
