### ISSUE TITLE
域名隐性解析跨域问题

### ISSUE THREAD

**Issue by versionchen** [star7th/showdoc#1042]
![image](https://user-images.githubusercontent.com/43264181/89279798-5e9e2c80-d67a-11ea-8fd3-541720b2c89b.png)
这个问题是否有办法解决,showdoc部署在家中,通过二级域名隐性解析

**Comment by star7th** [comment]
有共享需求的请部署到服务器上或者使用www.showdoc.cc 。

versionchen <notifications@github.com>于2020年8月4日 周二下午5:47写道：
