### ISSUE TITLE
建议：通过runapi自动生成的API文档希望能增加导出功能（word或markdown格式）。

### ISSUE THREAD

**Issue by shanesyk** [star7th/showdoc#1043]
通过runapi自动生成的API文档希望能增加导出功能（word或markdown格式）。

**Comment by star7th** [comment]
后续会在runapi客户端里增加导出功能

shane <notifications@github.com> 于2020年8月4日周二 下午7:00写道：

**Comment by wfion** [comment]
支持。也有这个需求

**Comment by star7th** [comment]
已在runapi客户端里新增导出word功能.

**Comment by FGadvancer** [comment]
https://github.com/FGadvancer/ruapi-generate-md
