### ISSUE TITLE
你好，docker删除镜像，重新拉取了一次镜像，数据出现丢失情况

### ISSUE THREAD

**Issue by Alary** [star7th/showdoc#1046]
你好，我将showdoc基础镜像删除了，然后重新拉取了一次，出现了数据丢失情况，但是之前的数据，我是有备份的，但是还原还是数据不完整，是否有遇到这种情况？

**Comment by star7th** [comment]
我没有遇到过这种情况。建议实用官方自动脚本管理。自己手动操作的话确保自己不出错。

aishiyushijiepingxing <notifications@github.com> 于2020年8月5日周三 下午5:22写道：
