### ISSUE TITLE
添加本地图片和上传附件 返回路径不正确

### ISSUE THREAD

**Issue by littlemolh** [star7th/showdoc#1048]
这是返回的url
https://域名/server/index.php?s=/api/attachment/visitFile/sign/5f09556ebffb4799b6340a0efb07edbc&showdoc=.jpg

**Comment by littlemolh** [comment]
实际上图片是有上传成功的，只是返回的地址不正确，
2020年7月 版本

**Comment by star7th** [comment]
搜索github历史问题，关键字https  图片

LittleMo <notifications@github.com>于2020年8月6日 周四下午4:43写道：
