### ISSUE TITLE
showdoc数据迁移问题

### ISSUE THREAD

**Issue by langdaoxinke** [star7th/showdoc#1049]
您好，现在遇到一个数据迁移的问题看能否提供帮助。
我在A服务器上使用自动脚本方式安装，现在想迁到B服务器上用的docker方式安装。根据您们提供的文档拷贝Sqlite/showdoc.db.php文件，但是拷贝到B服务器上，但是没效果。不知道哪里出了问题。希望能得到您们的技术支持。非常感谢！

**Comment by star7th** [comment]
请尝试在b服务器上也用自动脚本安装过后再迁移过去。如果不行的话，请详细描述，最好有截图，说明你上面说的“没效果”指的是什么。

langdaoxinke <notifications@github.com>于2020年8月6日 周四下午4:43写道：
