### ISSUE TITLE
MARKDOWN流程图支持求助

### ISSUE THREAD

**Issue by kussatom** [star7th/showdoc#1050]
```mermaid
graph TD;
  A-->B;
  A-->C;
  B-->D;
  C-->D;
```
请问一下 类似于这种的 支持吗 ，我写到文档里面始终显示不出来

**Comment by star7th** [comment]
这不是标准的markdown语法，不支持是正常的。
目前支持这种
![image](https://user-images.githubusercontent.com/2200494/89598767-37b94380-d890-11ea-8d0a-c21f0280988d.png)

**Comment by kussatom** [comment]
图片显示不出来

**Comment by star7th** [comment]
https://user-images.githubusercontent.com/2200494/89598767-37b94380-d890-11ea-8d0a-c21f0280988d.png

**Comment by kussatom** [comment]
GET ，3q,
