### ISSUE TITLE
runapi不支持环境变量吗

### ISSUE THREAD

**Issue by xuanLinDreamboy** [star7th/showdoc#1051]
类似postman的 environment

**Comment by star7th** [comment]
目前只支持项目变量，暂未支持环境变量。你手动改一下项目变量吧

xuanLinDreamboy <notifications@github.com> 于2020年8月7日周五 上午9:41写道：

**Comment by star7th** [comment]
已在新版支持环境功能。重启runapi便会自动更新完毕。
