### ISSUE TITLE
Mac版RunApi打开后白屏，一直加载不出来，窗口点击刷新页面也没有反应。

### ISSUE THREAD

**Issue by z66232232** [star7th/showdoc#1052]
部署在自己服务器上，第一次打开可以。关闭后再次启动RunApi便一直白屏，这是什么问题？
![image](https://user-images.githubusercontent.com/6468238/89707458-a259a480-d9a0-11ea-8c6e-e6b3818a1892.png)

**Comment by star7th** [comment]
showdoc可以部署在内网，但runapi自身需要网络访问。请确保自己能访问外网

moyang <notifications@github.com> 于2020年8月8日周六 下午5:57写道：

**Comment by z66232232** [comment]
网络试了没问题，我发现CMD+Q无法关闭，然后点击菜单的关闭，实际没有关闭。我在程序坞中右击退出后再次打开可以了。

**Comment by star7th** [comment]
可能是运行出了异常。只能重启或者重装试试了

moyang <notifications@github.com> 于2020年8月8日周六 下午6:42写道：

**Comment by wish5115** [comment]
用的官方服务器，同样打开Mac客户端白屏。

**Comment by star7th** [comment]
@wish5115 先按上面说的操作一遍。如果不行，提供详细电脑型号和截图
