### ISSUE TITLE
showdoc导入文件、导出文件出错

### ISSUE THREAD

**Issue by xiaoizichao** [star7th/showdoc#1054]
在https://www.showdoc.com.cn 此域名导出文件，选择markdown压缩包，导出来的文件是一个文件夹，文件夹名称：showdoc，然后在本地部署的showdoc节点上导入文件，不让我选中文件夹，随便一个json文件报错：未知错误。

**Comment by star7th** [comment]
我没理解你到底是要导入压缩包还是导入json。另外比较推荐使用官方自动脚本安装。

xiaoizichao <notifications@github.com>于2020年8月10日 周一下午5:39写道：

**Comment by xiaoizichao** [comment]
在https://www.showdoc.com.cn 此域名导出文件，导出的是一个文件夹，文件夹名称：showdoc，
现在我需要把导出的文件夹导入到本地部署的showdoc中，没有办法选中导入的文件夹，只能选择文件夹中的文件，所以我选择了showdoc文件夹中的一个json文件，然后报错：未知错误。

**Comment by star7th** [comment]
怎么会导出的是一个文件夹呢。不用解压，直接把压缩包扔进去

xiaoizichao <notifications@github.com> 于2020年8月11日周二 下午3:27写道：

**Comment by xiaoizichao** [comment]
没有解压 导出的就是一个文件夹

**Comment by xiaoizichao** [comment]
![截屏2020-08-11 下午3 41 16](https://user-images.githubusercontent.com/27492132/89870949-38800b80-dbe9-11ea-8565-12e27dcc63b1.png)

**Comment by star7th** [comment]
这是你的电脑系统问题，自动帮人解压了。反正导出来就是一个压缩包

xiaoizichao <notifications@github.com> 于2020年8月11日周二 下午3:41写道：

**Comment by xiaoizichao** [comment]
好的 谢谢 么么么哒
