### ISSUE TITLE
视频播放问题

### ISSUE THREAD

**Issue by lanboss** [star7th/showdoc#1055]
<video id="video" width=100% height=300 controls src=""></video>
视频播放，在一台测试机上搭建一切正常，搬到生产环境视频就是播放不了（都是window server环境），求给点思路，关键词，可能的原因

**Comment by lanboss** [comment]
``<video id="video" width=100% height=300 controls src="、     "></video>

**Comment by lanboss** [comment]
`<video id="video" width=100% height=300 controls src="、     "></video>`

**Comment by star7th** [comment]
感觉这是视频源的问题。跟showdoc无关。提供下外网地址看看。

fighting <notifications@github.com>于2020年8月11日 周二下午12:21写道：

**Comment by lanboss** [comment]
解决了要在IIS下增加MIME类型
