### ISSUE TITLE
文件被锁定不能编辑

### ISSUE THREAD

**Issue by kussatom** [star7th/showdoc#1056]
遇到个问题，文件被其它同事锁定了，但是他浏览器都是关完了的  这要怎么破啊

**Comment by star7th** [comment]
如果他退出编辑的话会立马解除锁定。如果是把整个都关了，默认半个小时后解除锁定

kussatom <notifications@github.com> 于2020年8月11日周二 下午5:55写道：

**Comment by kussatom** [comment]
OK,那只有等一下了 谢谢
