### ISSUE TITLE
几个功能建议

### ISSUE THREAD

**Issue by charles-slangelec** [star7th/showdoc#1057]
1. 导出能否支持到单页面导出?而不是只能整个目录导出.
2. 文档目录显示的区域是否可以扩大一些? 目前的目录显示区域太小了
3. 在编解界面下,滚动左边的编辑部分可以让右边的预览部分一起滚动, 但是滚动预览部分,编辑部分不会一起滚动

**Comment by star7th** [comment]
1，单页的话，自己直接复制打印即可，这个不需要程序来做。
2，目前设计如此，暂时不改设计。
3，目前是这样的。

zhsun <notifications@github.com> 于2020年8月12日周三 上午11:22写道：

**Comment by charles-slangelec** [comment]
1. 用网页直接打印的话, 1. 只能打印为pdf, 有时需要是word. 2. 网页打印为pdf的话, MD里有些代码块过长, 需要滚动条的,打印为pdf之后就显示不全了.
现在只能是导出为word,然后自己删掉不要的部分.或者自己复制到别的MD软件中导出.具体来说只是操作复杂了点.
2. pass
3. 这个可以考虑一下,能否做到真正两边联动? 
因为我们的文档都很长, 在编辑界面下,编辑框里的搜索使用起来不是太方便(不能搜索下一个), 所以要定位到一个地方的话很不方便. 但是在预览框中,可以直接点击开头的 [TOC] 跳转到对应的地方,还是很方便的, 但是对应的编辑框中不会跳转,所以要编辑还是要在编辑框中滚动

**Comment by star7th** [comment]
单页导出的需求，考虑在后面增加吧。
至于你说的那个两边同时联动。很少人会把单个文档弄得太长。要做到两边联动需要消耗很多精力。考虑到需求少，可能不做了。如果多点人反馈就再看吧。

zhsun <notifications@github.com> 于2020年8月12日周三 下午12:17写道：

**Comment by charles-slangelec** [comment]
好的, 我们文档写的是我们API的协议文档, 一般都比较长. 其实编辑框中把搜索做成支持不断搜索下一个也行的. 现在只能搜索一次,要搜下一个需要重新输入搜索关键字.
作者辛苦了! 有时间有精力心情好考虑添加一下这些吧, 用了一年多showdoc了,其他都感觉还不错的,谢谢!

**Comment by star7th** [comment]
已在新版支持单页面导出。
