### ISSUE TITLE
私有项目题目过长引起的界面问题

### ISSUE THREAD

**Issue by jiang1988tao1** [star7th/showdoc#1058]
当设置了私有项目后，标题过长，会在指向卡片时，导致界面显示异常，如图

![异常截图](https://user-images.githubusercontent.com/16534377/89979717-ff0bd680-dca2-11ea-959f-9600a1cc375a.png)

**Comment by star7th** [comment]
项目标题就别起那么长了吧。在项目描述里填写备注信息。

jiang1988tao1 <notifications@github.com> 于2020年8月12日周三 下午1:52写道：
