### ISSUE TITLE
建议增加一个备份功能

### ISSUE THREAD

**Issue by wyp0596** [star7th/showdoc#106]
## 数据的备份与恢复
web界面直接导出备份文件
web界面直接导入恢复文件

**Comment by star7th** [comment]
不需要这么做。你直接把整个文件夹复制一份即可

**Comment by wyp0596** [comment]
直接复制可以备份整个系统,不过我想如果是单个项目的备份是不是可以做成web的方式

**Comment by jackpgao** [comment]
如果有一键备份的话 会简单很多。

**Comment by jackpgao** [comment]
这个竞品：https://wiki.js.org/   配置的时候 可以指定一个git，自动的把文档备份过去。


不过这个太难用了，放弃了。
