### ISSUE TITLE
给runapi建议

### ISSUE THREAD

**Issue by kreocn** [star7th/showdoc#1060]
1 . Mock一定要引入
2 . 每个项目都会有固定的参数 , 比如Authentication的Header , 所以除了可自定义变量外.还可以固定项目的几个参数 , 包括Header/Param
感觉上面2点解决掉 , 就不单单是个写文档的工具了.

**Comment by star7th** [comment]
后面考虑更新这方面

kreo <notifications@github.com> 于2020年8月12日周三 下午8:22写道：

**Comment by star7th** [comment]
已在runapi中增加全局参数功能，也就是你说的固定参数。mock功能的话，需要另外从长计议。

**Comment by star7th** [comment]
已在runapi中增加mock功能，在返回参数的选项卡旁边。重启runapi就会热更新完毕。

**Comment by wonderfulxin** [comment]
现在我用runapi 去mock 的时候 这个地址 咋都复制不下来 呢？

<img width="1966" height="726" alt="Image" src="https://github.com/user-attachments/assets/419bdbbb-1e88-4885-9db1-046b3a3fd11b" />
