### ISSUE TITLE
自动脚本安装报错 http://localhost:4999/install/install.lock

### ISSUE THREAD

**Issue by dachuanTao** [star7th/showdoc#1066]
![image](https://user-images.githubusercontent.com/37361012/90591257-3f280780-e215-11ea-8c68-9db0850332bd.png)

**Comment by star7th** [comment]
这个跟服务器自身的配置有关。你可以尝试手动docker安装一步步调错。
https://www.showdoc.com.cn/help?page_id=65610

dachuanTao <notifications@github.com> 于2020年8月19日周三 下午12:12写道：

**Comment by dachuanTao** [comment]
好的,我试一下
