### ISSUE TITLE
runapi生成的markdown文档为何不能编辑,只能查看

### ISSUE THREAD

**Issue by javaboomBird** [star7th/showdoc#1067]

**Comment by star7th** [comment]
-


   runapi的数据可以生成markdown格式，但不可逆，markdown数据很难再转换回来runapi。所以它无法跟showdoc原有数据互相转换。只是它们可以共用文档浏览/团队协作等功能。后面如果要做数据共用，可能需要对showdoc编写格式有一定的规范约束，这个后面再探索下。



HuangZhangHong <notifications@github.com> 于2020年8月19日周三 下午2:00写道：
