### ISSUE TITLE
请问附件下载时文件名如何与上传时保持一致

### ISSUE THREAD

**Issue by hsysh** [star7th/showdoc#1068]
上传的文件下载时文件名是一串数字，请问可不可以让下载时保持和上传的文件名相同呢

**Comment by star7th** [comment]
为了可能的潜在风险，文件都是改名存在。不能保持一致。

Hoo <notifications@github.com> 于2020年8月19日周三 下午2:34写道：

**Comment by star7th** [comment]
为了可能的潜在风险，文件都是改名存放在服务器。不能保持一致。

Chen Xing <xing7th@gmail.com> 于2020年8月19日周三 下午2:41写道：

**Comment by hsysh** [comment]
可以告诉我这段代码在哪个文件吗，刚用不久，不熟悉，我想尝试本地改一改

**Comment by star7th** [comment]
不好改。你硬要这样子的话我也没办法。
https://github.com/star7th/showdoc/blob/master/server/Application/Api/Controller/AttachmentController.class.php


Hoo <notifications@github.com> 于2020年8月19日周三 下午2:51写道：

**Comment by hsysh** [comment]
好的，谢谢
