### ISSUE TITLE
linux上安装启动成功，也开放了4999端口，但是用浏览器就是访问不了

### ISSUE THREAD

**Issue by liubiao1** [star7th/showdoc#1071]
![image](https://user-images.githubusercontent.com/35096601/91026560-7c353500-e62d-11ea-8d42-06dd935b7527.png)

浏览器上就一直是拒绝连接

**Comment by liubiao1** [comment]
哪位大佬指导下是什么原因

**Comment by star7th** [comment]
防火墙，安全组，selinux，这个东西取决你的服务器配置

**Comment by liubiao1** [comment]
![image](https://user-images.githubusercontent.com/35096601/91120164-9b80a080-e6c7-11ea-9bb3-b4869d6eedb1.png)
崩溃了，应该不是上面说的那些原因吧

**Comment by star7th** [comment]
从这个图我无法得知是什么原因。

liubiao1 <notifications@github.com> 于2020年8月25日周二 上午11:40写道：
