### ISSUE TITLE
图片附件存储到云功能好像没效果

### ISSUE THREAD

**Issue by lgyhitler** [star7th/showdoc#1072]
我设置了图片附件储存到云 选的七牛云配置完成后，上传图片 但是图片附件链接没有变成 设置的oss绑定域名导致图片无法显示，这个是我配置的问题么？

**Comment by star7th** [comment]
提供生成后的图片链接示例

lgyt34 <notifications@github.com> 于2020年8月25日周二 上午10:10写道：

**Comment by lgyhitler** [comment]
抱歉，秀逗了，我用的https 协议 但是链接生成的是http的，改成https就能显示了...
