### ISSUE TITLE
docker升级时showdoc版本安装时一直提示需要授予可写权限

### ISSUE THREAD

**Issue by chanboo1985** [star7th/showdoc#1075]
curl http://localhost:4999/install/non_interactive.php?lang=zh
请赋予 server/Application/Home/Conf/config.php 文件以可写权限！<br>(如果你确定赋予了文件权限但却一直看到此信息，则可考虑关闭selinux试试)

请问如何来解决这个问题？

**Comment by star7th** [comment]
把docker挂载的那个目录整体递归给777权限

**Comment by chanboo1985** [comment]
已经给了权限：chmod  -R 777 /showdoc_data/html/
但是还有提示

**Comment by star7th** [comment]
那就是服务器自身的问题了。为什么给了权限还是写不进去，这个得看服务器自身的安全限制。showdoc做不了什么。

bchen <notifications@github.com> 于2020年8月27日周四 下午6:16写道：

**Comment by chanboo1985** [comment]
好的，谢谢
