### ISSUE TITLE
操作数据库时一直提示未知错误

### ISSUE THREAD

**Issue by chanboo1985** [star7th/showdoc#1076]
![image](https://user-images.githubusercontent.com/8817112/91435155-7db66580-e898-11ea-8acd-8e964599002f.png)

**Comment by chanboo1985** [comment]
新增用户、删除用户以及修改密码等操作，均会提示此信息

**Comment by star7th** [comment]
尝试给整个目录递归777权限。另外确保自己安装好了环境，建议使用官方自动脚本。

bchen <notifications@github.com> 于2020年8月27日周四 下午7:08写道：
