### ISSUE TITLE
功能建议: 文档编辑 - 支持拖动文件到浏览器 自动上传功能

### ISSUE THREAD

**Issue by FollowTheTrend** [star7th/showdoc#1077]
功能建议: 在 Markdown 输入框中支持拖动文件自动上传功能, 可以更便捷地编辑带有附件的文档, 谢谢

**Comment by star7th** [comment]
原来这个问题我还没回复。要监听整个编辑器挺麻烦的，得探索下能不能实现。我觉得最可能得情况是附件对话框那里允许拖动上传

**Comment by star7th** [comment]
已发布新版，解决了此问题。

**Comment by star7th** [comment]
但是附件拖动上传不是拖动在编辑器里。监听整个编辑器有点麻烦。而是打开附件按钮，然后会有个小窗口可以拖动文件上传。
