### ISSUE TITLE
RunApi 不支持put 无法传递数据

### ISSUE THREAD

**Issue by fwlst** [star7th/showdoc#1082]
RunApi put 服务端接受不到传过来的json数据， 使用Postman服务端就可以接收到。

**Comment by star7th** [comment]
目前已经知道的问题是，put方式的时候要表单传参数，暂时不支持json 。后面会看下怎么修复

fwlst <notifications@github.com> 于2020年8月31日周一 下午5:13写道：

**Comment by fwlst** [comment]
好的持续关注

**Comment by wfion** [comment]
同持续关注。我以为是Content-Type问题，是我想错了

**Comment by wfion** [comment]
建议增加一个raw格式 哈哈 这样就能自己搭配了

**Comment by star7th** [comment]
已修复此问题，重启runapi就会热更新完毕。

**Comment by wfion** [comment]
收到收到
