### ISSUE TITLE
希望完善对HTML <details> 标签的支持

### ISSUE THREAD

**Issue by YaoXuanZhi** [star7th/showdoc#1083]
- 详情看：[detail标签](https://www.w3school.com.cn/tags/tag_details.asp)
 - 同vscode的渲染效果对比图：
   - ![image](https://user-images.githubusercontent.com/14124918/91856094-ab385000-ec98-11ea-944b-cba8fa04b5d6.png)

**Comment by star7th** [comment]
其实我有点倾向于不处理这个。但看看需要的人多不多吧，多人需要的话就做。showdoc其实并没有打算支持完善的html标签

**Comment by YaoXuanZhi** [comment]
所噶，我这边有空的话，兴许也能加上这个特性支持，希望到时可以合并到主干上哈
