### ISSUE TITLE
解除锁定怎么用？

### ISSUE THREAD

**Issue by xiaomizaza** [star7th/showdoc#1085]
进入某个项目，状态是已锁定状态，可以在里面编辑内容。
但是在浏览器中打开一个同样的项目，仍然可以编辑。
解除锁定的功能不起作用吗？

**Comment by star7th** [comment]
你的话有歧义，没看懂。你从编辑框返回就会自动解锁。

xiaomizaza <notifications@github.com>于2020年9月2日 周三下午10:43写道：

**Comment by xiaomizaza** [comment]
是多人协作的场景。
按照我的理解，这个功能的意思是，某个人在编辑页面进入锁定状态。其他人不能编辑。此人点击“解除编辑”，其他人可以编辑页面。

但我操作了下，没有出现这样的效果，所以不知道这个按钮有何意义。

**Comment by xiaomizaza** [comment]
#729 
看到这个贴子，已经加了锁。但我试了下，没有自动锁定的效果出现。
我打开两个浏览器，一个进入编辑页面后，另一个也进入编辑页面，是可以编辑的

**Comment by star7th** [comment]
可能是因为相同账号引起的。尝试用不同的账号测试。

xiaomizaza <notifications@github.com> 于2020年9月2日周三 下午10:55写道：

**Comment by star7th** [comment]
多人协作功能，顾名思义就是多人，怎么可以使用同一个账号测试呢。

Chen Xing <xing7th@gmail.com> 于2020年9月2日周三 下午10:57写道：

**Comment by xiaomizaza** [comment]
用了不同账号，还是可以同时编辑

**Comment by star7th** [comment]
我刚才测试了下，功能一切正常。我不知道是你安装有问题还是测试方式 有问题。你可以试下官网  https://www.showdoc.com.cn/

xiaomizaza <notifications@github.com> 于2020年9月2日周三 下午11:09写道：
