### ISSUE TITLE
寻求帮助

### ISSUE THREAD

**Issue by xianzhikeji** [star7th/showdoc#1087]
showdoc访问不了了，安装方式也忘了，在服务器中看了一下，有showdoc相关的文件
![image](https://user-images.githubusercontent.com/35454175/92204743-b7015d80-eeb6-11ea-937c-7ded3c52449d.png)
。如果我现在想重新启动或者重新安装(保留原有的数据)应该怎么做?

**Comment by star7th** [comment]
docker restart  showdoc

xianzhikeji <notifications@github.com>于2020年9月4日 周五下午1:59写道：
