### ISSUE TITLE
put请求无法传数组，post请求则正常

### ISSUE THREAD

**Issue by YouLiLiao** [star7th/showdoc#1088]
![image](https://user-images.githubusercontent.com/11286354/92617745-35646200-f2f2-11ea-8924-7545d42abd3e.png)
上面是put请求，参数传数组无法识别
下面则是post请求
![image](https://user-images.githubusercontent.com/11286354/92617847-5331c700-f2f2-11ea-9192-72f952da2b68.png)

**Comment by star7th** [comment]
传递复杂结构数据建议使用json传输。或者把数据变成以逗号分隔的纯字符串。你这样设计的接口可能在手机端或者web端调用起来没那么方便。

YouLiLiao <notifications@github.com> 于2020年9月9日周三 下午11:15写道：
