### ISSUE TITLE
【样式问题】dropdown-menu会撑出视区

### ISSUE THREAD

**Issue by wingmeng** [star7th/showdoc#109]
页头的“项目”菜单，点击后会弹出当前项目的管理菜单，这个菜单使用了Bootstrap的dropdown-menu组件，默认是左对齐点击对象的，此处会导致弹出的菜单撑出可视区，出现水平滚动条：
![image](https://cloud.githubusercontent.com/assets/9009389/23596105/840e107e-0262-11e7-8c1a-a0cdbfc69de3.png)
请为此处的dropdown-menu增加如下CSS代码即可解决问题（需要覆盖bootstrap中的原有样式）：
`left: auto; right: 0;`
补充：Bootstrap自带实现菜单右对齐的功能，只需为dropdown-menu增加pull-right这个样式即可。
修复后效果：
![image](https://cloud.githubusercontent.com/assets/9009389/23596181/0a31cf6a-0263-11e7-83ed-174c5839de96.png)

**Comment by star7th** [comment]
好的，已经修复此问题
