### ISSUE TITLE
页面排序

### ISSUE THREAD

**Issue by srain20** [star7th/showdoc#1090]
现在目录有拖拽排序功能，请问页面可以也增加拖拽排序功能吗？

**Comment by star7th** [comment]
编辑页面的时候，右上角有个页面排序

Xu Xiaoxiang <notifications@github.com> 于2020年9月10日周四 下午12:12写道：

**Comment by star7th** [comment]
编辑页面的时候，上方有个页面排序。目录编辑的右边也有页面排序的按钮

Chen Xing <xing7th@gmail.com> 于2020年9月10日周四 下午2:13写道：

**Comment by srain20** [comment]
找到了，感谢回复！
