### ISSUE TITLE
console errors report length undefined error

### ISSUE THREAD

**Issue by hiproz** [star7th/showdoc#1091]
下载docker运行，F12 console有error，于是到官网demo 确认，也是同样的现象：

vue.min.js:6 TypeError: Cannot read property 'length' of undefined
    at a.render (app.f024f2450b83cca33fec.js:1)
    at a.e._render (vue.min.js:6)
    at a.r (vue.min.js:6)
    at fn.get (vue.min.js:6)
    at new fn (vue.min.js:6)
    at vue.min.js:6
    at a.wn.$mount (vue.min.js:6)
    at a.wn.$mount (vue.min.js:6)
    at init (vue.min.js:6)
    at vue.min.js:6
Ue @ vue.min.js:6
Be @ vue.min.js:6
Re @ vue.min.js:6
e._render @ vue.min.js:6
r @ vue.min.js:6
fn.get @ vue.min.js:6
fn @ vue.min.js:6
(anonymous) @ vue.min.js:6
wn.$mount @ vue.min.js:6
wn.$mount @ vue.min.js:6
init @ vue.min.js:6
(anonymous) @ vue.min.js:6
f @ vue.min.js:6
h @ vue.min.js:6
f @ vue.min.js:6
h @ vue.min.js:6
f @ vue.min.js:6
h @ vue.min.js:6
f @ vue.min.js:6
(anonymous) @ vue.min.js:6
e._update @ vue.min.js:6
r @ vue.min.js:6
fn.get @ vue.min.js:6
fn @ vue.min.js:6
(anonymous) @ vue.min.js:6
wn.$mount @ vue.min.js:6
wn.$mount @ vue.min.js:6
init @ vue.min.js:6
(anonymous) @ vue.min.js:6
f @ vue.min.js:6
(anonymous) @ vue.min.js:6
x @ vue.min.js:6
(anonymous) @ vue.min.js:6
e._update @ vue.min.js:6
r @ vue.min.js:6
fn.get @ vue.min.js:6
fn.run @ vue.min.js:6
un @ vue.min.js:6
(anonymous) @ vue.min.js:6
qe @ vue.min.js:6
Promise.then (async)
ze @ vue.min.js:6
Ye @ vue.min.js:6
(anonymous) @ vue.min.js:6
fn.update @ vue.min.js:6
ce.notify @ vue.min.js:6
set @ vue.min.js:6
pn.set @ vue.min.js:6
gl.close @ index.js:1
(anonymous) @ app.f024f2450b83cca33fec.js:1
Promise.then (async)
get_item_menu @ app.f024f2450b83cca33fec.js:1
mounted @ app.f024f2450b83cca33fec.js:1
He @ vue.min.js:6
Yt @ vue.min.js:6
insert @ vue.min.js:6
k @ vue.min.js:6
(anonymous) @ vue.min.js:6
e._update @ vue.min.js:6
r @ vue.min.js:6
fn.get @ vue.min.js:6
fn @ vue.min.js:6
(anonymous) @ vue.min.js:6
wn.$mount @ vue.min.js:6
wn.$mount @ vue.min.js:6
t._init @ vue.min.js:6
t._init @ vendor.625efbf18fa14ca74d00.js:31
wn @ vue.min.js:6
NHnr @ app.f024f2450b83cca33fec.js:1
t @ manifest.2ae2e69a05c33dfc65f8.js:1
window.webpackJsonp @ manifest.2ae2e69a05c33dfc65f8.js:1
(anonymous) @ app.f024f2450b83cca33fec.js:1
Show 10 more frames
vendor.625efbf18fa14ca74d00.js:13 Uncaught (in promise) Error: Avoided redundant navigation to current location: "/demo?page_id=7".
    at At (vendor.625efbf18fa14ca74d00.js:13)
    at n.Ct.confirmTransition (vendor.625efbf18fa14ca74d00.js:13)
    at n.Ct.transitionTo (vendor.625efbf18fa14ca74d00.js:13)
    at n.replace (vendor.625efbf18fa14ca74d00.js:13)
    at vendor.625efbf18fa14ca74d00.js:13
    at new Promise (<anonymous>)
    at Gt.replace (vendor.625efbf18fa14ca74d00.js:13)
    at a.change_url (app.f024f2450b83cca33fec.js:1)
    at a.select_menu (app.f024f2450b83cca33fec.js:1)
    at a.mounted (app.f024f2450b83cca33fec.js:1)

**Comment by star7th** [comment]
已修复。你更新就好。
