### ISSUE TITLE
本地部署的程序上传附件或图片外网访问问题

### ISSUE THREAD

**Issue by oopsu** [star7th/showdoc#1093]
我是内网192部署的上传附件或图片后外网访问，附件下载或者图片开头的网址都是192开头的，导致无法获取图片或下载附件，请问这个问题要怎么解决呢？

**Comment by oopsu** [comment]
[](url)

**Comment by star7th** [comment]
没办法解决。showdoc更多是为服务器准备的，请把showdoc部署到可外网访问的服务器，或者使用官网
https://www.showdoc.com.cn/

oopsu <notifications@github.com> 于2020年9月18日周五 下午6:06写道：

**Comment by oopsu** [comment]
服务器是有外网ip的。现在就是192.168内网上传附件或图片后，外网183打开图片无法显示，附件也没法下载。不然要一个一个改已存在的附件和图片的ip就非常麻烦了。后期也不能保证外网ip不会换一个。看有什么办法内网编辑外网能正常访问和下载，

**Comment by star7th** [comment]
没有办法。

oopsu <notifications@github.com> 于2020年9月18日周五 下午6:18写道：

**Comment by oopsu** [comment]
我的公网IP183.x.x:9000操作时,遇到了新问题，上传图片生成的链接后面没有端口。上传附件也是，手动添加也不正常。这个要在哪里改一下呢？

**Comment by star7th** [comment]
请使用官方自动脚本部署。正常是不会存在你说的问题的，我不知道你是怎么部署的。

oopsu <notifications@github.com>于2020年9月19日 周六下午5:14写道：
