### ISSUE TITLE
runapi中编辑纯markdown文档, 内容被html转义问题

### ISSUE THREAD

**Issue by hsk-story** [star7th/showdoc#1094]
在[纯markdown文档]中如果有填写""<>&之类的符号, 下次重新打开时, 会被转义成&lt; &gt;&amp;&quot;这种html实体符. showdoc网页版就不会有这个问题

**Comment by star7th** [comment]
后面更新再修复此问题。

hhsskk <notifications@github.com> 于2020年9月21日周一 上午10:20写道：

**Comment by hsk-story** [comment]
@star7th 好的, 不过这个问题其实发现很久了, 而且这个自动转义还挺影响编辑纯markdown文本的

**Comment by star7th** [comment]
已修复此问题
