### ISSUE TITLE
开源版的编辑器无法粘贴内容?

### ISSUE THREAD

**Issue by sn01615** [star7th/showdoc#1098]
开源版的编辑器无法粘贴内容?粘贴无反应只能手动输入?

**Comment by star7th** [comment]
一直都可以。请截图说明下你是怎么得出无法粘贴内容的结论的

YangLong <notifications@github.com> 于2020年9月22日周二 下午6:46写道：

**Comment by sn01615** [comment]
可以了 刚才是我电脑故障
