### ISSUE TITLE
缺少导入功能

### ISSUE THREAD

**Issue by CinderellaCiCi** [star7th/showdoc#11]
看到有导出功能，但没有逆操作。

建议按导出的内容格式创建导入功能。
格式不正确时将内容放到一个页面，页面标题设为“xx用户导入”即可，方便复制编辑。

**Comment by star7th** [comment]
mrakdown格式的文本要转为html很容易，可是逆操作则难了。迟点看看怎么处理。现在先用着吧

**Comment by CinderellaCiCi** [comment]
哦这样啊。期待更新~

**Comment by CinderellaCiCi** [comment]
哦对了，其实没必要逆操作将html转为markdown，我看了下输入框本身就支持纯html吧？
如果能将word内容整成html也是一样的。

（不过，预览框貌似不支持显示纯html写的内容、

**Comment by star7th** [comment]
如果纯html的话，以后都不能使用markdown编辑器了的。到时再看看吧，这个需求并不是很多人需要

**Comment by CinderellaCiCi** [comment]
看到了一个html和markdown互转的工具，推荐给你：http://www.atool.org/html2markdown.php

**Comment by star7th** [comment]
html转markdown，兼容性很一般。可能空闲下来会考虑做markdown源文件的导出与导入。
