### ISSUE TITLE
runapi客户端

### ISSUE THREAD

**Issue by shenjungit** [star7th/showdoc#1102]
runapi客户端创建的项目，希望可以在网页版转成markdown自信编辑！！

**Comment by star7th** [comment]
runapi的数据可以生成markdown格式，但不可逆，markdown数据很难再转换回来runapi。所以它无法跟showdoc原有数据互相转换。只是它们可以共用文档浏览/团队协作等功能。同时runapi生成的文档只能在runapi上编辑，不能在showdoc上编辑。后面如果要做数据共用，可能需要对showdoc编写格式有一定的规范约束，这个后面再探索下。


jun <notifications@github.com> 于2020年9月24日周四 下午7:20写道：
