### ISSUE TITLE
建议项目添加团队时能对团队权限进行控制

### ISSUE THREAD

**Issue by Fionashow** [star7th/showdoc#1107]
![image](https://user-images.githubusercontent.com/16496309/94397171-d88ff500-0195-11eb-8bbd-695c798a5d8b.png)
项目添加团队时，能跟添加个人账号有相似功能，可以统一设置只读权限（目前默认添加团队是编辑权限）

**Comment by star7th** [comment]
默认都是继承编辑权限的。如果要只读权限，则需要单独设置。这个主要是出于使用频率的原因。整个团队只读的概率还是蛮低，这种特殊情况还是建议手动设置下成员权限。如果多一点用户反馈有这个需求的话再改。

Fionashow <notifications@github.com> 于2020年9月28日周一 下午2:23写道：
