### ISSUE TITLE
RunApi请求地址https会报错

### ISSUE THREAD

**Issue by weirdo945** [star7th/showdoc#1108]
同事用https请求就可以成功，我用https请求一直显示网络异常
<img width="659" alt="屏幕截图 2020-09-28 184201" src="https://user-images.githubusercontent.com/68574101/94422977-7ac1d400-01ba-11eb-9aaa-da0f52b064f0.png">

**Comment by star7th** [comment]
不支持自签名的证书。必须是经过公网验证的

weirdo945 <notifications@github.com> 于2020年9月28日周一 下午6:43写道：

**Comment by weirdo945** [comment]
好的，感谢
