### ISSUE TITLE
请问调试模式下怎么设置后端api？

### ISSUE THREAD

**Issue by tang086** [star7th/showdoc#1109]
执行npm run dev 以启用调式模式，通过访问 localhost:8080 便可以实时看到改动的效果。请使用代理以便请求后端API的时候代理到PHP服务端。
请问具体怎么配置访问后端API？

**Comment by star7th** [comment]
通常来讲不懂这个基本操作的人也不会二次开发的。劝你放弃吧....

tang086 <notifications@github.com> 于2020年9月29日周二 下午4:30写道：
