### ISSUE TITLE
搜索功能报错

### ISSUE THREAD

**Issue by visionding** [star7th/showdoc#111]
环境：Windows Server 2012R2、PHP 5.6

在项目页面的搜索框搜索的时候会出现错误：

Class 'SQLite3' not found
错误位置
FILE: E:\Web\showdoc\Application\Home\Controller\ItemController.class.php 　LINE: 173

**Comment by star7th** [comment]
奇怪，你既然能用showdoc了，证明sqlite3是被支持了的。怎么会缺失

参考这个解决方法http://www.jianshu.com/p/0d63eaf17f66

**Comment by visionding** [comment]
找到原因了，我改错了配置文件了。。。。

**Comment by oceanbaby715** [comment]
@visionding  你的配置是哪里改错了   我升级版本后也发现有这个问题   但是我不知道我忘记我改了什么东方了
