### ISSUE TITLE
迁移旧版本的数据到新版本的Sqlite后plantUML就不能正常显示了

### ISSUE THREAD

**Issue by jhhe66** [star7th/showdoc#1110]
问题：showdoc 支持plantUML,我程序是最新的，
把旧版本的数据导入到新的数据库后，UML就不能正常显示了。要怎么解决？

**Comment by star7th** [comment]
先清理浏览器缓存试下。不行再截图。

jhhe66 <notifications@github.com> 于2020年9月30日周三 上午9:33写道：
