### ISSUE TITLE
切换项目会来回切换死循环

### ISSUE THREAD

**Issue by zaq11qaz** [star7th/showdoc#1111]
切换项目会来回切换死循环
无法切换至目标项目

**Comment by star7th** [comment]
尝试重启后再看看。不行再截图

zaq11qaz <notifications@github.com>于2020年10月9日 周五上午11:04写道：

**Comment by zaq11qaz** [comment]
![Uploading 20201009-124936.gif…]()

**Comment by zaq11qaz** [comment]
![20201009-124936](https://user-images.githubusercontent.com/55392923/95544781-b4060980-0a2e-11eb-9517-852c9a79367f.gif)

**Comment by star7th** [comment]
它切换的时候可能需要加载项目没那么快，你尝试重启后，排序遗留影响，然后切换慢一些。或者再新建个项目试着下切换多个项目

**Comment by zaq11qaz** [comment]
问题是切不过去,得一直点才能切换到目标项目,新建多个项目比这个还惨,每一个切换都切不过去

**Comment by zaq11qaz** [comment]
![20201009-141444](https://user-images.githubusercontent.com/55392923/95549463-ec5f1500-0a39-11eb-9551-b7053ed9a185.gif)
有bug啊 不是重启能解决的问题

**Comment by zaq11qaz** [comment]
![20201009-141444](https://user-images.githubusercontent.com/55392923/95549511-01d43f00-0a3a-11eb-8cf1-9fccaee7e6d1.gif)

**Comment by zaq11qaz** [comment]
![20201009-141444](https://user-images.githubusercontent.com/55392923/95549565-1ca6b380-0a3a-11eb-9f03-073ef842414f.gif)

**Comment by star7th** [comment]
我重现不了这个问题。我自己试了是没问题的。但我确实记得历史我曾经遇过小概率的这种事情，只是后来无法重现所以不管了。现在也重现不了。此外你尝试不连接私有服务器，直接采用官方showdoc看看。

**Comment by zaq11qaz** [comment]
官方服务器没问题,这个是私有服务器就这个项目很难切换过去

**Comment by zaq11qaz** [comment]
![image](https://user-images.githubusercontent.com/55392923/95550500-94c1a900-0a3b-11eb-9ec1-49dd8cfede69.png)
这个短时间循环调切换项目就离谱

**Comment by zaq11qaz** [comment]
[log.txt](https://github.com/star7th/showdoc/files/5352938/log.txt)
看看日志有没有帮助吧,求解决233

**Comment by star7th** [comment]
这日志看不到啥帮助。这个问题暂时没想到解决方法。主要是重现不了，只能等到能重新的时候才好分析问题

**Comment by star7th** [comment]
另外私服的接口如果延迟太长可能会有点问题。你尝试装在一个延迟快点的服务器上试试会不会是这个问题

**Comment by zaq11qaz** [comment]
了解 
![image](https://user-images.githubusercontent.com/55392923/95555071-d0607100-0a43-11eb-9167-cf3192cc695d.png)
延迟不太高吧

**Comment by star7th** [comment]
我这边利用自动脚本安装了一个私有版showdoc，链接到runapi也没发现你说的问题。也可能是我的接口数太少导致重现不了。如果你的接口数很多的话，切换慢点让它加载完。加载那么多接口延迟很高的

**Comment by zaq11qaz** [comment]
接口很多 ，怎么切换慢点诶，是点一下等他加载吗
现在是点切换来回跳 ， 但是跳不到目标目录 ，是什么机制吗

**Comment by star7th** [comment]
我不知道。我以上只是猜测。实际上我无法重现你的问题，我不知道为什么。建议你提供一个外网可重现例子，否则我可能无能为力。

zaq11qaz <notifications@github.com> 于2020年10月14日周三 上午10:14写道：

**Comment by zaq11qaz** [comment]
好难哦，私服也不能导出项目，也没法重现，那等以后有机会在说吧

**Comment by zaq11qaz** [comment]
切换空的和内容少的没问题 ，就那个内容多的会有这个问题

**Comment by star7th** [comment]
我在切换项目的时候增加了一个loading，应该能缓解下这个问题。

**Comment by zaq11qaz** [comment]
收到 我更新一下

**Comment by zaq11qaz** [comment]
SQLSTATE[HY000]: General error: 1 no such table: runapi_global_param 。错误位置：/var/www/html/server/ThinkPHP/Library/Think/Db/Driver.class.php 174

完 更新出错了

**Comment by zaq11qaz** [comment]
SQLSTATE[HY000]: General error: 1 no such table: runapi_global_param 。错误位置：/var/www/html/server/ThinkPHP/Library/Think/Db/Driver.class.php 174

新版本报错

**Comment by star7th** [comment]
访问下showdoc的项目列表页面，就触发它自动升级数据库的机制。

zaq11qaz <notifications@github.com> 于2020年11月16日周一 上午11:36写道：

**Comment by star7th** [comment]
是网页版showdoc

Chen Xing <xing7th@gmail.com> 于2020年11月16日周一 上午11:40写道：

**Comment by zaq11qaz** [comment]
升级可以了 切换小的项目没问题 大的项目还是不灵 切不到目标项目

**Comment by zaq11qaz** [comment]
> 我在切换项目的时候增加了一个loading，应该能缓解下这个问题。

给你网址登一下好使吗

**Comment by star7th** [comment]
大的项目估计就是网络加载慢，导致前端响应延迟。你可以给我网址登录下吧。

**Comment by zaq11qaz** [comment]
> 大的项目估计就是网络加载慢，导致前端响应延迟。你可以给我网址登录下吧。

xing7th<xing7th@gmail.com>
发送给你这个邮箱了 带文件一起

**Comment by star7th** [comment]
我比较了一下，可能不是大小问题。因为”pc端“这个项目也挺大的。但也能正常使用。然后我看了下，不能正常切换的是”成员项目“，即不是自己创建的项目。你尝试用创建者账户登录，或者说复制一个项目出来转让给当前用户试试能不能切换。可能对于像项目成员，有地方权限判断出错了。

**Comment by zaq11qaz** [comment]
好的 试一下

**Comment by zaq11qaz** [comment]
showdoc
这个帐号也是这样 
这个是最高权限了吧

**Comment by star7th** [comment]
要用项目创建者账户登录。不是showdoc账户。showdoc不会继承全部项目的权限。

**Comment by zaq11qaz** [comment]
转让给我自己了  还是不好使 
![image](https://user-images.githubusercontent.com/55392923/99225887-c04a6700-2823-11eb-8241-161fb1a43fdf.png)

**Comment by zaq11qaz** [comment]
现在的需要再发你一份吗

**Comment by zaq11qaz** [comment]
使用showdoc帐号转让的

**Comment by star7th** [comment]
我先用你发的网址调试下。

**Comment by star7th** [comment]
这个问题解决了。你重启runapi就热更新完毕。此问题主要是当showdoc服务端返回数据慢的时候才会出现。我本地调试以及使用官网都很快，所以一直没发现此问题。

**Comment by zaq11qaz** [comment]
好的 重启一下试试

**Comment by zaq11qaz** [comment]
好了 谢谢
