### ISSUE TITLE
使用base64编码的图片无法正常显示

### ISSUE THREAD

**Issue by gaokingK** [star7th/showdoc#1113]
作者你好，最近在自己服务器上部署的showdoc在使用中发现无法显示base64编码格式的图片，无论是使用markdown还是html语法都不能正常显示，而在vscode的markdown预览里却能显示图片。

**Comment by star7th** [comment]
大部分编辑器都不支持。支持的只是因为人家特地做了兼容。

gaokingK <notifications@github.com>于2020年10月9日 周五下午5:25写道：

**Comment by gaokingK** [comment]
那html语法里使用base64编码引入的图片也不能在showdoc里显示吗？

**Comment by star7th** [comment]
你试下吧，我忘记了，可能不支持。当初为了安全禁用了很多东西。

gaokingK <notifications@github.com>于2020年10月9日 周五下午5:32写道：

**Comment by gaokingK** [comment]
多谢多谢！
