### ISSUE TITLE
后台新增用户

### ISSUE THREAD

**Issue by zhendeainio** [star7th/showdoc#1114]
在后台用户管理页面:
先操作用户 "编辑", 再点击 "新增用户", 弹出的窗口一直都是属于 "编辑" 用户的状态.
在确认之后再点 "新增用户" 窗口才正确.
不确定是否浏览器的问题, 使用的是Chrome 84.0.4147.105

**Comment by star7th** [comment]
我后面找时间重现下

莫丶何释爱 <notifications@github.com> 于2020年10月9日周五 下午7:46写道：

**Comment by star7th** [comment]
经测试，不存在此问题。请确保自己使用新版代码。

**Comment by star7th** [comment]
我好像又重现了。下一版本再一起改。

**Comment by star7th** [comment]
已修复该问题
