### ISSUE TITLE
能否增加一个上传文件的API

### ISSUE THREAD

**Issue by gaokingK** [star7th/showdoc#1115]
作者你好，最近准备用showdoc搭建一个文档中心，需要把之前的大量文档给导入进去，遇到了一个问题，原来的文档中有很多图片，通过开放API导入包含base64编码的图片无法正常显示（这个昨天已经提过issue了#1113），准备在后台将图片上传后，然后在源文件中将base64编码替换为对图片的引用。要不手动一个一个太麻烦了。这个通过二次开发可以实现吗？

**Comment by star7th** [comment]
你自己在showdoc上传图片然后看下网络请求。同时自己用程序用cookie模拟登录。


gaokingK <notifications@github.com>于2020年10月10日 周六下午2:25写道：

**Comment by gaokingK** [comment]
OK，TKS！

**Comment by gaokingK** [comment]
按照你的指导，我使用借口测试工具来测试上传接口，但是在前台却查不到上传的图片，查看日志发现有个WARN，这是什么原因呢？
```
# 发送请求
curl -XPOST   --url 'http://90.90.67.14:4999/server/index.php?s=%2Fapi%2Fpage%2FuploadImg&guid=1602321717217'  --header 'cookie: PHPSESSID=6fc6517a12c24b47a694528ed5585b7b;think_language=zh-CN'  --form "file=@/tmp/112.png"
# 日志
2020/10/12 08:28:49 [warn] 429#429: *4493 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000117, client: 90.253.80.171, server: _, request: "POST /server/index.php?s=%2Fapi%2Fpage%2FuploadImg&guid=1602321717217 HTTP/1.1", host: "90.90.67.14:4999"
90.253.80.171 - - [12/Oct/2020:08:28:49 +0000] "POST /server/index.php?s=%2Fapi%2Fpage%2FuploadImg&guid=1602321717217 HTTP/1.1" 200 5 "-" "insomnia/7.0.1"

```

**Comment by star7th** [comment]
我可能没太大时间帮你找问题。程序本身能上传图片的。应该就是模拟登录以及请求接口没做好。你可以了解下相关爬虫知识，用一个现成的爬虫框架也行，不一定纯命令行

gaokingK <notifications@github.com> 于2020年10月12日周一 下午4:32写道：

**Comment by gaokingK** [comment]
OK , 我冷静分析下:stuck_out_tongue_closed_eyes:
