### ISSUE TITLE
建议左侧目录菜单做成「可收缩展开」

### ISSUE THREAD

**Issue by yuxingxin** [star7th/showdoc#112]
如题，类似我们的编辑器一样,这样当菜单收缩进去时右侧内容展示的区域就更大了

**Comment by star7th** [comment]
往后考虑

**Comment by star7th** [comment]
官网已经提前上线了 可收缩功能  https://www.showdoc.cc/web/#/help?page_id=13732
开源版迟点发布2.0版，连同其他更新。

**Comment by phpyii** [comment]
@star7th  谢谢作者回答。我设置了顺序数字。 但是感觉没有倒序方便。  数字越大越靠前感觉设置容易

**Comment by star7th** [comment]
@phpyii 这会容易导致乱。比如说我忘记设置多大才会靠前了，于是设置一个很大的数字。下次又设置一个超大的数字。数字的不连贯增加逻辑理解难度
