### ISSUE TITLE
引用外部图片，显示不出来

### ISSUE THREAD

**Issue by muziling** [star7th/showdoc#1121]
浏览器F12发现是因为请求带了referer，所以被拒绝了，去掉referer就可以显示。powershell里的脚本

Invoke-WebRequest -Uri "https://img-blog.csdn.net/20130618224337734" -Headers @{
"method"="GET"
  "authority"="img-blog.csdn.net"
  "scheme"="https"
  "path"="/20130618224337734"
  "pragma"="no-cache"
  "cache-control"="no-cache"
  "user-agent"="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
  "accept"="image/avif,image/webp,image/apng,image/*,*/*;q=0.8"
  "sec-fetch-site"="cross-site"
  "sec-fetch-mode"="no-cors"
  "sec-fetch-dest"="image"
  "referer"="http://192.168.1.8:6690/"
  "accept-encoding"="gzip, deflate, br"
  "accept-language"="zh-CN,zh;q=0.9,zh-TW;q=0.8"
}

**Comment by star7th** [comment]
这个是外部图片自身的防盗链机制，跟showdoc无关

**Comment by muziling** [comment]
可能是chrome浏览器自动加上的， 我装了个refer control扩展将就着用
