### ISSUE TITLE
【建议】现在的字体太小了！！！

### ISSUE THREAD

**Issue by inhere** [star7th/showdoc#1126]
现在的字体太小了！！！

- 目录栏 `12px`
- 文档内容 `14px`

现在的屏幕分辩率这么高了，看着眼睛伤不起啊!!

**Comment by star7th** [comment]
内容文字大小明明是14px ， 你怎么得出是12的说法

**Comment by inhere** [comment]
内容该改成 16px

**Comment by star7th** [comment]
不打算改，设计如此。你可以在你自己的代码里改。

Inhere <notifications@github.com>于2020年10月14日 周三下午7:38写道：
