### ISSUE TITLE
markdown序号展示不正确

### ISSUE THREAD

**Issue by muziling** [star7th/showdoc#1127]
新增一个页面内容

> 1. 检查 spark的这几个参数，不要太大，生产环境比较大，测试的小，如下改为20。

```ini
--num-executors 20
-conf spark.dynamicAllocation.initialExecutors=20
-conf spark.dynamicAllocation.minExecutors=20
```

2. 脚本里的spark2-submit 要改为 spark-submit

查看时，第2点的2展示成1，变成两个1

**Comment by star7th** [comment]
请手写数字。showdoc对数字序号支持不是很好。

muziling <notifications@github.com> 于2020年10月15日周四 下午3:53写道：

**Comment by star7th** [comment]
自动生成数组不好控制的，有时候写的内容多了，它就失去效果了。不建议对多内容进行这种写法

Chen Xing <xing7th@gmail.com> 于2020年10月15日周四 下午3:54写道：
