### ISSUE TITLE
找回密码功能

### ISSUE THREAD

**Issue by rebaomi** [star7th/showdoc#113]
忘记密码后无法登陆，希望添加找回密码功能

**Comment by star7th** [comment]
对于在线showdoc https://www.showdoc.cc/ 是有找回密码功能的。而对于开源版，由于找回密码功能依赖邮件，而很多主机不支持发邮件，所以开源版showdoc不打算支持

**Comment by star7th** [comment]
如果是自己部署的ShowDoc，可以先自行注册一个密码为123456的新用户。然后进数据库，把user表里新用户的password字段覆盖原用户。这样便可以将密码重置为123456。登录后，可在个人设置处改密码。关于如何连接数据库，请看本页面后续问题。

**Comment by star7th** [comment]
关于链接数据库，你可以网络搜索如何在命令行中使用 sqlite数据库.或者使用SQLiteStudio等可视化工具

**Comment by rebaomi** [comment]
ok,之前不知道怎么使用sqlite可视化，但是我没找到相应的数据文件，数据好像存在php文件内部

**Comment by star7th** [comment]
showdoc.db.php是个数据库文件，我更改扩展名只是为了防止被下载而已，不影响使用。你在sqlite软件了选择打开文件，选择showdoc.db.php
