### ISSUE TITLE
左边编辑区域能输入文字，但是不能ctrl+v粘贴文字！

### ISSUE THREAD

**Issue by longdw** [star7th/showdoc#1130]
在自己服务器上搭建了一套，但是左边编辑区域只能输入文字，不能ctrl+v粘贴文字。

**Comment by star7th** [comment]
剪切板是系统行为，跟showdoc无关。你重启电脑试试。

longdw <notifications@github.com> 于2020年10月16日周五 下午2:04写道：

**Comment by star7th** [comment]
我说的是重启你自己的电脑，不是服务器。它跟服务器无关。

Chen Xing <xing7th@gmail.com> 于2020年10月16日周五 下午2:24写道：

**Comment by longdw** [comment]
官网的markdown编辑器左边的区域就能复制粘贴，就是我自己搭建的不行。
![image](https://user-images.githubusercontent.com/4987178/96220721-d44c4000-0fbb-11eb-8ce9-a4c2c0c9c3d8.png)
这两个区域都没法ctrl+v复制东西进去。

**Comment by longdw** [comment]
可以了，浏览器进程关掉重新打开就好了，也是奇了怪了。

**Comment by aimei54** [comment]
这个问题我也重现了……不知道为啥
