### ISSUE TITLE
删除页面返回404

### ISSUE THREAD

**Issue by zhaohexiang-zhx** [star7th/showdoc#1133]
删除页面时没有反应，查看返回404

![image](https://user-images.githubusercontent.com/58206566/96418348-39569e80-1225-11eb-8e2e-25f0b3b51ba8.png)

**Comment by star7th** [comment]
升级到最新版

zhaohexiang-zhx <notifications@github.com> 于2020年10月19日周一 下午4:08写道：

**Comment by zhaohexiang-zhx** [comment]
升级到最新版，问题解决了，请问是什么导致的呢

**Comment by star7th** [comment]
不知道。反正你那个404一看就知道不是新版。先升级新版再说。

zhaohexiang-zhx <notifications@github.com> 于2020年10月19日周一 下午4:54写道：
