### ISSUE TITLE
导出word丢失一部分数据

### ISSUE THREAD

**Issue by wuhao052710** [star7th/showdoc#1134]
![image](https://user-images.githubusercontent.com/73168173/96570693-3af39580-12fd-11eb-85e7-d2f513866d5b.png)
![image](https://user-images.githubusercontent.com/73168173/96570677-37f8a500-12fd-11eb-9cea-35df255fcc72.png)
丢失了好多目录

**Comment by star7th** [comment]
内容中如果包含尖括号则可能截断

wuhao052710 <notifications@github.com> 于2020年10月20日周二 下午5:54写道：
