### ISSUE TITLE
权限控制功能bug

### ISSUE THREAD

**Issue by wgege** [star7th/showdoc#1137]
比如我的项目下面有两个文档目录，给用户只开通第一个目录的权限，用户从项目进去无法看到第二个目录中的列表和内容，但是如果知道第二个目录中页面的ID，直接在浏览器中访问该ID的页面就可以看到未授权目录下页面的内容。

**Comment by star7th** [comment]
其实这是个已知的问题。当时做这个功能的时候，只是简单地筛选展示出用户有权限的目录。一般同一个项目的成员里，我觉得权限可以不那么严格。对方都能利用id了，摆明是一个有贼心的用户，那为何把他加为成员呢。

wgege <notifications@github.com> 于2020年10月22日周四 上午10:13写道：

**Comment by star7th** [comment]
假如要做很严格的话，挺麻烦的。比如说新建编辑页面/目录等等全部地方都加一层判断，可能影响程序性能。

Chen Xing <xing7th@gmail.com> 于2020年10月22日周四 上午10:17写道：

**Comment by star7th** [comment]
如果不是项目成员，则会非常严格地不可访问。如果是项目成员，权限判断就没那么严格。一般情况下用户不知道id

Chen Xing <xing7th@gmail.com> 于2020年10月22日周四 上午10:18写道：

**Comment by wgege** [comment]
@star7th 万分感谢大佬回复，我们的使用场景是这样的：
想用showdoc做一个文档中心，用来管理我们产品的文档，每个产品会创建一个item，然后将产品的所有文档放进去release给客户，但是文档分成了公开文档和授权文档两部分，授权部分的文档只有添加了授权目录权限的客户才能看到。而我们的文档ID基本上是顺序的，机灵点的客户如果发现这个规律就可以通过ID看到所有的文档了，哈哈
