### ISSUE TITLE
Tag 5.6-apache not found in repository docker.io/library/php

### ISSUE THREAD

**Issue by Leibosite** [star7th/showdoc#114]
I use docker to install showdoc , when run command "docker build -t showdoc ./", 
result "
Sending build context to Docker daemon 8.351 MB
Step 0 : FROM php:5.6-apache
Pulling repository docker.io/library/php
Get https://registry-1.docker.io/v1/repositories/library/php/tags/5.6-apache: EOF
"
what should I do ?

**Comment by star7th** [comment]
Maybe try another  mirror source clould be helpful
