### ISSUE TITLE
超过6k的项目无法保存。

### ISSUE THREAD

**Issue by Zeng-QJ** [star7th/showdoc#1140]
问题：无论是页面，还是贴图超过6k的都无法保存。保存的时候弹出空白提示框。小于6k的可以保存。
环境：phpstudy构建的windows服务器。
问题截图：
![图片](https://user-images.githubusercontent.com/60689366/97405732-174ed180-1933-11eb-9dde-3b934fce0a3f.png)

**Comment by star7th** [comment]
先看看网络返回的内容是什么

Zeng-QJ <notifications@github.com> 于2020年10月28日周三 下午3:35写道：

**Comment by Zeng-QJ** [comment]
![Uploading 图片.png…]()

**Comment by star7th** [comment]
看不到图

**Comment by Zeng-QJ** [comment]
图重新提交了。返回的是“没有权限”

**Comment by star7th** [comment]
估计要么就是符号特殊，要么就是超过php使用内存。

**Comment by Zeng-QJ** [comment]
确认是大小限制。手动调整内容，超过6k，就无法保存。删减内容少于6k，又可以保存了。如果是PHP使用内存限制，需要如何调整

**Comment by star7th** [comment]
搜索下网络就有答案

Zeng-QJ <notifications@github.com> 于2020年10月28日周三 下午4:08写道：

**Comment by Zeng-QJ** [comment]
![图片](https://user-images.githubusercontent.com/60689366/97409016-ea50ed80-1937-11eb-8ed1-34ca34df9317.png)

**Comment by star7th** [comment]
哎，这种基础性的问题就自行搜索解决就好

Zeng-QJ <notifications@github.com> 于2020年10月28日周三 下午4:09写道：

**Comment by Zeng-QJ** [comment]
php.ini中的 memory_limit这个配置改过了，修改配置之后也重启了Nginx的服务，但是没有效果。所以不能确定是否是这个配置的原因。

**Comment by Zeng-QJ** [comment]
![图片](https://user-images.githubusercontent.com/60689366/97434168-9525d380-1959-11eb-87ce-6383fd5a710f.png)

**Comment by Zeng-QJ** [comment]
贴图的报错
![图片](https://user-images.githubusercontent.com/60689366/97436687-56921800-195d-11eb-9f8a-9e59170c8119.png)

**Comment by star7th** [comment]
php和nginx本身也有个上传大小限制。尝试设置
