### ISSUE TITLE
分享项目给团队时出现空白

### ISSUE THREAD

**Issue by lbj239548** [star7th/showdoc#1142]
我在分享项目给团队的时候，出现空白界面
![20201016233210440](https://user-images.githubusercontent.com/66671099/97647187-8ee44400-1a8c-11eb-9048-f4bed70f5422.png)

**Comment by star7th** [comment]
先看看网络请求返回啥

lbj239548 <notifications@github.com> 于2020年10月30日周五 上午8:48写道：

**Comment by lbj239548** [comment]
{"error_code":10303,"error_message":"\u4e0d\u662f\u9879\u76ee\u521b\u5efa\u8005"}{"error_code":10103,"error_message":"request fail"}

**Comment by lbj239548** [comment]
出现上面这段错误代码

**Comment by star7th** [comment]
你先试着升级到最新版，看看还有没有这个问题

**Comment by lbj239548** [comment]
已经升级了最新版本，还是有这个问题

**Comment by star7th** [comment]
我现在改了下代码，让它能正常显示错误了。根据你上面说得返回结果，你是因为有一个项目缺少权限。目前你只能分配你自己创建的项目。

lbj239548 <notifications@github.com> 于2020年10月30日周五 下午2:42写道：
