### ISSUE TITLE
本地运行访问TypeError: $export is not a function

### ISSUE THREAD

**Issue by rboleynl** [star7th/showdoc#1144]
本地npm run dev访问前端页面报错；
网上搜索：解决如下：
https://stackoverflow.com/questions/43222249/webpack-2-3-3-typeerror-export-is-not-a-function

webpack.base.config.js修改为
{
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test')]
      }

**Comment by star7th** [comment]
我没有看到有这样的报错说“TypeError: $export is not a function ” 。请升级到最新版看看。如果还有问题请截图。

**Comment by rboleynl** [comment]
@star7th 我mac升级了，xcode也升级了还有npm升级，我本地clone了项目(以前一直都没问题)，pull最新版测试了，现在有问题，应该是升级导致，这个问题不算是问题，只是希望碰到同样问题的人有个参考
