### ISSUE TITLE
私密项目改成公开项目后，创建者没有出现在线编辑等按钮

### ISSUE THREAD

**Issue by alinaTing** [star7th/showdoc#1145]

**Comment by star7th** [comment]
刚才测试了下，没有重现到这个问题。如果你坚持有这个问题，请提供外网可重现链接。

alinaTing <notifications@github.com> 于2020年11月2日周一 下午3:39写道：

**Comment by alinaTing** [comment]
什么情况下项目右上角没有设置的图标按钮

**Comment by star7th** [comment]
不是创建者的情况。

alinaTing <notifications@github.com> 于2020年11月2日周一 下午3:46写道：

**Comment by star7th** [comment]
还有就是归档后的项目或者runapi项目，都是只读的。

Chen Xing <xing7th@gmail.com> 于2020年11月2日周一 下午3:46写道：

**Comment by alinaTing** [comment]
那runapi点击获取验证码的时候提示 你所用的showdoc服务器版本过旧，请联系网站管理员升级新版，，假设这个没有及时更新，那我runapi上的项目就不能编辑？

**Comment by star7th** [comment]
runapi项目只能再runapi里编辑，无法在showdoc里编辑。另外，runapi客户端是热更新的，需要相应的版本的showdoc以支持新功能。

alinaTing <notifications@github.com> 于2020年11月2日周一 下午3:52写道：

**Comment by alinaTing** [comment]
那能快速的把runapi上的项目修改成showdoc上面直接创建的项目一样吗

**Comment by star7th** [comment]
不能，两者储存的数据格式不一样。

alinaTing <notifications@github.com> 于2020年11月2日周一 下午4:01写道：

**Comment by alinaTing** [comment]
那如果我模拟showdoc上的文件路径去编辑runapi上的项目，还是可以修改成功和创建成功，那通过这样创建的接口是存哪种数据格式

**Comment by star7th** [comment]
我也不知道， 因为我没这样试过，也不推荐用户这样做。可能的后果是会毁掉数据。

alinaTing <notifications@github.com> 于2020年11月2日周一 下午4:10写道：

**Comment by alinaTing** [comment]
临时需要文档，runapi又登不上，只能这样处理了 ，hhhhhh

**Comment by star7th** [comment]
升级showdoc只需要几分钟而已。

alinaTing <notifications@github.com> 于2020年11月2日周一 下午4:14写道：

**Comment by star7th** [comment]
你问得来，这功夫都升级完了。

Chen Xing <xing7th@gmail.com> 于2020年11月2日周一 下午4:16写道：

**Comment by alinaTing** [comment]
搭建环境的人不在，线上升级了，但是本地环境没有升级

**Comment by qianmengkk** [comment]
@star7th 自己服务器上搭建的showdoc客户端如何热更新，一直提示版本过旧无法登录客户端

**Comment by qianmengkk** [comment]
@star7th 有无命令
