### ISSUE TITLE
RunApi未保存的接口会在切换功能栏以后丢失

### ISSUE THREAD

**Issue by Beancc** [star7th/showdoc#1147]
在RunApi中，新建的接口都写好了，也测试过接口了，这时候如果没保存接口，切换功能栏到“项目”或者“团队”以后，再回到接口页，未保存的接口会丢失，重置到demo接口。希望这一点可以改进一下。

**Comment by star7th** [comment]
为了提高运行效率，不打算在内存里塞那么多数据，会很慢的。所以切换项目后，不再留着上一个项目的数据。

Beancc <notifications@github.com> 于2020年11月3日周二 下午4:01写道：

**Comment by Beancc** [comment]
OK了解了，谢谢答复。
