### ISSUE TITLE
纯markdown文档，没选目录也能保存

### ISSUE THREAD

**Issue by YouLiLiao** [star7th/showdoc#1148]
如题，关键是保存之后找不到了，目录里面也没有，但是在预览文档搜索的时候可以搜出来，算是bug吗
![image](https://user-images.githubusercontent.com/11286354/97994135-f1886780-1e1f-11eb-8dc9-d1bbf31d7395.png)

**Comment by star7th** [comment]
似乎是个bug。默认情况下新建的页面/接口保存到当前选中的目录下。应该是判断当前选中的时候出了问题。你点击左侧菜单，指定选中一个目录就好。

YouLiLiao <notifications@github.com> 于2020年11月3日周二 下午10:00写道：

**Comment by star7th** [comment]
我后面看下。

Chen Xing <xing7th@gmail.com> 于2020年11月3日周二 下午10:30写道：

**Comment by star7th** [comment]
翻到了这个问题。应该是某次发版的时候修复了。
