### ISSUE TITLE
在showDoc创建的项目在runAPI里面不会显示

### ISSUE THREAD

**Issue by Beancc** [star7th/showdoc#1149]
工具是本地部署的。
有个问题，在runApi客户端创建的项目，在网页版刷新一下就可以同步，但是在网页新建项目以后，在runAPI客户端里面无论是刷新还是重启都没有这个项目。

**Comment by star7th** [comment]
runapi的数据可以生成markdown格式，但不可逆，markdown数据很难再转换回来runapi。所以它无法跟showdoc原有数据互相转换。只是它们可以共用文档浏览/团队协作等功能。同时runapi生成的文档只能在runapi上编辑，不能在showdoc上编辑。后面如果要做数据共用，可能需要对showdoc编写格式有一定的规范约束，这个后面再探索下。
