### ISSUE TITLE
删除的项目可以恢复吗等五个问题

### ISSUE THREAD

**Issue by Beancc** [star7th/showdoc#1150]
1. 删除的项目不可恢复，之后是否会考虑增加恢复功能？
2. 接口是否考虑增加跨项目克隆或者移动？
3. postman导出的项目，在runApi导入的时候无法把参数导入成功，是否会修改这个功能？
4. 新建团队添加成员时，网页版可以通过下拉框进行选择，但是runApi却要手动输入用户名，能否改进？
5. 只有网页版的单页项目可以使用数据字典模板或自定义模板，带目录的项目添加markdown文件时可否增加模板功能，以及表格能否也创建在目录下面？

**Comment by star7th** [comment]
1，暂时未考虑。删除项目的时候已经用密码验证并且警告不可恢复。
2，后面会考虑
3，你提供下postman的源文件json给我分析下
4，用户名不打算模糊输入。因为runapi客户端也给官方用，官网不能把用户名全暴露出来。
5，带目录的项目有模板功能，我不知道你是怎么操作的。

Beancc <notifications@github.com> 于2020年11月4日周三 下午5:17写道：

**Comment by Beancc** [comment]
公司环境不太方便提供json，非常感谢解答。
