### ISSUE TITLE
希望增加树形视图

### ISSUE THREAD

**Issue by swtseaman** [star7th/showdoc#1151]
希望可以增加树形视图，项目太多，每次查看另以个项目的文档要回到项目界面

**Comment by star7th** [comment]
可能需求有点小众？为了小众改变交互方式可能不要好。你可以右击，新窗口打开项目。

swtseaman <notifications@github.com> 于2020年11月5日周四 上午9:25写道：

**Comment by swtseaman** [comment]
不是要改变，是增加一种视图选择

**Comment by star7th** [comment]
还是建立新窗口打开。这样不需要反复返回。

swtseaman <notifications@github.com> 于2020年11月5日周四 下午3:51写道：

**Comment by star7th** [comment]
还是建议新窗口打开。这样不需要反复返回。

Chen Xing <xing7th@gmail.com> 于2020年11月5日周四 下午3:53写道：
