### ISSUE TITLE
希望上传的图片和附件，使用相对地址

### ISSUE THREAD

**Issue by zsinba** [star7th/showdoc#1152]
你好，我在使用过程中，上传的图片和附件，都是使用了绝对地址，这样造成一个问题是，我编辑上传的时候，是在内网进行的，用户访问的时候，是通过外网HTTPS://abc.com访问的，造成无法正常显示图片和附件。

希望使用相对地址来保存附件和图片，这样即使即使域名有变化，也不会造成的问题。

多谢。

**Comment by star7th** [comment]
要不要启用相对地址是个问题。首先担心的是对历史的兼容问题。比如说，导出的word，图片附件地址就是错的。这个后面再看看吧。有外网需求的，建议在外网域名下编辑。

zsinba <notifications@github.com> 于2020年11月6日周五 下午2:48写道：

**Comment by zsinba** [comment]
如果是在外网编辑，内网使用外网地址，可能打不开。网络的原因。

不过你说的导出到Word的时候，使用相对地址的确是一个问题，这应该可以导出的时候做修改，这属于代码的事情。
至于兼容性，使用相对地址不是有更好的兼容性吗？

感谢你的建议，在外网下面编辑，的确解决了现在的问题。也引入了新的问题。内网访问不了外网的地址。

所以期望作者能再考虑一下这个情况，使用绝对地址的确不是好的选择，既然没有内外网的问题，也有可能换域名或者换IP，最终还是出问题，而且挺大一问题。

**Comment by star7th** [comment]
相对地址太容易出问题了。只要用户不处于根目录就可能出问题。

zsinba <notifications@github.com> 于2020年11月10日周二 下午6:38写道：

**Comment by star7th** [comment]
换域名的话，就建议改一下数据库。其实我是建议有外网需要的，要么用外网编辑，要么使用云储存，url就很固定了。

Chen Xing <xing7th@gmail.com> 于2020年11月10日周二 下午6:40写道：

**Comment by zsinba** [comment]
很感谢你的showdoc，但是不太同意你的观点。我认为使用绝对地址，绝对不是一个好的处理办法。
“相对地址太容易出问题了。只要用户不处于根目录就可能出问题。" ,  编辑页面是用户在web上面进行的，是当前页面编辑当前的内容，即使你把上传内容独立列表出来，也是放在他该放的位置呀。为什么说用户不处于根目录呢？

**Comment by yixuan1912** [comment]
很遗憾对于不能使用相对位置.....
