### ISSUE TITLE
设置密码项目，为什么当设置为单页分享的时候不用密码访问？

### ISSUE THREAD

**Issue by mrjeke** [star7th/showdoc#1153]
当前设置需要密码的私密项目。分享创建的单页面地址却为什么不需要输入密码验证呢？
这是bug还是设计问题？

**Comment by mrjeke** [comment]
直接分享创建的单页面链接居然不需要密码访问？！既然项目需要密码访问，那单独分享的单页面链接那也必须要密码访问啊。

**Comment by star7th** [comment]
我当时想的是，分享出去的单页链接地址本身带有加密性质，不知道地址的人是无法访问的。所以就没加密了。

mrjeke <notifications@github.com>于2020年11月7日 周六下午10:41写道：

**Comment by mrjeke** [comment]
这不可思议的，重点不在于地址加密，重点在于内容加密。

**Comment by star7th** [comment]
你不如说一下你的使用场景。比如说为什么地址加密后，还必须输入访问密码？

mrjeke <notifications@github.com>于2020年11月7日 周六下午10:48写道：

**Comment by mrjeke** [comment]
还是内容泄露问题啊。一个常规项目文档说明，有很多内容页构成，我想分享项目文档里面某一个内容页（不想让别人看见全部项目文档）于是创建单页面地址分享，我只是想让某一些人看到这些内容，但是万一单页面链接被某一些人看了然后乱分享出去了，内容是不是泄露出去了？这时候如果是可以设置密码访问，我就可以立马更新密码，那任何人无法为访问了。

**Comment by star7th** [comment]
在生成单页链接那里，取消勾选，原链接就失效。再点击，则生成新链接。

mrjeke <notifications@github.com>于2020年11月7日 周六下午11:09写道：

**Comment by star7th** [comment]
我还是没看到设置密码的强必要性。

Chen Xing <xing7th@gmail.com>于2020年11月7日 周六下午11:11写道：
