### ISSUE TITLE
返回参数说明的问题

### ISSUE THREAD

**Issue by Kai-1992** [star7th/showdoc#1154]
1. 快速生成返回参数说明的功能，当返回示例中的string类型参数包含HTML标签时，快速生成会失败；
2. 已经根据返回示例快速生成了返回参数说明，当返回示例增删字段后，返回参数说明不会自动更新。建议加一个覆盖更新更能，或者一键删除

**Comment by star7th** [comment]
1，暂不支持html ，主要是 \n 字符
2，程序有点难做到完全自动，当中的细节判断还是人为控制比较好。覆盖更新或者一件删除功能可以考虑

Kai <notifications@github.com> 于2020年11月9日周一 上午9:45写道：

**Comment by star7th** [comment]
已在新版支持一键清空返回参数功能。重启runapi便会自动更新完毕。
