### ISSUE TITLE
runapi可否支持路径变量

### ISSUE THREAD

**Issue by mumuhhh** [star7th/showdoc#1155]
虽然可以用项目变量  但感觉不友好  参数中无法体现

**Comment by star7th** [comment]
你理解中的路径变量是会被如何使用的？

Mr CrazyMu <notifications@github.com> 于2020年11月10日周二 上午10:13写道：

**Comment by mumuhhh** [comment]
POST  /v1/workflow/:id

**Comment by mumuhhh** [comment]
就像postman中的  Path Variables

**Comment by star7th** [comment]
这个看一下需求，看后面有没有其他人反馈需要这个功能

**Comment by mumuhhh** [comment]
好的

**Comment by star7th** [comment]
已支持路径变量。此功能会自动更新到runapi客户端。
