### ISSUE TITLE
最新的docker镜像不支持mackdown导入导出

### ISSUE THREAD

**Issue by runningbeanxl** [star7th/showdoc#1156]
用最新的镜像部署成功
docker pull registry.cn-shenzhen.aliyuncs.com/star7th/showdoc

导出时没有mackdown选项
![图片](https://user-images.githubusercontent.com/42364672/98625349-5ffe8580-234a-11eb-8b3e-d009dd4b24bc.png)

**Comment by star7th** [comment]
更新下你的浏览器缓存

runningbeanxl <notifications@github.com> 于2020年11月10日周二 上午11:47写道：

**Comment by runningbeanxl** [comment]
你好。用浏览器无痕模式试了也是不行

**Comment by star7th** [comment]
我刚才直接拉取了最新镜像，docker pull registry.cn-shenzhen.aliyuncs.com/star7th/showdoc 是正常的。我不知道你是怎么做的。如果你是升级的话，请严格按照官方教程操作。官方教程的升级方法并不是拉取最新镜像就完事了。

![image](https://user-images.githubusercontent.com/2200494/98635611-4a945600-2360-11eb-8e4d-eec25bbfd782.png)

**Comment by star7th** [comment]
https://www.showdoc.com.cn/help?page_id=65610

**Comment by runningbeanxl** [comment]
我操作一下，非常感谢
