### ISSUE TITLE
项目变量地址&符号会被转义，无法便捷调试

### ISSUE THREAD

**Issue by wangyifani** [star7th/showdoc#1157]
比如下面地址：https://xxx.xxx.xxx/app/index.php?i=1&m=web&c=entry&a=wxapp&do=api&tpp=/
会被转义成：https://xxx.xxx.xxx/app/index.php?i=1&amp;m=web&amp;c=entry&amp;a=wxapp&amp;do=api&amp;tpp=/

**Comment by star7th** [comment]
不支持变量值中写&符号。实际上变量值不支持很多特殊符号。你不要把一整串都做变量。一个一个打散。
