### ISSUE TITLE
生成数据字典,部分表字段趋势

### ISSUE THREAD

**Issue by lovegames** [star7th/showdoc#1158]
用sh脚本生成数据库字典,发现部分表的字段少了很多,这个表字段比较多,是不是对每张表的字段有限制,超过就不会生成了

**Comment by star7th** [comment]
你这个脚本是什么时候下载的？

少年别回头 <notifications@github.com> 于2020年11月11日周三 下午2:19写道：

**Comment by star7th** [comment]
升级showdoc版本+重新下载脚本看看。

Chen Xing <xing7th@gmail.com> 于2020年11月11日周三 下午2:32写道：
