### ISSUE TITLE
您好，导出word版本图片大小宽高全部错乱了请问有解决方法吗？谢谢

### ISSUE THREAD

**Issue by Evaxtt** [star7th/showdoc#1159]

**Comment by star7th** [comment]
导出的样式跟网页样式是不一样的。这个可能没什么好办法。尝试去掉一些特殊字符看看。

**Comment by Evaxtt** [comment]
收到，感谢回复！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "star7th/showdoc"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月12日(星期四) 上午9:30
收件人:&nbsp;"star7th/showdoc"<showdoc@noreply.github.com&gt;;
抄送:&nbsp;"徐婷婷^^"<394012641@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [star7th/showdoc] 您好，导出word版本图片大小宽高全部错乱了请问有解决方法吗？谢谢 (#1159)





 
导出的样式跟网页样式是不一样的。这个可能没什么好办法。尝试去掉一些特殊字符看看。
