### ISSUE TITLE
api接口文档可以将参数值显示出来吗

### ISSUE THREAD

**Issue by wangyifani** [star7th/showdoc#1160]
![image](https://user-images.githubusercontent.com/43734404/98881305-a37cff00-24c4-11eb-9244-8ed6f42c2b31.png)
![image](https://user-images.githubusercontent.com/43734404/98881324-ad9efd80-24c4-11eb-9495-1258a7ba2122.png)

不然好像每个参数的默认值都是需要在描述中提醒呢？
参数前可以增加个是否请求此参数的选择框，更加便于调试
![image](https://user-images.githubusercontent.com/43734404/98881417-e5a64080-24c4-11eb-9e4e-7fa3684beeb2.png)

**Comment by star7th** [comment]
如果自己要显示，在说明描述中展示出来就好。程序不会统一展示。大部分情况不需要展示，所以不会强制所有用户展示。至于那个选择框，后面看看吧。

流氓凡 <notifications@github.com> 于2020年11月12日周四 上午8:57写道：

**Comment by star7th** [comment]
已在新版支持勾选/去掉勾选参数的功能。重启runapi便会自动更新完毕。
