### ISSUE TITLE
RunApi标签页切换问题

### ISSUE THREAD

**Issue by Napoleon1234** [star7th/showdoc#1164]
作者你好：
我在使用您开发的runapi时，现在有4个项目，在项目下拉框切换时，有出现切换不成功的问题（多切换几次），重新加载页面或者重启软件都没办法解决，希望您能看一下是不是我操作不规范引起的？

**Comment by star7th** [comment]
有个类似的问题。https://github.com/star7th/showdoc/issues/1111#issuecomment-727768236  你的项目是不是都比较大啊？

**Comment by star7th** [comment]
另外为防止版本影响，你先把服务端showdoc升级到最新版。

Napoleon1234 <notifications@github.com> 于2020年11月16日周一 下午2:40写道：

**Comment by star7th** [comment]
这个问题解决了。你重启runapi就热更新完毕。此问题主要是当showdoc服务端返回数据慢的时候才会出现。我本地调试以及使用官网都很快，所以一直没发现此问题。
