### ISSUE TITLE
RunApi post请求无法上传文件

### ISSUE THREAD

**Issue by z66232232** [star7th/showdoc#1165]
<img width="734" alt="image" src="https://user-images.githubusercontent.com/6468238/99227183-d8bb8100-2825-11eb-83db-1b04b81f3132.png">

选择file后，提交请求，api中接收到的是空。相同参数使用postman没有问题。
可能是新版问题，之前都正常。今天更新版本到2.8.9后出现的。

**Comment by star7th** [comment]
现在可以了。你重启runapi客户端就会热更新完毕。是增加全局参数功能时候忽略了一些小细节。

**Comment by z66232232** [comment]
可以了。
