### ISSUE TITLE
建议新增Mock功能

### ISSUE THREAD

**Issue by xxzts54cwl** [star7th/showdoc#1166]
建议支持Mock功能

**Comment by star7th** [comment]
其实是有点想在runapi客户端增加mock功能。这个交互得好好想想。

WilliamChen <notifications@github.com> 于2020年11月18日周三 上午9:45写道：

**Comment by xxzts54cwl** [comment]
谢谢回复，期待更新。目前Api接口管理工具没有Mock的话，对外实用性会大打折扣。

**Comment by star7th** [comment]
已在runapi中增加mock功能，在返回参数的选项卡旁边。重启runapi就会热更新完毕。
