### ISSUE TITLE
导入

### ISSUE THREAD

**Issue by aleass** [star7th/showdoc#1167]
你好，请问未来会增加导入功能吗？或者允许本地showdoc同步到服务器的showdoc？
因为我朋友想把家里的showdoc数据存到服务器，虽然可以导出到本地，但是没有导入，只能一个一个复制张贴，他不会编程所以api方式不行

**Comment by star7th** [comment]
showdoc有个导出markdown压缩包功能。可以重新导入showdoc。如果找不到该功能，先升级到最新版。

Tsuki <notifications@github.com> 于2020年11月18日周三 下午2:45写道：
