### ISSUE TITLE
私有化部署showdoc，访问页面偶尔出现页面一直刷新停不下来

### ISSUE THREAD

**Issue by jamelli88** [star7th/showdoc#1168]
docker 私有化部署后的showdoc，访问（任意）页面时会出现一直刷新的情况。但是关闭该页面之后重新打开页面就没有问题

**Comment by star7th** [comment]
当前窗口大小如果发生变化，则会刷新。你是不是装了什么浏览器扩展一直改版当前窗口大小。如果还有问题，请提供外网可重现链接。

Jamel.Li <notifications@github.com> 于2020年11月20日周五 上午10:41写道：

**Comment by jamelli88** [comment]
非也，不单单是我一个浏览器的问题。其他同事也会遇到这样的问题。目前出现问题的浏览器包含（谷歌/QQ浏览器）
该问题不可以稳定重现，但是经常出现，
出现场景：直接访问showdoc地址正常，过段时间刷新一下该地址就可能会出现一直刷新的情况。目前还没有开放外网链接

**Comment by star7th** [comment]
目前没收过这样的反馈。如果是共性问题应该还会有人反馈的。由于我不能重新，只能看谁能提供重现链接给我了。

Jamel.Li <notifications@github.com> 于2020年11月20日周五 上午10:49写道：

**Comment by yangyz** [comment]
我也遇到了这个问题 一直在刷 大概10s左右会好  动下又刷

**Comment by star7th** [comment]
当前窗口大小如果发生变化，则会刷新。你是不是装了什么浏览器扩展一直改版当前窗口大小。如果还有问题，请提供外网可重现链接。
