### ISSUE TITLE
编辑器无法使用

### ISSUE THREAD

**Issue by TangXiaoLv** [star7th/showdoc#117]
如题，用的1.3.2 编辑器上所有按钮点击都无效???

**Comment by TangXiaoLv** [comment]
你的官方演示也不行，都失效了

**Comment by star7th** [comment]
经验证，没有发现问题。请检查你自己的网络以及浏览器兼容

**Comment by TangXiaoLv** [comment]
@star7th chrome 57.0.2987.110

**Comment by star7th** [comment]
我自己测试没问题，也暂时没有收到其他类似反馈。所以我觉得这跟你的本机环境有关。具体原因需要你去排查看看了
