### ISSUE TITLE
arm64上用docker的方式报错

### ISSUE THREAD

**Issue by cnjeffliu** [star7th/showdoc#1170]
Ubuntu18.04.2

报错信息：exec user process caused "exec format error"

**Comment by star7th** [comment]
我印象中，构建所用的基础镜像就不支持arm。

Jeff <notifications@github.com>于2020年11月22日 周日下午11:13写道：

**Comment by star7th** [comment]
官方初步推出了ARM版本的docker镜像。 命令 

docker pull star7th/showdoc:arm-latest

docker run -d --name showdoc --user=root --privileged=true -p 4999:80 \
-v /showdoc_data/html:/var/www/html/ star7th/showdoc:arm-latest 


目前已知的ARM版docker镜像缺陷：
0,只能使用docker官方镜像 star7th/showdoc:arm-latest  ，可能没有大陆镜像加速
1，只支持ARM64位，应该不支持ARm32位.目前在ARM64位的centos7上安装测试已经通过，其他硬件设备由于缺乏测试环境，故尚未测试。理论上ARM64环境都可以兼容。
2，可能无法使用英文版，只能用默认的中文版
3，无法使用mock功能
4，上传图附件到云储存功能尚未测试，且没打算逐一测试各平台，不保证能支持各大云储存
5，导入中文命名的压缩包可能出错。这个问题不打算测试和处理

**Comment by cnzf1** [comment]
@star7th  ok, thanks.
