### ISSUE TITLE
服务器更新完，报错了

### ISSUE THREAD

**Issue by YouLiLiao** [star7th/showdoc#1171]
![image](https://user-images.githubusercontent.com/11286354/99971783-a0ddac00-2dd8-11eb-94ec-2c46630f24ba.png)

**Comment by star7th** [comment]
登录一下网页端。会触发它升级数据库。

YouLiLiao <notifications@github.com>于2020年11月23日 周一下午10:10写道：

**Comment by star7th** [comment]
登录下就行，会自动触发。

Chen Xing <xing7th@gmail.com>于2020年11月23日 周一下午10:12写道：
