### ISSUE TITLE
单页面分享不能全屏查看文档，文档全屏后目录丢失

### ISSUE THREAD

**Issue by gx0803** [star7th/showdoc#1173]
两个问题，如标题所示，希望修复哈，这两个功能还是挺重要的
相关截图：

问题1：
![image](https://user-images.githubusercontent.com/8998033/100207578-b40c8b00-2f42-11eb-9988-121aa82e8ba5.png)
非单页面分享，有放大按钮
![image](https://user-images.githubusercontent.com/8998033/100207714-e0280c00-2f42-11eb-8f01-2b4399293688.png)
单页面分享，放大按钮消失了

问题2：
![image](https://user-images.githubusercontent.com/8998033/100207847-05b51580-2f43-11eb-82dc-87a18b627aea.png)
放大前
![image](https://user-images.githubusercontent.com/8998033/100207893-136a9b00-2f43-11eb-87a8-edd525949667.png)
放大后，目录被隐藏
![image](https://user-images.githubusercontent.com/8998033/100207940-1f565d00-2f43-11eb-8db3-21088068befc.png)
还原后，目录依然没有复原

**Comment by star7th** [comment]
这个后面有时间再看下

**Comment by gx0803** [comment]
> 这个后面有时间再看下

好的，辛苦啦，非常好用的开源工具，期待越来越完善~~

**Comment by star7th** [comment]
已发布新版，解决了此问题。
