### ISSUE TITLE
新增项目保存，出行未知错误

### ISSUE THREAD

**Issue by lingsui** [star7th/showdoc#1175]
![image](https://user-images.githubusercontent.com/9814013/100321261-5c7f2580-2ffd-11eb-8d4b-2a453a3cab70.png)
![image](https://user-images.githubusercontent.com/9814013/100321296-6dc83200-2ffd-11eb-9cdc-e461151e8a83.png)

**Comment by star7th** [comment]
你如果更新过showdoc服务端，那么，要先登录下网页端以自动触发升级数据库的脚本。

**Comment by lingsui** [comment]
谢谢大佬的回复，网页端是那个链接，我是docker私有化部署

**Comment by star7th** [comment]
别我说你安装showdoc以来从来没登陆过showdoc网页端

**Comment by lingsui** [comment]
账号退出，重新登录？没有特殊的链接，哈哈
