### ISSUE TITLE
图片上传失败

### ISSUE THREAD

**Issue by pierswu** [star7th/showdoc#1177]
我这边是私有化部署的，今天刚刚更新到最新版本，之前一直用的是4月份的版本。
升级后发现上传图片的功能不能使用了
看了一下浏览器的network标签，发现是
http://192.168.1.81:4999/server/index.php?s=/api/page/upload这个请求返回内容是：string(27) "文件上传保存错误！

请问这个问题要怎么排查

![QQ图片20201127115724](https://user-images.githubusercontent.com/13825994/100409788-be946500-30a7-11eb-9ca8-20bf3333f5e7.png)
![QQ截图20201127114530](https://user-images.githubusercontent.com/13825994/100409802-c3591900-30a7-11eb-831b-00879f91c85a.png)

**Comment by star7th** [comment]
有给目录777权限了吗

pierswu <notifications@github.com>于2020年11月27日 周五上午11:48写道：

**Comment by star7th** [comment]
你是脚本自动安转还是docker？  给那个挂载的目录递归777权限。我记得文档里是有命令的。请严格按照文档说的升级。

Chen Xing <xing7th@gmail.com>于2020年11月27日 周五下午12:01写道：

**Comment by pierswu** [comment]
我的是脚本自动安装的，挂载的目录是这样的。我有疑惑的地方是，我的系统中没有uid=100 和 gid = 101的用户，是不是和文件的owner有关？我没有注意以前的是怎么样的
![QQ截图20201127121153](https://user-images.githubusercontent.com/13825994/100410458-c35a1880-30a9-11eb-8933-9bb081522023.png)

**Comment by star7th** [comment]
这些数字是正常的。是docker里面的用户。你给777权限就对了。另外在网页端退出再重新登录试试

pierswu <notifications@github.com>于2020年11月27日 周五下午12:13写道：

**Comment by star7th** [comment]
图片你是用默认保存在本地服务器还是用了云存储，另外新建项目功能正常吗

Chen Xing <xing7th@gmail.com>于2020年11月27日 周五下午12:15写道：

**Comment by pierswu** [comment]
图片用的是本地，新建项目正常，也退出再重新登录过了

**Comment by star7th** [comment]
换常见的小图片文件试试。不知道是不是文件本身的问题，比如大小，格式

pierswu <notifications@github.com> 于2020年11月27日周五 下午2:18写道：

**Comment by pierswu** [comment]
升级之前写文档的时候上传成功的图片，升级后也不能上传

**Comment by star7th** [comment]
我刚才试了下用最新版docker镜像安装了下，是可以正常上传图片的。不是很清楚你的问题。你尝试上传附件等非图片文件看看。另外留意磁盘有没有满。

**Comment by pierswu** [comment]
都不能上传，我试试重装吧。

**Comment by pierswu** [comment]
重装后可以上传了
