### ISSUE TITLE
私服showdoc和runapi的https地址连不上

### ISSUE THREAD

**Issue by DreSunny** [star7th/showdoc#1178]
![image](https://user-images.githubusercontent.com/23360125/100437944-7f343b80-30dc-11eb-97f1-e0e7da648b86.png)

**Comment by star7th** [comment]
不支持私有证书。必须是浏览器信任的公开证书

Daniel <notifications@github.com> 于2020年11月27日周五 下午6:15写道：

**Comment by star7th** [comment]
或者你使用http协议

Chen Xing <xing7th@gmail.com> 于2020年11月27日周五 下午6:55写道：
