### ISSUE TITLE
showdoc 最高支持php哪个版本？

### ISSUE THREAD

**Issue by guangsnow** [star7th/showdoc#1179]
1、目前采用的版本是7.3.4 ，通过phpstudy部署。
2、因公司漏洞扫描工具扫描环境存在漏洞，需要切换到高版本的php，切换到7.3.25 和8.0.0等版本均报错。

请问showdoc最高支持php哪个版本

**Comment by star7th** [comment]
我记得是支持到php7.4的。你把错误信息发下

guangsnow <notifications@github.com>于2020年11月30日 周一下午3:08写道：

**Comment by guangsnow** [comment]
[](url)
![image](https://user-images.githubusercontent.com/35698738/100580025-2a810280-3320-11eb-9469-24ce60a8af44.png)

**Comment by guangsnow** [comment]
切换到7.3.4的版本是可以访问的。

**Comment by star7th** [comment]
喂，这跟php版本有什么关系。纯粹是没安装php的sqlite扩展。

guangsnow <notifications@github.com>于2020年11月30日 周一下午3:25写道：

**Comment by guangsnow** [comment]
![image](https://user-images.githubusercontent.com/35698738/100580595-328d7200-3321-11eb-9980-28220f7ee56e.png)
相关的扩展已安装好了。

**Comment by guangsnow** [comment]
请问除了已安装扩展，还需要安装哪些？

**Comment by star7th** [comment]
你打印phpinfo看看是不是真的包含sqlite扩展了

guangsnow <notifications@github.com> 于2020年11月30日周一 下午3:40写道：

**Comment by star7th** [comment]
我刚用phpstudy试了下，用其最高的版本php7.4开启sqlite后可以正常访问。你说的版本似乎不是软件内置的版本。如果你是自定义安装php版本，那理所当然的软件不会帮你安装好扩展。应该也需要自己安装。

**Comment by zingkingcn** [comment]
> 我刚用phpstudy试了下，用其最高的版本php7.4开启sqlite后可以正常访问。你说的版本似乎不是软件内置的版本。如果你是自定义安装php版本，那理所当然的软件不会帮你安装好扩展。应该也需要自己安装。

![image](https://user-images.githubusercontent.com/16666381/101614098-7e3dcb00-3a47-11eb-9538-effa1a55ed6a.png)
这个打印应该是开启了 sqlite3
但是还是报错
![image](https://user-images.githubusercontent.com/16666381/101614174-94e42200-3a47-11eb-91bf-002d8d289da1.png)

**Comment by zingkingcn** [comment]
一定加 extension=pdo_sqlite
不是  extension=sqlite3

**Comment by leochen12-rgb** [comment]
我在安装完成PHP出现此问题解决方法如下
cd /usr/local/lib
mv libsqlite3.so.0 ./libsqlite3.so.0.back
rm -f libsqlite3.so.0
