### ISSUE TITLE
强烈建议

### ISSUE THREAD

**Issue by MatthewLv** [star7th/showdoc#118]
强烈建议加个评论功能。

**Comment by star7th** [comment]
详细说说你在什么场景下需要用到它？

**Comment by MatthewLv** [comment]
因为我们是做成接口文档给别人看的,如果加上了这个功能别人就可以在我们的接口文档上面,填写他们的意见.
最好是可以在每一篇文档上面可以勾选是否开启评论功能

**Comment by weijer** [comment]
自己加呗

**Comment by wingmeng** [comment]
感觉没多大必要，接口文档是面向团队开发人员的，本身具有专业、规范和统一的特性，不像设计图那样需要收集意见、讨论界面来集思广益。如果大家在某个接口上存在争议，大可用其他方式来讨论沟通，用 showdoc 来“撕逼”，已经超出它的设计初衷了。
