### ISSUE TITLE
附件地址问题

### ISSUE THREAD

**Issue by phynos** [star7th/showdoc#1180]
你好，我使用docker部署和nginx反向代理，并把文件放入到二级目录，具体参数如下：
-v /showdoc_data/html/tale:/var/www/html/   star7th/showdoc
此时，访问showdoc基本功都没问题，但是上传附件无法访问，具体原因如下图：
![image](https://user-images.githubusercontent.com/17548559/100686628-ac713a00-33b9-11eb-813d-ef489a647f5a.png)

不知道有没有地方可以配置图片附件的地址前缀？

**Comment by star7th** [comment]
看不到参数。另外请确保按照官方教程进行docker部署。自己自定义安装的，可能我没有时间帮你排查bug

**Comment by phynos** [comment]
原始部署要求有一个独立的端口用来访问，不然会地址冲突
实际肯定要统一由nginx反代（最外层会统一处理https，然后内部http访问），但是没看到官方可以设置附件地址前缀和host的配置说明，我自己找了下源码，也没有找到，只看到最终会调用 attachment->upload这个方法，但是没找到具体实现（我不是很懂php）

**Comment by star7th** [comment]
就按照原始部署。别折腾。然后nginx转发到4999端口。 配置nginx转发的时候记得带上代理header等信息，否则上传的图片地址出错。参考这个：
https://github.com/star7th/showdoc/issues/573

贺兰 <notifications@github.com> 于2020年12月1日周二 上午9:50写道：

**Comment by star7th** [comment]
showdoc新版管理后台现在可以配置网站访问url，会作为上传的附件网址前缀。
