### ISSUE TITLE
使用put请求from类型参数无法传入

### ISSUE THREAD

**Issue by qianbidao** [star7th/showdoc#1181]
put传参请求截图
![image](https://user-images.githubusercontent.com/48899426/100719917-38a25200-33f8-11eb-8d27-db2ab5ec9073.png)
以下是post传参请求
![image](https://user-images.githubusercontent.com/48899426/100720044-66879680-33f8-11eb-9c83-5bcdc6f31599.png)
至于其它请求我还没有测试

**Comment by star7th** [comment]
在图1里，你勾选的是json类型参数，这个时候form参数是不会传过去的

qianbidao <notifications@github.com> 于2020年12月1日周二 下午5:14写道：

**Comment by qianbidao** [comment]
![image](https://user-images.githubusercontent.com/48899426/100720620-3f7d9480-33f9-11eb-83a6-572a5b3929c9.png)
截图有些问题

**Comment by star7th** [comment]
如果是包含文件的,确实只考虑到post请求的情况。pul的话不含文件应该是没问题的。对文件的兼容后面再弄下。

qianbidao <notifications@github.com> 于2020年12月1日周二 下午5:19写道：

**Comment by qianbidao** [comment]
runapi是在哪儿发布release的,我好像只看到官网文档中的下载地址

**Comment by star7th** [comment]
runapi只能去官网下载。它会自动热更新的。更新时候不需要用户操作。

qianbidao <notifications@github.com>于2020年12月1日 周二下午5:28写道：

**Comment by qianbidao** [comment]
好的

**Comment by qianbidao** [comment]
请观察如下我使用红框框出的两个矩形
![image](https://user-images.githubusercontent.com/48899426/100722881-16123800-33fc-11eb-905d-b2a86d9b7cd4.png)
qing
fileId 使用x-www-form-urlencoded类型表单提交,参数始终为null

**Comment by star7th** [comment]
我这边是能获取到delte方式的参数的。不知道你的代码框架是不是正确的

**Comment by qianbidao** [comment]
使用postman测试可以使用,如何才能清楚我的runapi版本是最新?

**Comment by star7th** [comment]
runapi每次重启都会使用最新版。

qianbidao <notifications@github.com> 于2020年12月1日周二 下午8:20写道：

**Comment by star7th** [comment]
印象中这个问题我在之前某个时间点改了，只是没说。
