### ISSUE TITLE
可以在创建接口增加一个Header吗

### ISSUE THREAD

**Issue by ICLXL** [star7th/showdoc#1182]
![image](https://user-images.githubusercontent.com/30027321/100859745-94d5a680-34ca-11eb-91a4-8787b0b46891.png)

**Comment by star7th** [comment]
你截图的是手写？手写的，你自己加什么都行。如果是想自动生成，用这个https://www.showdoc.com.cn/runapi?page_id=30291

**Comment by ICLXL** [comment]
好吧
