### ISSUE TITLE
导出word是空白的，是什么情况

### ISSUE THREAD

**Issue by czaiq** [star7th/showdoc#1183]
使用的是自己安装的服务器版本，写了一个页面，现在导出word是空白的，是什么情况，版本限制了，还是那个地方没操作对

**Comment by star7th** [comment]
试一下，是所有项目的任意内容都导出不了，还是说只是当前的特殊情况

czaiq <notifications@github.com> 于2020年12月3日周四 下午3:21写道：

**Comment by czaiq** [comment]
都导不出，导出的文档是0k，而且反应很慢

**Comment by czaiq** [comment]
用的最新的版本，windows的服务器

**Comment by star7th** [comment]
额，那应该就是服务器环境问题了。建议使用官方建议的方式安装，比如说自动脚本或者docker镜像。每个人的服务器环境差太多了，我可能没精力一一排查问题

czaiq <notifications@github.com> 于2020年12月3日周四 下午5:15写道：

**Comment by star7th** [comment]
win可以参考这个 https://www.showdoc.com.cn/help?page_id=4087044677189279

czaiq <notifications@github.com> 于2020年12月3日周四 下午5:17写道：

**Comment by czaiq** [comment]
就是用你提供的方式去安装的，那我再试试吧
