### ISSUE TITLE
好卡

### ISSUE THREAD

**Issue by zaq11qaz** [star7th/showdoc#1184]
有个地方又bug 突然就很卡

**Comment by zaq11qaz** [comment]
![image](https://user-images.githubusercontent.com/55392923/101020008-c91f9480-35a8-11eb-810d-26c285386247.png)
这三个特别卡

**Comment by star7th** [comment]
我看了下，你那么多的返回内容，当然卡了。看了这个接口生成的文档，居然要加载1M的数据。加载后还要渲染，代码着色，你不卡谁卡。把返回结果弄小点吧。

![image](https://user-images.githubusercontent.com/2200494/101022593-8d86c980-35ac-11eb-8603-3fef01fcd0f7.png)

**Comment by star7th** [comment]
你在测试环境弄那么多跳相应数据没有太大意义的

**Comment by star7th** [comment]
你在测试环境弄那么多条响应数据没有太大意义的

**Comment by zaq11qaz** [comment]
了解，一般都是一页10条，不大吧

**Comment by zaq11qaz** [comment]
保存点返回值加示例也就2m就会卡吗

**Comment by star7th** [comment]
10条是不多的。但你看一下你每条的结构，单条就很多嵌套，单条就很大了。这种情况弄三四条示例就够了。我觉得这么设计接口是有问题的。在单次接口就返回那么多内容。到时候app用起来也可能会慢。如果用户手机信号不好说不定就卡死了

zaq11qaz <notifications@github.com> 于2020年12月3日周四 下午9:24写道：

**Comment by star7th** [comment]
runapi是保存响应体和返回示例的。所以你这个会是双重负担。

zaq11qaz <notifications@github.com> 于2020年12月3日周四 下午9:27写道：

**Comment by zaq11qaz** [comment]
了解，我这个对象里放map 每一条map里搁一个对象集合

**Comment by star7th** [comment]
理论上2M的文字可以相当于一部小说了。渲染那么多文字，还要着色。而且你同时还打开多个标签，我觉得是很难流畅的。至少runapi没有对此专门优化。

Chen Xing <xing7th@gmail.com> 于2020年12月3日周四 下午9:28写道：

**Comment by zaq11qaz** [comment]
大文件能把这个着色渲染去了吗，
我复制拿网页格式化也行，
主要一页十条是标准

**Comment by star7th** [comment]
这个是特殊情况，卡就卡，将就用吧。据我所知很少人会这么设计接口。

zaq11qaz <notifications@github.com> 于2020年12月3日周四 下午9:33写道：

**Comment by star7th** [comment]
我的同事如果这样设计接口会被我怼的。完全没考虑过用户手机信号不好导致app卡死的情况。当中肯定有些字段或者map是不需要的。肯定能减少体积的。

Chen Xing <xing7th@gmail.com> 于2020年12月3日周四 下午9:36写道：

**Comment by zaq11qaz** [comment]
确实，这个是直接把对象拿了用，没用优化，先把项目做出来再考虑优化的问题

**Comment by zaq11qaz** [comment]
卡死不至于，收不到数据500就是了
