### ISSUE TITLE
无法导出word，密码验证功能失效

### ISSUE THREAD

**Issue by ccccccmd** [star7th/showdoc#1185]
最新版，docker部署。
无法导出world，文档加密分享，用密码访问，每次都验证失败。
需要升级docker 镜像么？

**Comment by star7th** [comment]
我感觉是因为docker挂载的目录没有写入权限

**Comment by ccccccmd** [comment]
是777的，密码无法验证这个很迷，管理员的账号密码是好的。

**Comment by star7th** [comment]
你尝试把镜像重新拉起一个容器，不挂载任何目录。看看能使用正常不

**Comment by ccccccmd** [comment]
重新拉了镜像正常了
之前用的 xd2idwf5.mirror.aliyuncs.com/star7th/showdoc 
忘记是什么时候弄的了。谢谢
