### ISSUE TITLE
无法成功调整本地部署版的附件大小限制

### ISSUE THREAD

**Issue by lixiaodao01** [star7th/showdoc#1187]
star7th，您好，我用docker自动脚本在CentOS7.6下本地部署安装的showdoc，由于是最新版本，附件已经能支持到100M了，但考虑到将除了文档还有一些视频文件也需要该系统存储和管理，因此希望将附件大小限制调整为4GB。
系统默认配置中，上传如果上传300M的附件，会在上传进度到33%的时候中断，取消后续的上传。参考bug#571中您的回复，我搜了一下nginx.conf文件，只搜到了docker路径下的该文件，修改了/var/lib/docker/overlay2/6beacb27c308714fbc98f2b9d73ffb79452ffefd1793fb1adf70ad879937e6b6/diff/etc/nginx/nginx.conf中的client_max_body_size 100m为4096m，上传进度条可以上传完成，showdoc中的附件列表也会刷新一下，但最后没法保存成功；我们尝试找php.ini在docker环境下也没找到。

需求：
1. 能否将自动脚本本地部署版中的附件限制调整为4GB或更大，以满足有大文件存储管理的需求，接受收费；
2. 如果1不能实现，能否帮忙看下还有哪些思路或配置文件可以尝试？我们再试试。

辛苦了！谢谢！

**Comment by star7th** [comment]
感觉内存也可能会限制。试着把内存限制放开。我要另外找时间的时候才能测试。现在只能先回复你一下思路

lixiaodao01 <notifications@github.com> 于2020年12月10日周四 下午1:29写道：

**Comment by acracker** [comment]
210M 传不上去, 上传接口 返回200, uploadList 返回空的.

**Comment by star7th** [comment]
我刚更新了下官方镜像。实测已经可以上传600M文件。理论值是5g，但我不确定。不承诺支持那么大的文件吧。
用docker手动安装的人根据经验更新镜像即可。用自动脚本的人，参考这个教程

```
# 先备份数据
cp -r /showdoc_data /showdoc_data_bakup
# cd 到showdoc安装脚本目录，执行卸载旧版镜像
./showdoc uninstall 
# 安装新版镜像
./showdoc 
# 还原代码
rm -rf /showdoc_data
mv /showdoc_data_bakup /showdoc_data
# 升级代码
./showdoc update

```

**Comment by lixiaodao01** [comment]
> 
> 
> 我刚更新了下官方镜像。实测已经可以上传600M文件。理论值是5g，但我不确定。不承诺支持那么大的文件吧。
> 用docker手动安装的人根据经验更新镜像即可。用自动脚本的人，参考这个教程
> 
> ```
> # 先备份数据
> cp -r /showdoc_data /showdoc_data_bakup
> # cd 到showdoc安装脚本目录，执行卸载旧版镜像
> ./showdoc uninstall 
> # 安装新版镜像
> ./showdoc 
> # 还原代码
> rm -rf /showdoc_data
> mv /showdoc_data_bakup /showdoc_data
> # 升级代码
> ./showdoc update
> ```

已使用自动安装方式测试，最大可以支持1G的附件上传，再大仍然会有之前的问题：能完成上传进度，但无法保存成功。对绝大多数场景来说已经完全够用了。谢谢！
