### ISSUE TITLE
插入代码, 复制后空行消失

### ISSUE THREAD

**Issue by huenrong** [star7th/showdoc#1190]
使用```xxxx```插入多行代码时, 若代码中存在空行. 将代码复制并粘贴到其它文档后, 会出现空行消失的情况. 详情见下图
![image](https://user-images.githubusercontent.com/47348530/101977585-5e95e500-3c89-11eb-8bdf-ee1dcb4f8d45.png)

**Comment by star7th** [comment]
感觉这个问题略微麻烦。有时间再处理。

huenrong <notifications@github.com> 于2020年12月12日周六 下午2:51写道：

**Comment by star7th** [comment]
已发布新版，解决了此问题。
