### ISSUE TITLE
建议删除快捷键ctrl+del的绑定

### ISSUE THREAD

**Issue by sssaaa123** [star7th/showdoc#1192]
容易误操作删除

**Comment by star7th** [comment]
不是有确认按钮吗，为什么会误操作。

sai <notifications@github.com> 于2020年12月14日周一 上午4:48写道：

**Comment by sssaaa123** [comment]
我已经删除两次了... ctrl+del删除行当前到行尾文字的时候就弹出删除对话框, 明明按的esc, 也不知道有没有按enter快一点整个文件都删了...也不知道哪里可以找回这个文件..

**Comment by sssaaa123** [comment]
主要是这个快捷键删除文件的需求真的存在吗? 或者说常用吗, 这个快捷键太常用了, 刚才又删了一次, 经常编辑会弹出这个删除对话框

**Comment by star7th** [comment]
后面再清理掉这个快捷键吧

sai <notifications@github.com> 于2020年12月16日周三 下午5:48写道：

**Comment by sssaaa123** [comment]
嗯, 可能比较习惯用这个快捷键, 不留意就按出删除弹窗了
然后一删文件好像就找不回了..有没有类似回收站什么的

**Comment by star7th** [comment]
已在新版解决此问题。
