### ISSUE TITLE
在系统进入首页中新增全局搜索功能

### ISSUE THREAD

**Issue by chanpintong** [star7th/showdoc#1193]
star7th，您好，我用docker自动脚本在CentOS7.6下本地部署安装的showdoc最新版本，系统主页现有搜索功能只能进行主页模块标题的对应字节检索，不能将模块内各个文件内容中的对应字节检索出来。

需求：

能否将系统主页中的搜索功能扩大为全局文件内容的搜索，以满足大量堆叠文件的快速检索功能需求；
如果以上不能实现，能否帮忙看下还有哪些编程思路可以尝试？我们再试试。
辛苦了！谢谢！

**Comment by star7th** [comment]
这是个难题，要兼顾效率做全文搜索是不容易的。万一人家数据多一点呢，官方总不能出一个功能只能适合小数据的时候使用吧。

chanpintong <notifications@github.com> 于2020年12月14日周一 上午9:30写道：

**Comment by Amwsup** [comment]
感觉这个需求还是有必要。
是不是可以在管理员里面加个全局搜索开关选项，默认不能全局搜索，开了就支持。具体开不开管理员可以根据各自需要来设置嘛。

**Comment by lixiaodao01** [comment]
> 
> 
> 感觉这个需求还是有必要。
> 是不是可以在管理员里面加个全局搜索开关选项，默认不能全局搜索，开了就支持。具体开不开管理员可以根据各自需要来设置嘛。

跨项目的资料搜索功能还是挺有必要的。

**Comment by star7th** [comment]
已经在计划中了。我已经想到了一种兼顾性能的方案。

lixiaodao01 <notifications@github.com> 于2020年12月24日周四 上午11:14写道：

**Comment by star7th** [comment]
当用户搜索的时候，只在当前用户有权限的项目中搜索。然后，后台是一个个项目搜索，结果逐个展示。这样应该会性能好一点，不用一股脑全部联合搜索

Chen Xing <xing7th@gmail.com> 于2020年12月24日周四 上午11:15写道：

**Comment by star7th** [comment]
已在最新master分支上传了此功能代码。在我的项目列表页面上方的搜索框，可以在我的有权限的项目中全局内容搜索
