### ISSUE TITLE
配合runapi使用 当响应参数有多个数组时 不能自动生成 还有数组之后可否添加缩进展示 具体看图

### ISSUE THREAD

**Issue by yangyz** [star7th/showdoc#1195]
![image](https://user-images.githubusercontent.com/6257884/102855412-8fcb9d80-445f-11eb-8520-23c9dcd2e6fc.png)

**Comment by yangyz** [comment]
![image](https://user-images.githubusercontent.com/6257884/102855629-f781e880-445f-11eb-83d7-15eb15246a86.png)

**Comment by star7th** [comment]
只会显示第一个数组。因为数组是重复的，不会遍历第二个相同字段名的数组

yangyz <notifications@github.com> 于2020年12月22日周二 下午2:13写道：

**Comment by star7th** [comment]
目前缩进的话，这个比较难判断，后面再看吧

yangyz <notifications@github.com> 于2020年12月22日周二 下午2:14写道：

**Comment by yangyz** [comment]
![image](https://user-images.githubusercontent.com/6257884/102857263-13d35480-4463-11eb-88e7-2c0ff2cc3df1.png)

**Comment by yangyz** [comment]
刚父节点有name 导致子节点就没有name 想添加一行 还的吧之后的全部删掉  

缩进 可以根据 array类型来简单判断

**Comment by yangyz** [comment]
{
  "status": 200,
  "message": "操作成功",
  "data": {
    "id": "1",
    "username": "admin",
    "name": "管理员",
    "menus": [
      {
        "code": "merchant",
        "type": "menu",
        "uri": "/merchant",
        "method": "GET",
        "name": "访问",
        "menu": "商户管理"
      }
    ],
    "elements": [
      {
        "code2": "po:view",
        "type2": "uri",
        "uri2": "/admin/depart/{*}",
        "method2": "GET",
        "name2": "查看岗位",
        "menu2": "部门管理"
      }
    ]
  }
}

**Comment by star7th** [comment]
这个事情不好处理，得后面有时间再看

yangyz <notifications@github.com> 于2020年12月22日周二 下午2:41写道：

**Comment by yangyz** [comment]
还好吧  是数组你就取第一个   不管父节点有没有相同的名字 生成就行了  我觉得到不难  比如上 数组这块 我就拿menus[0]  elements[0] ... 来循环生成行 如果里头还有 menus[0][0] menus[0][0][0]  暂时只支持3层嵌套，估计也差不多了。还有那个添加行的支持 按鼠标焦点来 这样如果有4层或者其他 自己可以灵活天机  要不然一个小地方生成出错了 改动多很大 ，缩进也可以按数组来做标记 不难的 ，暂时可以弄死只支持几层嵌套。

**Comment by star7th** [comment]
我觉得没那么简单的事情，如果你觉得能轻易做到，那你自己做一个。在我看来这是纯后端人员的通病，啥都只想到逻辑，就没想过前端交互的复杂度就超过了后端逻辑复杂度。

yangyz <notifications@github.com> 于2020年12月22日周二 下午2:52写道：

**Comment by star7th** [comment]
增加一行那里，要基于选中行，就是要嵌套。涉及到嵌套的交互哪是一句话的事情。

Chen Xing <xing7th@gmail.com> 于2020年12月22日周二 下午2:59写道：

**Comment by star7th** [comment]
都讲了两次了，我有时间再看。还跟我讲这个很简单。真是不吐槽不行。

**Comment by yangyz** [comment]
好吧 看我这样理解对没 关键是定义好下标   焦点在哪个下标组  然后获取到下标的长度 添加新添加的  重新来生成     下标 比如：现在有 1组 2组 3组  {  1:[ 2:[ 3:[] ] }

**Comment by star7th** [comment]
你说的只是其中一环。但明白逻辑，跟做这个功能出来，存在非常多的细节。你不相信，你可以直接去做一个demo出来，包括前端的交互，比如对字段的增加修改删除，甚至还要考虑后后续别人可能提出的拖曳需求，跨数组拖曳需求。然后把这些结构存储在数据库。生成文档到showdoc的时候还自动转换成markdown。你说只支持三层嵌套，但是后面肯定有人会提出支持更多层的。
另外，如果更改了存储数据结构，那么，要考虑到兼容之前的showdoc版本。否则这样改动后，别人使用旧版showdoc的时候可能会直接用不了。总之一堆细节。

**Comment by star7th** [comment]
比如说如果不细细看兼容性，改动了，像你这样连接了私有版showdoc的用户，会直接用不了runapi。做新功能的时候不能只考虑新功能怎么做，还要考虑跟原来怎么兼容

**Comment by yangyz** [comment]
通用版 全确要考虑方方面面  期待大佬们完善  还是看好你们产品的，其他很多api 多用了 要么做的太复杂 虽然很强大 但学习成本高了。。 轻量好用 才是关键

**Comment by yangyz** [comment]
缩进可以放给用户自己 是不是简单些

**Comment by star7th** [comment]
关于返回参数多层级，最终采用了这种方式 https://github.com/star7th/showdoc/issues/1356
