### ISSUE TITLE
导入postman文件，runapi的参数描述未显示postman同一字段的description

### ISSUE THREAD

**Issue by kobe08242020** [star7th/showdoc#1196]
![Postman](https://user-images.githubusercontent.com/63766273/102871147-06c16000-4479-11eb-862e-d186fc6ea3d2.jpg)
![runapi](https://user-images.githubusercontent.com/63766273/102871265-2c4e6980-4479-11eb-9c22-86652a7cddeb.jpg)

**Comment by star7th** [comment]
这是个bug，等有时间再修正

kobe08242020 <notifications@github.com> 于2020年12月22日周二 下午5:15写道：

**Comment by star7th** [comment]
已发布新版，解决了此问题。
