### ISSUE TITLE
请问新建文档，是否可默认不公开

### ISSUE THREAD

**Issue by deepbluesea99** [star7th/showdoc#1197]
请问新建文档，是否可默认不公开
现在新建文档后，别人默认可访问。还需要加密码设置比较还比较麻烦。
可否文档新建后，默认不公开，需要手动公开或者设置密码公开。
谢谢。

**Comment by star7th** [comment]
文档的私密性继承项目的私密性。你可以进入项目设置把项目改为私密

deepbluesea99 <notifications@github.com> 于2020年12月24日周四 上午9:17写道：

**Comment by deepbluesea99** [comment]
是的，就是项目的私密性默认私密。

**Comment by star7th** [comment]
创建项目的时候加上密码，那么后续的文档都是私密的

deepbluesea99 <notifications@github.com> 于2020年12月24日周四 上午11:23写道：

**Comment by star7th** [comment]
创建项目的时候如果是公开的，那就是默认公开。

Chen Xing <xing7th@gmail.com> 于2020年12月24日周四 上午11:25写道：
