### ISSUE TITLE
请问在哪里可以搜索api

### ISSUE THREAD

**Issue by cyokvip** [star7th/showdoc#1198]
我在runapi里没看到搜索啊，只能在接口文档上搜索吗

**Comment by star7th** [comment]
runapi确实暂无搜索功能，后面有时间再看

CY <notifications@github.com> 于2020年12月25日周五 下午5:16写道：

**Comment by star7th** [comment]
已经在runapi客户端增加接口搜索。重启客户端便可自动升级到最新版。
