### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by zxj95121** [star7th/showdoc#1200]
如果对项目可以分组就好了，项目多了现在显示就很难找。

**Comment by star7th** [comment]
后面再看看要不要对项目进行标签分组过滤

**Comment by lixiaodao01** [comment]
强烈建议可以分组显示，现在有二十多个项目，找起来已经比较麻烦了，后面持续积累几十个项目后不分组的话就很难找了。

**Comment by star7th** [comment]
现在刚给showdoc加了全局搜索功能，在我的项目列表里可以看到搜索框。这种情况下，检索会很方便。不知道项目分组或者标签是否还有必要。你可以说说你的想法。

**Comment by star7th** [comment]
已发布新版，支持了项目分组功能。
