### ISSUE TITLE
统计

### ISSUE THREAD

**Issue by lbj239548** [star7th/showdoc#1202]
麻烦问下，能不能在showdoc里面可以统计我有多少条数据吗

**Comment by star7th** [comment]
没有做可视化功能。自己要看可以进入数据库 Sqlite/showdoc.db.php

lbj239548 <notifications@github.com> 于2020年12月29日周二 下午3:03写道：

**Comment by star7th** [comment]
用 Sqlite工具，不要当文本文件

Chen Xing <xing7th@gmail.com> 于2020年12月29日周二 下午3:04写道：

**Comment by lbj239548** [comment]
您这边有没有什么Sqlite工具呢，

**Comment by star7th** [comment]
自己sous 网络。这跟showdoc无关。

lbj239548 <notifications@github.com> 于2020年12月29日周二 下午3:10写道：

**Comment by star7th** [comment]
自己搜索网络。这跟showdoc无关

Chen Xing <xing7th@gmail.com> 于2020年12月29日周二 下午3:10写道：

**Comment by lbj239548** [comment]
好的，问下是哪个表能够查出统计数据呢

**Comment by lbj239548** [comment]
好的，谢谢了
