### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by 1872306094** [star7th/showdoc#1203]
![image](https://user-images.githubusercontent.com/33020247/103265364-62936800-49e8-11eb-8830-324570989eca.png)

RunApi 软件版本，左侧菜单栏和右侧的内容编辑区，滚动能不能分开，不要一起滚动，左侧菜单很多的话，编辑的时候来回上下滚动很不方便

**Comment by star7th** [comment]
这个后面优化下

By <notifications@github.com> 于2020年12月29日周二 下午3:10写道：

**Comment by star7th** [comment]
忘记说这个问题了。这个应该很早修复了
