### ISSUE TITLE
部署后，打开页面报错 Uncaught (in promise) Error: Avoided redundant navigation to current location

### ISSUE THREAD

**Issue by honwooh** [star7th/showdoc#1204]
![showdoc](https://user-images.githubusercontent.com/46131621/103275789-ea38a100-49ff-11eb-8925-7bfac6a7b781.png)

**Comment by star7th** [comment]
能正常使用吗

honwooh <notifications@github.com> 于2020年12月29日周二 下午6:02写道：

**Comment by honwooh** [comment]
可以使用，就是一直有报错，看着不舒服

**Comment by star7th** [comment]
后面有时间再修复下

**Comment by star7th** [comment]
已在新版解决此问题
