### ISSUE TITLE
当页面放在根目录下时，没有 left_page_xxx 这个id ，导致报错 Cannot read property 'scrollIntoView' of null

### ISSUE THREAD

**Issue by honwooh** [star7th/showdoc#1205]
![sd02](https://user-images.githubusercontent.com/46131621/103276372-4b14a900-4a01-11eb-83f6-cb747ba18187.png)
![sd01](https://user-images.githubusercontent.com/46131621/103276375-4e0f9980-4a01-11eb-8b5d-425f72cbb307.png)

**Comment by star7th** [comment]
这个后面更新功能的时候一并处理下。

honwooh <notifications@github.com> 于2020年12月29日周二 下午6:12写道：

**Comment by honwooh** [comment]
好的，谢谢提供这么好用的开源软件

**Comment by star7th** [comment]
已在新版解决此问题
