### ISSUE TITLE
登录页建议

### ISSUE THREAD

**Issue by yunyongzhang** [star7th/showdoc#1206]
建议弄个新的登录页，增加一些产品化的元素，这样看着更像一个专业的产品，有利于产品化。

**Comment by star7th** [comment]
增加一些产品化的元素——这个描述很抽象。不明白指的是什么。其实设计师有帮我设计过一般暗黑风格的登录页，跟这个差不多，但我没上线。还没想清楚是黑色好还是原来的白色简单好。 https://www.showdoc.com.cn/clients

**Comment by lixiaodao01** [comment]
> 
> 
> 增加一些产品化的元素——这个描述很抽象。不明白指的是什么。其实设计师有帮我设计过一般暗黑风格的登录页，跟这个差不多，但我没上线。还没想清楚是黑色好还是原来的白色简单好。 https://www.showdoc.com.cn/clients

链接里的黑色页面还不如现在的白色的，公司里使用一般不容易接受。
