### ISSUE TITLE
chrome版本 57.0.2987.133 (64-bit)

### ISSUE THREAD

**Issue by divts** [star7th/showdoc#121]
chrome版本版本 57.0.2987.133 (64-bit)浏览器下，编辑文档不兼容，不能更改数据。

**Comment by star7th** [comment]
我的版本是57.0.2987.133 (64-bit)
没发现问题。建议你检查其他原因，如网络是否加载完毕等

**Comment by divts** [comment]
![Uploading 20170421101906.jpg…]()

**Comment by divts** [comment]
http://pan.baidu.com/s/1bT0v3g

**Comment by star7th** [comment]
直接复制编辑内容到https://www.showdoc.cc/ 试试，同时发链接过来

**Comment by dengzgg** [comment]
你好，在你的地址测试了没什么问题，不知道我这边的编辑器怎么会这样，谢谢
