### ISSUE TITLE
新建文档问题

### ISSUE THREAD

**Issue by sealSky-git** [star7th/showdoc#1210]
现在新建文档的时候会出现不是当前文件夹的问题，这个是否可以优化一下，每次都得去选择当前文件夹。

**Comment by star7th** [comment]
新建页面时候，默认使用的是上次选择的目录。

sealSky-git <notifications@github.com>于2021年1月6日 周三上午11:28写道：

**Comment by sealSky-git** [comment]
这样的话有点不方便，因为经常存在跨目录编写文档的时候，默认使用上次选择的目录很容易把新建的文档归到默认目录中

**Comment by star7th** [comment]
后面再看有没有必要优化这方面

sealSky-git <notifications@github.com> 于2021年1月6日周三 下午1:34写道：

**Comment by star7th** [comment]
已发布新版，解决了此问题。
