### ISSUE TITLE
登录后，多个项目托动时可以移位，松开手后，位置回复到原来的位置了，请问可以有别的办法调整吗。

### ISSUE THREAD

**Issue by deepbluesea99** [star7th/showdoc#1214]
登录后，多个项目托动时可以移位，松开手后，位置回复到原来的位置了，请问可以有别的办法调整项目位置吗。

**Comment by star7th** [comment]
理论上是可以保存的，你尝试升级到最新版

deepbluesea99 <notifications@github.com>于2021年1月9日 周六上午11:28写道：

**Comment by acracker** [comment]
我这边的问题是 我改变了顺序,但是其他人看,顺序还是没有变.

**Comment by star7th** [comment]
” 改变了顺序,但是其他人看,顺序还是没有变“是因为顺序保存到数据库没有成功。我严重怀疑也是因为没有升级好。尝试按官网教程升级到最新版

acracker <notifications@github.com> 于2021年1月12日周二 上午10:10写道：

**Comment by deepbluesea99** [comment]
请问在哪里看版本，因为是才下载的，大概应该是最新版本。在设置中未看到版本号。

**Comment by acracker** [comment]
我是上个月月底,全新安装的,docker一键安装的.

**Comment by mini1025** [comment]
我这里，同一个项目，里边的目录，顺序也调整不了，老大帮忙看下

**Comment by star7th** [comment]
当出现问题的时候，留意浏览器网络里返回信息是什么

**Comment by mini1025** [comment]
感谢回复，我这里调整目录顺序，没有保存按钮呀，用的是php5.3,不是docker，是手工部署的

**Comment by star7th** [comment]
@mini1025 当出现问题的时候，留意浏览器网络里返回信息是什么

**Comment by mini1025** [comment]
没有任何异常报错信息，也没有提示，我是这样操作的
1、进出项目
2、点右侧的文件夹图标（新建/管理目录）
3、拖动目录顺序，因为没有保存按钮，拖动后点返回
之间没有返回任何异常

**Comment by mini1025** [comment]
同样的部署，还有一台的php环境是7.4，是正常的。我再切一下php版本再测一下吧，感谢回复

**Comment by mini1025** [comment]
确实是PHP的问题，切换到PHP7.4后（原环境是PHP5.3），目录顺序可以调整了

**Comment by star7th** [comment]
@mini1025 理论上showdoc是支持php5.3的，我刚用php5.3.29试了下，确实是可以的。不清楚你安装的时候是否缺少了什么。不管了，你就用新版php吧。
