### ISSUE TITLE
低版本的PHP存在安全漏洞

### ISSUE THREAD

**Issue by ApuXiong** [star7th/showdoc#1216]
最近公司安全扫描得到以下安全漏洞,能否帮忙更新一下Dockerfile,richarvey/nginx-php-fpm到1.10.4版本.我自己更新重新打镜像导致应用启动失败了.
PHP 7.2.x < 7.2.8 在 EXIF 中释放后使用任意代码执行
PHP 7.2.x < 7.2.13 多个漏洞
PHP 7.2.x < 7.2.14 多个漏洞。
PHP 7.2.x < 7.2.17 多个漏洞。
PHP 7.2.x < 7.2.16 多个漏洞。
PHP 7.2.x < 7.2.18 基于堆的缓冲区溢出漏洞。
PHP 7.2.x < 7.2.19 多个漏洞。
PHP 7.2.x < 7.2.21 多个漏洞。
PHP < 7.1.33 / 7.2.x < 7.2.24 / 7.3.x < 7.3.11 远程代码执行漏洞。
PHP 7.2.x < 7.2.28 / PHP 7.3.x < 7.3.15 / 7.4.x < 7.4.3 多个漏洞
PHP 7.2.x < 7.2.30 多个漏洞
PHP 7.2.x < 7.2.31 / 7.3.x < 7.3.18, 7.4.x < 7.4.6 拒绝服务 (DoS)
PHP 7.2.x / 7.3.x < 7.3.22 内存泄露漏洞
PHP 7.2 < 7.2.34 / 7.3.x < 7.3.23 / 7.4.x < 7.4.11 多个漏洞
PHP < 7.3.24 多种漏洞

**Comment by star7th** [comment]
单纯升级这个基础镜像的版本是不行的。这个基础镜像感觉作者越更新越不好用，所以一直用旧的。我找另外一个时间，换个镜像吧。

ApuXiong <notifications@github.com>于2021年1月11日 周一下午8:38写道：

**Comment by star7th** [comment]
已更换镜像。看最新master代码。或者重新下载官方镜像。
