### ISSUE TITLE
openldap 删除用户之后,系统用户并未被删除

### ISSUE THREAD

**Issue by acracker** [star7th/showdoc#1217]
ldap user filed 这个字段对应着用户管理的 用户名字段,  姓名却没有, 可以增加一个配置吗?

**Comment by star7th** [comment]
openldap删除用户后，showdoc不会删除的。要删除的话自己在管理后台手动。
姓名字段我没有仔细研究过。一般来讲，建议把ldap的用户名设置为名字拼音，这样就不容易弄混了。如果要加的话，需要考虑到通用性。不知道是不是企业的ldap都有姓名字段

**Comment by acracker** [comment]
使用ldap 本来就是方便管理用户, 删除用户这个应该是需要的. 名字那个不重要.

**Comment by star7th** [comment]
目前的机制来看有点做到同步。如果没有很多人反馈这个需求，可能支持不了了。

acracker <notifications@github.com> 于2021年1月12日周二 上午11:13写道：

**Comment by acracker** [comment]
有点难吗? 你刚才的回复应该打掉字了

**Comment by star7th** [comment]
是有点麻烦。

acracker <notifications@github.com> 于2021年1月12日周二 上午11:41写道：
