### ISSUE TITLE
请问LOGO和网页标题在哪里修改，谢谢

### ISSUE THREAD

**Issue by deepbluesea99** [star7th/showdoc#1218]
请问LOGO和网页标题在哪里修改，谢谢

**Comment by star7th** [comment]
不能改。你忽视版权得也太理所当然了吧。showdoc开源出去的是代码和使用权，所有权属于showdoc。

deepbluesea99 <notifications@github.com> 于2021年1月12日周二 上午11:28写道：

**Comment by deepbluesea99** [comment]
请作者勿轻易给人扣帽子，“忽视版权得也太理所当然了” 。
软件的版权介绍，当然是不可以改的。比如各种BLOG和BBS，都有版权申明，也不允许修改这个版权申明 ，如：Powered by Discuz! 。但是，LOGO和网页标题，都是可以改的。比如discuz。
我肯定会尊重你的版权，这软件是你的我只有使用权，没有代码的知识产权。但在大量网页程序约定成俗可以修改网页标题，和LOGO的基础上，我可以接受你不允许修改，我无法接受，我提问一个网页程序改了标题和LOGO，被你认为这是属于侵犯了你的版权。
当然，你可以这么认为，你也可以禁止用户修改网页标题，和网页的LOGO，这是你的权利。这依然尊重你的这个权利。

**Comment by star7th** [comment]
人家是因为有了额外的文字版权声明，所以才可以修改logo和标题。我想保持整洁，所以不想加这么一个东西。默认使用logo和标题以及超链接声明版权。另外对于你认为”大量网页程序约定成俗可以修改网页标题和logo“，我有点不认同。但这个主观性的东西，不讨论了。我使用开源版程序就很少改这个东西。



deepbluesea99 <notifications@github.com> 于2021年1月12日周二 上午11:37写道：

**Comment by deepbluesea99** [comment]
已卸载showdoc, 用 WordPress 重新搭建文档，很自由，也支持WP Githuber MD编辑器。

**Comment by star7th** [comment]
你的使用场景应该不是主用来写api文档，这个时候确实用wp更合适。
