### ISSUE TITLE
增加类似内容流展示的建议

### ISSUE THREAD

**Issue by Amwsup** [star7th/showdoc#1219]
# 场景
- 场景一：
组件1的item下有很多的page(可能是接口、可能是文章)，组件2的item也有多个，但每次变更可能涉及多个组件接口变更，如果要告知团队最新变更内容，经常得提供多个链接地址
- 场景二：
想找一个前两天改的内容，到底在哪个page呢？忘了忘了

# 建议
- 方案一：
    增加一个类似Blog内容流页面（比如127.0.0.1/web/#/blog），进行最近变更内容展示，显示内容如参考展示
- 方案二：
    在首页（localhost/web/#/item）最下面增加内容流展示，进行最近变更内容展示，显示内容如参考展示
- 方案三：
   每个item页面进去默认界面（localhost/web/#/1?page_id=122），不是展示pageid=122，而是展示一个本item的内容流（localhost/web/#/1?blog），显示内容如参考展示

# 参考展示
--【item_1名称】（点这个可以直接链接到对应item内），
----【page名称+更新时间】
--【item_2名称】
----【page名称+更新时间】
> 如何展示page
> - 方案一：
>     按page.addtime倒序显示page(显示3、5条)，（如果考虑权限，可关联team_item_member表，只有登录用户权限范围内的才显示）
> - 方案二：
>     每个page增加一个发布属性（属性也行、新加表也可以），只有发布的，才用于展示。
> - 方案三：
>     方案一、方案二结合

**Comment by star7th** [comment]
其实我很早就有过这个规划。只是它产生了太多数据而被我废弃。当时我的做法是新建item_chage_log表，专门记录项目变更情况，比如说目录的新增修改删除，页面的新增修改删除。展示到一个页面去，就是类似你说的内容流。可能后面还是有必要再重启这个功能。

Amwsup <notifications@github.com> 于2021年1月12日周二 下午12:09写道：

**Comment by Amwsup** [comment]
感谢回答。
我考虑到如果是log的话，的确有太多数据产生，可能用不了几个月log的大小比page的还大。所以提出这么一种折中的方案（直接排序page表）。
如果page原本就很多的话，如果有性能问题（但我觉得不会有性能问题，毕竟不是业务数据，不会海量），考虑只有发布的（写到一个新表），限制这个表只允许每个item存的条数（比如20条），多了的老的删除。

**Comment by star7th** [comment]
新版已经支持项目变更日志。入口在某个项目主页的右侧栏按钮，展开更多。
