### ISSUE TITLE
在centos下一直报错SQLSTATE[HY000]: General error: 11 database disk image is malformed

### ISSUE THREAD

**Issue by eingbol** [star7th/showdoc#122]
我在win环境下安装没有问题，然后我还特意把win下安装成功的showdoc.db.php覆盖在centsos系统上，还是提示这个问题。

**Comment by eingbol** [comment]
我以为是我系统问题，我换了另外一台阿里云上的centos系统，还是这样。

**Comment by star7th** [comment]
Delete the /tmp/debug_kit.sqlite

http://stackoverflow.com/questions/31554588/cakephp-3-x-sqlstatehy000-general-error-11-database-disk-image-is-malformed

**Comment by eingbol** [comment]
这个我已经看过了，tmp目录下根本没有这个文件，我换了好几台系统了

**Comment by eingbol** [comment]
另外安装网上说的修复方法dump出来只有
BEGIN TRANSACTION;
COMMIT;
这样两句话。

**Comment by eingbol** [comment]
pdo_sqlite版本 3.8.10.2

**Comment by star7th** [comment]
说不定你用什么编辑过db文件导致损坏了。比如，如果你用文本编辑器打开，再保存，就会损坏。以及其他原因。
我用阿里云的centos6测试没问题。你试着下载最新的全新安装下

**Comment by eingbol** [comment]
我就是全新安装的。然后我从1.0 1.3 最新版试了好多版本了。难道是我安装的php环境问题。db文件我在本地windows环境下就没有问题了，复制上去就出现问题了。

**Comment by star7th** [comment]
这个问题我也无能为力了。可能是跟环境有关。你试着用阿里云的时候用其他镜像系统

**Comment by chenmaojie** [comment]
我也碰到这个问题，解决不了，也许是SQLLITE存在兼容性问题
建议作者还是同时支持mysql
