### ISSUE TITLE
希望能支持<details>下的summary标签

### ISSUE THREAD

**Issue by soolooqoo** [star7th/showdoc#1224]
希望能支持\<details\>下的summary标签,希望能像下面一样支持修改标题
\<details\>\<summary\>title\<\/summary\>body\<\/details\>
<details><summary>title</summary>body</details>

**Comment by star7th** [comment]
showdoc不承诺支持完善的html语法。这个不是markdown自有功能。实现的逻辑也不简单，所以不打算做。

soolooqoo <notifications@github.com> 于2021年1月14日周四 下午8:56写道：

**Comment by soolooqoo** [comment]
因为不了解前端写法,请问大致在什么地方修改,能稍微指导一下吗?谢谢

**Comment by star7th** [comment]
挺麻烦的，我也是需要看源码才知道哪里改。不建议改。

soolooqoo <notifications@github.com> 于2021年1月14日周四 下午9:17写道：

**Comment by soolooqoo** [comment]
好吧 谢谢

**Comment by wll8** [comment]
可以换个 md 解析器吗？

**Comment by star7th** [comment]
换md编辑器是牵一发动全身，得全方位测试兼容性问题。目前还不打算去弄
