### ISSUE TITLE
可以支持其他格式的附件上传吗?

### ISSUE THREAD

**Issue by acracker** [star7th/showdoc#1225]
因为项目文档可能还有pdf之类的一些文件, 我想把这些文件也传上去,文档里面提供一个超链接啥的.

**Comment by star7th** [comment]
有附件上传功能。项目列表页面——更多——文件库。或者编辑页面——附件。

acracker <notifications@github.com> 于2021年1月15日周五 下午4:10写道：

**Comment by acracker** [comment]
大小限制可以修改吗? 还有就是pdf 不能预览. 我们自己有预览服务接口, 可以配置上去吗?

**Comment by star7th** [comment]
如果是使用谷歌浏览器，打开pdf文件就会预览。修改大小可以查找历史问题。

acracker <notifications@github.com> 于2021年1月15日周五 下午4:20写道：

**Comment by acracker** [comment]
感谢
