### ISSUE TITLE
下载附件没有反应,控制台有报错

### ISSUE THREAD

**Issue by acracker** [star7th/showdoc#1226]
![image](https://user-images.githubusercontent.com/16358913/104703535-6813e080-5752-11eb-8915-84bdb36c954b.png)

**Comment by star7th** [comment]
这个报错跟附件下载没有关系。你可以看下网络请求的返回内容

acracker <notifications@github.com> 于2021年1月15日周五 下午4:55写道：

**Comment by acracker** [comment]
好像是因为我用nginx 转成了https,但是附件下载地址还是http的原因

**Comment by acracker** [comment]
我通过nginx 把服务弄成了https, 插入的附件的时候连接地址地址, 还是http. 我改成Https, 点击文档的超连接一样不能下载.
连接单独打开可以下载

**Comment by star7th** [comment]
你搜索下历史问题看能不能解决。另外我觉得可能我后面是要改一些，不依赖后端判断协议。要改成用前端获取协议然后上传参数。

acracker <notifications@github.com> 于2021年1月15日周五 下午5:02写道：

**Comment by acracker** [comment]
没有找到相关问题呢

**Comment by star7th** [comment]
https://github.com/star7th/showdoc/issues/573

acracker <notifications@github.com> 于2021年1月15日周五 下午5:18写道：

**Comment by acracker** [comment]
那个issue,只是让访问http的时候跳转到对应https链接, 我这里http, https 链接复制出来到浏览器都可以直接下载. 但是点击文档里的连接不行.
示例:
https://doc.gaoyusoft.com/web/#/p/f876616cec5f663aee53a350021623ac

**Comment by star7th** [comment]
不知道这是不是跟你的证书有关。你的是自定义证书，不清楚浏览器会不会做出限制。另外就是你强制http跳转到了https，而https可能证书有问题，可能就这样导致访问不了吧

acracker <notifications@github.com> 于2021年1月15日周五 下午5:41写道：

**Comment by star7th** [comment]
尝试用一个免费https证书试下

Chen Xing <xing7th@gmail.com> 于2021年1月15日周五 下午6:07写道：

**Comment by acracker** [comment]
我本地安装了CA的证书的, 浏览器没有其他提示

**Comment by star7th** [comment]
开一个临时账户给我

acracker <notifications@github.com> 于2021年1月15日周五 下午6:35写道：

**Comment by acracker** [comment]
test/test

**Comment by star7th** [comment]
是浏览器的限制。谷歌浏览器会限制。我用IE试了下能下载。估计是https禁止了http文件的下载。暂时无解。我只能建议你用公认https证书试下。如果不行的话，只能等我有空的时候再更新程序，使用前端判断协议。另外我发现把图片文件当附件上传就是可预览的。

acracker <notifications@github.com> 于2021年1月15日周五 下午6:42写道：

**Comment by acracker** [comment]
文档里面插入的超链接下载地址改成了Https还是不能下载呀.

**Comment by star7th** [comment]
你用IE11试一下。这是浏览器自身的安全限制。IE11没有这个限制。

**Comment by acracker** [comment]
edge 可以正常下载.
