### ISSUE TITLE
Mock生成的URL能否自定义？

### ISSUE THREAD

**Issue by alphaerp** [star7th/showdoc#1229]
star7th  你好，
Mock生成的URL能否自定义？ 这样mock才显示更有意义，随机生成的不敢写在文档上，后期对接后端api, 路径这块改动太大了。

**Comment by star7th** [comment]
这个issue原来没回。mock自定义后面规划下吧，应该是前面一大段url固定，后面允许自定义部分路径

**Comment by star7th** [comment]
已发布新版，支持了改功能。
