### ISSUE TITLE
建议新增编辑审核功能

### ISSUE THREAD

**Issue by ibonker** [star7th/showdoc#123]
成员A编辑了文档，不是立即生效，要经过老大审核后发布。其他成员才可以看到。

**Comment by star7th** [comment]
因这种需求太少而开发成本有点高，所以不打算做。
成员A在编辑文档前后应该找老大过目再确定更新。或者A只有只读权限，统一由老大来更新上线

**Comment by star7th** [comment]
其实这个有点类似开发环境跟线上环境的关系。
你们可以新开一个镜像项目。bate的文档统一更新在这里。更新后找老大过目。老大觉得ok，就复制文本到正式项目中去
