### ISSUE TITLE
Showdoc 文档里面无法黏贴图片的问题

### ISSUE THREAD

**Issue by charlie2009** [star7th/showdoc#1231]
![showdoc](https://user-images.githubusercontent.com/29229817/105137245-fa8afa00-5b2d-11eb-9226-0bd80329330d.png)

**Comment by star7th** [comment]
把url复制出来看看

charlie2009 <notifications@github.com> 于2021年1月20日周三 下午2:44写道：

**Comment by charlie2009** [comment]
![图片](https://user-images.githubusercontent.com/29229817/105138606-155e6e00-5b30-11eb-8dce-b9fe6391097b.png)
![showdoc](https://user-images.githubusercontent.com/29229817/105138636-1db6a900-5b30-11eb-8dc0-472cc2523afb.png)
![showdoc1](https://user-images.githubusercontent.com/29229817/105138638-1ee7d600-5b30-11eb-9a82-e11d7479aa10.png)
showdoc1正常，正式重新部署的showdoc不正常，配置的Nginx里面内容一样

**Comment by star7th** [comment]
把url复制出来，拿到浏览器里访问一下

charlie2009 <notifications@github.com> 于2021年1月20日周三 下午3:00写道：

**Comment by charlie2009** [comment]
![showdoc3](https://user-images.githubusercontent.com/29229817/105138935-8dc52f00-5b30-11eb-8fc6-080856d6fc95.png)

**Comment by star7th** [comment]
应该跟这个是同一类问题。你试着自己手动把url改为https

**Comment by star7th** [comment]
https://github.com/star7th/showdoc/issues/1226

**Comment by songshengping** [comment]
最新版怎么直接黏贴 不显示图片了??之前都可以.(内网docker部署)
![](https://192.168.1.147:4999/server/index.php?s=/api/attachment/visitFile&sign=fe80549931dafd6db930b50a240bcc24)

**Comment by songshengping** [comment]
![Image](https://github.com/user-attachments/assets/f973eb02-b2f3-4097-b605-7859d1f7a974) 这个点查看,都查看你不了

**Comment by songshengping** [comment]
感觉用了重定向....内嵌一样的问题
