### ISSUE TITLE
showdoc 显示可否设置宽度

### ISSUE THREAD

**Issue by g00n1** [star7th/showdoc#1232]
在浏览表格的时候，很明显宽度太短了，需要拖过去，预览很不方便。

**Comment by star7th** [comment]
点击右上的全屏按钮可以大屏预览

g00n1 <notifications@github.com> 于2021年1月21日周四 上午9:08写道：

**Comment by star7th** [comment]
不支持设置宽度。

Chen Xing <xing7th@gmail.com> 于2021年1月21日周四 上午9:18写道：

**Comment by g00n1** [comment]
![image](https://user-images.githubusercontent.com/2044846/106226674-ad401400-6222-11eb-90ad-de6ec82e9b28.png)

**Comment by star7th** [comment]
https://github.com/star7th/showdoc/issues/927
