### ISSUE TITLE
BUG来了

### ISSUE THREAD

**Issue by kussatom** [star7th/showdoc#1233]
DOCKER安装的，编辑内容时，明明是输入的--  ，再次打开就是 —  这个了 ，

**Comment by star7th** [comment]
其实它还是两个 - - ，只是中间的空格去掉了而已

kussatom <notifications@github.com> 于2021年1月21日周四 上午10:04写道：

**Comment by kussatom** [comment]
并不是噢，删除的话一下就删掉了，而不是两下

**Comment by star7th** [comment]
showdoc是用这个开源编辑器的 https://pandao.github.io/editor.md/  但原编辑器的作者不怎么维护了。所以我自维护showdoc的编辑器。但我觉得这个是小问题，可能不值得去钻研编辑器底层。所以我倾向不改了。除非是严重影响到使用的。

**Comment by kussatom** [comment]
嗯，我经常拿来存DOCKER的命令 ，所以这个--经常要用到，每次都要改 也是有点麻烦，实在不行也就将就用了 。

**Comment by star7th** [comment]
放在代码块里就好，看官方是怎么写docker教程的 https://www.showdoc.com.cn/help?page_id=65610

kussatom <notifications@github.com> 于2021年1月21日周四 上午10:23写道：
