### ISSUE TITLE
能否增加个腾讯云的对象存储

### ISSUE THREAD

**Issue by kai0754** [star7th/showdoc#1234]
账户系统基本都在腾讯云了，想看看作者是否有这个计划增加腾讯云的云存储。

**Comment by star7th** [comment]
后面看下有没有必要

kai0754 <notifications@github.com> 于2021年1月21日周四 下午11:45写道：

**Comment by kai0754** [comment]
好的。感谢，觉得阿里云之后应该就是腾讯云了。毕竟很多服务走内网。

**Comment by star7th** [comment]
已发布新版，解决了此问题。
