### ISSUE TITLE
新建页面、目录时，所属目录检索优化建议

### ISSUE THREAD

**Issue by huangmaidi** [star7th/showdoc#1235]
新建页面、目录时，选择所属目录时，是一个下拉框，能否给这个下拉框加一个搜索功能，我们现在项目上百个目录了，选择的时候只能边拉边找，有点不方便。
![image](https://user-images.githubusercontent.com/13467095/105458788-28a24280-5cc4-11eb-83d8-55935f65f9c3.png)

**Comment by star7th** [comment]
这里是会按层级折叠目录的。一般来讲一个项目不会有那么多同一级的目录。你可以优化下项目结构，上百个目录放在同一层是肯定不合理的。建议合理分配层级关系，以及最重要的是划分项目。你这个是可以按模块划分成不同项目的。

huangmaidi <notifications@github.com> 于2021年1月22日周五 下午3:12写道：

**Comment by huangmaidi** [comment]
好的，谢谢，理解你的意思，不过目前确实不太合适我们的实际情况。
