### ISSUE TITLE
目录如何自动展开

### ISSUE THREAD

**Issue by deepbluesea99** [star7th/showdoc#1237]
一直以为文档侧边的目录无法自动展开。但是今天发现在默认的数据
“API文档示例” 中 “用户相关” 目录是自动展开的，未发现在哪里可以设置其它目录的自动展开。
请问如何设置目录的自动展开。
![image](https://user-images.githubusercontent.com/62432612/105652574-8ae18a00-5ef4-11eb-938c-254508cd0c41.png)

**Comment by star7th** [comment]
没有做自动展开的功能
