### ISSUE TITLE
发现一个小bug  可以提交空数据  在新增用户和新建文档时

### ISSUE THREAD

**Issue by ailcc** [star7th/showdoc#1239]
发现一个小bug  可以提交空数据  在新增用户和新建文档时  未做新增限制

**Comment by star7th** [comment]
下次发版再顺带修复此问题

ailcc <notifications@github.com> 于2021年1月25日周一 下午3:31写道：

**Comment by ailcc** [comment]
感谢关注  目前我自己已经手动修复了！感谢源码分享！

**Comment by star7th** [comment]
已在新版解决此问题
