### ISSUE TITLE
怎么修改默认的80端口为其他端口呢

### ISSUE THREAD

**Issue by l97069947** [star7th/showdoc#1241]
如题

**Comment by star7th** [comment]
showdoc是一套程序，并不直接监听端口，而是由nginx或者docker监听端口转发。如果你是用docker安装，是要改docker映射的端口而非showdoc‘的端口。可以上网了解下docker的使用。
docker安装教程 https://www.showdoc.com.cn/help?page_id=65610

**Comment by l97069947** [comment]
> showdoc是一套程序，并不直接监听端口，而是由nginx或者docker监听端口转发。如果你是用docker安装，是要改docker映射的端口而非showdoc‘的端口。可以上网了解下docker的使用。
> docker安装教程 https://www.showdoc.com.cn/help?page_id=65610

我的意思是,比如现在是4999:80 相当于占用了docker里虚拟网路的80端口,那么可不可以修改启动端口80为4999?就是4999:4999

**Comment by star7th** [comment]
不同容器内部的端口互相隔离，可以共用80端口。不需要考虑这个冲突问题。

Liaoweiming <notifications@github.com> 于2021年1月27日周三 上午10:22写道：

**Comment by l97069947** [comment]
好的 谢谢

**Comment by guojingwen** [comment]
确实可以修改为其他端口，但是带了的一个问题是 图片上传后 不显示
![image](https://user-images.githubusercontent.com/12098305/134197702-72a9f454-3292-48a2-ac5a-59037aa7327e.png)

**Comment by star7th** [comment]
官方教程和程序都是默认使用4999端口，如果要改的话自己可以探索。官方不承诺支持用户修改端口。

**Comment by star7th** [comment]
还有就是绑定域名根据这个来，可以不用改端口 https://www.showdoc.com.cn/help/7240953917068087

**Comment by guojingwen** [comment]
个人用自家电脑和宽带搭建了服务器， 
nginx 配置的端口 是 10443 ， 
开放80，和443端口  2万多一年，而且网速还是最差的，不划算

我这可能要二次开发了
