### ISSUE TITLE
runApi创建纯文档后保存再打开按ctrl

### ISSUE THREAD

**Issue by zaq11qaz** [star7th/showdoc#1244]

**Comment by zaq11qaz** [comment]
runApi创建纯文档后保存再打开按ctrl+z会清空
![image](https://user-images.githubusercontent.com/55392923/105948330-b8216a00-60a5-11eb-8635-bbb997e52f3c.png)
![image](https://user-images.githubusercontent.com/55392923/105948351-bce61e00-60a5-11eb-8443-55141f7f981a.png)
也没有提示保存弹窗
若这个时候点了保存是不是就没了

**Comment by zaq11qaz** [comment]
![微信截图_20210127134621](https://user-images.githubusercontent.com/55392923/105948583-249c6900-60a6-11eb-903c-97faa643f8a1.png)
![微信截图_20210127134647](https://user-images.githubusercontent.com/55392923/105948588-26fec300-60a6-11eb-937b-1b743ed02c78.png)

**Comment by star7th** [comment]
我是直接集成了一个第三方开源编辑器，估计是监听了快捷键 crtl z 清空。你不要保存，直接关闭runapi重开吧

zaq11qaz <notifications@github.com> 于2021年1月27日周三 下午1:47写道：

**Comment by zaq11qaz** [comment]
嗷
