### ISSUE TITLE
water mark feature

### ISSUE THREAD

**Issue by siwen1017** [star7th/showdoc#1246]
showdoc will plan to add watermark feature  or not ?

**Comment by star7th** [comment]
Maybe this function will be added later, but I'm not sure.

**Comment by star7th** [comment]
It depends on how many users are needed

**Comment by xrmm** [comment]
强烈建议增加图片水印功能

**Comment by star7th** [comment]
The new version has been released, and the watermark function can be started in the management background.

已经发布新版，可以在管理后台启动水印功能。
