### ISSUE TITLE
希望附件名下载后还是保持原名称.

### ISSUE THREAD

**Issue by acracker** [star7th/showdoc#1247]
> 为了防止别人传入一些特殊字符，所以是重命名后存放的。而附件的链接是直接连文件，不经脚本处理，所以改不了名。 如果要做到这样效果，可以是可以，单会增大服务器和网络资源开销，就先不考虑了。

文件名名称真的真重要呀. 很多文件名称被改了就不能用了,  比较出名的就是python 依赖包,名称一改就用不了.
看了一下 下载连接 是302的文件直链的, 能不能302到一个可以改名字的接口呀.

**Comment by star7th** [comment]
会增大服务器和网络资源开销 ，大文件尤其麻烦。我建议对这种不能改名的场合，你可以压缩存放。这样改名的只是压缩包，里面的文件不会改

acracker <notifications@github.com> 于2021年1月29日周五 上午9:44写道：

**Comment by acracker** [comment]
差不多吧.  浏览器改名, 只需要加一个 `Content-Disposition`的header就行就行了.

**Comment by star7th** [comment]
怎么一样呢。假如一个100M的文件，你必须用程序写进内存里，然后再改header输出。

acracker <notifications@github.com> 于2021年1月29日周五 上午9:58写道：

**Comment by star7th** [comment]
目前是直连文件，由nginx直接返回文件，不经过脚本。像你说的自定义header，就肯定要经过脚本了。这个时候消耗的资源取决于文件大小。大一点的，比如几百M，可能就挂了

Chen Xing <xing7th@gmail.com> 于2021年1月29日周五 上午10:00写道：

**Comment by acracker** [comment]
不会呀. 怎么可能这么2, 一般都是 从文件系统读取 1-1024 的内容, socket发送, 然后继续读后面的,第一次读取就释放了.

**Comment by acracker** [comment]
或者有没有接口根据下载链接能查询到文件名称, 我自己用nginx 去做.

**Comment by star7th** [comment]
我之前处理文件都是直接读入内存处理。原来你想说的是这种读取方式。理论上可行，我后面试一下吧。

acracker <notifications@github.com> 于2021年1月29日周五 上午10:05写道：

**Comment by zhangjingwen2008** [comment]
同    这个被改名的功能影响太大了    我们500强公司的部门就因为这个原因没有直接使用了。

界面精简这一点已经能成为非常大的亮点，使用起来非常的舒服且能够很直观找到自己想要的东西，这非常棒。

但上传文件这方面，由于我们的使用群体属于不是非常了解电脑程序的员工，所以下载后文件名的不同直接影响了体验，也对后续寻找已下载的文件造成了阻碍，强烈建议作者改善。

**Comment by star7th** [comment]
@zhangjingwen2008 已经纳入开发计划了的，不过不会专门做这一个功能。可能下次发版的时候顺带把这个功能带上。

**Comment by star7th** [comment]
已在新版解决此问题。
