### ISSUE TITLE
升级流程不明确。希望更新文档

### ISSUE THREAD

**Issue by mowangjuanzi** [star7th/showdoc#1248]
这是文档描述的：

```
如果你是手动安装环境的，则继续往下看。首先将旧代码目录复制一份以便备份。

全新安装（具体操作参考文档）并初始化ShowDoc完毕后，进入之前备份的目录。将Sqlite/showdoc.db.php（这是原来的数据库文件），以及Public/Uploads/下的所有文件（这些是上传的图片。如没有图片则可忽略之），全部复制并覆盖到新showdoc目录的相应文件。覆盖后重新给这些文件可写权限。
```

但是实际上的升级过程却不是这样。升级流程是：

1. 备份原来的项目目录
2. 部署新的项目内容(不要留有之前的 `showdoc.db.php`)
3. 浏览器访问，选择默认语言，这时会修改PHP的配置等
4. 复制备份文件中的 `showdoc.db.php` 到 `Sqlite\showdoc.db.php`。
5. 浏览器访问地址：`/index.php?s=/home/update/db` 升级数据库结构
6. 完成

**Comment by star7th** [comment]
我没理解你的第二步“ 不要留有之前的 showdoc.db.php”是什么意思。另外第5步已经可以省略，会自动升级数据库结构。

魔王卷子 <notifications@github.com> 于2021年1月29日周五 上午10:47写道：

**Comment by star7th** [comment]
我还是看不懂我原来写的升级流程有什么问题

Chen Xing <xing7th@gmail.com> 于2021年1月29日周五 上午10:50写道：

**Comment by mowangjuanzi** [comment]
我是从 v2.4.3 直接升级到 v2.8.12 的。

我先介绍一下我之前的操作流程：

1. 执行以下命令下载源码：

```bash
git clone https://github.com/star7th/showdoc.git
```

切换分支：

```bash
cd showdoc
git checkout v2.8.12
```

初始化项目，完毕，从备份中复制 `showdoc.db.php` 覆盖项目中的同名文件。

然后再去浏览器中访问，提示：

```
SQLSTATE[HY000]: General error: 1 no such table: item_sort 。错误位置：/Users/baoguoxiao/code/company/showdoc/server/ThinkPHP/Library/Think/Db/Driver.class.php 174
```

手动访问该地址：`http://localhost:7999/index.php?s=/home/update/db` 升级数据库。

再次访问项目。可以正常浏览。

解释下我最开始写的步骤：
- 我说的第二步，括号里面的东西是因为我担心初始化项目会修改原本的数据库文件，所以我才这么写的。
- 第五步并没有按照你期望的自动执行升级程序，而是我手动执行之后才可以。

**Comment by star7th** [comment]
当用户访问登录页面或者项目列表页面的时候，会触发页面请求后台，自动升级数据库脚本。估计是因为你没有进入这两个页面，所以没触发，所以才需要手动升级数据库。我觉得当前的升级流程是没问题的，可能自动触发的机制要改一下。比如说在访问项目主页的时候也触发，不需要用户自己手动执行升级脚本。

魔王卷子 <notifications@github.com> 于2021年1月29日周五 下午2:12写道：

**Comment by mowangjuanzi** [comment]
我访问的是这个页面：`http://examle.com/web/#/item/index`

**Comment by star7th** [comment]
就是这个页面，url没问题。不排除版本差异太大引起的特殊问题。你这个版本时间戳应该有两年吧。普遍上应该没问题，反馈的人不多。

魔王卷子 <notifications@github.com> 于2021年1月31日周日 下午9:17写道：

**Comment by star7th** [comment]
就是这个页面，url没问题。不排除版本差异太大引起的特殊问题。你这个版本时间应该有两年前了吧。普遍上应该没问题，反馈的人不多。

Chen Xing <xing7th@gmail.com> 于2021年1月31日周日 下午9:20写道：

**Comment by mowangjuanzi** [comment]
是的。很久了。得两年了。
