### ISSUE TITLE
runApi中，不同项目之间互相移动API

### ISSUE THREAD

**Issue by 1074191791** [star7th/showdoc#1249]
同项目中移动文件及文件夹是可以的，不同项目之间，想要复制一份同样的API做不到吗？

**Comment by star7th** [comment]
暂不支持跨项目克隆。你可以导出参数复制过去吧

1074191791 <notifications@github.com> 于2021年1月29日周五 下午1:32写道：

**Comment by star7th** [comment]
已经支持此功能。重启runapi就会热更新完毕。
