### ISSUE TITLE
一直提示错误11 database disk image is malformed，建议作者兼容下mysql

### ISSUE THREAD

**Issue by chenmaojie** [star7th/showdoc#125]
一直提示错误：11 database disk image is malformed，解决不了，也许是SQLLITE存在兼容性问题

**Comment by star7th** [comment]
不会再支持mysql.
你的系统版本多少？
有网络搜索相应教程处理过了吗
http://www.cnblogs.com/adinet/archive/2011/11/03/2233858.html

**Comment by chenmaojie** [comment]
这个错误是install之后登录就出现的，按照教程处理也修复不了，没有其它解决办法了吗？

**Comment by nwater** [comment]
项目设置页面，输入项目名、描述、密码后，点击保存无响应。
在数据库中直接修改项目名后，在此页面也没有显示。

**Comment by chenmaojie** [comment]
11 database disk image is malformed终于找到问题的原因了，是因为[<?php] 这个表名称引起的问题，把这个删掉就OK了。
![image](https://cloud.githubusercontent.com/assets/22437642/25219740/f758c19e-25e1-11e7-9cc1-072e9b30095d.png)

**Comment by star7th** [comment]
@chenmaojie <?php这个表是为了防止直接web下载数据库文件的。你在其他方面做好限制防止被下载就好。

**Comment by star7th** [comment]
@nwater 检查自己的nignx规则有没有写对。你说的那个页面，请求的api是请求server目录的。可能是规则没写好导致请求不了数据
