### ISSUE TITLE
Postman的json导入，解析信息很多都缺少

### ISSUE THREAD

**Issue by 402002930** [star7th/showdoc#1251]
字段的数据类型，描述字段都为空

**Comment by star7th** [comment]
你可以把数据脱敏后，提供一个样式json文件，我有空看下格式

Nicolas Carry <notifications@github.com> 于2021年2月1日周一 下午7:01写道：

**Comment by star7th** [comment]
现在已发布了一个新版，对导入格式完善了很多。如果觉得有不足的可以重开issue提供一个样式json文件
