### ISSUE TITLE
markdown 显示bug

### ISSUE THREAD

**Issue by acracker** [star7th/showdoc#1252]
如图:
![image](https://user-images.githubusercontent.com/16358913/106561457-acc9b500-6563-11eb-8380-3dbfdbd7026b.png)
另外可以支持目录吗?

**Comment by star7th** [comment]
test后面加一个空格，或者加多一个换行。目录的话，看编辑器上有个插入TOC目录按钮

acracker <notifications@github.com> 于2021年2月2日周二 下午2:34写道：

**Comment by acracker** [comment]
多换一行就行了.

**Comment by acracker** [comment]
另外就是我怎么清空草稿箱呀? 我明明每次都保存了, 但是每次都提醒我.

**Comment by star7th** [comment]
是最新版吗，不应该有这个问题

acracker <notifications@github.com> 于2021年2月2日周二 下午2:48写道：

**Comment by acracker** [comment]
是新版本, 上周更新的. 这个md比较大.小md 好像没有这个情况了.

**Comment by star7th** [comment]
可能是特殊情况吧，我没怎么遇到此问题，反馈的人也不多

acracker <notifications@github.com> 于2021年2月2日周二 下午2:59写道：

**Comment by acracker** [comment]
小的也一样.

**Comment by star7th** [comment]
请提供外网可重现链接看下。我重现不了

acracker <notifications@github.com> 于2021年2月2日周二 下午3:06写道：

**Comment by acracker** [comment]
[test/test1234](https://doc.gaoyusoft.com/web/#/page/edit/14/54)

**Comment by star7th** [comment]
经测试，在你的站点上也没有发现此问题。
