### ISSUE TITLE
附件可不可以支持大文件上传

### ISSUE THREAD

**Issue by ssjshengjie** [star7th/showdoc#1254]

**Comment by ssjshengjie** [comment]
目前附件只能支持4mb左右的上传 ，10mb以下都可以上传成功，但几百mb的文件 会失败 。可以支持一下吗

**Comment by star7th** [comment]
官方docker镜像可以支持400M+的文件

ssjshengjie <notifications@github.com> 于2021年2月3日周三 下午2:17写道：

**Comment by star7th** [comment]
https://github.com/star7th/showdoc/issues/1187
