### ISSUE TITLE
你好，系统可以支持直接删除项目吗，现在是需要一个个的删除，谢谢

### ISSUE THREAD

**Issue by divts** [star7th/showdoc#126]

**Comment by star7th** [comment]
你的项目数不会多达上百个吧，如果不多，手动删除也没啥问题

**Comment by dengzgg** [comment]
10几个吧，但每个项目里面的接口页面都有五六十个，一个个删确实挺浪费时间的。

**Comment by dengzgg** [comment]
另外，在线测试API功能建议放在查看接口的页面，而不是放在编辑位置；好处就是是方便调试和测试人员使用，
在线请求的方式目前只有GET, POST, 希望增加DELETE, PUT ,PTACH就完美了

**Comment by star7th** [comment]
删除项目的时候会一并把项目里面的页面删除了的。所以点击数没那么多

**Comment by dengzgg** [comment]
请问，删除项目的操作按钮在什么地方，我点击某个项目后没看到删除按钮

**Comment by star7th** [comment]
项目设置，高级
