### ISSUE TITLE
给showdoc的一点点建议

### ISSUE THREAD

**Issue by java-lyf** [star7th/showdoc#1260]
> 公司使用showdoc也有一年多了，使用起来还是很不错的，在此，谨代表公司的开发成员感谢大佬提供这个开源工具。
结合使用了一年多的经验，提一两个建议：

### 1.团队管理，添加成员
添加成员的时候，搜索目前好像只能根据用户名搜索的，由于开放了注册权限，各个用户注册有的是用自己的名字全拼，有的是邮箱，不是很统一，导致添加成员的时候，搜索不知道谁是谁，**希望可以增加根据姓名搜索功能**

### 2.管理端，用户管理
目前用户管理，只有修改密码和删除功能，用户的姓名只能用户自己设置，后台不能设置，**希望能增加姓名修改功能**

**Comment by star7th** [comment]
这个后面优化下

java-lyf <notifications@github.com> 于2021年2月19日周五 上午10:48写道：

**Comment by star7th** [comment]
新版代码已支持这些功能
