### ISSUE TITLE
关于Dockerfile的一些建议

### ISSUE THREAD

**Issue by liukai6** [star7th/showdoc#1261]
由于apline镜像国内访问问题,希望加入国内源
`RUN set -eux && sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories`

**Comment by star7th** [comment]
我是这么想的，如果你是使用而已，那么官方已经有了构建好的镜像 https://www.showdoc.com.cn/help?page_id=65610
如果你是要自己构建，自己二次开发，那么可以自己加上一下。我不加入是因为保持最低第三方依赖。同时官方是使用国外服务器构建的，速度不会存在问题。

kailiu <notifications@github.com> 于2021年2月20日周六 上午9:54写道：
