### ISSUE TITLE
Docker安装Showdoc的数据库访问端口及用户名和密码是什么

### ISSUE THREAD

**Issue by charlie2009** [star7th/showdoc#1266]
Docker安装Showdoc的数据库用户名和密码是什么，如何连接这个数据库

**Comment by charlie2009** [comment]
sqlite数据库远程连接端口什么

**Comment by star7th** [comment]
-

   showdoc使用sqlite数据库。数据库文件是安装目录下的Sqlite/showdoc.db.php。你可以网络搜索如何在命令行中使用
   sqlite数据库.或者使用SQLiteStudio等可视化工具


charlie2009 <notifications@github.com> 于2021年2月24日周三 下午3:14写道：

**Comment by charlie2009** [comment]
了解，谢谢
