### ISSUE TITLE
集成openldap之后姓名为空

### ISSUE THREAD

**Issue by csw89742** [star7th/showdoc#1268]
集成openldap之后，拉取用户以及用户登录都没有问题，但是【姓名】这一列显示为空，这个字段取自于openldap中的哪个属性的值？能否在配置ldap的时候增加一项指定【姓名】取自于openldap哪个属性的值？

**Comment by star7th** [comment]
目前没有同步这个字段。其实配置项已经听过了的，应该不在打算增加字段。不然很多人会莫名其妙这个怎么配置。目前用这个的没有很多。如果很多用户反馈这个需求就加上
