### ISSUE TITLE
视频上传功能改善

### ISSUE THREAD

**Issue by zhangjingwen2008** [star7th/showdoc#1269]
希望能做到像图片粘贴那样简便。

目前在编写文章时，若遇到需要上传的视频，点击后弹出来的 video 标签让非程序行业的员工不知如何下手，希望能有所改善。

**Comment by star7th** [comment]
我好像没怎么遇到过视频文件都可以粘贴上传的案例。好像视频是不可以粘贴的。

zhangjingwen2008 <notifications@github.com> 于2021年2月26日周五 上午10:54写道：

**Comment by zhangjingwen2008** [comment]
可以考虑像目前的添加图片按钮一样，让员工自行选择本地视频的路径来进行上传。

主要是目前这个video标签实在是让员工不好下手。

**Comment by star7th** [comment]
当附件来上传吧。还有就是，上传的文件大小跟环境部署有关。大部分人上传视频可能时失败的。因为大文件需要额外调整，且跟showdoc无关，是调整nginx和php环境本身的设置。鉴于可能大部分用户都会失败，可能不打算集成这个功能进来

zhangjingwen2008 <notifications@github.com> 于2021年2月26日周五 上午11:11写道：
