### ISSUE TITLE
建议新增针对一个目录或者一个项目的changelog功能

### ISSUE THREAD

**Issue by johnniesong** [star7th/showdoc#127]
建议新增针对一个目录或者一个项目的changelog功能，内容是那个项目或目录的文档被更新了，点击链接可以看更新详情。这样别的成员看文档的时候可以快速知道那些文档被更新过了。

**Comment by star7th** [comment]
其实有过这种想法。别人也提过。
关于修改提示，有两种方案。一种是事无巨细地纪录下changelog，另一种是对新增加和新编辑过的文档进行红点标示，持续一两天。
不知你觉得哪种方案好

**Comment by johnniesong** [comment]
第一种方案更可行吧，第二种红点方案需要对每个用户做单独的跟踪，另外具体改了哪些行，还是得去看详细的chengelog。持续一两天的做法容易让人迷惑，不能精确的知道底改了没改。

第一种的话就在进入项目后，加一个超链接，可以看changelog。在chengelog页面每个目录做一个大标题，内容的话是时间，修改人，修改项目名，然后给个跳转或者浮窗查看具体的diff。大概这样子就行了吧。

**Comment by star7th** [comment]
如果做changelog自然是根据项目来做的好点，就不根据目录进行划分了。
往后的更新考虑这方面吧。

**Comment by johnniesong** [comment]
好的，非常感谢

**Comment by star7th** [comment]
经过一段时间的观察，发现这种需求比较少，而且changelog会产生大量无用信息，所以不再考虑
