### ISSUE TITLE
runapi客户端功能不足[个人建议]

### ISSUE THREAD

**Issue by Meleuo** [star7th/showdoc#1270]
项目的绝大多数的接口都是具有加密
目前showdoc是根据 runapi客户端中填写的请求参数生成参数文档, 

runapi请求的参数是经过加密的和实际未加密的数据大相径庭, 
目前的解决方法就是在备注的地方补上未加密的数据参数, 这样用着很不舒服, 也很奇怪

希望在参数哪里提供一个 类似于 未加密的参数展示功能

![image](https://user-images.githubusercontent.com/48749322/109255496-0c4b7580-782f-11eb-8fd9-46418f8a0803.png)
![image](https://user-images.githubusercontent.com/48749322/109255881-cb079580-782f-11eb-9523-3f24a952c0c5.png)

**Comment by star7th** [comment]
目前runapi是不支持这种功能的，你这个接口是需要前端实时加密再发送才行。说实话这种做法还是挺少见的，一般都是token校验+数字签名校验的方式来增强安全性。传输上的安全用https传输，是不需要业务层把参数全加密的
