### ISSUE TITLE
请问怎么输入latex公式呀

### ISSUE THREAD

**Issue by sknpy** [star7th/showdoc#1271]
请问怎么输入latex公式呀，我用$$x_a$$可以输入行间公式，但我尝试矩阵的时候好像不行呢~
例如：
$$
\begin{array}{ccc}
x_1 & x_2 & \dots \\
x_3 & x_ 4& \dots \\
\vdots & \vdots & \ddots
\end{array}
$$

**Comment by star7th** [comment]
参考 https://pandao.github.io/editor.md/

**Comment by sknpy** [comment]
emm，这个教程里好像没有如何输入矩阵
我试了试，带array体系的好像会直接消失

**Comment by star7th** [comment]
如果教程里不支持那就是可能不支持了。因为showdoc是用那个开源编辑器的

Shiro <notifications@github.com> 于2021年2月27日周六 上午10:27写道：

**Comment by sknpy** [comment]
好的，谢谢
