### ISSUE TITLE
优化需求：目录菜单item增加在新浏览器打开的链接

### ISSUE THREAD

**Issue by westudiodev** [star7th/showdoc#1272]
【AS IS】：现在左边目录菜单item只能点击直接跳转到目标文档页，经常会遇到阅读一个文档时，需要打开参考另一个文档，就会比较麻烦
【TO BE】：菜单item增加超链接，右键可以通过弹出浏览器菜单，快速在新浏览器窗口打开，或者提供快捷键+点击方式在新浏览器打开文档页，方便阅读一份文档时，参考另一个文档

**Comment by star7th** [comment]
后面看看怎么处理，可能是增加超链接

westudiodev <notifications@github.com> 于2021年3月2日周二 上午6:17写道：

**Comment by star7th** [comment]
已支持超链接。右击新窗口打开即可
