### ISSUE TITLE
优化建议：访问权限以及自主注册优化建议

### ISSUE THREAD

**Issue by jason-this** [star7th/showdoc#1273]
1、开源版建议增加项目以及文档 “登录用户公开” 功能，目前只有全公开和密码保护相对不是很人性化；
有些文档是团队成员公开的，设置密码不是太方便，但是如果部署在公网的话那就很多人能够看到了，这不是团队共享的本意；
2、建议添加关闭注册功能，小团队部署在公网上使用，如果开放注册，对文档的私密性、服务的安全性不是很好；
以上是个人简单的两点优化建议，已经使用ShowDoc好久了第一次提建议，希望作者能够采纳

**Comment by star7th** [comment]
1，设置密码保护是限制游客。团队成员访问是不需要密码的。
2，管理后台有关闭注册功能。

JasonHuang <notifications@github.com> 于2021年3月4日周四 下午7:59写道：
