### ISSUE TITLE
列表和表格缩进后无法正常显示

### ISSUE THREAD

**Issue by enoera00** [star7th/showdoc#1274]
如图：

![image](https://user-images.githubusercontent.com/8799797/110088671-1ee62180-7dd0-11eb-911a-994928d090ce.png)

无序列表缩进后会显示成有序列表，而表格缩进后无法渲染，很明显的问题啊，很奇怪为什么没有人提，还是说哪里操作不对么。。。。望解答

**Comment by star7th** [comment]
有序列表里面写东西容易出现不可控。建议手写数据 。 https://github.com/star7th/showdoc/issues/1074
另外某些语法里，缩进是会被当作代码块。我并不建议markdown编辑里使用缩进。

**Comment by star7th** [comment]
用空格代替缩进会好一些。

**Comment by enoera00** [comment]
我说的缩进就是空格，按照标准语法的4个空格。在其他编辑器里面，比如typora，以及showdoc官方使用的编辑器里面都是可以正常显示的。

**Comment by star7th** [comment]
我刚才试了下，https://pandao.github.io/editor.md/ 并不支持 在四个空格后还用表格。

enoera00 <notifications@github.com> 于2021年3月5日周五 下午5:10写道：

**Comment by star7th** [comment]
在markdown里使用四个空格或者缩进并不是好习惯。因为不同的解析器对缩进/四空格 的理解不一样。

Chen Xing <xing7th@gmail.com> 于2021年3月5日周五 下午5:14写道：

**Comment by enoera00** [comment]
如果不用空格，层级关系就不明显了，可读性会差很多，表格先不说，类似下面的嵌套列表是非常常见的书写方式，也是标准语法，但是showdoc里面会显示成有序列表，您可以试试，在github里面也是显示正常的

1. 第一项：
    + 第一项嵌套的第一个元素
    + 第一项嵌套的第二个元素
2. 第二项：
    - 第二项嵌套的第一个元素
    - 第二项嵌套的第二个元素

**Comment by enoera00** [comment]
在showdoc官方使用的编辑器里面也能正常显示，如图：
![image](https://user-images.githubusercontent.com/8799797/110094867-455b8b00-7dd7-11eb-8ee4-d81108c29967.png)

但是在showdoc里面会显示成下面这样：
![image](https://user-images.githubusercontent.com/8799797/110094984-615f2c80-7dd7-11eb-99ca-fa1cb3a5d5bb.png)

**Comment by star7th** [comment]
我不知道是不是自己改动过什么。我始终建议不要使用默认的数字有序列表。而是自己手写数字。

enoera00 <notifications@github.com> 于2021年3月5日周五 下午5:22写道：

**Comment by star7th** [comment]
第一层，第二层，都不建议使用数字 。自己手写个数据，然后逗号。

Chen Xing <xing7th@gmail.com> 于2021年3月5日周五 下午5:37写道：

**Comment by enoera00** [comment]
好吧，用表格的时候只能放弃缩进了，有序列表和无序列表不去嵌套使用。
