### ISSUE TITLE
私有部署：图片上传选择阿里云时如何设置上传图片文件夹位置

### ISSUE THREAD

**Issue by BlueWindQAQ** [star7th/showdoc#1276]
![QQ图片20210305173741](https://user-images.githubusercontent.com/33320180/110097077-98364200-7dd9-11eb-8b36-a1d1a930b14a.png)

**Comment by BlueWindQAQ** [comment]
这里只能设置bucket，无法设置bucket中的某个目录

**Comment by star7th** [comment]
不支持设置目录。好像阿里云也不是按bucket数收费的，单独建立一个给showdoc应该还可以吧。

BlueWindQAQ <notifications@github.com> 于2021年3月5日周五 下午5:39写道：
