### ISSUE TITLE
新增OIDC登录

### ISSUE THREAD

**Issue by TripodXiao** [star7th/showdoc#1278]
在企业里,单点登录是很重要的一件事,如果每个系统都有自己的账号的话,用起来会很麻烦,建议新增一个单点登录功能,支持OIDC就行,这样就可以整合其他的微信登录或者qq登录之类的了

**Comment by star7th** [comment]
后面y有时间探索下这方面

TripodXiao <notifications@github.com> 于2021年3月9日周二 上午8:49写道：

**Comment by star7th** [comment]
刚更新了下，后台增加了一个“集成登录”的菜单，支持Oauth2.0配置登录。
