### ISSUE TITLE
使用mysql数据库后，提示数据库连接不上。请确保安装了php-sqlite扩展以及数据库文件Sqlite/showdoc.db.php可用

### ISSUE THREAD

**Issue by jingyanXia** [star7th/showdoc#1280]
我按照网上教程吧数据库改为mysql,我在centos上安装了mysql数据库，并创建了了一个名为showdoc的数据库，另外我对config.php做了如下的更改
DB_TYPE'   => 'mysql',
    'DB_NAME'   => 'showdoc',
    'DB_HOST'   => 'localhost',
    'DB_USER'   => 'showdoc',
    'DB_PWD'    => 'xxxxxxxxx',
我把这些做完后，清理的缓存，当我打开网站确提示“数据库连接不上。请确保安装了php-sqlite扩展以及数据库文件Sqlite/showdoc.db.php可用”。对此我要怎么做？

**Comment by star7th** [comment]
showdoc官方不支持mysql。建议你去问那个写教程的人。

jingyanXia <notifications@github.com>于2021年3月10日 周三下午3:15写道：
