### ISSUE TITLE
添加团队之后添加成员，其他成员登录之后没有显示相关团队信息

### ISSUE THREAD

**Issue by mhxw** [star7th/showdoc#1281]
问题：进入团队添加成员后。其他成员没有相关信息
环境：按照官方docker版命令启动
![image](https://user-images.githubusercontent.com/32643286/110741615-f3e84b80-826f-11eb-802d-53e2a0efa0fc.png)

**Comment by star7th** [comment]
团队成员能在项目列表页面看得到分配到的有权限的项目。但没必要看到其他团队成员信息，所以没做。

MHXW <notifications@github.com> 于2021年3月11日周四 下午1:46写道：
