### ISSUE TITLE
搜索功能的一点建议

### ISSUE THREAD

**Issue by risoyo** [star7th/showdoc#1282]
在主界面的搜索默认的应该是搜索项目名称，不能搜索到项目内文档的内容，我们团队在使用之后，发现随着项目增多文档增多，当不确定某个文档在哪个项目内时，依靠现有的搜索功能很难快速定位到对应文档，能否考虑在主界面的搜索增加全局搜索的功能？

**Comment by star7th** [comment]
重复问题了。https://github.com/star7th/showdoc/issues/1193 其实是有规划的了。就另外找时间实现吧。

**Comment by risoyo** [comment]
不好意思，刚才搜索了下issue没有找到才提的，可能没看清楚，辛苦大佬了
