### ISSUE TITLE
showdoc 使用异常问题

### ISSUE THREAD

**Issue by qq675583110** [star7th/showdoc#1284]
showdoc私有化部署，环境docker 脚本部署安装
问题描述
         在使用RunApi的时候，使用RunApi windows客户端showdoc 管理员账号登录进去之后，无法看到showdoc上的项目，是否可以直接把showdoc 上的项目同步或者API文档同步到 RunApi 上来？？？如果可以，请问怎么操作 谢谢！！！ 急 急！！或者直接告诉我 两者之间使用的关系！

**Comment by star7th** [comment]
-


   runapi的数据可以生成markdown格式，但不可逆，markdown数据很难再转换回来runapi。所以它无法跟showdoc原有数据互相转换。只是它们可以共用文档浏览/团队协作等功能。同时runapi生成的文档只能在runapi上编辑，不能在showdoc上编辑。后面如果要做数据共用，可能需要对showdoc编写格式有一定的规范约束，这个后面再探索下。



Yang Xing Zhen ***@***.***> 于2021年3月12日周五 下午5:05写道：

**Comment by udbihss** [comment]
我追问下，RunApi的作用是 可以在上面创建项目，生成文档 自动生成API测试报告等，然后可以在showdoc 上浏览，而showdoc上的文档 项目 等是无法 同步到RunAPI 上来对吧？ 在Runapi 上无法看到showdoc上的原有的文档？

**Comment by star7th** [comment]
是的。runapi可以生成到showdoc，但showdoc无法转回runapi

udbihss ***@***.***> 于2021年3月12日周五 下午6:28写道：
