### ISSUE TITLE
请问如何全局替换呀

### ISSUE THREAD

**Issue by sknpy** [star7th/showdoc#1287]
最近换了个图床，想要全局替换个链接，请问怎么操作呀

**Comment by star7th** [comment]
showdoc使用sqlite数据库。数据库文件是安装目录下的Sqlite/showdoc.db.php。你可以网络搜索如何在命令行中使用 sqlite数据库.或者使用SQLiteStudio等可视化工具

打开数据库后，执行 update page set page_content = replace(page_content,'原始host','新host')

**Comment by sknpy** [comment]
多谢，已解决！
