### ISSUE TITLE
showdoc迁移问题

### ISSUE THREAD

**Issue by udbihss** [star7th/showdoc#1288]
部署环境：docker   
迁移大概步骤：由于早期的版本过低，最近更换了新的版本，直接拉了个最新的镜像，docker启动  只把里面两个数据文件迁移了showdoc.db.php  Uploads  ，目前数据什么的没有问题，但是有同事反映说里面的图片和附近不见了，请问这2个数据是不是存放在其它目录下？

**Comment by star7th** [comment]
请按官网提示安装和升级 https://www.showdoc.com.cn/help?page_id=13732 ，不是拉个镜像就完事了

**Comment by star7th** [comment]
docker的话，是这个链接 https://www.showdoc.com.cn/help?page_id=65610  按照文档操作，官方文档有问题再反馈。

**Comment by udbihss** [comment]
首先我目前迁移已经完成了，服务也是正常访问，但是同事反馈说有些文档存在图片，在新的环境里面没有了。问题在这里。我目前迁移 就拷贝了   showdoc.db.php Uploads   我想应该也是可以的吧？

**Comment by star7th** [comment]
文字是不是全部都在？图片是不是全部都不在？直接在浏览器里访问该图片url得到的提示是什么

udbihss ***@***.***> 于2021年3月17日周三 下午3:59写道：

**Comment by udbihss** [comment]
![Uploading image.png…]()

**Comment by star7th** [comment]
你上传的图片看不到。

**Comment by udbihss** [comment]
文字部分都存在，目前是图片 我使用F12 查看了下  提示找不到数据 
![image](https://user-images.githubusercontent.com/80514886/111434475-8db16c00-873a-11eb-924f-d97cde934076.png)

**Comment by star7th** [comment]
直接新窗口打开看看如何。另外自己也尝试上传一张新图片看是否正常

udbihss ***@***.***> 于2021年3月17日周三 下午4:05写道：

**Comment by udbihss** [comment]
打开窗口是找不到因为我看了下 那个图片的链接地址 还是源服务器的 这是为啥？？

**Comment by star7th** [comment]
https://github.com/star7th/showdoc/issues/1287

**Comment by udbihss** [comment]
![image](https://user-images.githubusercontent.com/80514886/111443397-4b8d2800-8744-11eb-99f6-b15d79a9554c.png)
麻烦看下 是这样执行更新吗？

**Comment by star7th** [comment]
理论上是的

udbihss ***@***.***> 于2021年3月17日周三 下午5:15写道：

**Comment by udbihss** [comment]
这样更新成功了吗？ 貌似我网站上还是不行？

**Comment by star7th** [comment]
你还没回复我的问题。新上传一张图片是否正常上传并且能访问。

udbihss ***@***.***> 于2021年3月17日周三 下午5:18写道：

**Comment by udbihss** [comment]
![image](https://user-images.githubusercontent.com/80514886/111446686-a1170400-8747-11eb-857b-2bf916651458.png)
重新上传图片肯定是没有问题 你看图 链接和显示都有了 ，问题肯定是修改那个host地址的问题

**Comment by star7th** [comment]
执行 update upload_file set real_url= replace(real_url,'原始host','新host') 看看

**Comment by udbihss** [comment]
![image](https://user-images.githubusercontent.com/80514886/111452755-cc9ced00-874d-11eb-8466-64ec117ace31.png)
执行拉  不行啊

**Comment by udbihss** [comment]
还是没有改过来

**Comment by udbihss** [comment]
还是没有改过来

**Comment by star7th** [comment]
把其中一个无法访问的图片url 和一个能正常访问的图片url分别发出来看看

udbihss ***@***.***> 于2021年3月17日周三 下午6:28写道：

**Comment by udbihss** [comment]
上面都有截图呀 一个正常显示 一个不正常显示 是图片的链接地址 还是原来的！现在的问题很简单 就是改图片的请求地址

**Comment by star7th** [comment]
把文字复制出来我访问下

udbihss ***@***.***> 于2021年3月18日周四 上午10:28写道：

**Comment by udbihss** [comment]
你们可以搭建个环境试一试吗？

**Comment by udbihss** [comment]
都已经找到问题点了 为什么还在纠结这个？

**Comment by star7th** [comment]
请把文字复制出来让我访问下，一个正常的url例子和一个不正常的url例子。或者你尝试自己解决问题

udbihss ***@***.***> 于2021年3月18日周四 上午10:30写道：

**Comment by udbihss** [comment]
![image](https://user-images.githubusercontent.com/80514886/111564706-2a284c80-87d5-11eb-8c40-7f67de8c6cae.png)
![image](https://user-images.githubusercontent.com/80514886/111564722-33b1b480-87d5-11eb-86d8-2f6d3e780803.png)
你对比下，请求的地址 很明显是地址出问了 现在就是要改这个地址啊

**Comment by udbihss** [comment]
我要怎么复制给你？

**Comment by star7th** [comment]
提供文字版图片url，一个能正常访问图片文件的（新上传的图片），一个不正常的。

udbihss ***@***.***> 于2021年3月18日周四 上午10:33写道：

**Comment by udbihss** [comment]
http://192.168.10.12:8080/Public/Uploads/2020-07-13/5f0bfc4485ddc.png
http://showdoc.ugreengroup.com/web/#/2?page_id=387

**Comment by udbihss** [comment]
你对比下 不就知道了吗？ 总在纠结这个 我是服你
不就是吧所有的图片的  192.168.10.12:8080 改成  showdoc.ugreegroup.com 吗？

**Comment by star7th** [comment]
这是你上面截图执行的sql语句 
![image](https://user-images.githubusercontent.com/2200494/111565464-61e3c400-87d6-11eb-89fc-43bfe245c1a2.png)

而你内网的host前缀是 192.168.10.12:8080 。你没发现你执行sql替换的ip和实际的图片urlip不一样吗

**Comment by star7th** [comment]
我建议的是执行  update page set page_content = replace(page_content,'原始host','新host')  ，但自己原始host和新host自己对应好，我没法帮你检查那么细节。

**Comment by udbihss** [comment]
我是执行了啊 不是截图给你看了吗？



慈铭体检只为健康


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "star7th/showdoc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月18日(星期四) 上午10:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [star7th/showdoc] showdoc迁移问题 (#1288)





 
我建议的是执行  update page set page_content = replace(page_content,'原始host','新host')  ，但自己原始host和新host自己对应好，我没法帮你检查那么细节。

**Comment by star7th** [comment]
你把执行的sql里包含的ip和http://192.168.10.12:8080/Public/Uploads/2020-07-13/5f0bfc4485ddc.png 这条url的ip地址比较一下，一个是192.168.24.12 ，一个是192.168.10.12:8080 ,这哪里一样了

**Comment by udbihss** [comment]
![450B2494-2056-4241-8DEC-A6DCD4B6756F](https://user-images.githubusercontent.com/80514886/111566738-aff9c700-87d8-11eb-86e9-be23d0bebfdd.png)
都执行了 没用啊！好吧内网地址 换了 开始搞错了 但是 命令 你看看

**Comment by star7th** [comment]
你可以执行 select * from page where page_content like '%192.168.10%' limin 5 来看看是否还存在旧ip数据。这个细节问题可能要你自己排查下，我现在不是很有时间。从历史问题来看，我写的教程方法没问题，有人能正常操作成功 https://github.com/star7th/showdoc/issues/1287 。可能你就是哪里细节没操作好。

**Comment by star7th** [comment]
隐约记得好像sql语句是要加分号 ； 在后面才真正执行。你上面没有分号。加上试下。

**Comment by udbihss** [comment]
使用工具 Navi cat 连接 更改 的命令有吗？

**Comment by udbihss** [comment]
我是怀疑我没有进入到数据库里面去，我没有玩过这个数据库&nbsp;



慈铭体检只为健康


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "star7th/showdoc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月18日(星期四) 中午11:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [star7th/showdoc] showdoc迁移问题 (#1288)





 
你可以执行 select * from page where page_content like '%192.168.10%' limin 5 来看看是否还存在旧ip数据。这个细节问题可能要你自己排查下，我现在不是很有时间。从历史问题来看，我写的教程方法没问题，有人能正常操作成功 #1287 。可能你就是哪里细节没操作好。

**Comment by star7th** [comment]
我只告诉要执行什么sql，而对数据库的使用这么细节的地方，我那么多时间。自己搜索下吧

**Comment by udbihss** [comment]
好的 好的！！ 我自己研究下吧 辛苦你了



慈铭体检只为健康


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "star7th/showdoc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月18日(星期四) 中午11:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [star7th/showdoc] showdoc迁移问题 (#1288)





 
我只告诉要执行什么sql，而对数据库的使用这么细节的地方，我那么多时间。自己搜索下吧
