### ISSUE TITLE
能不能不777 ？？？

### ISSUE THREAD

**Issue by pptfz** [star7th/showdoc#1289]
docker安装，持久化目录上来就全部777？？？能否不777？这是要往生产中放的

**Comment by star7th** [comment]
docker环境已经隔离了的，不会影响到宿主服务器。我觉得不需要纠结权限问题。给777更多是为了方便。如果你真的要细分权限，你可以自己看着怎么给权限吧，总之保证docker进程能读写映射的文件和目录即可。

pptfz ***@***.***> 于2021年3月17日周三 下午4:04写道：

**Comment by pptfz** [comment]
好的，多谢多谢

**Comment by pptfz** [comment]
可否分享一下showdoc的dockerfile呢？

**Comment by star7th** [comment]
https://github.com/star7th/showdoc/blob/master/Dockerfile

**Comment by pptfz** [comment]
非常感谢🙏
