### ISSUE TITLE
发现个小bug,RunApi的

### ISSUE THREAD

**Issue by l97069947** [star7th/showdoc#1291]
请求json参数中,如果有long类型参数,长度19位,发请求会自动将最后一位重置为0,json快速美化也会将其重置为0

### 我发出的请求
![QQ截图20210319110444](https://user-images.githubusercontent.com/30620486/111725979-fe739800-88a2-11eb-944a-4e6f9f3476b2.png)
### 实际发出的请求
![QQ截图20210319110329](https://user-images.githubusercontent.com/30620486/111725860-d2f0ad80-88a2-11eb-8caf-c4bf442d0068.png)
### 我收到的请求
![image](https://user-images.githubusercontent.com/30620486/111726087-337fea80-88a3-11eb-8fa4-d4ee00669f08.png)

**Comment by star7th** [comment]
我也挺迷惑的。可能跟程序是32位的有关。如果是那样的话暂时无解吧

Liaoweiming ***@***.***> 于2021年3月19日周五 上午11:04写道：

**Comment by l97069947** [comment]
好的 多谢

**Comment by star7th** [comment]
runapi客户端已经改用64位版，可以支持大整数类型。卸载原客户端，然后去下载新的安装即可 https://www.showdoc.com.cn/runapi/30291
