### ISSUE TITLE
请问RunAPI有没有加类似PostMan  Tests的功能？

### ISSUE THREAD

**Issue by skipify** [star7th/showdoc#1292]
请问RunAPI有没有加类似PostMan  Tests的功能？
领RunApi有没有美化UI显示的打算？

**Comment by star7th** [comment]
test功能看一下计划，这块功能改动要很大，得计划很多。UI显示你可以建议一下。UI当然是想越好，但怎样才是好，是个问题。

skipify ***@***.***> 于2021年3月19日周五 下午11:00写道：

**Comment by yuyedaidao** [comment]
别犹豫了，这个功能简直是刚需，复制粘贴token这样的操作太拉垮了，一定不能成为一个优秀开发的日常操作啊。浏览了一遍issue已经很多人提了，还请认真对待啊，先行谢过

**Comment by moobing** [comment]
确实刚需+1

**Comment by star7th** [comment]
已增加执行前后脚本功能。可部分实现环境变量的自动赋值动作。等晚点再串起来做成测试流程。
重启runapi可自动更新。但showdoc服务端需要自行升级到最新版。

**Comment by star7th** [comment]
经过多天假期的努力，runapi已经支持流程测试功能（类似postman 的tests)，跟postman有一点不一样。可以在后执行脚本里设置断言，然后流程测试的时候会显示断言的通过失败情况。
重启runapi可自动更新。同时showdoc服务端需要自行升级到最新版。
