### ISSUE TITLE
RunApi的复制json过长的问题

### ISSUE THREAD

**Issue by shanesyk** [star7th/showdoc#1293]
在使用RunApi发送接口时，对于post请求，当json字符串过长，RunApi会闪退，我使用的json字符串的长度是一万行左右，直接闪退了，在postman里面没有问题， 不知道这方面有没有什么方法优化一下？

**Comment by star7th** [comment]
runapi链接官网看有没有这个问题。https://www.showdoc.com.cn/ 
如果官网ok，那就是你的服务器问题了。尝试搜索历史问题，把允许上传的附件大小调大。一般是调整php和nginx的配置，不用调整showdoc代码。

**Comment by shanesyk** [comment]
我试了一下，软皮连接官网也是会闪退，和连接自己的服务器一样。这个和允许上传的附件大小有关吗？我也试了一下postman，没有出现这个问题，可以正常复制。

**Comment by star7th** [comment]
那就可能不是上传附件大小关闭吧。你这个问题太特殊，就不打算在此问题上浪费太多时间了。一万行的json本身不合理，应该有很多优化空间。

shane ***@***.***> 于2021年3月21日周日 下午11:06写道：

**Comment by star7th** [comment]
如果是返回的json，可以不需要嵌套那么多对象。一个接口返回可以不需要那么多冗余数据的

Chen Xing ***@***.***> 于2021年3月22日周一 上午9:46写道：

**Comment by shanesyk** [comment]
恩恩，这个是我在测试接口的时候偶然发现的，也不太影响正常功能的使用，但是如果json数据稍微长一些好像会有一点卡顿的情况，可能应该是性能方便的问题吧，谢谢回答。
