### ISSUE TITLE
https://www.showdoc.com.cn/  打不开了 网站 报错504 网关超时

### ISSUE THREAD

**Issue by JJdog** [star7th/showdoc#1294]

**Comment by JJdog** [comment]
![image](https://user-images.githubusercontent.com/21210967/112250056-c221ac80-8c93-11eb-8694-c6f5f21aff5c.png)

**Comment by linchangshu0** [comment]
同样的问题。什么时候能解决？

**Comment by kaychiao** [comment]
me2

**Comment by zengwb617** [comment]
现在能打开了

**Comment by kaychiao** [comment]
现在进入项目特别慢，三分钟了还没刷新出来我的项目😂😂
好痛苦……

**Comment by star7th** [comment]
已恢复。带宽严重堵住，积压的请求导致恢复花了点时间。

kaychiao ***@***.***> 于2021年3月24日周三 上午11:44写道：

> 现在进入项目特别慢，三分钟了还没刷新出来我的项目😂😂
> 好痛苦……
>
>
>
>
> Sent from my iPhone
>
