### ISSUE TITLE
附件不可以预览，下载也是错的

### ISSUE THREAD

**Issue by littlemolh** [star7th/showdoc#1297]
附件可以上传，不可以预览和下载

**Comment by star7th** [comment]
粘贴出其中一个附件的地址看看

LittleMo ***@***.***> 于2021年4月6日周二 下午7:29写道：

**Comment by littlemolh** [comment]
@star7th http://doc.igeek.cc/server/index.php?s=/api/attachment/visitFile/sign/e2bc49f27946183a1fc20ca707e79586

**Comment by star7th** [comment]
从url来看是正常的。你尝试上传其他文件看正常不。会不会是当前这个图片文件的问题

LittleMo ***@***.***> 于2021年4月6日周二 下午9:46写道：

**Comment by littlemolh** [comment]
32	e2bc49f27946183a1fc20ca707e79586	image.png	image/png	7920	3	0	0	38	1617706188	https://showdoc-leeneo.oss-cn-hangzhou.aliyuncs.com/showdoc_1617706188454585251.png	0

@star7th 这是sqlite的记录，可以确认的是这个图片在oss是正常有效的

**Comment by star7th** [comment]
开一个账户给我试一下上传

LittleMo ***@***.***> 于2021年4月7日周三 上午9:16写道：

**Comment by littlemolh** [comment]
test

**Comment by littlemolh** [comment]
test 123456
@star7th

**Comment by star7th** [comment]
我改动了下代码，你更新上去看是否正常

**Comment by littlemolh** [comment]
可以了👍
