### ISSUE TITLE
刷新页面转圈半天没有刷出内容

### ISSUE THREAD

**Issue by linchangshu0** [star7th/showdoc#1299]
刷新页面转圈半天没有刷出内容。最近服务器怎么不稳定？上次宕机数小时，这又来。

**Comment by star7th** [comment]
啥？ 今天没异常过。我刚才新建编辑删除页面都正常。

linchangshu ***@***.***> 于2021年4月7日周三 下午4:21写道：

**Comment by star7th** [comment]
你说的是runapi的话，有可能是客户端缓存问题。参考这个常见问题中的“RunApi客户端打不开或者一直显示加载中”    https://www.showdoc.com.cn/3?page_id=16118
