### ISSUE TITLE
能不能增加下多级目录功能

### ISSUE THREAD

**Issue by a100944408** [star7th/showdoc#13]

**Comment by star7th** [comment]
如果页面太多，可考虑分成几个不同子项目。ShowDoc一开始考虑的只是小项目，因此没打算做二级目录。做二级目录的话，从样式到后台到数据库到导出文件，全都要改。如果这个需求很多人反馈就再新增吧。当前先切分子项目

**Comment by jian263994241** [comment]
增加到支持 三级目录吧  这功能比较常见啊 ...

**Comment by Luolired** [comment]
希望支持多级目录，将非常棒

**Comment by CinderellaCiCi** [comment]
多级目录不错，可以考虑呀。

**Comment by star7th** [comment]
新增了支持三级目录的功能；升级安装请参考部署手册中“升级安装”部分。http://blog.star7th.com/2016/05/2007.html
此外我新建了一个ShowDoc使用交流qq群（群号：564671853），欢迎探讨问题
