### ISSUE TITLE
项目页面分享，代码块不是很好看啊

### ISSUE THREAD

**Issue by shixueqian** [star7th/showdoc#130]
感觉单页面浏览时代码块看起来还可以。但是以项目页面分享出去，看着页面中的代码块显示会有阴影，还挺难看的，建议优化一下

**Comment by star7th** [comment]
单页面的代码块和项目页面的代码块样式是一致的。你可以截图对比看下

**Comment by star7th** [comment]
我做了下改动，把代码块的颜色调节淡一点https://www.showdoc.cc/demo?page_id=10

**Comment by shixueqian** [comment]
现在可以了，感谢
