### ISSUE TITLE
支持postman重复导入。

### ISSUE THREAD

**Issue by lyongdee** [star7th/showdoc#1301]
貌似只能在新建项目的时候可以导入 postman.json，是否可以支持在编辑项目的时候导入新的 postman.json 进行覆盖。

![image](https://user-images.githubusercontent.com/369124/114040404-26f51d80-98b6-11eb-803a-5c5dbd742438.png)

**Comment by star7th** [comment]
考虑在后面支持吧

**Comment by star7th** [comment]
已发布新版，支持了此功能
