### ISSUE TITLE
希望runapi增加：运行api之后用脚本动态修改环境变量的功能

### ISSUE THREAD

**Issue by qfsz168** [star7th/showdoc#1302]
有这样的需求：
我们大多数api是有权限验证的，比如在header的Authorization携带token，而token是通过登录获取的。
希望在登录api执行以后，可以用脚本动态设置环境变量，其他api的Authorization值就是这个变量，这样就避免每次手动复制登录api的返回值，再粘贴到要调试的api中了。

目前postman，以及apifox，apipost等类似工具已经由此功能。但是runapi能直接发布文档showdoc这一点就秒杀其他的了。
ps：从2016年就开始使用showdoc，简单且强大，感谢作者！

**Comment by star7th** [comment]
https://github.com/star7th/showdoc/issues/1292 跟这个问题类似。前端执行脚本，然后把脚本串起来做自动化测试。这块我是想做的。但这块改动太大了，不好说什么时候有时间做以及做完。只能说我确实想做这块。

**Comment by star7th** [comment]
一开始图省事，架构没设计好，导致包袱越积累越多。要做自动化测试功能不简单。

**Comment by qfsz168** [comment]
嗯嗯，作为程序猿，理解难处。
如果有这个功能，就能打通自测api和发布api文档，再加上showdoc的强大易用，在相关领域会特别有竞争力。
如果可能，可以大家一起来重构完善。

**Comment by star7th** [comment]
已增加执行前后脚本功能。重启runapi可自动更新。但showdoc服务端需要自行升级到最新版。

**Comment by dlwss** [comment]
服务端升级后，新版本客户端在编写前执行脚本和后执行脚本后，调用完接口后，会出现无法再编辑脚本，找不到光标的情况

**Comment by dlwss** [comment]
> 已增加执行前后脚本功能。重启runapi可自动更新。但showdoc服务端需要自行升级到最新版。
服务端升级后，新版本客户端在编写前执行脚本和后执行脚本后，调用完接口后，会出现无法再编辑脚本，找不到光标的情况

**Comment by star7th** [comment]
@dlwss 我实测没遇到你的问题。首先先确保服务端升级好。登录进服务端看看功能使用都正常不。其次保证脚本语法都正确。现在runapi没来得及对语法进行友好的校验。另外重启runapi看看

**Comment by dlwss** [comment]
@star7th 你好，我刚刚又试了下，发现再执行完弹窗语法后 `runapi.alert("调试信息" );` 会出现丢失光标的情况，此时刷新界面或打开帮助说明问题就会消失。

**Comment by star7th** [comment]
@dlwss 出现问题重启或者刷新是比较万能的解决方法。当前先这么用吧。后面我早晚要把alert这个方法干掉。默认使用了系统的alert，弹窗的时候会阻塞进程

**Comment by dlwss** [comment]
@star7th  好的，谢谢大佬。

**Comment by star7th** [comment]
另外我正在开发自动化测试功能，其中会需要在自定义脚本里填写判断表达式。我现在已经完成得七七八八了，还没上线。但文档写好了，有时间可以帮我看一下文档，看看文档里的语法是否满足自动化测试的需求的。如果不能满足我可能还需要封装一些语法  https://www.showdoc.com.cn/p/4949225ee3575af88b0748ae0e6fc105
