### ISSUE TITLE
通过runapi生成的文档没有导出按钮

### ISSUE THREAD

**Issue by CoderXiaohui** [star7th/showdoc#1304]
### 问题：
通过RunAPI生成的文档没有导出按钮.

### 环境：
RunApi-MAC客户端
showdoc-自己搭建

### 描述：
如果只在showdoc中新建项目，自己编写文档，是可以导出markdown和doc格式的。
而通过RunAPI生成的文档在showdoc中没有导出按钮了。
我知道RunAPI APP中可以导出，但是只能导出doc，没有markdown。

**Comment by star7th** [comment]
runapi的项目只能在runapi客户端里导出。目前只能导出word。它的底层不是以markdown形式保存的。

邓晓晖 ***@***.***> 于2021年4月11日周日 上午2:57写道：
