### ISSUE TITLE
升级之后不能上传附件了.

### ISSUE THREAD

**Issue by acracker** [star7th/showdoc#1305]
自动脚本装机
升级步骤
```
wget https://www.showdoc.com.cn/script/showdoc;chmod +x showdoc;
 ./showdoc update
```
然后上传附件,上传的时候附件列表里面有上传进度, 上传完后消失.
![image](https://user-images.githubusercontent.com/16358913/114509616-4dc1a400-9c68-11eb-92ed-009966da8a54.png)

**Comment by star7th** [comment]
尝试执行命令 chmod 777 -R /showdoc_data/html
