### ISSUE TITLE
第一次打不开，还是乱码，第二次能打开，但是之前的账号登录状态没了

### ISSUE THREAD

**Issue by linhanqiang** [star7th/showdoc#1306]
![image](https://user-images.githubusercontent.com/31612251/115171085-d622c780-a0f4-11eb-91de-591242b96b58.png)

**Comment by star7th** [comment]
大概是因为更新过。你重新登录看是否能正常使用。

linhanqiang ***@***.***> 于2021年4月19日周一 上午9:52写道：
