### ISSUE TITLE
账号删除未与团队成员同步

### ISSUE THREAD

**Issue by chenlw527** [star7th/showdoc#1307]
操作步骤：
1、对有正常账号添加到团队，并将项目授权给对应对团队。
2、在“用户管理”删除用户
3、在团队管理-对应团队的”成员”，已删除用户可见
4、在项目的成员管理里面的“成员权限”可见已删除的用户

**Comment by star7th** [comment]
这个不影响使用。对方已经无法登录了的。等下次更新的时候把这个小问题修复了。

**Comment by star7th** [comment]
我看代码发现已经有了这个功能了的。删除会同步删除团队成员。你可能用的就是很久的版本。需要升级到新版看看。
