### ISSUE TITLE
runapi提示未创建api项目，系统自动为你创建

### ISSUE THREAD

**Issue by fss815** [star7th/showdoc#1308]
我已经有在后台添加项目了，而且我在后台添加的项目，在runapi的列表也不显示，只有通过runapi创建的项目才会出现在列表中

**Comment by star7th** [comment]
showdoc原有项目不能被runapi使用。估计你没认真看提示。

runapi的数据可以生成markdown格式，但不可逆，markdown数据很难再转换回来runapi。所以它无法跟showdoc原有数据互相转换。只是它们可以共用文档浏览/团队协作等功能。同时runapi生成的文档只能在runapi上编辑，不能在showdoc上编辑。后面如果要做数据共用，可能需要对showdoc编写格式有一定的规范约束，这个后面再探索下。
