### ISSUE TITLE
部署完后，首页可以访问，但点击登录/注册 那个按钮就提示“No input file specified.”

### ISSUE THREAD

**Issue by 1181958400** [star7th/showdoc#131]
我域名部署的http://doc.wuwae.com
直接指向的showdoc文件夹，然后直接访问域名，首页可以打开，但点注册按钮就提示“No input file specified.”
跳转路径是http://doc.wuwae.com/.php?s=/home/user/login
奇怪的是中间的index.php不知道为什么变成了.php

求大神指点

**Comment by star7th** [comment]
https://github.com/star7th/showdoc/issues/100

**Comment by 1181958400** [comment]
好的，谢谢

我看着改下配置
