### ISSUE TITLE
关于showdoc登录验证码失效问题

### ISSUE THREAD

**Issue by jianghongzhou19910422** [star7th/showdoc#1310]
![image](https://user-images.githubusercontent.com/83057785/115828636-90d9ff00-a440-11eb-8101-af0cb3f35973.png)
尝试了文档的操作但是没有找到对应php.ini 的文件下的session，  磁盘也没有满， 麻烦帮忙看看 是什么原因。  
![image](https://user-images.githubusercontent.com/83057785/115828685-a2230b80-a440-11eb-81fe-a9afc4997cd7.png)

**Comment by star7th** [comment]
网络搜索  php.ini session 保存目录怎么看。

**Comment by fluxlinkage** [comment]
我遇到了相同的问题，最后发现问题和session没有任何关系，是忘了安装PHP的sqlite3扩展。
我是Debian系统，使用如下命令：
sudo apt install php-sqlite3
然后
sudo service apache2 reload
问题就解决了。
希望有帮助。
