### ISSUE TITLE
又拍云上传 功能

### ISSUE THREAD

**Issue by ailcc** [star7th/showdoc#1311]
我的服务器太垃圾所以自己弄了个又拍云上传代码
小白写的大神请勿嘲笑
不怎么怎么贴代码
所以弄了个链接
Https://doc.ailcc.com/14

**Comment by star7th** [comment]
感谢主动贡献代码的精神哈。不过我可能现在不太需要。主要因为我觉得又拍云市场份额低，不是很有必要接入。下个月我会发一个版本支持腾讯云的。这样，showdoc就支持了国内主流的阿里云七牛云和腾讯云
