### ISSUE TITLE
导入xls文件成为新项目时，一次最多导入500行数据

### ISSUE THREAD

**Issue by james-med** [star7th/showdoc#1312]
请问有办法导入更多吗，还是哪里可以配置？

**Comment by star7th** [comment]
其实导入应该是全量导入了。只是显示的时候固定了是500行。
这个是组件缺陷。showdoc是引用这个组件的。而这个组件在一开始的时候需要指定初始化行数。我就指定了个常用的数字500
https://github.com/myliang/x-spreadsheet
要修改的话，修改这个文件的190行的500为其他数字。https://github.com/star7th/showdoc/blob/master/web_src/src/components/item/show/show_table_item/Index.vue 
改完后参考教程进行打包 https://www.showdoc.com.cn/help?page_id=1385576954326448

**Comment by james-med** [comment]
非常感谢，回复速度真是感人，佩服
