### ISSUE TITLE
后台首页搜索功能 英文搜索必须匹配大小写 

### ISSUE THREAD

**Issue by ailcc** [star7th/showdoc#1313]
后台首页搜索功能 英文搜索必须匹配大小写 
列如：我的文档标题是大写的ABC
但是我搜索时输入小写abc 就搜索不到文档！必须使用大写ABC才可以

**Comment by star7th** [comment]
这个问题下次发版的时候顺便修正。

**Comment by star7th** [comment]
我以为是我忘记了忽略大小写匹配。但是我试了下，没问题的。你提供下截图说明你的问题

**Comment by ailcc** [comment]
我是21年1月份之前的版本 一直没更新  
我改了下JS  
![image](https://user-images.githubusercontent.com/67769103/115951650-65c0df80-a514-11eb-9152-4b16271a5f46.png)

**Comment by star7th** [comment]
升级按照官方的教程来会好些。 https://www.showdoc.com.cn/help?page_id=13732
你上面截图的这个函数已经在新版废除。新版不再简单查询项目标题关键字，而是配合后台进行全局项目和文档内容搜索。

ailcc ***@***.***> 于2021年4月24日周六 下午3:48写道：

**Comment by ailcc** [comment]
好的  我下载个新版本  谢谢了
