### ISSUE TITLE
希望添加导出html 功能

### ISSUE THREAD

**Issue by DestinyHunter** [star7th/showdoc#1315]
像apizza 那样导出一个可不联网页面友好的网页. 项目交付的时候可以直接导出html 给客户

**Comment by star7th** [comment]
后面有时间再看看。先推荐使用word吧。

古月明 ***@***.***> 于2021年4月26日周一 上午10:00写道：

**Comment by star7th** [comment]
决定还是不做导出html功能了。开发成本太高，导出的html无法加载showdoc本身的样式。有离线需求还是建议导出word解决。
