### ISSUE TITLE
不想自动更新，本来白色好好的突然间就变成黑色了

### ISSUE THREAD

**Issue by kevennet** [star7th/showdoc#1316]

**Comment by star7th** [comment]
runapi不想花时间精力去维护版本差异，所以都是默认使用最新版。现在想主推黑色风格。如果你有其他建议和想法，可以说一下

oaio ***@***.***> 于2021年4月26日周一 上午11:15写道：

**Comment by star7th** [comment]
已经换回去了。重启后就自动更新完毕。
