### ISSUE TITLE
新版的runapi更新之后，运行比较卡

### ISSUE THREAD

**Issue by shanesyk** [star7th/showdoc#1317]
更新之后的runapi使用上比较卡，在文本框输入文字时都需要反应个一两秒才能出现文字，体验不太好，包括删除文字也是，希望能优化一下

**Comment by star7th** [comment]
当你的接口返回结果很多的时候，可能格式化代码会比较消耗性能。你检查一下是不是接口返回结果太多，同时打开的标签里这样的接口又很多。如果都没有，尝试重启下

shane ***@***.***> 于2021年4月26日周一 下午1:30写道：
