### ISSUE TITLE
导出功能在哪里 找个半天找不到

### ISSUE THREAD

**Issue by PataPon-coder** [star7th/showdoc#1318]

**Comment by star7th** [comment]
右侧栏，更多导出。其中，如果是runapi项目，则只能在runapi客户端导出。

PataPon-coder ***@***.***> 于2021年4月27日周二 上午11:59写道：

**Comment by PataPon-coder** [comment]
![image](https://user-images.githubusercontent.com/22774078/116183727-08fe3880-a751-11eb-869d-7efd38e725d1.png)

**Comment by PataPon-coder** [comment]
没有啊 我使用的是在线版

**Comment by star7th** [comment]
点击进入具体某个项目。然后才是右侧栏。

PataPon-coder ***@***.***> 于2021年4月27日周二 下午12:07写道：
