### ISSUE TITLE
预览功能改进建议

### ISSUE THREAD

**Issue by moobing** [star7th/showdoc#1319]
1.希望预览功能可以完整展示html渲染(或新增一个查看html)
2.将现在的预览改为Raw

**Comment by star7th** [comment]
嗯，这个不难改，晚点跟上。

**Comment by star7th** [comment]
我了解了下，好像没有改动的必要。
“美化”那个tab，如果遇到json，就会显示json。如果不是json，则会文本框显示原文本。所以我感觉没有必要额外增加一个raw，因为用能看到返回结果了。
至于html，现在的预览就是能渲染html代码的。这个只能这样用来小预览一下吧，那个小框，总不能展示跟浏览器一样，能预览知道个大概就行。

**Comment by star7th** [comment]
我也不清楚tp的判断机制。

gamedevil ***@***.***> 于2021年4月27日周二 下午10:05写道：

**Comment by star7th** [comment]
加上这个功能了。重启runapi可自动更新

**Comment by moobing** [comment]
收到~
