### ISSUE TITLE
英文环境下，部分文字显示中文

### ISSUE THREAD

**Issue by yinshangwei** [star7th/showdoc#1321]
![image](https://user-images.githubusercontent.com/20291587/116352138-4b924480-a827-11eb-95a3-f80c541aa00b.png)
![image](https://user-images.githubusercontent.com/20291587/116352155-52b95280-a827-11eb-8c81-142179239d20.png)

**Comment by star7th** [comment]
这个晚点改下。另外你这个什么浏览器，好像左侧栏错位了

Yin Shangwei ***@***.***> 于2021年4月28日周三 下午1:43写道：

**Comment by yinshangwei** [comment]
最新版chrome, macOS。

另外英文环境下，主页的菜单栏只有4个，比中文环境少2个。
![image](https://user-images.githubusercontent.com/20291587/116352597-facf1b80-a827-11eb-81a5-53b2f5306b44.png)

**Comment by star7th** [comment]
因为客户端不打算支持英文，维护多语言版本太麻烦了。所以英文版showdoc里把客户端的链接屏蔽了。

Yin Shangwei ***@***.***> 于2021年4月28日周三 下午1:45写道：

**Comment by yinshangwei** [comment]
另外，首页的item card，现在超过三个单词就显示不下了，能不能宽度调宽一点或支持换行。
![image](https://user-images.githubusercontent.com/20291587/116353099-c871ee00-a828-11eb-8897-fdff442357e4.png)

**Comment by star7th** [comment]
不不太考虑换行，因为觉得换行难看。这个也算是中英文差异吧。中文情况下，这个长度是可以起个简练的十字标题了的。英文的情况下，如果太长的话，建议填写你们的项目内部的英文缩写

Yin Shangwei ***@***.***> 于2021年4月28日周三 下午1:52写道：

**Comment by star7th** [comment]
你反馈的问题已解决。请更新新版

**Comment by star7th** [comment]
主要修复翻译问题和左侧栏错位问题
