### ISSUE TITLE
刚创建的项目写了接口保存了目录里没有

### ISSUE THREAD

**Issue by zaq11qaz** [star7th/showdoc#1323]
![image](https://user-images.githubusercontent.com/55392923/116498264-eea49600-a8db-11eb-9b26-0a56678a13f1.png)
刚创建的项目写了接口保存了目录里没有

**Comment by zaq11qaz** [comment]
刷新给刷没了

**Comment by star7th** [comment]
试着 runapi

zaq11qaz ***@***.***> 于2021年4月29日周四 上午11:15写道：

**Comment by star7th** [comment]
试着重启  runapi

Chen Xing ***@***.***> 于2021年4月29日周四 上午11:24写道：

**Comment by zaq11qaz** [comment]
为啥刚创建的项目不能写接口
还得重启
这是功能残疾啊

还有个问题
我只有一个目录和一个接口的时候
不能把这个接口拖入目录中
为啥刚创建的项目不能写接口
还得重启
这是功能残疾啊

还有个问题
我只有一个目录和一个接口的时候
不能把这个接口拖入目录中
![Uploading image.png…]()

**Comment by zaq11qaz** [comment]
![image](https://user-images.githubusercontent.com/55392923/116500204-a045c600-a8e0-11eb-8ff8-31515372ff8e.png)

**Comment by zaq11qaz** [comment]
![image](https://user-images.githubusercontent.com/55392923/116500245-b6538680-a8e0-11eb-8710-15496f317ea3.png)

**Comment by zaq11qaz** [comment]
![image](https://user-images.githubusercontent.com/55392923/116500265-c4a1a280-a8e0-11eb-816e-c5b7abdcfba1.png)

**Comment by star7th** [comment]
拖到目录上面，然后放开。

zaq11qaz ***@***.***> 于2021年4月29日周四 上午11:47写道：

**Comment by star7th** [comment]
拖到目录重叠，表示放进这个目录中。而不是目录的上方或者下方。

zaq11qaz ***@***.***> 于2021年4月29日周四 上午11:48写道：

**Comment by zaq11qaz** [comment]
拖到重叠了
没有用
只能放上面或者放下面
丢不进去

**Comment by zaq11qaz** [comment]
![image](https://user-images.githubusercontent.com/55392923/116500413-1b0ee100-a8e1-11eb-8142-b4927b786f7e.png)

**Comment by zaq11qaz** [comment]
两个以上文件的时候可以
2个的时候就是丢不进去

**Comment by zaq11qaz** [comment]
![image](https://user-images.githubusercontent.com/55392923/116500691-a38d8180-a8e1-11eb-9676-7f0cdc16e39d.png)
你看嘛俩都重叠了还是显示放上面或是下面

**Comment by star7th** [comment]
那可能是个bug了。假如你创建目录后，点击那个目录，然后在新建的接口会自动保存进目录里。一个接口+一个目录的时候可能是那里有问题了。我有时间在看。

**Comment by zaq11qaz** [comment]
嗷，看啥时候搞一下
么得体验
