### ISSUE TITLE
这个拖动也不行

### ISSUE THREAD

**Issue by zaq11qaz** [star7th/showdoc#1324]
![KVBGOR4RY$I8S58)QJ@E`96](https://user-images.githubusercontent.com/55392923/116515395-d3974d80-a8fe-11eb-82c7-5463996da4d6.png)

把最下面那个拉倒文件夹下面第一个无效

应该和之前的是一个问题

**Comment by zaq11qaz** [comment]
![image](https://user-images.githubusercontent.com/55392923/116515751-46a0c400-a8ff-11eb-81d4-e3d3008051b7.png)

奇了怪了
我这个接口怎么变文件夹了

**Comment by star7th** [comment]
同一个层级的情况下，接口固定在目录的上方.这个顺序即使调整了也会还原。这个是兼容showdoc历史遗留下的规则，接口都在同一个层级的的目录之上。但是可以拖到目录里面（这种就不算同一个层级了）

zaq11qaz ***@***.***> 于2021年4月29日周四 下午3:24写道：

**Comment by star7th** [comment]
如果是数据错误可以尝试重启runapi。但如果重启后还是这样的话，应该是你误操作了。runapi和showdoc的目录和页面是截然不同的两种类别，应该不会互串的。

zaq11qaz ***@***.***> 于2021年4月29日周四 下午3:27写道：

**Comment by zaq11qaz** [comment]
![image](https://user-images.githubusercontent.com/55392923/116516021-a7300100-a8ff-11eb-9d48-9376a738eccb.png)

嗷 我这个接口为啥一会变文件一会又变接口

**Comment by zaq11qaz** [comment]
![image](https://user-images.githubusercontent.com/55392923/116516276-01c95d00-a900-11eb-990a-fd1c065fbfab.png)

把一个接口拖到另一个接口上会使另一个变成文件夹
但是那个接口就没了

**Comment by zaq11qaz** [comment]
这个是新功能吗
变文件夹的那个接口就没了

**Comment by zaq11qaz** [comment]
![image](https://user-images.githubusercontent.com/55392923/116516603-5ec51300-a900-11eb-8801-5843bd1f9cb8.png)
完了拖到一起文档崩了

**Comment by zaq11qaz** [comment]
重启一下好了.

**Comment by star7th** [comment]
我不清楚你是怎么做的。我这边试了下，是无法拖动一个接口覆盖另一个接口的，也不会存在变目录的情况。这种情况出现了可能只是客户端渲染错了。但是后端不支持这种转换的

zaq11qaz ***@***.***> 于2021年4月29日周四 下午3:36写道：

**Comment by zaq11qaz** [comment]
嗷，那应该是前段的问题，刷新一下就恢复了
