### ISSUE TITLE
M1 macbook docker安装方式失败

### ISSUE THREAD

**Issue by CoderXiaohui** [star7th/showdoc#1326]
环境：Macbook M1  BigSur

![image](https://user-images.githubusercontent.com/17446149/116569828-568ac900-a93c-11eb-96f4-5c178cb03613.png)

**Comment by star7th** [comment]
官方镜像不支持M1 .如果要安装的话，只能自己去寻找兼容M1的php环境。装好环境后再手动安装showdoc，不用docker

XiaohuiDeng ***@***.***> 于2021年4月29日周四 下午10:44写道：
