### ISSUE TITLE
功能建议，表格excel相关功能建议

### ISSUE THREAD

**Issue by shuixin536** [star7th/showdoc#1328]
1. 支持在线协作
2. 表格 sheet页之间的复制粘贴
3. 支持office excel和showdoc excel表格之间的互相复制粘贴

非常感谢

**Comment by star7th** [comment]
这是个巨大的工程。腾讯文档石墨文档是一整个团队在做。只能看看有没有这样的开源组件，然后集成进showdoc。如果你有看到这样的开源组件，可以告诉我去调研一下。

shuixin536 ***@***.***> 于2021年4月30日周五 下午4:39写道：

**Comment by star7th** [comment]
其实在线实时协作的难点比较高。

**Comment by SwankyTigerYY** [comment]
> 其实在线实时协作的难点比较高。

不知道luckysheet能不能满足，它有了一套java的demo服务

**Comment by star7th** [comment]
@SwankyTigerYY 离生产可用还差蛮远的，官方在线demo都跑不通。我觉得这是个天坑，后面需要更新维护的东西还很多。以luckysheet不上心维护demo的态度，还是不引入此功能比较好。

**Comment by star7th** [comment]
@SwankyTigerYY 另外你应该指的是这个吧，我不知道我是否理解偏差。https://github.com/mengshukeji/LuckysheetServerStarter  这个项目似乎Luckysheet官方也没有继续维护下去了，最后更新是7个月前

**Comment by imchj** [comment]
https://github.com/mengshukeji/Luckysheet
【GitHub - mengshukeji/Luckysheet: Luckysheet is an online spreadsheet like excel that is powerful, simple to configure, and completely open source.】
指这个吗？
以下模板我试了，感觉好炫酷，不知道适用不。
https://mengshukeji.gitee.io/luckysheetdemo/
【Luckysheet】
https://mengshukeji.github.io/LuckyexcelDemo/
【Hello World!】

**Comment by star7th** [comment]
> https://github.com/mengshukeji/Luckysheet 【GitHub - mengshukeji/Luckysheet: Luckysheet is an online spreadsheet like excel that is powerful, simple to configure, and completely open source.】 指这个吗？ 以下模板我试了，感觉好炫酷，不知道适用不。 https://mengshukeji.gitee.io/luckysheetdemo/ 【Luckysheet】 https://mengshukeji.github.io/LuckyexcelDemo/ 【Hello World!】

我不明白你说的意思跟本主题有什么关系。如果是跟本主题相关的，可以补充说明。如果不是，请另开主题。
