### ISSUE TITLE
软件跨域问题 

### ISSUE THREAD

**Issue by hejiaz1** [star7th/showdoc#1329]
程序更新了fastadmin最新版本后发现runapi软件发送post请求报403跨域 
get请求好使
老版本fastadmin post好使

除了我本地的runapi软件之外  其他地方请求都是通的
也没个设置啥的 实在是懵逼了麻烦帮看看
线上地址   fastbase.nulli.cc/index.php/api/login/wxapplet/auth_login

用网页版是通的
![image](https://user-images.githubusercontent.com/54265500/116685845-8e018000-a9e5-11eb-9162-a98e35d84a7c.png)

就软件不好使
![image](https://user-images.githubusercontent.com/54265500/116685871-98237e80-a9e5-11eb-8943-60b7f4007e61.png)

**Comment by star7th** [comment]
关闭服务器端的csrf 安全限制

hejiaz1 ***@***.***> 于2021年4月30日周五 下午6:56写道：
