### ISSUE TITLE
权限问题：移除项目成员后，成员依然可以查看项目页面

### ISSUE THREAD

**Issue by luo863** [star7th/showdoc#1332]
项目成员保留了项目页面的链接，管理员移除成员后，成员刷新页面依然可见，只有成员退出登录后才会显示需要密码

**Comment by star7th** [comment]
听起来有点像旧版的机制。你尝试用最新版代码看是否还有此问题。

**Comment by luo863** [comment]
按照教程更新最新后，还没解决，不过退出浏览器，再进去，虽然不用登陆，直接输入链接也需要密码了

**Comment by star7th** [comment]
想起来了。以前是为了少读几次数据库，直接记住权限信息在session中了。现在我改了下。你更新即可。我主要是改动了这个文件 https://github.com/star7th/showdoc/blob/master/server/Application/Api/Controller/BaseController.class.php
