### ISSUE TITLE
phpstudy环境下如何快速配置代理

### ISSUE THREAD

**Issue by noRUSHnoLIFE** [star7th/showdoc#1334]
本地部署在phpstudy环境下，如何对项目进行代理设置以便本地二次开发？

**Comment by star7th** [comment]
配置代理有多种方式。使用fiddle工具，使用webpack本身的配置都可以。
一种快速的配置方法是，修改 web_src/config/index.js 文件，把proxyTable下server的配置从http://127.0.0.1/showdoc/ 改为你实际的基本url

**Comment by noRUSHnoLIFE** [comment]
已配置成功，谢谢

**Comment by qingmiaos** [comment]
这个已经配置了 打开还是没什么用
