### ISSUE TITLE
返回值自动转换为科学计数法

### ISSUE THREAD

**Issue by dlwss** [star7th/showdoc#1335]
正常的测试接口，返回值为"87960e22"时，会自动转换为 8.796e+26 这种科学计数法的形式，可以调用下面这个测试接口试下

`47.107.144.232/test`

**Comment by star7th** [comment]
我感觉这个问题跟程序是32位的有关。32位显示的数跟64位不一样。短期内无解吧。64位电脑能跑32位和64位程序，当时为了兼容，就统一之打包32位了

HelloPupil ***@***.***> 于2021年5月9日周日 上午10:43写道：

**Comment by dlwss** [comment]
好的，谢谢

**Comment by star7th** [comment]
runapi客户端已经改用64位版，可以支持大整数类型。卸载原客户端，然后去下载新的安装即可 https://www.showdoc.com.cn/runapi/30291
