### ISSUE TITLE
新用户注册成功后默认有几个文档，能否自定义？

### ISSUE THREAD

**Issue by anewhen** [star7th/showdoc#1337]
![image](https://user-images.githubusercontent.com/54468065/117637300-41236380-b1b4-11eb-9764-2b3ef5084a11.png)
如上图，这几个文档新用户注册后会有，能否自定义默认文档内容或者不展示？

**Comment by star7th** [comment]
showdoc的定位就是这些使用场景。如果你不需要这些示例文档，我想了解下你是将showdoc用于怎样的场景？

anewhen ***@***.***> 于2021年5月10日周一 下午5:22写道：

**Comment by anewhen** [comment]
我们用的表格更多一些，其他文档在里边大家会问，所以想隐藏掉初始化的时候其他的文档，只留下表格示例

**Comment by star7th** [comment]
都一样的，showdoc很多地方都有非表格项目的提示。例如新建项目的时候，例如团队管理按钮等等。会问你的好奇宝宝，最后也还是会问你，跟有没有示例差不多。另外就是，假如你是在管理后台添加了该用户，并且给这个用户加入了某个项目的成员，那么，该用户将不会再生成示例项目。只有当用户一进来，没有初始项目也没有其他人加给他的成员项目，系统才会创建示例项目。


anewhen ***@***.***> 于2021年5月10日周一 下午5:29写道：

**Comment by anewhen** [comment]
好的，明白了多谢。
