### ISSUE TITLE
私密项目分享后 输入密码无法访问

### ISSUE THREAD

**Issue by xuefulong** [star7th/showdoc#1339]
创建私密项目后，通过分享链接进入，然后输入密码，会一直停留在输入密码页面，无法打开。查看发现返回了错误信息
/server/index.php?s=/api/item/info       {"error_code":10303,"error_message":"不是项目创建者"}

**Comment by star7th** [comment]
我实测一切正常。确认下自己是不是完全按照官方方式去做升级的。另外升级到最新版看看还有没有问题。如果还有问题，请提供可重现的外网链接。否则我不能重现我无法提供任何帮助。

xuefulong ***@***.***> 于2021年5月12日周三 下午6:03写道：

**Comment by star7th** [comment]
是前段时间更新引起的bug。现在已经修复。你再更新下就好。

**Comment by xsfecho** [comment]
目前最新版 我也出现了这个问题。更新的最新版

**Comment by xsfecho** [comment]
> 是前段时间更新引起的bug。现在已经修复。你再更新下就好。

恢复了，我前面更新的是gitee版本的，现在更新了github的就ok了

**Comment by a894890640** [comment]
Releases里下载的2.9.1还是有这问题，试了不导入以前的数据，随便创建个私密项目，输入正确的密码，也是和xuefulong一样{error_code: 10303, error_message: "不是项目创建者"}

**Comment by star7th** [comment]
> Releases里下载的2.9.1还是有这问题，试了不导入以前的数据，随便创建个私密项目，输入正确的密码，也是和xuefulong一样{error_code: 10303, error_message: "不是项目创建者"}

下载master的最新代码。这个是新引进的小bug，已经在master修复。还没发Releases

**Comment by ailcc** [comment]
BaseController.class.php文件第188行 添加如下代码 就好了


		if (session("visit_item_".$item_id)) {
			return true;
		}
