### ISSUE TITLE
runapi开源最新版分享文档链接时输入正确密码无法跳转

### ISSUE THREAD

**Issue by Aoional** [star7th/showdoc#1340]
runapi开源最新版分享文档链接时输入正确密码无法跳转

**Comment by star7th** [comment]
我实测一切正常。确认下自己是不是完全按照官方方式去做升级的。另外升级到最新版看看还有没有问题。如果还有问题，请提供可重现的外网链接。否则我不能重现我无法提供任何帮助。

**Comment by star7th** [comment]
忘记说了就关闭了。是前段时间更新引起的bug。现在已经修复。你再更新下就好。
