### ISSUE TITLE
附件的下载地址问题？

### ISSUE THREAD

**Issue by Zze0** [star7th/showdoc#1341]
最近重新部署了ShowDoc。发现现在附件的下载地址有所变化，导致浏览器不能直接预览PDF和图片之类的。

现在下载链接是 /server/index.php?s=/api/attachment/visitFile/sign/44474cdad3513e078000935ee6d8bc13

以前是：/Public/Uploads/2021-05-13/609c7b0f98634.jpg

所以可以在浏览器直接预览。

想问下通过怎么样的设置可以直接定位到文件实际路径？

**Comment by star7th** [comment]
现在没有这样的设置。后面我再根据文件扩展名做区别处理

Zze0 ***@***.***> 于2021年5月13日周四 上午9:10写道：

**Comment by Zze0** [comment]
看起来应该是为了兼容oss的时候，改造了这个功能吧？

**Comment by star7th** [comment]
主要是把oss和本地文件都统一起来，方便管理和统计

Zze0 ***@***.***> 于2021年5月13日周四 上午9:37写道：

**Comment by Zze0** [comment]
好的，谢谢，希望后面能对本地文件有个预览的功能，直接浏览器打开路径就好了：/Public/Uploads/2021-05-13/609c7b0f98634.jpg

**Comment by star7th** [comment]
已发布新版，解决了此问题。

**Comment by Zze0** [comment]
实测可行，谢谢。
