### ISSUE TITLE
showdoc存在一个漏洞

### ISSUE THREAD

**Issue by icexk** [star7th/showdoc#1342]
你好，隔一段时间会自动出现一个PHP木马文件，之前用的外网IP，改为内网IP后还是出现这个问题

运行环境：centos系统docker运行，showdoc是比较老的一个版本
木马文件路径: /proc/21822/root/var/www/html/Public/Uploads/2021-05-13/609c95ea7ed20.php
首次发现时间: 2021-05-13 10:58:58
更新时间: 2021-05-13 10:58:58
木马类型: Webshell
容器名: showdoc
镜像名: showdoc:latest
容器内部路径: /var/www/html/Public/Uploads/2021-05-13/609c95ea7ed20.php
请问更新新版本能不能解决？

**Comment by star7th** [comment]
更新版本能解决。历史已经被上传的附件需要自己处理。

icexk ***@***.***> 于2021年5月13日周四 上午11:28写道：

**Comment by star7th** [comment]
把.php后缀的附件全干掉

Chen Xing ***@***.***> 于2021年5月13日周四 上午11:29写道：

**Comment by icexk** [comment]
好的，谢谢

**Comment by xuhongbo** [comment]
@star7th 可以告知下在哪个commit修复的吗？

**Comment by cute-angelia** [comment]
更新，sqlite 文件不兼容，没法更新了。。。。。痛苦啊

**Comment by cute-angelia** [comment]
找到了

![image](https://user-images.githubusercontent.com/26561606/162109639-de0891fd-3fc2-4807-af2d-316fc5bde512.png)

**Comment by cute-angelia** [comment]
> @star7th 可以告知下在哪个commit修复的吗？

**Comment by star7th** [comment]
不是一次commit解决的。是多次断断续续修复。
不更新的最新版的话，不再维护旧版。

**Comment by star7th** [comment]
关于更新不兼容的问题，请新开问题且把问题描述清楚。
