### ISSUE TITLE
runapi客户端返回数据显示问题

### ISSUE THREAD

**Issue by xixigou** [star7th/showdoc#1343]
作者，你好。
是否有计划将接口返回的数据，将json数据编码后展示出来，或者提供返回的格式供选择？

比如下面：message的中文是：请先登录

服务器返回了状态码401，内容如下：
{"status":"error","code":401,"timestamp":1620878140,"once":"7Uxqdu8hh","message":"\u8bf7\u5148\u767b\u5f55"}

**Comment by star7th** [comment]
这个后面会修复下

万军 ***@***.***> 于2021年5月13日周四 下午12:01写道：

**Comment by star7th** [comment]
已修复。重启runapi就会自动更新完毕。
