### ISSUE TITLE
docker 安装完成之后登陆时无法显示验证码

### ISSUE THREAD

**Issue by yang0009** [star7th/showdoc#1344]

**Comment by yang0009** [comment]
无法显示图片验证码

**Comment by star7th** [comment]
我测试了下，没有这个问题。也没有其他人反馈这个问题。所以我不清楚你什么情况。请提供外网可重现场景看看。

**Comment by yang0009** [comment]
我用的是dockerhub源

**Comment by yang0009** [comment]
> 我测试了下，没有这个问题。也没有其他人反馈这个问题。所以我不清楚你什么情况。请提供外网可重现场景看看。

我用的是dockerhub源

**Comment by yang0009** [comment]
> 我测试了下，没有这个问题。也没有其他人反馈这个问题。所以我不清楚你什么情况。请提供外网可重现场景看看。

安装下面国内源的确没有问题

**Comment by star7th** [comment]
刚刚去测试了下，dockerhub源也没问题。
另外注意，用户登录页面默认是不显示验证码的。只有输入密码多次错误才会要求输入验证码。

**Comment by yang0009** [comment]
好的,我用国内源了,暂时没啥问题
