### ISSUE TITLE
返回参数说明 建议

### ISSUE THREAD

**Issue by zhouwenjun315** [star7th/showdoc#1349]
建议 返回参数说明 快速生成支持 点 结构    例如 desc_data.title   area_desc.title  因为返回参数中可能是多对象  然后对象里面的参数可能会一致,, 然后快速生成会自动去重,,,还有层级关系很不明显,,容易误解
![image](https://user-images.githubusercontent.com/18712897/118420254-ff814400-b6f0-11eb-8614-73317bcb1fd5.png)

**Comment by star7th** [comment]
这个后面探索下

**Comment by star7th** [comment]
已经实现此功能。重启runapi便会自动更新完毕。

**Comment by zhouwenjun315** [comment]
好的,谢谢了哦
