### ISSUE TITLE
浏览器上保存超过5449字符提示没有权限

### ISSUE THREAD

**Issue by mairoot** [star7th/showdoc#1350]
问题：一旦超过5449字符，保存的时候弹出【没有权限】提示框。小于5449字符则可以保存。
环境：docker部署showdoc版本是v2.3.0。
问题截图：![image](https://user-images.githubusercontent.com/23660039/118425671-3f015d80-b6fc-11eb-9eb4-01a56a682653.png)
通过参照提问 https://github.com/star7th/showdoc/issues/1140 并没有解决。
上述链接提问所说的php和nginx本身的上传大小限制增大3-5倍没有起作用，查看上传的文本大小大概为2k左右。
还使用postman来测试操作，一样的参数和内容，是能保存成功的，而在浏览器（使用过chrome和火狐）上就不行，提示没有权限。

**Comment by star7th** [comment]
先升级到最新版，有问题再反馈。

麦子稻草 ***@***.***> 于2021年5月17日周一 上午10:45写道：

**Comment by mairoot** [comment]
好的。
