### ISSUE TITLE
通过NAT访问页面时，图片打不开。建议图片用相对路径。

### ISSUE THREAD

**Issue by rockycao** [star7th/showdoc#1351]
在局域网ADSL路由器上，为showdoc服务器设置NAT。
例如：外网通过 http://test.cc:999/web/#/5?page_id=195
           实际访问到 http://192.168.0.5/web/#/5?page_id=195

在外网可以访问页面，但是看不到页面中的图片。
如果图片是相对路径/server/index.php?s=/api/attachment/visitFile/sign/eacebae55c8e782fb8d6ba4a6a89ce98就好了。

**Comment by star7th** [comment]
对于绑定域名，不能简单地就这么转发。还需要把请求host带过去。对于nginx，这样设置： https://github.com/star7th/showdoc/issues/573  
对于你的NAT，我不知道怎么设置。但最终实现的效果就是跟nginx那样把host带过去。

**Comment by star7th** [comment]
更新：showdoc管理后台可配置网址外部访问地址。它会作为附件链接的前缀。
