### ISSUE TITLE
Runapi 发送请求出现的问题

### ISSUE THREAD

**Issue by Xrtero** [star7th/showdoc#1352]
OS： windows10
环境 ： runapi 客户端，自搭建服务

描述：
发送指令： post  http:/mock地址/api地址 
使用runapi发送，响应体出现no such path
使用浏览器发送get请求, 出现正常mock数据

望答复

**Comment by star7th** [comment]
showdoc服务端先升级到最新版。有问题再反馈。

Xrtero ***@***.***> 于2021年5月17日周一 下午8:08写道：

**Comment by star7th** [comment]
另外我看了下代码。请确保你发起post请求没有同时传送冲突的参数名，比如path。还有就是把完整url放出来看是不是对的。

**Comment by Xrtero** [comment]
请求地址： http://服务器ip地址/server/index.php?s=/mock-path/12&amp;amp;path=/admin/user
以下是浏览器请求的
````
request:
Request URL: http://121.40.157.169:4999/server/index.php?s=/mock-path/12&path=/admin/login
Request Method: GET
Status Code: 200 OK
Remote Address: 127.0.0.1:7890
引用站点策略: strict-origin-when-cross-origin
resposne: 
{"code":"00000","data":"{}","message":"sucess"}
````
runapi 就直接没找到这个请求路径了

**Comment by star7th** [comment]
我不知道是你自己写错还是怎样，这个url错了，&amp;amp字符是怎么来的

**Comment by Xrtero** [comment]
我也不知道怎么来的，是我写错了。
是这个url ： http://ip/server/index.php?s=/mock-path/12&path=/admin/login

**Comment by star7th** [comment]
已修复此问题。将showdoc服务端升级到最新版即可

**Comment by Xrtero** [comment]
好，辛苦了.
