### ISSUE TITLE
图片怕爬虫爬取

### ISSUE THREAD

**Issue by lanboss** [star7th/showdoc#1353]
虽然网站内容有登录限制，不能不能看到项目里的内容，但不了解爬虫的原理和工作方式，纯外行咨询资料外泄风险，图片访问本身没有限制，仅是一个公开的网址链接，任何人网址一敲就能看到图片，虽然图片名难猜，但爬虫持续工作会不会把网站所有图片都盗走了

**Comment by star7th** [comment]
showdoc的图片url已经是加密串了，这种情况被爬取没办法。 这种情况只能建议放在内网。

fighting ***@***.***> 于2021年5月18日周二 上午10:00写道：
