### ISSUE TITLE
路径参数问题

### ISSUE THREAD

**Issue by Xrtero** [star7th/showdoc#1355]
请问 runapi 中有没有路径参数
比如说这个：
![image](https://user-images.githubusercontent.com/55886907/118666020-6869d880-b825-11eb-9a04-edf967e42d17.png)
{uid} 就为路径参数

**Comment by star7th** [comment]
环境与变量那里可以添加变量。然后变量可以通过冒号的方式引用。详情查看环境变量旁边的帮助说明按钮

Xrtero ***@***.***> 于2021年5月18日周二 下午10:08写道：

**Comment by star7th** [comment]
像你截图里的那个样子，要把路径变量做表格展开的， 这个功能还真没有。也不知道是否有必要改。这个改动还不小。

**Comment by Xrtero** [comment]
也可以换一个方式。
![image](https://user-images.githubusercontent.com/55886907/118820295-b85da380-b8e8-11eb-80a7-b8045c105e9a.png)
直接在这个后面加一个路径参数选项卡

**Comment by Xrtero** [comment]
会变成这个: `&amp;`

**Comment by star7th** [comment]
> 也可以换一个方式。
> ![image](https://user-images.githubusercontent.com/55886907/118820295-b85da380-b8e8-11eb-80a7-b8045c105e9a.png)
> 直接在这个后面加一个路径参数选项卡

路径参数不会经常用到，所以我不太倾向"加一个路径参数选项"这种百分比给所有人看到的交互方式。

**Comment by Xrtero** [comment]
> > 环境变量还有一个小bug。
> > 环境：
> > windows10+runapi
> > 出现的地方:
> > 添加变量之后会和原来输入的不一样。
> > 比如：
> > & 与符号会变成 & 这应该是&的转义符。
> 
> 为了安全，runapi与showdoc的所有参数都会经过html转义。我不太确定变量里支持特殊符号是不是有必要。

是这样的，我想添加一个mock地址的变量。 由于mock地址里面有`&`这个符号，转义之后会变成`%amp`。 这样会导致变量是错误的。
当我想用这个环境变量测试的时候就不能用了。

**Comment by star7th** [comment]
mock不支持变量

Xrtero ***@***.***> 于2021年5月19日周三 下午9:50写道：

**Comment by Xrtero** [comment]
我知道mock不支持的。

这是Mock地址： http://ip/server/index.php?s=/mock-path/12&path=

我想添加一个环境变量为A , A 的值为mock地址。

当我把这一串设置为环境变量。其中的`&`符号会转义成`&amp`

这样会导致使用的mock地址是错误的。 当我在地址栏使用这个环境变量并发送一个GET指令会导致找不到这个路径。

**Comment by Xrtero** [comment]
![image](https://user-images.githubusercontent.com/55886907/118827404-ec3bc780-b8ee-11eb-8154-2532262eb0ed.png)
比如这个地址
basePath 不是正确的mock地址

**Comment by star7th** [comment]
> ![image](https://user-images.githubusercontent.com/55886907/118827404-ec3bc780-b8ee-11eb-8154-2532262eb0ed.png)
> 比如这个地址
> basePath 不是正确的mock地址

已经对变量进行html反转义。重启runapi即可更新。

**Comment by star7th** [comment]
补充一下，原来的路径变量用法不太规范，已经废弃。
新版的路径变量的使用方式是：
在url里，使用冒号符号链接（跟postman的路径变量用法一致）。当存在路径变量时候，在Query标签页将出现一个列表让你填写路径变量的值（这一点的交互也跟postman类似）
