### ISSUE TITLE
建议：Runapi和Showdoc中，Json数据分层级显示

### ISSUE THREAD

**Issue by shanesyk** [star7th/showdoc#1356]
现在的json数据在显示的时候，没有按照层级来显示，对于前端开发者来说，看起来不是很清楚；并且如果不同的层级中有同名的字段，在参数说明内却只显示一个，其他层级的这个字段就会不显示，还需要再手动将其添加进去，希望能进一步优化一下，感谢！！！

**Comment by star7th** [comment]
有人建议用点号来展示。比如说data.id 。但我还在想怎么做才比较合适。目前没有太明确的解决方案

**Comment by Xrtero** [comment]
可以试一试yapi那样的

**Comment by shanesyk** [comment]
runapi可以试试yapi那种折叠的方式，但是自动生成的showdoc文档里面是不是没有办法使用折叠来展示，或者是否可以考虑在生成showdoc文档的时候使用缩进来展示呢？

**Comment by star7th** [comment]
我最终选择的方案是：
快速生成参数描述那里，点击生成后，会用点号来表示层级关系。比如说data.id  ,data.pages.id

**Comment by star7th** [comment]
重启runapi即可更新。

**Comment by shanesyk** [comment]
ok，非常感谢！

**Comment by dxkrs** [comment]
mac的3.0.6版本是不是还没更新这一点？

**Comment by star7th** [comment]
mac的早就更新了

**Comment by dxkrs** [comment]
不见得是噢，@star7th
```
{
    "error_code": 0,
    "test":{
      "a":123,
      "b":456
    },
    "data": [
        {
            "id": "28241",
            "code": "4401",
            "parentid": "44",
            "name": "广州市",
            "level": "2"
        },
        {
            "id": "28421",
            "code": "4402",
            "parentid": "44",
            "name": "韶关市",
            "level": "2"
        },
        {
            "id": "28558",
            "code": "4403",
            "parentid": "44",
            "name": "深圳市",
            "level": "2"
        }
    ]
}
```

[![imagee61688a306ef4090.png](https://s1.imagehub.cc/images/2023/09/22/imagee61688a306ef4090.png)](https://s1.imagehub.cc/images/2023/09/22/imagee61688a306ef4090.png)

**Comment by star7th** [comment]
@dxkrs 设计如此，第一层 ，以及第二层的索引为0 的时候，字段会被打平。
你多试一下深层数据结构吧。

**Comment by dxkrs** [comment]
@star7th  再试了一下，发现现在的设计逻辑应该是“无论哪一层遇到数字索引就打平“以及“第二层不会用点号连接第一层”。局限于现用的md渲染器，可能对层级的“缩进”或“折叠”展示实现有点困难，但点号设计也应该全展示层级关系：对object关系全显示，array关系则可打平。对接文档开发的时候最着重这个返回参数说明部分，且多数都是二层结构，当返回参数多起来的时候，就乱套了。

**Comment by dxkrs** [comment]
比如：
```
{
"other_data":[
    {
            "id": "28558",
            "code": "4403",
            "parentid": "44",
            "name": "深圳市",
            "level": "2"
      }
],
"data": [
        {
            "id": "28241",
            "code": "4401",
            "parentid": "44",
            "name": "广州市",
            "level": "2"
        },
        {
            "id": "28421",
            "code": "4402",
            "parentid": "44",
            "name": "韶关市",
            "level": "2"
        }
    ]
}
```

**Comment by star7th** [comment]
这种极端情况不管了，极少人会这样返回数据。

RaysonLu ***@***.***>于2023年9月22日 周五下午3:43写道：

**Comment by star7th** [comment]
我更觉得，你应该把所有业务数据都放进  data 里。然后 data 里如果分数据类型，再分成两个数组。

Chen Xing ***@***.***>于2023年9月24日 周日上午1:24写道：

**Comment by dxkrs** [comment]
@star7th 尊重你的选择，我也只是参考市面其他商业产品结合几个团队的使用情况得出的见解，anyway你可以当作这是一个更具有兼容性的可行改进建议。期待会有这部分功能的相关改进。
