### ISSUE TITLE
有bug

### ISSUE THREAD

**Issue by zaq11qaz** [star7th/showdoc#1357]
![image](https://user-images.githubusercontent.com/55392923/118911263-7f5d1780-b958-11eb-9863-dd87ac493133.png)

**Comment by zaq11qaz** [comment]
![image](https://user-images.githubusercontent.com/55392923/118911389-b0d5e300-b958-11eb-8c2f-7dcd35d3815f.png)
我docker命令装的怎么还不是最新版

**Comment by zaq11qaz** [comment]
啥啊更新完环境变量不能用了

**Comment by zaq11qaz** [comment]
![image](https://user-images.githubusercontent.com/55392923/118911527-e67acc00-b958-11eb-8309-aefdab721b7b.png)
今早才更新的

**Comment by star7th** [comment]
看你历史记录，命令是执行了，但是我不知道这过程中是不是哪里出错了。没有返回信息，判断不了。

zaq11qaz ***@***.***> 于2021年5月20日周四 上午10:48写道：

**Comment by star7th** [comment]
我觉得你是更新错了。导致源文件不在/showdoc_data/html 这个目录下。当这个目录不存在文件的时候，docker会从镜像中拉取很久的一个版本来覆盖。你要检查下，为什么看github下载的文件没在/showdoc_data/html 里。

**Comment by zaq11qaz** [comment]
[21_05_20.log](https://github.com/star7th/showdoc/files/6512617/21_05_20.log)

**Comment by zaq11qaz** [comment]
搁哪看日志

**Comment by star7th** [comment]
这个日志没空。不是runapi使用的问题。是你的showdoc服务器端没升级好。你先登录网页端，看看功能正常不，明显不是最新版，不正常。

**Comment by star7th** [comment]
> 我觉得你是更新错了。导致源文件不在/showdoc_data/html 这个目录下。当这个目录不存在文件的时候，docker会从镜像中拉取很久的一个版本来覆盖。你要检查下，为什么看github下载的文件没在/showdoc_data/html 里。
根据这个来排查下

**Comment by zaq11qaz** [comment]
![image](https://user-images.githubusercontent.com/55392923/118914284-863a5900-b95d-11eb-8356-136ea925d008.png)
![image](https://user-images.githubusercontent.com/55392923/118914290-89cde000-b95d-11eb-9f9b-71b557f1ede6.png)

**Comment by zaq11qaz** [comment]
什么东西没有

**Comment by star7th** [comment]
先重命名原来的/showdoc_data/html_bak文件为/showdoc_data/html还原吧。然后再重新升级。
这次升级还有问题的话，把整个命令行过程出现的返回信息都给我看下

**Comment by zaq11qaz** [comment]
好的

**Comment by zaq11qaz** [comment]
![image](https://user-images.githubusercontent.com/55392923/118920127-593f7380-b968-11eb-89d2-b2512e477ce8.png)
这是什么问题

**Comment by star7th** [comment]
所以问题比较清晰了。你的网络问题导致下载的文件不完整，docker镜像里找不到完整程序文件，就用默认的旧版本代码覆盖了。
你可以尝试在自己电脑上手动下载github上的文件然后自己上传到/showdoc_data/html 去，或者使用代理解决网络问题

**Comment by zaq11qaz** [comment]
好的
