### ISSUE TITLE
自动生成数据字典

### ISSUE THREAD

**Issue by yinshangwei** [star7th/showdoc#1358]
有没有计划让自动生成数据字典支持postgresql数据库？

**Comment by star7th** [comment]
这个是个未定数。有空看下吧。如果要支持其他数据库类型，那就需要重写现在的自动生成脚本才行。我突然想到的一种通用做法是每个数据库的表都导出一个create table语句，然后从语句里生成到showdoc。这个后面探索下。

**Comment by star7th** [comment]
这个用纯命令行是难以做到的。我有空探索下go来实现，然后打包成一个二进制执行文件。

**Comment by star7th** [comment]
现在已经有了一个第三方开发者做了项目，支持自动生成postgresql数据库数据字典到showdoc  https://github.com/whaios/showdocdb
