### ISSUE TITLE
最新的是这个9.8M的包吗

### ISSUE THREAD

**Issue by zaq11qaz** [star7th/showdoc#1359]
我windos下下了后拉到linux上重新装还说不是最新版
![image](https://user-images.githubusercontent.com/55392923/118924305-7a579280-b96f-11eb-8fd2-6b91648dd291.png)
![image](https://user-images.githubusercontent.com/55392923/118924334-85122780-b96f-11eb-90f0-b0f6ef914094.png)
![image](https://user-images.githubusercontent.com/55392923/118924351-8cd1cc00-b96f-11eb-8e2b-cd38e0f0e731.png)
最新版不是直接用这个 https://github.com/star7th/showdoc/archive/master.tar.gz 下的吗

**Comment by zaq11qaz** [comment]
![image](https://user-images.githubusercontent.com/55392923/118924467-b7238980-b96f-11eb-9c72-ee386803aa14.png)
![image](https://user-images.githubusercontent.com/55392923/118924520-c7d3ff80-b96f-11eb-9071-eb5cf20ffd2c.png)

**Comment by star7th** [comment]
分别执行 下面两条命令看各自返回什么内容

cat /showdoc_data/html/composer.json

curl http://127.0.0.1:4999/composer.json

**Comment by zaq11qaz** [comment]
![image](https://user-images.githubusercontent.com/55392923/118925560-83496380-b971-11eb-8384-030f4e037a3a.png)

**Comment by star7th** [comment]
你自己搞错了吧。你尝试下载https://github.com/star7th/showdoc/archive/master.tar.gz ，然后直接打开这个压缩包的composer.json 。里面的version字段很明显不是你截图的这个。你自己都没有更新最新代码到服务器

**Comment by star7th** [comment]
你自己折腾一下。一直到我给你发的这两行命令，其返回内容中的version字段为v2.9.1 。当前最新版是2.9.1

**Comment by zaq11qaz** [comment]
奥，我整一下

**Comment by zaq11qaz** [comment]
我好了，直接拿docker整个卸了重新拉镜像就可以了 ，下面介绍不如直接写docker删除镜像重新下载安装
![image](https://user-images.githubusercontent.com/55392923/118929198-cc4fe680-b976-11eb-965f-0a34f23d23eb.png)

**Comment by zaq11qaz** [comment]
![image](https://user-images.githubusercontent.com/55392923/118929310-eb4e7880-b976-11eb-8740-9b6a5f763895.png)
这下包给我整迷了，直接重新下镜像就可以的
