### ISSUE TITLE
如何在不同项目间复制文件或文件夹

### ISSUE THREAD

**Issue by yinshangwei** [star7th/showdoc#1360]
我知道新建项目的时候可以选择导入或者复制一个已经存在的项目，但如何才能在已经创建的项目上，将另一个项目的文件或文件夹批量复制过来？

**Comment by star7th** [comment]
1，将showdoc更新到最新版。
2，进入目录管理，可以复制或者移动目录到其他项目去

**Comment by ailcc** [comment]
> 1，将showdoc更新到最新版。
> 2，进入目录管理，可以复制或者移动目录到其他项目去

复制文件夹还好 移动文件夹 文件夹里的文档就被删除了呀   能否连文件夹里的文档一起移动到新的项目中呢

**Comment by star7th** [comment]
本来就是将文档一起移动。

ailcc ***@***.***> 于2021年5月20日周四 下午5:34写道：

**Comment by ailcc** [comment]
对对对  确实是一起移动的 是我改数据库导致出现了问题 用初始数据库是没问题的
