### ISSUE TITLE
关于密码重置的漏洞问题

### ISSUE THREAD

**Issue by mewchen** [star7th/showdoc#1361]
今天发现了1个密码重置问题，我把数据库复制到新版showdoc依旧能复现。但是完全部署一套新的（数据库也用新的）以后，暂时无法复现，我也不清楚是什么问题导致，先把能复现的复现流程写一下：

1. 通过SQLite 工具，把showdoc账号改名；
2. 访问 user/resetPasswordByUrl；
3. 输入密码123456提交，不用管错误信息；
4. 返回用户登录，输入showdoc/123456 即可进行登录；

只要数据库中存在showdoc的账号，就不会有这个问题。

**Comment by star7th** [comment]
为了兼容历史，showdoc规定死了管理员必须是showdoc账户。如果不存在此账户，会插入并且设置密码为123456。

mewchen ***@***.***> 于2021年5月20日周四 下午4:03写道：
