### ISSUE TITLE
新建项目的BUG

### ISSUE THREAD

**Issue by ailcc** [star7th/showdoc#1362]
开源版也有这个问题   官方版也有
账户登录后   新建项目时，复制下面的地址到浏览器打开 然后刷新 就会生成项目  刷新一下生成一下！
https://www.showdoc.com.cn/server/index.php?s=/api/item/add

**Comment by star7th** [comment]
这个问题不算bug，忽略。没有人会刻意这么干。会这么刻意干的人，就不再是正常用户了。我只要在项目总数做限制就行，中间过程他爱怎么创建就怎么创建。

**Comment by ailcc** [comment]
有道理
