### ISSUE TITLE
开源版注册时查询用户名是否重复时 用全大写可以注册相同用户名

### ISSUE THREAD

**Issue by ailcc** [star7th/showdoc#1364]
开源版注册时查询用户名是否重复时 用全大写可以注册相同用户名
比如我注册用户名为全小写或部分大写  Baidu
然后再次注册时 用户名为 baidu  
就能注册成功！

**Comment by star7th** [comment]
用户名区分大小写。

**Comment by star7th** [comment]
理论上大小写不同的是不同的一个账号

**Comment by ailcc** [comment]
有道理  
但是不能否认可能会出现2个用户注册的用户名除了大小以以外 没有其他区别 
而用户自己忘记了大小写   疯狂找回小写用户名密码的情况  
只是几率非常小

**Comment by star7th** [comment]
那种情况只能忽略了。通常情况下用户注册统一使用小写用户名比较好，实际上大部分场景也是小写。
