### ISSUE TITLE
项目分组功能能否限制项目只能分给一个分组 或

### ISSUE THREAD

**Issue by ailcc** [star7th/showdoc#1366]
项目分组功能能否限制项目只能分给一个分组 或者在添加分组文章的界面中 项目名称前提示该项目已有的分组名称

**Comment by ailcc** [comment]
然后项目分组里面 添加项目时  建议做一个分页功能  文档太多的时候 下拉框就太长了

**Comment by star7th** [comment]
其实现在的分组功能更像是标签功能。应该允许用户重复添加项目，以起到分类查看的目的。比如有些公共项目既属于A也属于B。
你说的第一个问题更像是历史遗留问题。一般如果是从头开始的话，会知道新加的项目应该加到哪个分组。所以第一个问题我倾向于不做改动。
第二个问题，由于项目是要铺开给用户选择的，这个时候摊开在同一页会合适一点。分页反而不好选。而且当用户进来修改时候，还得切换到不同分页才能查看这个分组下的项目。不合适。

**Comment by star7th** [comment]
等后面再看看其他用户有没有反馈说要改这个交互吧。目前我倾向于保持现状。

**Comment by ailcc** [comment]
收到 谢谢解答
