### ISSUE TITLE
分享密码无效

### ISSUE THREAD

**Issue by sololibra** [star7th/showdoc#1367]
设置文档分享密码 , 输入密码后提示密码错误

**Comment by star7th** [comment]
实测没有这个问题。我觉得你确实是输入错密码了

**Comment by sololibra** [comment]
谢谢!
docker删除容器 , 删除所有数据 , 重新部署 , 恢复数据 , 功能恢复正常




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月27日(星期四) 上午10:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [star7th/showdoc] 分享密码无效 (#1367)





 
实测没有这个问题。我觉得你确实是输入错密码了
