### ISSUE TITLE
给项目中用户只能分配一个目录的权限，可以多个吗

### ISSUE THREAD

**Issue by lhyxcxy** [star7th/showdoc#1369]
![image](https://user-images.githubusercontent.com/22721389/119928284-de044000-bfad-11eb-8198-582f03c758cb.png)

**Comment by lhyxcxy** [comment]
可以选择多个目录吗

**Comment by star7th** [comment]
目前只支持一个目录。

freedom ***@***.***> 于2021年5月28日周五 下午12:12写道：
