### ISSUE TITLE
docker部署的怎么备份数据库？

### ISSUE THREAD

**Issue by wly314** [star7th/showdoc#137]
我用Docker部署了showdoc，但是查看Sqlite/showdoc.db.php的时候，新增的用户不存在，不知道是不是docker用镜像的原因，应该怎么操作？

**Comment by star7th** [comment]
数据是放在镜像中的Sqlite/showdoc.db.php。
你可以考虑安装命令行工具进入镜像里面，也可以把整个镜像拷贝

**Comment by wly314** [comment]
容我搜一下怎么玩Docker，刚学会弄Docker。
哥哥的问题响应速度我给100分。
