### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by liuweitian** [star7th/showdoc#1370]
服务器重启后无法启动，报错如下
root@server:/opt/showdoc_web# ./showdoc start
Error response from daemon: driver failed programming external connectivity on endpoint showdoc (847090c26e9038a22728e1584af88667101e5375cbb871d25d09aaed2de0beb7): Error starting userland proxy: listen tcp6 [::]:4999: socket: address family not supported by protocol
Error: failed to start containers: showdoc

尝试重启了docker，无效
手动启动容器，一样的报错

**Comment by star7th** [comment]
感觉是你的docker服务没好。你尝试docker安装个其他镜像看能否正常转发端口。

**Comment by liuweitian** [comment]
> 感觉是你的docker服务没好。你尝试docker安装个其他镜像看能否正常转发端口。

找到问题了，我把docker给更新了，是新版本的docker有问题
卸载docker，然后回滚到20.10.5就好了
```
# 卸载
apt-get purge docker-ce docker-ce-cli containerd.io
# 安装
apt-get install docker-ce=5:20.10.5~3-0~ubuntu-bionic docker-ce-cli=5:20.10.5~3-0~ubuntu-bionic containerd.io
```

**Comment by liuweitian** [comment]
新版本(20.10.6)docker有问题
卸载后回退到20.10.5即可，卸载时注意备份
# 相关提问
https://forums.docker.com/t/ipv6-disabled-on-my-computer-but-docker-network-seems-looking-for-it/107299/15
# 卸载
apt-get purge docker-ce docker-ce-cli containerd.io
# 安装
apt-get install docker-ce=5:20.10.5~3-0~ubuntu-bionic docker-ce-cli=5:20.10.5~3-0~ubuntu-bionic containerd.io
