### ISSUE TITLE
管理员应该可以管理所有项目吧

### ISSUE THREAD

**Issue by DestinyHunter** [star7th/showdoc#1371]
目前. 只能看到自己创建的

**Comment by star7th** [comment]
在项目管理界面可以看到所有的。

古月明 ***@***.***> 于2021年5月31日周一 上午11:29写道：

**Comment by DestinyHunter** [comment]
不是呀,项目管理只是能看到醒目列表.项目创建人设置密码的话.我不知道是看不了,  应该有超级管理吧. 这个用户是无视权限的, 登录进去 在这个页面 
![image](https://user-images.githubusercontent.com/20897838/120154137-1dd35d80-c222-11eb-8f36-c411aa864543.png)
可以列出系统所有的项目. 并且可以查看编辑

**Comment by star7th** [comment]
系统管理员和项目管理员分开。
你可以选择转让项目给你自己。让这个项目成为自己 的项目。然后用项目管理员的身份访问

**Comment by DestinyHunter** [comment]
我作为管理员我应该有这个系统的超级权限.包扩所有普通用户的项目.我都应该可以查看编辑. 没有超级管理的话. 我作为系统管理者,查看已不再就职的人员,或者普通用户没有在线,需要给不是我创建的项目添加人员的话,还需要把目标项目转让给我,在添加上普通人员,当有很多个项目需要操作话,是不友好的. 我认为需要一个超级管理用户, 他拥有这个系统的绝对控制权,

**Comment by star7th** [comment]
> 我作为管理员我应该有这个系统的超级权限.包扩所有普通用户的项目.我都应该可以查看编辑. 没有超级管理的话. 我作为系统管理者,查看已不再就职的人员,或者普通用户没有在线,需要给不是我创建的项目添加人员的话,还需要把目标项目转让给我,在添加上普通人员,当有很多个项目需要操作话,是不友好的. 我认为需要一个超级管理用户, 他拥有这个系统的绝对控制权,

不打算这么做。改动太多了。你这不仅是要查看，还想拥有添加成员等权限。这就是项目管理者的角色。目前不打算这么大改。我还觉得要系统管理员跟项目管理员分离。

**Comment by DestinyHunter** [comment]
> > 我作为管理员我应该有这个系统的超级权限.包扩所有普通用户的项目.我都应该可以查看编辑. 没有超级管理的话. 我作为系统管理者,查看已不再就职的人员,或者普通用户没有在线,需要给不是我创建的项目添加人员的话,还需要把目标项目转让给我,在添加上普通人员,当有很多个项目需要操作话,是不友好的. 我认为需要一个超级管理用户, 他拥有这个系统的绝对控制权,
> 
> 不打算这么做。改动太多了。你这不仅是要查看，还想拥有添加成员等权限。这就是项目管理者的角色。目前不打算这么大改。我还觉得要系统管理员跟项目管理员分离。

也不是他要拥有项目管理角色权限. 而是这个超管组不去验证操作权限和获取所有项目

**Comment by star7th** [comment]
我现在做了一个改动：
管理员在查看具体某个项目的时候，拥有的权限跟项目管理员一模一样。可以对项目进行编辑修改。如果要进入设置界面，可以点击右侧栏的更多-设置。然后进入项目设置里做设置，也可以添加成员。
跟你上面提到的权限改造有一点不同的是，项目列表页，即使是管理员，也不会展示全站的项目。因为全站的项目里有很多是示例项目，都展现出来的话，管理员太烦了。所以，默认项目列表页只展示自己的项目。如果管理员想看全站项目，请进入管理后台，在项目管理那里点每一个项目来查看和管理。
