### ISSUE TITLE
导出文件失败

### ISSUE THREAD

**Issue by JRZhuang** [star7th/showdoc#1372]
您好，具体问题描述如下
一、导出word格式时，能够跳出下载，但是下载失败，显示-文件下载未完成；
![image](https://user-images.githubusercontent.com/5678962/120207186-b5ef3800-c25e-11eb-98e4-cca11e8429a4.png)
二、导出markdown格式，可以下载一个showdoc.zip文件，但是文件里面是空的；

我是在centos7下用docker安装的

感谢您抽空查看本issue ^^

**Comment by star7th** [comment]
单纯凭这个不能知道什么信息。你不如提供一个外网可重现链接我看看

**Comment by JRZhuang** [comment]
http://36.249.182.122:4999/web/#/41?page_id=2466
账号密码：
star7th/123456

您可以上这个地址测试下

> 单纯凭这个不能知道什么信息。你不如提供一个外网可重现链接我看看

**Comment by star7th** [comment]
感觉像是你服务器的限制。不能上传也不能下载任何文件。目前我本地测试是没问题的。就你的服务器才有问题，你尝试话换个服务器对比安装看下什么情况。

**Comment by JRZhuang** [comment]
> 感觉像是你服务器的限制。不能上传也不能下载任何文件。目前我本地测试是没问题的。就你的服务器才有问题，你尝试话换个服务器对比安装看下什么情况。

服务器应该是没有做这方面的特殊限制，我们也有在这台服务器上部署禅道，是可以正常上传下载文件的。

**Comment by star7th** [comment]
你换个服务器试下

JRZhuang ***@***.***> 于2021年5月31日周一 下午11:34写道：
