### ISSUE TITLE
从2.9.3开始PHP低于7.2.5的就都不能再用了吗？

### ISSUE THREAD

**Issue by a894890640** [star7th/showdoc#1374]
刚刚更新了发现登录不了，看了下错误原来是PHP版本低于要求，以后是都必须7.2.5以上吗？
Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.2.5". You are running 5.6.27.

**Comment by star7th** [comment]
是大意了没处理好兼容。你下载最新的master版本代码，已经修正。只是没发relastse
