### ISSUE TITLE
RunApi客户端与网页端数据同步问题

### ISSUE THREAD

**Issue by cp7766272** [star7th/showdoc#1377]
1、同一个用户在客户端新建的项目网页端不能操作；
2、同一个用户在网页端新建的项目客户端查询不到；

**Comment by star7th** [comment]
-


   runapi的数据可以生成markdown格式，但不可逆，markdown数据很难再转换回来runapi。所以它无法跟showdoc原有数据互相转换。只是它们可以共用文档浏览/团队协作等功能。同时runapi生成的文档只能在runapi上编辑，不能在showdoc上编辑。后面如果要做数据共用，可能需要对showdoc编写格式有一定的规范约束，这个后面再探索下。



cp7766272 ***@***.***> 于2021年6月3日周四 下午3:09写道：
