### ISSUE TITLE
升级至版本2.9.5最新版本之后，图片上传失败

### ISSUE THREAD

**Issue by Aronlele** [star7th/showdoc#1378]
采用自动化脚本./showdoc update更新showdoc之后，图片上传失败
![image](https://user-images.githubusercontent.com/7881859/120649395-48861600-c4af-11eb-909a-f80f6ea19261.png)

**Comment by star7th** [comment]
你是直接上传文件到服务器还是配置了oss

Aronlele ***@***.***> 于2021年6月3日周四 下午9:04写道：

**Comment by Aronlele** [comment]
服务器，没有额外配置

star7th ***@***.***> 于2021年6月3日周四 下午9:07写道：

**Comment by star7th** [comment]
是不是文件格式不对。你试下其他格式，还不行的话提供个外网链接我看看。

Aronlele ***@***.***> 于2021年6月3日周四 下午11:20写道：

**Comment by Aronlele** [comment]
直接复制照片，然后粘贴。之前都是好使的

star7th ***@***.***> 于2021年6月3日周四 下午11:22写道：

**Comment by star7th** [comment]
是不是文件格式不对。你试下其他格式，还不行的话提供个外网链接我看看。

**Comment by Aronlele** [comment]
[image: image.png]
点击添加图片按钮，选择上传之后，转圈之后，就没反应了。jpg png都试过了。升级完，就不好用了

star7th ***@***.***> 于2021年6月3日周四 下午11:29写道：

**Comment by Aronlele** [comment]
另外，重置密码，也报错

***@***.*** /]# docker exec showdoc php /var/www/html/index.php
home/common/repasswd
PHP Warning:  require(./server/ThinkPHP/ThinkPHP.php): failed to open
stream: No such file or directory in /var/www/html/index.php on line 24
PHP Warning:  require(./server/ThinkPHP/ThinkPHP.php): failed to open
stream: No such file or directory in /var/www/html/index.php on line 24
PHP Fatal error:  require(): Failed opening required
'./server/ThinkPHP/ThinkPHP.php' (include_path='.:/usr/local/lib/php') in
/var/www/html/index.php on line 24

star7th ***@***.***> 于2021年6月3日周四 下午11:29写道：

**Comment by Aronlele** [comment]
外网地址：http://58.56.139.46:4999/web/#/

用户名/密码  ***@***.***

star7th ***@***.***> 于2021年6月3日周四 下午11:29写道：

**Comment by star7th** [comment]
看不到你发的账号名和密码

**Comment by Aronlele** [comment]
***@***.***

star7th ***@***.***> 于2021年6月3日周四 下午11:44写道：

**Comment by star7th** [comment]
先再自己尝试下这样：删除原来的showdoc脚本。然后去重新下载官方的脚本。再执行update

**Comment by star7th** [comment]
看不到账号密码。不知道是github还是哪里的机制屏蔽了。

**Comment by star7th** [comment]
新建一个非邮箱账号密码看看。邮箱地址应该会被屏蔽。

**Comment by Aronlele** [comment]
> 新建一个非邮箱账号密码看看。邮箱地址应该会被屏蔽。

给我个你的邮箱，我单独发给你

**Comment by star7th** [comment]
xing7th@gmail.com

**Comment by star7th** [comment]
尝试两种解决方案：
1，删除原来的showdoc脚本。然后去重新下载官方的脚本。再执行update 。看能解决不。
2，给/showdoc_data 整个目录递归777权限看下。

**Comment by Aronlele** [comment]
看一下，showdoc密码重置的问题吧


star7th ***@***.***> 于2021年6月3日周四 下午11:57写道：

**Comment by Aronlele** [comment]
看一下，showdoc密码重置的问题吧
***@***.*** /]#  docker exec showdoc php /var/www/html/index.php
home/common/repasswd
PHP Warning:  require(./server/ThinkPHP/ThinkPHP.php): failed to open
stream: No such file or directory in /var/www/html/index.php on line 24
PHP Warning:  require(./server/ThinkPHP/ThinkPHP.php): failed to open
stream: No such file or directory in /var/www/html/index.php on line 24
PHP Fatal error:  require(): Failed opening required
'./server/ThinkPHP/ThinkPHP.php' (include_path='.:/usr/local/lib/php') in
/var/www/html/index.php on line 24

star7th ***@***.***> 于2021年6月3日周四 下午11:57写道：

**Comment by star7th** [comment]
应该是后来换镜像引起的问题。要执行另一个命令才行。我已经更新文档  https://www.showdoc.com.cn/help?page_id=16118

**Comment by keroroqingwa** [comment]
我也上传失败，后来发现是文件夹权限问题。
我是iis上部署的，图片上传失败，我把IIS上的错误详细信息打印了出来：
PHP Warning:  File upload error - unable to create a temporary file in Unknown on line 0
根据上面的提示，我把 C:\Windows\Temp 的相关权限开启，就可以了
