### ISSUE TITLE
添加团队成员时，没有判断可选择用户中是否已有团队成员

### ISSUE THREAD

**Issue by ailcc** [star7th/showdoc#1379]
添加团队成员时，没有判断可选择用户中是否已有团队成员
能否做成：去除已经是团队的成员或已经是团队的成员给一个特殊标记

**Comment by star7th** [comment]
你重新选择了也没事的。对重复选择程序会自动过滤。

ailcc ***@***.***> 于2021年6月4日周五 下午12:04写道：

**Comment by star7th** [comment]
你重复选择了也没事的。对重复选择程序会自动过滤。

Chen Xing ***@***.***> 于2021年6月4日周五 下午1:06写道：

**Comment by ailcc** [comment]
收到 谢谢
