### ISSUE TITLE
ShowDoc 图片附件储存到云 希望在集成一个 Minio 

### ISSUE THREAD

**Issue by yinxiulong** [star7th/showdoc#1380]
Minio 一个开源的对象存储。部署到docker 很方便。

**Comment by star7th** [comment]
暂时不考虑。要存在自己服务器的话直接存就行，不用配置什么。

yinxiulong ***@***.***>于2021年6月4日 周五下午8:53写道：

**Comment by star7th** [comment]
这么久以来才只有你有这个需求。我觉得其他人没有这个需求的

**Comment by yinxiulong** [comment]
主要你集成的都是大厂的。要票子。可能别人都有钱，用的都是付费云存储。能有自己的对象存储，又免费不安逸点哇😭。halo这个都支持很多图床包括minio 发自 网易邮箱大师 ---- 回复的原邮件 ---- 发件人 ***@***.***> 日期 2021年06月07日 13:55 收件人 ***@***.***> 抄送至 ***@***.******@***.***> 主题 Re: [star7th/showdoc] ShowDoc 图片附件储存到云 希望在集成一个 Minio  (#1380) 这么久以来才只有你有这个需求。我觉得其他人没有这个需求的 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by star7th** [comment]
对于使用自身服务器的，showdoc只支持直接写入磁盘，不支持使用开源云储存。你本来就是折腾，自己服务器都用一个这么重的东西。

yinxiulong ***@***.***> 于2021年6月7日周一 下午2:01写道：

**Comment by Aronlele** [comment]
其实，我也想用一下minio集成

**Comment by star7th** [comment]
不考虑支持。太小众了。

**Comment by Aronlele** [comment]
阿里云啥的，属于公有oss，但是一般都自建私有oss，这个是一个一般选择，其实不小众的

star7th ***@***.***> 于2021年6月26日周六 上午11:12写道：

**Comment by star7th** [comment]
主要是不想接入太多东西。每个都要去适配。
oss的核心优势是在sdn，自建的话，等于放弃了cdn，我并不觉得它比showdoc本地存储有明显的优势。我接触的公司中，极少极少用自建oss，开源软件中支持自建oss的也很少。我不觉得这是一个”一般性操作“。另外国内的又拍云我也放弃接入了，觉得又拍云少人用。如果以后自建oss的人多起来了，我会接入的。

**Comment by star7th** [comment]
新版已支持通用s3，支持minio

**Comment by Aronlele** [comment]
优秀~~~~

star7th ***@***.***> 于2022年1月7日周五 23:05写道：
