### ISSUE TITLE
作者，您好，runapi的项目同步到showdoc 无法编辑页面吗?

### ISSUE THREAD

**Issue by derqiang** [star7th/showdoc#1381]
![image](https://user-images.githubusercontent.com/44407550/120884239-76d13600-c614-11eb-8e2b-d791fca98f15.png)

**Comment by star7th** [comment]
-


   runapi的数据可以生成markdown格式，但不可逆，markdown数据很难再转换回来runapi。所以它无法跟showdoc原有数据互相转换。只是它们可以共用文档浏览/团队协作等功能。同时runapi生成的文档只能在runapi上编辑，不能在showdoc上编辑。后面如果要做数据共用，可能需要对showdoc编写格式有一定的规范约束，这个后面再探索下。



嘚儿强 ***@***.***> 于2021年6月5日周六 下午3:41写道：

**Comment by derqiang** [comment]
OK
