### ISSUE TITLE
部署后 控制台有个文件导致重定向超限

### ISSUE THREAD

**Issue by derqiang** [star7th/showdoc#1383]
![image](https://user-images.githubusercontent.com/44407550/120959423-4c09ed80-c78c-11eb-9bc2-145c01a2b7de.png)

如上图，这个文件没有，但是一直在拉取

**Comment by star7th** [comment]
你打开这个审查元素的工具才会尝试去请求而已。普通用户不会的。

嘚儿强 ***@***.***> 于2021年6月7日周一 下午12:32写道：
