### ISSUE TITLE
RunApi 导出文档可以导出为MarkDown格式吗

### ISSUE THREAD

**Issue by lzd0805** [star7th/showdoc#1384]
现在发现只能导出.doc, 能不能导出MarkDown格式呢

**Comment by star7th** [comment]
runapi本来就不是存储为markdown格式的

lzd0805 ***@***.***> 于2021年6月7日周一 下午3:40写道：

**Comment by lzd0805** [comment]
我在ruanapi项目模块，有个文档链接，链接过去是markdown的，我就想把这个文档保存为离线的md文件，我可以本地再次修改，我看里边只有copy ，只能复制单页面的，没法复制全部数据
还有看了 更多里边有个导出，能导出全部的但是是.doc 格式的

**Comment by star7th** [comment]
runapiI不支持导出markdown

lzd0805 ***@***.***> 于2021年6月8日周二 下午2:42写道：

**Comment by lzd0805** [comment]
有导出的途径吗，showdoc里可以吗

**Comment by star7th** [comment]
没有。

lzd0805 ***@***.***> 于2021年6月8日周二 下午2:45写道：

**Comment by lzd0805** [comment]
后边版本有打算做这种功能吗，感觉直接导出md文件比导出.doc 文件修改更方便

**Comment by star7th** [comment]
暂时没这个计划。runapi的项目只支持在runapi里编辑。并不会考虑兼容其他地方修改的场景。

lzd0805 ***@***.***> 于2021年6月8日周二 下午2:48写道：

**Comment by lzd0805** [comment]
好的，谢谢!
