### ISSUE TITLE
升级后，不能上传文件了，存储在本地的，另外直接截图粘贴的话，提示上传失败

### ISSUE THREAD

**Issue by smr0418** [star7th/showdoc#1385]

**Comment by star7th** [comment]
你是怎么升级的？尝试给目录777可写权限。

smr0418 ***@***.***>于2021年6月8日 周二下午12:20写道：

**Comment by smr0418** [comment]
已经解决了，估计需要重启下容器就好了 
![image](https://user-images.githubusercontent.com/42182074/121123874-863fc180-c856-11eb-8eec-ade01cb63c31.png)
shibush  是不是后面转移数据库后，还需要重启下容器

**Comment by star7th** [comment]
那个教程我测试过不需要的。不知道你的是什么情况

smr0418 ***@***.***>于2021年6月8日 周二下午12:40写道：

**Comment by star7th** [comment]
为了防止特殊情况，我干脆在教程最后再加上一句赋予权限吧
