### ISSUE TITLE
咨询一下啊  OAuth2 登录要怎么配置啊 能否出个简单教程

### ISSUE THREAD

**Issue by ailcc** [star7th/showdoc#1386]
咨询一下啊  OAuth2 登录要怎么配置啊 能否出个简单教程

**Comment by star7th** [comment]
要填写的东西不是在输入框的时候提示了吗

ailcc ***@***.***> 于2021年6月8日周二 下午10:14写道：

**Comment by star7th** [comment]
我开发这个功能的时候，是使用https://github.com/dromara/MaxKey 搭建oauth2登录服务端来测试的。测试的时候没问题。如果你觉得哪里有问题，可以详细描述下

**Comment by ailcc** [comment]
没有没有问题    我还没来得及设置    我是不会配置这个  我先研究研究看看！

**Comment by yymagicer** [comment]
使用maxkey搭建，通过oauth2登录服务端，登录后跳转，报Invalid state

**Comment by yymagicer** [comment]
使用maxkey搭建，通过oauth2登录服务端，登录后跳转，报Invalid state
