### ISSUE TITLE
希望增加不用登录即可下载附件的 项目配置开关选项

### ISSUE THREAD

**Issue by wierli** [star7th/showdoc#1387]
由于需要给客户 提供在线文档 附件中有sdk 可以下载但是目前必须登录后才能下载
目前的解决方案是创建了一个只读权限的来宾账号 给客户用，但是发现这个账号 竟然可以创建团队 又可以创建项目。
晕了，希望可以 增加免登录下载附件的 项目配置开关选项。

**Comment by star7th** [comment]
附件不需要登录就可以下载。我不清楚你是怎么得出需要登录的。

Wierli ***@***.***> 于2021年6月9日周三 下午12:35写道：

**Comment by star7th** [comment]
如果是把附件链接插入文中的话，是可以直接游客下载的。如果是点击那个按钮的话，确实是做了登录检测。我晚点去掉这个的登录检测。

Wierli ***@***.***> 于2021年6月10日周四 上午2:43写道：

**Comment by wierli** [comment]
感谢

**Comment by star7th** [comment]
已修复问题

**Comment by wierli** [comment]
> 已修复问题

感谢
