### ISSUE TITLE
单页项目最好能够捕获Ctrl+S的保存动作

### ISSUE THREAD

**Issue by wlincai** [star7th/showdoc#1389]
使用表格进行表格制作的时候大部分还是保留着随手保存的习惯，建议捕获Ctrl+S直接触发保存行为

**Comment by star7th** [comment]
这个后面看下怎么优化

Wlin ***@***.***> 于2021年6月9日周三 下午3:07写道：

**Comment by star7th** [comment]
已发布了新版，支持了此功能。
