### ISSUE TITLE
新添加功能

### ISSUE THREAD

**Issue by scafel** [star7th/showdoc#1390]
对接口进行标记,已完成,未完成,已测试等

**Comment by scafel** [comment]
可以设置一个筛选对未完成和已完成的接口进行筛选

**Comment by star7th** [comment]
我不清楚此需求是否合理。请详细描述下使用场景。

**Comment by scafel** [comment]
> 对接口进行标记,已完成,未完成,已测试等



> 我不清楚此需求是否合理。请详细描述下使用场景。

**Comment by scafel** [comment]
> 我不清楚此需求是否合理。请详细描述下使用场景。

例如我们在做项目时会先写接口文档,开发期间会导致有些接口被开发完全,有些接口未被开发完全(测试不达标),在查找这些接口的时候希望可以在测试人员测试接口时可以标记为[已测试,不达标]等相关标签或标记

**Comment by star7th** [comment]
直接改接口标题，添加前缀如何，比如【已测试】用户登录接口

**Comment by scafel** [comment]
> 直接改接口标题，添加前缀如何，比如【已测试】用户登录接口

在接口数量少和目录层级少的时候可用,在接口数量和目录层级多的时候还是需要每个目录点开看才可以,相对就比较复杂

**Comment by star7th** [comment]
这样的话你说的不单是标志的问题了，还想提供根据标志来筛选。这个功能还挺麻烦的。我不清楚是否有必要做，用户需求多强烈。
你这个问题跟这个问题有部分重合  https://github.com/star7th/showdoc/issues/1347

**Comment by scafel** [comment]
> 这样的话你说的不单是标志的问题了，还想提供根据标志来筛选。这个功能还挺麻烦的。我不清楚是否有必要做，用户需求多强烈。
> 你这个问题跟这个问题有部分重合 #1347

确实有部分重合,这个看需求吧

**Comment by star7th** [comment]
已经在runapi客户端增加接口状态的选择。重启客户端便可自动升级到最新版。
