### ISSUE TITLE
新增集成企业微信账号

### ISSUE THREAD

**Issue by enyusmile** [star7th/showdoc#1391]
两个建议:
1.新增集成企业微信账号到showdoc,做到企业微信扫码登录到showdoc
2.showdoc可集成进企业微信应用中使用

**Comment by star7th** [comment]
我没怎么看过企业微信。这个有空的时候探索下。

enyusmile ***@***.***> 于2021年6月11日周五 下午2:38写道：

**Comment by enyusmile** [comment]
期待

**Comment by star7th** [comment]
showdoc现在新版在管理后台的集成登录那里， 支持标准的oauth2协议。理论上企业微信也是oauth2协议  。你可以自行探索下怎么填写。showdoc暂时不针对企业微信出一个专门功能了。  https://github.com/star7th/showdoc/issues/1509

**Comment by yunskyline** [comment]
如果只是查看的话可以使用通用接入使用公用帐号，使用链接方式接入企业微信给别人浏览。

**Comment by yunskyline** [comment]
帅哥你集成进去没有？
