### ISSUE TITLE
后台能否增加一个 切换网站语言模式的按钮  比如安装的时候是英文的 想切换成英文的 后台可以控制

### ISSUE THREAD

**Issue by ailcc** [star7th/showdoc#1393]

**Comment by star7th** [comment]
为什么需要这么做，用什么语言不是一开始就应该定好了吗

ailcc ***@***.***> 于2021年6月11日周五 下午10:26写道：

**Comment by ailcc** [comment]
是没用 搞错项目了  笑哭 哭笑 笑出眼泪 破涕为笑 笑死 笑尿 笑cry

另外问一下 我想控制账户登录24小时后 失效 打开需要重新登录 要在那个地方设置哇

**Comment by star7th** [comment]
没有这种控制设置。

ailcc ***@***.***> 于2021年6月13日周日 下午1:07写道：
