### ISSUE TITLE
mac客户端bug反馈

### ISSUE THREAD

**Issue by wetist** [star7th/showdoc#1394]
runapi的mac客户端，command+w或者直接关闭窗口，再次打开软件出现白屏，必须完全退出重启才会正常。

**Comment by wetist** [comment]
刷新也不生效

**Comment by star7th** [comment]
好像还真是。showdoc的mac端都没问题，runai的mac端口反而存在。 这个问题有时间再好好研究。

暖气片烫袜子 ***@***.***> 于2021年6月15日周二 下午6:08写道：

**Comment by star7th** [comment]
应该修复这个问题了。你重新下载安装试下 https://www.showdoc.com.cn/runapi/30291
