### ISSUE TITLE
文件上传漏洞

### ISSUE THREAD

**Issue by yf33** [star7th/showdoc#1395]
用户上传恶意php代码执行漏洞

./Public/Uploads/2021-04-23/6082c35516e86.php
./Public/Uploads/2021-04-23/6082cd5ef1f23.php
./Public/Uploads/2021-04-23/6082ce0138b23.php
./Public/Uploads/2021-04-23/6082c35a363e0.php

**Comment by star7th** [comment]
这个漏洞一年多前就修复了。升级新版吧

yang ***@***.***> 于2021年6月16日周三 上午11:24写道：
