### ISSUE TITLE
当使用OAuth2登录时,允许在登录时获取组信息

### ISSUE THREAD

**Issue by bobdxiao** [star7th/showdoc#1397]
目前在OAuth2登录完毕之后,需要重新为用户设置组信息,希望可以设置一个属性,从token中自动获取该用户所属的组信息,当用户每一次登录时从token中重新检索该用户的组信息,并覆盖在系统中用户原有的组信息

**Comment by star7th** [comment]
oauth2登录只是方便登录，但是团队功能之类的，都是使用showdoc本身的管理体系，跟oauth2很难集成。不打算从oauth的组同步到团队，这两个是不同的概念

TripodXiao ***@***.***> 于2021年6月20日周日 下午11:41写道：
