### ISSUE TITLE
允许使用OAuth2协议登录作为默认的登录方式

### ISSUE THREAD

**Issue by TripodXiao** [star7th/showdoc#1398]
在现有情况下,新增的OAuth2登录方式,只是在菜单中新增一个按钮,以允许用户从OAuth2登录,希望可以添加一个选项,以允许使用OAuth2作为默认的登录方式
而因为添加这个功能具有一定的风险性->当OAuth2登录不可用时,或者当前在进行OAuth2登录的配置,开启该选项将会无法进入系统
在这种情况下,需要设置一种方式以使showdoc可以在单点登录发生故障时可以使用管理员账号进入showdoc以进行配置
可以考虑的一种方式是,设置一个特殊的url,格式大致如下${showdoc_url}/oauth2/reset?code=${uuid}
这个url具有的特性大致如下
1. 在开启OAuth2为默认登录方式时,自动生成该url,管理员需要记录下该URL以便在SSO故障时进入后台
2. 允许将showdoc从默认OAuth2的登录方式切换为使用自带的默认方式,即现有的方式
3. 调用该url不需要任何的权限,直接在复制到浏览器中就可以进行调用
4. 当调用一次这个url之后,系统会自动刷新code的值,管理员需要重新记录这时的url

**Comment by star7th** [comment]
当初主要是为了考虑到OAuth2登录不可用时的问题。你提出的解决方案是一个思路，但是这种依赖管理员自行记录url的方式不太可取。我还是倾向于让用户都通过网址点击进入某个页面。
我觉得，在管理界面增加oa登录入口应该是可以接受的吧；很多登录提供多种方式登录的时候都是这样放置入口的
