### ISSUE TITLE
当使用OAuth2登录时,不会更新用户的最后登录时间

### ISSUE THREAD

**Issue by TripodXiao** [star7th/showdoc#1399]
将登录方式配置为使用OAuth2登录后,在管理员查看用户最后登录的时间时,无法看到该用户最后登录的时间
该问题可重现
出现问题的版本: 2.9.5
运行showdoc的方式: docker
![Snipaste_2021-06-21_00-12-20](https://user-images.githubusercontent.com/40219717/122681120-68466980-d225-11eb-90f7-9af1c4321066.png)
同时不知道为什么管理员的注册时间是2032年

**Comment by star7th** [comment]
有空时候修复下。另外管理员注册时间是内置的，所以就写了一个比较大的注册时间。它不是安装的时候才注册的，而是一开始就被写进了初始化数据库

TripodXiao ***@***.***> 于2021年6月21日周一 上午12:13写道：

**Comment by star7th** [comment]
已经有人贡献代码了，记录了oauth2登录的最后登录时间 https://github.com/star7th/showdoc/pull/1422 。你直接更新最新代码
