### ISSUE TITLE
允许设置某个用户为showdoc管理员

### ISSUE THREAD

**Issue by bobdxiao** [star7th/showdoc#1400]
在现有状态下,系统内置的管理员为showdoc账号,希望可以增加设置某个用户为管理员的功能,而不是仅showdoc用户可以成为管理员

**Comment by star7th** [comment]
为了兼容历史，showdoc用户必须是管理员。然后，这种情况下我觉得多个管理员账户没有必要

TripodXiao ***@***.***> 于2021年6月21日周一 上午12:17写道：
