### ISSUE TITLE
官网打不开

### ISSUE THREAD

**Issue by chy-study** [star7th/showdoc#1402]
**时间：2021-06-23 10:08**

![image](https://user-images.githubusercontent.com/41263368/123024064-119a8480-d40b-11eb-8518-7c568264571f.png)

**Comment by happydts** [comment]
+1

**Comment by China-Drummond** [comment]
+1

**Comment by star7th** [comment]
已恢复，不好意思，是我过于自信了，以为这个小变更直接在生产环境操作不会引起问题。

**Comment by DingMr** [comment]
东西没了
不能退出，也不能登录！

**Comment by China-Drummond** [comment]
> 已恢复，不好意思，是我过于自信了，以为这个小变更直接在生产环境操作不会引起问题。

还是502无法打开呢？是在部署吗

**Comment by simonlkch** [comment]
還是打不開

**Comment by javaXiaoHan** [comment]
还是不行

**Comment by javaXiaoHan** [comment]
新建的项目找不到

**Comment by star7th** [comment]
一恢复，就被高峰期的流量冲垮了。因为刚重启，缓存还没生成，导致大量请求请求直接压到原始数据库去了。
现在应该好多了
