### ISSUE TITLE
路由模式设置为history后，加载的静态资源路径错误

### ISSUE THREAD

**Issue by PickACatName** [star7th/showdoc#1405]

**Comment by star7th** [comment]
我没探讨过开源版showdoc怎么用history。你要用的话可能需要自己去探索下

lzbbp ***@***.***> 于2021年6月24日周四 上午11:22写道：

**Comment by ailcc** [comment]
你如果一定要设置history的话，那么静态资源的路径就要手动改，不然就会报404

**Comment by ailcc** [comment]
当然  一个页面一个页面的改太蠢了 给你一个简单的办法  你既然要去掉#号，那我猜你肯定也想要去掉web/这个路径，那么再confug/index.js里面 把
`    index: path.resolve(__dirname, '../../web/index.html'),
    assetsRoot: path.resolve(__dirname, '../../web'),`
这两行里面的web去掉，然后把
`   assetsPublicPath: './',`
改成 `assetsPublicPath: '/',`
再然后，把web_src目录下的index.html里面的
` "server": window.location.protocol +'//'+ window.location.host + window.location.pathname+ '../server/index.php?s=',`
改成
`"server": window.location.protocol +'//'+ window.location.host+ '/server/index.php?s=',`
然后 
再在nginx的配置文件里添加
`location / {
      try_files $uri $uri/ /index.html;
    }`
打包  就能解决掉静态资源404和路径里面的web/#了
