### ISSUE TITLE
官方镜像 docker 安装后 访问 nginx 报 403

### ISSUE THREAD

**Issue by olderwang** [star7th/showdoc#1408]
这个是 官方镜像nginx配置问题，把 /opt/docker/etc/nginx/vhost.conf 中配置修改一下

server {

> 把这一行改掉 增加 index.html 即可

    index index.php index.html;
}

**Comment by star7th** [comment]
用的是bieren
的base镜像。懒得改。如果你是从新版showdoc代码，web目录下既有index.html也有index.php，理论上是不需要再改nginx了的

olderwang ***@***.***> 于2021年7月1日周四 下午1:32写道：

**Comment by star7th** [comment]
用的是别人的base镜像。懒得改。如果你是从新版showdoc代码，web目录下既有index.html也有index.php，理论上是不需要再改nginx了的

Chen Xing ***@***.***> 于2021年7月1日周四 下午1:35写道：

**Comment by olderwang** [comment]
我是按官方文档里的这个镜像做的。
registry.cn-shenzhen.aliyuncs.com/star7th/showdoc

vhost.conf 中 配置有index.php。我这边是加了 index.html 就可以了。

**Comment by star7th** [comment]
我的意思，我的上层base镜像本来就这么写。我懒得覆盖他的写法。所以我在代码上兼容了。
web目录下既有index.html也有index.php，理论上是不需要再改nginx了的

olderwang ***@***.***> 于2021年7月1日周四 下午2:06写道：

**Comment by olderwang** [comment]
哦 。我搞错了。我这边是从低版本升级的，没有拉倒最新代码。
旧的代码里 没有  index.php 。最新版的没有问题的。
