### ISSUE TITLE
文档建议  添加 维护人(接口开发人) 开发状态(开发中,已完成) 当前版本(V1.1)

### ISSUE THREAD

**Issue by zhouwenjun315** [star7th/showdoc#1409]
![image](https://user-images.githubusercontent.com/18712897/124251512-93e81e80-db58-11eb-873a-c6eebfe8edcc.png)

**Comment by star7th** [comment]
你可以在接口描述那个输入框说清楚这些情况。

zhouwenjun315 ***@***.***> 于2021年7月2日周五 下午5:19写道：

**Comment by star7th** [comment]
或者标题处都行

Chen Xing ***@***.***> 于2021年7月2日周五 下午5:45写道：

**Comment by star7th** [comment]
已经在runapi客户端增加接口状态的选择。重启客户端便可自动升级到最新版。
