### ISSUE TITLE
用户编辑

### ISSUE THREAD

**Issue by coeus-lei** [star7th/showdoc#1410]
1.用户编辑项目时，直接退出网页，其他用户再进入该页面，只有读取权限，不能修改，显示页面被锁定，，
2.怎么查询当前安装的showdoc版本号

**Comment by star7th** [comment]
请按照教程升级到最新版 https://www.showdoc.com.cn/help/13732  
版本可以看目录下的composer.json文件

**Comment by coeus-lei** [comment]
不对呀，我升级到最新版本了，还是会有这个问题，，我用容器的方式部署的，，修改表格的人员，直接退出网页，不做保存退出，，其他人进入该表格，还是会出现页面被锁定的情况

**Comment by star7th** [comment]
突然想起这个bug是在常规项目修复了，不过表格项目是没有修复。下次发版一并更新。当前你不需要退出网页，然后点击返回按钮才会解锁。

Simmon ***@***.***> 于2021年7月4日周日 下午4:31写道：

**Comment by coeus-lei** [comment]
大哥，啥时候跟新呀，，等到花儿都谢了呀

**Comment by star7th** [comment]
你不用等啊。默认它半个小时自动解锁。有空再更

**Comment by coeus-lei** [comment]
大佬，啥时候，得空啊！
说好的协同工作呢？
要等半小时才自动解锁，黄花菜都凉凉了😯

发自我的iPhone

**Comment by star7th** [comment]
你们协同编辑的时候不要直接关闭网页，而是点击返回按钮。点击返回按钮的话，会立即解锁。直接关闭网页的话，由于发不出解锁请求，所以解锁不了。等晚点再监听下关闭网页事件。但就目前而言，你可以点击返回按钮来解锁。

**Comment by coeus-lei** [comment]
话是这么说，大佬啊
总有不按操作规则来的人呀
你想啊，
假如我是是煎饼果子的
遇到买二分之一个煎饼的奇葩，我也很无语啊

发自我的iPhone

**Comment by coeus-lei** [comment]
所以，大佬，速度更新呗

发自我的iPhone

**Comment by star7th** [comment]
已发布了新版，支持了此功能。
