### ISSUE TITLE
runApi生成的文档不支持修改吗？

### ISSUE THREAD

**Issue by ojbk-666** [star7th/showdoc#1413]
公司部署的不是最新版本 文档生成用不了 
![image](https://user-images.githubusercontent.com/45815297/124711153-4ee53300-df30-11eb-94c1-1284e3e4b6fb.png)

自己搭建个环境又没法导出。。。

**Comment by star7th** [comment]
runapi需要高版本showdoc才能使用，且runapi的项目只能在runapi上修改。

ojbk-666 ***@***.***>于2021年7月7日 周三下午2:34写道：
