### ISSUE TITLE
/api/common/version 报错

### ISSUE THREAD

**Issue by yingzk** [star7th/showdoc#1414]
`http://xxx/index.php?s=/api/common/version`
一直返回
```json
{"error_code":"10103","error_message":"Sqlite/showdoc.db.php文件不可写"}
```
已经给该文件权限设置为777
![image](https://user-images.githubusercontent.com/23278599/124889467-b4592280-e009-11eb-9ace-b846a3c7a970.png)

**Comment by star7th** [comment]
给了权限却不可写，很可能是selinux等安全设置

Ying Joy ***@***.***> 于2021年7月8日周四 下午4:30写道：

**Comment by yingzk** [comment]
![image](https://user-images.githubusercontent.com/23278599/124895063-c7222600-e00e-11eb-9940-0969a746c88b.png)
关闭后，仍无法解决问题

**Comment by star7th** [comment]
这个问题不清楚了。跟你的服务器配置强相关。只能去问你的运维为什么文件给了权限了，也还是有东西限制不可写。

Ying Joy ***@***.***> 于2021年7月8日周四 下午5:06写道：

**Comment by yingzk** [comment]
好的，谢谢
