### ISSUE TITLE
v2.8.10升级到v2.9.1报错

### ISSUE THREAD

**Issue by moobing** [star7th/showdoc#1416]
SQLSTATE[HY000]: General error: 1 no such column: item_group_id 。错误位置：/www/wwwroot/showdoc-2.9.6/server/ThinkPHP/Library/Think/Db/Driver.class.php 174

**Comment by star7th** [comment]
退出重新登录下看看

gamedevil ***@***.***> 于2021年7月8日周四 下午9:16写道：

**Comment by moobing** [comment]
还是一样

**Comment by star7th** [comment]
刷新浏览器缓存再登录看看

gamedevil ***@***.***> 于2021年7月8日周四 下午9:45写道：

**Comment by moobing** [comment]
安装方式是php，全新安装后，复制v2.8.10的数据库和public下的文件覆盖v2.9.1

**Comment by moobing** [comment]
是runapi报错

**Comment by moobing** [comment]
![image](https://user-images.githubusercontent.com/31676598/124932882-03b54800-e036-11eb-94bd-21552caa3af7.png)

**Comment by star7th** [comment]
先确认showdoc升级好再tunapi，去showdoc上操作确认正常使用。

gamedevil ***@***.***> 于2021年7月8日周四 下午9:46写道：

**Comment by star7th** [comment]
服务端都没升级好，跟我说客户端错误有什么用呢。先去showdoc上操作，确保showdoc能正常新建文档。

gamedevil ***@***.***> 于2021年7月8日周四 下午9:47写道：

**Comment by moobing** [comment]
我傻了，全新安装要先选中英文，是我忽略掉了，打扰了~
