### ISSUE TITLE
能不能新增一个添加备案号和网公安备的地方

### ISSUE THREAD

**Issue by maliang366359** [star7th/showdoc#1418]
能不能新增一个添加备案号和网公安备的地方，现在网站放到公网，想添加ICP备案号和网公安备案的地方都没有

**Comment by star7th** [comment]
后面增加一个添加备案号的设置。网安备案就没必要了吧。

maliang366359 ***@***.***> 于2021年7月13日周二 下午4:27写道：

**Comment by maliang366359** [comment]
在国内提供服务器的，网安备案是必需的，做个可选接口就是了，有需要就勾上添加一个，没有需要的不勾选，就不显示。

**Comment by star7th** [comment]
新版已经可以管理后台配置备案号
