### ISSUE TITLE
[Security] 加密文档密级是否太低

### ISSUE THREAD

**Issue by DukeWF** [star7th/showdoc#1419]
查看源码及SQLite可发现，加密文档的密码存储方式是明文。这样的存储方式，安全性是否太低？
或者是否考虑在分享加密文档时，强制使用自动生成密码以避免用户使用弱口令带来的风险。

**Comment by star7th** [comment]
用户的密码是密文的，明文的只是项目查看密码。仅有项目查看权限。
暂时不考虑强制使用强密码。很多人都是随便生成个弱口令就分享出去给其他人看的。因为场景上不是什么重要项目。重要项目自然而言会设置强密码。

Fan WANG ***@***.***> 于2021年7月13日周二 下午4:53写道：

**Comment by star7th** [comment]
行吧，下次把它加密存储。

Fan WANG ***@***.***> 于2021年7月13日周二 下午5:00写道：

**Comment by star7th** [comment]
思考了下，这个还是不能加上。因为某些场合需要把项目的原密码展示给用户。比如系统创建的runapi默认项目，会自动设置密码，要展示出给用户看。所以需要双向加解密的。如果程序能双向解密，那么加密存储的意义就很小了。
在安全性和便利性之间选择平衡，我选择便利性。毕竟项目密码不会太重要。
