### ISSUE TITLE
建议在线测试api工具runapi增加put，patch，delete等方法

### ISSUE THREAD

**Issue by rinka0414** [star7th/showdoc#142]
runapi目前只有post和get两种方法，建议把常用的几种方法如put，patch，delete等加上去。

**Comment by star7th** [comment]
post和get是更常用的方法。有机会我再把其他加上。

**Comment by star7th** [comment]
那个工具比较少维护，还是不做复杂了。只支持简单功能。复杂的可以用postman之类的专业工具
