### ISSUE TITLE
Runapi问题：Get请求时，下面的参数值和url后面的参数值能做成联动的吗？

### ISSUE THREAD

**Issue by shanesyk** [star7th/showdoc#1421]
如题，当我修改下方参数的参数值后，url中的对应参数的参数值并没有更新，还需要再在url中修改一遍参数值，不够优雅，希望能改进一下。（可参考一下postman）

**Comment by shanesyk** [comment]
postman如下，上下两个是同时变化的
![image](https://user-images.githubusercontent.com/30226201/125790745-ae366d15-ccdb-4ed5-a319-245b4fd91deb.png)
而runapi这两个是分离的，修改起来不是太方便

**Comment by star7th** [comment]
你写在参数列表里，不要写在url里

**Comment by star7th** [comment]
新版runapi已经做成联动
