### ISSUE TITLE
【功能增强】私有化部署：上传到OSS的图片在站点删除资源后OSS中也同步删除

### ISSUE THREAD

**Issue by xueshanlinghu** [star7th/showdoc#1423]
您好，今天在使用 Showdoc 的时候用了阿里云的 OSS 来上传图片。实测可以正常使用。但比如我在站点删除上传的文件资源后，站点中已经找不到，但阿里云的 OSS 源库的资源还存在。之前用过一些其他建站程序的类似服务应是可以有接口同步删除的，请问这块后续是否可以考虑做个优化，在站点点删除资源之后 OSS 中的文件也同步能够删除，做到同步呢？

感谢！

**Comment by star7th** [comment]
后面有空再完善下同步删除功能。

**Comment by xueshanlinghu** [comment]
> 后面有空再完善下同步删除功能。

感谢您的回复和帮助！期待完善！

**Comment by star7th** [comment]
已经发布新版，解决了此问题

**Comment by xueshanlinghu** [comment]
非常感谢！
