### ISSUE TITLE
使用nginx做反向代理并强制跳转https后，插入的pdf,xlsx等资源会出现访问问题

### ISSUE THREAD

**Issue by eno16777736** [star7th/showdoc#1424]
使用nginx做反向代理并强制跳转https后，插入的pdf,xlsx的路径默认使用的是http,强制跳转https后部分文件无法正常打开；
![image](https://user-images.githubusercontent.com/37285753/126111683-78c17f21-cf3c-4b75-a718-408596d790c8.png)

**Comment by star7th** [comment]
是浏览器自身的安全机制禁止了https网站中访问http资源。
其实如果用https的话，比较建议在管理后台设置使用云储存。

**Comment by eno16777736** [comment]
现有数据如何迁移到云存储上去，有什么可以参考的文档吗？

**Comment by star7th** [comment]
没有现有数据迁移的方案。你可以复制粘贴上传上去。

**Comment by eno16777736** [comment]
能否通过更改生成资源链接的代码，把默认生成http协议的链接地址更改成https?

**Comment by star7th** [comment]
这个我不太清楚。代码都是开源的，理论上你可以修改

**Comment by star7th** [comment]
其实这是个遗留难题。因为没想到很好的兼容方案。改成https后，http又用不了。技术上的问题都很简单，问题是怎么样的技术方案才是兼容的

**Comment by eno16777736** [comment]
这个可以将这个设计成用户可自定义的参数选项：root_url= %(protocol)s://%(domain)s/;让用户自行配置要使用的协议和域名domain；root_url将成为生成资源url的地址头部

**Comment by star7th** [comment]
是一个可考虑的方向吧。我还要想想会不会带来新的兼容问题。

**Comment by star7th** [comment]
已经发布新版，可以在管理后台配置网址，配置的网址将用于附件的前缀。你在前缀写死https协议头即可
