### ISSUE TITLE
SSO单点登录，退出的时候没有做SSO退出回调

### ISSUE THREAD

**Issue by SuimgPhilip** [star7th/showdoc#1425]
使用SSO账号进行登录，目前单点登录功能正常
但是退出的时候应该跳转到SSO的退出接口

解决方案：在集成登录 -> OAuth2 里面新增配置项 logout url,并在系统退出接口 判断是否配置了这个选项 如果配置 就跳转到这个页面

**Comment by SuimgCn** [comment]
从国内的gitee提到这里的https://gitee.com/star7th/showdoc/issues/I41EZU

**Comment by star7th** [comment]
这个后面有空再研究探索下

**Comment by star7th** [comment]
已发布新版，支持了
