### ISSUE TITLE
mac客户端白屏

### ISSUE THREAD

**Issue by Fantast416** [star7th/showdoc#1428]
<img width="1147" alt="截屏2021-07-27 上午2 57 53" src="https://user-images.githubusercontent.com/45848260/127043585-c97a2020-6b46-473e-9e63-7c899e191075.png">

**Comment by star7th** [comment]
这个问题其实也有用户反馈过。只是没找到具体原因。当前你可以这么处理：在底部菜单栏点击退出，然后再重新打开。

**Comment by Fantast416** [comment]
已解决
