### ISSUE TITLE
runapi Mac端 请求Header Origin配置无效

### ISSUE THREAD

**Issue by gongcf** [star7th/showdoc#1429]
runapi Mac端 请求Header 中Origin和User-Agent配置无效，会自动被替换成默认：
Origin: https://runapi_client.showdoc.cc
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16_0) AppleWebKit/537.36 (KHTML, like Gecko) runapi/1.0.0 Chrome/80.0.3987.165 Electron/8.3.3 Safari/537.36

**Comment by star7th** [comment]
目前是的，ua写死了。
