### ISSUE TITLE
导出出现“链接已重置”的问题

### ISSUE THREAD

**Issue by aiqiao** [star7th/showdoc#143]
之前为了其他电脑能访问，修改了下httpd.conf文件的位置
之后不知怎么了，改成之前的也不能导出了

还有在另一台电脑上也部署，然后把本地的showdoc的Application拷贝过去，账户名是相同的，但是密码却是之前的旧密码，新增加的几个api接口也没有

**Comment by star7th** [comment]
“但是密码却是之前的旧密码，新增加的几个api接口也没有”证明用的不是同一个db，所以导致数据不一样。我不清楚你的环境是怎么弄的，我建议你部署到服务器上试试

**Comment by aiqiao** [comment]
@star7th 
大佬，我的问题还没解决，
每当我要导出时都会这样：
不能插入图片所以只能把浏览器上的文字复制过来了
> 无法显示此网页
> 错误代码： ERR_CONNECTION_RESET
> 连接已重置。
> 刷新  上网导航
> 您所遇到的问题可以通过清理缓存和Cookies来修复 立即修复
> localhost ERR_CONNECTION_RESET


我的部署环境是windows，按照你说的教程部署的
之前是可以用的，后面为了能够让其他电脑访问本机，改了下httpd.config文件
其他就没动过了。

按照你的方法进行迁移的时候，另一台机子上也出现这个问题，
我在想，是不是，迁移的public 文件和Sqlite这两个文件有问题啊，可是我找不到啥问题

**Comment by star7th** [comment]
这个网页提示是比较笼统的提示，看不出任何详细错误提示。我暂时也没有什么好的头绪。你试着重新安装的showdoc试试
