### ISSUE TITLE
请求参数包含对象数组时，无法正确生成json字段说明

### ISSUE THREAD

**Issue by oshome** [star7th/showdoc#1431]
请求参数包含对象数组时，无法正确生成json字段说明
还有生成字段说明时，如果是数字型的字符串，最好把字段类型设置为数字
字段说明能增加枚举类型吗？
~~~
{
    "name": "某某",
    "type": [42,56],
    "journey":[
        {"sort":"1","day":1,"time":"09:00","name":"出发","remark":"自备","type":"gather","content":""}
    ],
    "status": "show"
}
~~~

**Comment by oshome** [comment]
数据字典能否使用sql表结构直接导入？

**Comment by star7th** [comment]
一个结构体里，只有第一个对象数组被处理。比如你上面的type那个字段如果删除，那么journey对象数组就能正常生成。
使用sql表结构导入是另一个问题。不应该这个问题下问题。晚点有时间探索这方面。

oshome ***@***.***> 于2021年7月29日周四 下午12:12写道：
