### ISSUE TITLE
/api/item/attorn接口执行item转让时无法正常获取用户列表

### ISSUE THREAD

**Issue by eno16777736** [star7th/showdoc#1433]
转让item时，执行/api/item/attorn接口执行item转让时无法正常获取用户列表，前端会直接跳转到首页
![image](https://user-images.githubusercontent.com/37285753/127821636-4fd23577-26c3-4def-ac8a-dfcebb42e966.png)

**Comment by star7th** [comment]
你这个截图说明不了什么情况。切换到响应页看看返回什么数据。另外可以自己先尝试升级showdoc到最新版，如果有绑定域名的话，按照这个教程来 https://www.showdoc.com.cn/help/7240953917068087
