### ISSUE TITLE
本地部署，表格项目如何创建更多的表页（当前限制10个）

### ISSUE THREAD

**Issue by sslsimon** [star7th/showdoc#1434]
本地项目部署，新建表格项目如何能创建更多的表页（当前限制10个），超过后会提示
![image](https://user-images.githubusercontent.com/2697155/127823151-24632733-4892-430a-ba6a-2a4b87d56f32.png)

**Comment by star7th** [comment]
showdoc是引用了一个第三方开源就表格组件。目测是这个组件本身的限制  https://hondrytravis.com/x-spreadsheet-doc/guide/#%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8%E5%BC%80%E5%8F%91 估计是为了防止资源性能问题。
