### ISSUE TITLE
集成LDAP程序卡死

### ISSUE THREAD

**Issue by 2777450490** [star7th/showdoc#1437]
集成LDAP程序卡死

**Comment by star7th** [comment]
这个我调试不了。只能说，有人是链接成功的，我自己也链接成功，你检查下是不是网络问题。另外你的ldap用户量大吗

pengxl ***@***.***>于2021年8月3日 周二上午10:54写道：

**Comment by 2777450490** [comment]
用户量几万的样子

**Comment by 2777450490** [comment]
集成始终不能成功

**Comment by star7th** [comment]
提供下用户列表截图看看导进来是什么用户

pengxl ***@***.***> 于2021年11月17日周三 下午1:25写道：

**Comment by 2777450490** [comment]
我试了多次都会卡死，应该是用户量太大导致，请问怎么集成LDAP用户组来过滤，我看集成页面没有提供用户组过滤配置输入框

**Comment by star7th** [comment]
我有好一段时间没接触ldap了，都不太记得它的机制了。 bind dn
我不知道是否能起到过滤作用。另外如果你的ldap服务器可以配置接口返回条数，先尝试限制单次返回条数看行不行

pengxl ***@***.***> 于2021年11月17日周三 下午1:39写道：

**Comment by star7th** [comment]
已发布新版，在ldap配置页面增加了search filter输入字段，可以输入筛选条件。 参考这个 https://github.com/star7th/showdoc/issues/1546
