### ISSUE TITLE
导出成 word 格式内容被截断

### ISSUE THREAD

**Issue by zealotpz** [star7th/showdoc#1439]
如下图 中的 List<Object>， 导出后尖括号< 后的内容被截断

- **文档内容：**

<img width="827" alt="Xnip2021-08-04_14-52-25" src="https://user-images.githubusercontent.com/13163700/128136303-84c21e66-5fba-425d-b7f4-2284cb2cb8c2.png">

- **导出 word 内容：**

<img width="851" alt="Xnip2021-08-04_14-52-39" src="https://user-images.githubusercontent.com/13163700/128136349-7140d63d-667a-40fe-b15a-da38fd35fb48.png">

**Comment by star7th** [comment]
导出的word不支持尖括号

木上贝 ***@***.***> 于2021年8月4日周三 下午2:59写道：

**Comment by sun3Lu** [comment]
我也发现该问题 文档中出现**<Object>**内容 导出文档时发现<Object>开始内容都丢失
![image](https://user-images.githubusercontent.com/37389121/128145403-0a8fc568-4f8f-413f-aec4-5e09e5227fb9.png)

**Comment by sun3Lu** [comment]
我也发现该问题 文档中出现**<Object>**内容 导出文档时发现<Object>开始内容都丢失
![image](https://user-images.githubusercontent.com/37389121/128145403-0a8fc568-4f8f-413f-aec4-5e09e5227fb9.png)
