### ISSUE TITLE
请问使用自动脚本安装后，Nginx的配置目录在哪儿，怎么配置SSL证书（已购买了通配符证书），感谢

### ISSUE THREAD

**Issue by znonymous** [star7th/showdoc#1440]
目前可以通过域名访问，使用的是默认4999端口，现在想加SSL证书，请大神指导，感谢感谢

**Comment by star7th** [comment]
配置nginx和ssl证书不需要对showdoc进行操作，而且在你绑定域名的时候，配置即可。首先你参考这个教程绑定域名 https://www.showdoc.com.cn/help/7240953917068087

然后，在nginx配置里尝试配置https
