### ISSUE TITLE
三个建设性建议

### ISSUE THREAD

**Issue by koy1619** [star7th/showdoc#1444]
1. 支持导入markdown文件（导入gitbook），方便适用于别的文档系统迁移至showdoc

2. 批量创建文档目录和文件（先把章节目录结构创建出来，然后再慢慢写内容。文档少的时候，一个个去创建倒没什么，但是文档数量多了之后，，太费事了）

3. 支持调用yapi（比如文档里面输入`[yapi_interface]25762[/yapi_interface]` 会自动显示yapi上对应的接口文档）

**Comment by star7th** [comment]
1，不同系统导出的文件格式略有不一样，很难有统一的导入方式。目前只针对postman和swaager的导入。其他的，建议自己写程序调用api写入 https://www.showdoc.com.cn/page/102098  。此外，对于纯markdown文件,我更建议自己复制粘贴就好。
2，批量创建的需求目测挺少的，。后面收集下更多反馈再看。
3，yapi已经停止维护，官方仓库的issue基本上没什么官方回应，同时过去一年也没有什么实际更新。所以不考虑支持yapi

**Comment by star7th** [comment]
对接口调试有需求的，可能用这个工具替代yapi https://www.showdoc.com.cn/runapi/30291

**Comment by koy1619** [comment]
非常感谢
