### ISSUE TITLE
时不时报错：Sqlite/showdoc.db.php文件不可写

### ISSUE THREAD

**Issue by bylpf** [star7th/showdoc#1445]
按照官方的教程Windows下通过phpStudy安装后，将原内网服务器的上的Sqlite/showdoc.db.php文件拷贝到了新安装的云服务上覆盖，设置了文件夹及文件的读写权限。编辑内容提交的时候时不时弹框报错“Sqlite/showdoc.db.php文件不可写”。点击确认后，再次提交又正常。请问这个是什么问题呢？

**Comment by star7th** [comment]
我自己也不太清楚这个问题。但是linux下几乎不会遇到这种情况。我只能说可能是win的文件机制问题。建议用linux

**Comment by star7th** [comment]
win下也不每个人都遇到这个问题。所以这个问题我没什么太好的办法。
