### ISSUE TITLE
通用接口创建的用户，密码是什么

### ISSUE THREAD

**Issue by vital94** [star7th/showdoc#1446]
http://{{host}}/server/?s=/api/extLogin/bySecretKey&username={{username}}&time={{time}}&token={{token}}&redirect={{redirect}}
根据这个创建的用户，默认密码是啥呀

**Comment by star7th** [comment]
密码是随机不可见的。如果要重置，请用showdoc用户登录管理后台去重置。默认你使用这种方法登录都是不需要密码的
