### ISSUE TITLE
runapi可以增加针对某个目录添加前执行脚本和后执行脚本吗

### ISSUE THREAD

**Issue by zuohl** [star7th/showdoc#1447]
目前只支持针对某个接口增加前执行脚本,不方便做统一的登录和鉴权

**Comment by zuohl** [comment]
@star7th 能帮忙看看这个么

**Comment by star7th** [comment]
不能根据目录来。你应该把认证token写进环境变量，其他接口都引用这个环境变量，而不是每个接口都请求一次。

zuohl ***@***.***>于2021年8月11日 周三下午4:23写道：

**Comment by zuohl** [comment]
![image](https://user-images.githubusercontent.com/10548200/129012186-b2000133-8c25-4288-89ea-a492af2dd188.png)
postman就是有这个功能的,我们目前就是计划从postman迁移,结果遇到的问题

**Comment by star7th** [comment]
我是比较少用到这个。我另外找时间研究下这方面。

**Comment by star7th** [comment]
在这之前，你临时先每个接口都添加脚本来解决吧。

**Comment by zuohl** [comment]
好的,多谢,或者开源出来我来补下这个逻辑应该也是可以的 @star7th

**Comment by FlyingFishBird** [comment]
同有这个需求。我们项目中会对每个请求的返回数据进行安全校验，有通用的算法来执行。如果每个api 都拷贝粘贴一份工作量就很大。一些api管理平台是通过引用公共的脚本来解决的

**Comment by star7th** [comment]
已经在runapi客户端增加全局脚本功能，重启客户端便可自动升级到最新版。
