### ISSUE TITLE
建议出个console界面

### ISSUE THREAD

**Issue by wangkunmin** [star7th/showdoc#1448]
使用接口的时候，不小心填错了接口参数，调查起来好困难

**Comment by star7th** [comment]
你是说shiyon给runapi的时候吗？填错参数的话，应该是你的后端针对缺少的参数而显示提示缺少什么参数，这样比较好

wangkunmin ***@***.***> 于2021年8月12日周四 上午10:10写道：

**Comment by star7th** [comment]
你是说使用runapi的时候吗？填错参数的话，应该是你的后端针对缺少的参数而显示提示缺少什么参数，这样比较好

Chen Xing ***@***.***> 于2021年8月12日周四 上午10:13写道：

**Comment by wangkunmin** [comment]
emmmm
