### ISSUE TITLE
可以把返回值注解放到这个后面吗

### ISSUE THREAD

**Issue by zaq11qaz** [star7th/showdoc#1449]
![企业微信截图_1628044735947](https://user-images.githubusercontent.com/55392923/129175521-d69e58e2-360e-4c4c-a4e9-3be912cd798a.png)
可以把返回值注解放到这个后面吗

**Comment by star7th** [comment]
不懂你在说什么。
首先这个截图不是showdoc，其次不明白你说的“这个”指的是什么。

**Comment by zaq11qaz** [comment]
就是下面写的注解不是一一对应的吗，
把下面的注解横向标到返回值上是否可行

**Comment by star7th** [comment]
你是不是搞错了，这个截图不是showdoc

**Comment by star7th** [comment]
另外你说是的哪里把返回值放到后面。

**Comment by zaq11qaz** [comment]
我知道不是showdoc 啊，
就是一个提议 :
下面标注的每一个词的意思能否横向放在返回值后面，
而不是单独在下面列表显示。

**Comment by zaq11qaz** [comment]
就跟那个图里一样

**Comment by zaq11qaz** [comment]
我发的那个应该是swagger，
和这个提议不影响吧

**Comment by zaq11qaz** [comment]
就是下面逐一对应的注解 
在返回值json 右边加个竖线 填充到竖线右边

**Comment by zaq11qaz** [comment]
感觉可以实现啊

**Comment by star7th** [comment]
不能这样。因为一旦自动填充后，它就不再是json，这样下次加载，要新增字段，程序会识别不出来原数据。

zaq11qaz ***@***.***>于2021年8月12日 周四下午5:54写道：
