### ISSUE TITLE
如果在添加成员时，再增加个列表，能看到所有成员就好了

### ISSUE THREAD

**Issue by sys0613** [star7th/showdoc#145]
如果在添加成员时，再增加个列表，能看到所有成员就好了，目前只能去问其他人用户名是什么，再添加

**Comment by star7th** [comment]
主要考虑到权限问题。不应该所有人都有权限看到本站的所有用户

**Comment by sys0613** [comment]
那您看看这样呢，用一个组功能，事先可以定义一个项目组，将相关人员加进来，然后其中成员建一个项目以后，当他想设定项目成员时，组内人员他是可见的，他直接勾选就行了。这种方式能否稍稍好一点呢？

**Comment by star7th** [comment]
成员组的想法可以后续考虑下

**Comment by whsheng** [comment]
类似的问题，我创建了一个项目，现在需要邀请其它人加入，即新增组员，但我如何知道团队成员，已经是showdoc的成员？

**Comment by star7th** [comment]
@whsheng 直接问对方吧。
showdoc暂时还没有做邮件邀请机制。大概最完善的流程是输入对方邮箱地址，存在则添加，不存在则发邮件邀请
