### ISSUE TITLE
BUG:流程图中包含搜索框搜索的文字时，流程图上的文字会暂时不显示

### ISSUE THREAD

**Issue by sslsimon** [star7th/showdoc#1451]
###  原流程图：
![WES}}__GBWTP0$9LI YXOFR](https://user-images.githubusercontent.com/2697155/129659176-2e94a86e-8c4e-4b6b-970f-3c2d47801f26.png)
### 搜索“测试”二字后效果 
![BY0{@A{F{A84IY X5WUAHF3](https://user-images.githubusercontent.com/2697155/129659163-0bf99fad-013f-42df-beba-a2f42c9244b6.png)

**Comment by star7th** [comment]
这个后面看下

**Comment by star7th** [comment]
寻思了一阵子。这个问题的存在是因为，搜索的时候，会给关键字加上高亮的样式。而流程图中如果使用了高亮样式则会无法识别。所以该关键字消失了。
这个场景用的很少，而修复起来太麻烦，所以就不修复了。
