### ISSUE TITLE
runapi文档没有一个方法能同步到showdoc中

### ISSUE THREAD

**Issue by zhifeifu** [star7th/showdoc#1453]
公司的项目是用的showdoc，每次写接口都要去编辑markdown，有点繁琐。
使用runapi可以在调试接口的时候自动生成文档，比较方便，但需要把这个自动生成的文档，在公司的项目中创建一个给前端看。
最开始想的是，runapi生成的文档转成markdown然后复制到showdoc那边。也就多一步复制操作。可惜现在没有。

**Comment by star7th** [comment]
你使用的在线runapi，右上角有个  完整客户端 的按钮。用它可以自动同步到showdoc中。
