### ISSUE TITLE
RunAPI在没有外网的环境，打开空白

### ISSUE THREAD

**Issue by beidouyunyun** [star7th/showdoc#1463]
在没有外网的环境中如何正确使用RunAPI

**Comment by star7th** [comment]
没办法。runapi尚不支持离线版。

风舒云卷-北斗不移 ***@***.***> 于2021年9月1日周三 上午11:22写道：

**Comment by beidouyunyun** [comment]
多谢，有计划有离线版吗？

**Comment by star7th** [comment]
短期内不会有这个计划吧。离线功能挺麻烦的

风舒云卷-北斗不移 ***@***.***> 于2021年9月1日周三 上午11:33写道：

**Comment by star7th** [comment]
现在win版runapi已经支持离线内网使用。到这个页面重新下载安装 https://www.showdoc.com.cn/runapi/30291
