### ISSUE TITLE
runapi 客户端Mac版 headers 设置X-*不会发送请求

### ISSUE THREAD

**Issue by 1521783500** [star7th/showdoc#1465]
**headers :**

> X-App-Version:4.3.0-6  
> X-Serial:cf9784ca-316b-4229-8f3c-5f223b4c439a 
> X-Auth:rP18BSdCOrWgkKYAiOhZE5ZgblI= 
> X-User-Id:111 
> X-Relative-Id: 111
> X-Hospital-Id:1
> X-Seed:1111 
> X-OsType:ios 
> X-Api-Version:1

去掉 headers 可以正常访问

**Comment by star7th** [comment]
理论上是可以发送请求的。请注意，如果你是复制粘贴，不要让header名带空格，发不出去的。
