### ISSUE TITLE
runApi 支持cookies

### ISSUE THREAD

**Issue by fs-danaus** [star7th/showdoc#1466]
官方能否考虑实现 runApi 对cookies的支持？

**Comment by star7th** [comment]
这块有计划做的

fs-danaus ***@***.***> 于2021年9月6日周一 下午2:24写道：

**Comment by fs-danaus** [comment]
有具体计划时间了吗，希望能尽快实现，谢谢！

**Comment by star7th** [comment]
看这个星期有没有时间搞吧

fs-danaus ***@***.***> 于2021年9月6日周一 下午10:30写道：

**Comment by star7th** [comment]
去重新下载runapi客户端，https://www.showdoc.com.cn/runapi  ， 已经支持cookie功能。在填写header参数的判断有个Cookies按钮。
