### ISSUE TITLE
Oauth2登录回调之后提示“登录成功但无法获取用户信息”

### ISSUE THREAD

**Issue by Mr-Maidong** [star7th/showdoc#1467]
showdoc中无报错日志，用户中心也没有收到showdoc访问User info path的访问记录。

**Comment by star7th** [comment]
是不是在获取用户信息之前的接口就已经授权失败了

**Comment by Mr-Maidong** [comment]
> 是不是在获取用户信息之前的接口就已经授权失败了

从我用户中心的接口日志看获取token的接口已经正常拿到access_token了。

**Comment by star7th** [comment]
那你检查下用户信息接口地址对不对

Mr-Maidong ***@***.***> 于2021年9月6日周一 下午7:05写道：

**Comment by star7th** [comment]
能不能从服务器访问

Chen Xing ***@***.***> 于2021年9月6日周一 下午8:09写道：
