### ISSUE TITLE
Swagger4导入json问题

### ISSUE THREAD

**Issue by zhongqingbin** [star7th/showdoc#1468]
您好，导入swagger文件出问题。在issue看到你说解决了，是否还没更新？

[swagger.txt](https://github.com/star7th/showdoc/files/7115251/swagger.txt)
![image](https://user-images.githubusercontent.com/7828474/132203862-d78d1455-c864-41cb-b365-2fb5be6ec2ea.png)

**Comment by star7th** [comment]
是解决过的。莫非格式又变了？s我晚点再看下

**Comment by zhongqingbin** [comment]
嗯嗯，感谢，感谢，我是看你解决过，然后尝试用这个文件导入还是不行。不着急，辛苦了
