### ISSUE TITLE
[Bug]页面右侧配置项展开问题

### ISSUE THREAD

**Issue by Jona-lee** [star7th/showdoc#1469]
页面右侧配置项，点击“更多” 倒三角，展开配置项后，刷新页面，展开部分的配置项被目录覆盖，如果想再次看到，需要点击两次“更多”倒三角的图标
![image](https://user-images.githubusercontent.com/3770638/132276826-e7e17b9c-42fd-4ee2-a176-ccc3ba36e2ef.png)

**Comment by star7th** [comment]
是因为后来加了一个记住状态的功能。当用户展开过菜单后，下次打开将自动展开菜单。

Jona-lee ***@***.***> 于2021年9月7日周二 上午10:54写道：

**Comment by star7th** [comment]
新版解决了
