### ISSUE TITLE
对接LDAP以后之前的存量用户的权限如何手动和LDAP用户关联

### ISSUE THREAD

**Issue by eno16777736** [star7th/showdoc#1470]
已经运行的showdoc目前存在上百用户，现在要使用LDAP进行登陆授权，如何把之前的用户的权限和LDAP的账号相关联？

**Comment by star7th** [comment]
没有做关联。暂时没办法。

eno16777736 ***@***.***> 于2021年9月8日周三 上午11:44写道：

**Comment by eno16777736** [comment]
用户的授权信息存储在什么地方，我可以手动导出来做批量更新吗？

**Comment by star7th** [comment]
没有手动导入导出功能。你这样不如同步用户到管理后台然后自己重新给这些用户赋权

eno16777736 ***@***.***> 于2021年9月8日周三 下午1:55写道：

**Comment by eno16777736** [comment]
对接LDAP以后，之前开通的老账户还能登录吗？

**Comment by star7th** [comment]
说实话我没试过这么做。理论上可以的


eno16777736 ***@***.***> 于2021年9月8日周三 下午2:07写道：

**Comment by eno16777736** [comment]
接入ldap以后经常会出现卡死无响应的情况

**Comment by star7th** [comment]
登录的时候卡死无响应还是什么时候，另外，使用docker方式安装的吗

eno16777736 ***@***.***> 于2021年9月9日周四 上午11:39写道：

**Comment by eno16777736** [comment]
docker 安装的，登录之后操作一段时间就502了

**Comment by star7th** [comment]
是不是你自己的服务器可用资源太少了。另外自己有绑定域名吗，是直接用4999端口吗，又改动过官方的安装步骤吗
