### ISSUE TITLE
老版本升级最新版本!!!

### ISSUE THREAD

**Issue by kiwi2019** [star7th/showdoc#1472]
以前比较老的版本升级到最新版本：
操作如下：
1.下载最新源码，解压，直接把代码放到环境
2.直接访问http://doc.com/install安装，提示安装成功
3.复制老的/Sqlite/showdoc.db.php到新版本相同目录覆盖，覆盖，覆盖...
4.复制老的/Public/Uploads/所有目录文件到新版版本相同目录
5.登录管理员账号，成功，点击我的项目 报错... 

SQLSTATE[HY000]: General error: 1 no such table: item_sort 。错误位置：E:\dev\php\showdoc\server\ThinkPHP\Library\Think\Db\Driver.class.php 174

应该是数据库、表结构有做修改，老版本的结构对不上的问题！ 
是否有相应的sql升级脚本或者该问题有没有其他解决方法？？？
还是我的操作有问题？

**Comment by star7th** [comment]
退出重新登录试下

kiwi2019 ***@***.***>于2021年9月9日 周四下午5:43写道：

**Comment by kiwi2019** [comment]
不行的，操作完都是有重新登录的...

**Comment by star7th** [comment]
当你重新登录的时候，应该会自动触发自动升级数据库结构的脚本。你这个应该就是升级不了的情况了。检查下是不是/Sqlite/showdoc.db.php不可写
