### ISSUE TITLE
Error: settings.emoji == false

### ISSUE THREAD

**Issue by gabacai** [star7th/showdoc#1473]
MAC客户端编辑框内组合键Control+e,报错:'Error: settings.emoji == false'

**Comment by star7th** [comment]
这个是触发了插入emoji表情的快捷键。而emoji，被禁用了。我觉得这个问题可忽略吧。

Clark Liu ***@***.***> 于2021年9月13日周一 上午11:13写道：

**Comment by gabacai** [comment]
你知道.Control+e在编辑框里面是让光标去到行尾.可以无鼠标编辑录入.所以,这对我来说很重要.

**Comment by star7th** [comment]
我很少用这个。刚刚去编程的编辑器里试了下，ctrl+e并不是到行尾，这个不算是通用规则吧？感觉showdoc不支持它不是特别过分。

Clark Liu ***@***.***> 于2021年9月13日周一 上午11:25写道：

**Comment by gabacai** [comment]
这个特性是MAC/Linux系统全局的,任何文本框都适用.下面是常用快捷键

移动光标快捷键
Control-F 光标前进一个字符，相当于右键（F = Forward）
Control-B 光标后退一个字符，相当于左键（B = Backward）
Control-P 上移一行，相当于上键（P = Previous）
Control-N 下移一行，相当于下键（N = Next）
Control-A 移动到一行的开头（A = Ahead）
Control-E 移动到一行的结尾（E = End）
文字删除快捷键
Control-H 删除光标前面的字符
Control-D 删除光标后面的字符
Control-K 删除从光标开始，到一行结尾的所有字符
文字选择快捷键
Control-Shift-A 选中从光标开始，到一行开头的所有文字
Control-Shift-E 选中从光标开始，到一行结尾的所有文字

**Comment by star7th** [comment]
showdoc使用的是这个开源编辑器 https://github.com/pandao/editor.md  应该是编辑器本身不支持你说的这个快捷键
