### ISSUE TITLE
关于历史项目和runapi的关联问题

### ISSUE THREAD

**Issue by clip-tail** [star7th/showdoc#1475]
我发现已经存在showdoc上的项目好像没法导入到runapi里，这就导致没法往历史项目里用runapi添加接口文档，请问这个问题有办法处理么

**Comment by star7th** [comment]
https://github.com/star7th/showdoc/issues/1381

**Comment by clip-tail** [comment]
> 
> 
> #1381

好的,知道了,谢谢
