### ISSUE TITLE
两人编辑表格，编辑人退出页面后，另一个人，仍无法编辑，一直提示【当前页面正在被其他成员锁定编辑中，编辑者：xxx】

### ISSUE THREAD

**Issue by wangbin6** [star7th/showdoc#1477]
两人编辑表格，编辑人退出页面后，另一个人，仍无法编辑，一直提示【当前页面正在被其他成员锁定编辑中，编辑者：xxx】

**Comment by star7th** [comment]
这个问题在新版修复了，更新新版吧

doc.Wang ***@***.***> 于2021年9月18日周六 上午10:55写道：
