### ISSUE TITLE
通用登录问题

### ISSUE THREAD

**Issue by KsxS666** [star7th/showdoc#1478]
通用登录打开根据文档生成的链接提示项目已过期或已删除
md5加密的字符串拼接是有什么要求吗
目前是按直接拼接的形式
或者是需要什么分隔符分割参数吗?

**Comment by star7th** [comment]
把你拼接的链接发出来一下

KsxS666 ***@***.***>于2021年9月18日 周六下午2:10写道：

**Comment by KsxS666** [comment]
http://10.5.30.70:4999/web/#server/?s=/api/extLogin/bySecretKey&username=admin&time=1631945833&token=44a358649631b8d747a36db0d46d2b99&redirect=http://10.5.30.70:4999/web/#/6

**Comment by KsxS666** [comment]
因为这是部署在内部网里面的所以外网是打不开...

**Comment by KsxS666** [comment]
因为其他参数是固定的 所以我怀疑是token生成这一环节出问题了

**Comment by star7th** [comment]
文档怎么说的，跳转的url要做urlencode转码。

KsxS666 ***@***.***>于2021年9月18日 周六下午2:22写道：

**Comment by KsxS666** [comment]
是encodeUri()吗
依然不行

**Comment by star7th** [comment]
redirect参数要url转码，不用语言有不同实现，自己找下

**Comment by star7th** [comment]
如果不行，把专门后的登录链接发出来

**Comment by KsxS666** [comment]
http://10.5.30.70:4999/web/#server/?s=/api/extLogin/bySecretKey&username=admin&time=1631945833&token=d09161ed3226c449e7fd0559cbf8226d&redirect=http%3A%2F%2F10.5.30.70%3A4999%2Fweb%2F%23%2F6
我用的是js 的encodeURIComponent
我看文档上这个redirect是可选值..
我不加redirect这个参数也是提示项目已删除或者不存在,依然没有登录成功

**Comment by star7th** [comment]
你是不是后台设置了首页是跳转到某个项目，而那个项目不存在。你把跳转后的链接发一下

KsxS666 ***@***.***> 于2021年9月18日周六 下午2:52写道：

**Comment by star7th** [comment]
提示不存在的时候的链接

Chen Xing ***@***.***> 于2021年9月18日周六 下午2:53写道：

**Comment by KsxS666** [comment]
后台那边配置的网站首页是全屏介绍页面
我单独浏览器打开这个跳转路径,就是我需要跳转到的项目是可以打开
解密后就是http://10.5.30.70:4999/web/#/6
提示不存在时候的链接:
http://10.5.30.70:4999/web/#server/?s=/api/extLogin/bySecretKey&username=admin&time=1631945833&token=d09161ed3226c449e7fd0559cbf8226d&redirect=http%3A%2F%2F10.5.30.70%3A4999%2Fweb%2F%23%2F6

**Comment by star7th** [comment]
我才意思到你host写错了，不需要带web、#。 http://10.5.30.70:4999/server/?s=/api/extLogin/bySecretKey&username=admin&time=1631945833&token=44a358649631b8d747a36db0d46d2b99&redirect=http://10.5.30.70:4999/web/#/6

**Comment by KsxS666** [comment]
这我之前有试过
我刚才再试了一下去掉web/#/
页面上报错
{"error_code": 10101, "error_message": "\u5df2\u8fc7\u671f"}

**Comment by KsxS666** [comment]
空白页

**Comment by star7th** [comment]
你json解码就知道这是过期的意思了

**Comment by KsxS666** [comment]
具体是什么过期呢...
时间戳(秒为单位)是在跳转前重新生成的

**Comment by star7th** [comment]
时间戳十分内的才有效。一般人使用的时候都是生成就很快用掉。

KsxS666 ***@***.***> 于2021年9月18日周六 下午3:19写道：

**Comment by star7th** [comment]
你这个是吃亏在纯手动拼凑参数。如果写程序随机生成时间戳随时测试不会遇到此问题。

Chen Xing ***@***.***> 于2021年9月18日周六 下午3:31写道：

**Comment by star7th** [comment]
实际上接入通用登录就是应该用程序测试的

Chen Xing ***@***.***> 于2021年9月18日周六 下午3:33写道：

**Comment by KsxS666** [comment]
我这边是前端开发
oa系统需要一个说明文档通过某个link跳转.....
按目前的情况我真不知道咋办了...

**Comment by KsxS666** [comment]
我这边是前端开发
oa系统需要一个说明文档通过某个link跳转.....
按目前的情况我真不知道咋办了...

**Comment by star7th** [comment]
问后端开发去。集成不同的系统不是后端人员的工作吗。

KsxS666 ***@***.***> 于2021年9月18日周六 下午3:40写道：

**Comment by KsxS666** [comment]
好吧
我跟我同事再研究研究
多谢了...

**Comment by KsxS666** [comment]
已解决.
时间戳前端js获取会导致showDoc返回过期问题
时间戳参数由后端接口返回即可.
另外host无需/web/#

**Comment by zhxiaofeng** [comment]
> 已解决. 时间戳前端js获取会导致showDoc返回过期问题 时间戳参数由后端接口返回即可. 另外host无需/web/#

你好！请问你这个时间戳参数由后端接口返回即可是什么意思？
有返回时间戳的接口吗？谢谢

**Comment by KsxS666** [comment]
你可以让你们后台写一个专门获取时间戳的接口，取到值后拼接 url 再执行跳转，因为这个时间戳参数值由前端生成的话有时间差不准确导致报过期错误

**Comment by KsxS666** [comment]
> > 已解决. 时间戳前端js获取会导致showDoc返回过期问题 时间戳参数由后端接口返回即可. 另外host无需/web/#
> 
> 你好！请问你这个时间戳参数由后端接口返回即可是什么意思？ 有返回时间戳的接口吗？谢谢
你可以让你们后台写一个专门获取时间戳的接口，取到值后拼接 url 再执行跳转，因为这个时间戳参数值由前端生成的话有时间差不准确导致报过期错误
