### ISSUE TITLE
在哪里可以查看当前showdoc的版本号？

### ISSUE THREAD

**Issue by wuwu20048** [star7th/showdoc#1480]
在哪里可以查看当前showdoc的版本号？

**Comment by star7th** [comment]
目录下的composer.json文件

xfgg ***@***.***> 于2021年9月22日周三 下午5:50写道：

**Comment by wuwu20048** [comment]
docker镜像是最新版本了吗，好像通过docker更新方式，还是之前的版本

**Comment by star7th** [comment]
要按照官网教程来升级，别简单地以为是更新镜像就可以。 https://www.showdoc.com.cn/help/65610

**Comment by star7th** [comment]
不对，我刚试了下，似乎不太成功。可能是阿里国内镜像没更新。你试着用docker官方镜像地址。
奇怪了，国内镜像一直都是自动同步的。我得额外看下。

**Comment by star7th** [comment]
已经构建成功了。原因是showdoc用到了alpine 的基础镜像。而alpine 的基础镜像里有些包的名字变更了，导致showdoc 的DockerFile里面有些命令执行失败，导致一直自动构建失败。
细节的话就是nodejs-npm包改名为了npm
