### ISSUE TITLE
使用gitlab oauth2授权登陆，无法正常注册用户信息

### ISSUE THREAD

**Issue by wuwu20048** [star7th/showdoc#1481]
配置截图如下
![](https://tva1.sinaimg.cn/large/008i3skNly1guqmx9v8trj60u011wmzx02.jpg)

点击授权登陆
![](https://tva1.sinaimg.cn/large/008i3skNly1guqmyvj7cxj60p00m0gm802.jpg)

前端提示：

![](https://tva1.sinaimg.cn/large/008i3skNly1guqmzkw1j4j60t40jcdgd02.jpg)

查看后台用户数据，授权登陆后，用户名为空
![](https://tva1.sinaimg.cn/large/008i3skNly1guqmrk8qy5j61yo0o2dia02.jpg)

这样可能是哪里出问题了？

**Comment by star7th** [comment]
不知道是不是preferred_username 字段的兼容问题  https://github.com/star7th/showdoc/issues/1460  我现在修改了下兼容代码，你更新下

**Comment by wuwu20048** [comment]
应该不是吧，通过/api/v3/user 这个接口获取到的用户信息，用户名字段就是username

**Comment by star7th** [comment]
我看你截图里，resource path补全试下？

**Comment by wuwu20048** [comment]
resource path填什么我没找到，这个应该不是必填的吧。另外你之前说的更新，是指通过更新脚本更新吗

**Comment by star7th** [comment]
更新按教程来 https://www.showdoc.com.cn/help/13732 
resource path 我是用其他oauth登录测试的，gitlab不清楚。

**Comment by bluesky4485** [comment]
最新版本的showdoc还是会存在这个问题，gitlab的登陆集成不正常，点gitlab登陆后会有几个跳转，然后又回到登陆界面了。

后台管理能看到很多空用户名的账户。

**Comment by star7th** [comment]
应该是获取用户信息那里没获取到。所以用户名是空。showdoc在这方便忘记做异常判断了。至于为什么获取不了用户名，我猜测是授权不正确。
现在我已经更新了一个版本 https://github.com/star7th/showdoc/commit/342c5defe4e1f24cdfa1eece071e78649291a482 ，你更新后再重试一下。这次有做异常判断，你看提示信息也许可以知道哪里出错。

**Comment by bluesky4485** [comment]
@star7th 找到错误原因了。  gitlab的获取用户信息的接口不是post请求的   是get请求的 
这个地方 使用http_post返回了404 not found，我直接用postman试了一下，确认相同参数 post报404，get正常返回数据。
![image](https://user-images.githubusercontent.com/442591/153412821-28008bb4-d128-4d0e-8557-0cb59ff62f9a.png)
这块要怎么做下兼容性处理？

**Comment by star7th** [comment]
我修改了代码，用get方式请求了。你更新后试下 。 https://github.com/star7th/showdoc/commit/e610f96fdb2999b433d53198f163a469edf0e636

**Comment by bluesky4485** [comment]
@star7th 修改之后 使用gitlab登陆正常了。
给后来的人参考一下，本人gitlab版本 14.7.   userinfo path 是  /api/v4/user
