### ISSUE TITLE
RunApi  传参 uint64 类型会溢出

### ISSUE THREAD

**Issue by Youngyezi** [star7th/showdoc#1483]
在使用 json raw 传参时候 uint64 类型数据会溢出

**Comment by star7th** [comment]
runapi是32位程序，暂时无法支持

Youngyezi ***@***.***> 于2021年9月27日周一 下午7:52写道：

**Comment by star7th** [comment]
runapi客户端已经改用64位版，可以支持大整数类型。卸载原客户端，然后去下载新的安装即可 https://www.showdoc.com.cn/runapi/30291
