### ISSUE TITLE
使用swagger.json的方式导入，原来的object类型结构信息全部丢失了，类型变成了string

### ISSUE THREAD

**Issue by LatitudeMaster** [star7th/showdoc#1484]

**Comment by star7th** [comment]
你可以附上你的swagger.json示例，我有空再看下

**Comment by LatitudeMaster** [comment]
> 你可以附上你的swagger.json示例，我有空再看下
![无标题](https://user-images.githubusercontent.com/24709587/136490631-f5d34fc6-88bd-4924-a036-03fedd16ab02.png)

**Comment by star7th** [comment]
没有文件给我分析，我做不了什么。
