### ISSUE TITLE
runapi导出文档能否可以选择指定的接口导出

### ISSUE THREAD

**Issue by skipify** [star7th/showdoc#1485]
runapi导出文档能否可以选择指定的接口导出

**Comment by skipify** [comment]
现在导出是直接导出全部，我这上百个接口一下导出 word打开都卡死...

**Comment by star7th** [comment]
这个后面考虑支持

**Comment by dongshasha812** [comment]
我本地的runapi点击导出没有反应呢

**Comment by star7th** [comment]
现在已经支持。重启runapi自动更新到最新版。然后点击具体接口的分享文档链接框，导出离线项目。便可以导出当前接口的word
