### ISSUE TITLE
使用雪花算法作为id回显id出现精度丢失

### ISSUE THREAD

**Issue by zddghost** [star7th/showdoc#1487]
606631627273625612 这个是实例id 回显id606631627273625000 会丢失后3位进度 long类型的数据

**Comment by star7th** [comment]
https://github.com/star7th/showdoc/issues/1483  runapi是32位程序，暂时无法支持

**Comment by star7th** [comment]
runapi客户端已经改用64位版，可以支持大整数类型。卸载原客户端，然后去下载新的安装即可 https://www.showdoc.com.cn/runapi/30291
