### ISSUE TITLE
手机浏览器无法打开web客户端

### ISSUE THREAD

**Issue by buqiaomuyudeheshang** [star7th/showdoc#1488]
我尝试使用docker部署和官网的，在手机上都无法打开项目！期望能够兼容一下。

**Comment by star7th** [comment]
请截图说明

buqiaomuyudeheshang ***@***.***> 于2021年10月9日周六 上午11:53写道：

**Comment by star7th** [comment]
不支持使用手机编辑网页showdoc。可考虑使用showdoc app

buqiaomuyudeheshang ***@***.***> 于2021年10月9日周六 下午1:53写道：

**Comment by buqiaomuyudeheshang** [comment]
感谢你的解答！
我有使用手机客户端。有时候难免会遇到没装客户端的人。所以想着尝试使用手机浏览器查看！

**Comment by star7th** [comment]
项目展示页是可以手机查看的，可以分享项目给手机用户看。但是手机不能登录编辑
