### ISSUE TITLE
本地部署后，在url输入错误地址会报重定向过多

### ISSUE THREAD

**Issue by rogerhesong** [star7th/showdoc#1491]
私有部署，采用自动脚本部署在Linux上，正常地址：xx.xx.xx.xxx:4999/web/#,如果输入的是xx.xx.xx.xxx:4999/web/abc，就回报重定向过多，如下图：
![image](https://user-images.githubusercontent.com/12381976/136721438-f012df87-ad23-45c0-b46c-ce70ca65c91d.png)

**Comment by star7th** [comment]
请输入一个合法url。

**Comment by star7th** [comment]
合法url在web后面带#符号的

**Comment by rogerhesong** [comment]
> 输入xx.xx.xx.xxx:4999/web/abc 本身是非法情况，没有人会这么做。

因为我这项目关联域名后要对外开放的，很容易引起外部恶意遍历的吧？

**Comment by star7th** [comment]
所有私密数据都应该放加密项目。公开项目默认就是能被人访问和遍历的

**Comment by star7th** [comment]
改动大。我的建议是不要改。
