### ISSUE TITLE
目录是否有单独的链接

### ISSUE THREAD

**Issue by Colby242222** [star7th/showdoc#1499]
![image](https://user-images.githubusercontent.com/92919109/138252044-7632bd3b-9891-479e-9dea-58a57f8e85d2.png)

**Comment by Colby242222** [comment]
悲催。有时只想分享某个目录下的 文档给别人看。。。页面太多，一个个点击分享链接又好麻烦。

**Comment by zsinba** [comment]
+1

> 悲催。有时只想分享某个目录下的 文档给别人看。。。页面太多，一个个点击分享链接又好麻烦。
