### ISSUE TITLE
页面分享没有继承项目的权限控制

### ISSUE THREAD

**Issue by CinderellaCiCi** [star7th/showdoc#15]
被分享的页面可以直接查看，没有继承项目的权限控制。

项目如果非公开，建议需要输入项目的访问密码或者登陆后才能查看，打开链接后先出现/showdoc/index.php/home/item/pwd这个页面。

同时pwd页面建议改进：
1.提示【项目名称】的访问密码；
2.“登陆/注册”后如果有权限则跳转至前面的链接，无权限则保持现状。

**Comment by star7th** [comment]
有继承的，请关闭浏览器或者清空所有Cookies再进行权限测试；
提示项目名称——没有一定的必要去提示，没必要的需求不做。而且项目标题如果过长还会把页面标题弄得难看；
登录注册跳转机制保持不变，主要是觉得跳来跳去麻烦。
我现在新增了一个机制，当用户访问别人发给他的项目时，如果此用户已经用过Showdoc，则会自动Cookies登录并权限判断，这样便可以不用每次输入访问密码或者登录；对于全新的用户，他依然只能注册登录后再点开你发给他的链接

**Comment by CinderellaCiCi** [comment]
我自己内网搭建的showdoc，页面分享给其他同事他能打开看呢。

这个同事没有用过showdoc、没有注册账号、而且我分享的链接所属的项目是设了访问密码的。

**Comment by star7th** [comment]
我这边测试是正常的。你试试这个链接：http://doc.star7th.com/index.php/96?page_id=32  它有提示输入密码的

**Comment by CinderellaCiCi** [comment]
我这边还是不行，更新了你刚刚最新的代码还是不可以。
好像问题在URL。。并不是我通过分享链接复制出去的。。

http://doc.star7th.com/index.php/Home/page/index?page_id=32
我的URL结构是这样的。可以看到你的这个页面内容。

**Comment by CinderellaCiCi** [comment]
不是分享按钮那个链接的问题哦，测试了下那部分确实没有问题。
我貌似就是通过浏览器历史进入到某个页面之后看到正好是要给同事的那个页面就直接给他了。

**Comment by star7th** [comment]
请分享应该分享的链接给对方。你分享的本身不是应该分享的链接，此问题不算bug，忽略。

**Comment by CinderellaCiCi** [comment]
。。。

**Comment by star7th** [comment]
想了想，此问题可能导致被别人抓站抓页面私密数据，所以还是给页面加上权限判断了

**Comment by heluo** [comment]
showdoc运行在linux系统下由于linux区分大小写导致编辑完成后不能跳转，算bug还是哪里配置问题啊？

**Comment by star7th** [comment]
好奇怪，我centos没出问题。区分大小写的问题可参考这个来改：https://github.com/star7th/showdoc/pull/50/commits/d8c01a4988acf9a398f696bbee5805736634e5db

**Comment by heluo** [comment]
谢谢，我的已经改好了，谢谢开源这套系统，挺好用的
