### ISSUE TITLE
yyyy-MM-dd HH:mm:ss 的问题

### ISSUE THREAD

**Issue by jeff1992** [star7th/showdoc#150]
会变成<code>"yyy-MM-dd HH"<img src="..." /></code>

**Comment by star7th** [comment]
看不到图片

**Comment by jeff1992** [comment]
<img src="http://images.cnblogs.com/cnblogs_com/mhsg/1050727/o_%e5%be%ae%e4%bf%a1%e6%88%aa%e5%9b%be_20170807180226.png" /> yyyy-MM-dd HH:mm:ss

**Comment by star7th** [comment]
尝试用代码块的方式插入，或者中文引号

**Comment by star7th** [comment]
我在最新代码中修复此问题了
