### ISSUE TITLE
Runapi创建的项目文档不支持showdoc在线编辑，应该允许让用户转showdoc（或克隆后转）

### ISSUE THREAD

**Issue by fangchao2017** [star7th/showdoc#1500]
建议用runapi创建的项目支持用户转在线showdoc，showdoc不能转runapi也没有关系，可以提示用户不可逆，或者先克隆runapi项目后转到showdoc，这样就能满足这2种情况了。

**Comment by star7th** [comment]
你这样做的目的是？假如说是为了调整文档，那么，去runapi调整不是更好吗？如果想你说转markdown文档，但是不能在runapi里用的，以后接口新增也很麻烦。为什么一开始不愿意在runapi里调整

**Comment by fangchao2017** [comment]
因为在团队协作的情况中，编辑文档太依赖runapi了。每个人都需要在有runapi的环境下才能增删改。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "star7th/showdoc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月22日(星期五) 中午11:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [star7th/showdoc] Runapi创建的项目文档不支持showdoc在线编辑，应该允许让用户转showdoc（或克隆后转） (Issue #1500)





 
你这样做的目的是？假如说是为了调整文档，那么，去runapi调整不是更好吗？如果想你说转markdown文档，但是不能在runapi里用的，以后接口新增也很麻烦。为什么一开始不愿意在runapi里调整
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by star7th** [comment]
可是这本来就是runapi项目，这个项目既然存在，表明你们就已经安装了runapi客户端。既然安装了，打开也不麻烦

**Comment by star7th** [comment]
如果说转markdown了，用户增删改了，可是下次还要增删改呢，要增加接口呢，要调试呢，要测试呢。不能贪一时爽，而堵住了后面的维护性啊

**Comment by fangchao2017** [comment]
或者runapi加个导出markdown 功能，我自己再手动导入， 这样就ok了。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "star7th/showdoc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月22日(星期五) 中午11:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [star7th/showdoc] Runapi创建的项目文档不支持showdoc在线编辑，应该允许让用户转showdoc（或克隆后转） (Issue #1500)





 
在runapi客户端里也能增加目录啊。为啥抗拒使用客户端呢，postman不也是客户端么
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by star7th** [comment]
runapi客户端有win版/mac版/linux版，基本覆盖了大部分平台情况，谈不上安装不了的问题。我觉得这只是你不习惯用客户端而已。我暂时还是不想开你说的这个功能，因为真的没这个必要，直接用一下客户端就能解决的问题，不需要绕一个大圈，并且还堵死了后期维护的路。

**Comment by bo961386926** [comment]
这里涉及到一个runapi云化版本迁移到本地化的问题，假如我使用云化的runapi生成文档，如何将已有数据迁移到本地，runap提供的导出功能，目前是无法按使用的咯

**Comment by anlondon** [comment]
> 在runapi客户端里也能增加目录啊。为啥抗拒使用客户端呢，postman不也是客户端么

我用showdoc两年了，runapi用了也快一年了，现在一点也不喜欢runapi客户端，太难用了。时不时无法送法请求，连提示都没有。如果不是老项目，早就放弃了。

**Comment by csoftware** [comment]
“Runapi创建的项目文档不支持showdoc在线编辑”，我看这个议题作者也留了口子的->浏览器地址栏输入
http://ip:port/web/#/项目id/文章页的id是可以进入编辑页面，跟showdoc的项目进入页编辑一样
