### ISSUE TITLE
为什么 POST 请求不能设置 url 参数, GET 请求不能 在 body 里放内容?

### ISSUE THREAD

**Issue by enostim** [star7th/showdoc#1506]
HTTP 协议 GET 和 POST 没有任何区别. postman 没有对其区别对待, 你们这倒好, 还限死了 get 必须url, post 必须 body 了

**Comment by star7th** [comment]
runapi已经更新了一个版本，重启就会自动更新完毕。这个版本里，参数分开成了body和query 。当你选择post方式的时候，可以填写body也可以填写query
