### ISSUE TITLE
mock 地址 自定义参数

### ISSUE THREAD

**Issue by isPony** [star7th/showdoc#1507]
![Z8QQ7C_9DI7QZ_W9NDBARYE](https://user-images.githubusercontent.com/5069322/139381167-0684532c-7034-43f1-957b-8dde044a08b9.png)

1. 参数未做去重处理：多个mock可以使用相同的参数，最终可能无法正确访问到需要的mock结果
2. 可否保留原来的自动生成：自动生成+自定义参数

**Comment by brizer** [comment]
私有化部署后的showdoc的runapi的mock，跨域cors防住了，请问怎么配置可以让mock的url可以跨域？

**Comment by star7th** [comment]
跨域问题问前端。不懂跨域的前端不是好前端。一般在开发环境就可以配置代理

**Comment by brizer** [comment]
> 跨域问题问前端。不懂跨域的前端不是好前端。一般在开发环境就可以配置代理

。。。。解决了，还是得兼容下的，易用性是工具的考量标准之一。在线接口mock一般都允许跨域的。
