### ISSUE TITLE
ShowDoc 本地部署运行一段时间后无法登录

### ISSUE THREAD

**Issue by 1647028806** [star7th/showdoc#1508]
我这边在服务器上用docker的方式部署ShowDoc，运行一段时间后，所用的用户都无法登录了。提示"你尚未登录"
另外新用户注册时提示"管理员已关闭注册"

请问该怎么解决？

**Comment by lazydan** [comment]
你如果单进程php, 可能会导致卡死的问题, 网上有弄多php进程调度的教程
