### ISSUE TITLE
oauth2登陆支持企业微信登陆吗？

### ISSUE THREAD

**Issue by yunskyline** [star7th/showdoc#1509]
能否添加企业微信登陆，应该蛮多朋友是接入企业微信使用的。

**Comment by star7th** [comment]
我不是很清楚企业微信平台的行为。showdoc支持标准的oauth2协议。理论上企业微信也是oauth2协议。你可以翻企业微信的分档来配置下

**Comment by yunskyline** [comment]
> 我不是很清楚企业微信平台的行为。showdoc支持标准的oauth2协议。实时企业微信也是oauth2协议。你可以翻企业微信的文档来配置下

翻了，但是不懂代码，多了个企业ID与应用id,哪个对应哪个。

**Comment by star7th** [comment]
我没有去研究过。应该是clintid之类的，你可以都试一下

刀客云空 ***@***.***> 于2021年11月1日周一 下午8:10写道：
