### ISSUE TITLE
项目添加团队，默认权限设置为只读是否更好一点，有时内容仅仅是分享而不是协作。

### ISSUE THREAD

**Issue by yunskyline** [star7th/showdoc#1510]
内容分享的情况应该会多于协作。

**Comment by star7th** [comment]
我个人认为协作的情况多于分享的。因为分享的大部分情形都是直接分享链接出去，分享团队的话，多数是为了合作。如果有更多人反馈的话，再综合考虑下改不改。

刀客云空 ***@***.***> 于2021年11月1日周一 上午1:36写道：

**Comment by forgaoqiang** [comment]
既然有这个功能，哪个是默认都无所谓了吧

**Comment by star7th** [comment]
新版已经在团队成员项目权限那里增加了一键设置为只读的按钮。所以设置全部为只读的操作方式也不难。因此推荐还是默认编辑，手动设置只读的方式。
