### ISSUE TITLE
本地部署更换网段后无法访问

### ISSUE THREAD

**Issue by leehyunhoe** [star7th/showdoc#1511]
原网段192.168.2.****。公司换网络设备后网段变成了192.168.1.****。然后我把服务器地址也改成对应地址后就无法访问服务了。其他项目都能访问。换回原来的网段后又正常了。但是公司要求用新的网段。这个问题怎么解决呢

**Comment by star7th** [comment]
是不是你自己有什么防火墙限制定了ip。这种网络访问问题一般都还没到showdoc这一层，理论上跟showdoc没关系

leehyunhoe ***@***.***> 于2021年11月7日周日 上午10:12写道：

**Comment by leehyunhoe** [comment]
防火墙已经关掉了，也ping得通新的网段。服务器里面其他项目全部都是可以正常访问的就唯独showdoc不行。

**Comment by star7th** [comment]
是用什么方式安装的showdoc

leehyunhoe ***@***.***> 于2021年11月7日周日 上午10:17写道：

**Comment by leehyunhoe** [comment]
自动脚本安装

**Comment by star7th** [comment]
那大概是docker端口映射有问题吧。尝试换网段后重启showdoc，或者执行一次更新命令

leehyunhoe ***@***.***> 于2021年11月7日周日 上午10:19写道：

**Comment by leehyunhoe** [comment]
我尝试重启过也没用。换回原来的网段已重启就好了

**Comment by star7th** [comment]
参考这个教程当作新服务器来迁移吧 https://www.showdoc.com.cn/help/2511252204165611
 或者找一台中间服务器，迁移过去再迁移回来

leehyunhoe ***@***.***> 于2021年11月7日周日 上午10:23写道：
