### ISSUE TITLE
runapi导出失效

### ISSUE THREAD

**Issue by dongshasha812** [star7th/showdoc#1512]
runapi客户端某个项目点击导出跳转页面后空白无反应

**Comment by star7th** [comment]
网页showdoc端能正常导出word吗

dongshasha812 ***@***.***> 于2021年11月8日周一 上午10:54写道：

**Comment by dongshasha812** [comment]
可以导出  就是runapi上面所有项目都没反应

**Comment by star7th** [comment]
用什么方式安装的

dongshasha812 ***@***.***> 于2021年11月8日周一 上午10:57写道：

**Comment by dongshasha812** [comment]
官方下载windows客户端

**Comment by star7th** [comment]
我说showdoc服务端是什么方式安装的

dongshasha812 ***@***.***> 于2021年11月8日周一 上午11:01写道：

**Comment by dongshasha812** [comment]
下载的exe安装的

**Comment by star7th** [comment]
你提供一下分享后的项目地址，在runapi目录树上方有分享按钮

dongshasha812 ***@***.***> 于2021年11月8日周一 上午11:05写道：

**Comment by dongshasha812** [comment]
https://www.showdoc.cc/1517844535968585

**Comment by dongshasha812** [comment]
我发现如果是一个接口可以正常导出，如果项目下接口比较多的话 点击导出就没反应

**Comment by star7th** [comment]
因为你这个接口的返回数据太多了 https://www.showdoc.com.cn/1517844535968585/7940267750054053

**Comment by dongshasha812** [comment]
返回数据多就不能导出了吗

**Comment by dongshasha812** [comment]
有没有其他的办法呢

**Comment by star7th** [comment]
返回数据那么多，导出都没有意义了。比如说总共文档是50页，你这个接口返回示例都占了40页。这没意思。办法就是不要返回那么多数据。至少在返回示例中不需要完整填上例子。
