### ISSUE TITLE
希望表格新增插入链接功能

### ISSUE THREAD

**Issue by imchj** [star7th/showdoc#1514]
因此希望表格支持插入链接，用于在不同文档和表格间跳转。

**Comment by star7th** [comment]
showdoc的表格是集成了这个开源组件。它不支持的话我没有太好的办法，二次开发不是很容易 https://github.com/myliang/x-spreadsheet

**Comment by imchj** [comment]
> showdoc的表格是集成了这个开源组件。它不支持的话我没有太好的办法，二次开发不是很容易 https://github.com/myliang/x-spreadsheet

好呢，谢谢您
