### ISSUE TITLE
个人觉得是一个严重的展示问题

### ISSUE THREAD

**Issue by kussatom** [star7th/showdoc#1515]
在进到项目里面后， 没有办法点击 直接进入到 首页item/index，搞得每次要去浏览器地址弄一下，相当不方便啊。有时候要在多个项目里面切换，成员管理这些

**Comment by star7th** [comment]
额，有返回按钮的，你找一下。全程不需要动浏览地址。

kussatom ***@***.***> 于2021年11月11日周四 上午9:34写道：

**Comment by kussatom** [comment]
额，看到了，有点不明显 。
