### ISSUE TITLE
复制单页面到另一个项目里

### ISSUE THREAD

**Issue by Colby242222** [star7th/showdoc#1519]
如果想把A项目里的5篇文章，都复制到B项目里，除了一篇篇复制再粘贴在B项目里，还有更便捷的方式吗？

**Comment by star7th** [comment]
目前可以把目录复制到另一个项目中。所以你把这些文章放到一个目录中，然后复制目录即可

**Comment by Colby242222** [comment]
请问如何把目录复制到另一个项目中呢？

**Comment by star7th** [comment]
在目录管理那里可以复制。找不到功能就升级最新版代码先
