### ISSUE TITLE
自动生成API文档中 header 不生效

### ISSUE THREAD

**Issue by lcljcbx** [star7th/showdoc#1520]
* @header token 可选 string 应用认证token 
生成的文档中没有 header 说明，请问是什么原因呢？

**Comment by star7th** [comment]
先尝试升级到最新版 https://www.showdoc.com.cn/help/13732
如果还不行，则检查下生成到https://www.showdoc.com.cn/ 是否正常

**Comment by lcljcbx** [comment]
生成到https://www.showdoc.com.cn/ 是正常的，但是私有版还是没有生成header

**Comment by star7th** [comment]
你确认已经升级到最新版了吗 ，目录下的composer.json文件可以看到版本
