### ISSUE TITLE
2点优化建议

### ISSUE THREAD

**Issue by phoebeyuer** [star7th/showdoc#1521]
使用showDoc时遇到的一些问题，希望后续可以优化下~

1、创建所有人可见的公开项目
建议管理员账号可以创建公开项目，即任何注册用户登录后都能看到该项目，而不用手动去添加项目成员。

2、团队权限分配
现在的项目支持添加团队，但团队的权限默认都是编辑，我们现在遇到一个需求，一些项目只有核心团队的权限是编辑，普通团队的权限都是只读。
如果手动一个个去修改为只读过于麻烦，而且后续如果有新成员加入普通团队，还要单独再设置一次权限。希望能够支持对单个团队设置权限，或者在对团队成员分配权限时，增加一个全选、全不选的按钮。

**Comment by star7th** [comment]
对于第1点，可以考虑吧。对于这种情况，所有人都只能继承只读权限。无法编辑。其实背后还是挺麻烦的，要引入一些新机制来实现。不能复用团队或者项目成员机制，不然用户数多了就有性能问题。我是想着这个功能是否能带来明显的好处，值不值得去这么做
对于第2点，后面考虑增加一键设置为只读功能吧


phoebeyuer ***@***.***> 于2021年11月16日周二 下午9:36写道：

**Comment by star7th** [comment]
新版已经在团队成员项目权限那里增加了一键设置为只读的按钮

**Comment by phoebeyuer** [comment]
> 新版已经在团队成员项目权限那里增加了一键设置为只读的按钮

真棒！辛苦啦~
