### ISSUE TITLE
没有附件管理功能

### ISSUE THREAD

**Issue by sdfweayhgrtjghzhfdhee** [star7th/showdoc#1522]
上传了很多截图，有些已经没用了，但是后台无法分辨哪些是没用的，所以不知道怎么删除，能不能加个检查附件有没有被文章引用的功能，或者一键删除没被引用的附件

**Comment by star7th** [comment]
无解。因为url是可以随便引用的。无法判断有没有被引用。

sdfweayhgrtjghzhfdhee ***@***.***> 于2021年11月17日周三 下午5:00写道：

**Comment by star7th** [comment]
有些人上传附件到showdoc，然后url引用到其他地方的。这个不好一刀切。

sdfweayhgrtjghzhfdhee ***@***.***> 于2021年11月17日周三 下午5:12写道：

**Comment by sdfweayhgrtjghzhfdhee** [comment]
那就做个提醒吧，让用户决定是否删除，一直占着资源也不是办法
