### ISSUE TITLE
水印相关问题

### ISSUE THREAD

**Issue by 42200741** [star7th/showdoc#1523]
现showdoc没有水印功能，使用开源版自行添加水印功能。但是移动端没有办法处理，请问有没有解决办法？

**Comment by star7th** [comment]
后续有空我再做水印功能吧。我目前不清楚你的情况。但是我觉得这个还是官方才好做。

liyue ***@***.***> 于2021年11月18日周四 下午7:39写道：

**Comment by 42200741** [comment]
谢谢回复，无比激动!showdoc是目前我们觉得做团队协作很好的工具，就是有两个地方有问题：1.集成LDAP的时候，由于我们LDAP的人员很多（4万+）当时实际使用showdoc的人员就40多，目前showdoc不支持LDAP组，我们一集成就直接卡死 2.就是上面的水印问题（水印需求只要能显示登录账号、姓名、时间即可），目前已自行代码解决，但是移动端连接以后又没有水印（问题解决60%实在不够完美）希望官方能提供对应的功能就最好。谢谢

**Comment by star7th** [comment]
已经发布新版，可以在管理后台启动水印功能。
