### ISSUE TITLE
阿里云 OSS 图片上传成功但页面报错

### ISSUE THREAD

**Issue by littlemolh** [star7th/showdoc#1524]
报错代码
```
{
error_code: 999
error_message: ":  RequestId:  。错误位置：/www/server/ThinkPHP/Library/Vendor/Alioss/src/OSS/Result/Result.php  97
}
```
oss图片上传记录
![image](https://user-images.githubusercontent.com/26665792/142586569-1ce6124c-39ff-47a2-be84-947f5525ad08.png)

**Comment by star7th** [comment]
实测能上传阿里云并且无报错。
对于你的情况，我怀疑你是使用了nginx转发把header信息给漏了。报错里的RequestId好像是从阿里云oss接口的header中获取的。我不清楚你的服务器为什么读取不到。
另外就是阿里云oss的访问权限要选择  公共读 ， 不要选择 私有。

**Comment by littlemolh** [comment]
我把PHP8.0换成7.4就可以了

**Comment by star7th** [comment]
已经发布新版了。理论上已经解决了该问题
