### ISSUE TITLE
markdown插入表格预览不正确

### ISSUE THREAD

**Issue by geekZZJ** [star7th/showdoc#1526]
![image](https://user-images.githubusercontent.com/26341906/142825772-036fb789-1d88-4f7a-aaed-fb823a7e2046.png)

**Comment by star7th** [comment]
前后留一些空格或者换行符。这是基本的语法问题，你可以多尝试。不懂的话可以点击编辑器的插入表格按钮

geekZZJ ***@***.***> 于2021年11月22日周一 下午4:12写道：
