### ISSUE TITLE
本地部署发现语法错误

### ISSUE THREAD

**Issue by ksi1110** [star7th/showdoc#1527]
[Tue Nov 23 17:01:00.305809 2021] [:error] [pid 4637] [client 192.168.123.15:4206] PHP Parse error:  syntax error, unexpected ')' in /var/www/html/showdoc/server/index.php on line 20, referer: http://192.168.123.168/showdoc/web/
[Tue Nov 23 17:01:00.312133 2021] [:error] [pid 4638] [client 192.168.123.15:4207] PHP Parse error:  syntax error, unexpected ')' in /var/www/html/showdoc/server/index.php on line 20, referer: http://192.168.123.168/showdoc/web/
[Tue Nov 23 17:01:10.460956 2021] [:error] [pid 4640] [client 192.168.123.15:4212] PHP Parse error:  syntax error, unexpected ')' in /var/www/html/showdoc/server/index.php on line 20, referer: http://192.168.123.168/showdoc/web/

![b21883b71eb1e387031dc0b66e354a2](https://user-images.githubusercontent.com/18417132/142998251-850d055f-4883-4b59-8771-19d9280d259e.png)

实测，将19行，逗号删除即可

**Comment by star7th** [comment]
你是手动安装的吗，使用什么版本的php

Nathan ***@***.***> 于2021年11月23日周二 下午5:18写道：

**Comment by ksi1110** [comment]
手动安装的，php版本是5.4.16，这个对php版本有要求么

**Comment by star7th** [comment]
这个是前阵子引入的bug。现在修正了

Nathan ***@***.***> 于2021年11月24日周三 下午4:07写道：
