### ISSUE TITLE
markdown编辑器工具栏在某些设备下存在bug

### ISSUE THREAD

**Issue by elinxer** [star7th/showdoc#153]
谷歌浏览器pc状态下工具栏未注册正确事件，无法点击

现场设备：出现在屏幕可点击的笔记本上，谷歌浏览器最新版59.*

这个是编辑器的bug，不过这编辑器貌似不怎么更新了，所以改不改看大大了，我项目这边改了可以正常，附带出现其他情况暂时没有发现。

参考 https://github.com/pandao/editor.md/issues/375

**Comment by star7th** [comment]
已修改
