### ISSUE TITLE
Mac runApi 保存接口时候出现错误，错误：您的网络发生异常，无法连接runapi-showdoc服务器

### ISSUE THREAD

**Issue by zb-suixinerle** [star7th/showdoc#1531]
**showDoc**： showDoc  安装在自己本地，使用的是本地 loccalhost  版本： 拉取的是master分支最新代码。
**runApi** ：  runapi-1.0.3.dmg  

**经历**：估计在今年7月份（具体记不清了）有尝试用一下你们的runApi 测试了一下，发现很好用，然后昨天更新了一下showDoc 本地代码，然后更新了runApi 客户端，就发现登陆到runApi 之后尝试去新建几个接口，总是出现无法保存的现象。
**二次开发** ：稍微改了一下导出markDown的代码，适应一下自己的个性化导出需求。修改文件： ExportController.php

发现我GET请求不带参数，是能保存成功，带了参数就不能保存成功。我依稀记得7月份的那次尝试没有出现过此类问题。

不知道是我哪里配置出现问题了，还是客户端出现新问题了。苦于手写文档，同事推荐使用showDoc，昨天算是第一次认真使用该软件，后期准备长期尝试。希望作者能确定一下不是客户端出问题了，感谢 🙏

**Comment by star7th** [comment]
我觉得可能是showdoc没更新好。你登录网页版showdoc，新建项目然后新建文档。确保使用正常再连接runapi

**Comment by zb-suixinerle** [comment]
你好，谢谢你的回复！

不知道 showdoc 没更新好是什么意思？

我是在网页版的showDoc 新建了项目，并且runApi 建立的目录还有接口都成功同步过来了，但是在保存接口时出现的。保存接口文档出现这个错误，我尝试开启错误日志，但没有找到日志。（没有仔细去看代码，我改的是Api下的conf里面的config.php, 把API_LOG 开启了没有在runtime目录找到错误日志）。

不知道有没有小伙伴在使用Mac 端 runApi 时遇到了跟我一样的问题。

再次感谢作者抽空回复了我的问题。

**Comment by star7th** [comment]
你先在网页端，退出并重新登录。然后，创建个项目，新建个文档，保存。确认这个过程没问题。从而保证showdoc是正常的

**Comment by star7th** [comment]
先别管runapi的问题。我现在是觉得你要先保证showdoc是正常的

**Comment by zb-suixinerle** [comment]
你好，确定是没有问题的。退出登录，正常建项目，然后新建一个文档，保存成功。一系列的操作都是成功的。

**Comment by star7th** [comment]
我没有听用户反馈过此类问题。也不知道你的参数里是不是有特殊符号导致。我只能说你尝试退出runapi登录，然后连接官网https://www.showdoc.com.cn/ 看看有没有问题。如果官网正常，则可能是你安装的本地哪里不对

**Comment by zb-suixinerle** [comment]
谢谢你的回复，我自己去尝试一下连接官网的服务器。
后续有结果，我会在此处回复。
感谢作者的开源项目。
