### ISSUE TITLE
Mac runApi MacOS Monterey 12.0.1   打开白屏

### ISSUE THREAD

**Issue by Anjinc188** [star7th/showdoc#1532]
系统版本MacOS Monterey 12.0.1 
Mac系统升级后，打开runapi一直处于白屏状态
runapi-1.0.3.dmg

**Comment by star7th** [comment]
可以考虑使用AppCleaner来卸载和清理数据后再重装。

**Comment by star7th** [comment]
另外注意runapi是需要外网的
