### ISSUE TITLE
文档页右侧展开菜单会被目录遮挡

### ISSUE THREAD

**Issue by MHXXX** [star7th/showdoc#1533]
- 版本号: 最新
- 部署方式: docker本地部署
- 问题描述: 第一次进入文档,点击右边菜单的三角符号展开菜单.返回后继续进入,如果有文档目录,则会挡住展开的菜单

![image](https://user-images.githubusercontent.com/29811618/144786825-83b99bce-960c-4daa-9342-c465e2345d6e.png)

**Comment by star7th** [comment]
这个后面有时间再看下

MHXXX ***@***.***> 于2021年12月6日周一 12:24写道：

**Comment by star7th** [comment]
已发布新版解决了问题
