### ISSUE TITLE
Docker方式安装中能否添加windows docker-desktop

### ISSUE THREAD

**Issue by aimei54** [star7th/showdoc#1534]
Windows中的 -v 卷的使用一般具名化即可，数据卷的位置在\\wsl$\docker-desktop-data\version-pack-data\community\docker\volumes\

如果使用 -v /showdoc_html/html:/var/www/html/   文件目录不明晰，即使加如盘符也无法正常使用。
我目前也在研究windows下的docker 如何安装希望得到关注并给予支持。

**Comment by star7th** [comment]
win下请使用这种安装方式 https://www.showdoc.com.cn/help/4087044677189279  不打算研究win下的docker
