### ISSUE TITLE
项目能进行分类吗？

### ISSUE THREAD

**Issue by Colby242222** [star7th/showdoc#1535]
项目列表能否进行自定义分类呢？当所涉及的项目太多的时候，全都平铺在一个页面上，不整洁也不方便查看。
![image](https://user-images.githubusercontent.com/92919109/145317508-a4f48007-76e1-47b6-a38e-560be37a27ed.png)

**Comment by star7th** [comment]
当项目数超过5个的时候才会显示项目分组功能

**Comment by star7th** [comment]
看不到项目分组功能就升级最新版

**Comment by Colby242222** [comment]
好的，谢谢~
