### ISSUE TITLE
runapi建议增加保存家口默认上一次保存分类的功能

### ISSUE THREAD

**Issue by skipify** [star7th/showdoc#1536]
1. 一个项目会包含很多分类，在添加接口的时候选择了一个分类，接口会正常添加到这个分类。但是再添加下一个的时候就又回到了顶级分类。根据局部性原理，做完一个功能会集中增加几个接口的文档，都属于一个分类，频繁点击分类选择不是很优雅建议可以添加接口的时候默认上一次的分类。
2. 建议增加接口搜索功能，接口太多了 找起来太费劲

**Comment by star7th** [comment]
1，你当前左侧栏点开的是哪个目录，默认就新建到哪个目录去。
2，后续看看怎么更新支持

skipify ***@***.***>于2021年12月9日 周四下午6:38写道：

**Comment by star7th** [comment]
目前已经发布新版，支持了接口搜索功能。重启runapi客户端就会自动更新好。
