### ISSUE TITLE
runapi 是否支持url前缀为某个环境变量

### ISSUE THREAD

**Issue by hanxi** [star7th/showdoc#1537]
如果更换了服务器，测试的url都需要重新修改一遍。

**Comment by star7th** [comment]
runapi有管理变量功能，也支持你说的情况。你找找按钮

涵曦 ***@***.***>于2021年12月10日 周五上午11:29写道：

**Comment by hanxi** [comment]
![image](https://user-images.githubusercontent.com/1185757/145522671-e830d790-a9b4-4184-b48c-ded9947a0261.png)
![image](https://user-images.githubusercontent.com/1185757/145522689-9029c567-35f1-408a-b54b-884d4ae50e45.png)
url中如何使用变量呢？

**Comment by star7th** [comment]
你截的这个图，有个帮助说明按钮，看见了吗

**Comment by hanxi** [comment]
谢谢，找到说明了。

**Comment by hanxi** [comment]
建议把说明文档也加入到帮助文档
