### ISSUE TITLE
runapi可以导入swagger.json吗, runapi有导入按钮, 但是点导入后就直接跳到登录页了

### ISSUE THREAD

**Issue by hsk-story** [star7th/showdoc#1538]
在runapi客户端的新建->导入项目下. 选择swagger导入, 选择完json文件导入后就直接跳转了runapi登录页, 也没有错误提示
附上导入json文件
`
{
  "swagger": "2.0",
  "info": {
    "title": "平台",
    "version": "last"
  },
  "basePath": "/",
  "tags": [
    {
      "name": "年卡相关",
      "description": null
    }
  ],
  "schemes": [
    "http"
  ],
  "paths": {
    "/checkVirtualCardCanBeActive": {
      "get": {
        "tags": [
          "相关"
        ],
        "summary": "判断卡是否可激活",
        "description": "",
        "parameters": [
          {
            "name": "virtual_no",
            "in": "query",
            "required": true,
            "description": "卡号",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "properties": {
                "code": {
                  "type": "number"
                },
                "data": {
                  "type": "number",
                  "description": "1可激活0不可激活"
                },
                "msg": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/activeVirtualCard": {
      "post": {
        "tags": [
          "相关"
        ],
        "summary": "激活卡",
        "description": "",
        "consumes": [
          "multipart/form-data"
        ],
        "parameters": [
          {
            "name": "virtual_no",
            "in": "formData",
            "required": true,
            "description": "卡号",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "properties": {
                "code": {
                  "type": "number",
                  "description": "200代表激活成功，其他code代表激活失败"
                },
                "msg": {
                  "type": "string"
                },
                "data": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        }
      }
    }
  }
}
`

**Comment by star7th** [comment]
你从swagger导出版本3的json

**Comment by hsk-story** [comment]
导入swagger3的数据, 就可以生成runapi可编辑的项目吗

**Comment by star7th** [comment]
理论上是的。我觉得你可以直接试一下，有问题再抛出来。
