### ISSUE TITLE
可以给 Arch 打个包吗？亲

### ISSUE THREAD

**Issue by vioulo** [star7th/showdoc#1539]
我远程办公的电脑，硬盘装的 Arch，但是 Linux 版本的装不了。
所以能不能按照流行 Linux 发行版分别打个包呀！
我现在很需要在 Arch 上使用 :thanks

**Comment by star7th** [comment]
showdoc用户里使用Arch系统的估计不超过10个人。不打算在冷门系统上维护多一个版本。其实我一开始甚至连linux版都不打包的。

**Comment by star7th** [comment]
盲猜你说的是runapi客户端。我的回答也是针对runapi客户端

**Comment by vioulo** [comment]
> 盲猜你说的是runapi客户端。我的回答也是针对runapi客户端

那 runapi 有办法我自己来打包吗？

**Comment by star7th** [comment]
没有的

vioulo ***@***.***>于2021年12月14日 周二下午5:57写道：

**Comment by vioulo** [comment]
后面要在家办公了，所以能不能麻烦给 Arch 打个包，哥 🐇

**Comment by star7th** [comment]
你愿意为了浪费他人时间付费吗。为了arch打包我还得专门安装个系统来测试。而且做好后还只是给你一个人用，还占我后续其他人可能再来问我的维护时间。
你都不愿意付出代价（金钱），又为何想别人付出代价（时间精力）。

**Comment by vioulo** [comment]
好吧。如果我情况好点的话，我会付费的。

**Comment by vioulo** [comment]
上次我直接拿 zip 安装失败，也没解压文件查看。前天解压文件才看到提示信息，可以顺利运行了。感谢！
