### ISSUE TITLE
sqlite的数据库文件在哪里啊

### ISSUE THREAD

**Issue by chenyeyuze** [star7th/showdoc#154]
没用过sqlite，我想备份下，但不懂sqlite的数据文件在哪。。
谢谢

**Comment by chenyeyuze** [comment]
好像Sqlite/showdoc.db.php这个文件就相当于是数据库了？

**Comment by star7th** [comment]
https://www.showdoc.cc/help?page_id=16118
![image](https://user-images.githubusercontent.com/2200494/29304289-cc7ebb1a-81c4-11e7-9e63-ad8aa2f41611.png)
