### ISSUE TITLE
使用全局参数提示版本过旧需要v2.9.14当前v2.9.12，但是已经升级成功了。

### ISSUE THREAD

**Issue by Darrenchenn** [star7th/showdoc#1541]
如何解决这个问题，版本信息是存在数据库中吗，在哪个表中，可否直接修改数据库数据。使之生效？

**Comment by star7th** [comment]
会提示你，就就证明了你升级没成功。先确保升级成功。

Darrenchenn ***@***.***>于2021年12月17日 周五上午10:06写道：

**Comment by Darrenchenn** [comment]
使用的脚本升级，docker 使用的latest的标签去拉最新镜像，html目录也正常替换成功了

**Comment by star7th** [comment]
去重新下载官方脚本再升级一遍。另外确保自己没有改过官方的东西，包括映射目录。

Darrenchenn ***@***.***>于2021年12月17日 周五上午10:09写道：

**Comment by Darrenchenn** [comment]
有重新下载脚本升级过，映射目录具体指什么呢？。 目前暂时是没有改动 重新安装也还是存在这个问题。暂时没有定位到问题所在，也是比较疑惑。  谢谢

**Comment by star7th** [comment]
用管理员账号登录管理后台。如果服务器有公网的话会自动检查更新。然后你点更新

Darrenchenn ***@***.***>于2021年12月17日 周五上午10:15写道：

**Comment by zwy66666** [comment]
![企业微信截图_20211229134258](https://user-images.githubusercontent.com/96455554/147631294-2ef973ac-09a3-499f-880e-2bbb04911c3b.png)

**Comment by zwy66666** [comment]
我用管理员账号登录了 ，并没有更新按钮，有没有可能，是这个判断写错了

**Comment by Darrenchenn** [comment]
> 我用管理员账号登录了 ，并没有更新按钮，有没有可能，是这个判断写错了

我在页面上也没找到，但是用脚本成功了。看下脚本那个网址你能不能通。

**Comment by star7th** [comment]
> ![企业微信截图_20211229134258](https://user-images.githubusercontent.com/96455554/147631294-2ef973ac-09a3-499f-880e-2bbb04911c3b.png)

看这个截图提示，你用的版本是2.9.6版本，没有界面上的自动更新按钮。你只能根据文档手动更新 https://www.showdoc.com.cn/help/13732

**Comment by zwy66666** [comment]
> 

不是我今天才更新的啊，而且2.9.1 比 2.9.6要新吗

**Comment by zwy66666** [comment]
嗷我在研究下，用docker删了重装了下似乎没更新掉

**Comment by zwy66666** [comment]
我好了 没执行 curl http://localhost:4999/install/non_interactive.php?lang=zh
