### ISSUE TITLE
runapi中的接口描述，请求参数，返回参数的备注能否多行？

### ISSUE THREAD

**Issue by yanghe1117** [star7th/showdoc#1542]
如标题，runapi中的接口描述，请求参数，返回参数的备注能否多行？

![image](https://user-images.githubusercontent.com/12536366/146670406-2bbd9675-dc0d-4817-86f5-c97e2084462e.png)

**Comment by yanghe1117** [comment]
![image](https://user-images.githubusercontent.com/12536366/146670433-5e52c2d0-a603-463d-848f-9a2aa092d948.png)
现在只能按一行输入，备注比较多的话，特别是返回值的参数，有的描述内容会比较多

**Comment by star7th** [comment]
这个看下怎么处理

**Comment by yanghe1117** [comment]
还有，能否在runapi的接口里加上查看变更记录的功能，就是网页版里文档的详情的信息展示；

**Comment by star7th** [comment]
https://github.com/star7th/showdoc/issues/1322

**Comment by star7th** [comment]
另外不同的问题不要在一个issue里问

**Comment by yanghe1117** [comment]
ok

**Comment by star7th** [comment]
目前已经发布新版，重启runapi客户端就会自动更新。
接口的描述已经支持回车换行。但是参数描述不支持，因为可能换行符会打乱表格展示。你可以用<br>这样的html标签来实现。
