### ISSUE TITLE
带数组的json解析是不是有问题？

### ISSUE THREAD

**Issue by yanghe1117** [star7th/showdoc#1543]
1.带数组的json解析是不是有问题，根据 #1356  ，生成的参数名是不是应该是list.a，现在还是a，见图，不知道我理解的对不对

![image](https://user-images.githubusercontent.com/12536366/146674766-ad621ed2-46a0-4322-90a0-3f2d8fc04348.png)

2.上图的返回示例与参数说明这儿能否也加个json美化？

3.不知道runapi是不是用electron实现的，有个moyu项目接口客户端（类似runapi）https://github.com/trueleaf/moyu， 使用electron实现的，可以实现参数数组嵌套的定义，不知道能不能给大佬做参考，仅作建议，勿怪
![image](https://user-images.githubusercontent.com/12536366/146674987-82268c88-2bdc-485d-bdde-30d6ad9fa8c0.png)

**Comment by star7th** [comment]
1，参数解析为了迎合大部分人的使用习惯，a 前面的list是顶层，所以默认省略list前缀。 不然的话太多参数要写前缀了。只有更深层的才需要。比如说
```
{
  "code": 0,
  "message": "ok",
  "list": [
    {
      "a": [
        {
          "a1": "test"
        }
      ]
    }
  ]
}

```

2，可以考虑后面加个json格式化攻击
3，moyu项目那种关于参数嵌套的方式不是没考虑过，是觉得实现成本高了点，同时没有找到很好的react开源组件做这种嵌套。自己手写拖曳嵌套实在太繁琐麻烦。

**Comment by star7th** [comment]
目前已经发布新版，在返回参数那里增加了一个格式化按钮。重启runapi客户端就会自动更新好。

**Comment by shenadmin** [comment]
我发现如果json 太长的话就不能生成 类似上面的list.a 
`{
  "msg": "登录成功",
  "code": 1,
  "data": {
    "uid": 481,
    "role_id": 4,
    "username": "cg_wyz_a",
    "realname": "采购a",
    "password": "",
    "email": "cg_wyz_a@163.com",
    "mobile": "13544011234",
    "avatar": 0,
    "dept_id": 15,
    "dept_id_for_front": "15",
    "group_id": "",
    "group_id_for_front": "",
    "back_group": "",
    "position_id": 4,
    "position": 0,
    "join_date": "2021-12-31",
    "signup_ip": 0,
    "create_time": "2021-12-31 15:00:53",
    "update_time": "2022-07-05 11:17:01",
    "delete_time": 0,
    "last_login_time": 0,
    "last_login_ip": 0,
    "sort": 100,
    "status": 1,
    "setting": null,
    "permission_group_id": "43,42",
    "permission_group_id_for_front": "",
    "role_name": null
  },
  "jump": null
}`
![image](https://user-images.githubusercontent.com/37206901/177245664-41d7af89-13b5-4978-a7e0-28cc1e51b44a.png)
客户端是最新的版本 runapi_setup_2.0.5

**Comment by star7th** [comment]
> 

@shenadmin 你非得找骂吗。你反馈的问题跟数组json解析有什么关系，为什么要发在这里。另外你反馈的问题你自己描述清楚，你给的示例里根本没出现过数组，却要反馈在数组问题下

**Comment by star7th** [comment]
再有问题，自己新发issue并且描述清楚，提供可重现json例子。
