### ISSUE TITLE
本地部署的showdoc误删项目如何恢复

### ISSUE THREAD

**Issue by dss6666** [star7th/showdoc#1544]

**Comment by star7th** [comment]
删除界面已经提醒过了，删除后无法恢复！ 并且要输入密码确认。

**Comment by bo961386926** [comment]
目前已恢复项目，可通过下载sqlite数据库连接工具恢复

**Comment by star7th** [comment]
@bo961386926 你可以自行留下教程。官方不做数据恢复承诺，因为承诺了就是官方要背责任。实际上这事情太繁琐，我不想纳入官方教程。你如果不留教程的话，请不要留言误导他人。
