### ISSUE TITLE
runapi 中 希望可以在单个api测试中返回响应时长

### ISSUE THREAD

**Issue by piliplaker** [star7th/showdoc#1547]
如题， 如此用户可以大体确认接口性能以及线路情况

**Comment by star7th** [comment]
这个后面优化下

piliplaker ***@***.***>于2021年12月26日 周日上午8:41写道：

**Comment by star7th** [comment]
目前已经发布新版，支持了此功能。重启runapi客户端就会自动更新好。

**Comment by star7th** [comment]
runapi本质是web  html网页包装成的客户端。
目前耗时这块应该做不到区分是线路延迟还是接口处理缓慢。

piliplaker ***@***.***>于2021年12月28日 周二上午1:16写道：

**Comment by star7th** [comment]
如果你上面说的“接口处理缓慢导致”是指runapi自身渲染耗时的话。现在的耗时指标仅仅指的是发起网络请求和返回，不包含runapi自身的ui渲染耗时
