### ISSUE TITLE
保存的问题

### ISSUE THREAD

**Issue by sugarcats** [star7th/showdoc#1548]
ctrl+s 保存后能不能不返回，写代码的时候习惯了，现在写文档有点难受，不自觉就按了

**Comment by star7th** [comment]
请截图说明哪里ctrl +s
是会返回的。如果指的是showdoc编辑页面，那么我印象中这个功能至少三年前就修复了。你拿三年前的版本来反馈问题，这个不好吧

sugarcats ***@***.***> 于2021年12月26日周日 17:09写道：
