### ISSUE TITLE
你的服务器挂了啊， 文档写不了了

### ISSUE THREAD

**Issue by rosstzc** [star7th/showdoc#155]
你的服务器挂了啊， 文档写不了了

**Comment by star7th** [comment]
没发现异常。有没有精确的时间点，同时说下出现了什么现象

**Comment by star7th** [comment]
还有，地址是这个https://www.showdoc.cc/
之前出现过有人把他人部署的开源showdoc当做官网了

**Comment by rosstzc** [comment]
@star7th 具体时间应该就是发那条评论的前几分钟，如果你那边没发现问题，那可能是网络之类的问题吧。。反正昨晚我用有正常了。
