### ISSUE TITLE
v2.9.15 网页端项目分组管理界面bug

### ISSUE THREAD

**Issue by piliplaker** [star7th/showdoc#1551]
如题 ，使用docker进行自搭建，复现步骤如下：

1. 登录后进入主界面
2. 点击”项目分组管理“，此时里面是空列表
3. 点击“新建分组”
4. 在弹窗中，不填组名， 选择任意已有项目，点击确定，可见名为undefined的分组
5. 不返回主界面，对上述分组点击“编辑”，试图编辑分组名，无效

**Comment by star7th** [comment]
这个是小问题。很少人不填写组名。下次发包顺便修复吧，不专门为此又发一个包了。

piliplaker ***@***.***>于2021年12月28日 周二上午1:24写道：

**Comment by star7th** [comment]
已发布新版，解决了此问题
