### ISSUE TITLE
当响应体中返回的json数据中数值过大时，失真问题

### ISSUE THREAD

**Issue by guanchuang1** [star7th/showdoc#1552]
后台数据查询的数据为"orderId":1300015981854322688，而而相应体重展示的数据为"orderId":1300015981854322700，这个问题是怎么回事啊，有办法解决么？

**Comment by star7th** [comment]
因为runapi是32位程序，不支持大整数。有时间再整64位

**Comment by star7th** [comment]
runapi客户端已经改用64位版，可以支持大整数类型。卸载原客户端，然后去下载新的安装即可 https://www.showdoc.com.cn/runapi/30291

**Comment by guanchuang1** [comment]
> runapi客户端已经改用64位版，可以支持大容量类型。卸载原客户端，然后去下载新的安装安装https://www.showdoc.com.cn/runapi/30291
为啥这个64版本的要安装好久，然后还安装不上去啊？？

**Comment by star7th** [comment]
是不是权限问题啊？先关闭。然后，右击安装程序，选择使用管理员身份运行。

**Comment by guanchuang1** [comment]
> 是不是权限问题啊？先关闭。然后，右击安装程序，选择使用管理员身份运行。
![bff588972c204eeba6a44d4cb1c3b9ca](https://user-images.githubusercontent.com/85087751/148151190-dcd006f8-2f55-4a7a-8f23-d70ff3772f7c.jpg)
一直卡在这里，安装好久，然后就是没有后续

**Comment by star7th** [comment]
大概率是权限问题。先试试管理员权限运行

**Comment by guanchuang1** [comment]
> 大概率是权限问题。先试试管理员权限运行

就是用管理员权限运行安装的，然后就一直卡在这里

**Comment by star7th** [comment]
先主动卸载请理，然后再安装呢

**Comment by guanchuang1** [comment]
已经好了，三克油
