### ISSUE TITLE
word文档导出问题

### ISSUE THREAD

**Issue by chaiguifeng007** [star7th/showdoc#1553]
导出的时候，选择word文档格式，没反应。
不论是nginx代理还是直接4999访问都是这样。10次有9次都没反应。
还有就是，在具体页面导出的时候，弹出的页面，是导出全部，不合直觉；应该弹出导出具体页面的对话框。

**Comment by star7th** [comment]
目前这个功能没怎么改过，也久经考验，应该没问题。不清楚你是怎么安装的。另外如果导出的文档太大而你的服务器资源不够，则不好说

**Comment by chaiguifeng007** [comment]
谢谢回复。
我是用的推荐方法，自动安装脚本安装的。我导出的是具体的一个页面，大概8-9页文档。
服务器是2核心4GB+100GB的硬盘。
CPU：个位数占用
内存：不到25%
是刚部署好的。
nginx设置就是官方文档--域名绑定里边，第一段nginx配置。
是我哪里搞错了吗？

**Comment by star7th** [comment]
不知道是不是有特殊字符。尝试一下其他普通的文字项目。

**Comment by chaiguifeng007** [comment]
把浏览器重置一下就行了。应该是某个插件导致的。不是showdoc的问题。
