### ISSUE TITLE
RunApi客户端-导入postman.json丢body参数

### ISSUE THREAD

**Issue by githubpan** [star7th/showdoc#1555]
postman.json

`{
	"info": {
		"_postman_id": "8ff706e9-54d0-49ad-aba3-159aee8a0820",
		"name": "测试导入",
		"schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
	},
	"item": [
		{
			"name": "test-export",
			"request": {
				"method": "POST",
				"header": [],
				"body": {
					"mode": "urlencoded",
					"urlencoded": [
						{
							"key": "checkIn",
							"value": "2022-01-01",
							"type": "text"
						},
						{
							"key": "checkOut",
							"value": "2022-01-02",
							"type": "text"
						},
						{
							"key": "hotelId",
							"value": "123456",
							"type": "text"
						},
						{
							"key": "manNum",
							"value": "1",
							"type": "text"
						},
						{
							"key": "roomNum",
							"value": "1",
							"type": "text"
						}
					]
				},
				"url": {
					"raw": "{{main}}/service_order/font?service=hotel",
					"host": [
						"{{main}}"
					],
					"path": [
						"service_order",
						"font"
					],
					"query": [
						{
							"key": "service",
							"value": "hotel"
						}
					]
				}
			},
			"response": []
		}
	]
}`
![1](https://user-images.githubusercontent.com/8693536/147810994-453c9a7c-1b49-4e62-825e-5af5543a480a.png)
![2](https://user-images.githubusercontent.com/8693536/147810996-177cd63c-3b38-4aa5-bcfc-736c035f25e2.png)

**Comment by star7th** [comment]
这个另外找时间分析下格式

**Comment by githubpan** [comment]
> 这个另外找时间分析下格式

我刚刚瞅了一下

> server/Application/Api/Controller/ImportPostmanController.class.php-> _fromPostmanV2

body的key写死为"formdata"了,把key改成body.mode的值估计可以,可能是版本问题吧,我先本地临时处理下,就是不知道客户端那边是依据哪个字段判断Content-Type的
