### ISSUE TITLE
runapi 使用CryptoJS加密报错

### ISSUE THREAD

**Issue by cqwebwang** [star7th/showdoc#1558]
前执行脚本
`
var md5 = runapi.CryptoJS.MD5('string') ; 
runapi.alert(md5)
`
提示报错内容
`
{"words":[-1268973600,-2065875680,-651641112,1585123105],"sigBytes":16}
`

**Comment by star7th** [comment]
教程少写了东西。现在已经修正。应该是这样：

var md5 = runapi.CryptoJS.MD5('string').toString() ;
var sha256 = runapi.CryptoJS.SHA256('string').toString() ;
runapi.alert(md5)
runapi.alert(sha256)

**Comment by cqwebwang** [comment]
好的。可以关闭了
