### ISSUE TITLE
showdoc v2.9.15 无法保存 类似 varchar(255) sum(TOTALAMONT)  等关键字

### ISSUE THREAD

**Issue by ambrato** [star7th/showdoc#1559]
更新了2.9.15之后， 无法保存带有类似  varchar(255) sum(TOTALAMONT) 等关键字文本

**Comment by star7th** [comment]
我把你说的话复制试了下，亲测没问题。

ambrato ***@***.***> 于2022年1月7日周五 15:40写道：

**Comment by ambrato** [comment]
![image](https://user-images.githubusercontent.com/43380345/148510314-a8288eac-43dd-4864-9c4e-9d3460d72838.png)

我这包含了相应关键字保存的时候会一直转圈， 其他文本没问题

**Comment by star7th** [comment]
看一下网络请求返回是什么

ambrato ***@***.***> 于2022年1月7日周五 15:51写道：

**Comment by ambrato** [comment]
没有任何返回， 服务器都连不上， 我先排查下是不是网络问题吧， 可能请求都没到服务器

**Comment by ambrato** [comment]
由于本地网络安全规则配置导致的问题
