### ISSUE TITLE
图片上传到七牛云有bug

### ISSUE THREAD

**Issue by wong2843** [star7th/showdoc#156]
将七牛的相关参数配置好后，上传图片始终返回null
~~~
{"url":null,"success":1}
~~~

**Comment by wong2843** [comment]
**已解决**。 ` ThinkPHP/Library/Think/Upload/Driver/Qiniu/QiniuStorage.class.php` 文件里里有`public $QINIU_UP_HOST = 'http://upload-z2.qiniu.com';  //华南` 这个地方，七牛云对不同的bucket所属的区是不同的上传地址的，默认是华东

**Comment by star7th** [comment]
动手能力赞一个。
