### ISSUE TITLE
GET 请求 Query里面的参数不会绑定

### ISSUE THREAD

**Issue by 1521783500** [star7th/showdoc#1560]
showdoc 2.9.15
runapi get 请求时,在 Query 填写参数保存后,重新进入 Query 里面的参数会消失

**Comment by star7th** [comment]
你保存了吗，没保存的话，重新进入当然会消失

1521783500 ***@***.***> 于2022年1月7日周五 17:32写道：

**Comment by star7th** [comment]
另外你提供下截图，我不是很清楚你的描述

**Comment by 1521783500** [comment]
在showdoc 2.9.15 之前的版本, 创建的GET 请求没有 Query ,默认是在 Body里面.更新到最新版本后,数据不兼容,导致再次进入,参数没有填充到Query里面

**Comment by 1521783500** [comment]
![image](https://user-images.githubusercontent.com/13377921/148527702-57378b68-4986-4092-b4b0-9b9bc0efe0bb.png)
[图一是保存后的网页截图]

![image](https://user-images.githubusercontent.com/13377921/148527764-b9904c02-1c6d-4d65-a11e-55707ca190dd.png)
[图二是保存后关闭重新进入的截图]
参数并没有绑定到Query下面

**Comment by star7th** [comment]
我明白了。是因为你的url中{{host}}:{{port}}这里的冒号，导致url解析有点问题。你先别保存其他数据，只要不保存它还是原有数据未被破坏。我晚点修复下这个问题。

1521783500 ***@***.***> 于2022年1月7日周五 18:07写道：

**Comment by star7th** [comment]
已经修复此问题。重启runapi客户端即可自动更新

**Comment by star7th** [comment]
如果不能自动更新，请点击左上角的页面-刷新 来更新缓存
