### ISSUE TITLE
markdown表格里的尖括号导出word文档不显示

### ISSUE THREAD

**Issue by chaiguifeng007** [star7th/showdoc#1561]
markdown插入表格，表格里有尖括号，例如“<参数>”，导出word文档时，尖括号和里边的内容都没有了。
也试过用转义字符（&lt;，&gt;）代替，保存后效果一样的，导出word还是没有内容。

**Comment by star7th** [comment]
导出的word不支持这个符号。这是已知问题且无法解决。

chaiguifeng007 ***@***.***>于2022年1月8日 周六上午8:29写道：
