### ISSUE TITLE
服务问题

### ISSUE THREAD

**Issue by zhanghe1995** [star7th/showdoc#1563]
服务器重新启动后，所有的接口文档都没有了，账号也没有了，是一个全新的服务

**Comment by star7th** [comment]
好歹说一下你是用什么方式安装的

**Comment by zhanghe1995** [comment]
用的是自动化安装方式

**Comment by star7th** [comment]
安装好后，showdoc的数据都会存放在 /showdoc_data/html 目录下。你自己去检查下挂载的数据吧。目前这么久来都没听过自动脚本会丢数据的问题。丢数据的往往是用户自己手动安装docker忘记挂载数据的

**Comment by zhanghe1995** [comment]
挂载的数据都是空的   已经看过了   用户的数据应该在这里吧showdoc.db.php， 这个打开看过了user里面只有一个用户

**Comment by star7th** [comment]
那就是你的服务器有东西限制了docker 挂载数据，同时也不产生报错。这导致了docker直接把数据放在容器里了。重启是会恢复的

**Comment by zhanghe1995** [comment]
这个服务我们都用来两年了    之前也重启过服务器   是没有问题的   今天重启了一下就都没有了

**Comment by star7th** [comment]
不是很清楚你的情况。总之，如果数据挂载正常的话，宿主机的/showdoc_data/html是应该有文件的。并且这个文件不会因为重启丢失。因为这是宿主机的文件
