### ISSUE TITLE
npm run dev 启动后 提示403

### ISSUE THREAD

**Issue by itdiy** [star7th/showdoc#1566]

**Comment by star7th** [comment]
执行这个命令，是要二次开发？ 二次开发的话，这里说了也自己做好代理转发到php后端服务 https://www.showdoc.com.cn/help/1385576954326448

假如你不是想二次开发，那么不需要执行这个命令。查看这个教程安装 https://www.showdoc.com.cn/help/13732

**Comment by itdiy** [comment]
感谢大佬恢复，修改了实际访问地址还是不行啊&nbsp; proxyTable: {
&nbsp; &nbsp; &nbsp; &nbsp; '/server/': 'http://showdoc.test:3080'
&nbsp; &nbsp; },





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月11日(星期二) 下午2:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [star7th/showdoc] npm run dev 启动后 提示403 (Issue #1566)





 
执行这个命令，是要二次开发？ 二次开发的话，这里说了也自己做好代理转发到php后端服务 https://www.showdoc.com.cn/help/1385576954326448
 
假如你不是想二次开发，那么不需要执行这个命令。查看这个教程安装 https://www.showdoc.com.cn/help/13732
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by star7th** [comment]
先保证自己使用showdoc是正常的，正常创建项目/新建页面/删除页面。然后再代理
