### ISSUE TITLE
showdoc update后无法连接

### ISSUE THREAD

**Issue by Aoional** [star7th/showdoc#1567]
如题，使用自动脚本更新后无法连接，更新结果：
showdoc-master/web_src/test/unit/setup.js
showdoc-master/web_src/test/unit/specs/
showdoc-master/web_src/test/unit/specs/HelloWorld.spec.js
showdoc
curl: (56) Recv failure: Connection reset by peer
curl: (56) Recv failure: Connection reset by peer
![image](https://user-images.githubusercontent.com/21098384/149058656-3fe8e7a3-7556-494c-abdc-3bf0ce8eb8e2.png)

**Comment by star7th** [comment]
重新下载官方脚本然后再执行update看下  https://www.showdoc.com.cn/help/828455960655160
