### ISSUE TITLE
建议在runapi增加路径参数的UI

### ISSUE THREAD

**Issue by juneszh** [star7th/showdoc#1568]
#1355 
看到以前的关于路径参数讨论, 提到由于不常用所以不添加.
其实当项目接入cdn之后, 这种接口方式会经常用到, 因为大部分cdn平台支持清理query功能, 来增加缓存的命中率.

例如, 当cdn不开启清理query功能时, ?a=1或?b=1由于参数不同, 会导致多次回源请求, 
但很多时候这些query参数并不是我们需要的, 这里面涉及一些小程序平台会自行添加各式各样的参数, 也涉及一些有心人刷量引流或ddos.

因此在实现一些变量值固定的接口时, 通常都会选用路径参数, 如: /api/member/{{platform}}, 这样我们有效的路由可以限定为/api/member/android或/api/member/ios, 以有效忽略不必要的服务器请求和攻击风险

以上是表达路径参数的一些重要性, 当然还有其他的诸如seo方面等的考虑就不额外展开.

但关键问题在于, **路径参数在旧版runapi中使用是可兼容**, 因为只有一个'参数'分类.
在v2.9.15之后就显得额外尴尬, 放在body/query/header都不合适, 稍微沾边的query也会强制在地址添加?xxx, 如上面提到的接口会变成/api/member/{{platform}}?platform=1

因此重新开issues建议增加路径参数UI的需求

**Comment by star7th** [comment]
补充一下，原来的路径变量用法不太规范，已经废弃。
新版的路径变量的使用方式是：
在url里，使用冒号符号链接（跟postman的路径变量用法一致）。当存在路径变量时候，在Query标签页将出现一个列表让你填写路径变量的值（这一点的交互也跟postman类似）

**Comment by juneszh** [comment]
> 补充一下，原来的路径变量用法不太规范，已经废弃。 新版的路径变量的使用方式是： 在url里，使用冒号符号链接（跟postman的路径变量用法一致）。当存在路径变量时候，在Query标签页将出现一个列表让你填写路径变量的值（这一点的交互也跟postman类似）

原来如此, 已测试能实现文档需求了, 谢谢解答.
