### ISSUE TITLE
开启oss对象存储后 文档视频页 全屏不了 

### ISSUE THREAD

**Issue by qq492269704** [star7th/showdoc#1569]
开启oss对象存储后 文档视频页 全屏不了 会强制重新刷新当前页面

**Comment by star7th** [comment]
这个后面优化下。其实跟开启oss无关。主要是原来有个机制，当窗口大小发生变化的时候自动刷新页面以重新适应窗口。可能跟视频全屏有冲突。后面看下怎么做

**Comment by star7th** [comment]
这个问题丢在这里有段时间忘记了。我刚试了下，是能全屏的。我不清楚你为什么不能全屏。如果你还有问题，请在官网重现并且重开此问题。 https://www.showdoc.com.cn/
