### ISSUE TITLE
特殊字符串会被当做图片解析

### ISSUE THREAD

**Issue by forgaoqiang** [star7th/showdoc#157]
我编写文档的时候写MAC地址字符串的时候遇到的

比如下面的字符串，写文档是发现这些字符串无法被当做文本，显示乱码

`a8:1f:66:cf:6b:f0`

**Comment by star7th** [comment]
跟表情的关键字冲突了的缘故。
建议上面使用中文冒号。

**Comment by forgaoqiang** [comment]
(⊙o⊙)… 编辑器特效问题？我通过 添加 <pre> </pre> 标签临时规避了这个问题 但这个的确是问题啊
