### ISSUE TITLE
https://www.showdoc.com.cn/网站里添加了团队成员，但runapi里看不到团队和项目

### ISSUE THREAD

**Issue by fictioner** [star7th/showdoc#1570]
https://www.showdoc.com.cn/
网站里新建了团队、添加了成员、关联了项目，但runapi里项目成员登录后却看不到团队和项目，为何？

**Comment by star7th** [comment]
证明你添加的那个成员跟 他实际登录的不是同一个账户。你可以把这两个账户都发出来对比下

fictioner ***@***.***> 于2022年1月12日周三 11:54写道：

**Comment by star7th** [comment]
如果还有疑问，把关联的项目地址你也发我一下。另外注意，showdoc创建的项目，无法在runapi上看到。只有runapi项目创建的项目才能在runapi上看到

Chen Xing ***@***.***> 于2022年1月12日周三 11:55写道：

**Comment by star7th** [comment]
至于项目不互通的原因，我复制一下给你看吧 

runapi的数据可以生成markdown格式，但不可逆，markdown数据很难再转换回来runapi。所以它无法跟showdoc原有数据互相转换。只是它们可以共用文档浏览/团队协作等功能。同时runapi生成的文档只能在runapi上编辑，不能在showdoc上编辑

**Comment by fictioner** [comment]
谢谢，原来是可以避免的问题。
什么时候可以实现互通呢？
可以改进一下，若是想要设置互通项目，提醒markdown问题即可，不应该因噎废食。

**Comment by star7th** [comment]
本来就有提醒。每个新用户，第一次使用tunapi的时候，会弹窗提醒创建了默认项目，并且看不到showdoc上的项目。

fictioner ***@***.***> 于2022年1月12日周三 15:01写道：

**Comment by fictioner** [comment]
实现互通才好
