### ISSUE TITLE
升级到2.10.x之后版本PHP版本要求php>=7.4

### ISSUE THREAD

**Issue by Arvintian** [star7th/showdoc#1572]
升级之后服务api报错
```
Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0".
```

看代码是引入s3 sdk导致的
![image](https://user-images.githubusercontent.com/17960734/149252177-2f995b6e-0bb5-4dd9-8415-86841d548e92.png)

**Comment by star7th** [comment]
我是按需引入的。如果你不需要用到s3功能，那么，就不用升级版本。如果你用到s3或者云储存功能，就必须升级php版本

**Comment by star7th** [comment]
在不使用一些特殊功能，比如说云储存。单纯写文档的话，php5.3足以。

**Comment by Arvintian** [comment]
我一直跟着升级，有什么bug都cover了，这个版本卡主，就跟不上了

**Comment by Arvintian** [comment]
不用到S3的存储，我先把这个Version检查给注掉了，暂时work

**Comment by star7th** [comment]
不只是s3 .原先的云储存，底层也改为了用s3协议统一上传。用到云储存功能的都要升级

**Comment by Arvintian** [comment]
那有问题了，我测测，我图片都放阿里的oss的

**Comment by Arvintian** [comment]
看涉及到sdk只有上传、删除接口，注掉了版本检查，目前没有影响showdoc功能

**Comment by Arvintian** [comment]
因为s3 sdk引入psr/container 大于1.1.2的问题，这里其实用不到sdk的更多功能，将这个包降级到1.1.1可以继续保持PHP 7.2版本兼容
https://github.com/star7th/showdoc/pull/1574
