### ISSUE TITLE
返回参数说明能否增加参数工具？

### ISSUE THREAD

**Issue by moobing** [star7th/showdoc#1573]
希望增加参数工具，方便复制克隆过来的数据到sublimeText等编辑器里，批量替换外部字段后，再导入，提高文档编写效率
示意图
![image](https://user-images.githubusercontent.com/31676598/149450166-ae796d30-707e-4d89-94a9-2e6a1be541eb.png)
克隆接口后，在编辑大量的字段时，只是外部结构变更，内部字段无需变更，描述也一样时：
1.要么使用快速生成（由于外部字段变更，导致中文描述全部被覆盖，要一个个手写，比较浪费时间）
2.要么自行将外部字段一个个修改（效率低下，重复，耗时长...）
![image](https://user-images.githubusercontent.com/31676598/149450603-1a501ffb-1f25-4a6b-8078-e995c2fed18f.png)

**Comment by star7th** [comment]
那个参数工具只是复制其他接口的参数过来。但实际上，每个接口可能不太一样。复制其他接口的数据过来的参考意义不大。引入参数工具解决不了你说的问题。
你说的问题，有人跟我反映过说建立一个统一的参数描述库。我还没想好怎么做

**Comment by star7th** [comment]
忘记提了。新版的runapi早提供了返回参数的导入导出功能
