### ISSUE TITLE
在编辑器上粘贴图片，报错

### ISSUE THREAD

**Issue by e3600** [star7th/showdoc#1576]
{"error_code":999,"error_message":"HTTP 400 returned for \"https:\/\/showdoc-jingyi.oss-cn-hangzhou.aliyuncs.com\/showdoc_ad76361204a3ca4d8e55651e683a1ba1.png\".\n\nCode:    NotImplemented\nMessage: Aws MultiChunkedEncoding is not supported.\nType:    \nDetail:  \n \u3002\u9519\u8bef\u4f4d\u7f6e\uff1a\/web\/sites\/showdoc\/www\/server\/vendor\/async-aws\/core\/src\/Response.php  406"}

不知什么原因，以前好好的，什么都没动，这之间更新过几个版本，好像没上传过图片，今天才发现的，请问怎么解决

**Comment by star7th** [comment]
你的云储存配置正确吗

**Comment by e3600** [comment]
正确的，我还尝试重新创建key，也不行

**Comment by star7th** [comment]
把你的配置信息发我邮箱，我自己试下 xing7th@gmail.com

**Comment by e3600** [comment]
**key有误**
{"error_code":999,"error_message":"HTTP 403 returned for \"https:\/\/showdoc-jingyi.oss-cn-hangzhou.aliyuncs.com\/showdoc_072fdea0733c45e14ed7ab3293c8bcf7.png\".\n\nCode:    InvalidAccessKeyId\nMessage: The OSS Access Key Id you provided does not exist in our records.\nType:    \nDetail:  \n \u3002\u9519\u8bef\u4f4d\u7f6e\uff1a\/web\/sites\/showdoc\/www\/server\/vendor\/async-aws\/core\/src\/Response.php  406"}

**密钥有误**
{"error_code":999,"error_message":"HTTP 403 returned for \"https:\/\/showdoc-jingyi.oss-cn-hangzhou.aliyuncs.com\/showdoc_1f5566a66115991b4c1185bcba681b45.png\".\n\nCode:    SignatureDoesNotMatch\nMessage: The request signature we calculated does not match the signature you provided. Check your key and signing method.\nType:    \nDetail:  \n \u3002\u9519\u8bef\u4f4d\u7f6e\uff1a\/web\/sites\/showdoc\/www\/server\/vendor\/async-aws\/core\/src\/Response.php  406"}

**都正确**
{"error_code":999,"error_message":"HTTP 400 returned for \"https:\/\/showdoc-jingyi.oss-cn-hangzhou.aliyuncs.com\/showdoc_595bb828105176d14f7838587b506601.png\".\n\nCode:    NotImplemented\nMessage: Aws MultiChunkedEncoding is not supported.\nType:    \nDetail:  \n \u3002\u9519\u8bef\u4f4d\u7f6e\uff1a\/web\/sites\/showdoc\/www\/server\/vendor\/async-aws\/core\/src\/Response.php  406"}

**Comment by e3600** [comment]
信息已发你邮箱

**Comment by e3600** [comment]
我都是在git上直接克隆覆盖的

**Comment by star7th** [comment]
感觉莫名其妙。我可没有在文档上写过让用户克隆，升级要根据文档来操作。https://www.showdoc.com.cn/help/13732

**Comment by star7th** [comment]
另外就是我说你可能是环境问题而非代码问题。如果不懂的话直接用官方自动脚本，别自己折腾

**Comment by e3600** [comment]
好的，感谢，我空了试试

**Comment by e3600** [comment]
你好，经过尝试，小图可以上传，大图都上传不了，如：随便微信快捷截图一个屏幕大小的，就会这样报错。

使用docker安装的也会报错

**Comment by star7th** [comment]
直接使用docker与原生端口4999使用，不要走nginx绑定域名。如果要绑定，请看文档 https://www.showdoc.com.cn/help/7240953917068087  如果你又是因为不看文档乱绑定域名引起的问题，你自己反思去吧，别再问我任何文档上有的东西。

**Comment by star7th** [comment]
不对，我重现这个问题了。这不是域名绑定的问题。
同样的一张5M大小的图片，我能上传到腾讯云，但是上传不到阿里云。不知道阿里云s3是不是对文件大小有限制。

**Comment by star7th** [comment]
实测，同样的一份代码，同样的测试环境，上传同样的5M大小的图片文件，腾讯云能成功。阿里云则失败。我猜测这是阿里云的s3协议兼容问题或者他们对此做限制。这个问题，我就不往下研究了。你可以换腾讯云或者使用服务器本地存储。

**Comment by e3600** [comment]
找到解决方法了。
https://async-aws.com/clients/s3.html
![image](https://user-images.githubusercontent.com/70061074/150132858-2d842769-e979-4a15-b9f9-f80d6269cf98.png)


//文件路径
server/Application/Api/Model/AttachmentModel.class.php
![image](https://user-images.githubusercontent.com/70061074/150132934-170b8043-1f78-427e-a3b2-40ba8def9722.png)

**Comment by star7th** [comment]
赞！ 我找时间测试一下加了这个设置后会不会影响到其他云储存，没问题的话我会更新到主仓库。

**Comment by star7th** [comment]
还有就是之前我之前态度一般般，以为又是一个不读文档的乱提问小白（做开源以来碰到这样的人太多了）。但其实你能找出问题来，证明你还有有些水平的。说实话你如果没找出这个问题的话恐怕我一直都想不到是这个配置项引发的影响。

**Comment by star7th** [comment]
已更新到官方仓库。如果你是用自动脚本安装的，执行`  ./showdoc update  ` 即可更新
