### ISSUE TITLE
安装目录问题

### ISSUE THREAD

**Issue by e3600** [star7th/showdoc#1577]
使用这个方法安装的，https://www.showdoc.com.cn/help/828455960655160

在root目录执行的，安装后，不知安装后的网站文件存在哪了

**Comment by star7th** [comment]
你好好看教程再提问行不行。你再这么自以为是我就要吐槽了。上一个问题是自以为是为直接克隆更新，不看文档。这次的问题又是不看文档直接发问。

**Comment by star7th** [comment]
你发的链接，“安装后说明”那段有写。

**Comment by e3600** [comment]
我在root目录下去执行的，安装后，root目录下确实没有“showdoc_data”，后面通过搜索方式找到，在 ”/var/lib/docker/overlay2/c289f47b3b606366e3d32a9ed53deebea0159b9d68dcbe6021f757f58f38b003/diff/showdoc_data/“ 里

**Comment by e3600** [comment]
不好意思，在root同级目录下找到了
