### ISSUE TITLE
或许可以考虑表格可以作为文件/页面/链接添加到某个项目中？

### ISSUE THREAD

**Issue by Ariczh** [star7th/showdoc#1578]
有时项目需要一个专业的表格，但目前项目无法直接添加表格，表格只能作为单独的项目创建；
一个项目也可能需要多个表格，但现在一个项目只能有一个workbook，用sheet管理相关度不够高的内容稍有点不太合理；
或许可以通过项目组/文件夹功能来实现？毕竟存档项目全放在主页上也有点乱。

**Comment by star7th** [comment]
我想问一下业务使用场景。你打算用表格来存放什么内容，为什么比较需要分级管理

Misakirovsky ***@***.***>于2022年1月19日 周三下午12:31写道：

**Comment by Ariczh** [comment]
1 某个项目涉及采购较多硬件设备，采购和到货进度用markdown的表格稍有点不足，且无法从已有表格导入；
2 还以采购为例，假定某项目前期采购做了一个workbook，里面有几个sheet，后来项目二期又要采购，再加sheet的话区分不明确，但新起项目会更乱；
3 就像一开始说的，存档项目没地方放都堆在首页上不方便查找和管理。

**Comment by star7th** [comment]
这个是通用性办公场景了。showdoc目前还是以IT团队协作为主。目前不太想为这么一个次要场景大改。要改动挺多东西的。而且据我的统计，showdoc用户中使用电子表格的比例总体也偏低，为了电子表格花太多功夫也更不值得了。

Misakirovsky ***@***.***> 于2022年1月19日周三 13:04写道：

**Comment by star7th** [comment]
你可以新建多个电子表格。然后最后起一个总的markdown项目，汇聚起这些电子表格的项目链接。

Chen Xing ***@***.***> 于2022年1月19日周三 13:32写道：

**Comment by Ariczh** [comment]
okay 那目前也没有更好的办法了。不过即便不考虑IT以外团队的需求，我依然觉得项目组/文件夹值得一改，毕竟项目需要归档。

另外提一嘴，表格筛选功能不能正常使用，筛不出来东西，见图。AC两列内容一致。
![image](https://user-images.githubusercontent.com/13712312/150079612-554846b8-c258-4a2f-aa19-30830ca23ab7.png)

**Comment by star7th** [comment]
showdoc使用这个开源电子表格库 https://github.com/myliang/x-spreadsheet  如果它的排序有问题的话，我不好弄。你可以向原作者反馈下。如果对方修复了我就集成进showdoc来

**Comment by Ariczh** [comment]
感谢。
