### ISSUE TITLE
刚才更新了最新版showdoc v2.10.2, 用runapi保存了之后, header样式有问题,如图所示

### ISSUE THREAD

**Issue by chutianjun** [star7th/showdoc#1580]
![image](https://user-images.githubusercontent.com/11752050/150532980-70a61912-bd19-46d9-b42e-61cfa15c5937.png)

**Comment by star7th** [comment]
刚更新了下代码，修复了此问题。

**Comment by mewchen** [comment]
> 刚更新了下代码，修复了此问题。

我今天刚更新的（手动安装升级），好像还是不行……就是  示例值 会输出两列。而且，他的显示顺序是我写的顺序的“逆序”。。。
![Uploading 微信截图_20220214103029.png…]()

**Comment by mewchen** [comment]
> 刚更新了下代码，修复了此问题。

更新后可以了……就是显示顺序和runapi中，变成了逆序……大问题没有~~~
