### ISSUE TITLE
私有项目分享问题

### ISSUE THREAD

**Issue by tw-dean** [star7th/showdoc#1581]
我这边出现了俩问题，烦劳解惑

1. 后续有私有项目关闭密码分享的需求改进嘛？现在是私有项目好像都有一个密码查看的功能，域名暴露到公网后，很容易被 DDOS 攻击~
2. 我看到管理后台页面有针对项目升级的按钮，这种升级功能是咋做到的呢？为啥私有部署的项目可以动态收到这种升级的通知呢~如果我们针对项目进行二次开发（比如关闭密码分享功能的开发）的话，是不是后续就无法通过管理后台对项目进行升级了呀？如果项目所在服务器无法与外网通信，是不是就无法通过这种方式进行升级啦？

**Comment by star7th** [comment]
1，密码设置得复杂一点就没人直到。这个跟ddos攻击没有关系；没密码照样会ddos你。在公网部署怕安全问题可以使用官网托管。
2，进入管理后台的时候，会判断是否能链接公网。能链接的话，会去检查更新。；自己二次开发的话，以后一旦升级，你的开发会被官方新代码覆盖；如果无外网，就不能通过这种方式升级

**Comment by tw-dean** [comment]
> 1，密码设置得复杂一点就没人知道。这个跟ddos攻击没有关系；没密码照样会ddos你。在公网部署怕安全问题可以使用官网托管。 2，进入管理后台的时候，会判断是否能链接公网。能链接的话，会去检查更新。；自己二次开发的话，以后一旦升级，你的开发会被官方新代码覆盖；如果无外网，就不能通过这种方式升级

感谢大佬的回答，解答了我的问题。
提前预祝新年快乐~
