### ISSUE TITLE
集成登录OAuth2设置中userinfo返回字段的问题

### ISSUE THREAD

**Issue by yinshangwei** [star7th/showdoc#1583]
![image](https://user-images.githubusercontent.com/20291587/151287606-519aa000-e29f-4477-91b2-fc77f6ec2ec1.png)
目前发现集成Auth0或者Github，userinfo的返回值中都没有包含"username"字段，只有"name"字段，这样就导致读取不到user信息，无法完成登录。
![image](https://user-images.githubusercontent.com/20291587/151287734-8d7c954d-9622-46c7-9057-80760322221d.png)
![image](https://user-images.githubusercontent.com/20291587/151287752-3bb19f80-d663-4628-9c38-a1ebe5084a69.png)

**Comment by star7th** [comment]
我后面再增加一个填写项，让用户指定用户名字段吧

**Comment by star7th** [comment]
已更新代码，兼容了返回name的情况。不需要额外设置
