### ISSUE TITLE
runApi移动接口到目录

### ISSUE THREAD

**Issue by xcjm820** [star7th/showdoc#1584]
我先建了一个接口，之后建了一个目录，我想把这个接口移动到这个目录下，但是我发现我操作接口和操作目录都做不到这样，难道要在目录下建一个接口，再弄数据过来吗

**Comment by star7th** [comment]
重启客户端也不行吗

xcjm820 ***@***.***> 于2022年1月27日周四 16:43写道：

**Comment by xcjm820** [comment]
重启也不行噢，拖动只能移动排序位置，从这个链接下的windows版本https://www.showdoc.com.cn/runapi/30291

**Comment by star7th** [comment]
暂时不清楚你的情况。你在保存接口的按钮那里，下拉框，选择保存到指定目录。先这么解决。

xcjm820 ***@***.***> 于2022年1月27日周四 17:20写道：

**Comment by xcjm820** [comment]
我的保存按钮那边没有下拉框的操作，是我下的版本不对吗

**Comment by xcjm820** [comment]
![image](https://user-images.githubusercontent.com/29228052/151330662-82ef3d0d-6886-4198-a5e2-68377b339864.png)

**Comment by star7th** [comment]
什么情况，应该有的。你的机器的分辨率多少，好像遮住了

**Comment by xcjm820** [comment]
是您说的问题，外接个屏幕出来了，感谢。我用的是14寸笔记本，分辨率1920*1080

**Comment by xcjm820** [comment]
大佬，升级后的版本，这个功能去掉了吗？
![image](https://github.com/star7th/showdoc/assets/29228052/9ad765c0-2778-432d-801a-81193be3e2e1)

**Comment by star7th** [comment]
> 

新版是去掉这个功能了。后面不知道是否应当加入。
其实可以拖动接口到目录的。方式是，按住 接口 ，然后拖到 目录 的上方，然后重点来了，再向右移动一下，示意让接口成为目录的 子节点 ，就好了

**Comment by xcjm820** [comment]
按照这个操作可以，这操作也太隐蔽了。我是先建了接口，后想归类到目录里，感觉这个功能还是有必要的哈~
