### ISSUE TITLE
建议markdown支持插入html片段功能

### ISSUE THREAD

**Issue by geneedyou** [star7th/showdoc#1585]
建议markdown支持插入html片段功能，这样玩法就灵活了

**Comment by star7th** [comment]
本来就支持。请截图证明为什么不支持

稚澳赵 ***@***.***> 于2022年1月28日周五 13:30写道：

**Comment by geneedyou** [comment]
![image](https://user-images.githubusercontent.com/51157457/151492863-49fef462-eb91-4413-afea-c44647f98314.png)
我看日志说2017年10月关闭了html功能，然后如果是要在哪开开的话可以说下吗

**Comment by star7th** [comment]
本来就支持。请截图证明为什么不支持。你再忽略我的话你自个儿找别人问去

稚澳赵 ***@***.***> 于2022年1月28日周五 13:35写道：

**Comment by star7th** [comment]
把你写的内容截图下

Chen Xing ***@***.***> 于2022年1月28日周五 13:36写道：

**Comment by geneedyou** [comment]
![image](https://user-images.githubusercontent.com/51157457/151493108-57275774-8b14-4b6c-af97-0e0b6e0c270f.png)

重新测试了一下是支持html标签的，之前是不支持iframe标签，我查看代码发现是把此标签禁止了，是我没搞清楚。但是日志并没有提及重新开启的信息。
开源项目确实辛苦但还请心平气和讲话，
