### ISSUE TITLE
LDAP设置失败，如何查看错误日志？

### ISSUE THREAD

**Issue by binsgit** [star7th/showdoc#1586]
官方自动脚本安装 ./showdoc
LDAP设置时说 "Can't bind to LDAP Server"。LDAP 服务使用 Windows 域控制器，同样的设置 GitLab 可用。
官网的文档翻了一遍也没找到日志路径，/var/log/syslog （Debian 系统）看到有一些 showdoc 相关的日志，但并没有提到 LDAP 设置失败的原因。
日志在哪里呢？

**Comment by star7th** [comment]
这个错误提示，估计是网络都链接不通。你先保证服务器ip端口能连。另外注意写的配置不要前后把空格也复制过去了。

Bin S ***@***.***>于2022年2月2日 周三下午4:07写道：

**Comment by binsgit** [comment]
之前确实存在网络不同的问题（局域网，DNS 解析不到，需要修改 /etc/hosts）。我修改了 showdoc 脚本，增加了 --add-host <HOSTNAME>:<IP> 参数，docker 进去已经能够 ping 通 AD 服务器。空格注意到了，绝不会有。但还是不行啊，依旧提示 "Can't bind to LDAP Server"。有没有啥地方能看到 showdoc 的日志啊，到底是因为啥不通？
另外有一个可能是 SSL 证书，毕竟私有域，没有买证书，不过 389 端口应该不用 SSL 的吧？

**Comment by star7th** [comment]
没有记录日志。我觉得这个错误是一开始链接的错误，应该是网络端口不通或者其他原因导致链接不上。还谈不上其他配置的问题。你如果能提供外网可连接场景我试下的话也许我可以看一下

**Comment by binsgit** [comment]
PHP 不是很熟，调试了一下，定位了原因，勉强将就用吧，懒得改代码、提 patch 了，你们酌情修改。

0. 日志可以加，报错的地方：$this->sendError(10011,"Can't bind to LDAP server"); 改成这样：
              if (ldap_get_option($ldap_conn, LDAP_OPT_DIAGNOSTIC_MESSAGE, $extended_error)) {
                    $this->sendError(10011, "Error Binding to LDAP: $extended_error");
                 } else {
                    $this->sendError(10011, "Error Binding to LDAP: No additional information is available.");
                 }

1. 文档里的 nginx 安装，照着官方独立安装的文档没搞定，fastcgi 用 9000 端口？服务器上这个端口根本就没有开放。我用 Debian，应该是一个 socket 文件：unix:/var/run/php/php7.3-fpm.sock

2. 始终连接失败的原因：LDAP 用户的密码里含有特殊字符（&），获取时候需要用 html_entity_decode()，否则没法用，懒得改代码了，干脆改了密码。可能其他字符也不行？懒得调试。

3. 对于 Windows AD，LDAP 设置中"user field"得全用小写，其实应该代码里自己转一下大小写的，懒得改代码了，目前使用的值是：samaccountname

4. 对于 Windows AD，为了不把域内的电脑、不该有权限的人加进去，我做了一个叫 Showdoc的组，只有这个组内的用户允许使用服务，search filter 使用的是：“(&(sAMAccountName=*)(objectClass=user)(objectClass=person)(memberOf=CN=Showdoc,OU=MYOU,DC=example,DC=com))” 【MYOU、example和com自行替换，话说 user 和 person 好像都没啥用，还是组好使】

5. 用户管理界面不带批量操作，一个个删除域里面的机器和调试时候加进来的用户，点得手都快断了

Anyway，这东西做到好用感觉还得继续加油，被乙方逼着硬折腾一下 PHP，唉……

**Comment by star7th** [comment]
赞，我后面根据你的建议来改一下。

Bin S ***@***.***>于2022年2月13日 周日上午5:57写道：
