### ISSUE TITLE
本地部署过一段时间之后无法新增编辑文档和登录

### ISSUE THREAD

**Issue by rogerhesong** [star7th/showdoc#1588]
使用官网docker部署showdoc有稳定运行几个月，浏览器记录的登录账户现在突然无法新增和编辑，新增提示request fail，编辑提示成功但文档内容没有改变，使用其他浏览器登录账户和换其他电脑登录账户都会提示尚未登录，然后立马又重置页面到登录页

**Comment by star7th** [comment]
先尝试更新到新版看看。历史短暂出现出一些有缺陷的版本。

rogerhesong ***@***.***>于2022年2月8日 周二下午3:28写道：
