### ISSUE TITLE
新建项目弹窗提示空白

### ISSUE THREAD

**Issue by Jona-lee** [star7th/showdoc#1589]
如果不填写项目名称，弹窗是个空白
![image](https://user-images.githubusercontent.com/3770638/152955446-e331feae-324f-46f5-8768-00313086cd25.png)

**Comment by star7th** [comment]
小问题。有空判断空值完善下。

Jona-lee ***@***.***>于2022年2月8日 周二下午5:17写道：

**Comment by star7th** [comment]
已更新
