### ISSUE TITLE
window环境下无法用程序注解自动生成文档

### ISSUE THREAD

**Issue by Daemon8828** [star7th/showdoc#1591]
新建的私密项目，使用了这个项目的中api_key和api_token，api_key="be904ce571dc1c9146214f61761188bd1961189848" 			#api_key
api_token="93a760a75d4d1ac76c7f5050efc2825e1355238351" 	#api_token
#url="https://www.showdoc.com.cn/server/?s=/api/open/fromComments" #同步到的url。使用www.showdoc.com.cn的不需要修改，使用私有版的请修改
url="http://xx.com/server/index.php?s=/api/open/fromComments"

最后双击showdoc_api.sh 不能生成文档，哪里有问题？

**Comment by star7th** [comment]
把url和错误提示贴出来

**Comment by star7th** [comment]
我比较怀疑你写错url了。我再次把说明里的文字复述一次，使用私有版的请修改
url="http://xx.com/server/index.php?s=/api/open/fromComments"  其中xx.com是你的私有showdoc地址。

**Comment by Daemon8828** [comment]
url="http://xx.com/server/index.php?s=/api/open/fromComments"

正在扫描 E:/IdeaProjects/java-study-master/java-study-master/src/main/java/com/pancm/showdoc/CalculateTest.java
 E:/IdeaProjects/java-study-master/java-study-master/src/main/java/com/pancm/showdoc/CalculateTest.java 扫描到内容 , 正在生成文档
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1589    0     0  100  1589      0  51258 --:--:-- --:--:-- --:--:-- 51258
curl: (56) Recv failure: Connection was reset
正在扫描 E:/IdeaProjects/java-study-master/java-study-master/src/main/java/com/pancm/showdoc/api_demo.test
 E:/IdeaProjects/java-study-master/java-study-master/src/main/java/com/pancm/showdoc/api_demo.test 扫描到内容 , 正在生成文档
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2645    0     0  100  2645      0  14297 --:--:-- --:--:-- --:--:-- 14220
curl: (56) Recv failure: Connection was reset
正在扫描 E:/IdeaProjects/java-study-master/java-study-master/src/main/java/com/pancm/showdoc/showdoc_api.sh

**Comment by star7th** [comment]
我再次把说明里的文字复述一次，使用私有版的请修改
url="http://xx.com/server/index.php?s=/api/open/fromComments" 其中xx.com是你的私有showdoc地址。 其中xx.com是你的私有showdoc地址。 其中xx.com是你的私有showdoc地址。 其中xx.com是你的私有showdoc地址。 其中xx.com是你的私有showdoc地址。

**Comment by star7th** [comment]
你直接浏览器访问你声称的这个url看能访问不。

**Comment by Daemon8828** [comment]
已经解决了
