### ISSUE TITLE
使用docker安装能否使用非root用户？

### ISSUE THREAD

**Issue by zllfdd** [star7th/showdoc#1594]
[Docker方式安装](https://www.showdoc.com.cn/help/65610)
中的说明：

> 新建存放showdoc数据的目录
> mkdir -p /showdoc_data/html
> chmod  -R 777 /showdoc_data
> 如果你是想把数据挂载到其他目录，比如说/data1，那么，可以在/data1目录下新建一个showdoc_data/目录，
> 然后在根目录的新建一个软链接/showdoc_data到/data1/showdoc_data
> 这样既能保持跟官方教程推荐的路径一致，又能达到自定义存储的目的.
> 
> 启动showdoc容器
> docker run -d --name showdoc --user=root --privileged=true -p 4999:80 \
> -v /showdoc_data/html:/var/www/html/ star7th/showdoc

使用root用户运行，并且目录权限为777，存在一定安全隐患。
能否使用其它用户运行？程序默认创建的目录权限也是777，能否改进？

**Comment by star7th** [comment]
我这样是为了兼容最大的情况，避免不同的服务器设置引出的权限问题。假如你自己有办法保证挂载的目录能被docker进程读写到也是可以的。这个需要你自己探索你服务器上的权限配置情况。

zll ***@***.***> 于2022年2月10日周四 22:03写道：

**Comment by star7th** [comment]
我个人觉得，在docker里面运行了，那么对宿主机的影响很有效，权限777并没有太明显的服务器被入侵的风险。

Chen Xing ***@***.***> 于2022年2月10日周四 22:06写道：

**Comment by star7th** [comment]
我个人觉得，在docker里面运行了，那么对宿主机的影响很有限，权限777并没有太明显的服务器被入侵的风险。

**Comment by zllfdd** [comment]
感谢回复。
我以www-data身份创建了目录showdoc_data/html目录
并以下列命令运行：
docker run -d --name showdoc --user=www-data --privileged=true -p 4999:80 -v /showdoc_data/html:/var/www/html/ star7th/showdoc
程序创建的目录所有者仍为root。
我对docker不熟悉，这是否是docker的问题？
