### ISSUE TITLE
showdoc使用oauth2集成之后，如何登陆runapi

### ISSUE THREAD

**Issue by bluesky4485** [star7th/showdoc#1595]
showdoc基础gitlab的oAuth2之后，账号体系都在gitlab中，使用runapi的时候，只能通过showdoc的账号密码进行登陆，没法使用gitlab登陆，这块要怎么处理？

**Comment by bluesky4485** [comment]
runapi登陆showdoc的时候，可否也显示一下 showdoc中的使用oauth2登陆的按钮？加个配置项之类的？

**Comment by star7th** [comment]
runapi未能支持使用oauth2登录。如果需要，可以自己去管理后台重置那个用户的密码，然后使用用户名密码登录

bluesky4485 ***@***.***> 于2022年2月12日周六 14:59写道：

**Comment by bluesky4485** [comment]
@star7th z这样就违背了使用OAuth2登陆的初衷了。我gitlab中账号停用了，showdoc中还能使用账号密码进行登陆，会增加账号维护工作量啊

**Comment by star7th** [comment]
runapi是一个比较独立的客户端，比较难实现oauth登录。目前只能支持账号密码登录。
