### ISSUE TITLE
showdoc移动端中没有使用OAuth2登陆的按钮

### ISSUE THREAD

**Issue by bluesky4485** [star7th/showdoc#1596]
关于showdoc的客户端，看了下 在配置了OAuth2之后，windows客户端上面是能正常显示本地部署的showdoc界面中的使用gitlab登陆的按钮的，能正常，但是移动端 安卓和ios中设置了showdoc地址后，没有出现使用gitlab登陆的按钮。

**Comment by star7th** [comment]
移动端不支持oauth2登录。需要的话，可以去管理后台重置用户密码，然后使用账号密码登录。

bluesky4485 ***@***.***> 于2022年2月12日周六 17:33写道：
