### ISSUE TITLE
带有图片的文档导出word后图片不显示

### ISSUE THREAD

**Issue by BringDragon** [star7th/showdoc#1597]
使用小皮运行，导出带有图片的文档图片不显示，格式混乱

**Comment by star7th** [comment]
这个教程离，sqlite相关的扩展开启了吗 https://www.showdoc.com.cn/help/4087044677189279

**Comment by BringDragon** [comment]
是的   ”php-pdo-sqlite”和”php-sqlite3”扩展 都开启了
![image](https://user-images.githubusercontent.com/57335691/153827972-dcc22004-3124-4e9a-a8e3-14c00599eeb3.png)
<img width="685" alt="image" src="https://user-images.githubusercontent.com/57335691/153829472-859a3c5c-0fbe-4877-8a5c-3a8e612f2b83.png">

![image](https://user-images.githubusercontent.com/57335691/153829391-3f6bd384-2b82-4b0c-9864-65cdb72c343d.png)

**Comment by star7th** [comment]
哦，我没看题目。显示不了是正常的。因为导出的图片只是一个url 。url访问得到就是访问得到，访问不到就是访问不了。建议后台启用云储存，这样各个地方都能访问到

**Comment by star7th** [comment]
像你说的，用xp运行。那应该是安装在你本机了。这种情况下，就别想别人能访问得到了

**Comment by BringDragon** [comment]
了解  因为现在是在本机测试 准备部署在服务器上呢  感谢
