### ISSUE TITLE
提示缺少 `team_member_group_id` 字段

### ISSUE THREAD

**Issue by qfsz168** [star7th/showdoc#1598]
升级到2.10.2之后，点击项目设置按钮，提示缺少 `team_member_group_id` 字段。
![image](https://user-images.githubusercontent.com/22514753/153997859-5c977194-a73a-42f3-9526-6ae191a7ad49.png)

升级前的版本不记得了；
升级方法是全新手动安装后，用原来的 Sqlite/showdoc.db.php、Public/Uploads/* 替换；

**Comment by star7th** [comment]
旧版大概是多久之前的版本？
是否确定能正常创建新文档？

**Comment by qfsz168** [comment]
> 旧版大概是多久之前的版本？ 是否确定能正常创建新文档？

旧版应该是2021年下半年的版本。创建文档也报错：
![image](https://user-images.githubusercontent.com/22514753/154001094-7b5ac19a-402f-4741-a3ba-402fea797d4e.png)

**Comment by qfsz168** [comment]
> 旧版大概是多久之前的版本？ 是否确定能正常创建新文档？

中间某些版本更新过数据库结构吧？是不是执行一下相应的sql脚本就能解决了

**Comment by star7th** [comment]
所以你不要误导人啊。上面又说“文档创建浏览正常” ，把我弄得一脸莫名其妙。
现在明显的问题是数据库没有写入权限，导致无法创建数据无法执行升级。

**Comment by star7th** [comment]
程序自动会执行升级，不需要手动执行sql脚本

**Comment by qfsz168** [comment]
> 所以你不要误导人啊。上面又说“文档创建浏览正常” ，把我弄得一脸莫名其妙。 现在明显的问题是数据库没有写入权限，导致无法创建数据无法执行升级。

真的不好意思，表达有误。我确认一下可写权限，再试试。

**Comment by qfsz168** [comment]
是写入权限的问题，赋了正确权限后已经正常了。添麻烦啦，真心抱歉！
