### ISSUE TITLE
历史记录太多，能否在操作栏加个删除的功能

### ISSUE THREAD

**Issue by CinderellaCiCi** [star7th/showdoc#16]
RT。。
请原谅强迫症。。

可以通过合理的权限限制（比如项目创建者才有权限

测试了好多内容，一股脑去清数据库了。

**Comment by star7th** [comment]
页面历史最多显示10条而已，不多

**Comment by star7th** [comment]
我说的是单页面历史最多10条

**Comment by CinderellaCiCi** [comment]
那之前的呢？是清空掉了还是没显示？

**Comment by star7th** [comment]
没显示。至于数据库，那张历史表本来是存放历史的，有冗余数据很正常。一般用户不用管数据库，那张表记录不会多到哪里去，多了也不会影响访问速度。而且也防止有人恶意删除页面后，并恶意覆盖历史。只要历史不被覆盖，数据被删了自己还是能通过历史数据库找回来
