### ISSUE TITLE
https端口转发，markdown直接截图后ctrl+v粘贴图片不能显示

### ISSUE THREAD

**Issue by xiaodongzhang1025** [star7th/showdoc#1601]
先基于内网做了80端口的showdoc安装，markdown粘贴图片显示正常。
但是在外网做了https映射到内网端口后，基于外网地址https访问时，markdown粘贴图片不能显示。
猜测应该是图片url加密问题？

**Comment by star7th** [comment]
管理后台可以填写网站外部访问url 。填写这个，上传的图片前缀就用设置值
