### ISSUE TITLE
两个小功能点，不知道是否再大佬的产品路线里呢？

### ISSUE THREAD

**Issue by lotustalk** [star7th/showdoc#1602]
1、手机app端可以考虑增加附件上传功能，这个挺常用的

2、页面上是否可以考虑支持txt、word之类的批量导入生成页面文章呢？因为存在很多旧文档

感谢

**Comment by star7th** [comment]
1，手机端使用率不是很高，因为showdoc主打IT协作场景，大部分人是PC端。可能不会花太多精力完善手机端。如果有更多用户反馈这个需求，就再完善。
2，txt、word之类要批量转成markdown文档不容易，可能不花无谓精力过度尝试。如果你有什么好的开源组件可以实现这个功能可以推荐下

lotustalk ***@***.***> 于2022年2月17日周四 14:19写道：

**Comment by lotustalk** [comment]
感谢大佬的回复，批量不行就算了，刚试用了下，手机端是否可以加个搜索功能啊。。网页和PC端都有，只要有个搜索基本上就可以用啦。

**Comment by star7th** [comment]
手机端使用率不是很高，因为showdoc主打IT协作场景，大部分人是PC端。可能不会花太多精力完善手机端。如果有更多用户反馈这个需求，就再完善。

lotustalk ***@***.***> 于2022年2月17日周四 15:58写道：
