### ISSUE TITLE
用命令行改sqlite数据库的时候报错Error: no such table: page

### ISSUE THREAD

**Issue by chuqingya** [star7th/showdoc#1603]
![image](https://user-images.githubusercontent.com/99868155/154432303-12bf0641-d4f2-4171-aaef-b28132b560bc.png)

**Comment by chuqingya** [comment]
按照官方文档迁移服务器里面的命令改的,还是报这个错
![image](https://user-images.githubusercontent.com/99868155/154432475-cfbdf81e-2088-48e3-b5ba-d16e374467f7.png)

**Comment by star7th** [comment]
sqlite3是一个命令，后面要加参数执行数据库文件路径和名字。去网络搜索下这个命令的用法
