### ISSUE TITLE
runapi 客户端必须要联网，是为了什么

### ISSUE THREAD

**Issue by shaonianlang-ooo** [star7th/showdoc#1604]

**Comment by star7th** [comment]
因为做纯离线版要付出额外开发精力。所以只支持联网版，不用花太多精力设计本地存储和同步一致性问题。

shaonianlang-ooo ***@***.***>于2022年2月19日 周六下午2:28写道：

**Comment by shaonianlang-ooo** [comment]
我在本地搭建了一套showdoc 服务端，连接本地的数据，还需要联网吗？联网是将项目API上传互联网吗？

**Comment by star7th** [comment]
showdoc程序可以离线使用。runapi需要联网。联网只是加载runapi程序本身服务，不会把你的私密数据上传到公网，是生成到私有showdoc

shaonianlang-ooo ***@***.***>于2022年2月19日 周六下午2:35写道：

**Comment by shaonianlang-ooo** [comment]
加载runapi程序本身服务，是为了升级？

**Comment by star7th** [comment]
runapi就是个打包成客户端的网站。就这么简单。网站就是要联网的。

shaonianlang-ooo ***@***.***>于2022年2月19日 周六下午2:40写道：

**Comment by zzkkss** [comment]
非常感谢作者。今天遇到了一个问题，可能是showdoc的网站受到了攻击，导致网页打开非常慢，这种情况在刚才9点以后恢复了。
但是runapi依旧无法加载。

我遇到的问题是，runapi打不开的情况下，虽然我可以打开私有网站进行查看文档，但是确无法编辑。

提示“runapi项目请在runapi客户端编辑”。

所以，如果有可能，还是把runapi做成离线吧。

如果是用electron写的客户端的话，其实也可以考虑把这部分需要下载的页面内容也做到服务器端。

最后，非常感谢作者，作为一个自由职业的码农，这个工具让我省了非常多的精力。

**Comment by star7th** [comment]
> 非常感谢作者。今天遇到了一个问题，可能是showdoc的网站受到了攻击，导致网页打开非常慢，这种情况在刚才9点以后恢复了。 但是runapi依旧无法加载。
> 
> 我遇到的问题是，runapi打不开的情况下，虽然我可以打开私有网站进行查看文档，但是确无法编辑。
> 
> 提示“runapi项目请在runapi客户端编辑”。
> 
> 所以，如果有可能，还是把runapi做成离线吧。
> 
> 如果是用electron写的客户端的话，其实也可以考虑把这部分需要下载的页面内容也做到服务器端。
> 
> 最后，非常感谢作者，作为一个自由职业的码农，这个工具让我省了非常多的精力。

还有就是，对于runapi无法加载的问题，你可以尝试点击左上角的  窗口——刷新页面以更新缓存。我需要看一下日志是不是曾挂过。毕竟我打开发现是好的，同时也没有其他人反馈挂了。

**Comment by star7th** [comment]
现在win版runapi已经支持离线内网使用。到这个页面重新下载安装 https://www.showdoc.com.cn/runapi/30291
