### ISSUE TITLE
导入功能和右上角设置功能异常

### ISSUE THREAD

**Issue by chenliang2012** [star7th/showdoc#1606]
![image](https://user-images.githubusercontent.com/52647642/155092141-6a325532-e34a-4871-90a8-63e836bde212.png)
1. 进入右上角设置时会弹出上图中的异常
2. 导入文档功能选择excel和word文件后没有生成对应的页面

**Comment by star7th** [comment]
1，把错误信息网络搜索一下就知道少了什么扩展。你如果不懂安装php扩展，请使用官方自动脚本或者docker安装。
2，showdoc不支持excel和word文件，你可以好好看导入文档的对话框的文字说明

**Comment by chenliang2012** [comment]
OK，第一次用php弄，非常感谢
