### ISSUE TITLE
"保存" 按钮有时不会响应

### ISSUE THREAD

**Issue by xiehongxin** [star7th/showdoc#161]
自己部署了一个showdoc,但是有时候点击 “保存” 按钮会没响应，文章也就无法保存，这是怎么回事？

**Comment by star7th** [comment]
建议先看下浏览器的网络请求看看是否有什么错误提示信息，就这样我也无法判断

**Comment by xiehongxin** [comment]
好的

**Comment by Jaychen007** [comment]
Failed to load resource: net::ERR_CONNECTION_RESET   /index.php?s=home/page/save 
![image](https://user-images.githubusercontent.com/16368002/30572791-698bdc62-9d22-11e7-820e-1112887813b1.png)

**Comment by star7th** [comment]
要再具体一些，点击这个请求，看它返回什么错误提示

**Comment by Jaychen007** [comment]
编辑完，点击保存，没有反应。。看console 出现这错误提示了。

**Comment by star7th** [comment]
切换到网络，然后点击出错的那个请求，再点击查看返回内容

**Comment by Jaychen007** [comment]
那个错误信息要等很久才会出现。。。

**Comment by Jaychen007** [comment]
![image](https://user-images.githubusercontent.com/16368002/30573013-f59cf9e2-9d23-11e7-8b93-432712427387.png)

**Comment by star7th** [comment]
再切换到你截图的preview选项卡

**Comment by Jaychen007** [comment]
fail to load response data

**Comment by star7th** [comment]
什么时候下载的showdoc版本

**Comment by star7th** [comment]
另外你存在的数据很多吗，看看代码文件夹有多大了

**Comment by Jaychen007** [comment]
好的好的，我看看先啊，我这次要存的数据挺多的，我先改一下服务器的一些参数试试，谢谢了。
