### ISSUE TITLE
Can I import the Yapi interface into showdoc？

### ISSUE THREAD

**Issue by 18211927120** [star7th/showdoc#1610]
Can I import the Yapi interface into showdoc

**Comment by star7th** [comment]
No. You can try to export the format of postman or swagger, and then try to import showdoc

**Comment by 18211927120** [comment]
I tried not to use swagger. Showdoc only supports swagger3






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月25日(星期五) 中午1:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [star7th/showdoc] Can I import the Yapi interface into showdoc？ (Issue #1610)






number 你可以尝试导出 postman 或者 swagger 的格式，然后尝试导入 show doc

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
使用 GitHub Mobile 随时随地发送分流通知IOS 系统或机器人. 
您收到这个消息是因为您编写了这个线程。留言 ID ***@***.***与&gt;

**Comment by star7th** [comment]
You can find some tools to convert swagger2 to swagger3. This is a legacy of Yapi itself. It has stopped maintenance and does not support swagger3. So you need extra tools to help.

**Comment by 18211927120** [comment]
ok think you发自我的华为手机-------- 原始邮件 --------发件人： star7th ***@***.***>日期： 2022年2月25日周五 13:35收件人： star7th/showdoc ***@***.***>抄送： 18211927120 ***@***.***>, Author ***@***.***>主    题： Re: [star7th/showdoc] Can I import the Yapi interface into showdoc？ (Issue #1610)
You can find some tools to convert swagger2 to swagger3. This is a legacy of Yapi itself. It has stopped maintenance and does not support swagger3. So you need extra tools to help.

**Comment by lifang218c** [comment]
find some tools to convert swagger2 to swagger3. 
i can not find it. can anyone help me .thanks very much~
