### ISSUE TITLE
runapi客户端请求失败没有任何提示 能添加错误提示么

### ISSUE THREAD

**Issue by ZhangTianyi-1998** [star7th/showdoc#1611]
![image](https://user-images.githubusercontent.com/37682379/155658896-c946a119-94be-4718-8d1e-fb0b2257ee02.png)

**Comment by star7th** [comment]
应该是直接引发了程序逻辑导致执行不了，弹不了提示框。你的环境变量设置成啥？是合法url吗？浏览器中能访问吗

**Comment by ZhangTianyi-1998** [comment]
是合法的url 浏览器可以访问    状态码502 404的时候就显示不出来 也没有提示

**Comment by star7th** [comment]
你试着不用环境变量，直接写url看行不行？我怀疑你变量配错了，比如带了空格之类的

ZhangTianti ***@***.***> 于2022年2月25日周五 17:32写道：
