### ISSUE TITLE
项目分组

### ISSUE THREAD

**Issue by Ljt992** [star7th/showdoc#1612]
一个docker安装的2.10.2 有项目分组，一个手动php安装2.20.3没有项目分组管理了
![image](https://user-images.githubusercontent.com/71000363/155685801-701d0df4-2146-4a8b-960d-bb4f28740f72.png)
![image](https://user-images.githubusercontent.com/71000363/155685955-1522878e-60c5-4d6d-abe4-92e7db6cf878.png)

**Comment by star7th** [comment]
项目数超过5个才会出现分组功能

LIjt ***@***.***> 于2022年2月25日周五 16:59写道：

**Comment by Ljt992** [comment]
谢谢
