### ISSUE TITLE
上传7z压缩文件失败

### ISSUE THREAD

**Issue by aohun** [star7th/showdoc#1613]
点上传后过一段时间刷新页面，但文件库中并无次压缩包。
请问是限制格式或者文件大小了吗？
php安装

**Comment by star7th** [comment]
使用php安装的话，上传文件的大小是由你安装的配置决定的。包括php配置和nginx配置。

aohun ***@***.***> 于2022年2月28日周一 11:18写道：

**Comment by star7th** [comment]
如果是使用官方自动脚本或者docker镜像，不绑定域名，直接使用docker的4999端口，是可以上传几百M的文件的。至于你手动安装的是情况，就要你自己去看了

Chen Xing ***@***.***> 于2022年2月28日周一 11:21写道：
