### ISSUE TITLE
如何修改用户的初始模板文件？

### ISSUE THREAD

**Issue by linmiaoyan** [star7th/showdoc#1615]
我在本地的php环境中部署了showdoc，现想修改用户的初始模板文件，但添加新文件后未生效，我应该如何修改？

模板文件路径 phpstudy_pro/WWW/Public/SampleZip
该目录下的文件包括teamdoc.zip、datavasedoc等，我导出了自己的文档并上传至该目录，但新用户注册时仍只有原模板内容

**Comment by star7th** [comment]
二次开发文档  https://www.showdoc.com.cn/help/1385576954326448

**Comment by star7th** [comment]
另外，理论上你导出并覆盖同名目录，应该是可以的。你确保自己的zip文件是ok的，自己导入试下看是否正常
