### ISSUE TITLE
code模块中的 &amp;被转换成 &

### ISSUE THREAD

**Issue by Ansen** [star7th/showdoc#1617]
输入的原文及预览
![1](https://user-images.githubusercontent.com/676412/156123474-a2cda219-d7a9-47aa-bada-603d5f187fa5.png)
保存后的结果，此时已经被转换成 &了
![2](https://user-images.githubusercontent.com/676412/156123520-5f948ae1-c7be-4178-a181-b33709291b07.png)
再次编辑，发现原文也被自动转换了
![3](https://user-images.githubusercontent.com/676412/156123590-23f904a5-8757-4a9b-90e8-0a43f8b6daea.png)

给出图片中的代码
`  <property>
    <name>javax.jdo.option.ConnectionURL</name>
    <value>jdbc:mysql://hadoop-10:3306/hive?createDatabaseIfNotExist=true&amp;autoReconnect=true&amp;autoReconnectForPools=true</value>
    <description>
      JDBC connect string for a JDBC metastore.
      To use SSL to encrypt/authenticate the connection, provide database-specific SSL flag in the connection URL.
      For example, jdbc:postgresql://myhost/db?ssl=true for postgres database.
    </description>
  </property>
`

因为在hive的配置文件中，不能直接使用`&`，得用转义字符`&amp;`替代

附上 showdoc官网的测试页面 https://www.showdoc.com.cn/p/fb9a8f352db032d0642b67be08e09f6f

**Comment by star7th** [comment]
我思考了下，你说的这个问题应该无解。因为对文档呈现来说，就是需要反转义的。

**Comment by Ansen** [comment]
> 我思考了下，你说的这个问题应该无解。因为对文档呈现来说，就是需要反转义的。

代码块里面应该要原样输出才对

**Comment by star7th** [comment]
我明白你意思。但是由于一些安全问题，引入了一些额外的转义规则。在这种规则之下要额外写正则才能解决你说的问题。我觉得太麻烦了，所以倾向于不解决。另外关于xml，导出word的时候也有问题。不打算在为支持这种特殊问题上浪费太多时间

**Comment by Ansen** [comment]
> 

问题确实比较小众，用了几年才遇到一回，目前我通过在转义符号里面加个空格的解决，然后在旁边定个说明
