### ISSUE TITLE
自动升级后，重启了docker数据全部丢失

### ISSUE THREAD

**Issue by xy136633** [star7th/showdoc#1619]
执行./showdoc update自动升级后，重启了docker数据全部丢失，再启动showdoc，数据全部丢失

**Comment by star7th** [comment]
目录showdoc_data/ 下有类似html_bak_xxxx的目录。将它重命名为html ，重启docker，便可以恢复备份。
恢复备份后，重新下载官方脚本再执行升级命令看看。再不行的话我不清楚了，也许你的服务器有进程限制了docker服务写文件。
