### ISSUE TITLE
runapi post body json 生成字段说明的问题

### ISSUE THREAD

**Issue by zywayh** [star7th/showdoc#1620]

**Comment by zywayh** [comment]
{
  "id": "xxx",
  "name": "xx",
  "list": [
    {
      "id": "xxx",
      "name": "xxx",
    }
  ]
}
这种结构的json，生成字段说明只有一个id和name，
正确的应该是
id
name
list.id
list.name

**Comment by zywayh** [comment]
post请求的body本身就对应这负责的请求结构，而且包含关系字段重复率很高，希望能优化一下这个

**Comment by star7th** [comment]
这是已经知晓的问题，并且不打算改。我觉得更多是你的接口返回格式不尊重主流规范。
主流规范里，是类似这样的结构：

{
  "error_code": 0,
  "data": [
    {
      "id": "xxx",
      "name": "xx",
      "list": [
        {
          "id": "xxx",
          "name": "xxx"
        }
      ]
    }
  ]
}

其中，data里的才是真正的内容。为了避免出现字段名为data.id 的情形，runapi默认不显示第一层的前缀。即不显示data。
回到你说的问题，你的第一层是list。runapi会默认隐藏第一层。

**Comment by star7th** [comment]
第一层一般都默认用来展示错误码或者业务码之类的信息。

**Comment by zywayh** [comment]
我说的是请求参数，不是相应参数
是post的请求体

**Comment by star7th** [comment]
哎，不对。你说的是请求body的，不是返回参数。我理解错了。

**Comment by star7th** [comment]
我复用了返回参数的生成代码。看来逻辑不完全一样，可能不能完全复用，我看下怎么处理吧

**Comment by zywayh** [comment]
感谢大佬，期待您的成果

**Comment by star7th** [comment]
已修复。重启runapi客户端便会自动更新完毕。如果无法自动更新，可尝试点击runapi客户端左上角的“窗口”--“刷新页面”以更新缓存。

**Comment by zywayh** [comment]
收到，感谢大佬

**Comment by zywayh** [comment]
已验证，已修复，再次感谢大佬
