### ISSUE TITLE
Showdoc 安卓端登录后显示空白&本地安装过程出现Cannot acquire reference to $GLOBALS（PHP8.1)

### ISSUE THREAD

**Issue by wushuang5112** [star7th/showdoc#1621]
Hi ShowDoc Teams:
      你好，我本想将Showdoc用来写接口及自己Blog用，按官方安装教程，我遇到了两个问题，希望你解答一下.
      问题1、我按照官方文档构建完showdoc环境之后，继而下载了它的安卓客户端，现在的问题是我通过APP登录到自己私有的showdoc账号，能在安卓APP上创建项目，但APP端无法显示任何的东西，显示空白。手机型号: 华为荣耀30Pro
![安卓APP空白图](https://user-images.githubusercontent.com/6307630/156950728-e3da849a-5684-46c6-abfc-b2a147359b93.png)
            以下是我的系统环境参数详细说明:
```bash
                root@ldap:~# php -v
                PHP 8.1.3 (cli) (built: Feb 21 2022 14:48:42) (NTS)
                Copyright (c) The PHP Group
                Zend Engine v4.1.3, Copyright (c) Zend Technologies
                    with Zend OPcache v8.1.3, Copyright (c), by Zend Technologies
                root@ldap:~# php-fpm8.1 -v
                PHP 8.1.3 (fpm-fcgi) (built: Feb 21 2022 14:48:42)
                Copyright (c) The PHP Group
                Zend Engine v4.1.3, Copyright (c) Zend Technologies
                    with Zend OPcache v8.1.3, Copyright (c), by Zend Technologies
```

      问题2、在初始安装好showdoc的环境及Nginx配置后访问页面时会出现如下错误:
![Nginx引导页截图](https://user-images.githubusercontent.com/6307630/156950688-ff9670fb-ad25-495e-8157-b9f74fb86ae3.png)
![PHP8.1命令行执行报错，但是PHP7却没问题](https://user-images.githubusercontent.com/6307630/156950668-8f446c39-26e7-41f5-9260-6130912eb538.png)

**Comment by star7th** [comment]
先保证服务器正常再链接客户端。暂未能支持php8.1 ，可以用php5.3-php8.0

**Comment by wushuang5112** [comment]
Hi, 我切换一下PHP版本，目前我的处理是注释那一行，就没报错了!  
服务端是连接正常的，且创建项目都没问题，安卓端也能创建项目并同步到服务端，但就是显示不了，这个很奇怪，即使是showdoc管理员账户也不行。

**Comment by star7th** [comment]
先退出登录。然后链接的地址选择官网 https://www.showdoc.com.cn/ ，看看是否正常。

**Comment by wushuang5112** [comment]
官网登录是正常的，但是我自己的却登录不了!  但是在手机web端是可以登录成功并操作的。
![登录https://www.showdoc.com.cn没有问题，如图](https://user-images.githubusercontent.com/6307630/156951550-c28bdaa2-cd77-490f-8b8b-b583bb75ea66.jpg)

官网链接登录是OK的，但是退出不了，弹窗确认后没有退出用户，很奇怪!
![退出登录后弹窗出现白屏，实际上也没有退出登录](https://user-images.githubusercontent.com/6307630/156951540-61ee9826-3ea3-4341-a863-e4244582d242.jpg)

**Comment by star7th** [comment]
官方服务器退出登录不正常是后来引入的兼容性问题。现在已经可以正常退出。
既然手机端链接官网是正常的，那我倾向认为是你的安装环境问题。你可以尝试用官方docker镜像安装。
