### ISSUE TITLE
新建的接口第一次调用都是这个错误，把默认的调用方式换成GET就可以了，然后再换成POST也行了

### ISSUE THREAD

**Issue by chenliang2012** [star7th/showdoc#1622]
为啥每次新建的接口第一次调用都是这个错误，把默认的调用方式换成GET就可以了，然后再换成POST也行了，这个是什么问题？
![1J}5SKJA3J_)FJIKJ2$OES8](https://user-images.githubusercontent.com/52647642/156960017-4eb58064-ebaa-4b87-917e-d378ac0c768a.png)

**Comment by star7th** [comment]
这个应该跟你的接口有关，而非runapi自身问题。如果想让我测试是否runapi的bug，请提供外网可访问接口供我测试下

**Comment by chenliang2012** [comment]
这个还真不太好提供，只有私有网络的地址，也能用，暂时就先这样吧
