### ISSUE TITLE
runapi能否与在线版本一样开放生成markdown代码？

### ISSUE THREAD

**Issue by chenliang2012** [star7th/showdoc#1624]
因为runapi接口文档无法分享单页，能否与在线版本一样开放生成markdown代码？

**Comment by star7th** [comment]
后面准备增加分享单页功能。生成markdown代码功能不再考虑。

**Comment by brizer** [comment]
> 后面准备增加分享单页功能。生成markdown代码功能不再考虑。

可以介绍下原因吗？

**Comment by FGadvancer** [comment]
https://github.com/FGadvancer/ruapi-generate-md
