### ISSUE TITLE
Mac m1 runapi特别卡

### ISSUE THREAD

**Issue by zywayh** [star7th/showdoc#1627]
在使用过程中，mac m1 pro芯片的机器，卡顿严重，尤其在参数多的情况下特别明显，这个是否可以优化一下？

**Comment by star7th** [comment]
一般是返回参数比较多的时候会有性能影响，而非入参。对于M1，没有太好的办法，暂未支持原生arm。

**Comment by star7th** [comment]
我说的是runapi客户端。

**Comment by zywayh** [comment]
对，我是想问runapi，希望能早点适配m1，谢谢

**Comment by star7th** [comment]
没有M1设备，测试不了兼容性。短期内不打算支持了。

**Comment by star7th** [comment]
已经出了m1兼容版，去下载即可 https://www.showdoc.com.cn/runapi

**Comment by zywayh** [comment]
收到，谢谢大佬
