### ISSUE TITLE
建议上传的图片按所属项目存放

### ISSUE THREAD

**Issue by MQjehovah** [star7th/showdoc#163]
我在自己服务器上搭建了一个showdoc项目，用来做一些笔记和写文档非常的方便，感谢star7th开源了这么好的一个项目，顺便提一下自己的意见，现在的项目上传图片会自动生成文件名按时间组织放在Upload文件夹下，一旦上传后就很难再找到这个文件，所以希望可以按所属项目组织上传的文件，并且删除项目是可以顺便删除项目的图片目录

**Comment by star7th** [comment]
项目名是中文的，用项目名分类不合理。
建议累计久了就自动手动清理下数据库不再使用的图片——根据url来判断有没有使用。
大部分情况下还是不需要清理的。

**Comment by MQjehovah** [comment]
图片有数据存数据库了吗？请问我直接去Upload目录删除文件行不行？

**Comment by star7th** [comment]
如果你确认你的文档不再引用任何图片，可以全部删除的。
