### ISSUE TITLE
showdoc-2.10.3系统升级导致图片显示问题

### ISSUE THREAD

**Issue by yhl173** [star7th/showdoc#1638]
背景：
将系统由showdoc-2.8.15升级到showdoc-2.10.3后部分文档图片不显示
在使用showdoc-2.8.15过程中更换过服务器域名
（历史域名1：https://lcyxs.iask.in:
    历史域名2https://cys888.cn:
    现域名3：https://www.cys888.cn )
情况说明：
1-文档图片地址1：https://www.cys888.cn:8089/server/index.php?s=/api/attachment/visitFile/sign/5f0cbb2f46abe642ce133b18b0cb90f1

2-浏览器打开后跳转地址：https://lcyxs.iask.in:8089/Public/Uploads/2021-07-02/60def3534fdf0.jpg

3-实际项目地址：https://www.cys888.cn:8089/Public/Uploads/2021-07-02/60def3534fdf0.jpg

更换服务器域名发生过图片不显示的问题，当时修改文档中图片地址后图片显示；
本次升级后文档中的图片地址正常，但跳转地址为上次记录的地址，请教如何修复图片并让它在文档中正常显示？

文档地址：https://www.cys888.cn:8089/web/#/7/50

**Comment by star7th** [comment]
迁移服务器按这个教程操作 https://www.showdoc.com.cn/help/2511252204165611

**Comment by star7th** [comment]
对于新版showdoc，可在管理员后台配置网站外部url，从而直接定死图片资源的前缀网址（只对新上传图片有效）

**Comment by yhl173** [comment]
在参照教程研究，感谢回复
