### ISSUE TITLE
能否在管理后台加个设置，在OSS上传图片后，使用原始链接附在文档上

### ISSUE THREAD

**Issue by CharmingCheung** [star7th/showdoc#1639]
考虑到以后迁移会出现问题，想图片上传到OSS后，附在文档里的是原始链接

看了一下源码，尝试把`AttachmentModel.class.php`的`upload`函数的这行删除，不使用showdoc来做url转发
```java
$url = server_url("api/attachment/visitFile",array("sign" => $sign)); 
```
能实现预期内的效果，只是没再看其他关于这部分功能的引用关系，不知道会产生什么连锁后果QAQ。

希望能在管理后台能添加这开关功能，感谢！

**Comment by star7th** [comment]
目前统计附件流量需要用到url转发。其他情况暂时未用到。为了以后扩展方便，我肯定要保留这个功能的，比如以后做防盗链也简单很多。showdoc官网也是用这种方式来统计流量和防盗链的

**Comment by CharmingCheung** [comment]
了解~那我先暂时先这样处理来实现我个人的需求吧，感谢回复~

**Comment by CharmingCheung** [comment]
了解~那我先暂时先这样处理来实现我个人的需求吧，感谢回复
