### ISSUE TITLE
markdown渲染效果不统一

### ISSUE THREAD

**Issue by mazechi** [star7th/showdoc#164]
编辑的时候一种效果， 保存后浏览又是另外的效果。
单页项目的跟又和普通项目的效果不一样。

**Comment by star7th** [comment]
会有小小的不一致，但绝大部分是相同的。
截图说下你觉得的不同点。

**Comment by mazechi** [comment]
主要还是在代码块的显示上面，用的是chrome浏览器。

编辑的时候：
![编辑](https://user-images.githubusercontent.com/3959927/29906182-d789c288-8e45-11e7-9fb9-24f8906f33a0.png)

查看的时候：
![单页项目](https://user-images.githubusercontent.com/3959927/29906207-ff0593e6-8e45-11e7-8923-0caea54be82f.png)


![普通项目](https://user-images.githubusercontent.com/3959927/29906162-c3df1616-8e45-11e7-88d6-c286ad9ffcbf.png)

**Comment by mazechi** [comment]
其实我是比较倾向于编辑时候的显示效果

**Comment by star7th** [comment]
发现问题了。现在已经修正。之前我改了样式，但是遗漏单页项目的没改。现在的代码块已经一致了。
![image](https://user-images.githubusercontent.com/2200494/29906912-de194f92-8e4a-11e7-96b7-236a66bbe660.png)
