### ISSUE TITLE
doc文件导出

### ISSUE THREAD

**Issue by GitChenfan** [star7th/showdoc#1641]
server/Application/Common/Common/function.php 下 output_word 方法中 有一句
`    $data = str_replace("<img ","<img width=500 ",$data);
`
这里的作用是什么？替换后图片的宽度都变了，去掉会有什么问题？

**Comment by star7th** [comment]
好像就是为了防止大图片变形。你去掉就去掉了，应该也没啥大影响

GitChenfan ***@***.***> 于2022年3月23日周三 23:27写道：

**Comment by GitChenfan** [comment]
有没有办法将内部引用的图片文件全部打包到doc里，避免打开doc文档还需要重新下载，因为导出后可能会在无网络模式下打开文档

**Comment by star7th** [comment]
不打算做这个。第一是难度问题，更重要是文件大小体积不可控。稍微多一点图片会让用户直接打不开文件

**Comment by GitChenfan** [comment]
ok
 $data = str_replace("<img ","<img width=500 ",$data);

**Comment by ClarenLee** [comment]
导出word后图片确实看起来又长又窄，看不清了
