### ISSUE TITLE
mac M1芯片的docker服务无法启动

### ISSUE THREAD

**Issue by skinhc** [star7th/showdoc#1642]
警告 :WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

系统版本:12.3 (21E230)
docker version 
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:53:34 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by MHXXX** [comment]
目前只有 amd64 架构的镜像, 没有 arm64 架构的, 所以你得自己做镜像

**Comment by star7th** [comment]
官方docker不支持M1 .如果你想安装，要手动运行ARM环境下的PHP，然后把showdoc源码包放进去。就跟运行普通php镜像那样。

**Comment by star7th** [comment]
官方初步推出了ARM版本的docker镜像。 命令 

docker pull star7th/showdoc:arm-latest

docker run -d --name showdoc --user=root --privileged=true -p 4999:80 \
-v /showdoc_data/html:/var/www/html/ star7th/showdoc:arm-latest 


目前已知的ARM版docker镜像缺陷：
0,只能使用docker官方镜像 star7th/showdoc:arm-latest  ，可能没有大陆镜像加速
1，只支持ARM64位，应该不支持ARm32位.目前在ARM64位的centos7上安装测试已经通过，其他硬件设备由于缺乏测试环境，故尚未测试。理论上ARM64环境都可以兼容。
2，可能无法使用英文版，只能用默认的中文版
3，无法使用mock功能
4，上传图附件到云储存功能尚未测试，且没打算逐一测试各平台，不保证能支持各大云储存
5，导入中文命名的压缩包可能出错。这个问题不打算测试和处理
