### ISSUE TITLE
可以提供一个导出pdf文件格式的功能吗

### ISSUE THREAD

**Issue by jj-lu** [star7th/showdoc#1643]
在现有导出word文件和md文件压缩包的功能基础上，再新增一个可以导出pdf文件的功能

**Comment by star7th** [comment]
导出的pdf也是用word格式来转的。建议用个转换工具自己转一下。目前导出的word格式不是很美观，一般需要用户自行调整一下。而pdf用户是无法调整的。目前的导出样式下，pdf格式的实用性不高。要做好样式的话，太难了。还是主打在线查看吧
