### ISSUE TITLE
是否提供第三方账号自动注册服务？

### ISSUE THREAD

**Issue by c4ys** [star7th/showdoc#1646]
公司打算为客户做一个知识库，希望现有的付费客户都能自动注册为只读账号，如果客户没有付费后，自动可以通过API回收权限。

**Comment by star7th** [comment]
接入Auth2登录就好了。然后你们自己程序控制Auth2里的账号是否可用。
不过showdoc并没有注册为只读账号的功能

**Comment by c4ys** [comment]
非常感谢回复，
个人认为这是一个非常好的卖点。

有很多乐意付费的用户都是希望给自己的部分客户提供无缝切换到文档平台的能力，
而现在市面上我今天找了语雀，石墨等，都没有提供这种能力，或者提供了但是收费贵，这可以作为产品一个重要的特色。

**Comment by star7th** [comment]
关于整合，你可以登录管理后台看看 集成登录 那一块

ning ***@***.***> 于2022年3月24日周四 18:24写道：

**Comment by c4ys** [comment]
https://www.showdoc.com.cn/1880831101782751/8618253667009643

你说的是这个吗？

我觉得能提供oauth2会更好：

在云平台注册一个app，
我得到这个app id和key后，可以自己通过api管理用户以及权限等等。

**Comment by star7th** [comment]
不是这个 ； 建议你先自己安装一个showdoc，然后自己研究下在已有功能下怎么实现自己的需求。

**Comment by star7th** [comment]
有新问题再提出来。关闭此问题了。

**Comment by yunskyline** [comment]
> 有偿客户自愿为客户做一个知识库，付费的客户可以自动注册为客户后勤做一个知识库，如果客户没有计划，可以自动通过API回收权限。

我是创建一个只读帐号，然后通过通用接入让他们通过链接直接访问。
