### ISSUE TITLE
登录账号密码明文传输

### ISSUE THREAD

**Issue by ghost** [star7th/showdoc#1647]
问题：用户登录过程中使用明文传输用户登录信息，若用户遭受中间人攻击时，攻击者可直接获取该用户登录账户

处置建议：
1、用户登录信息使用加密传输，如密码在传输前使用安全的算法加密后传输，可采用的算法包括：不可逆hash 算法加盐（4 位及以上随机数，由服务器端产生）；安全对称加密算法，如AES(128、192、256 位)，且必须保证客户端密钥安全，不可被破解或读出；非对称加密算法，如RSA(不低于1024 位)、SM2 等。
2、对账户进行策略限制，多次登录失败进行锁定

**Comment by star7th** [comment]
传输安全还是交给https吧。showdoc应用层不打算做多少。中间人攻击的话，说实话，对方如果能做到这一步，很多信息都没办法了。比如说他能获取到你账号的管理员权限。所以这一步showdoc层面做不了什么防范或者说防范的代价太高，不应该是showdoc的责任。
目前同一个账号登录失败多次是会弹出验证码的。但是不会锁定。

lwb332 ***@***.***> 于2022年3月25日周五 09:22写道：

**Comment by mazhewei** [comment]
https确实可以解决问题，查了数据库，数据库密码是密文存储的，个人感觉问题不大。

刚好在研究部署showdoc，顺便补充https的配置方案。

1. 外部架设nginx服务，在nginx服务上配https做4999端口转发，类似官网的绑定域名部分介绍，不再赘述
2. 直接配置到内部nginx中，举个例子，供参考

准备好证书文件和目录，我个人习惯在```/home/showdoc```目录下。

```text
/home/showdoc            => 主目录
/home/showdoc/html       => 存放主要资源
/home/showdoc/cert       => 存放证书文件
/home/showdoc/vhost.conf => 用于覆盖容器内部的nginx配置文件
```

下面这个是vhost.conf的文件内容

```conf
# 如果你希望保留http协议访问，则取消下面的注释
# server {
#     listen 80;
#     server_name _;
#     server_tokens off;
#     root "/app";
#     index index.php;
#     include /opt/docker/etc/nginx/vhost.common.d/*.conf;
# }

server {
    # 不要改此处的端口，端口直接改在docker run命令上
    listen       443 ssl;
    server_name  _;
    server_tokens off;
    # 配置SSL证书，路径在/opt/docker/etc/nginx/ssl/
    ssl_certificate      /opt/docker/etc/nginx/ssl/【你的证书文件名】;
    ssl_certificate_key  /opt/docker/etc/nginx/ssl/【你的证书密钥文件名】;
    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m;
    ssl_ciphers  HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers  on;
    # 禁用不安全的TLSv1.0和TLSv1.1协议
    ssl_protocols TLSv1.2;
    # 出现497错误时(使用了http协议访问https端口时)自动重定向到https上
    # 如果你保留http访问方式，则注释下面这行
    error_page 497 301 https://$http_host$request_uri;

    root "/app";
    index index.php;
    include /opt/docker/etc/nginx/vhost.common.d/*.conf;
}
```

修改docker的启动命令，增加相关文件的映射和端口隐射。

```shell
docker run -d --name showdoc -p 【你设置的https访问端口】:443 \
-v /home/showdoc/html:/var/www/html \
-v /home/showdoc/vhost.conf:/opt/docker/etc/nginx/vhost.conf \
-v /home/showdoc/cert:/opt/docker/etc/nginx/ssl \
star7th/showdoc
```

备注：

1. 如果保留http访问，需要增加一个指向80端口的映射
2. 官方文档有一个```--user=root --privileged=true```，我自己没加好像也能用，不放心的就加上
