### ISSUE TITLE
页面中或者返回的响应包中泄露了站点信息

### ISSUE THREAD

**Issue by ghost** [star7th/showdoc#1648]
问题：在页面中或者返回的响应包中泄露了站点信息（php版本，服务器版本），通过这些信息，给攻击者渗透提供了较多的有用信息。

处置建议：在服务器端对相关敏感信息进行模糊化处理。

**Comment by jason-this** [comment]
这些属于服务器的设置了，估计你是通过docker部署的吧，你可以自己搭建环境部署；我自己搭建的环境就不会；或者你可以自己定制docker镜像来部署；你提到的这个跟作者的应用没有关系的，开源的意义也不是说让你拿来就直接用，这种部署上的问题，也不应该提Issue ；

**Comment by star7th** [comment]
如果是用docker部署的，那么这些服务信息是docker内部的信息，应该风险还算可控吧。说实话，即使不返回，人家查一下showdoc的官方docker镜像用的是什么版本的php，也能知道信息。

如果是非docker部署的，自行在nginx层级隐藏这些信息吧。

**Comment by star7th** [comment]
docker里面的服务器环境信息返回也没什么的吧，反正又不是真的物理机环境。如果是自己部署的，自己在nginx层面禁止即可。

JasonHuang ***@***.***> 于2022年3月25日周五 11:34写道：
