### ISSUE TITLE
v2.10.4版本的编辑器无法粘贴代码

### ISSUE THREAD

**Issue by jason-this** [star7th/showdoc#1649]
使用v2.10.4的编辑器 添加代码的时候 使用粘贴 会贴到了 正常的编辑器中，而不是粘贴到弹出的代码编辑框；
使用的浏览器是
Microsoft Edge
版本 99.0.1150.46 (正式版本) (64 位)

**Comment by star7th** [comment]
这个有时间看看怎么兼容。其实你可以不用编辑框的代码插入。直接自己手写```符号即可

JasonHuang ***@***.***> 于2022年3月25日周五 11:29写道：

**Comment by jason-this** [comment]
目前是这样用的；
```语言
code
```
新版的这个代码样式是的确好看 @star7th

**Comment by star7th** [comment]
新版已经已经处理好这个兼容问题了
