### ISSUE TITLE
无法导出文档

### ISSUE THREAD

**Issue by JasonHonor** [star7th/showdoc#165]
master版本，选择路径后，点击导出，无任何响应也没有文档下载。

**Comment by star7th** [comment]
我下载了github上的这个版本权限安装，再次测试，是可以导出的。
你可以提供下你出错时的这个页面的网络请求，看看返回什么结果

**Comment by hpxy1314** [comment]
文档太大，导出apache会停止响应。

**Comment by XmYhkj** [comment]
> 文档太大，导出阿帕奇会停止响应。

请问是如何解决的？

**Comment by hpxy1314** [comment]
> > 文档太大，导出阿帕奇会停止响应。
> 
> 请问是如何解决的？

没有解决方案，后来我换成eolinker做api管理了，文档现在腾讯文档也挺方便~呵呵··

**Comment by star7th** [comment]
用官方docker安装新版showdoc基本没有这个问题。一般是自己安装的服务器有限制才如此。

hpxy1314 <notifications@github.com>于2019年3月26日 周二下午2:34写道：

**Comment by star7th** [comment]
尝试更新新版

Chen Xing <xing7th@gmail.com>于2019年3月26日 周二下午2:38写道：
