### ISSUE TITLE
win客户端修改服务器地址闪退

### ISSUE THREAD

**Issue by seaofcomplete** [star7th/showdoc#1651]
docker安装的，然后使用frp代理，修改服务器地址时，输入https://xxx.xx.xxx:1234/ 这种格式时点击确定时闪退，没代理的时候输入http://xx.xx.xx:1234, 是没问题的，安卓端的输入代理后的url是可以连上的。

**Comment by star7th** [comment]
直接浏览器访问地址正常吗，可正常创建项目删除项目吗

**Comment by star7th** [comment]
另外你说的win客户端指的是showdoc客户端还是runapi客户端？

**Comment by seaofcomplete** [comment]
是showdoc客户端，浏览器操作没有任何问题，并且安卓端可以连接。

**Comment by star7th** [comment]
请提供一个外网可重现例子。我重现不了的话我没办法。因为我这边正常

**Comment by seaofcomplete** [comment]
用这个吧，https://cn-cd-dx-7.natfrp.cloud:15569 @star7th

**Comment by star7th** [comment]
感觉问题挺明显的，你用的是自定义证书，你用浏览器访问的时候它不会提示不安全吗。客户端目前只支持公认证书

**Comment by seaofcomplete** [comment]
我也考虑过这个问题，但出现了手机端的可以使用，这就很诡异了 @star7th

**Comment by star7th** [comment]
手机端能使用是因为使用了官方代理 https://github.com/star7th/showdoc/issues/801  而服务端的代理被设置了忽略证书校验。

**Comment by seaofcomplete** [comment]
好的，了解了，谢谢！ @star7th
