### ISSUE TITLE
showdoc 可以做个 typora 的图片上传到 showdoc 的工具吗

### ISSUE THREAD

**Issue by hellolgml** [star7th/showdoc#1653]
尝试去理解过，暂时没搞懂需要怎么操作才能实现？

还望指导下，谢谢；

因文档编辑有大量的图片需要上传编辑归档，急需；

**Comment by star7th** [comment]
标题跟内容描述不是同一个问题。我不知道应该如何回答你。showdoc没有计划做个typora的图片上传工具

hellolgml ***@***.***> 于2022年3月29日周二 11:10写道：

**Comment by hellolgml** [comment]
@star7th 

很抱歉，语言没组织好；

就是typora的 图床设置，不知道如何实现 上传到 自己搭建的 showdoc 服务器；（见下图的 typora 的图床设置）
![image](https://user-images.githubusercontent.com/23045371/160526355-762ad6d2-8d7f-4c32-bf53-7a0b152bc79a.png)

**Comment by star7th** [comment]
跟showdoc有什么关系啊！你去问typora的客服！

**Comment by star7th** [comment]
如果typora本身是要showdoc做出适配的话，showdoc没有做任何适配，且不打算做。showdoc本身是个markdown编辑工具，然后专门去做个功能支持别的工具，你能不能不要来问这种奇奇怪怪的问题。

**Comment by star7th** [comment]
如果typora本身是要showdoc做出适配的话，showdoc没有做任何适配，且不打算做。showdoc本身是个markdown编辑工具，难道专门去做个功能支持别的markdown工具吗，这没道理啊 。 你能不能不要来问这种奇奇怪怪的问题。

**Comment by star7th** [comment]
你如果要使用typora作为编辑工具，那可能是它适合你，我支持你。但是你别因为typora的功能来找showdoc要支持。你应该去问typora能不能支持上传到showdoc

**Comment by hellolgml** [comment]
感谢耐心的解答；
感谢实时的沟通；
感谢热心的指导；

实测typora的图片markdown 语法 在 showdoc 上不能使用，所以。。。

typora 的自定义图床 网上有不少教程，也看懂了；

谢谢
