### ISSUE TITLE
私有化部署，后台配置了七牛云的oss绑定域名，但附件最终的连接还是原项目地址

### ISSUE THREAD

**Issue by feigaogit** [star7th/showdoc#1654]
showdoc，私有化部署，后台配置了七牛云的oss绑定域名，但附件最终的连接还是原项目地址
![image](https://user-images.githubusercontent.com/18181270/160748913-30f84cc5-87e7-45be-b735-9395ae50495e.png)
![image](https://user-images.githubusercontent.com/18181270/160748921-714f3aa0-b8b0-4832-a736-81f4a3cb547f.png)
真实的地址应该是
![image](https://user-images.githubusercontent.com/18181270/160748932-65bfe2d2-b68b-4f96-a117-8bf3cc0f5ef3.png)

请问为什么？是我哪里配置的有问题吗

**Comment by star7th** [comment]
配置后只对新上传的文件有效。旧文件连接不会发生变化

**Comment by feigaogit** [comment]
> 配置后只对新上传的文件有效。旧文件连接不会发生变化

就是新上传的，刚刚上传的文件也是不行的
![image](https://user-images.githubusercontent.com/18181270/160749411-71a528ec-2c26-4504-82e4-ad3e47fba396.png)
![image](https://user-images.githubusercontent.com/18181270/160749438-d6dc0643-3d58-432c-bb8e-4f851735716c.png)
![image](https://user-images.githubusercontent.com/18181270/160749541-2dd280b9-bc66-442a-8eed-a37137acf62f.png)

**Comment by star7th** [comment]
你的网站开个临时账号我上去测试一下

**Comment by star7th** [comment]
我不知道你那边什么情况。我用我自己的七牛云配置测试，绑定不绑定域名都没问题。我大概率觉得应该不是showdoc程序问题，因为我测试了几遍都可以。你那边确保自己的配置正确、使用新版代码、没有自行修改过官方程序，或者使用官方docker环境部署看看。由于我无法重现你的问题，所以我无能为力。

**Comment by Doyoo** [comment]
<img width="1116" alt="WX20220331-232553@2x" src="https://user-images.githubusercontent.com/20851045/161092324-6d433f6c-ee23-472d-9a75-5db2305d22ca.png">
这样试试

**Comment by star7th** [comment]
> <img alt="WX20220331-232553@2x" width="1116" src="https://user-images.githubusercontent.com/20851045/161092324-6d433f6c-ee23-472d-9a75-5db2305d22ca.png">
> 
> 这样试试 路径：/html/server/Application/Api/Model/AttachmentModel.class.php

理论上改了不影响，跟他反馈的不是同一个问题。但可以试试，如果真的可以了就反馈给我。

**Comment by feigaogit** [comment]
@star7th 
这样上传的时候就直接显示了源地址了，源地址显示也是正确的七牛云地址
![image](https://user-images.githubusercontent.com/18181270/161178365-1944c364-b624-4ab4-a842-56a29eb652da.png)

但这里只修改了上传，在后台文件库仍然是使用server_url /api/attachment/visitFile 方法，复制链接或查看的时候地址还是错误的
![image](https://user-images.githubusercontent.com/18181270/161178552-0ab81629-6b09-402f-b38b-37cb41784e41.png)

是否需要尝试修改 /api/attachment/visitFile api

**Comment by star7th** [comment]
showdoc访问附件有两层。第一层本来就是通过showdoc的脚本，然后脚本会自动重定向到真正的地址。
目前你反馈的问题我无法重现，我自己怎么测试都是好的。

**Comment by star7th** [comment]
而且也没有其他人反馈过这个问题。我倾向认为这不是一个普遍bug

**Comment by feigaogit** [comment]
> 而且也没有其他人反馈过这个问题。我倾向认为这不是一个普遍bug

我好想知道问题了
因为服务器上iis上托管了一些在用的站点，showdoc没办法直接使用80端口，nginx为showdoc绑定的90端口，然后在iis上绑定域名doc.yzl.ltd:80并重写到nginx的localhost:90端口

我在服务器本地直接使用localhost:90进行文件上传，获取到的地址是正确的七牛云地址，但是在外网使用doc.yzl.ltd获取到的地址就是源doc.yzl.ltd域名

![image](https://user-images.githubusercontent.com/18181270/161183695-3742b5f5-1b6f-4f9a-a65c-29bc14e249b4.png)

![image](https://user-images.githubusercontent.com/18181270/161183666-27da45fb-6ce0-465b-8408-8660ff391173.png)

**Comment by feigaogit** [comment]
解决不了，不知道转发为什么会这样，还是使用url重写吧
