### ISSUE TITLE
不支持MarkDown流程图渲染有点遗憾

### ISSUE THREAD

**Issue by zouwei** [star7th/showdoc#1655]
gitlab的wiki文档资料直接支持MarkDown流程图、时序图等图表代码直接渲染成图片。期待showdoc也能支持，那一定会是非常受欢迎的强大功能。
![微信截图_20220330194022](https://user-images.githubusercontent.com/16266571/160826475-bd5764f6-758c-46a6-8e20-3cc83ed4a7df.png)
目前sequenceDiagram直接按照代码块输出显示的。

**Comment by star7th** [comment]
系统生成的示例文档里有markdown教程，里面有使用示例。

胡邹不胡诌 ***@***.***>于2022年3月30日 周三下午7:39写道：
