### ISSUE TITLE
bug   markdown中有html标签时会出问题

### ISSUE THREAD

**Issue by zhouxiaofu** [star7th/showdoc#1657]
如果markdown文档中有html标签，然后会提示  转为纯文本，或者 尝试 html转markdown

如果尝试 html转markdown ，会将markdown中的代码给转换了 , 转的乱七八糟的，直接显示不行吗？

**Comment by zhouxiaofu** [comment]
我试了一下  docker pull star7th/showdoc:v2.9.6
这个版本没问题，非常完美。

**Comment by zhouxiaofu** [comment]
已根据[官方文档](https://www.showdoc.com.cn/help/65610)降级到 v2.9.6

**Comment by star7th** [comment]
这个机制还真卡住了。目前由于引入了判断机制，似乎暂时无解。因为你确实复制的是html代码（而非单纯的markdown文本）。
这种情况下建议你可以分段复制，涉及到html代码的部分手动完善下。
在目前的机制下，要兼容你说的情况挺麻烦的，所以我倾向于不处理。当有更多用户反馈的时候我再花时间处理。
至于你要回退旧版本，我不是很建议。因为以后会有新特性你用不了。但是你要用也行。
