### ISSUE TITLE
成员分享权限问题

### ISSUE THREAD

**Issue by HelloHaiGG** [star7th/showdoc#1660]
我作为项目的管理员，分享时可以选择分享的方式（单页面分享还是全页面分享）
如果我将成员A加入到我的项目，并且成员A是只读权限，成员A仍可以分享我的项目，并且默认全页面分享，这个是否是个BUG呢？有没有计划优化？

**Comment by star7th** [comment]
成员是有页面分享权限的。他可以分享出去，但是，外面的人看不看得到，取决于自己是否有权限。跟原分享人没关系

HelloHaiGG ***@***.***>于2022年4月1日 周五下午7:00写道：

**Comment by HelloHaiGG** [comment]
我的意识是，成员的分享链接是默认分享的全部的页面，并不能选择分享单一页面

**Comment by star7th** [comment]
成员分享什么都不会影响他人的访问性，我不觉得有问题。你如果想对项目保密，就设置项目密码。别人不知道密码，就算分享链接出去了也看不到。

HelloHaiGG ***@***.***>于2022年4月1日 周五下午7:12写道：

**Comment by HelloHaiGG** [comment]
为什么不能给成员一个选择呢，让他也可以控制分享内容

**Comment by star7th** [comment]
只读成员没有那么权限。要个性化处理就分配编辑权限或者项目管理权限

HelloHaiGG ***@***.***> 于2022年4月1日周五 19:23写道：
