### ISSUE TITLE
请在代码块中使用等宽字体

### ISSUE THREAD

**Issue by wynn5a** [star7th/showdoc#1662]
十分感谢作者提供此工具 💯 

有个小小的建议，请在代码块中使用等宽字体

**Comment by star7th** [comment]
请说明为什么

**Comment by wynn5a** [comment]
1. 字体等宽能够保证在注释里面绘制的流程图等不会变形
2. 等宽字体能够让代码更加清晰可读，能够保留足够的空间给部分字符，比如 l，i，j 等
3. 有些等宽字体能够更方便的区分 1lI，0o等

**Comment by wynn5a** [comment]
补充一个主观观察到的结论，供参考：🍶 这好像也是大部分程序员都默认了的一种约定，而且几乎所有程序员相关的阅读和写作平台，都会在代码块里使用等宽字体 😆

**Comment by star7th** [comment]
已发布新版，解决了问题
