### ISSUE TITLE
关于推送服务及编辑字体

### ISSUE THREAD

**Issue by Sshad0wsec** [star7th/showdoc#1663]
你好，showdoc部署到本地的话是不是不能使用推送到手机服务，如果可以，怎么设置？还有就是希望编辑器字体可以设置颜色，重点的可以标红。

**Comment by star7th** [comment]
你说的推送服务指的是哪个？这个吗 ？ https://push.showdoc.com.cn/  这个是一个独立工具，部署不部署showdoc都可以使用。
标红请自己使用hrml代码实现。showdoc使用的是markdown语法，不支持直接标红。

**Comment by Sshad0wsec** [comment]
你好我想问问，本地搭建的showdoc，showdoc推送服务怎么使用，比如我在web端项目做完了想通过手机推送给项目内的成员，怎样设置。还有就是为什么我在项目页面内突然不能ctrl+v粘贴了。

**Comment by Sshad0wsec** [comment]
不好意思可以粘贴了应该是我的问题，现在就是showdoc推送服务不会使用

**Comment by star7th** [comment]
“在web端项目做完了想通过手机推送给项目内的成员”——目前不支持此功能。以后可能会更新吧。
不清楚为什么不能粘贴，尝试重启浏览器吧。

另外就是我强烈建议你阅读一下推送服务的文档，你问这个问题似乎就完全不知道推送服务是干嘛用的

**Comment by Sshad0wsec** [comment]
谢谢

**Comment by star7th** [comment]
https://push.showdoc.com.cn/ 首页有个查看教程按钮。如果你读不懂，证明你不是推送服务的目标群体，你可以不用懂。

**Comment by Sshad0wsec** [comment]
明白了，我看了半天没怎么看懂，你这么一说我就懂了，谢谢
