### ISSUE TITLE
ldap 问题

### ISSUE THREAD

**Issue by AdamTulip** [star7th/showdoc#1673]
1. 使用ad域登录不成功，docker logs -f showdoc 看见错误 “Assertion failed: lr->lr_refcnt == 0 (request.c: ldap_find_request_by_msgid: 1672)。”， 请问是怎么解决？
2. ad域帐号同步到showdoc以后，再在showdoc里删除某用户，之后怎样还可以同步回 showdoc里？
3. 哪里找个集成登录配置的案例？

**Comment by star7th** [comment]
1，我看不懂错误提示；没遇到过；
2，重新点击一次保存ad域配置；
3，没有，官网文档说的挺清楚了，如果你不懂，你不是开发人员，就不建议使用。

**Comment by AdamTulip** [comment]
解决了，升级后 base dn 配置要加上OU, 之前是不用的，谢谢！
