### ISSUE TITLE
附件改成阿里云oss后，图片上传后类型默认变成了 application/octet-stream

### ISSUE THREAD

**Issue by wuwu20048** [star7th/showdoc#1674]
配置了阿里云oss，上传png图片后，文档里能正常显示图片。但是单独把图片链接复制出来在浏览器里打开，默认变成了下载，不能直接预览。到oss后台看，发现类型默认成了application/octet-stream 。请问下这个是不是代码问题，导致contenttype没有正确设置？
没有设置阿里云oss前，之前上传的图片，在浏览器里能正常打开浏览。

<img width="458" alt="image" src="https://user-images.githubusercontent.com/3445253/163124616-dd621fa4-5dd2-4151-b139-7657310770ad.png">

**Comment by star7th** [comment]
说实话我也没了解那么细节。上传oss这块是使用开源库用s3协议上传。可能是改了吧。

**Comment by star7th** [comment]
不对，我记得我之前上传的时候是可以直接打开图片在浏览器中预览的。你这个应该是特例问题吧？不清楚你的服务器为什么改

**Comment by wuwu20048** [comment]
问下，网站的描述 能清除或自定义吗 ？每次聊天窗口发消息都会提示这个
<img width="427" alt="image" src="https://user-images.githubusercontent.com/3445253/163335773-9feda5c7-20fb-4d47-978d-8caf1ac867ed.png">

**Comment by star7th** [comment]
很反感这种没头没尾也跟本问题无关的额外问题。又不说是在什么工具里显示的，以及分享什么url的时候才显示

**Comment by wuwu20048** [comment]
嗯，抱歉 的确和本issue无关，上面情况是我分享showdoc文档链接到钉钉聊天窗口时，钉钉会把网页的title和描述，自动显示出来，有点干扰。目前想的是去改源文件😂，把title和description去掉试试

**Comment by star7th** [comment]
发布了新版。修改了文字描述。
