### ISSUE TITLE
导入功能是否可以支持选择目录后导入

### ISSUE THREAD

**Issue by lovegames** [star7th/showdoc#1675]
一般项目管理都会建立多级目录,选择目录导入方便更新之前的api等文档

**Comment by star7th** [comment]
更新最新版，本来就有这个功能。

少年别回头 ***@***.***> 于2022年4月13日周三 17:22写道：

**Comment by lovegames** [comment]
我使用的是升级后的版本
![image](https://user-images.githubusercontent.com/33571601/163162773-befc3365-364d-4a69-a780-e357b4e18b36.png)
![image](https://user-images.githubusercontent.com/33571601/163163711-faf225a3-5a1b-46a3-88ba-7a734b9c8ded.png)
没有看到怎么选择目录
![image](https://user-images.githubusercontent.com/33571601/163163780-5d8ae72e-834d-432b-ab22-f3094c358d07.png)
同时同一个postman的json导入发现同样的接口名字没有覆盖
![image](https://user-images.githubusercontent.com/33571601/163163842-c6f2875e-e376-4c8b-ad1c-1ee3d6abc4dc.png)

**Comment by lovegames** [comment]
postman生成的json
{
	"info": {
		"_postman_id": "2bd17035-b81e-43be-8c11-0bd596a000a8",
		"name": "测试导入api",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "测试接口1",
			"request": {
				"method": "GET",
				"header": [],
				"url": {
					"raw": "test?1=1",
					"host": [
						"test"
					],
					"query": [
						{
							"key": "1",
							"value": "1",
							"description": "1"
						}
					]
				}
			},
			"response": []
		}
	]
}

**Comment by star7th** [comment]
我想起了。目录结构是根据导入的情况来的。你在postman新建那样的目录结构就好
