### ISSUE TITLE
能不能增加个统计返回文本大小的功能呢？

### ISSUE THREAD

**Issue by liuwm91** [star7th/showdoc#1677]
工具挺好用的，如果能增加个统计返回文本大小的功能就更棒了！

**Comment by star7th** [comment]
指的是runapi客户的请求接口吗？有时间加一下

**Comment by star7th** [comment]
已经支持显示大小。重启runapi客户端或者重新下载 https://www.showdoc.com.cn/runapi/30291

**Comment by liuwm91** [comment]
![image](https://user-images.githubusercontent.com/6902289/165456727-ab1fb27a-19b6-4d7d-bdd6-da298d61614f.png)
请问新加的显示大小是在哪里查看呢？重新下载客户端了，好像还是只能看到响应码和耗时。
像postman的话就会把size也一并显示
![image](https://user-images.githubusercontent.com/6902289/165457325-339b4b31-81ba-49c9-8f37-ce1a71e9c9c2.png)

**Comment by star7th** [comment]
额，目前的大于1K的才会显示。小于1K的没有显示的必要吧

**Comment by liuwm91** [comment]
好的了解
