### ISSUE TITLE
导入swagger3解析不完整。

### ISSUE THREAD

**Issue by renyp2** [star7th/showdoc#1679]
request query以及body没办法正常显示，也不支持map类型

**Comment by star7th** [comment]
把文件脱敏后发出来看看。我需要在我本地重现才能发现问题

**Comment by renyp2** [comment]
[testswagger3.md](https://github.com/star7th/showdoc/files/8553914/testswagger3.md)
如上md文件中有json数据

**Comment by renyp2** [comment]
对照https://editor.swagger.io/#解析，补充get返回为数组时，无法显示数组内容，见新md中json
[testswagger3.md](https://github.com/star7th/showdoc/files/8553946/testswagger3.md)

**Comment by star7th** [comment]
你提供的例子，我测试了下，完全是正常的。另外也不知道你为什么提到get，这个文件里没有get请求方式。你检查下自己是不是发错文件了

**Comment by renyp2** [comment]
get在第二个md文件中，可能文字没有描述清楚，我截图描述了一下，重新将swagger3 json文件放到了最下面。见swagger问题描述：
[swagger问题描述.md](https://github.com/star7th/showdoc/files/8559392/swagger.md)

**Comment by star7th** [comment]
嗯，看到问题了。感觉这swagger3嵌套格式好多，处理起来真麻烦。有空再处理下

**Comment by johnhorse** [comment]
我们也遇到这个问题了，把项目中的swagger的json文件导入之后，请求参数解析不出来，请问这个问题解决了吗？

**Comment by fan719** [comment]
我们也遇到这个问题了，把项目中的swagger的json文件导入之后，请求参数解析不出来，请问这个问题解决了吗？
 2024年了，请问这个问题解决了吗？
![图片](https://github.com/star7th/showdoc/assets/19567134/2172855e-9c4c-41f7-bb83-342bfb1983a3)
