### ISSUE TITLE
新版本，注册后退出重新登陆报错404

### ISSUE THREAD

**Issue by zhyzhyzhy** [star7th/showdoc#168]
新版本安装后退出重新登陆报错404
= =

**Comment by star7th** [comment]
试了下，没发现此问题

**Comment by youlinux** [comment]
我也遇到了，重新登录一直不行额。。。。 一直是404

**Comment by star7th** [comment]
@youlinux 建议截图说明。因为我重现不了你说的情况

**Comment by youlinux** [comment]
![image](https://user-images.githubusercontent.com/28828034/30536045-f02ea952-9c96-11e7-81fd-57fc733f83dd.png)

您好，如图，登录页面一直报404～

**Comment by star7th** [comment]
@youlinux @zhyzhyzhy 
你先手动删除下面截图的这个目录。我的本地git库是没有这个目录的，推送到github的时候就产生了。我待会看看怎么解决。你先手动处理
![image](https://user-images.githubusercontent.com/2200494/30536362-1ea6e834-9c98-11e7-8d12-6381dca3a4cd.png)

**Comment by youlinux** [comment]
额，好想还是不行。。。。    我是直接把 application 目录给删除了！  还是一样的报错～

**Comment by star7th** [comment]
@zhyzhyzhy @youlinux 

已经更新，请下载最新代码

**Comment by youlinux** [comment]
非常感谢🙏，可以了

**Comment by zhyzhyzhy** [comment]
nice~

**Comment by 457581449** [comment]
我这边也是遇到这个问题，刚试了下重新Git新的代码就好了，但是我之前的上边有项目啊，怎么迁移过来呢，我没安装多久，没用mysql，按之前的迁移教程不行

**Comment by star7th** [comment]
参考https://www.showdoc.cc/help?page_id=13732 的升级安装部分

**Comment by 457581449** [comment]
我这边看了下
Sqlite/sqlite.db.php（我这边没有这个文件）
还有就是这个错误是什么？
_STORAGE_WRITE_ERROR_:./Application/Runtime/Cache/Home/00569fd500a04baa59c34655677c3e9d.php
错误位置

FILE: /var/www/html/showdoc/ThinkPHP/Library/Think/Storage/Driver/File.class.php 　LINE: 48
TRACE

#0 /var/www/html/showdoc/ThinkPHP/Library/Think/Storage/Driver/File.class.php(48): E('_STORAGE_WRITE_...')
#1 [internal function]: Think\Storage\Driver\File->put('./Application/R...', ' #2 /var/www/html/showdoc/ThinkPHP/Library/Think/Storage.class.php(37): call_user_func_array(Array, Array)
#3 /var/www/html/showdoc/ThinkPHP/Library/Think/Template.class.php(114): Think\Storage::__callstatic('put', Array)
#4 /var/www/html/showdoc/ThinkPHP/Library/Think/Template.class.php(114): Think\Storage::put('./Application/R...', ' #5 /var/www/html/showdoc/ThinkPHP/Library/Think/Template.class.php(76): Think\Template->loadTemplate('./Application/H...', '')
#6 /var/www/html/showdoc/ThinkPHP/Library/Behavior/ParseTemplateBehavior.class.php(32): Think\Template->fetch('./Application/H...', Array, '')
#7 /var/www/html/showdoc/ThinkPHP/Library/Think/Hook.class.php(119): Behavior\ParseTemplateBehavior->run(Array)
#8 /var/www/html/showdoc/ThinkPHP/Library/Think/Hook.class.php(89): Think\Hook::exec('Behavior\ParseT...', 'view_parse', Array)
#9 /var/www/html/showdoc/ThinkPHP/Library/Think/View.class.php(126): Think\Hook::listen('view_parse', Array)
#10 /var/www/html/showdoc/ThinkPHP/Library/Think/View.class.php(72): Think\View->fetch('show_regular', '', '')
#11 /var/www/html/showdoc/ThinkPHP/Library/Think/Controller.class.php(56): Think\View->display('show_regular', '', '', '', '')
#12 /var/www/html/showdoc/Application/Home/Controller/ItemController.class.php(245): Think\Controller->display('show_regular')
#13 /var/www/html/showdoc/Application/Home/Controller/ItemController.class.php(169): Home\Controller\ItemController->_show_regular_item(Array)
#14 [internal function]: Home\Controller\ItemController->show()
#15 /var/www/html/showdoc/ThinkPHP/Library/Think/App.class.php(173): ReflectionMethod->invoke(Object(Home\Controller\ItemController))
#16 /var/www/html/showdoc/ThinkPHP/Library/Think/App.class.php(110): Think\App::invokeAction(Object(Home\Controller\ItemController), 'show')
#17 /var/www/html/showdoc/ThinkPHP/Library/Think/App.class.php(204): Think\App::exec()
#18 /var/www/html/showdoc/ThinkPHP/Library/Think/Think.class.php(120): Think\App::run()
#19 /var/www/html/showdoc/ThinkPHP/ThinkPHP.php(97): Think\Think::start()
#20 /var/www/html/showdoc/index.php(24): require('/var/www/html/s...')
#21 {main}

**Comment by 457581449** [comment]
“将Sqlite/sqlite.db.php（这是原来的数据库文件）”
我看了下我备份的里边没有这个文件（sqlite.db.php），我试了下最新代码，创建项目，也没有这个文件。那么还怎么迁移项目数据呢？

**Comment by star7th** [comment]
showdoc安装目录下的Sqlite/sqlite.db.php，百分比肯定有这个文件，你找找。

**Comment by star7th** [comment]
噢，文件名是叫showdoc.db.php @457581449

**Comment by 457581449** [comment]
有showdoc.db.php，但是我复制到新的代码目录里后，再以原来的账号登录不进去的

**Comment by star7th** [comment]
尝试给整个目录可写权限

**Comment by 457581449** [comment]
我试过了，整个目录权限777，依然不行。
