### ISSUE TITLE
有个疑问

### ISSUE THREAD

**Issue by chutianjun** [star7th/showdoc#1683]
![image](https://user-images.githubusercontent.com/11752050/165881903-0dcf5a7c-d41a-4a5d-abcc-b2cd2a0289c8.png)
我直接从复制浏览器的url,到文档中,就会变成一串文字
但是如果是从比如sublime复制过来,就是正常的url
我记得以前是可以直接复制url过来的

**Comment by star7th** [comment]
什么浏览器

**Comment by chutianjun** [comment]
哦,好像chrome,360是正常的,edge就会变成一段文字,那这么看可能是浏览器的原因
