### ISSUE TITLE
建议：能否多人协同工作？

### ISSUE THREAD

**Issue by Musicminion** [star7th/showdoc#1684]
感觉一个文档在多人同时打开的时候，别人做的修改我自己是不能同步看到的hhhh
要刷新一下才能看到，不知道是不是我的部署的问题还是什么，，

**Comment by star7th** [comment]
不支持同步。就是要手动刷新一下。

**Comment by asdio** [comment]
这个特性非常有用！希望能支持下。

**Comment by star7th** [comment]
多人实时同步编辑、比你们想象中的要难。这个东西的开发成本很高。哪怕你给showdoc赞助个50万，我也不能保证把事情做好。就先不考虑了。如果你真的愿意赞助50万，我们再开这个话题讨论吧。
