### ISSUE TITLE
RunApi客户端希望支持接口返回图片的显示

### ISSUE THREAD

**Issue by feihongxiansen** [star7th/showdoc#1685]
虽说大部分时间是用来测试json数据的接口，但有时候需要测试一些其他接口，比如返回验证码图片的，结果图片被显示成乱码，希望支持显示图片类型的数据
![image](https://user-images.githubusercontent.com/26507155/165883265-654589ce-975a-48c2-8f2d-842970b26e35.png)

**Comment by star7th** [comment]
后面找时间看下。当前你可以这样解决——在发送按钮，下拉，选择发送并下载

**Comment by feihongxiansen** [comment]
> 

好的，感谢
