### ISSUE TITLE
当无序列表和行内代码块一起使用时，效果需要优化

### ISSUE THREAD

**Issue by wynn5a** [star7th/showdoc#1687]
markdown 内容如下：

```

- 接口协议: `HTTP`
- 请求方法: `POST`
- 接口地址: `/login`
- 请求内容格式:  `JSON`

```
渲染效果如下：

<img width="312" alt="image" src="https://user-images.githubusercontent.com/3407317/165899787-343c5b23-2d39-43d0-9bee-e2abd1af63a1.png">

感觉需要优化一下， 代码块样式太宽了

github 的效果

- 接口协议: `HTTP`
- 请求方法: `POST`
- 接口地址: `/login`
- 请求内容格式:  `JSON`

**Comment by wynn5a** [comment]
一样会覆盖到上面的

<img width="296" alt="image" src="https://user-images.githubusercontent.com/3407317/165919459-ecff3881-7dfd-4e28-85d1-2853c42bdd56.png">

**Comment by star7th** [comment]
这种情况感觉还是用得少。就不专门为此优化了。建议你不在这里使用代码块，可以加粗

```


- 接口协议: **HTTP**
- 请求方法: **POST**
- 接口地址: **/login**
- 请求内容格式:  **JSON**


```

**Comment by wynn5a** [comment]
👌🏻

可以接受
