### ISSUE TITLE
showdoc如何对接oauth服务或第三方的认证服务？

### ISSUE THREAD

**Issue by nanhai-gvsun** [star7th/showdoc#1688]
公司有搭建自有的认证微服务，全兼容oauth2，showdoc中如何支持第三方的权限认证服务？

**Comment by star7th** [comment]
新安装完成后，默认管理员账号是showdoc/123456 。使用管理员帐户登录后，在项目列表页面的右上角便能看到管理后台入口。管理后台处可看到集成登录——oauth2

**Comment by Musicminion** [comment]
想问一下oauth2 用户信息的json返回结果，有的可能是user，有的可能是name，有的可能是username
好奇一下代码段里面对应这个json识别用户名的变量在哪里

**Comment by star7th** [comment]
> 想问一下oauth2 用户信息的json返回结果，有的可能是user，有的可能是name，有的可能是username 好奇一下代码段里面对应这个json识别用户名的变量在哪里

https://github.com/star7th/showdoc/blob/2d52caa869b64223046dd16bf218bfdddcf94d3a/server/Application/Api/Controller/ExtLoginController.class.php#L148
