### ISSUE TITLE
私有项目，没登录点链接也能看到

### ISSUE THREAD

**Issue by ZuiSong** [star7th/showdoc#169]
我建了一个私有项目，把链接复制下来，在其他没有登录的电脑上点进链接，没有登录居然能看到，这个按道理应该是先跳登录，登录后判断是否有权限才能看到的吧

**Comment by star7th** [comment]
如果能看到的话证明你建立的不是私有项目。私有项目请设置密码。

**Comment by ZuiSong** [comment]
检查后发现的确是没设置密码，谢谢回复
