### ISSUE TITLE
markdown编辑器里面ifream等HTML标签不能识别的问题

### ISSUE THREAD

**Issue by Musicminion** [star7th/showdoc#1690]
不知道作者可不可以在管理员端开启一个功能，对html的标签进行一个过滤，这样可以根据需求来开启部分标签hhh（单纯建议）
然后还想问一下管理员账户如何新建一个？直接改数据库嘛2333

- 写在这里给需要的人用一下！~~毕竟有些人动手能力强就是喜欢捣鼓各种功能，但是遇到了问题也很麻烦要到处找解决方法~~
- 毕竟，开启iframe可以带来极大的方便，用户可以嵌入更多的个性化的东西，**但是也会有很大的风险！使用前您必须谨慎！**

详情请参考这里：http://editor.md.ipandao.com/examples/html-tags-decode.html
可以看到，开启之后的效果，里面的内容可以运行脚本，把整个页面变红！！！

- 详细开启过程
- 定位到如下的文件（以我的安装目录为例子）
![image](https://user-images.githubusercontent.com/84625273/166094039-9bb966c0-c607-4411-b9f7-cba5897b508d.png)

- 找到这一行 关键字检索：`style,script,iframe`
- 把 `htmlDecode: 'style,script,iframe|filterXSS',` 修改成   `htmlDecode :"style,script,iframe,sub,sup|on*`
![image](https://user-images.githubusercontent.com/84625273/166094256-f2baa4e8-522e-435d-9aeb-a51e86cfad50.png)

- `npm run build` 即可更新！

**Comment by Musicminion** [comment]
> 

你好，请cd到web_src目录
然后执行npm run build

web_src目录是作者的前端代码的文件夹，执行npm run build就好，发布生成的文件是在web文件夹里面！

**Comment by Musicminion** [comment]
> 答主感谢你这分享。不过我是小白，只找到对应文件修改了内容，但是不会npm run build发布。你可以把发布生成的内容发我一下吗？（我是使用php安装的开源版，是不是我使用你发布的文件替换原有的文件就能开启iframe解析。）

![image](https://user-images.githubusercontent.com/84625273/175944714-07a9774f-3c20-459a-87f4-b0cb118c8217.png)

**Comment by star7th** [comment]
你可以自行修改，但官方不会开放这样的设置。

Musicminion ***@***.***>于2022年4月30日 周六下午2:22写道：
