### ISSUE TITLE
用户恶意访问管理端

### ISSUE THREAD

**Issue by Musicminion** [star7th/showdoc#1692]
在用户恶意访问的情况下：（普通用户权限）例如您的官网，https://www.showdoc.com.cn/admin/index

这个页面可以进行删除操作（当然我没有操作）
![image](https://user-images.githubusercontent.com/84625273/166131469-63313136-6a36-48fa-ae83-064ddc0b4072.png)

在开源的这个版本中，好像还能看到用户的用户名各种数据？哦不，刚刚测试了，并不可以，只能新增用户。

但是还是感觉管理端最好加一个权限鉴定？权限不足直接重定向个人的主页，而不是在管理端停留甚至渲染管理端的页面？

**Comment by star7th** [comment]
其实你删除不了。因为所有写入的数据，我在后台都是做管理权限检验的。前端只能看只读数据。而且也只是这个页面看得到只读数据，其他看不到。

Musicminion ***@***.***>于2022年5月1日 周日上午11:53写道：

**Comment by star7th** [comment]
而且首页推荐 这个菜单下都是汇集一些公开项目，本来就是可公开的，所以不算越权访问吧。后端限制你不能删除就好了
