### ISSUE TITLE
登录成功后是不是应该把之前错误的登陆的次数清零一下？

### ISSUE THREAD

**Issue by Musicminion** [star7th/showdoc#1693]
- 感觉只要一次密码输入错误，后面的所有的都要重新输入验证码

- 建议直接改成每次都要验证码（like官网）
- 或者好像要写一个清0函数？（我测试了一下好像可以了）

**Comment by star7th** [comment]
没有必要。真实用户不会频繁登录。

Musicminion ***@***.***>于2022年5月1日 周日下午12:51写道：
