### ISSUE TITLE
API Privilege Vulnerability

### ISSUE THREAD

**Issue by Vu1ner** [star7th/showdoc#1694]
After the user is registered, access the api interface to obtain all user accounts in the system
(Note that non-administrators can access data on this interface)
url:/server/index.php?s=/api/user/allUser

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/47616650/166868823-bcc32240-5a25-4345-a594-183022537ebc.png">

**Comment by star7th** [comment]
This is the design. The usage scenario of this interface is: when users want to add collaboration members in the project, they will be filtered from the user names of users in the whole site

**Comment by star7th** [comment]
Just uid and username，I think it's controllable.I think convenience is more important.

**Comment by star7th** [comment]
If you think this is a serious problem, please try to provide an example of attack recurrence
