### ISSUE TITLE
runapi 文档拖动更换目录 文档发生卡顿

### ISSUE THREAD

**Issue by liubaolong** [star7th/showdoc#1695]
runapi 文档拖动更换目录  更换过去文档，无法正常展示，刷新之后，文档回到之前目录，多次拖动项目直接卡没了，需要多次登录，或者重启服务器才能正常展示

**Comment by star7th** [comment]
这个问题我重现不了。如果要我解决的话，得先想办法重现才行。你有时间的话可以链接官网服务器https://www.showdoc.com.cn/ 然后做一个可重现例子，然后分享链接给我看看

**Comment by liubaolong** [comment]
这个是一个卡顿的问题，卡一会就好了，没法分享
![微信图片_20220506094028](https://user-images.githubusercontent.com/31124727/167052981-d42f97b0-88c9-482e-b275-1ab3b350342b.png)
![微信图片_20220506094109](https://user-images.githubusercontent.com/31124727/167052987-69f68f77-94f2-46a5-8f86-0b1ed887ebcd.png)

**Comment by liubaolong** [comment]
当我更换文档目录就卡了，如果拖动的多，整个项目短时间都不展示了

**Comment by star7th** [comment]
看你的目录也不少，移动的话确实会产生一些网络请求。如果你的服务器带宽慢的话是会卡的。
