### ISSUE TITLE
无法下载附件 excel word

### ISSUE THREAD

**Issue by zhaofy2323** [star7th/showdoc#1696]
docker一键部署了项目

浏览器是chrome 版本 100.0.4896.127（正式版本）
附件下载图片可以，但是excel点击后跳出一个页面然后秒关

**Comment by star7th** [comment]
这个可能是后面引入的兼容问题。有时间再改一下

**Comment by zhaofy2323** [comment]
@star7th 好的谢谢您，您更新后我再升级一下项目，非常感谢！

**Comment by star7th** [comment]
新版已修复此问题

**Comment by zhaofy2323** [comment]
@star7th 
谢谢您，请问一下附件需要重新上传吗？升级后点击下载附件还是这样。
![20220623104718](https://user-images.githubusercontent.com/17792187/175196353-3d0c7430-28a2-48e7-bee8-62fa761a7fd3.png)

**Comment by star7th** [comment]
不清楚你这个是什么情况。你先试着新上传一个附件，然后再看是不是所有历史附件都是你上图那样子。

**Comment by zhaofy2323** [comment]
@star7th 
现在上传好像也出现问题了= =
![image](https://user-images.githubusercontent.com/17792187/175198355-653c68b0-173d-4e40-9125-80bc3d045f03.png)

**Comment by star7th** [comment]
你怎么升级的

**Comment by zhaofy2323** [comment]
@star7th  ./showdoc update

**Comment by zhaofy2323** [comment]
![image](https://user-images.githubusercontent.com/17792187/175199458-5e16131a-6a51-4a3a-9b40-85f6543b3126.png)

**Comment by star7th** [comment]
是上传所有文件都出错吗？要给挂在的目录 /showdoc_data 以递归777权限

**Comment by zhaofy2323** [comment]
@star7th 
升级之前应该上传是好的，升级之后上传附件报错了，刚刚试了一下图片也报错了。
权限是有的
![image](https://user-images.githubusercontent.com/17792187/175199897-ac9973d1-771c-42fe-9c02-e8aa504bf318.png)

**Comment by zhaofy2323** [comment]
@star7th https://showdoc.steelhome.cn/web/#/

**Comment by star7th** [comment]
我打不开这个地址。确保外网可访问。 
另外，绑定域名要按照教程来 https://www.showdoc.com.cn/help/7240953917068087

**Comment by zhaofy2323** [comment]
@star7th  很奇怪。。。突然好了，文件能上传也可以下载了。。。有可能是我随手给了 showdoc_data 递归777权限了，非常感谢您。
