### ISSUE TITLE
OAuth2 集成Github登录，显示“登录成功但无法获取用户信息”

### ISSUE THREAD

**Issue by yinshangwei** [star7th/showdoc#1697]
![image](https://user-images.githubusercontent.com/20291587/167073289-f1b778cc-c9f7-433f-b0be-73054dc7bef3.png)

**Comment by star7th** [comment]
https://github.com/star7th/showdoc/issues/1481

**Comment by yinshangwei** [comment]
> #1481

不一样，这个是Github，错误也不一样。

**Comment by star7th** [comment]
github获取用户信息的接口是对的吗，返回的格式，你找一下文档看对不对

**Comment by star7th** [comment]
我自己没有去测试。但showdoc接入的，应该符合标准oauth2协议

**Comment by yinshangwei** [comment]
> github获取用户信息的接口是对的吗，返回的格式，你找一下文档看对不对

是对的，你可以测试一下，主需要花2分钟就可以测出来。
文档：
https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps

**Comment by star7th** [comment]
好像文档里，github https://api.github.com/user 是需要把认证参数放到header里去的。而showdoc请求接口的时候是使用get传递参数的。我不明白为啥github只支持这种写headre方式，其他认证服务器都没问题。或者，是否存在别的接口是支持get参数方式的。

**Comment by yinshangwei** [comment]
> 好像文档里，github https://api.github.com/user 是需要把认证参数放到header里去的。而showdoc请求接口的时候是使用get传递参数的。我不明白为啥github只支持这种写headre方式，其他认证服务器都没问题。或者，是否存在别的接口是支持get参数方式的。

应该是这个问题，能否增加一个传Header的方式？

**Comment by star7th** [comment]
后面有时间再加一下。

**Comment by leo220yuyaodog** [comment]
你好，请问Linux上使用自动安装脚本安装的是修复后的最新版本吗？我仍然遇到了同样的问题

> 新版已经修复此问题

**Comment by star7th** [comment]
是最新版

**Comment by leo220yuyaodog** [comment]
翻了下commit, 没有找到关于这个问题的修复。能确认下修复了吗？项目想集成docshow, 配置oauth2登录后，也是返回“登录成功无法返回用户信息"的错误。
具体见 ：https://github.com/casdoor/casdoor/issues/874

**Comment by star7th** [comment]
@leo220yuyaodog   casdoor获取用户info的路径是 /api/get-account 。另外我确认代码更新上来了。看这个 https://github.com/star7th/showdoc/blob/master/server/Application/Api/Controller/ExtLoginController.class.php#L140

**Comment by leo220yuyaodog** [comment]
> @leo220yuyaodog casdoor获取用户info的路径是 /api/get-account 。另外我确认代码更新上来了。看这个 https://github.com/star7th/showdoc/blob/master/server/Application/Api/Controller/ExtLoginController.class.php#L140

非常感谢，修改为/api/get-account后可以成功使用oauth2登录了

**Comment by seahurt** [comment]
gitlab也出现这个问题了. 

用户信息path用的是`/oauth/userinfo`

**Comment by seahurt** [comment]
> gitlab也出现这个问题了.
> 
> 用户信息path用的是`/oauth/userinfo`

好吧，gitlab官方文档真是太误导人了。
我从一个开源的代码库里找到了解决方法: 使用`/api/v4/user`作为path就可以解决拿到gitlab的用户信息了

参考: https://github.com/tarent/loginsrv/blob/master/oauth2/gitlab.go
