### ISSUE TITLE
表格文档页面浏览器搜索不能使用

### ISSUE THREAD

**Issue by sdial** [star7th/showdoc#1698]
## 表格文档页面浏览器搜索不能使用
如下图，使用CHROME浏览器打开表格页面，CTRL+F调出搜索，文档里的文字（北京的北）搜索不到
![Z`BYE$7HK`IAK5ASPL{_@6X](https://user-images.githubusercontent.com/18243690/167110248-fcf02b76-330f-44fb-8280-49914eddc343.jpg)

**Comment by star7th** [comment]
showdoc的表格是集成了这个开源组件。它不支持的话我没有太好的办法，二次开发不是很容易 https://github.com/myliang/x-spreadsheet
