### ISSUE TITLE
修改项目访问密码的时候一直pending，然后超时报错

### ISSUE THREAD

**Issue by liuzongyang255** [star7th/showdoc#1699]
版本：v2.10.5
![image](https://user-images.githubusercontent.com/54257047/167280830-354de905-58a5-4517-9c78-78a28d62bc9d.png)

![image](https://user-images.githubusercontent.com/54257047/167280800-9912126b-0679-4e28-a893-3a5e96421a74.png)

![image](https://user-images.githubusercontent.com/54257047/167280807-90826581-d295-401f-8922-cae197cdbc1a.png)

**Comment by star7th** [comment]
新建项目正常吗

**Comment by liuzongyang255** [comment]
恢复了，难道是网络问题
