### ISSUE TITLE
无法启动，显示_STORAGE_WRITE_ERROR_ 错误

### ISSUE THREAD

**Issue by kecoder** [star7th/showdoc#170]
昨天还正常运行。检查了文件夹权限，没问题。就是不知道为何会出现这个情况。

![2017-08-24_175753](https://user-images.githubusercontent.com/8684390/30742013-e6fabd5e-9fc9-11e7-8093-f23d25fbc19c.jpg)

**Comment by star7th** [comment]
是因为Application/Runtime/目录写不进去。至于为什么写不了，这个得自己看了。权限有没有，磁盘满了没，安全设置是不是限制了

**Comment by kecoder** [comment]
权限已经777了，磁盘df -h看过了，没有满。而且昨天之前都是可以正常使用的，突然变成这样，不知道为什么。

**Comment by star7th** [comment]
我只能肯定是服务器变动了。至于发生了什么变动，这就不知道了。你试着手动清空Application/Runtime/目录

**Comment by kecoder** [comment]
试过了，直接报错 “目录 [ ./Application/Runtime/ ] 不可写！” 。
请问数据是存在什么地方的？实在不行我重新安装，再导入数据。

**Comment by star7th** [comment]
Sqlite目录

**Comment by kecoder** [comment]
showdoc.db.php 这个文件是么？Sqlite目录下只有这一个文件。

**Comment by star7th** [comment]
是的

**Comment by kecoder** [comment]
多谢，我试一下看看。

**Comment by kecoder** [comment]
文件解决。原因是服务器意外关机，再次启动的时候，selinux 阻止了Application/Runtime目录的写权限。
解决方法：禁用selinux + 清空Application/Runtime/下的所有文件。

多谢帮忙。@star7th
