### ISSUE TITLE
导出导入导致图片找不到的问题·

### ISSUE THREAD

**Issue by asdf3309** [star7th/showdoc#1701]
老的好像是直接用public路径作为页面图片的，这样吧upload复制之后页面导入一次就可以的。
但是新的模式下，好像是用一个接口来获取图片，增加了图片的管理？
这样导致我导出再导入就没有图片了，表里没记录。

因为我安装了多个showdoc，并且是不同版本，需要合并，现在尴尬了，图片么了。

**Comment by asdf3309** [comment]
好像也不能说没了，只是比较麻烦，需要把文件中的路径找到，然后去表里拿到实际的路径进行替换。
希望后面能考虑下导出的时候图片怎么处理

**Comment by star7th** [comment]
目前不打算考虑处理图片，因为图片可大可小。比如上G大小的图片不可能导出得了

**Comment by liuzongyang255** [comment]
添加个上传大小限制怎么样？比如一张图片最大10M？

**Comment by star7th** [comment]
限制文件上传大小没什么用。比如说一个项目里可以有很多张图片。单张大小确实不超过10M 。
实际上，单个项目导出如果10M以上都挺有可能出错的，并且瞬时占用的内存巨高。不打算开这个坑。

**Comment by star7th** [comment]
导出的只是纯文本。图片只是导出url。不提供附件迁移功能

dim ***@***.***> 于2022年5月10日周二 20:04写道：
