### ISSUE TITLE
建议文章标题下新增修改时间、作者

### ISSUE THREAD

**Issue by liuzongyang255** [star7th/showdoc#1702]
有时候文章作者很重要，在修改记录里去翻着不方便

![image](https://user-images.githubusercontent.com/54257047/167782330-a77c4ca8-d77c-48b7-81fe-b642ab04366e.png)

**Comment by star7th** [comment]
但这也只是“有时候”重要。大部分时候是不必要的。所以我觉得没有必要强制放出来占视线

**Comment by liuzongyang255** [comment]
可以加给配置吗

**Comment by star7th** [comment]
太少用了，不会专门为此抽象出一个配置项

**Comment by liuzongyang255** [comment]
其实加起看起会更正式点，逼格一下就上去了，要不考虑一下？
![image](https://user-images.githubusercontent.com/54257047/167786627-17df161d-e60a-43c7-ab62-30cf8afe511a.png)

**Comment by star7th** [comment]
太少用到了。请你证明这个功能会被常用到。

**Comment by liuzongyang255** [comment]
当一个人用一个项目的时候，确实没必要，
当一个项目人比较多的时候(3个人以上？)，人人都上去写，需要找到作者是谁，有疑问可以直接找到人去问，类似于git代码日志一样
另外，接口反正已经返了字段的，放上去一下吧~~
![image](https://user-images.githubusercontent.com/54257047/167788448-232b1e6d-7863-4193-9aa3-0f0e5cbd05f6.png)

**Comment by star7th** [comment]
有三种方法可以看到作者：
点击详情按钮；点击历史版本按钮；点击项目变更日志按钮。
这个需求点两下就能解决。不打算放出来占用视觉空间。

**Comment by liuzongyang255** [comment]
好吧
