### ISSUE TITLE
不支持 exe 的附件上传？限制了哪些 文件类型

### ISSUE THREAD

**Issue by hellolgml** [star7th/showdoc#1706]
![image](https://user-images.githubusercontent.com/23045371/169756303-0e4ebb0f-f49f-4dec-898b-897243ce530e.png)

**Comment by star7th** [comment]
https://github.com/star7th/showdoc/blob/master/server/Application/Api/Model/AttachmentModel.class.php#L333

**Comment by star7th** [comment]
只允许代码里的这些域名

**Comment by hellolgml** [comment]
好的吧，谢谢

**Comment by Clpy** [comment]
能增加文件类型吗？sql一类的也需要上传

**Comment by star7th** [comment]
我的建议是把它压缩成zip压缩包然后上传。目前不打算放开文件类型限制，为了安全。
