### ISSUE TITLE
视频文件 加载 有点慢了，超过10秒 才能加载出来

### ISSUE THREAD

**Issue by hellolgml** [star7th/showdoc#1707]
视频文件 加载 有点慢了，超过10秒 才能加载出来，才可以获取预览帧、点击播放

**Comment by star7th** [comment]
这个跟showdoc无关，跟视频源所在的服务器有关。如果你是把视频上传到showdoc的，那就是你的服务器问题，比如说带宽太低。

**Comment by hellolgml** [comment]
本地局域网的刀片机服务器，感觉应该也没那么慢吧

**Comment by star7th** [comment]
视频源在哪，多大的文件

**Comment by star7th** [comment]
直接浏览器下载该文件，速度能有多少

**Comment by hellolgml** [comment]
视频源 在showdoc 附件，以附件形式上传的
浏览器下载的话：8Mb/s 的速率，文件100M

**Comment by star7th** [comment]
showdoc的视频是以纯html的形式插入的，它的播放速度取决于你浏览器和服务器加载的速度，就跟你在一个网页html插入视频一样，showdoc完全没有经过二次处理。

**Comment by hellolgml** [comment]
嗯嗯，好吧，谢谢
