### ISSUE TITLE
希望可以支持runapi生成的接口文档导出

### ISSUE THREAD

**Issue by jinyidong** [star7th/showdoc#1708]
目前runapi生成的接口文档不能导出，希望开发相关功能

**Comment by star7th** [comment]
runapi项目在runapi编辑和导出

**Comment by jinyidong** [comment]
markdown导出

**Comment by star7th** [comment]
runapi项目的底层存储格式不是markdown,无法导入导出markdown包。

**Comment by brizer** [comment]
只能导出成word吗？json不行吗？

**Comment by FGadvancer** [comment]
https://github.com/FGadvancer/ruapi-generate-md
