### ISSUE TITLE
使用runapi提示版本过低

### ISSUE THREAD

**Issue by zddghost** [star7th/showdoc#1709]
提示:runapi该功能要求showdoc服务端版本在v2.9.14以上，你当前使用的showdoc服务端版本v2.9.6已滞后,
但是我的showdoc已经是高版本了!
使用的是docker star7th/showdoc:v2.9.6

**Comment by star7th** [comment]
真的好无语。你都知道你使用的是docker star7th/showdoc:v2.9.6 ，难道标签v2.9.6 说得不够清楚吗，这是版本v2.9.6 。而runapi要求v2.9.14以上 。
你别啥折腾了，赶紧用latest 标签，按教程操作 https://www.showdoc.com.cn/help/65610
