### ISSUE TITLE
发现一个小问题：项目设置个性域名展示有误

### ISSUE THREAD

**Issue by zhixinglvren** [star7th/showdoc#171]
这是我设置的个性域名：https://www.showdoc.cc/RunApiDoc

在项目设置的时候，个性域名表单框内的内容展示的是我的注册邮箱，而不是RunApiDoc

**Comment by star7th** [comment]
没发现问题，可正常访问

**Comment by zhixinglvren** [comment]
![default](https://user-images.githubusercontent.com/25925339/30892403-23157e1a-a36b-11e7-99c6-3e7b42330521.png)

**Comment by star7th** [comment]
其实是你的浏览器误以为这是登录框而自动填充账号和密码。

**Comment by star7th** [comment]
我看看有没有办法规避浏览器的自动填充

**Comment by star7th** [comment]
已经限制了浏览器的自动填充。现在应该显示正常了

**Comment by zhixinglvren** [comment]
嗯嗯，清除浏览器缓存之后，就好了。

![default](https://user-images.githubusercontent.com/25925339/30893322-17f2ebe4-a370-11e7-8c31-b3b2ca580edf.PNG)
