### ISSUE TITLE
SQL Injection at 'member_username' parameter

### ISSUE THREAD

**Issue by haxpunk1337** [star7th/showdoc#1710]
Hello Team,

Software Link: https://github.com/star7th/showdoc/releases/tag/v2.10.5
Version: <= 2.10.5

Description:
Manipulating value of member_username parameter to %00  trows SQL exception

Steps to generate:
 
raw request

```
POST /server/index.php?s=/api/teamMember/save HTTP/2
Host: localhost
Content-Type: application/x-www-form-urlencoded;charset=UTF-8
Cookie: PHPSESSID=TOKEN; think_language=en-US; cookie_token=TOKEN
Content-Length: 54

team_id=121&member_username=%00&team_member_group_id=1
```

Here manipulating value of 'member_username' value as %00 THROWS SQL ERRORS

Response

{"error_code":999,"error_message":"SQLSTATE[HY000]: General error: 1
![SQL1](https://user-images.githubusercontent.com/92354410/170549992-509d9a91-651b-428f-967c-fad448702651.png)

Thank You

**Comment by star7th** [comment]
Is there any harm in this? If only errors occur, which will not lead to SQL execution and data exposure, I think this problem may not be serious.
If you say this will expose the path of the program, it doesn't matter. It's programming itself. In order to facilitate debugging, I have opened error prompts by default. Moreover, running in docker, the exposed path is not serious.

**Comment by haxpunk1337** [comment]
hello team,

sometimes QL statements also exposed (WHERE CLAUSE)  at #1711

**Comment by star7th** [comment]
Showdoc is an open source software. SQL itself can be seen in the source code. For malicious interfaces, there is no difference between whether the information is displayed or not.

**Comment by star7th** [comment]
My concern is whether he can obtain data and access other people's data beyond his authority

**Comment by haxpunk1337** [comment]
here exposing path is not an issue

here sql Server error is reflectimg which seems to indicate a vulnerability.
and also exposing HY000 ( MySQL ODBC extension) . here attacker can  penetrate the application and reach the SQL query itself, by injecting hazardous characters.

Here where statement was exposed , i.e attacker can craft sql payload can can retrieve Crifical Information

**Comment by star7th** [comment]
"here attacker can penetrate the application and reach the SQL query itself, by injecting hazardous characters."
Can you provide an example of hazardous characters? Because I really don't know how to be used. I personally feel that attackers can't take advantage of this
