### ISSUE TITLE
SQL injection at 'team_name' parameter

### ISSUE THREAD

**Issue by haxpunk1337** [star7th/showdoc#1711]
Hello Team,

Software Link: https://github.com/star7th/showdoc/releases/tag/v2.10.5
Version: <= 2.10.5

Description:
Manipulating parameter name team_name to team_name%5B%5D  throws SQL exception

Steps to generate:

raw request

```
POST /server/index.php?s=/api/team/save HTTP/2
Host: localhost
Content-Type: application/x-www-form-urlencoded;charset=UTF-8
Cookie: PHPSESSID=<SESSION_COOKIE>; think_language=en-US; cookie_token=<TOKEN>
Content-Length: 24

id=121&team_name%5B%5D=S
```

![SQL 2](https://user-images.githubusercontent.com/92354410/170552641-10fc6293-8699-41d6-b64e-dab73f3a98b9.png)

Thank You

**Comment by star7th** [comment]
https://github.com/star7th/showdoc/issues/1710
