### ISSUE TITLE
SQL injection at 'username' parameter

### ISSUE THREAD

**Issue by haxpunk1337** [star7th/showdoc#1712]
Hello Team,

Software Link: https://github.com/star7th/showdoc/releases/tag/v2.10.5
Version: <= 2.10.5

Description:
Manipulating value of username parameter to %00 throws SQL exception

Steps to generate:

raw request

```
POST /server/index.php?s=/api/adminItem/attorn HTTP/2
Host: localhost
Content-Type: application/x-www-form-urlencoded;charset=UTF-8
Cookie: PHPSESSID=<cookie>; think_language=en-US; cookie_token=<token>
Content-Length: 24

item_id=164&username=%00
```

![SQL 3](https://user-images.githubusercontent.com/92354410/170553784-53ebca27-1fff-4df5-97ea-8587d3d18145.png)
Thank You

**Comment by star7th** [comment]
https://github.com/star7th/showdoc/issues/1710
