### ISSUE TITLE
调试接口时，点击发送无反应

### ISSUE THREAD

**Issue by anlondon** [star7th/showdoc#1713]
最近在调试接口时，点击[发送]按钮总是没反应;
选择[发送并下载]，则提示[您的网络发生异常，无法连接服务器]

请问该怎么解决这个问题？
win10 21H2
runapi 1.0.3.0

另外该怎么导出接口文档呢？

**Comment by star7th** [comment]
有没有一种可能，真的是你的网络异常，无法连接服务器呢？
如果你想用排除法证明此问题，只需要用官网服务器试一下，包括接口也是调试官网的，看看还会不会有异常

anlondon ***@***.***>于2022年5月31日 周二上午9:39写道：

**Comment by anlondon** [comment]
> 
我又测试了下，我想可能并非是网络问题

![图片](https://user-images.githubusercontent.com/34559111/171077685-9d9e129a-cd91-4bce-9312-13459ea118c3.png)
![图片](https://user-images.githubusercontent.com/34559111/171077833-1ea6ee21-16c2-47f7-acb5-5a0f90965a39.png)
![图片](https://user-images.githubusercontent.com/34559111/171077916-2aed2185-1268-408f-9e2f-6a75742039a3.png)
![图片](https://user-images.githubusercontent.com/34559111/171078005-a55fcfe4-caa5-4401-8d38-a4fa1bbded76.png)

这个问题在最近这段时间一直出现，我怀疑是否为客户端版本过低导致的？

**Comment by star7th** [comment]
那我大概能猜到原因了。你配置环境变量的时候估计多了一些空格，导致最后拼接的url非法。在最新版showdoc里，如果再新增环境变量则自动去掉前后空格了

**Comment by star7th** [comment]
如果要更新客户端，到这个页面重下载安装即可 https://www.showdoc.com.cn/runapi

**Comment by anlondon** [comment]
> 那我大概能猜到原因了。你配置环境变量的时候估计多了一些空格，导致最后拼接的url非法。在最新版showdoc里，如果再新增环境变量则自动去掉前后空格了

emmmmm,或许不是这个原因
![图片](https://user-images.githubusercontent.com/34559111/171079143-f55c9752-b59a-4faf-82f9-2417f816114e.png)
![图片](https://user-images.githubusercontent.com/34559111/171079191-3a3c1941-54a3-400c-8d40-787266d47259.png)

不过我更新了客户端后，没有出现这个问题了

感谢
