### ISSUE TITLE
IE浏览器下载文件，文件名乱码

### ISSUE THREAD

**Issue by bigtiger-qian** [star7th/showdoc#1717]
Hi
在IE浏览器下，其他功能都正常，但下载文件时文件名变为乱码
![WechatIMG608](https://user-images.githubusercontent.com/45592375/172105224-048b0672-852b-4ba1-83a2-eb297634cb8c.png)
似乎是编码问题？

**Comment by star7th** [comment]
不承诺完全支持IE浏览器，能大部分兼容就好。IE浏览器即将被淘汰，不值得再去测试再去维护
