### ISSUE TITLE
docker版本的showdoc 什么时候升级到 2.9.14 以上

### ISSUE THREAD

**Issue by zddghost** [star7th/showdoc#1719]
目前使用的是docker版本的showdoc

**Comment by star7th** [comment]
docker镜像一直都是最新的。我觉得你应该是没升级对。按照这个教程更新
https://www.showdoc.com.cn/help/65610

do_you_like_van_游戏 ***@***.***>于2022年6月8日 周三下午2:24写道：

**Comment by ccimage** [comment]
docker hub里的镜像确实只有2.9.5  不过装好后可以自动更新

**Comment by zddghost** [comment]
> 

谢谢老兄

**Comment by star7th** [comment]
已经写了github ation来自动构建带版本号的镜像tag。目前最新的tag是 docker pull star7th/showdoc:v3.1.1
