### ISSUE TITLE
希望加强ShowDoc文档与用户的管理

### ISSUE THREAD

**Issue by zhixinglvren** [star7th/showdoc#172]
因为团队目前缺少一个文档管理的工具，所以最近一直在研究ShowDoc，无论是部署安装，还是编辑使用，ShowDoc非常容易上手，界面十分清爽简洁。

但是有一个方面希望可以加强，即文档与用户的管理方面
如果在团队中使用ShowDoc，会有如下几种应用策略：

**策略一**：开发团队共享一个ShowDoc公共账号，文档的编辑均由开发团队成员共同完成
**优点**：一个账号，无需管理账号；文档在一个公共账号共享与编辑，对文档能统一管理
**缺点**：一个账号拥有全部权限，文档可能随时被修改，虽然有版本，但没有版本比对，不知道改了什么，也不知道是哪个开发人员改了，更严重的是一旦有人将文档删除了，只能通过恢复备份库才能找回，文档安全性方面不好管理。

**策略二**：开发团队每位成员都拥有自己的ShowDoc账号，文档的编辑由各个开发团队在自己的账号中完成，然后通过分享链接或者二维码或者将其他人的账号加入项目成员当中来共享开发文档。
**优点**：文档归项目创建者所有，其他人没有权限删除文档，文档的安全性方面有了保障。
**缺点**：通过链接、二维码共享，需要其他人记住地址，不方便传播，将其他人员加入到项目成员，不利于某些全团队共享的文档的共享，且整个团队的文档无法统一进行管理。

**策略三**：在**策略二**的基础上，增加一个团队公共账号，每个人新建的文档项目需要将团队公共账号加入到项目成员中（只给只读权限）
**优点**：文档归项目创建者所有，其他人没有权限删除文档，文档的安全性方面有了保障，只要每位成员按照约定，将公共账号添加到项目成员中，团队可以有统一的文档中心。
**缺点**：需要创建者遵照约定，创建者可随时将公共账号的访问权限删除。

**策略四**：建一个管理员账号，所有文档先由管理员账号创建，具体由谁负责编写，只需将编辑权限赋予给谁即可，再建一个公共的只读权限账号，整个团队成员通过只读权限账号查看完整的文档。
**优点**：团队的文档可以统一管理，除了管理员账号其他人没有权限删除文档，文档的安全性方面有保障。
**缺点**：分配权限需要专人处理，且没新增一个账号都要添加一次，没有权限组的概念，比较麻烦。

在一些小团队中，可能**策略一**比较适合，但是在一些规模较大的团队中，会比较希望使用**策略四**，但目前这一块，类似于SVN那种分配权限组的方式，ShowDoc暂时不支持。

**Comment by star7th** [comment]
策略2是showdoc目前比较推荐的方案。
每个人都有自己的showdoc账号。如果你不想某个人有编辑删除权限，就把对方添加为只读成员就好。
在文档的编辑页面，有个历史版本，可以看到历史被谁编辑的以及比较编辑后的文本差异。

**Comment by star7th** [comment]
再补充一下，添加对方为只读成员后，他的主页是能看到这个项目的，所以不需要记住项目地址，不存在你说的记忆的麻烦。

**Comment by zhixinglvren** [comment]
历史版本刚看到是有文本差异比较的。

策略2的缺点，我有在上面描述。

上面几种策略在应用方面都是可行的，只是各有利弊吧，现在还在团队中推行......，希望可以成功。

**Comment by SbyXlmm** [comment]
我记得以前好像，项目成员只能操作自己新增的文档。现在改了？

**Comment by star7th** [comment]
@SbyXlmm 从来没有这个说法

**Comment by coeus-lei** [comment]
只读权限的用户，复制文档内容都不支持吗？

**Comment by star7th** [comment]
只读的用户没有复制功能。可以用浏览器本身的复制功能。

Simmon ***@***.***> 于2021年3月29日周一 下午9:07写道：

**Comment by coeus-lei** [comment]
好的，感谢

**Comment by coeus-lei** [comment]
话说，只读用户没有复制权限，大佬不改改咩

**Comment by star7th** [comment]
不打算让只读用户有复制权限。showdoc的复制是复制到编辑器中的意思。没有编辑权限就不能复制。

Simmon ***@***.***> 于2021年3月29日周一 下午9:16写道：

**Comment by coeus-lei** [comment]
好吧 ，那我只能祭出油猴--大杀器了

**Comment by coeus-lei** [comment]
我擦，，油猴都不行？？？

**Comment by coeus-lei** [comment]
ctrl+f  不支持页面查找功能呢|?
