### ISSUE TITLE
私有化部署不支持导出markdown压缩包么？还是有版本限制

### ISSUE THREAD

**Issue by 13110992819** [star7th/showdoc#1720]
私有化部署不支持导出markdown压缩包么？还是有版本限制

**Comment by star7th** [comment]
支持的。请截图说明为什么得出不支持的结论。

**Comment by star7th** [comment]
支持的。请截图说明为什么得出不支持的结论。

chenshan ***@***.***>于2022年6月8日 周三下午3:04写道：

**Comment by zk20180228** [comment]
是这样的，我最近刚开始使用，首先赞美一下，showdoc真的是太棒了，很轻量，很简单。我在测试使用时，也有同样有导出为markdown的需求。我的runapi版为2.1.1，showdoc的版本为v2.10.8，经过对比发现演示示例确实有导出markdown压缩包的功能，但是使用runapi生成的项目就没有markdown压缩包的功能。我现在的痛点是，runapi生成的项目，只能在showdoc中查看不能编辑，我试图绕过这个限制，想把runapi生成的项目经过复制，生成一个我可以编辑的项目(我想优化项目ui、其他内容)，但是失败了，它又生成了一个runapi项目，然后不死心的我决定导出为markdown格式文档，准备手动添加一个项目，靠手动复制markdown文档到新项目，但是又发现runapi生成的项目只能导出word格式的文档，然后我不死心的又来提需求了，哈哈，希望大佬能在下个版本新增该功能，十分感谢

**Comment by star7th** [comment]
runapi项目的底层存储格式不是markdown,无法导入导出markdown包。

**Comment by star7th** [comment]
markdown数据很难再转换回来runapi。所以它无法跟showdoc原有数据互相转换。只是它们可以共用文档浏览/团队协作等功能。同时runapi生成的文档只能在runapi上编辑，不能在showdoc上编辑

**Comment by FGadvancer** [comment]
https://github.com/FGadvancer/ruapi-generate-md
