### ISSUE TITLE
在Dockerhub的镜像版本问题

### ISSUE THREAD

**Issue by peerless-hero** [star7th/showdoc#1722]
https://hub.docker.com/r/star7th/showdoc/tags

生产环境为了业务稳定，一般采用锁定镜像版本的方式部署服务，所以会使用有明确版本号的镜像而不使用默认的latest镜像。
但是当前最新版本只有带**latest**标签的镜像，有具体版本号的**v2.9.6**已经是一年前的旧版本了。

建议发布新版本时对新镜像推送2个标签，即一个**latest**和一个**v2.x.x**，这样使用者遇到问题时可以回滚服务。

**Comment by peerless-hero** [comment]
那我研究一下github的workflow，找出方法后提一个pr

**Comment by star7th** [comment]
已经写了github ation来自动构建带版本号的镜像tag。目前最新的tag是 docker pull star7th/showdoc:v3.1.1
