### ISSUE TITLE
附件在Markdown上传并插入文档后 点击下载无反应

### ISSUE THREAD

**Issue by ccshuang** [star7th/showdoc#1724]
https://showdoc.talk-cloud.com/web/#/page/edit/13/3445

[a.txt](http://showdoc.talk-cloud.com/server/index.php?s=/api/attachment/visitFile&sign=5250b3c46dafccd31dfae1ccff5f7744 "[a.txt")

**Comment by ccshuang** [comment]
[图片](https://doccdncf.talk-cloud.net/OPS/WechatIMG231.png)

**Comment by ccshuang** [comment]
"version": "v2.10.5"
Docker 方式部署

**Comment by ccshuang** [comment]
server{
    listen 80;
    server_name showdoc.talk-cloud.com;
    server_tokens off;     # don't show the version number, a security best practice
    return 301 https://$server_name$request_uri;
}


server {
    listen       443 ssl;
    server_name  showdoc.talk-cloud.com;
    server_tokens off;
    charset utf-8;

    access_log  /var/log/nginx/showdoc443.access.log;
    error_log   /var/log/nginx//showdoc443.error.log crit;
    ssl_certificate         /usr/local/nginx/conf/ssl/6049038__talk-cloud.com.pem;
    ssl_certificate_key     /usr/local/nginx/conf/ssl/6049038__talk-cloud.com.key;
    ssl_ciphers "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4";
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 5m;
    location / {
        client_max_body_size 50m;
        proxy_redirect off;
        proxy_read_timeout      300;
        proxy_connect_timeout   300;
        proxy_redirect          off;
        proxy_http_version 1.1;

        proxy_set_header    Host                $http_host;
        proxy_set_header    X-Real-IP           $remote_addr;
        proxy_set_header    X-Forwarded-Ssl     on;
        proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto   $scheme;
        proxy_pass http://127.0.0.1:4999;
    }
}

**Comment by star7th** [comment]
按照这个教程绑定域名https://www.showdoc.com.cn/help/7240953917068087

**Comment by star7th** [comment]
我好像知道了。是因为你尝试在https网站中引用http网址资源。谷歌浏览器是不能的。你可以进入管理后台，设置网站外部访问地址，自己手动指定域名和https协议

**Comment by ccshuang** [comment]
> 我知道。是因为你尝试在https网站中引用http网址资源。谷歌浏览器是不能的。你进入管理后台，设置网站外部访问地址，自己可以手动指定域名和https协议

好的，这样设置后问题已经解决，十分感谢
