### ISSUE TITLE
粘贴带格式的文本（html文本）

### ISSUE THREAD

**Issue by ccimage** [star7th/showdoc#1725]
vscode里的代码，粘贴到showdoc的时候会被识别为带HTML标签的格式，会提示转化为纯文本还是继续用html格式。

问题1.  选择纯文本方式，会在原有空行的地方再增加一个空行。
问题2.  不能往代码块里面粘贴，始终会被主编辑器拦截。

**Comment by star7th** [comment]
感觉这个事情不好弄。首先因为vscode里的代码确实是html源码来的。因为vscode是用html技术写的。暂时的解决之道你可以先把代码复制到记事本，然后再粘贴进showdoc。
你反馈的格式问题不是很复杂但是细节改起来挺繁琐，我有时间再看吧

**Comment by ccimage** [comment]
好的。 那先不close了。哈

**Comment by star7th** [comment]
已经发布新版。当粘贴到代码弹窗的时候，将不再主编辑器拦截。
至于空行的问题，似乎没什么好办法。鉴于影响很小，所以忽略空行问题了

**Comment by ccimage** [comment]
好的  好快
