### ISSUE TITLE
导入的附件如何配置为https

### ISSUE THREAD

**Issue by mingyueyu** [star7th/showdoc#1726]
- 导入的附件是http，文档点那个附件链接，打开一个网页新标签马上消失，没下载。
- 把附件链接改为https以后，文档下载附件正常。
- 怎么默认添加附件的时候地址是https

**Comment by star7th** [comment]
参考迁移服务器时候的附件处理办法 https://www.showdoc.com.cn/help/2511252204165611

**Comment by mingyueyu** [comment]
还是一样，插入的附件地址还是http，不是https

**Comment by star7th** [comment]
在管理后台可以设置网站外部访问地址，自己指定https吧。另外它只对新上传的文件有效

**Comment by mingyueyu** [comment]
是这里了，解决了，谢谢
