### ISSUE TITLE
最近一直在用showodoc，感觉很爽，但还是觉得有几个不足，希望作者能考虑下

### ISSUE THREAD

**Issue by xiehongxin** [star7th/showdoc#173]
1.让手机也能编辑页面
有时候我想要在手机上用 showdoc 记录东西，但我发现如果屏幕太窄了，就无法新建页面，譬如手机和我那台分辨率较低（1024*768）的显示器。

2.如果有人在showdoc增加了文章，希望能推送消息给这个项目的所有人员
是这样子的，我们团队做一个项目，用到showdoc记录团队成员整理的资料，但是每次新增加一篇文章后总是要提醒别人，觉得这样很麻烦。

以上就是我的建议，希望作者有空的时候可以考虑下

**Comment by star7th** [comment]
开发文档需要在移动端编辑的场景比较少，短期内不做考虑吧。
至于推送通知，用什么推送，这个是个问题。推送短信的话，成本很高。推送邮件的话，需要搭建邮件服务器。而自搭建的邮件服务器有被当做垃圾邮件的风险。用第三方的邮件服务的话，要钱。所以，关于用什么推送消息，不知你是否有什么好建议？

**Comment by xiehongxin** [comment]
嗯嗯，关于推送消息，刚刚查了下，有下面的方法
1.用server酱：http://sc.ftqq.com/3.version
用GitHub账号登入它的网站，就能获得一个SCKEY；绑定它的微信公众号后，通过一个链接就可以post数据，微信上则会有消息提醒。
优点：简单粗暴，确实可以实现推送消息，现在微信使用频率高，推送的信息一般能收到
缺点：不适用广大showdoc用户，而且只能用github账号登陆，又阻挡了一部分用户

2.Rocket.chat
我们团队有在用这个聊天工具，之前有boss搞了个插件实现从其他工具推送消息到.Rocket.chat，不过现在他比较忙，不好意思打扰他
缺点：适用人群更少，而且还要自己写插件

3.灵机一动
对于用 作者搭的show doc 的用户，作者可以考虑申请个公众号，然后将信息推送到公众号，算是一个勉强的办法

以上就是我的想法，哈哈！

**Comment by star7th** [comment]
其实我也想。但申请一个有推送功能的公众号是需要企业资格的。

**Comment by xiehongxin** [comment]
对哦，看来只能求助我的boss了>_<，感谢作者的解答！

**Comment by zhixinglvren** [comment]
可以考虑搭建Websoket服务，每个账号登陆之后，可以看到消息提醒。

**Comment by star7th** [comment]
@zhixinglvren 做showdoc自身的消息中心是一个想法。不过他说的更多是消息的主动推送，即不登录也能得到通知
