### ISSUE TITLE
get请求生成的文档，回显不了在客户端工具RunApi中

### ISSUE THREAD

**Issue by songfayuan** [star7th/showdoc#1732]
get请求生成的文档，回显不了在客户端工具RunApi中

**Comment by star7th** [comment]
再更新了下。现在应该可以了

**Comment by songfayuan** [comment]
> 再更新了下。现在应该可以了

你现在最新版的get方式的请求参数，又不能在RunAPi中回显了

**Comment by star7th** [comment]
忘记了把代码同步到开源版本了。现在好了。https://github.com/star7th/showdoc/commit/e55f7f994f48b7381e1f51946626f66b58b33faa
