### ISSUE TITLE
编辑/创建页面标题始终为"默认页面"

### ISSUE THREAD

**Issue by ZengXiaoPi** [star7th/showdoc#1733]
无论是创建页面还是编辑页面的时候，标题都为默认页面。已经反复编辑标题多次了，也依旧是“默认页面”

**Comment by ZengXiaoPi** [comment]
![image](https://user-images.githubusercontent.com/102937102/175798163-5ef01576-632c-422f-a0d6-06de129f6c52.png)

**Comment by star7th** [comment]
是昨天引出的bug。现在已经修正，发布了新版

**Comment by ZengXiaoPi** [comment]
> 是昨天引出的bug。现在已经修正，发布了新版

更换2.10.8后问题依旧存在，重装了整个系统

**Comment by star7th** [comment]
你更新下浏览器缓存。这个逻辑写在js里的
