### ISSUE TITLE
无法进入后台

### ISSUE THREAD

**Issue by WeddedMercury15** [star7th/showdoc#1734]
在使用过一段时间后一直正常，在后台把默认页面改成一个指定文档后，过了一段时间 文档右上角的三角形不见了，我现在没有办法进入到后台，这应该如何解决？
![TMML2AU42ZS%0_WJI _{({X](https://user-images.githubusercontent.com/96825350/175818210-dec5285d-b14f-42a8-bf34-ac9be0d5c123.png)

**Comment by star7th** [comment]
额，主要是你的屏幕的横向分辨率太低的缘故。现在很少会有这种屏幕了吧。这个问题，你自己手动输入url访问吧，后台地址是/web/#/admin/index

**Comment by WeddedMercury15** [comment]
确实可以访问了，感谢，但是右上角的三角符号原本是会显示的，现在突然就消失了.... 怪事

**Comment by star7th** [comment]
应该是有登录态才会显示吧。这个逻辑我忘记了。反正是小众场景，不管了

WeddedMercury15 ***@***.***> 于2022年6月26日周日 22:37写道：
