### ISSUE TITLE
有没有可能重写样式？或者做皮肤？现在这个太简陋了

### ISSUE THREAD

**Issue by conanliuhuan** [star7th/showdoc#174]
你需要一个设计……重新把界面弄一遍……
有没有可能自己修改样式？

**Comment by star7th** [comment]
如果有好想法的话欢迎提出来。只是说不好看但是又没有建议的话就先不说了。

**Comment by fduck** [comment]
对于一个文档管理工具来说..这样就够用了..showdoc其他的已经强很多了 ，要自己觉得难看自己改样式啊
