### ISSUE TITLE
Android端不显示Web端上传的图片

### ISSUE THREAD

**Issue by wangYX657211334** [star7th/showdoc#1742]
在Web端上传图片后, 在Android预览不显示图片

是否是因为Android端Markdown插件预览时没有传递登录状态导致的?

**Comment by star7th** [comment]
需要外网能访问的图片，不能用内网

**Comment by wangYX657211334** [comment]
![image](https://user-images.githubusercontent.com/17154662/182547890-b31f49bf-d551-4d2b-b5fc-a949ba54ded2.png)
在web端上传之后自动会生成一个地址，而这个地址应该是需要有登陆凭证的，在web端的markdown预览图片可以正常携带凭证，我怀疑是不是Android端的markdown预览插件未能正常携带凭证，或者凭证过期等其他问题？

**Comment by star7th** [comment]
图片地址不需要凭据。你自己复制图片链接到安卓浏览器打开看行不行
