### ISSUE TITLE
runapi客户端设置cookie不生效

### ISSUE THREAD

**Issue by dance3366** [star7th/showdoc#1745]
完整客户端，不生效。如下图
![image](https://user-images.githubusercontent.com/71128756/179174821-062b798f-6d1b-4e02-bcc8-3c6683a2074d.png)
![image](https://user-images.githubusercontent.com/71128756/179174920-7f957794-675d-44bc-886d-7cc68a59f02e.png)
在线精简版可以使用
![image](https://user-images.githubusercontent.com/71128756/179175025-6f346c28-36db-40f9-9c0c-36397bd043c4.png)
![image](https://user-images.githubusercontent.com/71128756/179175093-4c1dda0e-c1a5-42f9-bf35-b73ccdba6525.png)

**Comment by star7th** [comment]
去下载最新的客户端看看 https://www.showdoc.com.cn/runapi 
另外就是后端框架是什么，能否打印出接收到的http报文

**Comment by dance3366** [comment]
卸载重装完，首次cookie会生效，如下图
![0217398ff083074cf89b23873380dd5](https://user-images.githubusercontent.com/71128756/179178237-4bc99f85-fd01-40a7-8563-51a8d0a43bb7.png)
奇怪的是，删除cookie，重新设置，就又失效了，用postman就没有这个问题
![image](https://user-images.githubusercontent.com/71128756/179180149-6574c360-e600-47ca-92b0-5d10a3cb0afc.png)

**Comment by star7th** [comment]
直接打印出接收到的http报文。你这个跟后台框架的识别机制有关。直接打印收到的http报文，排除框架影响

**Comment by dance3366** [comment]
后台是springboot，目前没找到可以打印http报文的方法
shiro可以打印出日志，接收到的cookie参数与设置的不一致
![image](https://user-images.githubusercontent.com/71128756/179182757-21b41591-a812-4950-a096-bd5828b79f94.png)
![image](https://user-images.githubusercontent.com/71128756/179182796-41e36704-d9fe-49f3-afb3-5a951d97c0c1.png)

**Comment by dance3366** [comment]
而且旧版的是可以的，旧版的下载链接可以发一个吗，我后台框架没有更换过

**Comment by dance3366** [comment]
精简版runapi跟完整版处理方式有什么不同之处吗，目前我用精简版测试没发现问题。
我排查下我代码吧

**Comment by star7th** [comment]
精简版和完整版是完全不同的两套东西来着。精简版发起http请求是经过后端php代理发出的。完整版是纯本地js发起请求。

**Comment by dance3366** [comment]
<img width="1026" alt="4d52cba5e2902835517c90f95b44da0" src="https://user-images.githubusercontent.com/71128756/179194606-bf794db1-0d8b-4113-b126-83e6266836b2.png">
后台debug，发现收到了两个cookie，一个是设置的，一个不知道哪来的

**Comment by star7th** [comment]
机制是这样的，当cookie选项卡存在用户设置的cookie时候，将会追加到header 的Cookie中（这个header的cookie由runapi客户端维护，用户无法自行设置）。一般来讲runapi自行维护的cookie来自服务器的返回。你服务器这边是否也回写了cookie？
如果真的是这个问题引起，我想我可以加一个设置。当cookie存在原header的时候，将用自定义值覆盖之

**Comment by star7th** [comment]
当前的机制不是覆盖，而是追加，所以可能存在两个

**Comment by dance3366** [comment]
cookie是不是重启runapi也不会清理，目前重启之后请求，还是会有两个cookie

**Comment by star7th** [comment]
那更印证我的猜测了。第一次访问你的服务器后，你的服务器返回了写cookies请求，所以就写了cca_token_id 。以至于第二次请求时候，带上了这个服务器写的值，以及你自定义设置的值。
重启runapi后，是否应该清理cookie，是由你的服务器决定的。你的服务器返回写请求的时候，设置的有效期应该比较长，所以下次还有。
当前你可以检查下你服务器有哪些组件返回了写cookie的请求，你禁用之。
后续我再发布一个兼容版本，用自定义值覆盖服务器返回值。

**Comment by dance3366** [comment]
嗯，我还有个小疑问，卸载runapi后，再次请求设置可用cookie，这个时候cookie有生效了

**Comment by star7th** [comment]
就跟浏览器原理差不多。服务器写的cookie会存到浏览器存储里。下次访问网页会再次带上。卸载后当然什么都没了。

dance3366 ***@***.***>于2022年7月15日 周五下午6:09写道：

**Comment by star7th** [comment]
已发布新版，解决cookie值重复问题，去这里重新下载安装 https://www.showdoc.com.cn/runapi
