### ISSUE TITLE
runapi客户端一直提示：你的网络发生异常,无法连接到runapi-showdoc服务器

### ISSUE THREAD

**Issue by limin05030** [star7th/showdoc#1747]
我用windows版的runapi客户端连接一个自己搭建的showdoc服务器，在使用一些保存功能的时候（比如环境变量，全局参数等）一直提示网络异常。showdoc服务器需要一些特殊配置来支持runapi客户端还是怎么回事儿？

**Comment by star7th** [comment]
showdoc服务器没安装好，缺少部分扩展，以至于使用部分功能的时候可能出错。比如zip扩展等。目前我没有更多信息，不好说。我的建议是使用官方最新docker镜像，比自己手动安装好

**Comment by limin05030** [comment]
除了文档里提到的php-pdo-sqlite和php-sqlite3之外，还需要哪些扩展呐，我目前用的是php5.6.40版本（一些原因导致只能手动安装）。或者有没有什么日志信息我可以提供的。

**Comment by star7th** [comment]
我忘记了都需要什么扩展了。另外，可能更多是你的版本问题。showdoc在php5下可以使用大部分功能，但有些是用不了的。我也忘记了。最好用php7.2以上

**Comment by star7th** [comment]
我已经对php5实现大部分兼容了。再细的细节就不管了，吃力不讨好。不承诺对php5的完整支持。

**Comment by limin05030** [comment]
好的，非常感谢！
