### ISSUE TITLE
文档权限

### ISSUE THREAD

**Issue by newstarqu** [star7th/showdoc#1748]
可以针对每个文档设置只有创建者可以编译，其他人是只读的吗？

**Comment by star7th** [comment]
可以，把其他人都指定为只读成员

quxiaolong ***@***.***> 于2022年7月26日周二 09:52写道：

**Comment by newstarqu** [comment]
这是针对项目和一级目录来说的吧，我的意思是目录下的每篇文档

**Comment by star7th** [comment]
添加成只读成员后，其他人对项目下的每个文档都是只有创建者可以编辑，其他人是只读。这不就是你上面描述的吗

**Comment by star7th** [comment]
如果想针对每篇文档设置不同人的有不同编辑权限，目前不能做到，也不打算做

**Comment by newstarqu** [comment]
想的是建立一个公共的项目，所有成员都可以在这个项目下创建文档，但是不能更改别人的文档

**Comment by star7th** [comment]
不能。
