### ISSUE TITLE
双击runapi客户端没有弹出管理窗口

### ISSUE THREAD

**Issue by zhukelili** [star7th/showdoc#1751]
runapi.exe 1.0.6
之前联网后是可以正常打开的，今天正常打开一次，然后自动退出后，就再打不开了

卸载【1.0.6】后，再重新下载【runapi_setup_2.0.5.exe】版，成功安装后，还是打不开

请问有解决办法吗？

**Comment by star7th** [comment]
可以这样尝试：首先卸载runapi，然后删除以下路径C:\Users\Administrator\AppData\Roaming\runapi（其中Administrator可替换为你当前登录win系统的账户名），然后再重装runapi。MAC环境的用户可以考虑使用AppCleaner来卸载和清理数据后再重装。如果依然不行，可以尝试点击runapi客户端左上角的“窗口”—“刷新页面”以更新缓存。

**Comment by zhukelili** [comment]
> 
win10h上，使用geek工具卸载后，在AppData\Roaming确认了不存runapi文件夹，再重新安装后，没有反应，都没打开客户端，所以是看不到左上角的“窗口”，这个问题比较奇怪，初步猜想是其它软件影响了

**Comment by star7th** [comment]
我能想到的有三个原因，第一就是文件损坏，卸载未清理干净导致这些坏了的文件影响到原软件。第二就是权限问题。你尝试用管理员权限运行。第三就是一些安全软件限制什么的

**Comment by zhukelili** [comment]
> 我能想到的有三个原因，第一就是文件损坏，卸载未清理干净导致这些坏了的文件影响到原软件。第二就是权限问题。你尝试用管理员权限运行。第三就是一些安全软件限制什么的

应该是第三种情况，第二种情况已经测试过，仍然是没有任何反应的，只是目前不知道是什么程序影响了，本人再找找看

**Comment by zhukelili** [comment]
> 

将runapi目录加入安全软件的信任名单之后 ，可正常运行了
