### ISSUE TITLE
域名修改图片，附件，无法显示

### ISSUE THREAD

**Issue by tmsxj** [star7th/showdoc#1752]
https://www.showdoc.com.cn/help/2511252204165611
问题描述：我根据教程修改了图片和附件域名，但是无法显示，请帮忙看看。
我使用nginx反向代理，域名由http://tmsxj.top变更为https://tmsxj.top，
`sqlite3 /showdoc_data/html/Sqlite/showdoc.db.php`
`sqlite> update page set page_content = replace(page_content,'http://tmsxj.top','https://tmsxj.top');`
`sqlite> update upload_file set real_url= replace(real_url,'http://tmsxj.top','https://tmsxj.top');`

**Comment by star7th** [comment]
如果要我看的话，你需要提供外网访网址和账号。按道理讲哪个教程那样做就可以了的

**Comment by star7th** [comment]
其实我主要是想直到图片的链接是怎么样的，访问后会跳转成怎样的。你发图片链接给我

**Comment by tmsxj** [comment]
我的项目地址是http://www.tmsxj.top
账户：test01
密码：112233
我是通过附件直接从本地上传图片和附件的。

**Comment by star7th** [comment]
我能上传图片并正常展示。如果想自定义url，比如说强制https访问，则网站后端设置，设置外部访问url

**Comment by tmsxj** [comment]
尴尬，我修改之后，原来的图片和附件就无法查看了。。

**Comment by star7th** [comment]
类似迁移教程那样改掉原来的图片和附件链接不就好了
