### ISSUE TITLE
fix: 开放接口响应数据格式与文档不一致

### ISSUE THREAD

**Issue by lkqm** [star7th/showdoc#1753]
开放接口：`/api/item/updateByApi`，文档创建成功，但是响应参数data字段有时候 true , 有时候 null , 有时候 和文档一致是个对象。

辅助信息： 项目没有任务目录和接口，由程序并发调用接口

**Comment by star7th** [comment]
根据返回码来判断是否成功比较好。data这个只是保留字段方便以后加东西。但目前来讲不需要用到。

**Comment by lkqm** [comment]
http状态码是2xx, 响应返回码 error_code=0, 但是还是会出现上面的问题，主要是想拿到 data里面的 itemId，catId 这样的基本本信息

**Comment by star7th** [comment]
后面有空再加吧

**Comment by star7th** [comment]
这个问题忘了回复了。应该是程序并发过大引起。只要并发小一点，慢慢更新每个页面，自然就没问题了。
