### ISSUE TITLE
fix: Markdown表格最后一列单元格为空渲染样式有问题

### ISSUE THREAD

**Issue by lkqm** [star7th/showdoc#1754]
<img width="1710" alt="image" src="https://user-images.githubusercontent.com/20638840/182379924-f7998e3b-bb27-456c-b434-4271e23c09cf.png">

**Comment by star7th** [comment]
其实这是一个不太好处理的已知问题。我建议在最后一列补上一个点号。

**Comment by lkqm** [comment]
可以填充一个&nbsp; 符号，但是我生成的是markdown是通用的, 优点小强迫症， 希望后续能得到解决
