### ISSUE TITLE
showdoc脚本自动化安装后，通过ngnix配置后，导致图片加载失败

### ISSUE THREAD

**Issue by lwq-js** [star7th/showdoc#1756]
<img width="419" alt="Snipaste_2022-08-03_17-12-44" src="https://user-images.githubusercontent.com/57469107/182571749-875042f4-0022-4e17-ac24-b7730c8e7116.png">
<img width="305" alt="Snipaste_2022-08-03_17-13-07" src="https://user-images.githubusercontent.com/57469107/182571761-fd142e52-5aa0-452d-b32d-0fdc3e9b6599.png">

**Comment by star7th** [comment]
参考这个文档绑定域名，里面有说到图片的规则。 https://www.showdoc.com.cn/help/7240953917068087

**Comment by lwq-js** [comment]
非常感谢，已经解决

**Comment by Mamba082481** [comment]
楼主怎么解决

**Comment by lwq-js** [comment]
> 楼主怎么解决
https://www.showdoc.com.cn/help/7240953917068087参考这个文档
