### ISSUE TITLE
runApi生成的文档链接问题

### ISSUE THREAD

**Issue by fs-danaus** [star7th/showdoc#1757]
能否把现在生成项目id由数字修改为uuid？很多公司的api文档分内部和对外二种，如果只是简单用数字来区分不同项目，就会出现分享出去后别人很容易通过猜测就能打开不想公共的文档了。像下面这种，很容易就通过21想到替换成其他项目id而打开其他项目的文档
http://localhost:9080/web/#/21?page_id=85

**Comment by star7th** [comment]
不要去掉访问密码，不要去掉访问密码。访问密码就是用来限制别人访问的。去掉访问密码意味着公开。这是设计机制。

**Comment by fs-danaus** [comment]
加访问密码是一种办法，能否也考虑下实现这个？

**Comment by star7th** [comment]
出于对历史项目的兼容，不打算改。项目都是用纯数字id

**Comment by star7th** [comment]
另外就是本来系统就生成默认的访问密码。用户自己别去掉就行了。

**Comment by fs-danaus** [comment]
好吧，谢谢
