### ISSUE TITLE
关于IOS视频附件播放的问题！

### ISSUE THREAD

**Issue by srduino** [star7th/showdoc#1758]
您好各位朋友，非常感谢得到您的帮助！

问题：关于上传的视频附件，在PC和安卓可以正常播放！
![322ad2c996dd9b34e753fba45b41e9a](https://user-images.githubusercontent.com/43785346/183385134-ecbc7ddf-389a-4ec0-bd7f-3f3485facaf5.jpg)
但在IOS上不能正常播放：
![3df04951da3aa63d7590c9a105bff45](https://user-images.githubusercontent.com/43785346/183385251-a0257213-a888-46ce-a4d7-ee482fffbb5a.jpg)

请问，如何解决掉这个问题！！！！！

**Comment by star7th** [comment]
你可以多刷新几次看看。如果确定不是网络问题，则可能是苹果那边的安全禁止。尝试使用https协议。再就没办法了。

**Comment by srduino** [comment]
> 你可以多刷新几次看看。如果确定不是网络问题，则可能是苹果那边的安全禁止。尝试使用https协议。再就没办法了。

非常感谢，更换HTTPS问题还是依旧，我尝试了另外一个方式：
![3cd3af0fd4e3199dd9374932ba69c3c](https://user-images.githubusercontent.com/43785346/183416841-e9b4edeb-4728-4ddc-8f8b-500ed5e187a5.jpg)

![image](https://user-images.githubusercontent.com/43785346/183417304-dbf3d9ac-a8c8-4c52-9f97-d3bc3a9fe1d0.png)

看起来问题出现在：是否包含.mp4后缀！

**Comment by srduino** [comment]
解决方法：
![image](https://user-images.githubusercontent.com/43785346/183427216-4e12e538-e7d6-42db-9d24-2c612d224a19.png)
