### ISSUE TITLE
能否支持excel、mind，doc文件导入和支持目录搜索

### ISSUE THREAD

**Issue by tuchaxiu** [star7th/showdoc#1759]
现在excel只能作为附件上传。我想在本地excel或者mind做好了内容，导入到服务器转换成内容，方便搜索和管理

**Comment by star7th** [comment]
不打算支持。技术上实现很难，同时使用群体小。

**Comment by star7th** [comment]
showdoc还是以技术群体的文档为主

**Comment by star7th** [comment]
excel、mind，doc文件要导入成markdown格式还是非常麻烦的。

**Comment by tuchaxiu** [comment]
目录支持搜索呢？？能否支持？？

**Comment by star7th** [comment]
在项目列表页面的搜索，可以模糊匹配目录。具体某个项目里面的话，则不匹配目录。
