### ISSUE TITLE
无法登陆，好纠结

### ISSUE THREAD

**Issue by conanliuhuan** [star7th/showdoc#176]
我用XAMPP安装在本机是完全OK的，我刚把它放到了阿里云的服务器上。然后就不能登陆了（点击登录按钮无效），也不能注册。这要怎么解决呢？地址是：
http://www.panda-studio.cn/sub-domain/showdoc/
默认密码还是showdoc，123456

**Comment by star7th** [comment]
尝试在服务器上安装一个全新的showdoc

**Comment by conanliuhuan** [comment]
删掉了重新上传，将目录权限设置为777。还是不行……
从网络面板上看登陆的时候调用了一个api，这个api返回的数据是：SQLSTATE[HY000]: General error: 11 database disk image is malformed

**Comment by star7th** [comment]
安装sqlite3扩展试试

**Comment by conanliuhuan** [comment]
阿里云的虚拟云主机不支持SQLite3的执行sql功能……看来我没办法用这个了。阿里云虚拟云主机只支持mysql数据库

**Comment by star7th** [comment]
用云服务。虚拟主机本来就很多限制
