### ISSUE TITLE
导出word时丢失数据或者不正确

### ISSUE THREAD

**Issue by hyhy01** [star7th/showdoc#1763]
![image](https://user-images.githubusercontent.com/12444588/184847228-bc69adb5-8505-4639-ba78-34621a84f4da.png)
![image](https://user-images.githubusercontent.com/12444588/184848327-660e0099-c278-496d-8735-80048a4c7320.png)
版本是v2.10.8的最新docker镜像

**Comment by star7th** [comment]
如果内容含有尖括号，比如说html标签，则会缺失内容，这是已知问题。

**Comment by hyhy01** [comment]
这是原始内容，没有尖括号
```md
[TOC]
# 业务概述
集群是容器运行所需要的资源集合，是容器运行的计算资源平台，由多个由一个主节点和多个工作节点组成，这些节点可以是物理计算机或虚拟机。是运行容器的先决条件。

平台安装部署时会默认建立一个平台级别的集群，基于平台集群可扩展多个业务集群。

平台支持接入三方标准集群，通过在线管理方式提供多集群统一管理能力。简化了集群部署、扩容等工作内容，让用户更专注于容器化应用的开发与管理。
## 集群纳管方式
- 自建集群
	通过平台线上创建集群。
- 三方接入
  通过接入集群功能接入已存在的标准Kubernetes集群，接入后可通过平台进行管理。充分考虑已有Kubernetes集群纳管需求，降低迁移、升级成本。
# 业务用例
![](http://192.168.2.173:4999/server/index.php?s=/api/attachment/visitFile&sign=b9d6a1af9583858510083e4b3acfa4f5)
# 业务流程
描述业务流

# 功能说明
## 新建集群
需要写清楚几个事情：使用场景、约束限制、业务规则、输入输出、关联业务、原型。
可参考需求文档中的表格

## 删除集群

## 编辑集群

## 集群详情

```

**Comment by star7th** [comment]
你说的是图片？ 导出的word这是链接，并不会包含图片源文件。如果图片不可被远程访问，则显示不出来。

**Comment by star7th** [comment]
还有就是导出的word不支持toc目录。

**Comment by hyhy01** [comment]
不是，我是说4.1.1.1这整个markdown文件图片和文字都消失了

**Comment by star7th** [comment]
我明白了。是因为导出的word没能支持三层以上的目录嵌套。showdoc网页本身是支持无限层目录嵌套的，但是word太麻烦了，很难支持无限层，所以只搞了三层。

**Comment by hyhy01** [comment]
那么能不能导出html或者pdf呢

**Comment by star7th** [comment]
就算导出，那也是跟word差不多的样式，很丑的。在线样式写了那么多，很难把效果都弄成离线文件。太麻烦了，所以不支持这么做了

**Comment by hyhy01** [comment]
html应该不难吧，只是把多个页面合并到一个页面。跟word差不多的样式就够了，主要是外网不能访问，这时候想把文档带到别动地方。

**Comment by star7th** [comment]
现在导出的word，知道我前面为什么说不支持尖括号吗，因为它就是html。尖括号会让html标签错位。导出html也是现在的word的效果。

hyhy01 ***@***.***>于2022年8月16日 周二下午7:04写道：

**Comment by star7th** [comment]
要做到跟网页一样的，太难了。不确定会不会做。

Chen Xing ***@***.***>于2022年8月16日 周二下午7:06写道：
