### ISSUE TITLE
UI调整建议

### ISSUE THREAD

**Issue by caobing-github** [star7th/showdoc#1765]
没必要做这样块状的网格显示风格，完全可以用列表的形式，否则不太直观，而且还不止分页，如果在不是用模糊查找的前提下，还要滑动，如果文档很多，那肯定是比较麻烦的

**Comment by star7th** [comment]
列表视图只适合大量的项目场景下。实际中很多人的项目不会太大量，还可以接受吧

**Comment by star7th** [comment]
重构的UI里，对项目进行了列表视图展示了
