### ISSUE TITLE
忘记密码功能

### ISSUE THREAD

**Issue by caobing-github** [star7th/showdoc#1766]
团队遇到一个问题就是浏览器登录或者客户端登录没有记住密码的习惯，那这里就需要有一个记住密码的功能，然后还需要提供一个忘记密码入口，去支持个人密码的修改，否则每次都要找超管账号去修改，比较麻烦

**Comment by star7th** [comment]
密码登录后会记住登录态半年。
开源版showdoc如果要做忘记密码功能，是需要管理员要配后台smtp邮件的，这块不知道要不要做

**Comment by star7th** [comment]
还是找超管改密码好吧。
