### ISSUE TITLE
文档链接分享优化建议

### ISSUE THREAD

**Issue by caobing-github** [star7th/showdoc#1768]
在分享的时候，会默认提供一个链接，也提供了一个复制的按钮，但如果这个文档是有密码的，发送给其他人的时候需要另外告诉他人，建议做成百度网盘分享的那种形式，能够一键复制连接和密码

**Comment by star7th** [comment]
密码是用户自己设置的，我觉得还是由用户自己把握比较好。百度那样的情况是因为是系统生成的
