### ISSUE TITLE
建议做下项目的历史编辑信息，都无法追踪谁编辑了什么时间编辑什么东西。

### ISSUE THREAD

**Issue by allen-hxn** [star7th/showdoc#177]

**Comment by allen-hxn** [comment]
另外还有每个页面的编辑信息和修改信息也没有，都不知道是什么时候创建的

**Comment by allen-hxn** [comment]
修改和删除的权限也可以分开啊。

**Comment by star7th** [comment]
原来这个问题没有回复。
查看的页面右边有个详情按钮，能看到最后编辑信息。
历史编辑信息的话，在编辑该页面的时候，选择 历史版本 便可以看到。
修改和删除的权限分开没有意义。把东西修改为空就是删除了
