### ISSUE TITLE
"&nbsp"编辑输入后自动消失问题

### ISSUE THREAD

**Issue by ccshuang** [star7th/showdoc#1773]
编辑模式下输入 &nbsp，当前页面显示无异常；如再次编辑此文档，则上次输入的空格会消失。

**Comment by star7th** [comment]
这是已知问题。经过前后端储存后，html会经过转义和反转义的过程。

**Comment by ccshuang** [comment]
> 这是已知的。过去的过程之后，会验证转义和电能的义。

有修复计划或者解决方案吗

**Comment by star7th** [comment]
无计划。这不算什么bug，本身showdoc没承诺过支持所有非markdown特殊字符。
