### ISSUE TITLE
希望新增 ARM 版本的docker镜像

### ISSUE THREAD

**Issue by zerot86** [star7th/showdoc#1774]
目前的镜像是x86的，无法在ARM的服务器上运行，希望作者增加ARM版本的镜像，谢谢！

**Comment by star7th** [comment]
现在arm的服务器极少，不太想为此增加维护成本

**Comment by star7th** [comment]
要想安装自己手动安装arm版本的php运行环境来运行showdoc吧

**Comment by zerot86** [comment]
目前政府机关部门相关软硬件全部国产化，服务器统一是arm的，那我先手动搭一套吧

**Comment by zerot86** [comment]
目前政府机关部门相关软硬件全部国产化，服务器统一是arm的，那我先手动搭一套吧

**Comment by star7th** [comment]
我了解到的情况是确实在推广信创，国产化，但是也有x86架构的吧，应该没规定死一定要arm服务器的。应该运维和软件人员申报采购的时候说明是x86架构即可

**Comment by mimicode** [comment]
`docker run -d --name showdoc --user=root --privileged=true -p 4999:80 -v /home/ubuntu/showdoc_data/html:/var/www/html/ registry.cn-hangzhou.aliyuncs.com/mearm64/star7th-showdoc:2.10.8`

搞出来了

我把 webdevops/php-nginx:7.4-alpine  构建了一个arm64版本的（在我的树莓派4b上）。

`registry.cn-hangzhou.aliyuncs.com/mearm64/star7th-showdoc:2.10.8`   在我树莓派上正常运行

**Comment by star7th** [comment]
官方初步推出了ARM版本的docker镜像。 命令 

docker pull star7th/showdoc:arm-latest

docker run -d --name showdoc --user=root --privileged=true -p 4999:80 \
-v /showdoc_data/html:/var/www/html/ star7th/showdoc:arm-latest 


目前已知的ARM版docker镜像缺陷：
0,只能使用docker官方镜像 star7th/showdoc:arm-latest  ，可能没有大陆镜像加速
1，只支持ARM64位，应该不支持ARm32位.目前在ARM64位的centos7上安装测试已经通过，其他硬件设备由于缺乏测试环境，故尚未测试。理论上ARM64环境都可以兼容。
2，可能无法使用英文版，只能用默认的中文版
3，无法使用mock功能
4，上传图附件到云储存功能尚未测试，且没打算逐一测试各平台，不保证能支持各大云储存
5，导入中文命名的压缩包可能出错。这个问题不打算测试和处理
