### ISSUE TITLE
左右两边余白太多

### ISSUE THREAD

**Issue by mfyproject** [star7th/showdoc#1776]
左右两边余白太多，希望可以两边靠左和靠右对齐，中间区域都留给正文显示

**Comment by star7th** [comment]
你说的这种方式会导致，同一样内容，在不同分辨率的屏幕上的效果可能千差万别。所以，showdoc采用固定中间宽度的做法。

**Comment by mfyproject** [comment]
你说的非常有道理，但是，目前我碰到的问题就是中间正文是一个大表格，所以出现了最下边出现了左右滚动条，浏览器两个还有余白，非常不友好。可以说一下，我应该在哪里修改中间宽度吗？或者可以做一个开关设置，提供两种显示模式，一种现在的固定中间宽度，一种是两边靠左和靠右对齐

**Comment by star7th** [comment]
showdoc有个全屏按钮，点击全屏就可以阅读大表格。

**Comment by ccshuang** [comment]
我这里看到的并不全屏，建议还是全屏比较合适

**Comment by ccshuang** [comment]
> 我这里看到的并不全屏，建议还是全屏比较合适

<img width="2452" alt="image" src="https://user-images.githubusercontent.com/25891802/190972154-f56bc193-8f2b-4d42-bfd8-a1227142eab9.png">
