### ISSUE TITLE
需求建议

### ISSUE THREAD

**Issue by westudiodev** [star7th/showdoc#1777]
后台可以配置顶部菜单栏，添加超链接，这样可以方便在多个独立文档库之间进行跳转
![Screen Shot 2022-09-06 at 11 37 17](https://user-images.githubusercontent.com/33219803/188541990-28fb2923-b982-4e7f-a12e-970d4e2a5865.jpg)

**Comment by star7th** [comment]
技术上加并不难。但是要设计好看，就得探索下。不清楚该不该加

**Comment by star7th** [comment]
决定不考虑此功能了。应该用得不多。建议先返回再进入其他项目。
