### ISSUE TITLE
能否支持普通的HTML编辑器

### ISSUE THREAD

**Issue by shaoming01** [star7th/showdoc#178]
能否支持普通的HTML编辑器，有时候需要丰富一些的文本样式
现在的格式有时候有前台不兼容显示不出来要刷新好几次

**Comment by star7th** [comment]
现在不支持普通html。后续可能考虑。
其实markdown格式真的挺适合编辑的。

**Comment by shaoming01** [comment]
谢谢回复。你说的我懂的，编辑没有什么问题，不过如果在前台展示的时候输出的是普通HTML就好了，展示效率高些，兼容性好些。
