### ISSUE TITLE
console升级后给用户授权报未知错误

### ISSUE THREAD

**Issue by ccshuang** [star7th/showdoc#1781]
showdoc v2.10.5 在console点的自动升级
现在版本是 v2.10.8  
目前发现当前版本给用户添加项目提示 未知错误
<img width="2214" alt="image" src="https://user-images.githubusercontent.com/25891802/190945643-397dd3fc-03fd-4e2b-b922-b28d7c5ee1f9.png">

**Comment by ccshuang** [comment]
> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/25891802/190945643-397dd3fc-03fd-4e2b-b922-b28d7c5ee1f9.png">

docker 方式部署

**Comment by ccshuang** [comment]
刚才在此也没点击自动升级
<img width="1342" alt="image" src="https://user-images.githubusercontent.com/25891802/190945809-cafb6ae2-0e17-4e7d-a5e0-51c3794d09c5.png">

**Comment by ccshuang** [comment]
刚才在此页面点击自动升级
<img width="1342" alt="image" src="https://user-images.githubusercontent.com/25891802/190945833-b16d380a-0a31-413f-821c-310a5eff97e5.png">

**Comment by star7th** [comment]
到docker挂载目录，递归给777权限然后重启容器

**Comment by ccshuang** [comment]
测试后问题依旧
我新开的无痕浏览也不行
<img width="963" alt="image" src="https://user-images.githubusercontent.com/25891802/190947604-866a1096-a5ab-4e58-8c97-4bf811259edf.png">

**Comment by ccshuang** [comment]
怎么可以回退到v2.10.5这个版本呢

**Comment by star7th** [comment]
按照这个教程再手动升级一次  https://www.showdoc.com.cn/help/65610

**Comment by star7th** [comment]
感觉你上面的成员是添加成功了的。可能只是程序提示语不正确而已。

**Comment by ccshuang** [comment]
升级提示用户都不存在了  重新被初始化了

**Comment by star7th** [comment]
每次升级，在 showdoc的  Sqlite/ 目录下都有一个日期命名的数据库文件备份。将它重命名去掉日期，就可以恢复备份。

**Comment by ccshuang** [comment]
已经升过级 没有发生这种问题  线上先恢复了  晚点我在测试吧

**Comment by ccshuang** [comment]
以前升过级 没有发生这种问题 线上先恢复了 晚点我在测试吧

**Comment by ccshuang** [comment]
> 感觉你上面的成员是添加成功了的。可能只是程序提示语不正确而已。

没有成功的

**Comment by ccshuang** [comment]
现在这种情况 我还需要怎么操作

**Comment by star7th** [comment]
按照这个教程再手动升级一次 https://www.showdoc.com.cn/help/65610

**Comment by ccshuang** [comment]
> https://www.showdoc.com.cn/help/65610

刚才就是执行了  项目 用户都不在了

**Comment by star7th** [comment]
如果按照升级文档操作有问题，可能是你当初不按照官方教程来安装。
为了避免此此类问题，请用官方自动脚本安装。安装好后，将旧的sqlite文件替换即可。

**Comment by ccshuang** [comment]
> 如果按照升级文档操作有问题，可能是你当初不按照官方教程来安装。 为了避免此此类问题，请用官方自动脚本安装。安装好后，将旧的sqlite文件替换即可。
上几次升级都没问题

**Comment by star7th** [comment]
安装脚本也是利用docker来安装的。所以你用安装脚本弄好，它会帮你跑起docker镜像。之后就是用旧的数据库文件替换，重启下容器即可

**Comment by ccshuang** [comment]
目前看来你们后台的升级点完之后肯定是有问题的

**Comment by ccshuang** [comment]
这里怎么隐藏

**Comment by star7th** [comment]
官方脚本安装的程序，升级没问题。你自动升级和手动升级都出问题，证明肯定是你没按照官方方式安装，导致有些东西跟官方预期不一样，所以升级也不对。用官方自动脚本吧。

**Comment by ccshuang** [comment]
> 官方脚本安装的程序，升级没问题。你自动升级和手动升级都出问题，证明肯定是你没按照官方方式安装，导致有些东西跟官方预期不一样，所以升级也不对。用官方自动脚本吧。

以前手动升级过多次，都没问题。今天先自动升级出的问题，在按照手动升级文档来也出现了问题。目前自动升级导致的故障还没处理，现在是所有用户都不可以在授权了。

**Comment by ccshuang** [comment]
> 怎么可以回退到v2.10.5这个版本呢

可以退回到指定版本吗

**Comment by ccshuang** [comment]
我想让不能授权的问题先恢复

**Comment by ccshuang** [comment]
> 官方脚本安装的程序，升级没问题。你自动升级和手动升级都出问题，证明肯定是你没按照官方方式安装，导致有些东西跟官方预期不一样，所以升级也不对。用官方自动脚本吧。

不好意思刚看见您说的  我们就是官网自动安装脚本部署的

**Comment by star7th** [comment]
先恢复数据。用带日期的旧数据库文件。确认恢复了后，再执行 ../showdoc update

**Comment by ccshuang** [comment]
已经升级成功了  感谢
