### ISSUE TITLE
全局参数删不掉了

### ISSUE THREAD

**Issue by zwy66666** [star7th/showdoc#1783]
全局参数删不掉了
![QQ截图20220920223904](https://user-images.githubusercontent.com/96455554/191288291-e1555bc9-13f7-4360-8bda-2952a32da168.jpg)
![QQ截图20220920223913](https://user-images.githubusercontent.com/96455554/191288296-ff49ca1d-4072-441c-ae81-302b1d3920df.jpg)
![QQ截图20220920223922](https://user-images.githubusercontent.com/96455554/191288308-eed43362-572b-4d49-a858-8bdc7dda7274.jpg)

删除之后还是有

**Comment by star7th** [comment]
试试官网是否有此问题 https://www.showdoc.com.cn/  ，如果官网无此问题，则需要提供一个你的地址给我测试重现下

**Comment by zwy66666** [comment]
直接发给你吗
有邮箱吗

**Comment by zwy66666** [comment]
官网没问题，
现在就是我自己这个runapi升级后出现的

**Comment by star7th** [comment]
github主页就有我邮箱
