### ISSUE TITLE
建议登陆密码加密传输

### ISSUE THREAD

**Issue by Eastair** [star7th/showdoc#1784]
官方登陆初始登陆密码为123456，过于简单，且登陆时使用明文传输
对于我们这些管得比较严的企业，内部网络有态势感知，首次登陆会被扫描出弱密码，触发告警
建议登陆接口使用加密传输用户名及密码。

**Comment by star7th** [comment]
1，初始密码肯定简单，你可以在管理后台修改密码。
2，传输的安全使用https协议解决

**Comment by Eastair** [comment]
> 那也得登陆了才能改密码，首次登陆就被扫描出来了

**Comment by star7th** [comment]
那你去跟网管沟通。或者一开始使用https链接。很多系统初始化都是使用弱密码的，按你这种规则限制这些系统都装不了了。

**Comment by star7th** [comment]
初始化用弱密码没毛病，安装界面已经提示过你改密码了。

**Comment by Eastair** [comment]
初始密码稍微强一点就好了，123456，显得太随意，太不专业了，你哪怕起个 Showdoc! 也不至于被扫出来
我就是个建议，觉得你们好用，希望你们更好而已，不过，看你的态度，估计就是不会改了，不用回复了，再见

**Comment by star7th** [comment]
这个初始密码机制都用了6年了，也不知道多少公司安装过，都没吐槽过这个问题。本身初始化密码就是给用户快速体验的，弄复杂了反而麻烦。
对于你的情况，我是真的建议一开始使用https证书，自生成一个证书都行，然后自己在浏览器里点击信任。这样安全软件是无法拦截到你的明文信息了的。
传输层的安全，由传输层解决，不需要业务介入。

**Comment by star7th** [comment]
你也知道是你自己的企业管得严，而不是通用问题，所以这个问题应该是由你针对实际情况来生成https证书访问，而不是倒推showdoc官方去操作。

**Comment by Eastair** [comment]
得，我们放弃showdoc，原因，不安全
