### ISSUE TITLE
导出当前文档为word操作麻烦，建议新增一个按钮，导出当前页

### ISSUE THREAD

**Issue by liuzongyang255** [star7th/showdoc#1786]
![image](https://user-images.githubusercontent.com/54257047/192426735-d219764b-40ff-4d51-b4dc-89e8dba1272a.png)

![image](https://user-images.githubusercontent.com/54257047/192426832-69790cc9-a65f-4ea6-a63e-ff40fa4d6e6e.png)

**Comment by star7th** [comment]
很少听到有反馈说非常经常地导出当前页、所以我觉得这应该是个低频操作，就不想放出来了

**Comment by liuzongyang255** [comment]
好吧，不过还是觉得放出来用比较方便，毕竟是个刚需个功能哈哈

还有个小问题，弹出页面选中单独导出一篇文章，文件的标题是整个项目的标题

**Comment by star7th** [comment]
默认就是项目标题的。然后下面是文档内容，只是内容你选择单页面而已
