### ISSUE TITLE
文档标题含特殊符号，如“&和&&的区别”，保存后被渲染成实体

### ISSUE THREAD

**Issue by notThinKeepNickname** [star7th/showdoc#1788]
1、我有一篇文档是标题是“&和&&的区别”，在保存后查看，文档标题的特殊符变成了实体“& amp;和& amp;& amp;的区别”

**Comment by star7th** [comment]
当前为了安全，做了一些安全转义。现在为了兼容历史，这个机制怕是去不掉。所以标题处不打算支持特殊字符了
