### ISSUE TITLE
图片的路径问题

### ISSUE THREAD

**Issue by ZuiSong** [star7th/showdoc#179]
现在上传图片上去后，图片路径写的是服务器ip的绝对路径，当showdoc部署在内网通过内网穿透出去的时候，图片的地址此时无法访问到，能否把图片的路径改成相对与服务器的路径

**Comment by star7th** [comment]
图片有可能是自行上传的图片或者网络地址图片，所以统一使用相对路径会引来很多麻烦。
如果你要迁移，可以进数据库里把图片路径统一改一遍。
