### ISSUE TITLE
关于权限控制

### ISSUE THREAD

**Issue by yejiuxing** [star7th/showdoc#1790]
能否实现单个用户菜单管理，就是一个用户，我想让他可编辑他自己的菜单A，但是不能编辑菜单B（但是可读），有办法实现吗

**Comment by star7th** [comment]
我第一感觉这不好实现。再考虑到需求太小众，所以应该不支持这么细分的权限管理了、

**Comment by yejiuxing** [comment]
好的，其实这就是相当于想要类似后台系统的权限功能。需求是想新人可以在项目中加新的文档。但是不想他动到现有文档
