### ISSUE TITLE
登陆的时候一直提示“验证码不正确”

### ISSUE THREAD

**Issue by halswong** [star7th/showdoc#1792]
可以关闭登陆验证码吗？
![2022-10-02_224027](https://user-images.githubusercontent.com/12635088/193460032-3156a447-99c2-4c32-8e14-48409a19d287.png)

**Comment by star7th** [comment]
先到php.ini文件下找找session的保存目录，然后检查安装session目录有没有写入权限，或者可不可能是磁盘空间满了的问题。如果是有绑定了域名，可以参考官方的教程来绑定 https://www.showdoc.com.cn/help/7240953917068087

**Comment by halswong** [comment]
> 

有写入的权限，也没有绑定域名。只是本地部署整理文档用，有没有办法关闭验证码？

**Comment by halswong** [comment]
登陆的时候，session目录下虽然生成了新文件“sess_3aaa18ae60fd4389655ac34c5f11769f”，但是字节大小为零，不知道正不正常？

**Comment by star7th** [comment]
没有关闭功能

halswong ***@***.***>于2022年10月3日 周一下午12:04写道：

**Comment by star7th** [comment]
推荐用官方自动脚本安装

Chen Xing ***@***.***>于2022年10月4日 周二上午10:31写道：

**Comment by halswong** [comment]
好的，谢谢~
