### ISSUE TITLE
KKfile 集成

### ISSUE THREAD

**Issue by ReviewClouds** [star7th/showdoc#1794]
hi 
之前问过这个问题，说的是不在版本中集成
私人部署的话可以给一些集成方法和建议吗，不太想单独部署kkfile

**Comment by star7th** [comment]
肯定要独立部署的。就算showdoc支持，也是要你独立部署然后调用的。而且短期内不打算支持。

rd-machine ***@***.***>于2022年10月5日 周三下午9:31写道：

**Comment by liuzongyang255** [comment]
自己部署一个kkfile，录链接就行了吧
