### ISSUE TITLE
移动端新建项目无限刷新

### ISSUE THREAD

**Issue by xiaobaia68** [star7th/showdoc#1795]
如题，移动端新建项目，点一下就刷新，无限刷新，也就是无法新建项目。（脚本自动部署的）

**Comment by star7th** [comment]
你确认服务端新建项目正常吗

**Comment by star7th** [comment]
去登陆web端试试新建项目

**Comment by xiaobaia68** [comment]
> 去登陆web端试试新建项目

pc新建正常，可能是我这边的问题。服务器有用宝塔挂着其他网站，绑定域名直接在宝塔更改的网站目录，可能是这个原因。

**Comment by star7th** [comment]
绑定域名尝试按照这个来 https://www.showdoc.com.cn/help/7240953917068087
