### ISSUE TITLE
MarkDown flow流程图偶尔不显示

### ISSUE THREAD

**Issue by froggoHao** [star7th/showdoc#1796]
常规项目中包含流程图，多次刷新下会偶尔显示为空白
![Video_2022-10-08_173826](https://user-images.githubusercontent.com/61374620/194734193-b18500e4-35b7-42d2-a3a3-64f18a4948cb.gif)

尝试过的版本:v2.10.8 v2.9.9
浏览器:chrome(105.0.5195.127) firefox(105.0.2)
流程图源码:
\```flow
st=>start: 打开支付中心
selectGameAndServer=>operation: 选择游戏，区服
requestRoleApi=>operation: 获取角色列表
selectRole=>operation: 选择角色
requestRechargeApi=>operation: 获取档位信息
selectRecharge=>operation: 玩家选择档位
start_pay=>operation: 点击支付
pay=>condition: 支付成功 ?
callbackCp=>operation: 我方回调【充值回调】接口
e=>end: 发货

st->selectGameAndServer->requestRoleApi->selectRole->requestRechargeApi->selectRecharge->start_pay
start_pay->pay(yes)->callbackCp->e
start_pay->pay(no)->start_pay
\```
浏览器中报错:
![image](https://user-images.githubusercontent.com/61374620/194700846-6962f56f-4560-4b63-8a63-66fe011163f7.png)

**Comment by star7th** [comment]
按照这个教程升级最新版然后更新浏览器缓存 https://www.showdoc.com.cn/help/13732

**Comment by star7th** [comment]
relese发的大版本尚未包含此次更新

**Comment by froggoHao** [comment]
拉取master部署后，在chrome下还是能复现，而firefox和edge下是修复了。确认已经清理过浏览器缓存。

**Comment by star7th** [comment]
大概找到原因了，晚一点改一下

**Comment by star7th** [comment]
我推送更新了，最新master版本已经修复。

**Comment by froggoHao** [comment]
验证master分支已经修复，感谢
