### ISSUE TITLE
docker镜像版本问题

### ISSUE THREAD

**Issue by zywayh** [star7th/showdoc#1798]
请问作者，是否可以打一个带tag的最新版本镜像？我们公司要求docker必须带tag，不能用latest

**Comment by star7th** [comment]
好了，刚手动打了一个v2.10.8  的tag

**Comment by zywayh** [comment]
好的，谢谢作者

**Comment by zywayh** [comment]
发现点问题，使用2.10.8版本部署后，在管理后台看，还是显示的2.9.15版本，是不是作者忘记改了
<img width="973" alt="image" src="https://user-images.githubusercontent.com/24758651/195311432-c196073b-b18a-401a-ac76-6de1fdd55499.png">

**Comment by star7th** [comment]
如果你还没有放置文档内容，你可以先清理掉所有挂载的数据再装

zywayh ***@***.***>于2022年10月12日 周三下午5:52写道：

**Comment by zywayh** [comment]
尝试过了，版本依然是2.9.15，但是里面多了个升级按钮，升级后才能到最新2.10.8，目前公司服务器不能连外网，无法升级，是否可以打个最细的呢

**Comment by zywayh** [comment]
或者是否可以提供构建脚本，我自己来也可以

**Comment by star7th** [comment]
其实你下载latest版，手动更改标签tab即可，连构建都不需要。

**Comment by star7th** [comment]
docker tag 命令可以改标签

**Comment by star7th** [comment]
已经写了github ation来自动构建带版本号的镜像tag。目前最新的tag是 docker pull star7th/showdoc:v3.1.1
