### ISSUE TITLE
Run API 的失败返回示例可以填写多个吗

### ISSUE THREAD

**Issue by howie6879** [star7th/showdoc#1799]
请问对于有多种失败响应怎么在runapi设置然后自动同步到showdoc

**Comment by star7th** [comment]
目前未支持。建议这么做：
可以在一开始的首页建立一个公共响应码，列举出所有错误响应情况。
失败响应是一个代码块，你手动写多个json串其实也行的

**Comment by howie6879** [comment]
好的，谢谢，手动填多个响应也可以。

后续有多请求示例支持的规划吗？

**Comment by star7th** [comment]
那个要看下情况，目前尚未能完全确定

**Comment by howie6879** [comment]
还有个问题，对于基于响应快速生成返回参数说明，如果我的参数是两级，那么生成的说明会出问题，没有层级区分：

![image](https://user-images.githubusercontent.com/17047388/195487664-d787d2cf-30bf-4406-a0e4-9e01d4d010e6.png)

**Comment by star7th** [comment]
这是有意为之，因为大部分情况下，第一级都是错误码，所以第一级是被忽略的，是从第二级开始算的
