### ISSUE TITLE
PHP Fatal error:  Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by Leafney** [star7th/showdoc#180]
从旧版本使用的mysql数据库，需要升级成新版本的sqlite数据库，进行迁移时，报如下错误：

```
PHP Fatal error:  Maximum execution time of 30 seconds exceeded in E:\WorkProject\apidoc\ThinkPHP\Library\Think\Db\Driver.class.php on line 223
```

现在迁移无法完成，我对php代码不懂，望能给出一个解决办法！！！

**Comment by star7th** [comment]
其实把这段代码在网上搜索一下就有答案了。需要调整下php的执行时间

**Comment by Leafney** [comment]
@star7th 感谢回复。
按照你的说法，我将php.ini中的 `max_execution_time=30` 改成了 120 ，然后超时的问题解决了，却又报了如下的问题：

```
:(
19:UNIQUE constraint failed: catalog.cat_id [ SQL语句 ] : INSERT INTO catalog (cat_id,cat_name,item_id,s_number,addtime,parent_cat_id,level) VALUES ('1','接口示例','2','99','1448461340','0','2')
错误位置
FILE: E:\WorkProject\apidoc\ThinkPHP\Library\Think\Db\Driver.class.php 　LINE: 350
TRACE
#0 E:\WorkProject\apidoc\ThinkPHP\Library\Think\Db\Driver.class.php(350): E('19:UNIQUE const...')
#1 E:\WorkProject\apidoc\ThinkPHP\Library\Think\Db\Driver.class.php(237): Think\Db\Driver->error()
#2 E:\WorkProject\apidoc\ThinkPHP\Library\Think\Db\Driver.class.php(824): Think\Db\Driver->execute('INSERT INTO cat...', false)
#3 E:\WorkProject\apidoc\ThinkPHP\Library\Think\Model.class.php(320): Think\Db\Driver->insert(Array, Array, false)
#4 E:\WorkProject\apidoc\Application\Home\Controller\UpdateController.class.php(489): Think\Model->add(Array)
#5 E:\WorkProject\apidoc\Application\Home\Controller\UpdateController.class.php(221): Home\Controller\UpdateController->_moveTable('catalog')
#6 [internal function]: Home\Controller\UpdateController->toSqlite()
#7 E:\WorkProject\apidoc\ThinkPHP\Library\Think\App.class.php(173): ReflectionMethod->invoke(Object(Home\Controller\UpdateController))
#8 E:\WorkProject\apidoc\ThinkPHP\Library\Think\App.class.php(110): Think\App::invokeAction(Object(Home\Controller\UpdateController), 'toSqlite')
#9 E:\WorkProject\apidoc\ThinkPHP\Library\Think\App.class.php(204): Think\App::exec()
#10 E:\WorkProject\apidoc\ThinkPHP\Library\Think\Think.class.php(120): Think\App::run()
#11 E:\WorkProject\apidoc\ThinkPHP\ThinkPHP.php(97): Think\Think::start()
#12 E:\WorkProject\apidoc\index.php(24): require('E:\\WorkProject\\...')
#13 {main}
```

**Comment by star7th** [comment]
之前转移失败了部分数据导致的主键重复。把数据都清理一遍，然后再重新转移。或者说干脆重新来过，代码也重新下载

**Comment by Leafney** [comment]
我在操作之前已将数据库和代码都做了备份，出现第一次超时的问题后，我将代码和数据库都恢复了原状态。但又导致了第二个问题。现在我又恢复了原状态。

现在主要问题是数据有点多，如果重新配置内容一条一条添加的话比较费时。

我再尝试一下看看吧。

**Comment by Leafney** [comment]
迁移成功了，还是要来感谢一下。说下我的操作吧：
1. 出现
```
UNIQUE constraint failed: catalog.cat_id [ SQL语句 ] : INSERT INTO catalog (cat_id,cat_name,item_id,s_number,addtime,parent_cat_id,level) VALUES ('1','接口示例','2','99','1448461340','0','2')
错误位置
```
这个问题应该是我的操作错误。就是在访问 `http://xxxx.com/index.php?s=/home/update/toSqlite ` 后浏览器一直在加载，然后报了 `http error 500` 的错误，我以为是加载失败，刷新了一下，就出现了主键重复的问题。
2. 出现上述问题后，我将数据库和代码恢复了原先备份前的状态，然后，按照迁移步骤，"将新代码中的/Sqlite/ 复制到旧目录(如果已存在/Sqlite则覆盖之)，并赋予/Sqlite/showdoc.db.php可写权限" ,“复制新代码中的/Application/Home/Controller/UpdateController.class.php 覆盖原来旧的相应文件。” 可能我之前安装的版本太老了，应该是15年的时候下载的，Controller目录下没有UpdateController.class.php 文件，不过好像不影响。然后访问 `http://xxxx.com/index.php?s=/home/update/toSqlite ` 地址，然后浏览器在加载一段时间后（在这之前我将前面设置过的max_execution_time改成了72000），又报了 http error 500 的错误。这时候我没有刷新，而是继续按照迁移步骤往下操作。“除了/Sqlite/showdoc.db.php文件外，旧目录的其他所有文件全部用新下载的文件覆盖。” 然后请求index.php页面，发现居然有数据了。
3. 但是又有一个问题，因为之前有登陆过，所以浏览器记住了密码，第二步后就直接进入项目页面了，所以看到了之前添加的数据。我退出当前账户后，发现使用之前的账号密码登陆不进去了，一直提示用户名密码错误。
4. 这时我又看了一下迁移文档，发现有一句话：“看到ok提示后，mysql的数据已经写入/Sqlite/showdoc.db.php” ，通过看文件名和这句话我就觉得这个文件应该是sqlite的数据库文件。所以我改了扩展名，用Navicat打开，找到了之前的数据表。在和原来mysql的数据表一一比对后，发现user表中为空，其他的page表中的数据都是完整的。然后我将原user表拷贝到了新的user表中，这样就能登录了。
5. 因为 http error 500 的问题导致数据迁移不完整，没想明白是怎么回事。现在项目访问正常，也就没有去深究。

再次感谢 @star7th 的及时回复。
