### ISSUE TITLE
文档更多按钮展开后，菜单遮挡了按钮

### ISSUE THREAD

**Issue by liuzongyang255** [star7th/showdoc#1801]
版本：docker 2.10.8
![image](https://user-images.githubusercontent.com/54257047/196070642-884c3277-deeb-4de4-9a29-198dbeffdffe.png)

复现步骤：先点击展开更多按钮，再刷新页面，按钮展开速度也偏慢

![image](https://user-images.githubusercontent.com/54257047/196070559-a6229711-f3f6-4db8-a286-70773f6aca73.png)

**Comment by star7th** [comment]
好像历史是解决过这个问题的。可能最近啥时候更新把问题重新引入了。晚点改下

**Comment by star7th** [comment]
已重构了UI
