### ISSUE TITLE
标题名一样，锚点也一样，导致无法精确定位

### ISSUE THREAD

**Issue by liuzongyang255** [star7th/showdoc#1802]
![image](https://user-images.githubusercontent.com/54257047/196074492-10a9fa0d-7565-4ed8-b56b-df91cf612301.png)

**Comment by wangxuwena** [comment]
老問題了，導致只能定位第一個標題是嗎

**Comment by star7th** [comment]
只能定位第一个标题。建议可以加个前缀，区别标题名字
