### ISSUE TITLE
容器化部署，将容器内部数据库或者资源，挂载出来，以防丢失数据

### ISSUE THREAD

**Issue by MyNameIsYangJianYu** [star7th/showdoc#1806]
容器内部数据如何存储？ 存储在哪的？是否能挂在出来呀，大佬们帮帮小老弟。

**Comment by star7th** [comment]
https://www.showdoc.com.cn/help/65610 教程里挂载命名就有挂载目录

**Comment by MyNameIsYangJianYu** [comment]
> https://www.showdoc.com.cn/help/65610 教程里挂载命令就有挂载目录

谢谢大佬
