### ISSUE TITLE
编辑完点保存及通知后没有保存T T

### ISSUE THREAD

**Issue by Paradoxyan** [star7th/showdoc#1807]
历史版本里也没有

**Comment by star7th** [comment]
不清楚你说的是什么情况，尝试在https://www.showdoc.com.cn/ 官网重现下，或者提供一个重现地址，最起码截图。我这么多年来没遇到你说的情况，也没收到这样的反馈

**Comment by Paradoxyan** [comment]
我是本地服务器私有部署。截图说明了一下
![image](https://user-images.githubusercontent.com/29299024/197452678-49d7793e-095c-4374-ad5d-083a388aca53.png)

**Comment by star7th** [comment]
再保存呢，分别试下两种保存方式。
再有问题，尝试放上公网我看看，用这个工具放出公网 https://www.gaoyixia.com/

**Comment by Paradoxyan** [comment]
试出来了，点击保存及通知，如果没有写通知内容，就不会保存

**Comment by star7th** [comment]
如果不写通知内容，直接点外面的保存就好了。

**Comment by star7th** [comment]
点击通知按钮就默认你会写通知

**Comment by Paradoxyan** [comment]
好吧，那建议如果没写通知备注，确定按钮就灰显，我以为可以不写内容😔 写了一上午啊……
是不是就找不到了，服务器里会有缓存吗

**Comment by star7th** [comment]
应该没有。
