### ISSUE TITLE
配置showdoc显示File not found.

### ISSUE THREAD

**Issue by kinghand** [star7th/showdoc#181]
问题描述 : 配置好后下一步应该是install, 打开页面却显示 File not found. 
配置过程 : 
    centos上用composer create 了showdoc目录, 
    nginx用一个域名直接对showdoc目录做了指向, 
    测试肯定是正常访问到index.php并调用install/index.php了, 也能访问其他文件比如Read Me.

**Comment by star7th** [comment]
贴一下完整的nginx配置出来看看

**Comment by kinghand** [comment]
server{
    listen	80;
    server_name doc.mydomain.ltd;

    location / {
        root   /var/www/showdoc;
        index  index.php index.html index.htm;   
    }

     location ~ \.php$ {    
        root           /var/www/shoudoc;
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_index  index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include        fastcgi_params;
    }  
}

**Comment by star7th** [comment]
把 

    location / {
        root   /var/www/showdoc;
        index  index.php index.html index.htm;   
    }

去掉试试

**Comment by kinghand** [comment]
解决了 和nginx配置无关 是目录权限设置的问题 
我直接chmod a+x showdoc -R 了一下
