### ISSUE TITLE
runapi请求头修改无效

### ISSUE THREAD

**Issue by jkpeng** [star7th/showdoc#1810]
接口请求修改了：User-Agent 请求头
服务端收到的:User-Agent 如下
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) runapi/2.1.1 Chrome/87.0.4280.141 Electron/11.5.0 Safari/537.36

后续版本希望可以支持修改请求头信息

runapi有贡献地址么，希望可以参与贡献

**Comment by star7th** [comment]
UA目前是固定死的，没让用户自定义。后面再考虑吧。修改ua会略麻烦。

**Comment by star7th** [comment]
已更新客户端，重新下载安装包即可 https://www.showdoc.com.cn/runapi
