### ISSUE TITLE
请教权限问题

### ISSUE THREAD

**Issue by MrXieH** [star7th/showdoc#1811]
普通项目成员只能删除自己发布的内容，但却能删除整个目录，删除整个目录则目录中的内容都会被删除，包含不是自己发布的内容~

**Comment by star7th** [comment]
是的，不然权限太麻烦太乱了，所以目录那里不区分是谁创建的。

**Comment by star7th** [comment]
我建议，如果想严格控制权限，就只给一个目录的权限，或者只读权限

**Comment by MrXieH** [comment]
谢谢回复。 本身是想做到 #1790 这样的控制，但目前无法做到。  尝试了一下创建同样的用户多个团队分开权限控制，权限也不会重叠。
