### ISSUE TITLE
编辑器的保存问题

### ISSUE THREAD

**Issue by twxstar** [star7th/showdoc#1812]
当内容中如下内容：
if(!strcmp(pStr,"auto"))
点击保存的时候，页面会一直转圈，处于保存中。超时后无法保存内容

**Comment by star7th** [comment]
大概率是你们公司网络的安全限制。比较说检测到一些特殊字符，就断开你的网络链接。你尝试用其他网络，或者用代理试一下。如果还有问题，可以查看网络返回什么

**Comment by twxstar** [comment]
更换了下网络，还是有这个问题。
![企业微信截图_16682139974651](https://user-images.githubusercontent.com/10843898/201448350-4d7024c3-6435-4e10-9066-168b8eb3d0d9.png)
查看了下，返回的是405.  服务器使用了nginx的域名转发，部署方式是用docker。是不是nginx上有什么限制

**Comment by star7th** [comment]
绑定域名尝试按照这个教程来 https://www.showdoc.com.cn/help/7240953917068087

**Comment by twxstar** [comment]
域名部署没问题
问题出在内容里，内容里包含strcmp ，只要改个strcmp1就可以保存
然后我查了下，strcmp是php里面的函数。感觉上提交保存的时候，后台api在解析内容里的strcmp这个函数，不知道是不是这个问题

**Comment by star7th** [comment]
看一下响应的具体内容，不要只看返回码。

peterwang ***@***.***>于2022年11月13日 周日上午11:20写道：

**Comment by star7th** [comment]
还有就是尝试不用nginx，直接访问docker端口。如果docker可以，证明跟php没关系。

Chen Xing ***@***.***>于2022年11月13日 周日下午12:08写道：

**Comment by twxstar** [comment]
感谢回答
问题已经定位到了，是阿里云服务器的防火墙对敏感字有过滤
![企业微信截图_16683181497738](https://user-images.githubusercontent.com/10843898/201507702-f1772a51-4c3a-4982-9108-5f4e76bcb27a.png)
