### ISSUE TITLE
能否通过路由将请求转发到showdoc服务器

### ISSUE THREAD

**Issue by brickmove** [star7th/showdoc#1813]
比如showdoc部署在A服务器，此时访问地址为http://hostA:4999/web/#/user/login
通过B服务器转发之后地址为http://hostB/api/#/user/login

实测在B服务器上用apisix做路由转发到上游A服务器的showdoc会出现`Sqlite/showdoc.db.php文件不可写`的报错

**Comment by star7th** [comment]
可以转发； 
出现Sqlite/showdoc.db.php文件不可写的报错是因为文件不可写，跟转发没关系。建议你先不用转发，先确保A服务器完完全全能正常创建和编辑文档

**Comment by star7th** [comment]
绑定域名可以参考这个文档 https://www.showdoc.com.cn/help/7240953917068087

**Comment by star7th** [comment]
#符号后面的参数是不能去掉的。开源版固有属性。官方是通过各种方式去掉了。没有将此功能包含在开源版
