### ISSUE TITLE
showdoc.db.php文件为0KB：在编辑文档时出现错误后，排查问题发现该文件异常，请问数据还能恢复吗？

### ISSUE THREAD

**Issue by yeqinfang** [star7th/showdoc#1815]
你好，我的showdoc私有环境出现问题了，情况如下：

环境情况：
1、使用phpstudy_pro在win10搭建的本地测试环境
2、登录后新建了几个项目，而且编辑保存了很多文档，但远远没有达到磁盘容量

BUG情况：
1、在一次编辑过程中，出现错误，要求重新登录
2、发现无法登录
3、排查发现showdoc.db.php文件为0KB

我想了解的是，我还能恢复之前的数据吗？

**Comment by star7th** [comment]
从没有遇到过或者听说过此文件会变成0kb的情况，也没有其他人反馈过。不太清楚怎么搞的。大概率跟你的系统有关。0kb意味着没数据，不可能恢复。默认情况下，该文件一开始安装就有几百k。

yeqinfang ***@***.***>于2022年11月20日 周日上午11:14写道：
