### ISSUE TITLE
登录页面可以添加地址保存功能吗？

### ISSUE THREAD

**Issue by yundada123** [star7th/showdoc#1816]
[
![image](https://user-images.githubusercontent.com/20831794/202887370-a5ffd301-5bc2-4e78-a1b6-ec361ccfd0f4.png)
](url)
在填写私有地址的时候能否主动保存一下登录过的地址，每次打开都需要输入 ，多个私有地址的情况下   需要切换和多次重复的操作。

**Comment by star7th** [comment]
设置之初就只考虑单个服务端的情况。不考虑多个的情况。建议你新建不同的项目来区分不同场景。而不是用不同的服务器。

枯木老妖 ***@***.***>于2022年11月20日 周日下午1:40写道：
