### ISSUE TITLE
为啥没有更新推送了？

### ISSUE THREAD

**Issue by kileroppo** [star7th/showdoc#1818]

**Comment by star7th** [comment]
你如果是指showdoc管理后台的程序更新。大一点的更新才会推送。小修小补不推送。
另外最近都没做什么大更新。迟点把ui重构下。

**Comment by kileroppo** [comment]
意思上次发版到现在都在重构ui吗 还有想提的一点建议，能加上全局tag吗，类似于macos的，这样找东西能从更多维度去找

**Comment by star7th** [comment]
从上次发版到现在都在忙另一个项目。忙了挺久。除此之外showdoc也在重构UI 。所以比较多工作量。

**Comment by star7th** [comment]
全局tab短期内不考虑，因为会对整个交互提出比较大的挑战。建议暂时先多利用全局搜素功能。

**Comment by kileroppo** [comment]
好的 谢谢
