### ISSUE TITLE
项目设置密码之后匿名访问项目链接依然可以浏览项目文档

### ISSUE THREAD

**Issue by liuzhe1985** [star7th/showdoc#182]
我是在本地自己搭建的环境，项目设置密码之后，在另一个浏览器匿名访问项目路径依然可以浏览项目，感觉密码没起作用，这是为什么呢？
匿名访问的本地链接为http://local.showdoc.com/index.php?s=/Home/Item/setting/item_id/2

**Comment by liuzhe1985** [comment]
现在又可以了，不知道是不是缓存的问题~

**Comment by star7th** [comment]
已经多次测试过此功能，确定没问题。你检测下自己的设置。

**Comment by liuzhe1985** [comment]
感谢回复，我重新登录一次之后好用了，我觉得是缓存的问题吧~
因为之前项目没设置密码的时候我用同一个浏览器访问过~

**Comment by star7th** [comment]
是session记住了访问权限。因此总不能每刷新一次页面都读取数据库判断一次
