### ISSUE TITLE
宝塔面板添加好网站、域名、证书如何详细设置？

### ISSUE THREAD

**Issue by ghost** [star7th/showdoc#1820]
showdoc 如何用域名不加端口打开，带https。看不懂官方教程。

**Comment by ooelisha** [comment]
server {
    listen       80;
    server_name  test.showdoc.com.cn;
    client_max_body_size 1000m;
    location ^~ / {
        proxy_pass http://127.0.0.1:4999/;
        proxy_redirect off;
        proxy_connect_timeout 90;
        proxy_send_timeout 90;
        proxy_read_timeout 90;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header http_user_agent $http_user_agent;
    }
}
放到哪个地方呢

**Comment by star7th** [comment]
这个超出showdoc的范畴了。不是配置showdoc，而是你要学会怎么配置nginx 。去网络搜索nginx怎么配置https访问。这种通用部署网站能力，所有网站都这么干，不只是showdoc 。我总不能连  怎么安装nginx都教你吧。你自己的服务器要自己配置，跟showdoc没有关系。

**Comment by ooelisha** [comment]
唉

**Comment by gaoxianghua** [comment]
去学一下nginx和docker

**Comment by sunnyqa233** [comment]
你都用宝塔了就直接在宝塔创建网站和使用证书， 然后把你下面这串塞进宝塔网站的伪静态里就好了。
```
location ^~ / {
proxy_pass http://127.0.0.1:4999/;
proxy_redirect off;
proxy_connect_timeout 90;
proxy_send_timeout 90;
proxy_read_timeout 90;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header http_user_agent $http_user_agent;
}
```
