### ISSUE TITLE
复制过去的文件还需要关闭4999吗

### ISSUE THREAD

**Issue by ooelisha2** [star7th/showdoc#1821]
我用宝塔搭建了nginx，建立了一个网站并开启了https。脚本安装的showdoc，html文件夹下所有文件剪贴到/www/wwwroot/xxxx.com 文件夹下，还需要关闭4999吗。现在带https的新域名能打开showdoc了，且不带4999。

**Comment by star7th** [comment]
不需要4999了

**Comment by star7th** [comment]
你这种做法等于绕过了脚本安装的showdoc （安装了但是不用之）。直接用宝塔的nginx搭建。这个你自己可以看着处理。

**Comment by ooelisha2** [comment]
现在我访问https://xxxx.com 可以直接打开主页和后台，那我去把4999端口关闭了。其他不用改了吧。

**Comment by star7th** [comment]
大概是吧。我只能对自动脚本安装的负责。你自己自行用宝塔安装的，我只能猜测是这样

**Comment by ooelisha2** [comment]
另外这个可以像gitbook 那样装魔板吗？

**Comment by ooelisha2** [comment]
![xxxxx](https://user-images.githubusercontent.com/119152378/204123455-f875b8f6-7b89-4121-99c3-a0d40b0e7a9b.png)

**Comment by star7th** [comment]
没有自定义模板
