### ISSUE TITLE
希望能加入mysql支持

### ISSUE THREAD

**Issue by zywayh** [star7th/showdoc#1826]
如题，希望能加入mysql支持。
目前公司内，开发和运维完全是分开的，运维部门对mysql有完善的备份和恢复方案，并且保障数据安全，对showdoc自己弄的数据文件，运维部门还需要针对这个单独处理，不是特别现实，再就是哪天硬盘挂了，是灾难性的。还是希望能支持mysql。

**Comment by star7th** [comment]
写个定时脚本而已，定时备份文件，很容易。
showdoc要支持mysql实在太麻烦了，以后开发什么功能，都要测试两种数据库，所有工作量都乘以两倍。在目前免费开源的模式，永远不会支持mysql。假如以后有针对企业的收费版再考虑支持。

zywayh ***@***.***>于2022年12月4日 周日下午4:46写道：

**Comment by star7th** [comment]
如果你们有足够的预算去推动开发mysql版本，则可以谈。如果只打算免费使用，可能我不太愿意突然给自己增加两倍工作量。

Chen Xing ***@***.***>于2022年12月4日 周日下午5:09写道：

**Comment by zywayh** [comment]
明白了，感谢回复，要是java就好了，我也能参与维护，对php不熟悉
