### ISSUE TITLE
后台管理历史版本修改不起作用

### ISSUE THREAD

**Issue by lenjou** [star7th/showdoc#1828]

**Comment by star7th** [comment]
后台管理没有历史版本修改功能

**Comment by lenjou** [comment]
![image](https://user-images.githubusercontent.com/75348353/206121264-05add9a9-0df1-480f-896d-6c8ace1c09a0.png)

**Comment by lenjou** [comment]
就是上面那历史版本数量，修改了没反应，前台展示

**Comment by star7th** [comment]
刚才试了一下，可以修改。

**Comment by star7th** [comment]
要输入纯数字

**Comment by lenjou** [comment]
![image](https://user-images.githubusercontent.com/75348353/206122201-970e72b8-7448-4083-9bcb-c549c1f3388c.png)

**Comment by lenjou** [comment]
跟这历史版本有关系么？我后台修改为0，但前端还能搜到

**Comment by star7th** [comment]
新修改只会影响新增数据，不会影响历史已经存在的数据

**Comment by star7th** [comment]
印象中不支持直接改为0

**Comment by lenjou** [comment]
那这历史版本怎么隐藏呢，我看有些文档是没有这历史版本

**Comment by star7th** [comment]
好像没有。不想公开的话就设置密码。公开的话，默认可以给别人看历史版本的

**Comment by lenjou** [comment]
![image](https://user-images.githubusercontent.com/75348353/206131697-c4cf8b63-71e9-4976-b46b-d344c480e6c4.png)

**Comment by lenjou** [comment]
我找到了源代码我注释了历史版本，但代码没生效

**Comment by star7th** [comment]
登录台和游客态的区别。UI晚点会重写，所以不纠结此事了。

**Comment by star7th** [comment]
要二次开发，请参考这个文档  https://www.showdoc.com.cn/help/1385576954326448

**Comment by lenjou** [comment]
重写后

**Comment by star7th** [comment]
对于公开文档，大概率会放出来。

**Comment by star7th** [comment]
新版ui发布了。对游客用户隐藏了历史版本。
