### ISSUE TITLE
RunApi数据同步方式

### ISSUE THREAD

**Issue by Alexander-Chiang** [star7th/showdoc#1832]
你好，在阅读官方文档和相关代码时有些问题想请教，如下：
1. 如RunApi帮助文档所述：

> runapi的数据可以生成markdown格式，但不可逆，markdown数据很难再转换回来runapi

，那么runapi的数据是如何在同一团队中的不同用户之间同步的呢？在数据库中未找到对应数据表，这部分数据存储在哪里了？
2. runapi是否有开源计划？

**Comment by star7th** [comment]
1,没有此功能
2，无开源计划。

**Comment by star7th** [comment]
1,数据存在showdoc服务端。
2，无开源计划。
