### ISSUE TITLE
图片链接地址

### ISSUE THREAD

**Issue by ReviewClouds** [star7th/showdoc#1833]
hi

新版本中图片地址是这样的
http://ip:port/server/index.php?s=/api/attachment/visitFile&sign=f6499b221e730e3351535f08f485bb41

怎么修改让地址直接指向 639eb65ac0eb4.png

**Comment by star7th** [comment]
不提供此设置。

rd-machine ***@***.***>于2022年12月18日 周日下午3:54写道：

**Comment by ReviewClouds** [comment]
hi

1. http://ip:port/server/index.php?s=/api/attachment/visitFile/sign/9eba0e0fd7c33704b86a56d157550851&showdoc=.jpg

比如第一种地址的原图已经备份到Uploads中，ip，port 同，怎么修改才能正确显示？

**Comment by star7th** [comment]
不提供此设置。有需要的话可以自行二次开发。

rd-machine ***@***.***>于2022年12月18日 周日下午4:03写道：

**Comment by ReviewClouds** [comment]
hi
上面1中的地址，是老版本showdoc生成的，现在已经找不到这个图片了，有修复办法吗

**Comment by star7th** [comment]
很多程序都不会直接暴露源文件地址，showdoc也应当如此。不提供额外设置，有需要的可能自行二次开发。

rd-machine ***@***.***>于2022年12月18日 周日下午4:07写道：

**Comment by star7th** [comment]
你单纯备份upload是没用的。很多对应关系在数据库里。如果数据库没备份，那就等于没备份。

Chen Xing ***@***.***>于2022年12月18日 周日下午4:08写道：

**Comment by ReviewClouds** [comment]
sqlite 倒是没有差异备份，因为同时有2个版本的showdoc在正常运行， 不能单纯的直接拷贝

那如果上面这种情况，应该怎么处理才不导致数据遗漏

**Comment by star7th** [comment]
手动一张张上传到新版去吧

rd-machine ***@***.***>于2022年12月18日 周日下午4:15写道：

**Comment by ReviewClouds** [comment]
好的 感谢
