### ISSUE TITLE
能实现某个登录用户查看特定文章吗

### ISSUE THREAD

**Issue by ooelisha2** [star7th/showdoc#1834]
用户登录后显示管理员分配的私密文章或内容页面，此内容只有该登录用户能查看。n 个客户，每人登录之后都能查看自己的文章。

**Comment by star7th** [comment]
我刚看到你V站的帖子了。showdoc可以勉强实现你说的这种功能（毕竟不是专为这种场景设计，所以只能说勉强）

showdoc 的分配粒度是项目的。所以，你可以为每个用户新建不同的项目，然后分配给该用户。这样用户登录就能看到为自己分配的项目。点击进项目，便可以查看项目下的文档文章。
