### ISSUE TITLE
导出word后，直连图片url在word中显示，如果是这种AIP转换地址word是不显示图片的

### ISSUE THREAD

**Issue by tw20510946** [star7th/showdoc#1838]
很老的版本，图片都是直连的，导出word后，图片是可以显示的。
并且可以在：信息→编辑指向文件的连接→将图片保存在文档中→断开连接。等一系列操作让图片文件化后，docx文件可以便于分发。

但是现在由于上传图片是转换地址，导致word中图片都不能显示。
（确定图片上传的没问题，在页面中正常显示，图片url单独复制到浏览器也显示）

1.导出word时，能否直接图片文件化，在docx中，而不是连接。
2.转换为直连地址
![image](https://user-images.githubusercontent.com/10859313/210048978-7c48db9c-58be-483b-8e48-5d29f9f8d7f6.png)

**Comment by star7th** [comment]
导出的文档中包含图片不可取，因为那样可能会导致文件超大而失败。
目前showdoc不是很在意离线功能那块。还是主打在线功能

**Comment by tw20510946** [comment]
导出word能显示图片这个功能蛮好的。
我准备自己改造一下，不知作者是否支持。
之前的项目都是返回项目真实路径。
能否告知，在哪个PHP文件。
我准备用之前版本，部分代码替换一下。

**Comment by star7th** [comment]
无法直接替换。要二次开发请研究下代码机制
