### ISSUE TITLE
配置阿里云OSS文件上传, 不能设置目录

### ISSUE THREAD

**Issue by zxc881166** [star7th/showdoc#1839]
![image](https://user-images.githubusercontent.com/33917320/210532956-02fc9cdb-6c00-49ca-b370-e5ad5f9e9f1b.png)
比如我想上传到 bucket/aaa下面
这样配置后, 文件上传报错

**Comment by star7th** [comment]
不支持上传到目录。

阿飞 ***@***.***>于2023年1月4日 周三下午6:15写道：

**Comment by zxc881166** [comment]
这. . . 不太合理吧, 那图片全在根目录了

**Comment by star7th** [comment]
设计如此。新建一个存储桶又不用钱。

阿飞 ***@***.***>于2023年1月4日 周三下午6:20写道：

**Comment by zxc881166** [comment]
好吧
