### ISSUE TITLE
关于分享页面的权限问题

### ISSUE THREAD

**Issue by gzxuliang** [star7th/showdoc#184]
当我分享某个页面或项目时，可以手工把地址中的page或page_id参数改成其它数字，这样可以非法访问未经授权的页面。

比如：http://127.0.0.1/showdoc/index.php?s=/page/4，改成/page/5，就可以访问其它页面了。

**Comment by star7th** [comment]
那是因为你本来就是page 5的权限所有才能这样访问。没权限的人是访问不了的

**Comment by gzxuliang** [comment]
我测试的时候，是退出账号的。只要知道地址就可以访问，不知道是不是我哪里设置的有问题。

**Comment by star7th** [comment]
如果你的项目本身没设置密码，那么确实是可以被访问的

**Comment by gzxuliang** [comment]
嗯。我确实没有设置密码。但是密码好像只能设置一个，如果只需要分享某个页面，那么目前就做不到了。

谢谢了。
