### ISSUE TITLE
项目添加成员, 未知错误

### ISSUE THREAD

**Issue by zxc881166** [star7th/showdoc#1841]
![image](https://user-images.githubusercontent.com/33917320/211232135-ee617d97-f1e0-4fed-b571-a0c54c542200.png)

**Comment by star7th** [comment]
先尝试更新到最新版

**Comment by zxc881166** [comment]
![image](https://user-images.githubusercontent.com/33917320/211232551-77b91a3d-a216-4077-bb44-db8b98f5e117.png)
已经更新到最新版. 已尝试重新登录, 还是提示未知错误

**Comment by star7th** [comment]
1, 新建和删除页面功能都正常吗？
2，添加的成员是已经加过了吗

**Comment by zxc881166** [comment]
![image](https://user-images.githubusercontent.com/33917320/211232752-005eaf90-2148-41d3-a0ef-65c21e9af65f.png)
![image](https://user-images.githubusercontent.com/33917320/211232826-74774cfa-9b1c-4176-8be7-3c68c7195c62.png)
![image](https://user-images.githubusercontent.com/33917320/211232870-93e7acb9-d7ef-4e87-9a1f-7a9923469644.png)

新建, 编辑, 删除正常, 上周添加成员还可以呢, 这周就不行了

**Comment by zxc881166** [comment]
抱歉, 不好意思, 大意了, 已经加过了, 只显示2条, 我同事加过了, 有滚动条, 没有看到, 我以为还是我加的, 只有2个人, 感觉这个框可以大点, 或者提示在明确一些,
![image](https://user-images.githubusercontent.com/33917320/211233171-e30e5a56-d489-4b78-b8a2-3fbdc1bb0112.png)

**Comment by star7th** [comment]
后面可能打算重设计这个界面

**Comment by zxc881166** [comment]
好的, 期待ing

**Comment by star7th** [comment]
新版已经重设计这个页面了。
