### ISSUE TITLE
群晖docker部署showdoc的装载路径

### ISSUE THREAD

**Issue by RivieraS** [star7th/showdoc#1850]
群晖docker部署showdoc的装载路径应该怎么填，才能在file station中看到showdoc的文件？
目前是这么配
<img width="443" alt="image" src="https://user-images.githubusercontent.com/13445030/218414395-100607a2-caa0-4b09-b9cc-9e6c5fcd41b1.png">

**Comment by star7th** [comment]
没用过群晖，不知道怎么填。通用逻辑上，就是把文件映射到本地磁盘。

**Comment by RivieraS** [comment]
你好，根目录的完整路径是？

**Comment by star7th** [comment]
把宿主机的某个目录（可以自定义，只要确认有写入权限）挂载到容器内部的 /var/ww/html/

**Comment by RivieraS** [comment]
经提醒，原来是权限问题，打开权限后所以文档都可见。十分感谢！
