### ISSUE TITLE
[Bug]从示例界面跳转登录,会导致页面假死

### ISSUE THREAD

**Issue by rolitter** [star7th/showdoc#1851]
从示例界面跳转登录,会导致页面假死
https://www.showdoc.com.cn/demo/7
![image](https://user-images.githubusercontent.com/27326998/218651924-d4b98a7c-2b69-4881-8cb1-b7c6435cf37c.png)
![showdoc](https://user-images.githubusercontent.com/27326998/218652184-add06aa6-0f17-411a-accf-3fa2ec3a2162.gif)

**Comment by star7th** [comment]
晚点修复这个问题。我的预想中，用户是点击右上角的登录按钮的。没想到左下角的按钮。

**Comment by star7th** [comment]
已发布新版，修复了此问题
