### ISSUE TITLE
代码被自动重新转码

### ISSUE THREAD

**Issue by Mydingyan** [star7th/showdoc#1852]
编辑器保存后，代码被转码如何解决

![image](https://user-images.githubusercontent.com/37063878/218682975-09256894-dc21-4ec3-892d-4c1f9283d215.png)

**Comment by Mydingyan** [comment]
版本：3.0.0

**Comment by star7th** [comment]
现在提交代码了。你更新试下。另外历史数据，只能手动纠正下。对新的数据，应该可以了。

**Comment by Mydingyan** [comment]
> 现在提交代码了。你更新试下。另外历史数据，只能手动纠正下。对新的数据，应该可以了。

验证OK
