### ISSUE TITLE
3.0.1一些bug提交

### ISSUE THREAD

**Issue by zhoubai996** [star7th/showdoc#1853]
1.操作：进入编辑页面，点击全屏按钮进入全屏状态，再按Esc键退出全屏
现象：不会退回编辑页面状态，而是直接退回页面浏览展示页面，且上方编辑等按钮无法点击
2.操作：进入编辑页面，点击全屏按钮进入全屏
现象：保存按钮偶尔显示，经常不显示

**Comment by star7th** [comment]
因为编辑页面弹出默认监听esc事件了。我晚点去掉监听就不会冲突了。

**Comment by star7th** [comment]
已修复问题。

**Comment by star7th** [comment]
已修复esc快捷键的问题

**Comment by zhoubai996** [comment]
好的，大大辛苦了
