### ISSUE TITLE
docker升级最新版后PHP报错

### ISSUE THREAD

**Issue by NagaseKouichi** [star7th/showdoc#1854]
docker升级最新版后，打开showdoc首页显示：

![image](https://user-images.githubusercontent.com/53267025/218947084-9ecf286b-bc70-451a-b5c2-56e4992ea402.png)

日志中提示：

NOTICE: PHP message: PHP Fatal error:  Cannot acquire reference to $GLOBALS in /var/www/html/server/ThinkPHP/Common/functions.php on line 331
NOTICE: PHP message: PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/html/server/ThinkPHP/Library/Think/Log.class.php on line 52

请问应该怎么解决呢

**Comment by star7th** [comment]
按照官方文档操作是不会有这样的错误的。请确保按官方文档操作 https://www.showdoc.com.cn/help/65610

**Comment by NagaseKouichi** [comment]
> 按照官方文档操作是不会有这样的错误的。请确保按官方文档操作 https://www.showdoc.com.cn/help/65610

原来需要重新安装之后再迁移数据，我之前是用watchtower自动更新的。
谢谢，解决了
