### ISSUE TITLE
showdoc更新3.0.1版本后，runapi上项目不显示

### ISSUE THREAD

**Issue by chenliang2012** [star7th/showdoc#1855]
![image](https://user-images.githubusercontent.com/52647642/219248542-41f4dca3-6a39-412f-ac52-07a7b11936cb.png)
在更新showdoc3.0.1版本后，在showdoc上runpai项目能正常展示，但是在runapi上的项目不展示，而且接口调试上选不了项目了。

**Comment by star7th** [comment]
你是怎么升级的？去网页上操作一下showdoc，看 新建项目和新建页面正常不

**Comment by chenliang2012** [comment]
> 


> 你是怎么升级的？去网页上操作一下showdoc，看 新建项目和新建页面正常不

我是docker方式升级的，在showdoc上能新建项目和页面，但是在runapi上不行，新建不了项目

**Comment by star7th** [comment]
现在修复了。你更新下。

其实代码没啥问题。主要是构建的docker镜像有问题。我在1月30日的时候，修改了docker基础镜像，使用了更高版本的php运行环境（php8.2) ，从而有一点点的兼容问题。所以过去十几天里，这个问题就一直存在了。只是说没什么大改，很多用户没有升级。
但这次发布3.0.1版后，很多用户升级了。所以出现了你说的问题。
现在我重新构建docker镜像了，你再按教程升级即可，或者手动拉取最新镜像。

**Comment by chenliang2012** [comment]
> 现在修复了。你更新下。
> 
> 其实代码没啥问题。主要是构建的docker镜像有问题。我在1月30日的时候，修改了docker基础镜像，使用了更高版本的php运行环境（php8.2) ，从而有一点点的兼容问题。所以过去十几天里，这个问题就一直存在了。只是说没什么大改，很多用户没有升级。 但这次发布3.0.1版后，很多用户升级了。所以出现了你说的问题。 现在我重新构建docker镜像了，你再按教程升级即可，或者手动拉取最新镜像。

好的，我升级后试下

**Comment by chenliang2012** [comment]
正常了，感谢！
