### ISSUE TITLE
使用docker升级后并无变化

### ISSUE THREAD

**Issue by InfraBackend** [star7th/showdoc#1856]
<img width="849" alt="image" src="https://user-images.githubusercontent.com/42115674/219269303-1343fa25-b690-4d09-bbc1-c9264f29331c.png">
按照该步骤进行升级，升级后不是3.0版本的UI，还是跟以前一样

**Comment by star7th** [comment]
把你命令行里的操作记录发出来看看

**Comment by InfraBackend** [comment]
<img width="731" alt="image" src="https://user-images.githubusercontent.com/42115674/219281826-0b0a2c58-3ff3-472e-96ee-2f24ed14f670.png">
<img width="606" alt="image" src="https://user-images.githubusercontent.com/42115674/219281973-7f5dfef1-2814-4326-aa2c-7ad5ea6a1255.png">
<img width="1362" alt="image" src="https://user-images.githubusercontent.com/42115674/219282031-8939633d-2703-4b89-bc5b-9433891d101d.png">
