### ISSUE TITLE
别人给自己发送消息通知，但主页面看不到消息提醒 （Message Notification Improve）

### ISSUE THREAD

**Issue by feixiangzhang** [star7th/showdoc#1857]
![image](https://user-images.githubusercontent.com/3973047/219342989-3c58957b-b3e3-4b71-8d04-a68fc6d4e882.png)
主页面看不到消息提醒，还得点下拉框-我的信息 进去后才能看到，有点繁琐。

**Comment by star7th** [comment]
你这个是旧版UI ，升级一下到新版。另外，再你提醒下，我页更完善了下新UI。总之你升级就对了
