### ISSUE TITLE
1.83版本图片无法显示

### ISSUE THREAD

**Issue by xpoutman** [star7th/showdoc#186]
markdown 图片无法显示

**Comment by star7th** [comment]
刚下载github最新开发版本试了下，没有问题。

**Comment by xpoutman** [comment]
最新的开发版确实没有这个问题好想只有1.83有这个问题

**Comment by xpoutman** [comment]
@star7th 经测试这套源码存在上传漏洞，通过此漏洞可获取网站权限，建议修复一下

**Comment by star7th** [comment]
可否仔细描述下，配图也好。你这样直接说一个程序有漏洞但却不说是什么，让人有点摸不着头脑

**Comment by xpoutman** [comment]
@star7th 如图
![1111](https://user-images.githubusercontent.com/29286106/32482620-726b9aac-c3d3-11e7-9d92-5f83781dd688.jpg)
![2222](https://user-images.githubusercontent.com/29286106/32482625-7ef1d20a-c3d3-11e7-9fac-02b157582dc2.jpg)

**Comment by star7th** [comment]
已发布新版，修复了此问题
