### ISSUE TITLE
请教一个问题 用自动脚本私有化部署后 如何修改favicon.ico  谢谢

### ISSUE THREAD

**Issue by wlsDDD** [star7th/showdoc#1861]

**Comment by star7th** [comment]
自己探索。凡是要修改showdoc标识的问题，不要来问官方，问就是侵权。

wlsDDD ***@***.***>于2023年2月17日 周五下午6:04写道：

**Comment by duoxun** [comment]
感谢作者的开源。。。。关于标识，想请教下，我们目前想用这个系统给用户提供些些方便，如果上面的标识全都是showdoc，人家会以为我们是showdoc公司的，比如左上角，想问明白一点再操作，谢谢解答！
