### ISSUE TITLE
字体、颜色、截图功能

### ISSUE THREAD

**Issue by chinababy-zlj** [star7th/showdoc#1862]
我自己部署showdoc，但是无法把自己的截图粘贴上去，只能在本地保存之后上传，这样对用户来说，是否不太方便
字体和颜色也需要写一些代码才可以实现，那如果有些用户不懂，是否对于用户来说，造成不好的体验

**Comment by star7th** [comment]
showdoc可以粘贴截图。如果你无法操作，重启浏览器试试。
字体和颜色功能不考虑，因为markdown编辑里本身不支持这些功能
