### ISSUE TITLE
移动磁盘数据

### ISSUE THREAD

**Issue by Lbj557** [star7th/showdoc#1865]
我这边使用脚本安装得，现在位置在根目录下，我怎么把根目录下得文件移动到/u01下

**Comment by star7th** [comment]
# 如果你是想把数据挂载到其他目录，比如说/data1，那么，可以在/data1目录下新建一个showdoc_data/目录，
# 然后在根目录的新建一个软链接/showdoc_data到/data1/showdoc_data
# 这样既能保持跟官方教程推荐的路径一致，又能达到自定义存储的目的.
