### ISSUE TITLE
升级失败

### ISSUE THREAD

**Issue by Lbj557** [star7th/showdoc#1866]
![image](https://user-images.githubusercontent.com/80319597/221344368-aa4cba51-7fb9-4264-8bd9-788c257d3a08.png)
这个升级失败后，我该怎么做呢！

**Comment by star7th** [comment]
你的服务器docker服务有问题。这个问题引起的情况很多，跟服务器自身的权限有关，我无法猜出什么原因，且理论上跟showdoc代码无关。你可以手动安装，一步步调试看哪里出错

**Comment by Lbj557** [comment]
11
