### ISSUE TITLE
优化：增加表格背景色的自定义

### ISSUE THREAD

**Issue by duoxun** [star7th/showdoc#1867]
你好，希望能考虑增加底色的自定义，一般公司里面做都会有自己的自定义的主题色，在背景中较常用，特别是演示的时候，谢谢!

**Comment by star7th** [comment]
暂时不考虑。主题是一个牵一发动全身的东西，不是单单改个表格底色就能搞定。各种麻烦，所以不打算做了

**Comment by duoxun** [comment]
明白了，如果将来比较顺路的话，希望能安排搞下，谢谢哦！
