### ISSUE TITLE
阿里云虚机主机

### ISSUE THREAD

**Issue by wyongjian** [star7th/showdoc#1871]
在阿里云虚机主机中自动升级会报无法解压的错误，应该是路径问题引起的。是否可以考虑兼容，谢谢。
![image](https://user-images.githubusercontent.com/19405120/222315266-a335713a-381e-43d2-9f9a-cf150d654c9e.png)

**Comment by star7th** [comment]
showdoc不打算兼容任何虚拟主机，请用服务器或者docker容器。

**Comment by wyongjian** [comment]
感谢回复，有空儿了再折腾，旧版用着也没有什么问题。
