### ISSUE TITLE
图片不显示

### ISSUE THREAD

**Issue by Lbj557** [star7th/showdoc#1872]
![image](https://user-images.githubusercontent.com/80319597/222363534-88ef93cf-2ea0-48fc-9f8d-6bbe341d7cf7.png)
文中图片不显示是什么原因呢！

**Comment by star7th** [comment]
绑定域名按这个教程来 https://www.showdoc.com.cn/help/7240953917068087

**Comment by star7th** [comment]
要排除问题，你自己看看浏览器网络请求就好

**Comment by lookcompany** [comment]
![image](https://user-images.githubusercontent.com/121848086/233535191-2d33008e-5544-4ec3-bd83-fa69563e27c1.png)
![image](https://user-images.githubusercontent.com/121848086/233535227-45d68cb0-c03a-418f-a9b0-b5d44a174bb4.png)
我应该修改哪个目录下的文件的html,或者js?

**Comment by star7th** [comment]
> 

你的问题跟本issue无关，将被关闭。第三方图片的防盗链机制导致的显示问题不在showdoc的讨论范围内。

**Comment by lookcompany** [comment]
ok

**Comment by lookcompany** [comment]
/home/showdoc/html/web/index.html
