### ISSUE TITLE
【v3.0.3】item页无法删除项目

### ISSUE THREAD

**Issue by gotounix** [star7th/showdoc#1873]
删除时，提示输入登录密码，输入登录密码后，提示密码错误。
已确认密码无误。

后台管理可以正常删除。

**Comment by star7th** [comment]
在上个月，我把docker镜像里的环境升到了最新版，结果导致兼容问题。后来过了十几天才发现并回退了。

你现在所用的docker镜像，你想办法更新到官方现在的版本就好了
