### ISSUE TITLE
支持仅允许登陆用户访问（半公开模式，用户登陆后方可访问）

### ISSUE THREAD

**Issue by zhendongli** [star7th/showdoc#1877]
看过之前作者对于类似问题的回答，但每个项目都需要手工维护一个大团队的方式很不方面（开放查看权限）；
现在公司的安全策略要求必须如此，所有系统都必须经过用户登陆认证才能查看，作者能否考虑支持该功能；

**Comment by star7th** [comment]
要改成这样的机制，需要动的东西不少。考虑到性价比，我还是觉得不动了。
这种需求很少，如果有，还是推荐使用大团队的方式。
除非确实有很多用户反馈他们公司普遍采用这种策略。

**Comment by star7th** [comment]
另外就是，不需要每个项目都维护团队。维护一个就好了，一个团队可以分配到多个项目的

**Comment by youzhili** [comment]
我们也有类似需求，公司内网环境访问showdoc，但是至少需要加一层登入

**Comment by star7th** [comment]
我突然想到了一个好的办法，我只在项目展示页面拦截请求，判断登录态即可，这样的改动小。晚点加上这个改动。

**Comment by star7th** [comment]
新版已经支持后台设置全站项目需登录查看。
