### ISSUE TITLE
2.x升级到3.1后项目存在，里面数据全部为空

### ISSUE THREAD

**Issue by oyvfhp** [star7th/showdoc#1881]
2.x升级到3.1后项目存在，里面数据全部为空，请教如何处理？同时runapi也无法登陆。
@star7th   麻烦指教一下。

**Comment by oyvfhp** [comment]
![image](https://user-images.githubusercontent.com/4404279/223370307-3984d370-6520-4f1f-9fc3-c94c55621e80.png)

**Comment by star7th** [comment]
你是怎么安装的，以及怎么升级的，具体哪个版本开始升级过来的，有没有做过二次开发

**Comment by oyvfhp** [comment]
1. 使用了docker安装的，直接在后台点击了升级按钮。
2. 具体是从2.1.x升级上来的，具体我没注意看，升级后就是3.1.0
3. 没有进行过二次开发

@star7th

**Comment by oyvfhp** [comment]
![image](https://user-images.githubusercontent.com/4404279/223373301-c171dcff-a1eb-43f8-a9ec-99f36a168a28.png)
就是在这个页面点击升级

**Comment by oyvfhp** [comment]
![image](https://user-images.githubusercontent.com/4404279/223373500-353687d0-edd9-4772-a4f2-90996fafadf8.png)
项目都在，只是点击进去后就出现了第一个发给您的页面

**Comment by star7th** [comment]
试着去  /showdoc_data/html 去递归777权限，然后重启一下docker容器。

**Comment by oyvfhp** [comment]
好的，我备份一下，再进行操作一下

**Comment by oyvfhp** [comment]
![image](https://user-images.githubusercontent.com/4404279/223377205-11bd9748-d9af-48b0-88eb-1eb15a966d67.png)

@star7th  按这样操作了，重启了容器，还是一样。

**Comment by star7th** [comment]
把数据备份。然后把旧数据和容器全删掉。然后全新拉取官方镜像，安装。这个时候是个全新showdoc，应该没问题。然后，用备份的目录，覆盖掉新showdoc的/showdoc_data/html  ，然后递归777权限，然后重启一下docker容器

**Comment by oyvfhp** [comment]
升级的时候是不是把 Sqlite  删除了？ 我看到里面的数据库大小才
![image](https://user-images.githubusercontent.com/4404279/223378662-eb7d5fa5-325a-4ef6-9230-0e57828e7137.png)

**Comment by oyvfhp** [comment]
我之前看这个数据库大小很大的，按M计算，是不是说明。。。。。

**Comment by star7th** [comment]
/showdoc_data/ 下应该能找到 htmlxxxx之类的备份

**Comment by star7th** [comment]
先备份好再操作我说的。

**Comment by oyvfhp** [comment]
恩，我去操作一下，刚看了一下，没有备份，就刚才操作第一步时，我备份了一个操作。
![image](https://user-images.githubusercontent.com/4404279/223380486-d3c11c73-7b47-4b8e-b20b-192566e6929c.png)

**Comment by oyvfhp** [comment]
![image](https://user-images.githubusercontent.com/4404279/223381911-52cd6a89-94ed-4a36-8a50-131a177934d1.png)


@star7th   我注册表中只看到2.9.6，我用的是群晖

**Comment by oyvfhp** [comment]
我能不能用同样的方式退到2.9.6？

**Comment by oyvfhp** [comment]
https://registry.hub.docker.com/r/star7th/showdoc/

**Comment by star7th** [comment]
我没有群晖，不懂群晖相关操作。
你用你第一个的备案，来实施我上面的操作吧。

把数据备份。然后把旧数据和容器全删掉。然后全新拉取官方镜像，安装。这个时候是个全新showdoc，应该没问题。然后，用备份的目录，覆盖掉新showdoc的/showdoc_data/html ，然后递归777权限，然后重启一下docker容器

**Comment by oyvfhp** [comment]
好的，正在操作中，操作后再给您信息，麻烦您了。

**Comment by oyvfhp** [comment]
![image](https://user-images.githubusercontent.com/4404279/223390633-4984a5c0-1597-4147-82da-72844280d7b1.png)
按这个方式操作了，拉了一个新的3.1，重启了，这样目录也没有了
![image](https://user-images.githubusercontent.com/4404279/223390967-759cdf7f-b583-4c50-a749-2a6720248edc.png)

**Comment by oyvfhp** [comment]
之前是3000，现在用的端口是3001

**Comment by star7th** [comment]
1，确认你的备份里的showdoc.db.php的有数据的，其大小单位是M而不是原始的252K
2,  确认你用备份的数据覆盖了/showdoc_data/html 。可以去看看/showdoc_data/html/Sqlite/showdoc.db.php的文件大小来确认。
3，如果确认了上面两步的showdoc.db.php都是有数据的，大小单位都是M ，那么，就是你的群晖机制问题了。跟showdoc没有关系。它没有正确地把本地文件映射到容器，或者映射进去没有读写权限。

**Comment by star7th** [comment]
我非常建议你使用linux服务器来建立showdoc 。我不保证群晖下的使用不出问题。

**Comment by oyvfhp** [comment]
1，确认你的备份里的showdoc.db.php的有数据的，其大小单位是M而不是原始的252K

这里说明一下，我从2.x升级到3.1后，showdoc.db.php已经变成了原始值的252K，但我看到项目名称还在，估计升级后是不是影响了showdoc.db.php文件？

**Comment by star7th** [comment]
升级肯定要影响数据库文件的。大概率是没有写权限导致有问题。

Mijon ***@***.***>于2023年3月7日 周二下午7:38写道：

**Comment by oyvfhp** [comment]
我发现  /var/www/html   下也有数据库文件，是不是升级后目录变了？

<img width="884" alt="image" src="https://user-images.githubusercontent.com/4404279/223412688-e56a7459-6dc3-449f-8df9-51482c83053e.png">

**Comment by star7th** [comment]
宿主机路径：/showdoc_data/html  对应  容器内部路径：/var/www/html 

容器内部的 /showdoc_data/html 是没有使用的！只是初始代码。
突然觉得肯定你乱来映射目录。都不想理你了。不按官方教程操作的，你自己折腾去。

**Comment by oyvfhp** [comment]
真没乱映射目录，我就在后台点击了一下升级，就出现这种情况，因为我们上面很多说明文档，需要进行恢复，不然损失很大，我们可以有偿恢复，方便加一下您微信吗？

**Comment by oyvfhp** [comment]
您再理解我一下意思；
1. 点击后台界面上的升级后，/showdoc_data/html  下的 showdoc.db.php 变成了默认大小
2. 刚看到 /var/www/html 下的大小是正常的

@star7th  再帮看一下，这两个目录之间我需要怎么调整

**Comment by oyvfhp** [comment]
<img width="633" alt="image" src="https://user-images.githubusercontent.com/4404279/223425596-37079c62-adab-40f5-a4a5-875f6b2961d3.png">
就是在这个时间进行后台点击升级的

**Comment by star7th** [comment]
容器内部的/showdoc_data/html/Sqlite/showdoc.db.php ，变成默认大小是正常现象。注意是容器内，不是宿主机。

宿主机的/showdoc_data/html/Sqlite/showdoc.db.php，应该是十几M，且宿主机的/showdoc_data/html/Sqlite/showdoc.db.php  对应着容器内部的/var/www/html/Sqlite/showdoc.db.php ，这两者都应该是十几M 。

如果你宿主机下没有/showdoc_data/html/ 这个路径，那我不知道你把目录映射到哪里去了。官方的教程里推荐的是映射到宿主机的/showdoc_data/html/ 。

从你的上一个截图来看，showdoc.db.php 文件是16.4M ，那就应该是正常的有数据的文件。这样情况下应该访问正常。

先谈定吧。从你截图来看，备份数据是有的，丢不了。就看怎么拿出来。

我需要你详细描述你是怎么安装的，映射的目录是什么，把群晖上跟showdoc有关的配置截图发出来看看。

**Comment by oyvfhp** [comment]
我安装没有将目录映射到宿主机，都在容器内，因安装前不知道具体目录，所以没有映射。
<img width="564" alt="image" src="https://user-images.githubusercontent.com/4404279/223449039-7b33e9df-867e-45c6-8853-50bd24831cd9.png">
您所说的showdoc有关的配置，具体是需要那些配置，我给您截图看。

**Comment by oyvfhp** [comment]
如果实在不行，您可以告诉一下我，如何将/var/www/html/Sqlite/showdoc.db.php的数据恢复回去，这也是个办法。

**Comment by star7th** [comment]
你没有映射目录出来？ 那容器挂了的话，数据就没了！

你公司真是乱来，重要数据都敢这么搞。所以为啥有些公司即使有自建服务，也依然用官网在线服务，是因为他们觉得由showdoc官方维护，比他们自己折腾要安全稳定得多。

你现在访问是什么情况，是完全没数据，还是说，有项目列表数据，但是项目展示页是空的？

**Comment by oyvfhp** [comment]
之前不知道要映射那个目录，安装github我就把目录映射出来了，现在是项目列表数据有数据，点击进去是空的。

**Comment by star7th** [comment]
把你微信号发我邮箱，邮箱在这里能找到 https://github.com/star7th  。赶紧的。我要休息

**Comment by oyvfhp** [comment]
好的，麻烦您好。

**Comment by star7th** [comment]
没有收到。你在这里发吧。晚点你再自己删来保护隐私。

**Comment by oyvfhp** [comment]
好的，微信号：mijons
