### ISSUE TITLE
前执行脚本的执行顺序

### ISSUE THREAD

**Issue by 581cFz** [star7th/showdoc#1886]
您好，
当前项目需要将body中的参数做一个排序、拼接、加密的处理，然后形成一个新的参数添加到body中。
但是当在前执行脚本中操作body参数时，发现body中参数值设置为变量的参数，值还为变量的样式，不是变量值内容。
不知道可不可以调整前执行脚本的执行顺序？
<img width="420" alt="image" src="https://user-images.githubusercontent.com/47130937/223638793-1f1ee851-a4f0-49b0-b143-57081e23b9a8.png">

**Comment by star7th** [comment]
当初是出于这样的考虑：

用户很可能会在前执行脚本中修改环境变量的。修改完环境变量后，我再用新值来填充，这样比较好。

我建议你当前这么处理：获取环境变量里的openid  ，自己手动把“{{openid}}”这个字符串替换成你想要的值

**Comment by 581cFz** [comment]
好的谢谢您
