### ISSUE TITLE
v3.1.0项目分组功能

### ISSUE THREAD

**Issue by hanxu00920** [star7th/showdoc#1889]
版本 : v3.1.0
php : PHP 5.4.16 (cli) (built: Apr  1 2020 04:07:17) 
nginx : nginx/1.22.1

可以通过index页面分组栏目的+号增加、删除、修改分组。
但是点击创建号的分组，再创建项目还是会放到所有项目下，放不到新增的组里。

**Comment by star7th** [comment]
所有项目 就是显示所有项目的，无论有没有分组，这里都会显示全部项目。

创建分组的功能，我测试过是ok的，其他人也没反应过有问题。所以大概率跟你的环境有关。你可以看下你的网络返回有没有什么错误。不然，请提供外网可重现例子我看看。

**Comment by hanxu00920** [comment]
是我理解错了，创建分组的时候才可以勾选项目，选择分组后点击创建新项目也和当前展示的分组无关😂
