### ISSUE TITLE
关于我添加用户之后没有找到用户的信息表和全新控制表

### ISSUE THREAD

**Issue by carl-leopard** [star7th/showdoc#189]
准备使用showdoc作为团队的共享文档， 自己部署到服务器。目前在研究阶段。 在我安装注册成功之后， 我希望拿掉注册功能， 使用管理员手动添加用户的操作。 但是我没有找到用户信息表， 用户权限控制表。 望解答。
sqlite> .database
seq  name             file
---  ---------------  ----------------------------------------------------------
0    main
sqlite> .tables
sqlite>
但是在项目里面是看到至少应该有一个user表的。 求大神解答。 本人没学过php，sqlite。 (ˇˍˇ) 想～

**Comment by star7th** [comment]
里面确实有个user表。你没找到的话证明你打开的文件不对
