### ISSUE TITLE
私有部署版团队添加项目报错

### ISSUE THREAD

**Issue by zwy66666** [star7th/showdoc#1890]
私有部署版团队添加项目报错
如图
![批注 2023-03-10 084516](https://user-images.githubusercontent.com/96455554/224196623-404077a5-fe48-435e-a26d-48dd8663b570.png)
![批注 2023-03-10 084555](https://user-images.githubusercontent.com/96455554/224196629-6d383ca2-38e6-4c8f-9c81-3cec30d6232c.png)

**Comment by star7th** [comment]
win教程里不是提到了 要开启扩展吗  

https://www.showdoc.com.cn/help/4087044677189279

点击右边按钮“管理”-“php扩展”，确保”php-pdo-sqlite”和”php-sqlite3”开启。

**Comment by zwy66666** [comment]
嗷明白了，
还有一个问题，
windows下的Sqlite 
不能在linux docker 下使用吗

**Comment by star7th** [comment]
应该能吧，不清楚，你自己去试

zwy66666 ***@***.***>于2023年3月10日 周五上午9:53写道：

**Comment by zwy66666** [comment]
试了不好使.
拿docker部署的，
挂载目录下的Sqlite替换了,
还是初始目录

**Comment by star7th** [comment]
你自己探索吧。多看文档。我没试过把win移到linux。

zwy66666 ***@***.***>于2023年3月10日 周五上午9:59写道：

**Comment by zwy66666** [comment]
好
