### ISSUE TITLE
关于修改域名后附件及文件库链接错误问题

### ISSUE THREAD

**Issue by wxtanker** [star7th/showdoc#1891]
按照官方教程修改域名之后，页面中图片及文件显示正常，如下图：
![image](https://user-images.githubusercontent.com/96677987/224534068-d4dce206-8990-42e2-879a-e44b735e5adb.png)
在这里，域名后增加了/showdoc代理到showdoc服务
但是当打开附件及文件库时，发现图片及文件查看和下载功能均不能正常访问
![image](https://user-images.githubusercontent.com/96677987/224534188-dd176113-c2b4-4eb6-b47a-94b1168c6d23.png)
点击下载后跳转的链接缺少/showdoc路径，原因是如下接口：
![image](https://user-images.githubusercontent.com/96677987/224534243-007a63f5-4fcb-49b0-a4c1-9f926e5b0fea.png)
![image](https://user-images.githubusercontent.com/96677987/224534266-64564809-5e38-4478-a2c2-999f4ebd9c05.png)
接口返回了图片文件的全路径，该路径中丢失/showdoc路径
经过跟进源码发现
![image](https://user-images.githubusercontent.com/96677987/224534904-bb638857-3760-4c6f-9a70-66475a96aa65.png)
在该方法中获取了域名信息，HTTP_X_FORWARDED_HOST首先从请求中获取host
nginx配置如下
![image](https://user-images.githubusercontent.com/96677987/224534536-b11d75df-d375-4579-85a0-c44ecb81ec44.png)
proxy_set_header HTTP_X_FORWARDED_HOST $http_x_forwarded_host/showdoc; 配置后始终无效，按照我的设想，改配置生效就会走源码中第一个判断，此时域名会返回我设置的值。我的服务是脚本自动安装的，是否是docker中的nginx没有转发HTTP_X_FORWARDED_HOST这个值
在这里是否能够在nginx中不增加/server配置前提下，通过HTTP_X_FORWARDED_HOST解决这个问题

**Comment by star7th** [comment]
1，绑定域名按这个教程来 https://www.showdoc.com.cn/help/7240953917068087

2，showdoc的管理后台，网站设置，有一个选项，可以设置网站外部访问地址前缀。

**Comment by star7th** [comment]
如果是修改域名，参数这个迁移教程里对福建链接的处理 https://www.showdoc.com.cn/help/2511252204165611

**Comment by wxtanker** [comment]
> 1，绑定域名按这个教程来 https://www.showdoc.com.cn/help/7240953917068087
> 
> 2，showdoc的管理后台，网站设置，有一个选项，可以设置网站外部访问地址前缀。

用方法二解决问题，感谢回答
