### ISSUE TITLE
使用云存储的情况下，页面上删除附件无法删除云端的对应资源

### ISSUE THREAD

**Issue by KylinVnne** [star7th/showdoc#1892]
如题。
`server/Application/Api/Model/AttachmentModel.class.php `的49行至51行
```php
$real_url = $file['real_url'];
$array = explode("/Public/Uploads/", $real_url);
$file_path = "../Public/Uploads/" . $array[1];
```
测试发现这里的file_path无论如何都会返回True，导致后面的deleteOss($real_url)逻辑永远无法执行。望作者指正。

**Comment by star7th** [comment]
没懂，什么叫 file_path无论如何都会返回True， file_path 是一个变量，怎么会有返回true的说法

**Comment by star7th** [comment]
如果是说 (file_exists($file_path) ，那么，它的意思是判断本地文件是否存在，如果存在则删除本地文件。
而如果使用云存储，那本地文件不可能存在，也就是返回false.

**Comment by KylinVnne** [comment]
> 没懂，什么叫 file_path无论如何都会返回True， file_path 是一个变量，怎么会有返回true的说法

前面用了explode做分组，如果是oss文件，则array[1]是空，那么file_path会被赋值为 ../Public/Uploads/，下面的if(file_exists)判断逻辑会永远返回True，变成去unlink这个目录了，但这目录不为空的情况下是不会被删除，但是deleteoss的逻辑就不会执行了

**Comment by KylinVnne** [comment]
> 如果是说 (file_exists($file_path) ，那么，它的意思是判断本地文件是否存在，如果存在则删除本地文件。
> 而如果使用云存储，那本地文件不可能存在，也就是返回false.

是的，这个逻辑没问题。现在实际问题是如果oss文件的话，file_path被赋予了../Public/Uploads/，这个目录是一直存在的，我想这里应该需要对
 array[1]加一个空内容判断。

**Comment by star7th** [comment]
好，更新了 https://github.com/star7th/showdoc/commit/125ce1938bef2b3e6a18ecd9054db462e4f005c9
