### ISSUE TITLE
RunApi增加了header参数但没有生效

### ISSUE THREAD

**Issue by wind-labs** [star7th/showdoc#1893]
![image](https://user-images.githubusercontent.com/8413919/224888174-c4091a84-e38b-4669-a9d9-2d894a21c7b9.png)
在header里增加了个参数referer，是我没有配置正确吗？接口接收不到这个参数

**Comment by star7th** [comment]
暂未支持配置像UA ，reffer 此类浏览器级别的参数。目前只能增加业务级别的。后面再改进。
