### ISSUE TITLE
建议：在详情页面把历史版本和项目变更历史开放出来，有查看权限的也可以看到这些信息

### ISSUE THREAD

**Issue by wind-labs** [star7th/showdoc#1896]
这样可方便有查看权限的人员查看接口的变更记录，历史版本和项目变更记录也不牵扯到敏感数据，却能把编辑和查看的权限范围更明确了

**Comment by star7th** [comment]
目前权限设置如下：
有编辑权限的用户，才能看到历史版本。
有项目管理权限的，才能看到变更记录。

不打算把这两个功能下发到阅读权限。
