### ISSUE TITLE
目前使用的ThinkPHP3.2.3性能各方面都不如TP5，老版本学习成本也高，建议将代码升级到最新版本。

### ISSUE THREAD

**Issue by MaMaiGeLai** [star7th/showdoc#1906]
目前使用的ThinkPHP3.2.3性能各方面都不如TP5，老版本学习成本也高，建议将代码升级到最新版本。

**Comment by star7th** [comment]
如果不是因为兼容问题，早就转用laravel 。永远不会考虑升级到TP系列。
现在因为有历史包袱在，转的话工作量大，且没有明显必要。
现在用的这个ThinkPHP3.2.3 ，其实被我魔改了，性能很好，甚至都支持php8.
你觉得性能差的话，不如去试试官网。 https://www.showdoc.com.cn

**Comment by star7th** [comment]
说实话，就我魔改后的性能表现，比laravel 和TP5都好。维护成本高倒是真的包袱。

**Comment by MaMaiGeLai** [comment]
感谢及时回复！
因为公司需求，需要二次开发，githup的源码也是经过魔改的么，我这边下载githup源码部署后查询稍有点慢。支持PHP8还是相当6的。最主要还是语法的原因，近两年入职嘛，一开始接触就学习的ThinkPHP5，所以有这方面的顾虑。




在身后陪你微笑，，
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "star7th/showdoc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月11日(星期二) 上午10:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [star7th/showdoc] 目前使用的ThinkPHP3.2.3性能各方面都不如TP5，老版本学习成本也高，建议将代码升级到最新版本。 (Issue #1906)





 
如果不是因为兼容问题，早就转用laravel 。永远不会考虑升级到TP系列。
 现在因为有历史包袱在，转的话工作量大，且没有明显必要。
 现在用的这个ThinkPHP3.2.3 ，其实被我魔改了，性能很好，甚至都支持php8.
 你觉得性能差的话，不如去试试官网。 https://www.showdoc.com.cn

**Comment by MaMaiGeLai** [comment]
对嘛，就是这个原因，不然其实也没事，而且给新人交接工作，成本都是问题，稍稍有点遗憾。




在身后陪你微笑，，
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "star7th/showdoc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月11日(星期二) 上午10:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [star7th/showdoc] 目前使用的ThinkPHP3.2.3性能各方面都不如TP5，老版本学习成本也高，建议将代码升级到最新版本。 (Issue #1906)





 
说实话，就我魔改后的性能表现，比laravel 和TP5都好。维护成本高倒是真的包袱。

**Comment by star7th** [comment]
githup的源码也是经过魔改的 ，目前支持php8.0 .建议开启JIT 。但是，对于开源版showdoc，性能天花板定死了。因为数据库使用的是sqlite 。官网使用的是redis和mysql 。虽然代码上没差多少，但数据库架构不一样，差很多。总之不至于是代码严重影响性能。

**Comment by star7th** [comment]
数据库io差蛮多。你可以使用 php8.0 ,开启 jit ，使用ssd硬盘加快数据库读写。

**Comment by MaMaiGeLai** [comment]
这个项目已经非常完善了，就没想再继续做么，看你好久没更新了， 我倒有很多想法，例如notion一样，很多企业没法使用就是没法私有化部署，你这已经很接近了，建议继续搞下去




在身后陪你微笑，，
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "star7th/showdoc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月11日(星期二) 上午10:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [star7th/showdoc] 目前使用的ThinkPHP3.2.3性能各方面都不如TP5，老版本学习成本也高，建议将代码升级到最新版本。 (Issue #1906)





 
说实话，就我魔改后的性能表现，比laravel 和TP5都好。维护成本高倒是真的包袱。

**Comment by star7th** [comment]
啥？ github上的最后更新时间是上周，你怎么得出项目好久没更新的结论的？

**Comment by MaMaiGeLai** [comment]
这样啊，那就了解了，情有可原，哈哈，官网确实很给力




在身后陪你微笑，，
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "star7th/showdoc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月11日(星期二) 上午10:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [star7th/showdoc] 目前使用的ThinkPHP3.2.3性能各方面都不如TP5，老版本学习成本也高，建议将代码升级到最新版本。 (Issue #1906)





 
githup的源码也是经过魔改的 ，目前支持php8.0 .建议开启JIT 。但是，对于开源版showdoc，性能天花板定死了。因为数据库使用的是sqlite 。官网使用的是redis和mysql 。虽然代码上没差多少，但数据库架构不一样，差很多。总之不至于是代码严重影响性能。

**Comment by MaMaiGeLai** [comment]
嗯嗯，看到更新了，我指的是没有大的改动，官网redis+mysql的源码能共享不




在身后陪你微笑，，
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "star7th/showdoc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月11日(星期二) 上午10:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [star7th/showdoc] 目前使用的ThinkPHP3.2.3性能各方面都不如TP5，老版本学习成本也高，建议将代码升级到最新版本。 (Issue #1906)





 
数据库io差蛮多。你可以使用 php8.0 ,开启 jit ，使用ssd硬盘加快数据库读写。

**Comment by star7th** [comment]
最近的几个月都把精力放在重构这个工具上 ， 后面可以关注一下 https://www.showdoc.com.cn/runapi  

官网的redis mysql版本永远不会开源共享。增加维护复杂度。目前还没有一个公司的使用量会超越sqlite的性能上限。如果有，就是大公司了，这个时候就应该花钱找官方维护，而不是想着又白嫖。

**Comment by MaMaiGeLai** [comment]
看到了看到了，只是想提提建议哈，就是文档内部和文档之间的跳转，因为很多知识都是关联的，就不需要再到目录去找了。




在身后陪你微笑，，
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "star7th/showdoc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月11日(星期二) 上午10:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [star7th/showdoc] 目前使用的ThinkPHP3.2.3性能各方面都不如TP5，老版本学习成本也高，建议将代码升级到最新版本。 (Issue #1906)





 
啥？ github上的最后更新时间是上周，你怎么得出项目好久没更新的结论的？

**Comment by star7th** [comment]
不跟你讲太多了。有新问题再开新issue。

**Comment by MaMaiGeLai** [comment]
好的，感谢解答！十分感谢




在身后陪你微笑，，
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "star7th/showdoc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月11日(星期二) 上午10:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [star7th/showdoc] 目前使用的ThinkPHP3.2.3性能各方面都不如TP5，老版本学习成本也高，建议将代码升级到最新版本。 (Issue #1906)





 
不跟你讲太多了。有新问题再开新issue。
