### ISSUE TITLE
V3.1.0版本 表格自动保存问题

### ISSUE THREAD

**Issue by yjlwl1213** [star7th/showdoc#1908]
在表格中设置好固定的表格格式，在某单元格中设置相应的数据格式，表格是自动保存的，但返回项目列表再进入表格，单元格未显示最新的数据格式， 会提示是否需要重新编辑的弹窗

**Comment by star7th** [comment]
你在官网做一个可重现例子出来我看看 https://www.showdoc.com.cn/

**Comment by yjlwl1213** [comment]
已在官网上操作 链接为 https://www.showdoc.com.cn/2239585776364802

**Comment by star7th** [comment]
经测试，没有发现你说的问题。

**Comment by star7th** [comment]
即使我自己新建一个表格项目也未见你说的问题

**Comment by yjlwl1213** [comment]
![image](https://user-images.githubusercontent.com/8540994/232187785-85223fe2-7592-46d2-a072-cd64ae542db2.png)

**Comment by star7th** [comment]
经测试，输入 ￥ 12,520.00  能保存。我不知道如何重现你的情况。

**Comment by star7th** [comment]
大概率是出现在特殊字符这个问题上了。

**Comment by star7th** [comment]
我不知道你那边的输入是不是带了什么特殊格式。

**Comment by yjlwl1213** [comment]
不是输入的，直接选择格式
![image](https://user-images.githubusercontent.com/8540994/232196746-2f0d9eda-024b-4f15-9cd4-563bb0729285.png)

**Comment by star7th** [comment]
你手写吧。这个不知道是什么问题。showdoc在这一块功能是直接用一个开源组件的 https://github.com/myliang/x-spreadsheet 。大概率我不好修复。我个人觉得这是个很少用的功能，就不去纠结它了。
