### ISSUE TITLE
一个项目多个管理员

### ISSUE THREAD

**Issue by Cyrus414** [star7th/showdoc#191]
目前一个项目只能有一个管理员来管理项目成员，希望能支持多个管理员。
如A，B两组，A组组长是项目的创建者，他把自己组的组员都加入到项目中，他想与B组共享此项目，但是他又不想去关心B组中到底谁要加入此项目，只想把权限给B组组长，由B组组长来管理哪些成员需要加入到项目中。

**Comment by star7th** [comment]
目前还没有考虑到那么详细的权限控制
