### ISSUE TITLE
表格隐藏后，无法执行取消隐藏，导致已隐藏数据无法再次显示查看

### ISSUE THREAD

**Issue by changsa** [star7th/showdoc#1911]
表格隐藏后，无法执行取消隐藏
![image](https://user-images.githubusercontent.com/33210442/233831765-1203a90b-49d8-4716-9a4f-029db1eea79d.png)

**Comment by star7th** [comment]
showdoc在这一块功能是直接用一个开源组件的 https://github.com/myliang/x-spreadsheet 。大概率我不好修复。我个人觉得这是个很少用的功能，就不去纠结它了

**Comment by changsa** [comment]
谢谢回复，发现双击可以打开隐藏，也算是解决了问题
