### ISSUE TITLE
v1.0.5升级到3的最新版本报错3.1.1

### ISSUE THREAD

**Issue by li-lin99** [star7th/showdoc#1913]
SQLSTATE[HY000]: General error: 1 no such table: options 。错误位置：/var/www/html/server/ThinkPHP/Library/Think/Db/Driver.class.php 174

尝试覆盖ThinkPHP文件，虽然不报错，但是验证码无法支持显示

**Comment by star7th** [comment]
1.0.5应该有至少五年了吧？ 这么久远的版本，我不再维护了。不再花时间去测试它是否升级成功。单单模拟个环境来测试就很麻烦。

**Comment by star7th** [comment]
另外就是，官方教程从来没让人覆盖过ThinkPHP文件，别乱来。官方教程是让你全新安装showdoc，然后再迁移过去。推荐使用docker方式安装。

**Comment by star7th** [comment]
再看下了时间记录。是七年前的版本。这七年来你都没升级过，那我也不再维护了。
一般来讲，老用户最多两三年就升级一次到官方的版本。以保持跟官方最新版差异没那么大。你那个直接跳7年，差异太大了，升级过程中太多不可控因素了，且我不打算再花精力去排查了。

**Comment by li-lin99** [comment]
好的,这边测试将sqlite的库里面的表一一导出在导入的新的sqlite库里面就可以成功了
