### ISSUE TITLE
使用showdoc的open api如何读取一个showdoc文档？

### ISSUE THREAD

**Issue by nanhai-gvsun** [star7th/showdoc#1915]
需要做一个知识库，showdoc的页面布局不太合适，因此想单独做一个前端，调用showdoc api的方式读取指定的文档，没找到相关参考，请求帮助

**Comment by star7th** [comment]
没有开发这样的open api

**Comment by nanhai-gvsun** [comment]
https://www.showdoc.cc/server/index.php?s=/api/item/show

**Comment by star7th** [comment]
你单纯发个链接是什么意思，说人话。

**Comment by nanhai-gvsun** [comment]
我在找读取一个项目的api接口，遍历项目中的文章列表，并且读出来，主要是契合知识库的界面需要

**Comment by nanhai-gvsun** [comment]
我现在找到了index.php?s=/api/page/info和index.php?s=/api/item/info

**Comment by star7th** [comment]
我是没有把这些接口作为开放api来开放出去的，这些是showdoc程序本身使用的接口，不是开放出去的接口。你要复用的话你自己去研究showdoc的内部机制。我没有把它们当开放接口开放出来。

**Comment by nanhai-gvsun** [comment]
谢谢
