### ISSUE TITLE
docker 没有arm版本，建议增加

### ISSUE THREAD

**Issue by Lfh2msn** [star7th/showdoc#1917]
docker 没有arm版本，无法正常启动

**Comment by star7th** [comment]
showdoc是一个  服务端 软件 ，请将其安装到服务器上 。服务器上，极少arm版本。所以官方没打算支持。
https://github.com/star7th/showdoc/issues?q=is%3Aissue+arm+is%3Aclosed

**Comment by Lfh2msn** [comment]
> showdoc是一个 服务端 软件 ，请将其安装到服务器上 。服务器上，极少arm版本。所以官方没打算支持。 https://github.com/star7th/showdoc/issues?q=is%3Aissue+arm+is%3Aclosed

曾经较少，当前较多。如NAS，如苹果新M1 M2处理器，都采用ARM。

**Comment by star7th** [comment]
苹果新M1 M2处理器，都不是装在服务器的。请你表明你一定要装在mac上而不是服务器的绝对理由是什么。

**Comment by Lfh2msn** [comment]
> 苹果新M1 M2处理器，都不是装在服务器的。请你表明你一定要装在mac上而不是服务器的绝对理由是什么。

公司的各类共享文件均在内部NAS，它是ARM64架构。

**Comment by star7th** [comment]
我极少看到有公司使用nas来存放公司文件的。都是使用服务器的。nas更多是个人在用。我不清楚实际的公司使用nas的情况。不敢确定。

**Comment by star7th** [comment]
你当前可以自己手动安装arm版本的php文件，然后手动把showdoc装过去。我主要是不想增加维护成本，每个修改都要考虑向后兼容arm版本

**Comment by Lfh2msn** [comment]
可能接触面不同吧，我见到的是极多小型公司或团队内部共享环境选用的是NAS。而为了更简便运维工作，大部分选择docker。就如我的团队，自己我周边的几个团队。

**Comment by star7th** [comment]
我有空探索下吧。或者推出个arm版本，但是不承诺支持全部新功能，可能小部分功能阉割。

**Comment by Lfh2msn** [comment]
我见到许多github项目自动化部署docker镜像，而它们有些选择区分arm镜像和x86，也有一些长期兼容。
虽然我不懂这应该如何实现，也许它是可行的。

**Comment by star7th** [comment]
官方初步推出了ARM版本的docker镜像。 命令 

docker pull star7th/showdoc:arm-latest

docker run -d --name showdoc --user=root --privileged=true -p 4999:80 \
-v /showdoc_data/html:/var/www/html/ star7th/showdoc:arm-latest 


目前已知的ARM版docker镜像缺陷：
0,只能使用docker官方镜像 star7th/showdoc:arm-latest  ，可能没有大陆镜像加速
1，只支持ARM64位，应该不支持ARm32位.目前在ARM64位的centos7上安装测试已经通过，其他硬件设备由于缺乏测试环境，故尚未测试。理论上ARM64环境都可以兼容。
2，可能无法使用英文版，只能用默认的中文版
3，无法使用mock功能
4，上传图附件到云储存功能尚未测试，且没打算逐一测试各平台，不保证能支持各大云储存
5，导入中文命名的压缩包可能出错。这个问题不打算测试和处理

**Comment by Lfh2msn** [comment]
这效率，有点太6
