### ISSUE TITLE
runapi接口入参标点符号问题

### ISSUE THREAD

**Issue by JefferyTest** [star7th/showdoc#1920]
runapi里面填写的接口入参，格式为json，双引号是英文格式
![image](https://user-images.githubusercontent.com/33674804/236726411-e27575c5-af66-4ecf-ae4b-a174efb1df86.png)

showdoc里面显示的格式，双引号变成了中文格式
![image](https://user-images.githubusercontent.com/33674804/236726509-5c987714-070c-4a0a-991c-72212bf5453e.png)

**Comment by star7th** [comment]
尝试放在代码块语法 ```里面

**Comment by JefferyTest** [comment]
> 尝试放在代码块语法 ```里面

表格的截图是runapi里面的，runapi的文档，在showdoc里面不支持修改啊

**Comment by star7th** [comment]
这是一个很早就发现了的bug，且暂时找不到解决方式；问题是出在showdoc上的编辑器渲染上。那个编辑器是开源的，被原作者放弃维护了。我不好魔改。

**Comment by star7th** [comment]
我比较建议，要传json的场景，就用传递json的方式，而非表单key value方式

**Comment by JefferyTest** [comment]
> 我比较建议，要传json的场景，就用传递json的方式，而非表单key value方式

感谢作者积极回复，我也是这么想的，有些老接口不敢轻易变，这个也无伤大雅，就是看文档的时候要注意点
