### ISSUE TITLE
Minio Upload file Error

### ISSUE THREAD

**Issue by senhao-xu** [star7th/showdoc#1922]
我配置minio作为云端存储时，上传文件出现了改错误
![image](https://github.com/star7th/showdoc/assets/47684791/7293132a-72b2-4b2d-8438-55de40181108)

这是我的minio配置
![image](https://github.com/star7th/showdoc/assets/47684791/0d7a579c-8b31-41e5-b032-6bfa9e1feddb)

**Comment by senhao-xu** [comment]
![image](https://github.com/star7th/showdoc/assets/47684791/eb85cf1c-f39c-4eea-80a8-923e5fbb632e)

我在容器内是可以访问的呢

**Comment by star7th** [comment]
再看了下，那当然连不上了。docker容易是不会使用主机的hosts的

**Comment by star7th** [comment]
去上网搜一下怎么给docker容器指定hosts

**Comment by senhao-xu** [comment]
我用的是kubernetes呢

**Comment by senhao-xu** [comment]
> 去上网搜一下怎么给docker容器指定hosts

我用的kuberntes创建的服务，它们在同一个namespace下，内部通信时正常的
![image](https://github.com/star7th/showdoc/assets/47684791/8229f7f6-f4f1-45cd-a530-64fd77cf5464)

**Comment by star7th** [comment]
这个问题跟showdoc无关。你可以尝试用公有云的s3服务，是可以的。只能说你搭建的有问题

**Comment by senhao-xu** [comment]
> 

好的，我尝试排查下错误，测试了好几次都不太对，我看看minio配置问题
