### ISSUE TITLE
附件按钮能否移到一级菜单

### ISSUE THREAD

**Issue by aohun** [star7th/showdoc#1923]
![image](https://github.com/star7th/showdoc/assets/37433539/cbe2cf7e-0575-406d-a596-f39d3b327c45)
附件上传应该算是比较高频使用的按钮，发现是在文档工具的二级菜单下，比较麻烦，能否移到一级菜单？

**Comment by star7th** [comment]
showdoc是主要给IT团队协作使用的工具。我觉得你大概不是用于IT团队内部协作。如果是协作场景，附件不会是高频使用。

**Comment by aohun** [comment]
很巧的是我们就是IT协作使用，常与乙方合作，乙方提供资料时，showdoc没有直接导入docx这类功能， 只能选择上传附件



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月12日(星期五) 上午9:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [star7th/showdoc] 附件按钮能否移到一级菜单 (Issue #1923)





 
showdoc是主要给IT团队协作使用的工具。我觉得你大概不是用于IT团队内部协作。如果是协作场景，附件不会是高频使用。

**Comment by star7th** [comment]
可能你的情况是有点特殊吧。我搞了IT那么多年，showdoc的大部分群体用户不会太经常用到附件。用肯定会用到，但是不会高频。一般 像 插入接口模板 这些功能比较高频。

**Comment by aohun** [comment]
接口肯定是高频，但是乙方格式不一样，并不能第一时间去整理成标准接口格式，此时先上传附件，后续再整理是个不错的选择。我记得以前的版本是在编辑页直接可以上传附件的（也许记错了？）



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月12日(星期五) 上午9:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [star7th/showdoc] 附件按钮能否移到一级菜单 (Issue #1923)





 
可能你的情况是有点特殊吧。我搞了IT那么多年，showdoc的大部分群体用户不会太经常用到附件。用肯定会用到，但是不会高频。一般 像 插入接口模板 这些功能比较高频。

**Comment by star7th** [comment]
旧版是这样的。新版设计就统一收起来了。其实我也想过把按钮平铺开来。但这个需要再看看吧。
可能后面对整体UI又来个大翻修，这种细节问题可能一起处理掉

**Comment by aohun** [comment]
好的，最通用的方式可能是按钮自定义，不过重构这种会很麻烦




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月12日(星期五) 上午9:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [star7th/showdoc] 附件按钮能否移到一级菜单 (Issue #1923)





 
旧版是这样的。新版设计就统一收起来了。其实我也想过把按钮平铺开来。但这个需要再看看吧。
 可能后面对整体UI又来个大翻修，这种细节问题可能一起处理掉

**Comment by cnkikd** [comment]
虽然 我们公司不搞IT  但附件这个功能确实很需要，我们常用的PDF 有MD里面无法插入，不像HTML可以在线预览。所以我们也只能上传到附近里面。至于在一级或者二级这个到无所谓。

**Comment by star7th** [comment]
新版已经重新放出附件按钮
