### ISSUE TITLE
SQLSTATE[HY000]: General error: 26 file is not a database  数据库迁移

### ISSUE THREAD

**Issue by xiaohui1997** [star7th/showdoc#1925]
问题: 数据库迁移到新的服务器后出现如下报错，新服务器代码使用的是最新代码。
接口地址:  http://showdoc1.fanye.tk/server/index.php?s=/api/user/info
error_code
: 
999
error_message
: 
"SQLSTATE[HY000]: General error: 26 file is not a database 。错误位置：/www/wwwroot/showdoc/server/ThinkPHP/Library/Think/Db/Driver.class.php  174"

**Comment by star7th** [comment]
如果你以FTP方式上传代码到服务器，那么请使用二进制模式上传，否则会损害数据库文件，导致此错误提示

**Comment by xiaohui1997** [comment]
好的谢谢
