### ISSUE TITLE
关于接口覆盖问题，需要使用api接口删除文档的问题

### ISSUE THREAD

**Issue by 1314520lfd** [star7th/showdoc#1926]
删除页面或者项目的    api接口地址是啥，需要带哪些参数呢？

**Comment by star7th** [comment]
showdoc没有开放接口删除文档。

**Comment by 1314520lfd** [comment]
我梅生成一次新文档，都会产生新的目录，而不会覆盖，导致文档冗余，而且配置文件也配置了coverOld：true，这该怎么办呢

**Comment by star7th** [comment]
目录名相同是会覆盖的。不清楚你的为什么不会。你可以用官网试试
