### ISSUE TITLE
建议UI调整一下

### ISSUE THREAD

**Issue by Clpy** [star7th/showdoc#1928]
![image](https://github.com/star7th/showdoc/assets/38339426/7d3cf3d2-d8b7-451a-9bcb-6b430b86f89d)
左边这里太空荡荡的空，文档目录靠左一些比较好，有的电脑分辨率太低，导致一些文档的右边标题栏无法正常显示

**Comment by Clpy** [comment]
![image](https://github.com/star7th/showdoc/assets/38339426/160f6ea0-9f60-4735-9a40-bb7da69a1c77)

**Comment by star7th** [comment]
几个月后可能还会整体重现设计一版UI，所以当下这个就不改了

**Comment by iefc** [comment]
> 
确实是，左边太窄了

**Comment by yakamoz423** [comment]
赞同，屏幕利用率太低

**Comment by star7th** [comment]
已经重现设计UI，并且经过跟设计师讨论下决定保留这个设定。

**Comment by star7th** [comment]
保留左侧空着而不全屏的设定。至于右侧标题栏，会额外优化。
