### ISSUE TITLE
mac如何部署

### ISSUE THREAD

**Issue by N0o01** [star7th/showdoc#1930]
mac如何部署
docker也不行

**Comment by star7th** [comment]
最起码也说一下上下文信息吧。你直接一句不行，谁能帮你啊。你讲废话，那我也回你废话。

**Comment by N0o01** [comment]
docker run -d -v /root/showdoc/Sqlite/:/var/www/html/Sqlite --name showdoc -p 4999:80 showdoc
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
308a9c5c7a1ecc46ff1fe9ccb1d9ea13a

**Comment by star7th** [comment]
这个教程  https://www.showdoc.com.cn/help/65610  里说了 

“如果你打算安装ARM版本的docker镜像，请将 latest 标签改为 arm-latest”

**Comment by N0o01** [comment]
The path /showdoc_data/html is not shared from the host and is not known to Docker.

**Comment by N0o01** [comment]
没办法添加/showdoc_data路径，找不到根目录

**Comment by star7th** [comment]
你执行了 mkdir -p /showdoc_data/html 命名吗 ，教程里写的

**Comment by star7th** [comment]
先留意  mkdir -p /showdoc_data/html  ，看是否报错。如果有报错，多半是权限问题。mac下的权限我不知道怎么处理，这种是系统本身的问题，你自己去探索下。

**Comment by N0o01** [comment]
如何在拉取时候更改版本号，docker pull star7th/showdoc:arm-latest

**Comment by star7th** [comment]
arm版本用得不多，所以不打其他标签了。只有一个最新版标签
