### ISSUE TITLE
配置MinIO后 附件预览问题

### ISSUE THREAD

**Issue by chenrj-u** [star7th/showdoc#1933]
图片上传到MinIO后预览不了，数据库存储的查看地址如图：
![image](https://github.com/star7th/showdoc/assets/72954982/1fa90602-7346-416f-8409-d762238ccb43)
对应处理代码如下：
![image](https://github.com/star7th/showdoc/assets/72954982/6239434c-aa8d-44b7-a3fe-3b186a943076)
请问下这是bug吗

**Comment by star7th** [comment]
s3协议使用http方式访问的太少了。你这种少数情况就应该多填写个自定义域名。 说是选填，是对其他平台来讲的。

**Comment by chenrj-u** [comment]
配置s3存储的域名绑定是选填，这样的话结合代码来看有点不合理，因为必填才能保证附件正常查看，但我这边问题也解决了，感谢
