### ISSUE TITLE
UI优化

### ISSUE THREAD

**Issue by Pony-liuli** [star7th/showdoc#1935]
不知道你们这个新版本是谁设计的，页面丑就算了，操作按钮一点也不人性化，相比于旧版本很明显就知道哪个按钮是哪个操作，新版本真的太难看太难用了，希望重新设计一款符合大众的操作审美的新UI，不要搞得花里胡哨的

**Comment by star7th** [comment]
建议截图说明哪里难看哪里难用。

**Comment by Pony-liuli** [comment]
<img width="522" alt="image" src="https://github.com/star7th/showdoc/assets/51707916/0bb07fee-6624-462a-9c46-bccea2e45ab8">
所有的按钮都用，建议找一个完全没用过你们项目的新人试一下，看他知不知道你这几个按钮是什么意思，还要一个一个点进去才知道是什么功能

**Comment by star7th** [comment]
旧版不也差不多是这样吗，只是换了图标和样式

**Comment by Pony-liuli** [comment]
最好测试的办法就是找一个没用过的人 旧版和新版都试一下 你们就知道要改哪里了

**Comment by star7th** [comment]
谁主张，谁举证。你说难看难用，那你就证明之。如果连证明都不想，那就拉到。说的好像这个项目收了你钱似的。

**Comment by Pony-liuli** [comment]
哟哟哟 牛逼呀  不让提意见就关掉这个项目

**Comment by star7th** [comment]
你这么牛逼，showdoc承受不起。你改用其他项目去吧

**Comment by Pony-liuli** [comment]
开源项目就是要受得起别人的评论 不让评论你开源干什么？？

**Comment by Pony-liuli** [comment]
早点闭源 早点收费

**Comment by star7th** [comment]
开源是鼓励用户一起完善，不是让你像个大爷一样指手画脚

**Comment by star7th** [comment]
你这么牛逼，来贡献代码啊，github随时欢迎你贡献代码

**Comment by Pony-liuli** [comment]
只有垃圾产品只会和别人扯皮，真正好的产品是会收集整改

**Comment by star7th** [comment]
你也不好好看一下你提的都是什么馊主意。 按钮图标 + 文字提示的方式 ，这几年来showdoc都是这种交互。包括改版前都是这种交互。然后开个贴吐槽这个事情，还嗷嗷叫让我们自己找人验证去。

**Comment by star7th** [comment]
有效的反馈意见我当然会接受。问题你是在乱提意见，态度还不友好。

**Comment by Pony-liuli** [comment]
要你回复了？我提问我的 你回复干什么？

**Comment by Pony-liuli** [comment]
觉得不好的 可以不回复 什么公司找了你这样一个人天天和用户扯皮 也是倒了八辈子霉

**Comment by star7th** [comment]
这里是showdoc开源仓库，你来这里不友好地反馈了一个无效问题，还倒怪起人来了

**Comment by star7th** [comment]
我才懒得天天跟你扯皮。你看下历史问题，绝大部分我都是好好回答问题。用户也是好好反馈。是你这种乱提意见还是一脸高高在上的人，我才觉得要怼回去
