### ISSUE TITLE
保存文档后总是跳转到所有项目首页，很不友好

### ISSUE THREAD

**Issue by chenjia0831** [star7th/showdoc#1937]

**Comment by star7th** [comment]
这个是设计如此，为了省掉很多刷新的麻烦。不然很多地方我都需要做监听有没有更新

**Comment by chenjia0831** [comment]
您好 感谢回复！
  第一  我是一个常规项目在2.9的版本中无此问题，升级到3.1.0版本才有
          图1现在我打开jenkins下面的链接就会直接跳转到图2
         在图1我新建，编辑一个文档 后保存也会直接跳转到图2
        带来的问题就是我每次到图2页得从新进入到项目
图1
  
图2


| |
陈嘉
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年5月24日 09:20 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [star7th/showdoc] 保存文档后总是跳转到所有项目首页，很不友好 (Issue #1937) |

单纯保存不会刷新项目页面的。关闭编辑框才会。而且，服务器不满的，对用户的感知比较小。官网的就很快。如果你的服务器慢，那就确实慢

**Comment by star7th** [comment]
我这边看不到你的图，不太明白你的描述

**Comment by chenjia0831** [comment]
转附件图片
| |
陈嘉
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年5月24日 09:39 |
| 收件人 | ***@***.******@***.***> |
| 主题 | 回复： [star7th/showdoc] 保存文档后总是跳转到所有项目首页，很不友好 (Issue #1937) |
您好 感谢回复！
  第一  我是一个常规项目在2.9的版本中无此问题，升级到3.1.0版本才有
          图1现在我打开jenkins下面的链接就会直接跳转到图2
         在图1我新建，编辑一个文档 后保存也会直接跳转到图2
        带来的问题就是我每次到图2页得从新进入到项目
图1
  
图2


| |
陈嘉
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年5月24日 09:20 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [star7th/showdoc] 保存文档后总是跳转到所有项目首页，很不友好 (Issue #1937) |

单纯保存不会刷新项目页面的。关闭编辑框才会。而且，服务器不满的，对用户的感知比较小。官网的就很快。如果你的服务器慢，那就确实慢

**Comment by star7th** [comment]
不行的，邮件里的附件无法上传倒github 。你需要登陆github，而非邮件回复
