### ISSUE TITLE
保存，点击连接一直跳转首页问题

### ISSUE THREAD

**Issue by chenjia0831** [star7th/showdoc#1938]
您好 感谢回复！
  第一  我是一个常规项目在2.9的版本中无此问题，升级到3.1.0版本才有
          图1现在我打开jenkins下面的链接就会直接跳转到图2
         在图1我新建，编辑一个文档 后保存也会直接跳转到图2
        带来的问题就是我每次到图2页得从新进入到项目
图1
![image](https://github.com/star7th/showdoc/assets/29670733/ff8408d7-c633-4227-8938-1800a541e921)
图2
![image](https://github.com/star7th/showdoc/assets/29670733/4a25f41f-efa6-4bbf-ab6f-146a9ea5babc)

**Comment by star7th** [comment]
你说的这个是比较奇怪，我没有遇到此问题。你需要开个账号账号让我去看下你的程序是什么情况。

**Comment by star7th** [comment]
你发地址以及开个测试账号给我测试下新建和保存页面。

**Comment by chenjia0831** [comment]
test_1234/test_1234
http://150.139.207.58:9600/
| |
陈嘉
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年5月24日 09:56 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [star7th/showdoc] 保存，点击连接一直跳转首页问题 (Issue #1938) |

你发地址以及开个测试账号给我测试下新建和保存页面。

**Comment by star7th** [comment]
我试了，没问题 http://150.139.207.58:9600/web/#/44/476

**Comment by chenjia0831** [comment]
收到感谢，我在查看一下
是我历史文档 问题，还是 我浏览器问题 


| |
陈嘉
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年5月24日 10:00 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [star7th/showdoc] 保存，点击连接一直跳转首页问题 (Issue #1938) |

我试了，没问题 http://150.139.207.58:9600/web/#/44/476

**Comment by immmp** [comment]
![image](https://github.com/star7th/showdoc/assets/26154658/a27b4877-3651-4aa1-8bc2-eb772ce71d63)
新建目录文件夹，点击确定保存后也会跳首页

**Comment by immmp** [comment]
![image](https://github.com/star7th/showdoc/assets/26154658/92ce1b7a-9f4b-4f07-8d9c-bf448642b821)
关掉文档后，也跳首页，用起来很不方便

**Comment by immmp** [comment]
> ![image](https://private-user-images.githubusercontent.com/26154658/312689206-92ce1b7a-9f4b-4f07-8d9c-bf448642b821.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzODczNjcsIm5iZiI6MTcxMDM4NzA2NywicGF0aCI6Ii8yNjE1NDY1OC8zMTI2ODkyMDYtOTJjZTFiN2EtOWY0Yi00ZjA3LThkOWMtYmY0NDg2NDJiODIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDAzMzEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlMWRlMjhkOGY3OTBmNGFlMDVjZDBiOWUwZDhjODU4ZTQ0NzcxNjdiODE0MWMwMTI5Nzg3YmQ1ZjBkMDJmYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y5_K7CWiBYAWqGkW1YG-WLmRI6YyaMDNs9onZVRH7vM) 关掉文档后，也跳首页，用起来很不方便

用的最新docker版本安装部署的有这个问题。在官网提供的demo页面测试没有这个问题。
