### ISSUE TITLE
关于关闭首页跳转到指定目录的问题

### ISSUE THREAD

**Issue by cnkikd** [star7th/showdoc#1939]
可能存在网络的差异，会影响点时间
能否在关闭首页的前提下优化一下代码
![0dca8c746480f4c987511eccd263a6c1](https://github.com/star7th/showdoc/assets/128293872/a1517958-1557-4f64-949a-2d19feaf23c1)

**Comment by cnkikd** [comment]
![image](https://github.com/star7th/showdoc/assets/128293872/e249ab11-b8ed-47f2-9ded-dab6cebabed9)

**Comment by cnkikd** [comment]
官网没有关闭首页，所以感觉不到这个情况 
![image](https://github.com/star7th/showdoc/assets/128293872/c5ab0b79-bfed-4a2e-a024-5193c011739d)
我开启了不显示全屏介绍页，直接跳转到登录页面，而且实际后台还是再继续加载全屏页面，等加载完后再跳到登录页

**Comment by cnkikd** [comment]
这是官网加载页面的速度
![image](https://github.com/star7th/showdoc/assets/128293872/ceec3d8b-2ed9-4458-a4bb-39e9b1697b05)

**Comment by cnkikd** [comment]
![image](https://github.com/star7th/showdoc/assets/128293872/f8abf849-865b-45e6-b861-322efd54bb3a)

**Comment by cnkikd** [comment]
可能我们是公司内部使用，不考虑开放公用，所以这一点在打开首页会有一闪，看着比较难受，没有考虑到到大局，所以能否在关闭首页的情况下考虑优化这个代码。

**Comment by star7th** [comment]
倒不是说不愿意，而是我没想到啥好办法。showdoc是前后端分离的产品，一开始肯定需要先读取后台接口配置来确定要跳转到什么地方。
