### ISSUE TITLE
编辑页面很卡

### ISSUE THREAD

**Issue by tianxiang2017** [star7th/showdoc#194]
本地部署后，编辑模式，输入字符反应很慢，是什么原因。是数据库配置问题吗

**Comment by star7th** [comment]
如果页面太长才有可能预览比较慢

**Comment by tianxiang2017** [comment]
编辑比较慢，已经打开了，输入文字后显示文字慢。有没有提示速度的版本

**Comment by star7th** [comment]
那我也不知道了。你试着把内容复制到https://www.showdoc.cc/ 看看
