### ISSUE TITLE
无法访问分享的私密项目

### ISSUE THREAD

**Issue by tangshuanglong** [star7th/showdoc#1940]
分享项目，项目设置为私密，有访问密码，当分享链接打开后，输入访问密码、图形验证码，点击提交，不跳转，通过F12开发者工具，接口：server/index.php?s=/api/item/info，返回：
`{
    "error_code": 10303,
    "error_message": "不是项目创建者"
![2023-05-24_180511](https://github.com/star7th/showdoc/assets/18552913/e78f24df-ad18-4cbf-8d32-44ef100c7cbd)

}`
接口一请求：server/index.php?s=/api/item/pwd
对应文件：/server/Application/Api/Controller/ItemController.class.php中pwd()方法，577行：
`
session("visit_item_" . $item_id, 1);
`
此处成功设置session。

接口二请求：server/index.php?s=/api/item/info
对应文件：/server/Application/Api/Controller/BaseController.class.php，213行，
`
                // 这个session会在item/pwd那里设置
		if (session("visit_item_" . $item_id)) {
			return true;
		}
`
发现这里获取session为NULL
同样的代码在测试服务器上能正常跑，线上服务器就报上面错误，请问大家知道怎么解决吗？

**Comment by star7th** [comment]
用 docker

tangshuanglong ***@***.***>于2023年5月24日 周三下午6:06写道：
