### ISSUE TITLE
新版本的皮肤有点难受啊，有没有切换皮肤功能

### ISSUE THREAD

**Issue by austconthing** [star7th/showdoc#1941]
看着一片白茫茫的，字体大小也很不舒服，有切换皮肤的功能吗

**Comment by star7th** [comment]
暂时没有切换功能。后面考虑增加。当前习惯习惯就好了。以前的更丑不也习惯了。

**Comment by lym1121** [comment]
新皮肤确实很难受，还有字体太小，15.6的屏幕看不清楚 @star7th

**Comment by star7th** [comment]
> 还有就请求参数的body显示行数是否可以调整，接口参数过多，编辑不太方便，恳请改进，多谢！

要照顾到全局。这里设置显示的行数是会影响全局的。目前不是那么多人的接受都有那么多参数。而且，可以鼠标滚轮滚动的

**Comment by star7th** [comment]
> 还有就请求参数的body显示行数是否可以调整，接口参数过多，编辑不太方便，恳请改进，多谢！

参数实在太多的情况下，也许你们更应该考虑的是使用json方式传递数据。此问题在这里结束。新问题请开新issue

**Comment by lym1121** [comment]
参数就是json格式，但是参数描述的行数展示也是5行，如果参数有百多条，滚轮也是不太方便的

**Comment by star7th** [comment]
> 参数就是json格式，但是参数描述的行数展示也是5行，如果参数有百多条，滚轮也是不太方便的

json方式的参数行下次更新弄多点，其他的先不管了
