### ISSUE TITLE
一级目录不能转移一级目录？

### ISSUE THREAD

**Issue by cnkikd** [star7th/showdoc#1942]
由于前期思路不明确导致多项目后无法把一级目录转移到一级目录下面

![image](https://github.com/star7th/showdoc/assets/128293872/f5490464-ab86-4b54-959e-c39b276675a9)

想把“计量款”的目录移到合同资料内，现在似乎无法找到相对应的操作，难道只能通过复制页面来实现吗？

**Comment by star7th** [comment]
你这个图，截大一点，完全看不懂这是哪个页面，要做什么

**Comment by star7th** [comment]
如果单纯看你的截图，  从图标推断，这些都是页面啊。页面是无法变成目录的。要自己额外创建

**Comment by cnkikd** [comment]
我手动复制，目前资料还不是很多
