### ISSUE TITLE
能不能不要强制更新

### ISSUE THREAD

**Issue by wxy-yuki** [star7th/showdoc#1943]
![ab0cbd7e326af50ea00a35c43d8761d](https://github.com/star7th/showdoc/assets/96413725/c53991b1-0fa3-4e81-b487-0eff885b83f9)

新版本各种小小的不明含义的图标，还有莫名奇妙的地方设置了定高，非常难用，为什么要强制更新呢？？？

**Comment by star7th** [comment]
为了减少维护负担，我只维护最新版。所以一切旧版不能存在，如果存在就意味着会有用户来问我问题，要我负责。所以我只处理最新版，同时会自动升级到最新版。
至于新版的问题，可以一一讨论清楚。
1，大大小小不明含义的图标，你把鼠标当上去悬浮就能看到提示。其实旧版也有部分功能也是这种设计，即 图标按钮 + 文字悬浮提示
2，有哪些地方觉得  定高  设置不合理的，可以发出来探讨

**Comment by star7th** [comment]
发布了一个新版，微调了下字体，同时对表格的限高进行了调整   https://www.showdoc.com.cn/runapi
