### ISSUE TITLE
runapi 新版3.0.3 不好用，能否取消强制更新

### ISSUE THREAD

**Issue by 509854708** [star7th/showdoc#1944]
界面字体太小，太费眼，操作逻辑太难受

**Comment by star7th** [comment]
后面更新会提供设置字体大小的选项

**Comment by 509854708** [comment]
有没有深色模式，或者其他背景颜色。 灰底 黑字 看着很吃力

**Comment by 509854708** [comment]
![image](https://github.com/star7th/showdoc/assets/7114091/318e929d-ba6e-4327-b76d-19a93e793530)
能否把输入内容的地方换成 白底黑字呢

**Comment by star7th** [comment]
配色是设计师调的，我觉得整体上还算好看。所以不打算单独调色，如果调色肯定是总体搭配来改。
我晚上发一个把字体放大一点点的版本。改起来会容易一点。

**Comment by star7th** [comment]
发布了一个新版，微调了下字体 https://www.showdoc.com.cn/runapi

**Comment by 509854708** [comment]
感谢

**Comment by wangzhanjianshe** [comment]
这个界面可以，字体跟配色需要优化，这个东西主要是前后端人员用，要清爽明了，不要太费眼睛。实用为主。
