### ISSUE TITLE
3.0.3更新之后接口不能正常下载文件

### ISSUE THREAD

**Issue by xiongtianwen** [star7th/showdoc#1946]
在2.x的版本是好的，自动更新到3.0.3之后调用下载xlsx的接口后，弹窗保存文件的系统弹框，但是文件名是这样的：_å_ å·¥ç»_è®¡å¯¼å_º_20230526_1238_6036.xlsx_ 不仅经过后台编码的中文名识别成乱码，而且文件名末尾还带了一个下划线，导致下载之后不能正常打开，望尽快修复

**Comment by star7th** [comment]
什么情况，我怎么印象中我没有做过这种的重命名呢。我记得我的重命名统一是 file.rename 
能提供一个可重现例子我试试吗
