### ISSUE TITLE
RUNAPI版本升级后，编辑、保存、克隆文档导致目录层级混乱及丢失问题

### ISSUE THREAD

**Issue by PJCFT** [star7th/showdoc#1947]
ShowDoc版本：v3.1.0
runApi版本：3.0.3

runApi版本从2.1.1升级到3.0.3后在进行文档编写时点击克隆后
当前项目的目录层级变混乱并且层级发生变化导致原接口丢失。

当第一发生次情况时，只能将备份数据库覆盖还原。
然后隔天又出现这样的情况。

目前暂未发现出现该问题的源头。

**Comment by star7th** [comment]
这个问题，我这边重现不了。感觉很难办。我自己克隆文档都是很正常的

**Comment by shchzh85** [comment]
![image](https://github.com/star7th/showdoc/assets/2274762/d6c8d321-a501-49e9-b738-67e3229ddbe9)

**Comment by shchzh85** [comment]
![image](https://github.com/star7th/showdoc/assets/2274762/d93e49e4-08e7-4fb4-9393-72b870d11997)
正常应该是这种界面才对的，一保存就成上面那种界面，还叫人怎么使用的

**Comment by star7th** [comment]
> 遇到一样的问题，客户端使用不了，一保存就是编辑器乱码了

你的跟他不是同一个问题。有需要的话应该发新帖。你的这个，大概率是因为返回数据是html代码，导致解析异常。但我觉得其他接口应该是没问题的，应该只是一个很特殊的情况

**Comment by PJCFT** [comment]
> > 遇到一样的问题，客户端使用不了，一保存就是编辑器乱码了
> 
> 你的跟他不是同一个问题。有需要的话应该发新帖。你的这个，大概率是因为返回数据是html代码，导致解析异常。但我觉得其他接口应该是没问题的，应该只是一个很特殊的情况

今天runApi更新到了3.0.5版本，目前发现在左侧目录处，对接口长按进行移动到其它目录后，再次点击刷新，就会出现目录丢失和错乱了。
不知官方对移动这个操作是否有其它处理。

**Comment by star7th** [comment]
https://github.com/star7th/showdoc/issues/1953 这里有人反馈 丢失的接口可以通过搜索出来。所以我猜测是用户拖动逻辑不对导致。
