### ISSUE TITLE
一升级就乱套了

### ISSUE THREAD

**Issue by shchzh85** [star7th/showdoc#1948]
![image](https://github.com/star7th/showdoc/assets/2274762/d8ce39fd-5985-4259-a167-c616927848e3)
正常的不显示了，一保存再打开就出现了不可思议的页面了，啥功能都没有的，还叫人怎么使用的
![image](https://github.com/star7th/showdoc/assets/2274762/122d6a0d-81dc-47cc-a72e-08b8cd015f88)
只有一个保存和生成 文档的，生成 打开后的页面又是正常的文档形式

**Comment by star7th** [comment]
你确认下是不是响应内容包含特殊html代码导致的。比如你试着请求个正常的json接口看看

**Comment by star7th** [comment]
此外，试着用showdoc最新版，同时也到这里下载最新的runapi客户端 https://www.showdoc.com.cn/runapi

**Comment by star7th** [comment]
还有就是说下你的showdoc安装环境，用哪种方式安装的，如果是自己手动搭建的php环境，则用的版本是多少

**Comment by shchzh85** [comment]
PHP版本是7.4， window10环境，只要返回的结果中有html就是乱套了，添加运行都是没有问题，编辑就不行了，所有的界面都显示不了

**Comment by shchzh85** [comment]
![image](https://github.com/star7th/showdoc/assets/2274762/f4944ce0-40d3-4cea-a216-3cdc257f96ce)
但是showdoc里面也是显示正常的，就是runapi显示不行，而且还是最新的版本，直接升级安装的最新版本

**Comment by star7th** [comment]
我这边试了下，也不是所有html代码都会干扰runapi，我这边倒是显示正常。
所以我只能说是特殊html代码干扰了runapi自身的判断。鉴于是要特殊代码才会被触发，所以我可能倾向于不管它。因为很少接口会返回这些特殊html

**Comment by shchzh85** [comment]
我自己写的接口就会经常返回html的，特别是新闻类的都是会返回这样的问题，非文章或是其他简单类型不会有这样的问题

**Comment by star7th** [comment]
你在后端返回的html ，其内容 分别  html转义 跟 html 不转义 ，html转义两遍   这三种情况各试一下，看能不能兼容

**Comment by shchzh85** [comment]
好吧，这个问题，你们不修复一下的吗

**Comment by star7th** [comment]
我自己没法重现，我返回的html都是好的，我很难搞啊

**Comment by shchzh85** [comment]
没有调试了，关键之前添加的接口一打开就是乱的

**Comment by star7th** [comment]
如果你想我帮忙处理的话，你至少要提供一个可重现接口，让我用runapi请求看看

**Comment by shchzh85** [comment]
http://43.248.119.113:82/api/news/index  这个接口直接请求，然后保存一下，再在目录里面重新打开就乱了

**Comment by shchzh85** [comment]
新增的时候，窗口调式，啥都是正常的，然后把这个窗口关闭了，再重新打开进行编辑就不行了

**Comment by shchzh85** [comment]
![image](https://github.com/star7th/showdoc/assets/2274762/d131cfe8-1ace-451a-aa61-031cd65f74ab)
保存后再次打开就行了，这是不是这里面有html没有转义的原因的
![image](https://github.com/star7th/showdoc/assets/2274762/a980f639-d926-4918-94ab-5362b7d4bc7c)

**Comment by shchzh85** [comment]
那这问题，你们会修复的吗

**Comment by star7th** [comment]
我先看看怎么回事吧

**Comment by shchzh85** [comment]
rpv

**Comment by star7th** [comment]
我发布了3.0.6版，修复了此问题 。你到这里下载安装即可。https://www.showdoc.com.cn/runapi

因为这个问题是特殊情况才触发的问题，所以我不推送全体用户更新了，也暂时没打包其他平台，只更新了win安装包。你重新安装即可

**Comment by star7th** [comment]
等下次更新的时候，再顺便集成这次的改动到其他更新的版本
