### ISSUE TITLE
没办法在自己平台上实现接口文档迁移吗？

### ISSUE THREAD

**Issue by Simon-Wayne** [star7th/showdoc#1949]
之前服务器迁移没完成，于是那段时间的接口文档写在了公有地址上，现如今服务器部署了，本想着导出迁移一下，竟发现只支持postman和swagger 所以说 自己平台导出的文件自己没办法导入吗？

**Comment by star7th** [comment]
runapi项目的话，是的。

**Comment by star7th** [comment]
这也是为了避免白票资源吧。你本身自己由服务器，何必还要来白嫖官方服务器资源。毕竟官网本身要花资源来应付数据量的问题。

**Comment by star7th** [comment]
同时官网也得做数据托管的生意。
