### ISSUE TITLE
文档转让不了

### ISSUE THREAD

**Issue by WiFiUncle** [star7th/showdoc#195]
我点击“转让”，然后让我验证用户名密码(我输入我自己账户密码)， 然后就提示“”转让成功“”了
而没有让我选择某个其他成员，难道刚刚输入是别人的账户么？ 
麻烦有空解答下，谢谢！

**Comment by WiFiUncle** [comment]
我刚刚输入别人的账户，自己的密码，然后“转让成功”了，我去看我项目，的确没有了。
别人的账户名，自己的密码。。。。。

**Comment by star7th** [comment]
正常。自己的密码用于验证是你本人。别人的账号用来指定接受者，没毛病。
