### ISSUE TITLE
求目录批量删除！

### ISSUE THREAD

**Issue by yangcc001** [star7th/showdoc#1950]
不是很常用，但是感觉可以有

**Comment by star7th** [comment]
我是觉得必要性不是很大，一般项目，不会很多目录。就算有，也是很少数的情况。而且让用户单个删除也避免误操作带来的后果，让他多确认一下

**Comment by yangcc001** [comment]
嘻嘻

**Comment by yangcc001** [comment]
可以只扫描指定文件



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月29日(周一) 上午10:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [star7th/showdoc] 求目录批量删除！ (Issue #1950)




 
我是觉得必要性不是很大，一般项目，不会很多目录。就算有，也是很少数的情况。而且让用户单个删除也避免误操作带来的后果，让他多确认一下
