### ISSUE TITLE
新版的 runapi 界面字体是啥？感觉很好看，求字体

### ISSUE THREAD

**Issue by curomic** [star7th/showdoc#1951]
![image](https://github.com/star7th/showdoc/assets/75515846/c60579b4-6cb8-4cb2-ad73-c20f8230d949)
![image](https://github.com/star7th/showdoc/assets/75515846/0f9d7aeb-c33f-403b-b47a-56ab4f91dcbe)

**Comment by star7th** [comment]
江城圆体

**Comment by curomic** [comment]
> 江城圆体

![image](https://github.com/star7th/showdoc/assets/75515846/7d7535d4-f160-4401-9393-54e5dbd8528f)


具体哪个规格的呢？

**Comment by star7th** [comment]
正常字体是400字重，加粗字体是700字重。
