### ISSUE TITLE
无法运行调试,一直提示, 您的网络发生异常,无法连接服务器或服务器没有响应

### ISSUE THREAD

**Issue by yangyuanhu** [star7th/showdoc#1952]
runapi版本3.0.5 ,貌似更新之后就这样了,不是地址问题测试了百度首页也一样不能访问 ,showdoc正常能用

**Comment by star7th** [comment]
是不是有安全程序禁止runapi访问网络了

**Comment by star7th** [comment]
runapi没有后台日志，理论上发生错误会直接报出来。
尝试更新showdoc到最新版看看。

**Comment by yangyuanhu** [comment]
更新了，目前问题是无法登陆
原来的文档还在且可以访问,但runapi无法登陆
用户名或密码不正确

**Comment by star7th** [comment]
那就说明你没更新好。先别管runapi，先确保showdoc自身能登陆并且能创建文档，保证showdoc是正常的再用runapi。

**Comment by yangyuanhu** [comment]
感谢你的耐心回复  是按照docker的升级文档 一步步做的，showdoc 同样无法登录

**Comment by star7th** [comment]
挂载目录直接递归777权限再重启容器

**Comment by yangyuanhu** [comment]
问题依旧 o(╥﹏╥)o

**Comment by star7th** [comment]
那我不知道了。其他用户很少有这样的问题。大概率跟你的服务器或者操作方式有关。你的服务器，要怎么运维只有你知道了
如果不想费力运维，建议使用官方在线服务 https://www.showdoc.com.cn/

**Comment by star7th** [comment]
从来没有遇到过showdoc服务端是好的，而runapi用不了的问题。我解释不了，也重现不了。我觉得是你的系统上才有的问题，别人应该不会有问题。你可以尝试从别人的电脑安装runapi然后连接同一个showdoc服务端试试，也连接官网服务器试试，用排除法确认是哪个的问题

**Comment by star7th** [comment]
你卸载runapi，改用官网showdoc服务器试试

**Comment by yangyuanhu** [comment]
i am fucking stupid!
