### ISSUE TITLE
导出文档时候报504

### ISSUE THREAD

**Issue by ayanjoyful** [star7th/showdoc#196]
文档内容比较多.

**Comment by star7th** [comment]
增加php文件执行时长和执行内存。方法去搜索之。

**Comment by ayanjoyful** [comment]
调整内存大小和执行时长了,还是504,是不是录入的文档格式有关报错了呢

**Comment by star7th** [comment]
很难猜。试试把内容复制到https://www.showdoc.cc/ 看是否能用导出功能
