### ISSUE TITLE
3.0.5和3.0.7打开接口文档时，客户端展示的接口名称不对，网页版展示是对的

### ISSUE THREAD

**Issue by wangxianbiao** [star7th/showdoc#1962]
![image](https://github.com/star7th/showdoc/assets/43992814/23d195bc-8efc-4e1c-8cb6-9383163ee82e)

![image](https://github.com/star7th/showdoc/assets/43992814/18088074-cb19-41de-82da-833cafa2f347)

**Comment by star7th** [comment]
你在runapi再填写正确的标题，然后保存就好
