### ISSUE TITLE
runapi会自动升级吗？现在3.0.5导致目录混乱，接口文档丢失了大部分

### ISSUE THREAD

**Issue by wpinbin** [star7th/showdoc#1967]
现在3.0.5导致目录混乱，接口文档丢失了大部分，怎么把丢失的找回来了？混乱这个还能去找下，接口文档丢失这个问题很严重把

**Comment by star7th** [comment]
会自动升级。
尝试看这个问题是否有帮助 https://github.com/star7th/showdoc/issues/1957
