### ISSUE TITLE
可以增加接口作者或负责人的标记吗？

### ISSUE THREAD

**Issue by zzj89082** [star7th/showdoc#1968]
因公司多人维护一个项目，其中每个人所编写负责的接口不一样。
前期可能比较清楚的记得，后期渐渐自己都模糊了；而且前后端之间协作时，前端可能找负责接口的人员比较麻烦，总找错...
所以是否可以在每个接口处，增加"作者 or 负责人" 标识呢？谢谢~

**Comment by star7th** [comment]
感觉这个需求不是非常通用。但似乎也可能会有。
当前我不确定是否应该增加负责人字段，但是我觉得你可以现在接口描述处说明。

**Comment by star7th** [comment]
定好个团队规范，负责的接口在接口描述或者最后的备注中说明

**Comment by zzj89082** [comment]
好吧，谢谢您的答复，期待增加此字段。毕竟从关注点来说，描述就是描述，备注就是备注，不应承载其他职责。
描述中加负责人多少有点歧义，并且个人账号已经登录了（账号中本身就有明确个人信息）。
人为填写，可能存在错误信息...
