### ISSUE TITLE
建议在api里加个版本控制，方便管理不同版本api

### ISSUE THREAD

**Issue by thinkingroom** [star7th/showdoc#197]

**Comment by star7th** [comment]
什么意思

**Comment by thinkingroom** [comment]
![图片](http://ww1.sinaimg.cn/large/a1c0df1agy1fm5ppl1lb4j20sg0ea75z.jpg)
就是类似apidoc里的api版本控制

**Comment by thinkingroom** [comment]
就是类似apidoc的版本控制
[](http://ww1.sinaimg.cn/large/a1c0df1agy1fm5ppl1lb4j20sg0ea75z.jpg)

**Comment by star7th** [comment]
不打算支持此功能，交互过于复杂了。
如果需要另开一个版本，完全可以复制出一个相同项目然后在此基础上修改

**Comment by forhuan** [comment]
如果能保留几个历史版本就好了，这样万一哪次操作错了也不要紧。

**Comment by star7th** [comment]
编辑页面的时候，能看到页面的历史版本按钮
