### ISSUE TITLE
runApi 升级使用新版本, 无法多开了

### ISSUE THREAD

**Issue by yangxinbo** [star7th/showdoc#1971]
当前使用的版本3.0.5,  升级前一直可以多开

**Comment by star7th** [comment]
为什么想多开，是什么使用场景

Yangxinbo ***@***.***>于2023年6月22日 周四下午7:32写道：

**Comment by yangxinbo** [comment]
我有好几个小项目, 需要相互调用.

**Comment by star7th** [comment]
下次考虑要不要多开吧。

**Comment by star7th** [comment]
由于比较多人有 多开 实例的需求，故我先打个包以支持该功能（原计划是一股脑做很多功能再一起上线）。现在去这个页面https://www.showdoc.com.cn/runapi/30291 下载v3.0.8版本即可

**Comment by yangxinbo** [comment]
给力呀
