### ISSUE TITLE
内网上编辑上传的图片，用公网IP地址登录项目查看不到图片是怎么回事？

### ISSUE THREAD

**Issue by victorsango** [star7th/showdoc#1974]
如题？我看图片都是一个路径地址，上传的时候是内网地址，公网地址web访问就打不开这个内网地址的图片了。那意思是我要用公网地址去上传这个图片吗？还有就是说如果公网地址是变动的话，那变动后我用公网地址上传的图片也显示不了了吗？

**Comment by star7th** [comment]
管理后台可以设置 网站外部访问地址。附件和图片都会使用这个设置
