### ISSUE TITLE
正文 13px 字号有点费眼睛

### ISSUE THREAD

**Issue by dingeral** [star7th/showdoc#1977]
能否添加一个字号开关；
目前通过修改 css 文件达到修改字号效果

**Comment by star7th** [comment]
新版改为14px，同时曾经了一些行距和段落距离，感觉会比之前显得好一点

**Comment by star7th** [comment]
新版改为14px，同时增加了一些行距和段落距离，感觉会比之前显得好一点

**Comment by dingeral** [comment]
是的，官方文档里确实是 14px，我搭建的里面是 13px

**Comment by star7th** [comment]
昨晚改的。你更新下

**Comment by dingeral** [comment]
1. 我在网页的 关于本站 更新
2. 我执行了命令`./showdoc update`
3. F5 刷新
结果是 13px

另外
1. `GitHub` https://github.com/star7th/showdoc/blob/master/web/static/css/app.2347154dd742da33795a57fb2942f2dd.css
2. `https://www.showdoc.com.cn/`  https://dfyun-spare1.showdoc.com.cn:8888/static/css/app.b6b2804c8b66caa396488095b559ca0b.css?_ex=1688140799&_si=e28369fac7
3.  我的 /showdoc_data/html/web/static/css/app.2347154dd742da33795a57fb2942f2dd.css

**Comment by star7th** [comment]
那确实是我没同步到开源版。我晚上再发个版本吧

**Comment by star7th** [comment]
发布新版了

**Comment by dingeral** [comment]
Perfect
