### ISSUE TITLE
插入图片是否能增加一个用哪种语法插入的选项

### ISSUE THREAD

**Issue by Lxj96** [star7th/showdoc#1978]
插入图片现在默认是使用markdown语法插入的
```![](xxxx)```
这种方式调整宽高不太方便。
能否增加一个选项，插入的时候可以插入img标签形式的。

**Comment by star7th** [comment]
其实你自己手写标签就行。加按钮也是插标签而已。大部分不太需求img标签，而你刚好有需求，所以手写比较合适

**Comment by star7th** [comment]
编辑器是支持img的html标签的
