### ISSUE TITLE
runapi可调试的接口页面交互建议

### ISSUE THREAD

**Issue by hsk-story** [star7th/showdoc#1979]
响应显示区域太小了, 整个页面只有四分之一不到的区域能看到响应内容, 但是接口调试过程中响应内容一定是最常看的位置.
1. 可以将各个组件的边距调小, 组件之间的留白不用这么宽
2. 底部按钮区域占用了大量空白空间, 调试按钮的位置放到URL栏不是挺好的, 不明白为什么要放到底部固定

字体颜色偏浅了, 加上本来字体就比较小, 看起来很吃力

**Comment by star7th** [comment]
牺牲了什么便利性？

**Comment by hsk-story** [comment]
> 牺牲了什么便利性？

就是我这个issues的诉求呀, 响应展示的区域太小了. 稍微长一点的响应内容还要往下拉.
runapi既然作为一个接口请求工具, 是否应该尽可能精简调试过程中的操作呢

**Comment by star7th** [comment]
有些人要我放大 请求区域 卡片， 说他们的场景请求参数太多 。有些人想 响应区域放大。
目前我只是尝试找一个平衡而已。目前并没有收到太多不好的反馈。

**Comment by hsk-story** [comment]
我前面提的两点方案和其他人的诉求不冲突呀
1. 缩小各个组件之间的留白: 现在页面有大量留白, 作为一个生产力工具, 大量留白除了可以提高审美上的观感, 并不能提升效率吧?
2. 底部按钮占用了大量空间: 按照作者你的考虑, 是为了引导用户操作, 但是这种操作点过一次就知道是什么作用了, 为什么要做强制展示呢, 而且应该也有相当大部分用户是从类似postman这类老牌接口调试工具中迁移过来的, 需要刻意学习的成本应该不高

**Comment by star7th** [comment]
先收集下其他人的反馈吧。反正，新版上线后，只有你反馈这个问题，我并不确定是否值得为此改版。

**Comment by star7th** [comment]
说实话，底部按钮也没占多高的高度。习惯问题而已，习惯就好。
postman把发送按钮放在url后面是历史问题，因为历史它就是这么做的。
但是，从一个全新的使用者角度来看，他可能无法理解，一个 藏在 地址栏判断的按钮，为什么会对 环境变量 这些起作用。它不应该只是对地址起作用吗。

调试按钮放在 页面层 是最合适的。它表示对整个页面生效，而不只是对个地址生效。
