### ISSUE TITLE
新版v3.2.2 部署私有版没有AI辅导功能吗?

### ISSUE THREAD

**Issue by MatteDog** [star7th/showdoc#1980]
新版v3.2.2 部署私有版没有AI辅导功能吗? 如果有是需要怎样的去配置? 官方的文档有点找不全这方面的内容.

**Comment by star7th** [comment]
进入管理后台，网站设置那里

**Comment by chudaozhe** [comment]
是的。
![WX20230708-151711@2x](https://github.com/star7th/showdoc/assets/1473364/406dddb9-2dcf-43aa-8935-fab1879a11d9)

**Comment by chudaozhe** [comment]
我录了一个视频详细介绍ai助手的使用 https://www.bilibili.com/video/BV1tM4y1j7x4
