### ISSUE TITLE
彩色 emoji

### ISSUE THREAD

**Issue by dingeral** [star7th/showdoc#1981]
emoji 的支持（例如：👍）显示黑白
希望支持一下

**Comment by star7th** [comment]
我不知道你是什么情况。反正我试着是可以的。

**Comment by star7th** [comment]
首先，升级到新版。还有问题的话，截图

**Comment by dingeral** [comment]
![image](https://github.com/star7th/showdoc/assets/36292978/75434aa4-9068-4bce-94b7-1e94ca13531c)

**Comment by star7th** [comment]
去官网试一下 行不行 https://www.showdoc.com.cn/ ，把在官网上的例子链接发我看看

**Comment by dingeral** [comment]
![image](https://github.com/star7th/showdoc/assets/36292978/4ba8abd9-e688-4f56-b2f4-f652064b8467)

https://www.showdoc.com.cn/2313441264955503/10337988053236749

**Comment by star7th** [comment]
我看到的是彩色。
这是是浏览器本身渲染问题。跟你使用的浏览器和电脑系统有关。

**Comment by dingeral** [comment]
是的，我在云浏览器中看到的是彩色的
![image](https://github.com/star7th/showdoc/assets/36292978/534d4281-0bd5-48e6-be58-4443ff6bd4a9)

**Comment by star7th** [comment]
应该是不同系统不同浏览器渲染的问题

![image](https://github.com/star7th/showdoc/assets/2200494/662762f5-1362-4fb3-a12b-9c0bf784da39)

**Comment by dingeral** [comment]
如何解决呢
是缺少字体，还是某种设置或是系统问题

**Comment by star7th** [comment]
没法解决。不建议使用。emoji还不是浏览器标准，目前在各个浏览器以及平台上看到都不一样，你无法保证目标用户浏览的时候是正常的。所以不建议使用emoji

**Comment by dingeral** [comment]
已查明原因：
我使用了 `字体渲染` 脚本，开启了字体重写，关闭后即可 
🤣
