### ISSUE TITLE
 v3.2.2 导入文档异常出现bug

### ISSUE THREAD

**Issue by ikaijian** [star7th/showdoc#1985]
![image](https://github.com/star7th/showdoc/assets/40664684/dc53c13e-6d88-4b26-889b-7f6bd48e7b84)

**Comment by star7th** [comment]
导入的文件是什么，只支持 提示文字 里面说到的三种格式。

**Comment by ikaijian** [comment]
> 

markdown格式和swagger都不可以导入

**Comment by star7th** [comment]
把文件脱敏后发出来看下

**Comment by ikaijian** [comment]
> 把文件脱敏后发出来看下

![image](https://github.com/star7th/showdoc/assets/40664684/d73e91fb-946c-44a8-adb5-eb5358962586)

**Comment by star7th** [comment]
你给我截图是什么意思？
showdoc导入说明不是说了吗，只支持json或者zip格式。你给我的哪里是json或者zip格式

**Comment by star7th** [comment]
尝试发我json或者zip格式的文件，你说导入不了的问题

**Comment by ikaijian** [comment]
> 
导入内容乱码&文档样式不兼容
![image](https://github.com/star7th/showdoc/assets/40664684/b9eb7c0e-dd4c-402c-b291-995e813caea2)
![image](https://github.com/star7th/showdoc/assets/40664684/fdefe696-e832-4dd6-aa1f-5eaba3c3db98)

**Comment by star7th** [comment]
部分中文名导入会乱码。这个问题好像之前有了，没明白怎么回事，先不管了

至于说导入有一大片空白的问题，我还是那番话，把文件脱敏后发出来。你单纯截效果图没有太多意义，因为我不知道你原来的为文本是怎样的。

**Comment by ikaijian** [comment]
> 部分中文名导入会乱码。这个问题好像之前有了，没明白怎么回事，先不管了
> 
> 至于说导入有一大片空白的问题，我还是那番话，把文件脱敏后发出来。你单纯截效果图没有太多意义，因为我不知道你原来的为文本是怎样的。
[授权登录.zip](https://github.com/star7th/showdoc/files/11998631/default.zip)

**Comment by star7th** [comment]
你这不是纯markdown，参杂了大量的html代码。
showdoc如果支持html，则html标签里不能包含换行，因为换行符经过markdown解析后，换翻译成p标签或者br标签。
你这个文本本身就不是标准的md文件，所以才出现问题。

**Comment by star7th** [comment]
这个不是showdoc的问题，你应该追溯上游，为什么上游导出的markdown表格是一大推html表格。跟showdoc无关。
