### ISSUE TITLE
v3.2.2 代码和``的蓝色不好看，求换回之前的红色，logo也是

### ISSUE THREAD

**Issue by ioc-liuc** [star7th/showdoc#1986]
![image](https://github.com/star7th/showdoc/assets/67723219/c2c10b92-c9da-4aa3-8cba-696802be505c)
![image](https://github.com/star7th/showdoc/assets/67723219/5e133867-781d-4a64-ab9d-24683f9ad056)

**Comment by star7th** [comment]
如果你强制要用红色，可以自己写html标签实现吧

**Comment by sn01615** [comment]
链接刷新后内容空白怎么回事？

**Comment by star7th** [comment]
什么叫 链接刷新后 ？ 如果你是使用了描点，那么，不支持描点

**Comment by sn01615** [comment]
我使用php8.2 手动搭建，内容是通过api导入的，切换到3.2.2代码后
![image](https://github.com/star7th/showdoc/assets/7794149/f5fb3c59-4925-414c-947d-129da305e2bb)
刷新页面少调用了个接口 /api/page/info，切换到3.1.1可以正常显示，有少量二开
![image](https://github.com/star7th/showdoc/assets/7794149/466278e5-6e94-44b4-a9b3-e60e6995f723)
![image](https://github.com/star7th/showdoc/assets/7794149/3ba34ce8-7c5b-42fd-978b-6ee7fabf13ee)
![image](https://github.com/star7th/showdoc/assets/7794149/838705cc-67c2-4cba-a836-1c7c0ebe074e)

nginx:
```
server {
    listen       4999;
    listen  [::]:4999;
    server_name  localhost;

    root   /var/www/php/doc/;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    index index.php;

    charset utf-8;

    #access_log  /var/log/nginx/host.access.log  main;

    client_header_timeout 7d;
    client_body_timeout 7d;
    send_timeout 7d;

    location / {
        try_files $uri $uri/ /index.php$uri$is_args$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(.*)$;
        fastcgi_param  PATH_INFO $fastcgi_path_info; # TP要这玩意
        # fastcgi_pass unix:/var/run/php/php8.0-fpm.sock;
        # fastcgi_pass unix:/var/tmp/php-fpm/php-fpm.sock;
        fastcgi_pass php-fpm:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_connect_timeout 7d;
        fastcgi_read_timeout 7d;
        fastcgi_send_timeout 7d;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
```

**Comment by star7th** [comment]
感觉是你二开的问题。你试着全新装一个空showdoc有没有这个问题。应该是没有的

**Comment by star7th** [comment]
少挑起一个请求应该是前端没发起请求。我不清楚为什么会有这种情况。你试着用全新showdoc来试一下，确定有问题再反馈bug
