### ISSUE TITLE
runAPI    参数和响应 点击快速生成 结构不正确

### ISSUE THREAD

**Issue by xjy1592922966** [star7th/showdoc#1987]
场景：runAPI  参数和响应 点击快速生成 结构不正确

符合预期：
https://www.showdoc.com.cn/server/api/attachment/visitFile?sign=ce6e08f2af4a5d4774644aa8ceae1f5c&file=file.png

不符合预期：
https://www.showdoc.com.cn/server/api/attachment/visitFile?sign=12cfb440cc5689c41181cf50e2f06acf&file=file.png

```
{
  "id": 1,
  "username": "",
  "count": "",
  "arr": [
    1,
    2,
    3
  ],
  "object": {
    "a": 1,
    "b": 2
  }
}
```

**Comment by star7th** [comment]
是不太好支持数组类型的。这个以前就发现。
因为问题不多见，所以不管了。你把生成的多余的给删除就好

**Comment by xjy1592922966** [comment]
好的，那我们自己生成对应的json
