### ISSUE TITLE
分享链接时,能否直接分享跳转到指定标题的链接

### ISSUE THREAD

**Issue by liuende501** [star7th/showdoc#1988]
如题, 拷贝链接分享给他人时,能否通过参数直接跳转到指定标题? 谢谢!

**Comment by star7th** [comment]
不支持。vue的路由本身是hash，所以不支持再hash到标题

**Comment by liuende501** [comment]
好的 谢谢!

**Comment by star7th** [comment]
开源版不支持修改为path的方式，因为会强依赖nginx规则。对非docker用户来说，增加部署的麻烦。
