### ISSUE TITLE
ruanapi 是否可以支撑项目中的单页面和目录分享

### ISSUE THREAD

**Issue by xtjeiu88** [star7th/showdoc#1995]
是否可以支持一个项目只分享单个页面。

**Comment by star7th** [comment]
目前有计划做单页分享，晚点更新。
但是目录分享暂时不确定会不会做，有点偏向不做

**Comment by xtjeiu88** [comment]
单页分享就解决了很多场景了，期待更新。

**Comment by star7th** [comment]
已更新客户端，重新下载安装包即可 https://www.showdoc.com.cn/runapi
