### ISSUE TITLE
开放API http://xx.com/server/index.php?s=/api/item/updateByApi 无法更新，一直创建新的

### ISSUE THREAD

**Issue by ComingLong** [star7th/showdoc#1999]
当新建的文档在根目录时，即cat_name不传或者为空，page_title相同依然创建新的，而不是根据page_title进行更新操作

**Comment by star7th** [comment]
你确认标题是一样的吗，有时候含有特殊字符是会导致不一样的。
cat_name 试着传 /

**Comment by ComingLong** [comment]
确认标题一样的，用postman测试的，只改了内容部分，cat_name 传 / 会导致出现一个没有名称的目录

**Comment by star7th** [comment]
好像是忘记了对根目录进行判断。后面再更新下吧。
你当前就新建个目录装起来吧

**Comment by ComingLong** [comment]
OK，谢谢

**Comment by star7th** [comment]
新版已经修复
