### ISSUE TITLE
您好，编辑文档的时候，上传不了图片？

### ISSUE THREAD

**Issue by angerpeanut** [star7th/showdoc#2]

**Comment by star7th** [comment]
showdoc引用的是一个第三方编辑器，而编辑器的上传图片功能我没有去弄。我迟点有空再看看能不能优化

**Comment by star7th** [comment]
上传图片的问题搞定了

**Comment by CinderellaCiCi** [comment]
我今天更新了代码，发现图片上传坏掉了，没有生成链接，点击确定窗口就关闭了，不知道什么原因，能帮看下不？
![](http://ww2.sinaimg.cn/large/5ebd877egw1f215hyvu18g20ul0jbe1e.gif)

**Comment by star7th** [comment]
邮件审核元素，看看js报什么错

**Comment by star7th** [comment]
新增了支持三级目录的功能；升级安装请参考部署手册中“升级安装”部分。http://blog.star7th.com/2016/05/2007.html
此外我新建了一个ShowDoc使用交流qq群（群号：564671853），欢迎探讨问题
