### ISSUE TITLE
已有的markdown项目， 怎么导入

### ISSUE THREAD

**Issue by wulibin163** [star7th/showdoc#200]
目前文档都是用markdown写的， 归档在gitlab上， 想导入到showdoc， 有没有推荐的方法

目录结构如下：

```
example\
mapreduce\
tools\
_sidebar.md
aggregation.md
field.md
fmtmdd.PNG
mapreduce.md
php.md
query.md
README.md
readydata.md
sexample.md
sort.md
```

**Comment by star7th** [comment]
几个文档而已，直接手动复制也不麻烦吧。

**Comment by wulibin163** [comment]
这只是其中的一小部分， md还好说， 还有依赖的附件呢？一个一个导进去也不是这么容易

**Comment by zyqwadr** [comment]
看代码是吧内容压缩保存在sqlite,不能直接导入,希望能够直接读写md文件

**Comment by star7th** [comment]
@zyqwadr showdoc不会走读md源文件的路线的。很多小工具就是因为读取md源文件、不适用数据库导致它几乎只能成为个人用的文档，无法应对规模写作。

**Comment by star7th** [comment]
@wulibin163 针对你说的情形，只能使用开发api自己编程实现了https://www.showdoc.cc/page/102098
