### ISSUE TITLE
Runapi的前执行脚本可以卡住进程吗？

### ISSUE THREAD

**Issue by CodingFishWu** [star7th/showdoc#2002]
我需要在前执行脚本里面发送一个网络请求，拿到数据以后设置参数，再执行实际的接口？

前执行脚本是否支持 await或promise的方式？

**Comment by star7th** [comment]
执行脚本有个 帮助按钮 。里面 有个 封装好的ahax方法可以调用。它是同步发起网络请求的

**Comment by CodingFishWu** [comment]
那个原来是同步的呀，我还以为是异步的。

那我知道怎么做了，谢谢
