### ISSUE TITLE
showdoc首页视图展示建议

### ISSUE THREAD

**Issue by wll-github-root** [star7th/showdoc#2005]
1、老版本展示项目是类似九宫格，新版本直接一列，但是每个人可能喜欢的视图不一样，建议保留老版本视图，然后能根据自己的喜欢欢相应的视图

**Comment by star7th** [comment]
设计师建议如此，我觉得这种交互听他的建议似乎更好。
不支持切换九宫格是不想增加维护的麻烦。

**Comment by weily2** [comment]
强烈建议新增一个切换视图的按钮。项目多了的话排一列确实不美观也不好找，就因为视图的原因我老版本用了好久，因为新版本的同级目录和页面可以混排所以才升级的。
