### ISSUE TITLE
文档托管打不开了

### ISSUE THREAD

**Issue by xjy1592922966** [star7th/showdoc#2007]
https://[www.showdoc.com.cn](https://www.showdoc.com.cn/)/

这个地方国内国外都打不开了， 我是广州电信千兆宽带，

可能需要帮忙看看我的文档还在上面

**Comment by ChieveiT** [comment]
+1

**Comment by fuyunqin** [comment]
+1

**Comment by xjy1592922966** [comment]
我还以为就我一个

**Comment by star7th** [comment]
由于受到大量请求攻击，目前带宽持续被打满，导致无法访问。但数据都是好的，并未受任何破坏或者非法访问。对于带宽持续被占满的问题，我们正在想办法。

**Comment by xjy1592922966** [comment]
我建议静态文件放阿里云的oss+CDN， 这样高并发和静态请求都能上一个量级。

**Comment by xjy1592922966** [comment]
开源真的好难

**Comment by xjy1592922966** [comment]
国内有个国家应急响应中心， 可以处理这种问题，而且事件会被记录下来，直接开始查源头。

**Comment by hardy50574** [comment]
有没有应急方案呢？ 起码受到攻击时，文档可以在线看，不然没法协调工作了

**Comment by hardy50574** [comment]
估计是哪个同行眼红了。。蛋疼。居然来搞网络攻击

**Comment by star7th** [comment]
现在应该逐步恢复了
