### ISSUE TITLE
网络又无法访问了

### ISSUE THREAD

**Issue by hardy50574** [star7th/showdoc#2008]
runapi无法请求网络了。。昨晚还好好的。今天一天打不开。。在线的文档也打不开

**Comment by star7th** [comment]
由于受到大量请求攻击，目前带宽持续被打满，导致无法访问。但数据都是好的，并未受任何破坏或者非法访问。对于带宽持续被占满的问题，我们正在想办法。

**Comment by hardy50574** [comment]
有没有其他方案可以访问文档的？ 或者临时导出下

**Comment by star7th** [comment]
现在应该逐步恢复了
