### ISSUE TITLE
代码块复制后多出一空行

### ISSUE THREAD

**Issue by jxzzlfh** [star7th/showdoc#2009]
showdoc的代码块一键复制后，在剪贴板内容会多出一个空行，这个怎么解决？

**Comment by star7th** [comment]
什么意思？ 如果只是多一个空行，直接删除不就好了吗

**Comment by jxzzlfh** [comment]
多行代码一键复制，在命令行粘贴后出现错误，比如多行docker命令

**Comment by star7th** [comment]
截个图看看什么影响吧，我不知道你在说什么现象

**Comment by jxzzlfh** [comment]
如果是单行代码，一键复制后，剪贴板多出来的空行相当于直接回车执行

**Comment by star7th** [comment]
额，这个是为多行代码准备的功能，确实没考虑你说的情况。
我感觉，如果你真的只是放单行代码，不如用单行代码语法吧。不要用代码块语法
