### ISSUE TITLE
升级到runapi-win-3.0.7版本后，项目接口目录出现严重错乱，还丢失了部分接口目录

### ISSUE THREAD

**Issue by whynotchat** [star7th/showdoc#2010]
在准备新增一个接口目录时，输入完目录名称点击回车时，可能正好到了runapi自己的刷新时间，导致页面出现了十几秒的卡顿，卡顿结束后发现我新增目录的同级和上级目录全部消失了，不知道跑去哪了，但是奇怪的是以前的老接口还能搜到，最后展开所有接口目录后在一个别的子目录里面看到了部分老接口目录，这是第一次，后续在恢复接口时，删除了一个不需要的接口目录，又再一次触发刷新，刷新结束当前操作的目录又全部丢失，又找了半天才在别的子目录中找到，最终尽量恢复了大部分接口，但是还是丢失了部分接口目录，希望目录错乱和丢失的问题能够引起重视！！！太吓人了！！！最后只能卸载了最新版runapi，重新安装的老版本runapi，希望老版本不会这么爆雷

**Comment by star7th** [comment]
https://github.com/star7th/showdoc/issues/1957

新用户不会再有这个问题的。就是部分老用户升级版本的时候才有这种低概率的兼容问题

**Comment by star7th** [comment]
看这个 https://github.com/star7th/showdoc/issues/1957
