### ISSUE TITLE
v3.2.2 两个问题（python代码块格式不能正确的展示，进入具体文章页后刷新就没有了，还需重新找一遍）

### ISSUE THREAD

**Issue by wsfnk** [star7th/showdoc#2011]
1、
![image](https://github.com/star7th/showdoc/assets/26306360/af8abe7f-29c5-44bd-8b7e-4c7036412889)

![image](https://github.com/star7th/showdoc/assets/26306360/91b429c5-78ed-4430-bbb1-e0b8ab048593)

2、
![image](https://github.com/star7th/showdoc/assets/26306360/1fd3a97a-64d0-4318-9882-bc95faed4d25)

![image](https://github.com/star7th/showdoc/assets/26306360/67b302dc-4820-41df-a187-0066105bb3cf)

**Comment by star7th** [comment]
你是新用户还是用哪个版本升级上来的

**Comment by star7th** [comment]
你说的第1点是正常的，设计如此。
第2点，请提供可重现链接

**Comment by star7th** [comment]
不认真看我都忘记了，python跟缩进格式强相关的。

你说的这两个问题，我都无法重现。

到官网弄个可重现例子出来 https://www.showdoc.com.cn/

**Comment by wsfnk** [comment]
https://www.showdoc.com.cn/2332422779318065/10401534898381647
哇塞：确实，用你们官方这个，我也没遇到这个问题，这是你们官方实例，这就奇怪了，修了？还是我的哪儿有点问题，O(∩_∩)O哈哈~？懵逼ing

**Comment by star7th** [comment]
开源版是有 # 符号 的。你可以尝试安装一个新的showdoc，然后重现下。想办法提供一个可以给我访问的重现例子，不然这个问题我无法解决。而且我感觉应该也没什么人遇到这个问题，因为没其他人反馈

**Comment by wsfnk** [comment]
好，我先重新搞一个折腾折腾，多谢多谢

**Comment by wsfnk** [comment]
您好，我这边更新了 docker images 解决了第二个问题，crtl+f5 无法定位文章的问题，
前面说的第一个问题，我测试吧nginx的反代去掉，直接访问4999 端口，代码就是正常的
![image](https://github.com/star7th/showdoc/assets/26306360/e0325844-1cc4-41d2-8c1b-d9542fdc8fe5)
![image](https://github.com/star7th/showdoc/assets/26306360/c0f5a3f1-3957-4343-8ba2-1491d3074252)

**Comment by wsfnk** [comment]
对不起，请忽略我所提的两个问题，该issueissues 可关闭

我说的代码 展示不一致，根本原因是，我的cdn 开启了html代码 性能优化
![image](https://github.com/star7th/showdoc/assets/26306360/e0928ff5-b307-4c81-b05d-9af8e8dfa4ce)
