### ISSUE TITLE
关于3.2.2版本表格自动保存样式丢失的问题反馈

### ISSUE THREAD

**Issue by conghua1013** [star7th/showdoc#2015]
## 问题描述: 

1. 打开表格页面
2. 表格内输入文字
3. 选择表格工具栏"填充颜色"任意选择颜色
4. 点击表格返回按钮
5. 再次选择该表格进入页面,检测上次编辑内容,仅保留步骤2的内容, 步骤3的操作结果丢失未保存

**Comment by star7th** [comment]
要用鼠标修改文字后才会触发自动保存。
自动保存的机制，后面看看怎么改吧。

**Comment by conghua1013** [comment]
建议优先发布修复版本增加手动保存按钮,解决当前样式丢失问题

**Comment by star7th** [comment]
你先随便修改点什么。鼠标谈起单元格的瞬间触发保存事件的

**Comment by star7th** [comment]
你先随便修改点什么。鼠标弹起单元格的瞬间触发保存事件的

**Comment by star7th** [comment]
新版已经加上保存按钮
