### ISSUE TITLE
导出openapi规范的yaml文件

### ISSUE THREAD

**Issue by shenmy89** [star7th/showdoc#2018]
showdoc支持swagger3导入功能，可以提供导出swagger3文件吗

**Comment by star7th** [comment]
不能，不可逆。

**Comment by shenmy89** [comment]
有什么办法，可以转换成openapi规范的数据吗，我看表里存的是json格式的数据，但是又夹杂了很多html数据，导致转换很困难

**Comment by star7th** [comment]
是转换困难，所以我说了不可逆。没什么好办法。

**Comment by ethan-jo** [comment]
showdoc 里有些数据（markdown、html之类）无法完整导出
基于其他参考写了个支持部分导出的工具，可以用来迁移数据 https://github.com/ethan-jo/ruapi-generate-md
