### ISSUE TITLE
使用runapi创建的接口有几率丢失问题

### ISSUE THREAD

**Issue by hsk-story** [star7th/showdoc#2019]
runapi 3.0.5版本，最近已经出现很多次创建接口后丢失了，复现场景不确定。如果这个工具定位成生产力工具，应该把数据稳定性放在第一位吧。

**Comment by star7th** [comment]
https://github.com/star7th/showdoc/issues/1957

**Comment by austconthing** [comment]
貌似是克隆之后再保存就会有问题,接口到处乱飞到别的接口下面去

**Comment by star7th** [comment]
不是，你们要看我发的那个问题。这个跟接口克隆没关系。
你把项目克隆一份应该就好了
