### ISSUE TITLE
上传大图片失败

### ISSUE THREAD

**Issue by thm1994** [star7th/showdoc#202]
上传大图片失败，在Application/Home/Controller/PageController.class.php里面修改上传大小的上限，还是不起做用。

**Comment by thm1994** [comment]
![image](https://user-images.githubusercontent.com/17030652/34035992-c9078d7c-e1be-11e7-8f0e-b0dc144b8cad.png)

**Comment by star7th** [comment]
搜索如何修改php上传文件大小

**Comment by thm1994** [comment]
谢谢，我是在docker里面部署的，发现没有php.ini文件，在/use/local/etc/php/里面创建了php.ini文件并修改，重启docker后生效
