### ISSUE TITLE
升级最新版之后目录上多了个web？

### ISSUE THREAD

**Issue by happily655** [star7th/showdoc#2023]
原来域名是这样的
【域名】/web/#/28/370
升级到最新版之后变成了
【域名】/web/web/#/28/370

这个是咋回事呢

**Comment by star7th** [comment]
大概率是你自己没写好规则。 绑定域名参考这个教程写规则 https://www.showdoc.com.cn/help/7240953917068087

**Comment by happily655** [comment]
多谢，运维给加代理导致的。。。
