### ISSUE TITLE
是否可以增加动态功能

### ISSUE THREAD

**Issue by jkpeng** [star7th/showdoc#2026]
背景：查看项目组成员文档更新状态
动态功能描述：
1.支持查看权限范围内所有项目更新动态
2.动态包含的内容：更新人、项目名、文档标题、文档链接、更新时间、状态(新增、编辑、删除等)
3.动态内容中的连接支持点击跳转

可以参考Gitlab/Github动态功能样例

**Comment by star7th** [comment]
在右下角的下拉菜单，可以看到项目变更日志。

**Comment by star7th** [comment]
在右上角的下拉菜单，可以看到项目变更日志。

**Comment by jkpeng** [comment]
感谢，看到了
不知道这个“项目变更日志”是否方便增加到项目列表那个页面去
能够有个“动态” 按钮，按变更日期倒叙展示所有项目的变更日志信息

**Comment by star7th** [comment]
不打算。不是高频功能。需要的话，自己点击看一下就好

**Comment by ctxqlxs** [comment]
runAPI 创建的项目没有动态吗

**Comment by star7th** [comment]
runAPI 创建的，暂时没有。以后再加。
