### ISSUE TITLE
编辑接口文档，修改目录，无法进行对目录进行模糊搜索

### ISSUE THREAD

**Issue by hellhker** [star7th/showdoc#2027]
![image](https://github.com/star7th/showdoc/assets/14212220/728119da-2572-42f1-a883-a7d8cea265ab)
最开始的版本，是没有搜索的；半年前的版本，是可以搜索的；更新到最新的，现在又变成不能搜索了。希望作者加上，项目目录太多，滚动查找太麻烦了，谢谢~

**Comment by star7th** [comment]
可能是忘记更新了。后面改一下

**Comment by hellhker** [comment]
现在更新了吗

**Comment by star7th** [comment]
已更新

**Comment by star7th** [comment]
刚push到最新master版本
