### ISSUE TITLE
集成登录的建议

### ISSUE THREAD

**Issue by GameByHand** [star7th/showdoc#2028]
1. 集成登录后不能关联到已有的账号，不方便。
2. 只获得了登录后的账号，没有获得昵称/真实姓名

**Comment by star7th** [comment]
哪种集成登录

**Comment by star7th** [comment]
如果是说LDAP的话，不同系统获取姓名的字段不知道是否存在差异，如果这样，就不好操作和测试了。如果说让用户配置，太多配置项也容易把人搞混。

**Comment by star7th** [comment]
oauth2的昵称真实姓名字段是什么

**Comment by GameByHand** [comment]
字段名没有在协议中约定的吧，最好是配置的。
一定要写死的话  账号用email， 姓名用name吧

**Comment by star7th** [comment]
我发了个新版，如果获取到的用户信息包含name字段，则会写入showdoc的姓名处。
