### ISSUE TITLE
获取数据不一致

### ISSUE THREAD

**Issue by 18362210221** [star7th/showdoc#2037]
同一个人的账号，打开公开项目，登录与未登录状态看到的内容不一样（未登录状态看到是全的，登录状态内容缺失）

**Comment by star7th** [comment]
你是不是给这个账号  只授权 了某个目录

**Comment by star7th** [comment]
再有问题的话，请提供可重现链接。因为我这边从没听说过也无法重现

**Comment by 18362210221** [comment]
已解决，谢谢
