### ISSUE TITLE
docker安装方式升级后部分目录和页面丢失

### ISSUE THREAD

**Issue by tmsxj** [star7th/showdoc#2042]
安装方式：我按照https://www.showdoc.com.cn/help/65610提供的升级方式从2.x升级到最新版，然后部分目录和页面丢失。
问题描述：
我从服务器拉取showdoc.db.php文件用SQLiteSpy查看，可以看到对应的页面和图片路径，服务器/showdoc_data/html/Public路径下也有对应的文件。但是客户端看不到一部分目录和页面了。
1.我从服务器拉取showdoc.db.php可以看到页面和附件。但是不知道怎么修复。
（1）新上传的图片路径http://112.74.79.204:4999/Public/Uploads/2023-08-27/64eaa3a7bf386.png
旧图片路径（在客户端看不到）http://112.74.79.204:4999/server/../Public/Uploads/2021-11-15/6192341d97b8a.png
旧图片路径（在客户端可以看到，只有很少一部分）http://112.74.79.204:4999/server/index.php?s=/api/attachment/visitFile/sign/5e8ac28b22072df73176a13748382163
请问下这个该怎么修复呀，请教下sql怎么写。
![微信截图_20230830003719](https://github.com/star7th/showdoc/assets/88723230/25623f56-89f8-4dfd-bc7b-fdb283163779)
![微信截图_20230830003910](https://github.com/star7th/showdoc/assets/88723230/19b88477-790f-4754-957c-975ec373fd59)
![微信截图_20230830004318](https://github.com/star7th/showdoc/assets/88723230/c83cb65d-10c1-4dea-8798-740d7867a0f6)

**Comment by star7th** [comment]
目录表是 catalog ，进入，找到不见得目录 ，把它的父id变为 0 ，就可以在根目录看到了

**Comment by star7th** [comment]
另外也参考下这个问题 https://github.com/star7th/showdoc/issues/1957

**Comment by tmsxj** [comment]
> 另外也参考下这个问题#1957

多谢。我通过showdoc.db.ph进行了数据恢复，还好新版本有多个文件生成，现在已经没问题了。
