### ISSUE TITLE
不能通过Url直接访问到文档

### ISSUE THREAD

**Issue by MakesYT** [star7th/showdoc#2043]
例如我有一个
https://wiki.XXX.com:777/web/#/671961065/152984211
这样网址我打开后没有任何页面被打开,右边是空白的还需要手动选中目录,url中的路径不会被自动选中
自己搭建的服务器,直接使用了nginx+php,可以正常使用附件/图片等功能
![image](https://github.com/star7th/showdoc/assets/42534870/e7bb37ab-3040-439c-a59f-62189d1284a7)

**Comment by star7th** [comment]
请提供可重现链接

**Comment by MakesYT** [comment]
https://wiki.ncserver.top:777/web/#/671961065/152984203

**Comment by star7th** [comment]
说实话我也不懂这是什么原因。你是怎么安装的，尝试升级到最新版

**Comment by star7th** [comment]
我自己安装了最新版试了试，是没问题的。实在没明白你的是怎么回事。并且也没怎么听到其他人的反馈，所以我觉得这是一个特例问题，可能跟你的安装方式有关。

**Comment by MakesYT** [comment]
我直接克隆的github仓库，是这个问题吗

**Comment by star7th** [comment]
应该跟直接克隆没关系。你试着用官方docker跑，看有没有这个问题

**Comment by MakesYT** [comment]
php版本太高了？我用了8.1😂

**Comment by MakesYT** [comment]
就是版本太高了，缓换成7.4好了

**Comment by star7th** [comment]
后面有空的时候修复下兼容问题

**Comment by yeriwei** [comment]
这小问题啥时候能修复不？ 不用Docker，现在新版的Linux很多默认安装的PHP都是8.1版本的。。

**Comment by star7th** [comment]
已经推送到master分支，修复了此问题。

**Comment by star7th** [comment]
实测已经兼容到了php8.3，此问题结束。有兼容问题可再另外帖子。
