### ISSUE TITLE
关于七牛云存储配置问题

### ISSUE THREAD

**Issue by bmphjhu906** [star7th/showdoc#2045]
`bucket`的值，`scdn-nodjoy`这样填入一级是正常的，文件可以上传到根目录，但是我想将文件上传到`scdn-nodjoy/showdoc`目录中，则不行，是不支持吗？
![image](https://github.com/star7th/showdoc/assets/120728683/b2da4e7d-e20d-41dc-aedd-0754b6741eb6)

![image](https://github.com/star7th/showdoc/assets/120728683/d34b5c1c-a278-42f8-ab2e-d2fb67e801b4)

**Comment by star7th** [comment]
现在不支持上传到子目录。以后看看有没有必要支持。

**Comment by bmphjhu906** [comment]
ok
