### ISSUE TITLE
建议增加单独控制某个文件的编辑权限

### ISSUE THREAD

**Issue by tianxiang2017** [star7th/showdoc#205]
现在用户要么没有编辑权限，如果有编辑权限，就对所有文件都可以编辑。能不能增加一个功能，对某个文件进行单独权限控制，比如让一个文件只能让一个用户可以编辑，其他用户只能查看

**Comment by star7th** [comment]
做那么深的权限控制没有意义。配置的时候会特别繁琐。
比如说一个项目里很多文档。配置的时候就要从一大堆文档中选择。这种配置没有普遍意义
