### ISSUE TITLE
Editor.md年久不更新了，是否可以更换成cherry-markdown

### ISSUE THREAD

**Issue by wangzy1976** [star7th/showdoc#2058]
我们团队用showdoc做文档分享，还是非常不错的，但是Editor.md年久不更新，有时候解析md还是有一些问题，另外不支持memraid等，对比了一下，发现腾讯刚出的cherry-markdown还不错，支持更多特性，更新较为频繁，不知道有更换的编辑器的计划吗？

https://github.com/Tencent/cherry-markdown/tree/main

**Comment by star7th** [comment]
它不够成熟，即使换也应该不会考虑它。编辑器其实我是做过二次开发的，新编辑器未必会兼容历史。要兼容估计我得魔改。
而且，换编辑器带来的额外收益并不高，并不好明显提升体验。所以没必要冒着兼容风险。

wangzy1976 ***@***.***>于2023年9月12日 周二下午11:40写道：

**Comment by wangzy1976** [comment]
好的，谢谢！
