### ISSUE TITLE
导入接口问题

### ISSUE THREAD

**Issue by caofqgit** [star7th/showdoc#2063]
最新版runapi在导入接口选择swagger3文件，当请求为post json传递参数请求时，showdoc生成的文档无请求体信息

**Comment by star7th** [comment]
脱敏后发一下json文件出来看看，要能重现的

**Comment by caofqgit** [comment]
{
  "openapi": "3.0.1",
  "info": {
    "title": "myself",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [
    {
      "name": "showdoc测试文件"
    }
  ],
  "paths": {
    "/test": {
      "post": {
        "summary": "测试",
        "x-apifox-folder": "showdoc测试文件",
        "x-apifox-status": "developing",
        "deprecated": false,
        "description": "",
        "tags": [
          "showdoc测试文件"
        ],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string",
                    "title": "id"
                  },
                  "type": {
                    "type": "string",
                    "title": "type"
                  }
                },
                "required": [
                  "id",
                  "type"
                ],
                "x-apifox-orders": [
                  "id",
                  "type"
                ],
                "x-apifox-ignore-properties": []
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string",
                      "title": "编码"
                    },
                    "data": {
                      "type": "string",
                      "title": "数据"
                    }
                  },
                  "required": [
                    "code",
                    "data"
                  ],
                  "x-apifox-orders": [
                    "code",
                    "data"
                  ],
                  "x-apifox-ignore-properties": []
                }
              }
            }
          }
        },
        "x-run-in-apifox": "https://apifox.com/web/project/2816442/apis/api-112190536-run"
      }
    }
  },
  "components": {
    "schemas": {}
  },
  "servers": []
}

**Comment by star7th** [comment]
好像这个格式又变了。找个有空的时间再钻研吧

**Comment by XuMengEnEli** [comment]
我也遇到同样问题，请问这个问题fix了么

**Comment by star7th** [comment]
已推送到最新master分支，解决了问题
