### ISSUE TITLE
Docker部署出现问题

### ISSUE THREAD

**Issue by kevin-ma** [star7th/showdoc#207]
Warning: include(lang.zh-CN.php): failed to open stream: No such file or directory in /var/www/html/install/common.php on line 9

Warning: include(): Failed opening 'lang.zh-CN.php' for inclusion (include_path='.:/usr/local/lib/php') in /var/www/html/install/common.php on line 9

**Comment by star7th** [comment]
如果你是按照这个的话应该是没问题的，多次测试过。https://www.showdoc.cc/help?page_id=65610
其他方式的话自己多找原因吧

**Comment by kevin-ma** [comment]
完全按照你的教程执行的

**Comment by star7th** [comment]
那就可能是你的docker 安装不对或者做了什么自定义修改了。这个教程放了很久了，一直没人反馈过你这样的问题

**Comment by star7th** [comment]
你尝试把lang.zh-CN.php 这个文件复制过去/install 目录下试试

**Comment by kevin-ma** [comment]
你工程中的语言文件分别为lang.en.php、lang.zh.php，而报错的提示是lang.zh-CN.php文件找不到，所有在我在docker中尝试修改了文件名，现在可以运行了。另外为什么URL的参数lang=zh，而我在common.php文件中echo $lang 输出的是 zh-CN？

**Comment by star7th** [comment]
"另外为什么URL的参数lang=zh，而我在common.php文件中echo $lang 输出的是 zh-CN？"
确实诡异，应该是url中的小写才对。是不是什么东西补上了-CN后缀

**Comment by kevin-ma** [comment]
$lang = $_REQUEST['lang'] ? $_REQUEST['lang'] :"zh";  如果url中没有值应该会默认赋值zh，我在下面一行马上echo，发现依旧是zh-CN，有点儿想不通（我是部署到腾讯云），我现在打算按照你说的复制一下语言文件来处理这个文件
