### ISSUE TITLE
针对单页分享的时候，网页标题是否应该为文章标题。

### ISSUE THREAD

**Issue by yancheng2** [star7th/showdoc#2074]
我的应用场景是微信小程序植入使用文档，我使用showdoc编写后，单页分享后，在微信小程序打开后标题是Showdoc，而不是文章本身的标题。

**Comment by yancheng2** [comment]
还有一个是浏览量的统计

**Comment by star7th** [comment]
以后有空改下标题。
不打算增加浏览统计。有需要的话自行植入网站统计代码。

**Comment by star7th** [comment]
已更新到最新master分支
