### ISSUE TITLE
路由地址的#号怎么去掉？

### ISSUE THREAD

**Issue by aligarduo** [star7th/showdoc#2083]
原本地址是这样的
【域名】/web/#/666

我想把#号去掉，变成这种的
【域名】/web/666

要修改哪里呢？

**Comment by star7th** [comment]
开源版showdoc不支持去掉

**Comment by star7th** [comment]
只有官方能去掉

**Comment by star7th** [comment]
官网 https://www.showdoc.com.cn/

**Comment by aligarduo** [comment]
哦哦，原来是这样。谢谢啦。
