### ISSUE TITLE
项目内搜索关键字

### ISSUE THREAD

**Issue by ChenWeihua123** [star7th/showdoc#2088]
能否支持搜索目录名称呢，有时候目录很多，找起来不方便，现在只能搜索页面内的内容

**Comment by star7th** [comment]
如果要对搜索结果进行目录层级展示，则太麻烦了。所以现在搜索出来的结果，都是没有目录概念的。
鉴于搜索目录是很小众的需求，所以就不为这个小众需要增加麻烦了
