### ISSUE TITLE
能否升级editor.md为veditor

### ISSUE THREAD

**Issue by LinkedDestiny** [star7th/showdoc#2098]
https://github.com/Vanessa219/vditor

editor.md 很多年没维护了， 各种bug都没人修复

**Comment by star7th** [comment]
请从使用的角度去列举下为啥要升级，带来的好处有多少。因为升级成本很大，有很多向后历史兼容问题。
除非能明显提升使用体验，不然不太想花时间去做。

**Comment by LinkedDestiny** [comment]
或者升级一下他内置的katex版本也行，现在默认的0.3.0太坑了

**Comment by LinkedDestiny** [comment]
我尝试hack了一下代码没生效，不知道是设置的不对还是怎么样，不懂前端

**Comment by star7th** [comment]
列出可重现场景 https://www.showdoc.com.cn/ 说明哪些语法不支持，看看是否真的只是版本问题还是其他问题引起

**Comment by star7th** [comment]
你在官网新建一个页面放上代码看看

**Comment by LinkedDestiny** [comment]
https://www.showdoc.com.cn/2416714032445402/10735415453747411

访问密码 1234

编辑模式下可以看到未被渲染的内容，同样的内容在katex官网可以被渲染

**Comment by LinkedDestiny** [comment]
https://katex.org/#demo

这个是官网

**Comment by LinkedDestiny** [comment]
核心的问题两个：

1. 不支持中文
2. 不支持换行（任意数量的 \ 都不行……）

**Comment by LinkedDestiny** [comment]
确定了，我手动修改了本地的版本，升级到了最新的0.12.0版本，就可以了
<img width="2485" alt="image" src="https://github.com/star7th/showdoc/assets/5689061/ac7e853c-9eaa-4da6-905d-3a9841cdec48">

**Comment by LinkedDestiny** [comment]
确定了，我手动升级到了0.12.0版本，就可以了

**Comment by star7th** [comment]
你是怎么升级的，可能我可以把它集成到官方仓库里来

**Comment by LinkedDestiny** [comment]
直接替换了代码里面的路径

  editormd.katexURL = {
    css: 'https://cdn.bootcdn.net/ajax/libs/KaTeX/0.12.0/katex.min',
    js: 'https://cdn.bootcdn.net/ajax/libs/KaTeX/0.12.0/katex.min'
  }
  
  原来是个 0.3.0 的，现在换成这个路径就行。

**Comment by star7th** [comment]
katexURL 已经更新到官方库
