### ISSUE TITLE
建议，哈哈

### ISSUE THREAD

**Issue by cnlinjie** [star7th/showdoc#21]
喜欢用mackdown编写文档，提两个个人建议，希望不要介意。
1.  `复合数据`，比如`List` 包含 `Object `，`Object `又可能包含其他对象，此时用表格的形式表现不怎么容易。
2.  `Try` 的功能，在线测试。

谢谢~

**Comment by star7th** [comment]
1、对于复合数据，可以写入代码块。请参考“返回结果示例”。而解释字段意思的时候才用表格；
2、有在线网络可供测试和正式使用，http://doc.star7th.com/

**Comment by star7th** [comment]
如果你说的测试是只测试api的吧，抱歉，showdoc的定位是写文档和展示文档，不深入具体文档测试

**Comment by cnlinjie** [comment]
@star7th 
1. 符合数据如果有表格时，好像也只能使用二级关系，包含关系无法描述，只能对应看着示例了。

是的，是测试API，哈哈。
没关系，这UI已经很好看了~，开源的，可以让有需求的人fork之后自己加入需求~
