### ISSUE TITLE
docker db文件外挂之后找不到驱动

### ISSUE THREAD

**Issue by Jonathan-Wei** [star7th/showdoc#210]
通过docker run -v /Users/jonathanwei/work/showdoc/Sqlite:/var/www/html/Sqlite -p 4999:80 showdoc命令执行数据文件外挂本地路径，启动之后无法登陆。

无法加载数据库驱动: Think\Db\Driver\
错误位置
FILE: /var/www/html/ThinkPHP/Library/Think/Db.class.php 　LINE: 42

TRACE
#0 /var/www/html/ThinkPHP/Library/Think/Db.class.php(42): E('\xE6\x97\xA0\xE6\xB3\x95\xE5\x8A\xA0\xE8\xBD\xBD\xE6\x95\xB0...')
#1 /var/www/html/ThinkPHP/Library/Think/Model.class.php(1443): Think\Db::getInstance('')
#2 /var/www/html/ThinkPHP/Library/Think/Model.class.php(97): Think\Model->db(0, '', true)
#3 /var/www/html/ThinkPHP/Common/functions.php(588): Think\Model->__construct('UserToken')
#4 /var/www/html/Application/Home/Controller/BaseController.class.php(21): D('UserToken')
#5 /var/www/html/Application/Home/Controller/ItemController.class.php(42): Home\Controller\BaseController->checkLogin()
#6 [internal function]: Home\Controller\ItemController->add()
#7 /var/www/html/ThinkPHP/Library/Think/App.class.php(173): ReflectionMethod->invoke(Object(Home\Controller\ItemController))
#8 /var/www/html/ThinkPHP/Library/Think/App.class.php(110): Think\App::invokeAction(Object(Home\Controller\ItemController), 'add')
#9 /var/www/html/ThinkPHP/Library/Think/App.class.php(204): Think\App::exec()
#10 /var/www/html/ThinkPHP/Library/Think/Think.class.php(120): Think\App::run()
#11 /var/www/html/ThinkPHP/ThinkPHP.php(97): Think\Think::start()
#12 /var/www/html/index.php(24): require('/var/www/html/T...')
#13 {main}

**Comment by Jonathan-Wei** [comment]
注册提示注册失败

**Comment by star7th** [comment]
请自行保证外挂成功并且可写
