### ISSUE TITLE
Class 'SQLite3' not found 。

### ISSUE THREAD

**Issue by JaysonLi** [star7th/showdoc#2103]
按回车搜索的时候会报错.
<img width="374" alt="1701248231768 (1)" src="https://github.com/star7th/showdoc/assets/9313102/93955f46-222d-473c-b454-b51e9d482afa">
,我需要怎么解决。

**Comment by star7th** [comment]
这个教程说了 https://www.showdoc.com.cn/help/4087044677189279

点击左侧菜单“网站”，然后点击右边按钮“管理”-“php扩展”，确保”php-pdo-sqlite”和”php-sqlite3”开启

**Comment by JaysonLi** [comment]
好的好的 明白了
