### ISSUE TITLE
页面链接无法跳转到指定页面

### ISSUE THREAD

**Issue by dzsk-g** [star7th/showdoc#2104]
页面内插入链接,点击链接无法跳转到指定页面。

**Comment by star7th** [comment]
链接如何的

**Comment by dzsk-g** [comment]
https://XXXXXXXXXX/web/#/109?page_id=6528

**Comment by dzsk-g** [comment]
问题未描述清楚
https://XXXXXXXXXXXXXXXXXX/web/#/109?page_id=6528

**Comment by dzsk-g** [comment]
问题未描述清楚,重新描述下

1. 在当前页面内插入一个指向另外一个页面的链接https://xxxxxxxxxxxx/web/#/199?page_id=6528。

2. 页面保存后点击链接，页面无法跳转到6528界面。

**Comment by star7th** [comment]
目前确实不支持
