### ISSUE TITLE
runapi3.0.6 linux版是deb包，使用alien8.95.5转码成rpm报错

### ISSUE THREAD

**Issue by hzwcome** [star7th/showdoc#2108]
使用的是Centos8系统，之前的runapi1.0.6 linux版解压即可使用，现在提供deb包无法转成rpm
确认过alien没问题
```
[root@localhost runapi]# alien -r runapi.deb 
Warning: Skipping conversion of scripts in package runapi: postinst postrm
Warning: Use the --scripts parameter to include the scripts.
Package build failed. Here's the log of the command (cd runapi-3.0.6; rpmbuild --buildroot='/path/臨時/runapi/runapi-3.0.6' -bb --target x86_64 'runapi-3.0.6-2.spec'):
错误：行 5：空的标签：Summary:
构建目标平台：x86_64
为目标x86_64构建
```

**Comment by star7th** [comment]
不支持ARM版本的linux，极少人用ARM版的linux作为主力开发机器用，故先不考虑。

**Comment by star7th** [comment]
不好意思，看错了，以为是要兼容ARM版本的linux

**Comment by star7th** [comment]
目前我是直接用electron-build打包出来的deb包，我也是依赖开源工具去实现打包。至于你说的这个问题，我暂时也不清楚，可能我无法解决，这取决于electron-build打包

**Comment by hzwcome** [comment]
> 不好意思，看错了，以为是要兼容ARM版本的linux

检查了，是x86_64

**Comment by hzwcome** [comment]
> 目前我是直接用electron-build打包出来的deb包，我也是依赖开源工具去实现打包。至于你说的这个问题，我暂时也不清楚，可能我无法解决，这取决于electron-build打包

那能否像之前一样提供zip包呢😘

**Comment by star7th** [comment]
deb不能直接安装吗？ 我在deepin linux桌面系统试过是可行的

**Comment by hzwcome** [comment]
> deb不能直接安装吗？ 我在deepin linux桌面系统试过是可行的

centos8不是deepin的，是fedora的，我刚刚看了下electron的打包，应该是不支持它的，好像也不提供zip，那我先用着1.0.6吧，之后看能不能自己编译下

**Comment by hzwcome** [comment]
中标麒麟系统也是需要rpm的

**Comment by hzwcome** [comment]
感谢提供好用的软件:)
