### ISSUE TITLE
上传图片域名怎么修改？

### ISSUE THREAD

**Issue by txdier** [star7th/showdoc#211]
自己通过DOCKER部署的，上传图片时，默认生成的路径中域名为showdoc，每个图片都要手动修改，有没有地方可以直接修改默认值？
![](http://**showdoc**/Public/Uploads/2018-01-19/5a615c896d5c3.jpg)
![](http://my-domain/Public/Uploads/2018-01-19/5a615c896d5c3.jpg)

**Comment by txdier** [comment]
http://showdoc/Public/Uploads/2018-01-19/5a615c896d5c3.jpg

**Comment by star7th** [comment]
没有。自己可以到数据库批量修改

**Comment by txdier** [comment]
欧了，谢谢！
