### ISSUE TITLE
修改文档的排序

### ISSUE THREAD

**Issue by wukchao** [star7th/showdoc#212]

**Comment by star7th** [comment]
编辑页面的时候有个顺序序号。数字越小越靠前

**Comment by bbbbuffon** [comment]
哪个配置文件里可以把默认的序号改为最小值，确保新页面排在最前呢

**Comment by star7th** [comment]
没有这样的配置。

bbbbuffon <notifications@github.com> 于2020年9月10日周四 上午10:56写道：
