### ISSUE TITLE
导入Swagger格式(我用的apifox导出的toc.openapi.json)的文件，body参数丢失

### ISSUE THREAD

**Issue by yinxingxing** [star7th/showdoc#2123]
是不支持apifox吗？可是query参数是可以的，返回参数也可以
![Snipaste_2023-12-28_17-47-00](https://github.com/star7th/showdoc/assets/30684898/19015d58-a15f-45de-b958-b6b80b0daf7c)
下面是代码json

{
  "openapi": "3.1.0",
  "info": {
    "title": "toc",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [
    {
      "name": "2.7.5"
    }
  ],
  "paths": {
    "/192.168.5.62:8071/api/pay/notify/order": {
      "post": {
        "summary": "充值支付回调",
        "x-apifox-folder": "2.7.5",
        "x-apifox-status": "developing",
        "deprecated": false,
        "description": "",
        "tags": [
          "2.7.5"
        ],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "openid": {
                    "type": "string",
                    "description": "openid"
                  },
                  "attach": {
                    "type": "string",
                    "description": "固定2"
                  },
                  "transactionId": {
                    "type": "string",
                    "description": "对应表orders_pay.serial_no(微信流水号，真正微信充值成功才会返回，这边你可以自己伪造)"
                  },
                  "outTradeNo": {
                    "type": "string",
                    "description": "对应表orders_pay.paid_no(微信充值号)"
                  },
                  "totalFee": {
                    "type": "string",
                    "description": "微信回调充值金额"
                  }
                },
                "x-apifox-orders": [
                  "openid",
                  "attach",
                  "transactionId",
                  "outTradeNo",
                  "totalFee"
                ],
                "required": [
                  "openid",
                  "attach",
                  "transactionId",
                  "outTradeNo",
                  "totalFee"
                ],
                "x-apifox-ignore-properties": []
              },
              "example": {
                "openid": "o44cI43q-xspJQ5M",
                "attach": "2",
                "transactionId": "888888",
                "outTradeNo": "TN001123111318352813556892958818",
                "totalFee": "100000"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {},
                  "x-apifox-ignore-properties": [],
                  "x-apifox-orders": []
                }
              }
            }
          }
        },
        "x-run-in-apifox": "https://apifox.com/web/project/2607547/apis/api-123736155-run",
        "security": []
      }
    }
  },
  "components": {
    "schemas": {},
    "securitySchemes": {}
  },
  "servers": []
}

**Comment by star7th** [comment]
理论上是支持的。得找时间看一下兼容问题。

尹星星 ***@***.***>于2023年12月28日 周四下午5:51写道：

**Comment by yinxingxing** [comment]
谢谢你的回答，期待能确认一下原因

**Comment by star7th** [comment]
已推送到最新master分支，解决了问题

**Comment by yinxingxing** [comment]
谢谢，解决速度很快，祝apifox越来越好

**Comment by star7th** [comment]
apifox是runapi的竞争对手。你祝福错了啊。
对于showdoc用户，如果想调试接口，建议使用 runapi   https://www.showdoc.com.cn/runapi/30291
