### ISSUE TITLE
生成的接口文档没有Header值

### ISSUE THREAD

**Issue by CKT-xiaoling** [star7th/showdoc#2132]
在请求参数中填写了header参数调试成功后生成文档，文档中没有header的参数，这样别人查看文档根本就不知道需要增加header值，而且runapi项目的文档我还无法手动编辑，想自己手动添加都不行

**Comment by star7th** [comment]
你点击保存了吗，保存后才会生成文档

**Comment by CKT-xiaoling** [comment]
你回得太快了，我需要定义的是cookie值，在postman是添加到header的，你多增加了一个cookie的选项，没事了
