### ISSUE TITLE
强制以移动端样式进行展示

### ISSUE THREAD

**Issue by SangSpace** [star7th/showdoc#2135]
在PC端怎么设置可以以移动端样式进行展示，用于嵌入在其它系统当作帮助文档

**Comment by star7th** [comment]
不提供这些的设置。

SangSkyStand ***@***.***>于2024年1月23日 周二下午5:54写道：

**Comment by SangSpace** [comment]
好的。以前老版本宽度小的时候会自适应。新版不会了。所以才提出这个问题

**Comment by SangSpace** [comment]
我有看到大部分判断this.isMobile()的时候都有同时判断$(window).width() < 1000，唯独在src/components/item/show/show_regular_item/Index.vue:244行少了一个。

**Comment by star7th** [comment]
你可以二开满足你自身的需求，但是这个需求，不是共性需求，官方不打算做。除非确实很多人需要。

**Comment by SangSpace** [comment]
明白。
