### ISSUE TITLE
文件夹能否按拼音排序

### ISSUE THREAD

**Issue by awenw** [star7th/showdoc#2136]
建议项目子文件夹能够按拼音排序，现在找文件夹相当不方便，甚至可以建立同名文件夹

**Comment by star7th** [comment]
可以拖动的，你自己拖动成按拼音排序的样子即可

**Comment by awenw** [comment]
我知道可以托运，可是太麻烦了，还怕不小心不知道拖哪儿去了。最好能够按字符串大小自动排序，如果我想指定顺序，可以在前面加上数字序号，不用担心乱排的问题

**Comment by star7th** [comment]
默认是按  建立文件夹的时间来排序，如果用户拖动过，则使用拖动的排序。

**Comment by star7th** [comment]
修改排序规则要考虑到通用性。一旦改了就影响全部人。目前我不确定是否全部用户都有拼音排序的需求。

**Comment by awenw** [comment]
按常理都应该按字符串进行排序，毕竟乱序查找不方便，当然可以考虑做一个系统参数，是否打开目录排序功能
还有在搜索时候能够搜文件夹就更好了，目前只能搜文件，如果忘记文件夹在哪个子文件夹下，查找 非常不方便

**Comment by star7th** [comment]
我不觉得自己拖动文件夹排序有什么麻烦，不值得为了这个而大动干戈。

**Comment by star7th** [comment]
怎么会乱序呢，这是你自己 业务上的不规范吧。正常人，新建一个文件夹，都会改变到合理位置。只有  新建文件 从没改过排序的人，在文件夹多了后，才会变得乱序。

**Comment by awenw** [comment]
文件夹不多就不觉得，如果数量超过屏幕高度时候，完全就是灾难，而且按字符串排序就是sql语句是否排序的问题，不算大动干戈吧，并且添加文件夹时候默认是添加到最后，要移动到前面很麻烦，不小心就拖到其它目录里面去了，而且找都不好找，因为系统没有目录查找功能

**Comment by star7th** [comment]
如果按你这个逻辑，新建文件夹后，默认是出现在中间，用户才觉得奇怪。
现在默认出现在最后，至少他知道怎么找新建的目录

**Comment by star7th** [comment]
一个项目不会超过三百多目录吧，展开来看一下不就好了。如果实在太多目录，是否应该考虑切分成多个项目

**Comment by awenw** [comment]
我不是这个意思，我觉得文件夹按大小排序就方便查找，没有其他意思，而且手工排序的话，因为有人读音不标准，两个人对排序理解可能都不一样，而且如果前面相同字符比较多的时候，手工排序也相当麻烦

**Comment by awenw** [comment]
超过30个目录就不好处理了，手工排序简直是灾难

**Comment by awenw** [comment]
我是希望项目越做越好，不需要花太多心思而提高可用性的功能最好能够增加

**Comment by star7th** [comment]
对于多目录，命名不规范的话，怎样都是麻烦。你可以自己命名加个 数字前缀 ，然后 ，按这个前缀 拖动顺序

**Comment by star7th** [comment]
你以为   是  按时间排序的。其实并不完全是。
当你完全没拖动过，则  是按新建时间排序。
当你拖动过一次，那么，系统自动为所有目录生成一个序号。这个时候，已经是按序号展示了，已经不按新建时间或者名称排序了。

加了你说的这个逻辑，并不起作用。

**Comment by awenw** [comment]
https://zhuanlan.zhihu.com/p/663159154，这个介绍的也是一个开源markdown文档系统，它就是按目录字符串排序，如果要调整顺序，只要重命名目录就行了，搞个手工拖动排序，功能非常鸡肋，还容易出错，并且不方便迁移

**Comment by star7th** [comment]
因为它是基于文件系统的，showdoc是基于数据库的，不是同一样东西。

**Comment by star7th** [comment]
你说的这个系统，用户量最好达到了showdoc的十分之一，再来建议showdoc参考它的设计。

**Comment by ftrako** [comment]
目前创建的文件只有按创建时间升序的，建议支持按时间降序等多种排序方式（让用户自己选），
当文件比较多时，手动拖动真的好麻烦

**Comment by star7th** [comment]
新建的时候自己按规范拖动即可。你说的这些大概率是存量项目。新项目应该还好

**Comment by ftrako** [comment]
真的建议大佬 支持下自动排序， 因为在文件数比较多的情况下，手动拖动真的很麻烦，望大佬考虑下

**Comment by star7th** [comment]
新建的时候自己按规范拖动即可。你说的这些大概率是存量项目。新项目应该还好。存量的项目，只是一次性工作量，拖完就没事了。

**Comment by star7th** [comment]
我关注的是共性且尽量高频的需求。如果只是很特殊用到，甚至只是一次性工作量，我感觉没有必要

**Comment by awenw** [comment]
大侠能不能增加一个用户状态，是否允许登录，然后给项目授权时候不允许登录的就不显示在列表里面，因为删除用户的话，历史文档的作者信息就变成垃圾信息了&nbsp;


awenw
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月24日(星期五) 上午8:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [star7th/showdoc] 文件夹能否按拼音排序 (Issue #2136)














 
我关注的是共性且尽量高频的需求。如果只是很特殊用到，甚至只是一次性工作量，我感觉没有必要

**Comment by star7th** [comment]
不要在旧issue下提无关问题，要就开新的并且说明使用场景。
