### ISSUE TITLE
如何导入makedown文件

### ISSUE THREAD

**Issue by 18202022630VV** [star7th/showdoc#2147]
本地之前用typora写了很多md文件，有没有什么方法能导入到showdoc

**Comment by immmp** [comment]
@18202022630VV  请问是如何操作的

**Comment by star7th** [comment]
把md文件压缩成一个zip包，然后在导入 压缩包到showdoc。
此方式只能导入到网页版showdoc，无法导入到runapi客户端

**Comment by immmp** [comment]
感谢~已顺利操作完，好使
