### ISSUE TITLE
swagger的json文件导入之后，请求响应参数解析不出来

### ISSUE THREAD

**Issue by fan719** [star7th/showdoc#2148]
swagger的json文件导入之后，请求参数解析不出来，我看到很多提这个的问题的issue，也不知道解决了没有，啥情况呀？
![图片](https://github.com/star7th/showdoc/assets/19567134/594884b9-75e3-46eb-a45a-a7cc42d55850)

**Comment by star7th** [comment]
前段时间修复了过一次导致json的问题。
但这个问题比较难搞，所以往后拖下。有时间再看

**Comment by star7th** [comment]
新版已改善导入问题
