### ISSUE TITLE
应该有自动保存的功能。

### ISSUE THREAD

**Issue by 841809077** [star7th/showdoc#215]
1. 如题，应该有自动保存的功能，并且如果断网保存失败，会不会在页面上提示用户保存失败呢。
2. 还有，当页面编辑后，没有点击保存而是点击了取消，等到下一次会有一个提示说上次未保存，是否添加到模板里，这点做得很好，但是当我再次点击了取消，没有保存的话，那些编辑的信息就消失了。
3. 编辑文档的时候，有一个表情的按钮，按了以后页面报错，无法添加表情，提示：Uncaught TypeError: Cannot set property 'emojiDialog' of undefined  和  Uncaught TypeError: _this[name] is not a function  错误

您的产品很好，再次感谢

**Comment by star7th** [comment]
会60秒保持一次用户的草稿在前端页面、服务器不保存草稿数据。
"当我再次点击了取消，没有保存的话，那些编辑的信息就消失了"——那是因为还没到60秒，没有处罚草稿保存。
表情功能去掉是因为跟某些文章内容冲突。这个按钮应该去掉的

**Comment by 841809077** [comment]
好的，非常感谢。祝您的产品越来越好

在 2018-01-31 10:53:11，star7th <notifications@github.com> 写道：


会60秒保持一次用户的草稿在前端页面、服务器不保存草稿数据。
"当我再次点击了取消，没有保存的话，那些编辑的信息就消失了"——那是因为还没到60秒，没有处罚草稿保存。
表情功能去掉是因为跟某些文章内容冲突。这个按钮应该去掉的
