### ISSUE TITLE
runapi在访问nginx反向代理的服务器时配置user-agent不生效

### ISSUE THREAD

**Issue by paopaoqqcbg** [star7th/showdoc#2150]
runapi在访问nginx反向代理的服务器时配置user-agent不生效

**Comment by star7th** [comment]
其实之前就有问题提出。https://github.com/star7th/showdoc/issues/1810

我找时间改改

**Comment by paopaoqqcbg** [comment]
> 其实之前就有问题提出。#1810
> 
> 我找时间改改

本来就写死的吗？我刚另一个服务器用user_agent添加上是能生效，但Referer不生效，另一个nginx反向代理的服务器不生效，我以为是支持的，nginx的是bug了

**Comment by star7th** [comment]
目前是写死的，需要改造

**Comment by star7th** [comment]
已更新客户端，可以修改ua ，重新下载安装包即可 https://www.showdoc.com.cn/runapi

**Comment by paopaoqqcbg** [comment]
我这测试的怎么修改了还是不起作用啊
&nbsp;


小裴
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月18日(星期五) 下午4:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [star7th/showdoc] runapi在访问nginx反向代理的服务器时配置user-agent不生效 (Issue #2150)





 
已更新客户端，可以修改ua ，重新下载安装包即可 https://www.showdoc.com.cn/runapi
 
&mdash;

**Comment by star7th** [comment]
我测试是生效的。请提供你的重现场景，截图什么的

**Comment by paopaoqqcbg** [comment]
您好，我的场景是这样，对外是nginx,nginx反向代理到iis服务器，经过测试修改ua结果如下第一张图。另外如果接口请求返回了重定向还是什么会导致整个runapi界面白屏，见第二张图





下面是第二张图










小裴
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "star7th/showdoc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月8日(星期五) 上午9:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [star7th/showdoc] runapi在访问nginx反向代理的服务器时配置user-agent不生效 (Issue #2150)





 
我测试是生效的。请提供你的重现场景，截图什么的

**Comment by star7th** [comment]
看不到图

**Comment by star7th** [comment]
另外，如果出现白屏，请确认下返回的内容是什么

**Comment by star7th** [comment]
要登录github才能放图。邮件是不行的

**Comment by paopaoqqcbg** [comment]
![image](https://github.com/user-attachments/assets/c62b825a-eb59-448f-9d5a-abc33765fec1)
![Uploading image.png…]()

**Comment by paopaoqqcbg** [comment]
![093710137091841190073b715118998fed131e03ffd76110_recompress](https://github.com/user-attachments/assets/173ebb41-9653-4aed-bb41-4d6bfc67a142)

**Comment by star7th** [comment]
![image](https://github.com/user-attachments/assets/02008c8a-a0b7-4cc7-9c79-c3be50806c01)

实测能传递。如果你确保自己是使用最新版runapi的话，还出问题则表明是你的服务端配置有问题，漏了一些header

**Comment by paopaoqqcbg** [comment]
我刚试了3.0.8的版本支持ua，也没有白屏会出现，出现白屏的是返回了脚本跳转了url&nbsp;


小裴
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月8日(星期五) 上午9:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [star7th/showdoc] runapi在访问nginx反向代理的服务器时配置user-agent不生效 (Issue #2150)














 
image.png (view on web)
 
实测能传递。如果你确保自己是使用最新版runapi的话，还出问题则表明是你的服务端配置有问题，漏了一些header

**Comment by star7th** [comment]
新版使用了iframe来执行用户返回的html代码和脚本。如果你返回了脚本，那么它会执行
