### ISSUE TITLE
通过接口获取内容时如何按项目轮询页面？

### ISSUE THREAD

**Issue by zsinba** [star7th/showdoc#2151]
在使用LLM+RAM进行知识对话时， 对接已有Showdoc时， 使用接口/server/index.php?s=/api/page/info来获得页面的标题、内容； 
但是想按项目来获取时似乎没有现成的接口可用。
例如：https://myshowdoc.com/web/#/5/349这个内容， 项目ID（item_id）为5； 页面id（page_id）为349；
在全量导入时： 通过这个地址“https://myshowdoc.com/”可以轮询所有的可用的“/server/index.php?s=/api/page/info”参数 item_id，从start到end页面可以迅速获得。 

然而，希望建立基于特定项目ID的导入流程：

地址（base_url）：https://myshowdoc.com/， 
项目ID（item_id）：5
开始页码：10
结束页面：30

目前看来需要遍历整个网址库并根据项目ID进行筛选。请问是否存在更便捷的方法来实现此需求？或者有没有现行的API接口可以直接支持按项目ID批量获取数据？

在探索最优解决方案的同时，欢迎尝试我们的 LLM+RAG 实验性接入点：https://aid.daxue.cloud/

<img width="726" alt="image" src="https://github.com/star7th/showdoc/assets/890157/11f30d43-ad24-427d-9ac6-a6f275ca97b8">

如上图，轮询是通过开始id和结束id。
期望添加的是通过项目id过滤。
并且可以忽略开始页码和结束页码参数 ， 以此增加易用性。

**Comment by zsinba** [comment]
另外请问： 
当前自动更新是通过轮询页面的更新内容进行跟踪变化的。
有没有更简化的办法实现监听页面变化？

**Comment by star7th** [comment]
showdoc没有这样的api，不提供这样的功能。如有必要，可自行尝试读取数据库。官方不提供支持。

**Comment by zsinba** [comment]
请问当前继续使用/server/index.php?s=/api/page/info这个接口,会有未考虑的问题吗?
当前空上接口可以满足基本的功能需求.

**Comment by star7th** [comment]
不清楚你的情况。你如果觉得满足需求，就用即可。

**Comment by zsinba** [comment]
多谢
