### ISSUE TITLE
showdoc接口文档修改后如何通知到企微机器人？

### ISSUE THREAD

**Issue by Maruying** [star7th/showdoc#2155]
请问假如后端修改接口文档后，如何自动通知对应的前端、测试人员？是否有对应的插件通知到企业微信群？

**Comment by star7th** [comment]
修改后，可以通知到  站内 。至于说通知到企业微信，则监听是否有新站内消息就好。
目前不知道这个需求的人多不多，多的话我再做

**Comment by Maruying** [comment]
> 修改后，可以通知到 站内 。至于说通知到企业微信，则监听是否有新站内消息就好。 目前不知道这个需求的人多不多，多的话我再做

辛苦大佬。提这个主要原因是经常接口改了后，信息同步不及时。

**Comment by Maruying** [comment]
> 修改后，可以通知到 站内 。至于说通知到企业微信，则监听是否有新站内消息就好。 目前不知道这个需求的人多不多，多的话我再做

开发同事在二开源码上加了推送企微机器人，现在可以了。
