### ISSUE TITLE
手机端图片显示不出来，报错：图片路径有问题

### ISSUE THREAD

**Issue by 841809077** [star7th/showdoc#216]
1. 在电脑上，markdown的图片可以插入和显示，但是在手机端访问mardown，图片就加载不出来了，实际上就是手机访问不到图片路径，我图片是放在的默认位置，/Public/Uploads目录下的。
我的服务器是阿里云的，然后用的lnmp一键安装包，安装的ngnix和php，然后部署的showdoc。
请问，您知道是哪出了问题吗？
2. 当我在手机上访问我的整个项目地址，而不是分享的单页面链接的时候，它会卡在顶端，好长时间才加载出来，请问这又是怎么回事呢？

**Comment by star7th** [comment]
我建议你把地址发出来。单纯文字描述很难知道问题所在

**Comment by 841809077** [comment]
showdoc默认的图片存储路径是/showdoc/Public/Uploads文件夹：
http://192.168.162.129/Public/Uploads/2018-02-01/5a72b2a1547ef.png,比如这个链接，电脑上能打开，但是手机端打不开，难道只有我的手机打不开吗

**Comment by star7th** [comment]
这个是内网地址

**Comment by 841809077** [comment]
那怎么办？能告诉我解决办法吗

**Comment by star7th** [comment]
内网是不能被外网访问的。如果有外网访问的需求，可以考虑使用官网托管 https://www.showdoc.cc/

**Comment by 841809077** [comment]
那算了吧，好复杂

**Comment by star7th** [comment]
使用官网托管会简单些，不需要自己技术部署。 https://www.showdoc.cc/
