### ISSUE TITLE
在文档中增加TOC目录后，展示的目录无法正确定位

### ISSUE THREAD

**Issue by lxl1140989** [star7th/showdoc#2168]
只有第一个和第二个标题可以点击并定位，后面的都无法点击，我的版本是开源版本v3.2.5。请帮忙看看是什么问题，谢谢。

**Comment by star7th** [comment]
提供下文档内容以重现

**Comment by star7th** [comment]
或者文档链接

**Comment by lxl1140989** [comment]
https://lxl3188.top:4443/web/#/619280827/271393167

**Comment by star7th** [comment]
额，那是因为已经顶到底了啊。再点也无法拉下页面。页面不长。不需要再点。
或者你在页面下方增加很多空行或者无意义字符。

**Comment by lxl1140989** [comment]
我想点击右边目录的最后一行，页面只会跳转到文档最后一个页面的第一个标题上。以前的版本是不会有这个问题的，我点目录的任何一个标题，都能准确跳转到对应的位置上。

![Snipaste_2024-03-27_14-48-59](https://github.com/star7th/showdoc/assets/19900613/29385742-c6ee-431d-954c-bdd4b72fee13)

**Comment by lxl1140989** [comment]
我明白你意思了。只是新老版本有差异，老版本鼠标可以识别到目录里的所有标题，新版本只能识别到文档最后一页的标题。
新版本：
![image](https://github.com/star7th/showdoc/assets/19900613/c8e13a7c-d120-43ab-9e69-9b3906b6808e)
老版本：
![image](https://github.com/star7th/showdoc/assets/19900613/5d85fd58-6a71-43e8-bce4-3b5474b0173d)

**Comment by lxl1140989** [comment]
TOC目录这里，确实有点问题，实际点击的位置，跟识别的位置不一致。比如我点击目录第5行，识别并显示的是第四行。以前的版本不会有这个问题。

![image](https://github.com/star7th/showdoc/assets/19900613/d6f2c8db-bd4e-4f2a-83ca-c0bd0ea9995f)

**Comment by star7th** [comment]
这个问题前几天修复了，不应该还有问题吧。你用的是最新master版本代码或者最新docker镜像吗

**Comment by lxl1140989** [comment]
我用的是arm 的docker 镜像，大概是这个月15号安装的。那我试试新版本。
![image](https://github.com/star7th/showdoc/assets/19900613/7b5c78da-813b-48a1-8637-1af537556e3a)

**Comment by lxl1140989** [comment]
更新版本后，问题解决
