### ISSUE TITLE
请问下 base64 返回数据图片显示后面会做支持吗

### ISSUE THREAD

**Issue by 1em0n9527** [star7th/showdoc#2171]
base64 图片在一些场景会经常出现，有时手动调试需要看一下具体内容，这个特性不知道会不会纳入支持

**Comment by star7th** [comment]
你说的是runapi客户端？

**Comment by 1em0n9527** [comment]
是的，runapi 桌面客户端

**Comment by star7th** [comment]
后面可以加一下吧。
不过返回的字符串，图片标识前缀还是需要的，不能是纯base64内容。
比如 这样  data:image/png;base64,iVBORw0KGgoA....

**Comment by 1em0n9527** [comment]
感谢感谢
