### ISSUE TITLE
runApi工具Mock结果报错

### ISSUE THREAD

**Issue by 514892637** [star7th/showdoc#2181]
- 我正在使用的系统版本

  OS 名称:          Microsoft Windows 11 专业版
  OS 版本:          10.0.22000

  

- 我正在使用的相关开发者工具版本

  微信开发者助手	`1.06_2402040win32-x64`

  谷歌浏览器	`123.0.6312.106`

  runApi工具	`3.0.7`

- 哪些操作可以复现该错误

  使用`Fatch Api` get方式请求Mock接口  https://www.showdoc.cc/server/index.php?s=/mock-path/2492822943714835&path=/index/getproduct?imei=862651060041289

  

- 我期望的行为

  正确请求到相关Mock数据

  

- 我看到的错误是什么

  谷歌浏览器下：![image-20240418234216573](https://github.com/star7th/showdoc/assets/48344715/7e4b813a-75c7-4615-8de2-0aece7294b4a)

  

  微信开发者工具下：![image-20240418234433010](https://github.com/star7th/showdoc/assets/48344715/9ed22465-3bc2-4540-ac73-3b335653b621)

**Comment by 514892637** [comment]
部分已解决，因为正式接口为get.post请求均可以，自身程序发送Mock请求时没注意get请求不应该携带"content-type": "application/json;charset=UTF-8"，浏览器查看已正常。微信开发者工具下的错误暂时未知

**Comment by star7th** [comment]
微信开发者工具好像说是不支持http2协议，你看是否有设置让其支持http2
