### ISSUE TITLE
目录树有点问题，缩进太多导致无法看到内容，全部被隐藏了

### ISSUE THREAD

**Issue by sunnysteam** [star7th/showdoc#2185]
![image](https://github.com/star7th/showdoc/assets/19546500/7afefd12-acd4-43ed-87e5-7092061bcc98)

**Comment by sunnysteam** [comment]
两个问题，请作者大大关注：
1、目录无法缩进太多导致无法展示全部，目录框应该加宽，减少缩进；
2、点击目录框空白的地方，会把目录框关闭，无法找到再次打开的方法，只能刷新，应该有个开关控制收起展开；

**Comment by sunnysteam** [comment]
> 你说的是右边的目录树？ 那个不打算支持多层级。不在原设计范围内。 原设计只打算用右边的目录树解决简单的标题层级。 复杂层级请使用左侧目录树解决。设计如此。

好的，如果是这样，那我就重新设计一下文档结构，没关系。

刚刚发现了一个问题，从页面A添加链接到页面B中，跳转到页面B后，点击浏览器的返回按钮，没有回到页面A，但是浏览器页签标题已经变成了A的标题。预期是能够返回到A页面

**Comment by star7th** [comment]
跳转的这个问题，无解。因为开源版showdoc要使用哈希路由。而浏览器对哈希路由的返回就是有这样的问题

**Comment by star7th** [comment]
如果想避免，可以尝试自己加一些get参数，让浏览器认为不是同一个url
