### ISSUE TITLE
附件（文件）的访问时间（last_visit_time）不会更新

### ISSUE THREAD

**Issue by yixuan1912** [star7th/showdoc#2186]
你好，请问下    这是个bug吗，还是功能暂时还没做完呢？
浏览次数正常，但是 last_visit_time 一直没变
![image](https://github.com/star7th/showdoc/assets/44570514/4d1bde2e-6c17-4324-8281-69211e4d285c)

**Comment by star7th** [comment]
没有展示到UI上的功能可能会被忽略。这个应该是忘记更新了，也没展示到UI上。下次再加下

**Comment by star7th** [comment]
建议等一个个上传

**Comment by star7th** [comment]
新版已更新最后访问时间
