### ISSUE TITLE
容器化运行后，每次启动都需要安装

### ISSUE THREAD

**Issue by barnettZQG** [star7th/showdoc#219]
我以容器化运行，持久化了/var/www/html/Sqlite 和 /var/www/html/Public/Uploads目录。
但是每次启动都会要求重新安装。安装逻辑是怎么样的，有写什么标志文件？

**Comment by barnettZQG** [comment]
建议将 /Application/Common/Conf/config.php 此类表示安装状态的文件放入持久化目录或换一种形式表示是否安装，既然提供了Dockerfile。

**Comment by star7th** [comment]
尝试把整个/var/www/html目录持久化
