### ISSUE TITLE
关于下载类接口的bug

### ISSUE THREAD

**Issue by sylar003** [star7th/showdoc#2197]
通过runapi调试下载文件类的接口时
1. 卡顿住无法操作
2. 当请求结束后可以看到响应头，当点击响应体时软件卡死，必须强制重启

**Comment by sylar003** [comment]
希望可以做到，当卡住时 可以主动取消该次请求，否则当接口响应时间过长时 只能等待或者杀掉进程重新进入

**Comment by star7th** [comment]
运行调试的按钮，可以下拉，选择 运行并下载

**Comment by star7th** [comment]
这个才是设计。原响应体不应该下载文件

**Comment by sylar003** [comment]
但是无法处理长时间运行后的取消动作呀，能考虑加个取消请求的功能么

**Comment by star7th** [comment]
这是很特殊的情况，暂时就不为特殊情况增加功能了。实际上，极端的情况下才会卡住。当真的卡的时候，结束进程吧。

**Comment by star7th** [comment]
js套壳程序，js发起请求不太方便取消。考虑到麻烦度，同时是极少需求，所以不打算做。
