### ISSUE TITLE
oauth2授权登录，报错

### ISSUE THREAD

**Issue by yymagicer** [star7th/showdoc#2199]
{"error_code":999,"error_message":"Invalid response received from Authorization Server. Expected JSON. \u3002\u9519\u8bef\u4f4d\u7f6e\uff1a\/var\/www\/html\/server\/vendor\/league\/oauth2-client\/src\/Provider\/AbstractProvider.php 539"}

**Comment by yymagicer** [comment]
使用的是authorization_code，这个方式授权登录的

**Comment by star7th** [comment]
问题请在同一个issue描述，你的问题分散到几个issue，每次要了解上下文都要翻来翻去。我不想回答这个问题了。

**Comment by star7th** [comment]
目前你的host 和路径配置都有问题
