### ISSUE TITLE
建议新增快捷键操作

### ISSUE THREAD

**Issue by cipchk** [star7th/showdoc#22]
比如：保存、编辑、切换上下页面。

另：
+  markdown中【#、##】在编辑时预览的效果和查看时字号、风格不相同。
+  是否考虑增加 markdown 数据导入和导出功能呢？
+  新增页面时默认选择为上一次所选的上级目录呢？

**Comment by star7th** [comment]
1、目前修改了一项：新增页面时默认选择为上一次所选的上级目录。
2、关于那个 markdown 样式跟预览时不一致的解释：
因为编辑器的样式对移动端不够友好，所以展示页面的时候没有用编辑器本身的样式而是用bootsrate；而编辑页面的话，不得不用编辑器自身的样式。
3、快捷键和markdown数据的导入导出，下次有时间更新会考虑下

**Comment by cipchk** [comment]
@star7th 720f9a124ced235a42a46e1bedaa56eeb64d7fd3

**引入了两个第三方库：**
+ https://github.com/tzuryby/jquery.hotkeys
+ https://github.com/ifightcrime/bootstrap-growl

**增加了show页面快捷键（排除移动端）**

+ `ctrl+E` 编辑
+ `ctrl+D` 删除
+ `ctrl+F1` 新建页面
+ `ctrl+F2` 新建目录

**增加了edit页面快捷键（排除移动端）**

+ `ctrl+S` 保存

**edit页面保存时去alert，增加 `saving` 判断是否正在保存中，防止多次提交。**

**如果是新建页面时，进入编辑页面时光标默认在页面标题文本框。**

**Comment by star7th** [comment]
挺好的。我已经把快捷键代码集成到线上showdoc里去了

**Comment by CinderellaCiCi** [comment]
ctrl+S 是浏览器提示保存html呢，手工保存的时候还是alert没有看到saving。
环境：Win10 / chrome 46.0.2490.80 m

**Comment by star7th** [comment]
更新浏览器缓存，ctrl+f5

**Comment by CinderellaCiCi** [comment]
必须已更新啊，其他快捷键都能用，就这个不行。。

**Comment by star7th** [comment]
http://doc.star7th.com/  实测可用

**Comment by star7th** [comment]
新增了支持三级目录的功能；升级安装请参考部署手册中“升级安装”部分。http://blog.star7th.com/2016/05/2007.html
此外我新建了一个ShowDoc使用交流qq群（群号：564671853），欢迎探讨问题
