### ISSUE TITLE
可以将写好的文档导出为pdf？

### ISSUE THREAD

**Issue by xuzhibin** [star7th/showdoc#220]
可以将写好的文档导出为pdf？

**Comment by star7th** [comment]
不支持。导出为pdf麻烦，性价比不高。导出为word后，有需要的，自己转换下。

**Comment by xgdgsc** [comment]
有什么麻烦的吗，不是调下pandoc吗

**Comment by star7th** [comment]
@xgdgsc 你留意showdoc的官方文档就会发现showdoc的安装部署很容易，同时对老旧系统兼容性强。pandoc则会增加部署复杂度同时对老服务器的兼容性不够友好。我暂时没有计划为了一个小功能增加安装复杂度。后面我可能会在官方在线服务里增加导出pdf功能，不过不会加在开源版里。我还是极力保持简单。
