### ISSUE TITLE
获取图片资源的url耗时1s以上

### ISSUE THREAD

**Issue by shao77622** [star7th/showdoc#2204]
https://xxx/server/index.php?s=/api/attachment/visitFile&sign=56b8dab225afdb99c4db78057bfa45a8
这个url请求每次都要1s以上，哪怕图片是已经缓存在浏览器

只有简单文字页面，https://xxx/server/index.php?s=/api/item/info
打开也要1.3s

容器集群监控看也不是服务器性能瓶颈

<img width="1833" alt="image" src="https://github.com/star7th/showdoc/assets/16330359/f7d9bb42-eefa-4e28-bed6-1b47822e6935">

**Comment by shao77622** [comment]
只有简单文字页面，https://xxx/server/index.php?s=/api/item/info
打开也要1.3s

**Comment by star7th** [comment]
我能百分百肯定是你的部署问题而非showdoc镜像问题。因为我自己刚才试着把镜像部署在rancher上（k8s的封装UI） ，接口的响应速度也不到100ms 。
我猜测你的瓶颈可能有： 网关或者nginx没配置好，数据库文件映射后的读写io太差等等

**Comment by nickilchen** [comment]
同样我这边也遇到改情况，看日志
![image](https://github.com/user-attachments/assets/483be20e-17b6-4c46-a1f4-1c1b151c82f1)
进到容器是curl测试单页面
![image](https://github.com/user-attachments/assets/283cc238-753a-4356-af1f-1eaa7226836c)

**Comment by shao77622** [comment]
从NAS换到部署ssd，速度飞起
