### ISSUE TITLE
希望客户端和网页能展示当前页面由谁创建的和创建时间

### ISSUE THREAD

**Issue by ZhangTianyi-1998** [star7th/showdoc#2210]
![image](https://github.com/star7th/showdoc/assets/37682379/0dd578ee-69d8-44b9-b3b9-478c0f2f12a7)
![image](https://github.com/star7th/showdoc/assets/37682379/d74b7722-1174-44e5-b027-d65af35493cf)
这样这个接口如果有问题 就可以方便找到负责的人

**Comment by star7th** [comment]
后面加一下，计划是，在客户端的左侧栏，右击接口-创建信息，然后弹窗。

**Comment by ZhangTianyi-1998** [comment]
好的 期待!
