### ISSUE TITLE
软件闪退

### ISSUE THREAD

**Issue by Zbinglun** [star7th/showdoc#2214]
3.0.5版本
在添加参数的时候，有几率闪退，刚才加了数据，配置了几十个参数的值，其中包含一个数组，准备保存的时候，点击保存无响应。界面的其他按钮也没用，然后就闪退了，参数回到上次保存的时间

**Comment by star7th** [comment]
这个事情好难办，因为我无法重现。可否提供重现例子我看看。

**Comment by Zbinglun** [comment]
> 这个事情好难办，因为我无法重现。可否提供重现例子我看看。

要提供例子比较难，之前都没有出现过，主要就在这月.出现了两次.最近也没有升级PC的系统，软件也没有升级。实在不行我找一下老版本的先用着.（不然加了几十个然后丢失掉，我直接不想写文档了😢）

**Comment by star7th** [comment]
你可以添加多几个参数的时候就保存一次，这样损失最小化。
建议下次的时候留一下重现条件，尽可能重现下，这样才能排查问题

**Comment by Zbinglun** [comment]
> 你可以添加多几个参数的时候就保存一次，这样损失最小化。 建议下次的时候留意一下重现条件，尽可能重现下，这样才能排查问题

今天早上又出现了，没有任何征兆，就是在一个项目下新建一个文件夹，保存以后发现文件夹名称有问题准备修改，此时点击文件夹后方的三个点准备编辑已经没有用了，过了2/3秒直接闪退，我下了最新版本的包，再用用试试吧！
