### ISSUE TITLE
全屏页面内滚动条不好找, 不方便拖动

### ISSUE THREAD

**Issue by HWTsang** [star7th/showdoc#2215]
![image](https://github.com/star7th/showdoc/assets/47599239/8a645bef-5627-4483-810c-54cc18e2ab70)
如图, 全屏状态下最右侧滚动条很难找, 太小不好拖动

**Comment by star7th** [comment]
showdoc的预设场景是 鼠标滚轮滚动，不鼓励拖动

**Comment by HWTsang** [comment]
那数据比较长并且比较宽的情况怎么做处理呢

**Comment by star7th** [comment]
可以建立一些标题，使用markdown的TOC语法

**Comment by HWTsang** [comment]
[TOC] 只能应用在标题上, 我的数据表格比较大, 不能用这个解决
![image](https://github.com/star7th/showdoc/assets/47599239/6bd97f50-e96c-4b4f-a4b9-e1c2d662eb63)

其次发现一个问题, toc在有相同标题时右侧渲染会全部选择
![image](https://github.com/star7th/showdoc/assets/47599239/b7d234d5-4e76-454b-a06b-cae88b7d32ed)

**Comment by star7th** [comment]
我看了下你的截图，我更建议多使用左侧目录树。一个接口最好只有一个页面。别过度依赖太长的单页
