### ISSUE TITLE
请安装php-mcrypt

### ISSUE THREAD

**Issue by helllkz** [star7th/showdoc#222]
PHP7.1已经不再支持该扩展，建议是使用openSSL，是否可以考虑升级呢

**Comment by star7th** [comment]
mark一下，后续更新考虑支持

**Comment by helllkz** [comment]
但是我把安装里面的模块检测去掉了，好像也没提示报错呢

**Comment by star7th** [comment]
我在在代码里也把它去掉了。大部分情况下没用到它。出错了再看错误提示吧
