### ISSUE TITLE
文件夹展开和折叠状态不更新

### ISSUE THREAD

**Issue by xuezh01** [star7th/showdoc#2222]
点击左侧箭头展开或折叠,文件夹的展开和折叠状态不会跟着更新

**Comment by star7th** [comment]
会的。请提供一个 不会  的网址来看看。

**Comment by star7th** [comment]
实测可以正常折叠和展开。
如果你说的是是想把折叠和展开的状态保存到服务器，供下次使用。那么，showdoc不打算支持这种。

**Comment by xuezh01** [comment]
> 会的。请提供一个 不会 的网址来看看。

http://doc.laoleng.vip/web/#/539/3926

**Comment by xuezh01** [comment]
> 实测可以正常折叠和展开。 如果你说的是是想把折叠和展开的状态保存到服务器，供下次使用。那么，showdoc不打算支持这种。

我指的是文件夹图标

**Comment by star7th** [comment]
你提供的这个网址，图标在折叠和展开的时候，会变化的。可能只是你的浏览器扩展冲突问题

**Comment by xuezh01** [comment]
> 我指的是文件夹图标

点左侧小三角,右侧方块图标不会变,我试了chrome和edge
文件夹可以正常展开

**Comment by star7th** [comment]
我知道你意思了。就是  单纯点击箭头的时候，文件夹图标没有替换成展开的图标。后面改一下

**Comment by xuezh01** [comment]
> 我知道你意思了。就是 单纯点击箭头的时候，文件夹图标没有替换成展开的图标。后面改一下

好的,辛苦
