### ISSUE TITLE
退出账号,尤其是管理员账号时,页面无法进行任何操作

### ISSUE THREAD

**Issue by xuezh01** [star7th/showdoc#2223]
退出账号,尤其是管理员账号时,页面无法进行任何操作
整个页面点击无效
必须F5刷新后才可进行操作

**Comment by star7th** [comment]
我刚刚使用docker镜像搭建了一个环境来看。并没有发现你说的问题。如果有必要，请提供可重现例子。

**Comment by xuezh01** [comment]
> 我刚刚使用docker镜像搭建了一个环境来看。并没有发现你说的问题。如果有必要，请提供可重现例子。

http://doc.laoleng.vip/web/#/783/6104
test1  test123
登录,随便打开一个默认项目,然后退出账号
浏览器会回到首页,然后自动跳转到我指定的一个项目
进入后,这个页面就无法点击了

**Comment by star7th** [comment]
用你的地址，我试了两次，都是正常可点击的

**Comment by xuezh01** [comment]
> 用你的地址，我试了两次，都是正常可点击的

那就不管他了,影响不大,感谢回复
