### ISSUE TITLE
升级到最新版后所有图片都挂了。。。

### ISSUE THREAD

**Issue by guoai2015** [star7th/showdoc#223]
之前是 
`![](Public/Uploads/2017-10-16/59e4536944eb6.jpg)`
升级到2.0.2图全挂了
必须得改成
`![](/Public/Uploads/2017-10-16/59e4536944eb6.jpg)`
这样才显示

我要改到何年何月。。。

**Comment by star7th** [comment]
原来的程序里写的是绝对地址，是不会有问题的。你要改成相对地址那就没办法了

**Comment by guoai2015** [comment]
之前的版本写相对地址和绝对地址都可以，现在最新版只支持绝对地址了

**Comment by star7th** [comment]
官方推荐绝对地址
