### ISSUE TITLE
表格项目&页面自适应问题

### ISSUE THREAD

**Issue by XJY00** [star7th/showdoc#2232]
1. 有时表格的数据不能够正常的更新修改后的内容，不会触发自动保存，但是会保存到草稿
2. 电子表格是否能够添加到常规项目的分页中？
3. TOC的页面标题大纲在不同缩放的电脑页面不能显示或显示不完整，必须要调整浏览器缩放才行
4. 移动端页面自适应

页面自适应的问题以前提过，请告诉我自己如何自行修改CSS？
比如我用docker部署了showdoc，能在web-src路径下里找到对应的css修改来实现页面自适应吗？

**Comment by star7th** [comment]
表格项目不能自动保存，参考这个问题 https://github.com/star7th/showdoc/issues/2015 

电子表格是否能够添加到常规项目的分页中  参考这个问题  https://github.com/star7th/showdoc/issues/1836 

TOC由于需要占据一定宽度，故不支持小屏、或者把自己屏幕缩放成小屏效果

请举例说明移动端适应问题

**Comment by star7th** [comment]
二次开发请参考 https://www.showdoc.com.cn/help/1385576954326448

docker里面安装有Node环境，可进入docker命令行，自行修改和build

**Comment by star7th** [comment]
showdoc主要为技术文档场景，如果你重度使用电子表格功能，则可能需要思考下自己是否更适合其他开源软件，比如说专门做在线表格的

**Comment by XJY00** [comment]
强烈建议加保存按钮，有自动保存草稿就可以了（自动保存和自动保存草稿应该不是一个东西吧）
现在是完全不知道什么时候发生自动保存事件，也没有弹窗提示，
所谓的单元格弹起事件也不清楚是什么时候怎么发生的，宁愿不要自动保存，还不如有个保存按钮方便。

其他的问题都无所谓啦

**Comment by star7th** [comment]
新版里，表格项目已经增加手动保存按钮。
