### ISSUE TITLE
部署后无法访问，什么也不显示

### ISSUE THREAD

**Issue by shxiq01** [star7th/showdoc#2235]
<img width="1106" alt="874990fd4e6d856c09ed1ad693a4a37b" src="https://github.com/user-attachments/assets/65545e5b-4b26-4d2f-8f50-b03246b65d77">

**Comment by star7th** [comment]
这就对了。你去浏览器访问就好了

**Comment by star7th** [comment]
如果浏览器无法访问，则可能你的服务器有防火墙或者安全组之类的

**Comment by shxiq01** [comment]
> 如果浏览器无法访问，则可能你的服务器有防火墙或者安全组之类的

浏览器无法访问，检查了一下没有防火墙，因为安装mysql、redis那些都能直接访问

**Comment by star7th** [comment]
从你的截图看，端口服务已经起来了的。你可以执行这个看看

curl 127.0.0.1:4999/web/

**Comment by shxiq01** [comment]
> 从你的截图看，端口服务已经起来了的。你可以执行这个看看
> 
> curl 127.0.0.1:4999/web/

谢谢，找到问题了，是VPN的问题。。。
