### ISSUE TITLE
最新版导出

### ISSUE THREAD

**Issue by java-xdo** [star7th/showdoc#2239]
最新版导出按钮在哪呀，新建项目后，找不到导出按钮

**Comment by star7th** [comment]
截图看下

java-xdo ***@***.***>于2024年7月25日 周四下午12:12写道：

**Comment by java-xdo** [comment]
![Uploading 微信图片_20240725133337.png…]()

**Comment by java-xdo** [comment]
不知道怎么上传图片，showdoc登录后，默认展示项目列表页，没有看到导出按钮

**Comment by java-xdo** [comment]
<img width="960" alt="微信图片_20240725133337" src="https://github.com/user-attachments/assets/69566c49-fe3a-4948-88d8-4c7c64f9adc7">

**Comment by star7th** [comment]
鼠标放上具体某个项目的时候，右边会显示  ...   按钮

**Comment by java-xdo** [comment]
![image](https://github.com/user-attachments/assets/f28746a6-a35a-409c-adb1-623061ecc6eb)

**Comment by java-xdo** [comment]
是需要赋权限吗？没有显示呀

**Comment by star7th** [comment]
导出菜单放在里面了。点击进入该项目，然后右上角下拉菜单有

**Comment by java-xdo** [comment]
![image](https://github.com/user-attachments/assets/c84ec1e2-5c70-4e66-a7ca-e4e3f5c46db6)
也没有下拉菜单呀

**Comment by star7th** [comment]
从界面上看，你不是项目的管理员，没有导出权限。https://github.com/star7th/showdoc/issues/2220

**Comment by star7th** [comment]
等一下，你这个是runapi项目？ 那就跑runapi客户端去操作。

**Comment by star7th** [comment]
showdoc网页本来就没有runapi的全功能。

**Comment by star7th** [comment]
反正，必须是 showdoc项目，且是项目管理员，才能在showdoc网页上看到导出按钮

**Comment by java-xdo** [comment]
![image](https://github.com/user-attachments/assets/83c24698-bd07-4b58-9c75-1d3d07b3d0de)
runapi项目，上，导出按钮也没找到

**Comment by star7th** [comment]
点击左侧栏上方的分享按钮， 导出离线项目

**Comment by java-xdo** [comment]
好的，感谢
