### ISSUE TITLE
建议将1.x版本，api模板样式适配一下，那个样式醒目点。

### ISSUE THREAD

**Issue by haibozhou1011** [star7th/showdoc#224]
建议将1.x版本，api模板样式适配一下，那个样式醒目点。

**Comment by star7th** [comment]
api模板样式适配一下  是什么意思

**Comment by haibozhou1011** [comment]
新版 api接口模板 ，表格表头 没有原来的 蓝色，代码块，高亮也没有原来的好，建议默认 也加入一下 请求参数示例代码块 模板。

**Comment by star7th** [comment]
这是整体风格改变。在当前风格下，表格头加蓝色会相当难看

**Comment by star7th** [comment]
现在已经参照原来样式做了些许优化

**Comment by haibozhou1011** [comment]
那个版本，能够优化后结果！

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by star7th** [comment]
最新版。
效果看这里https://www.showdoc.cc/web/#/demo?page_id=7

**Comment by haibozhou1011** [comment]
这个好，谢谢！

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
