### ISSUE TITLE
镜像版本和实际代码版本不匹配

### ISSUE THREAD

**Issue by weily2** [star7th/showdoc#2248]
我用容器跑了一个showdoc:v2.10.8，但是打开网站后进入后台却提示版本是v2.9.15
![Lenovo20240815172414](https://github.com/user-attachments/assets/33ccdc5e-0602-4d8d-99c8-055eef5c8468)

![Lenovo20240815172424](https://github.com/user-attachments/assets/222ee3bf-22ea-4025-8edd-c9d63280dd8a)

**Comment by star7th** [comment]
不再维护旧版。旧版可能之前有过搞错的情况。你可以确定下最新的几个版本是否有这样的情况。

weily2 ***@***.***>于2024年8月15日 周四下午5:27写道：

**Comment by weily2** [comment]
感谢，我自己根据Dockerfile 构建了一个。
