### ISSUE TITLE
通用登录首次注册时能否增加姓名变量

### ISSUE THREAD

**Issue by 99u** [star7th/showdoc#2253]
大佬好， 我这边参照showdoc通用登录文档 [https://www.showdoc.com.cn/p/0fb2753c5a48acc7c3fbbb00f9504e6b](url)  已可以顺利完成登录功能，这里提个小建议，希望能考虑下
即首登时，接口注册的用户，似乎只有用户名，姓名字段初始值为空，能否额外增加一个name姓名变量呢，用于首登时传姓名过来

**Comment by star7th** [comment]
这个可以有，有空的时候改下

**Comment by star7th** [comment]
> 用户名能不能改？我用docker搭建，然后用户名只能是showdoc

跟本主题无关的问题请勿在这里提问。

**Comment by 99u** [comment]
> 这个可以有，有空的时候改下

好滴

**Comment by star7th** [comment]
新版已经支持姓名name字段
