### ISSUE TITLE
是否可以增加一个公开项目列表页面？

### ISSUE THREAD

**Issue by jagtu** [star7th/showdoc#226]
公开项目列表页面，可供任何登录与非登录的用户查看。

或者我可以在哪个地方添加这个代码？

非常感激您的分享！

**Comment by star7th** [comment]
官方不想做这个功能，因为小众。
web_src是前端源码，server是后端目录。
前端使用wepack+vue+element，后端使用thinkphp3 具体自己去搜索它们的使用文档
