### ISSUE TITLE
关于富文本的支持

### ISSUE THREAD

**Issue by vaas1993** [star7th/showdoc#2263]
是否有增加支持富文本的计划？
今天跟同事在寻找开源且功能足够简约专注的知识库，后来想想还是showdoc来的直接干脆
但说服不了IT部门以外的同事使用markdown，请问未来是否有增加富文本支持的计划？

**Comment by star7th** [comment]
可是 showdoc 本身定位就是 it 相关人员，没有特意让非 it
人员使用的。维护富文本是一个挺大的坑。如果说富文本能带来更大的使用量，那倒还不错。但是我有预感  这个事情会带来很大工作量的同时、不会有太多人用。

vshen ***@***.***>于2024年9月10日 周二上午10:14写道：

**Comment by star7th** [comment]
而且 showdoc 的编辑器是有编辑按钮的，他们也不用去记住 markdown 语法。即使富文本编辑器，不也一样是点图标的么。

Chen Xing ***@***.***>于2024年9月10日 周二上午10:29写道：

**Comment by vaas1993** [comment]
好的明白了，谢谢
