### ISSUE TITLE
showdoc 目录调整 出现莫名奇妙的问题 要么有些子菜单乱跑 要么子菜单样式乱了

### ISSUE THREAD

**Issue by yangyz** [star7th/showdoc#2272]
![image](https://github.com/user-attachments/assets/cd101416-4ede-41a6-943e-a911c90d63ae)

**Comment by yangyz** [comment]
![image](https://github.com/user-attachments/assets/690cb63d-ef4b-4200-bebd-a86c96462263)

**Comment by yangyz** [comment]
是不是要升级版本 才可以解决啊

**Comment by yangyz** [comment]
![showdoc目录文件丢失问题](https://github.com/user-attachments/assets/056417e3-2616-4d5f-abba-aa0ea2263308)
 
目录直接丢了  上传了gif 动图

**Comment by yangyz** [comment]
目前的这个项目  接口 有一定的数量 大几百应该是有的

**Comment by star7th** [comment]
可能是历史文档里，页面id和目录id重复引起的。参考这个 https://github.com/star7th/showdoc/issues/1957 ，将项目复制一份，然后以后都在复制品的基础上修改就好。

**Comment by davieee** [comment]
> 可能是历史文档里，页面id和目录id重复引起的。参考这个 #1957 ，将项目复制一份，然后以后都在复制品的基础上修改就好。

文档多了之后拖动排序要等好久，抓包一看，每次拖动都要提交好多数据
