### ISSUE TITLE
收到网警警告文件上传漏洞

### ISSUE THREAD

**Issue by dysodeng** [star7th/showdoc#2273]
近日我们部署的showdoc收到网警提示发现文件上传漏洞，我给2家不同城市的企业部署过showdoc，都收到这个漏洞的警告，更新最新版漏洞依然存在
<img width="555" alt="image" src="https://github.com/user-attachments/assets/e3b564c7-611f-4db4-a012-aaf4ac355aaa">
<img width="628" alt="image" src="https://github.com/user-attachments/assets/7c368c90-73c8-44df-9616-d1bf845cbafe">
<img width="641" alt="image" src="https://github.com/user-attachments/assets/0f98823f-c831-4578-88e8-1a632e46b9ce">
<img width="560" alt="image" src="https://github.com/user-attachments/assets/1d2ba07d-508b-4a6d-a93d-b2606e1d7937">

**Comment by star7th** [comment]
你发的这两个漏洞描述，我确定最新版已经修复。
但存在可能早期已经被人上传了风险文件。对于已经上传的文件，在 /Public/Uploads 下，需要自己手动清理。

**Comment by star7th** [comment]
另外就是，确认你更新的方式正确。我觉得有可能是你没更新对 https://www.showdoc.com.cn/help/13732

**Comment by dysodeng** [comment]
> 另外就是，确认你更新的方式正确。我觉得有可能是你没更新对 https://www.showdoc.com.cn/help/13732

好的，我再试试

**Comment by sylar003** [comment]
@star7th 搭楼请教一下楼主，我碰到的应该也是类似的问题，是否需要更新PHP版本？还是说仅更新showdoc后就不会被扫查到？

**Comment by ilaotan** [comment]
亲身经历 --user=root   --privileged=true 这种给docker主机权限的玩意，叠加webshell  直接进机器内部畅行无阻了 ，不知道作者为什么要这么搞，作为一个开源作者，别人提了意见，还一意孤行，哎

**Comment by star7th** [comment]
理论上更新 showdoc 就好

不想当厨子的老谭 ***@***.***>于2024年10月8日 周二下午7:16写道：

**Comment by star7th** [comment]
> 亲身经历 --user=root --privileged=true 这种给docker主机权限的玩意，叠加webshell 直接进机器内部畅行无阻了 ，不知道作者为什么要这么搞，作为一个开源作者，别人提了意见，还一意孤行，哎

比在这里说什么一意孤行的话，对他人的意见，我都是有理有据地说明不接受的原因。某些系统上去掉权限参数会导致挂载的目录不可写。所以为了便利性，就保留这些权限参数。如果你能帮我测试遍大部分系统，确认现在的软件更新了，去掉这个过年前就加上了的参数也不会造成问题，那就可以去掉。你都不测试过系统的兼容性，就盲目让我去掉参数，我觉得你才是一意孤行。
再有问题可开新issue讨论，只要是合理的建议，我会有理有据说明为什么接受或者为什么反对。不要在这里无关问题讨论。
