### ISSUE TITLE
runapi的bug

### ISSUE THREAD

**Issue by Vec9527** [star7th/showdoc#2274]
DEL请求, 不论请求参数如何设置, 此请求头的content-type总是application/json;charset=UTF-8, 这就导致DEL请求只能通过请求体的方式传参, runapi版本是3.0.7

**Comment by star7th** [comment]
能否截图说明

**Comment by Vec9527** [comment]
query参数时, 虽然content-type不对, 但java后端自动解析了路径参数, 得到了name, 如下图:



form-data参数时, content-type应该为multipart/form-data, 但实际如下图:



x-www-form-urlencoded参数时, content-type应该为application/x-www-form-urlencoded,但结果还是application/json, 如下图:



附java后端测试源码:







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "star7th/showdoc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月30日(星期一) 中午1:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [star7th/showdoc] runapi的bug (Issue #2274)





 
能否截图说明

**Comment by star7th** [comment]
看不到截图。要登录github才能传图。

**Comment by Vec9527** [comment]
query参数时, 虽然content-type不对, 但java后端自动解析了路径参数, 得到了name, 如下图:
![12b792afdad7c316ba446db28f4f0949](https://github.com/user-attachments/assets/563cf65e-d207-48c7-9dfd-c59e22ad0c2b)


form-data参数时, content-type应该为multipart/form-data, 但实际如下图:
![53d4718efc98ec35e157b6c1ce3bc5fb](https://github.com/user-attachments/assets/82b77d13-d8c7-4760-ae46-f7ac5953cf27)



x-www-form-urlencoded参数时, content-type应该为application/x-www-form-urlencoded,但结果还是application/json, 如下图:
![66399cb26a9b1681f7b7d3ff37b0c29b](https://github.com/user-attachments/assets/e0789110-0629-4344-a22f-3fee2a3084da)



附java后端测试源码:
![code](https://github.com/user-attachments/assets/4ed77d2e-1600-4d2d-ba78-e84a99a47d83)

**Comment by star7th** [comment]
我也确实发现你说的问题了。应该是Content-Type没自动选好。
这样，你切换到Header页面，强制指定 Content-Type 看看

**Comment by star7th** [comment]
好像强制指定Content-Type的版本我还没发布出去。估计你也指定不了。
等下次发版的时候我再一并解决这些问题吧

**Comment by Vec9527** [comment]
可以指定, 在Headers栏指定content-type时, 值是追加在原值后面的, 如图:
![image](https://github.com/user-attachments/assets/d1ec452d-6de8-4615-9b1e-269d73f11b6a)

如果改成指定Content-Type(首字母大写), 结果是覆盖原值, 如图:
![image](https://github.com/user-attachments/assets/383989fd-609c-4597-abac-9669ff74a451)

以上后端均无法获得name值, 如果将Content-Type设置成multipart/form-data, 并在form-data上加上参数, 后端直接报错: the request was rejected because no multipart boundary was found. 如图:
![image](https://github.com/user-attachments/assets/65a2e452-c86a-43fa-a544-188d9b827e19)

另外, 通过写执行前脚本的方式改content-type, 效果跟上面一致

**Comment by star7th** [comment]
我发现问题了。下个版本修复

**Comment by star7th** [comment]
已更新客户端，重新下载安装包即可 https://www.showdoc.com.cn/runapi
