### ISSUE TITLE
安全漏洞问题

### ISSUE THREAD

**Issue by sylar003** [star7th/showdoc#2276]
作者你好，根据之前和你的讨论，已经升级了showdoc到最新版本，但是公司的漏扫仍然扫到同样的漏洞，IT给的建议是升级PHP，能否给一些建议？

![img_v3_02fg_dd47b35d-13e9-4fdd-afcb-307a900b62dg](https://github.com/user-attachments/assets/54e20e31-b1f8-4354-8897-5c74e54cc891)

**Comment by star7th** [comment]
你是使用官方docker镜像安装的吗？ 官方docker镜像使用的是php7.4  ， 但你的截图里使用的是php7.3 。我不太理解这是怎么回事

**Comment by star7th** [comment]
如果你是手动php环境安装的，那不用想，果断将php环境升级到php8.0

**Comment by sylar003** [comment]
好的 谢谢作者，我是使用小皮里自带的7.3，确实没有用docker

另外升级到php8.0会对我的项目产生影响吗？php的依赖有什么需要注意的么？我确实没使用过php，谢谢回复

**Comment by star7th** [comment]
依赖的话应该跟原来差不多，你参考你原来开启了什么扩展就好。
php8.0是之前测试过完全兼容的，理论上没问题

**Comment by sylar003** [comment]
好的 非常感谢❤
