### ISSUE TITLE
apifox 导出swagger3.0格式接口导入之后body参数注释不显示

### ISSUE THREAD

**Issue by hai3333** [star7th/showdoc#2281]
![image](https://github.com/user-attachments/assets/6a047a91-3310-4e6d-aef3-bbd3f7eab26c)
![image](https://github.com/user-attachments/assets/a22b5ba3-62e8-4d45-a319-a7f5768e9091)

**Comment by star7th** [comment]
可否提供下脱敏后的文件给我导入来分析下

**Comment by hai3333** [comment]
[1.openapi.json](https://github.com/user-attachments/files/17564697/1.openapi.json)
麻烦分析一下 这是导出的单个接口文档

**Comment by hai3333** [comment]
[1.openapi.json](https://github.com/user-attachments/files/17564705/1.openapi.json)
麻烦分析一下 这个是单个接口参数为body情况下的文档

**Comment by star7th** [comment]
晚点看下

**Comment by hai3333** [comment]
用这个json吧 前面json脱敏完有点问题
[sm3.0.openapi.json](https://github.com/user-attachments/files/17566216/sm3.0.openapi.json)

**Comment by hai3333** [comment]
您好 有查出来是什么问题吗


发自我的iPhone

**Comment by star7th** [comment]
我推了一个代码更新上来。你更新再试试

**Comment by hai3333** [comment]
可以了 所有参数都在 formdata 里面 能用了感谢作者大大

发自我的iPhone
