### ISSUE TITLE
Runapi创建的项目showdoc在线编辑问题

### ISSUE THREAD

**Issue by yishen-yishen** [star7th/showdoc#2282]
现在通过runapi创建的项目，整个项目都不能通过showdoc网页编辑。

能否，(再runapi项目下)普通的md文档，showdoc网页上允许编辑，通过runapi生成的接口文档，showdoc网页继续维持现在，不允许编辑。即 这个是否允许编辑的范围，从整个项目，细化到项目中的单个文档？

使用场景：runapi项目中，会有一些，说明介绍之类的非api接口文档，像是需求收集/BUG反馈/基础介绍之类的，这些可能需要非开发人员参与维护(这些非开发人员，是没有runapi客户端环境的)。这些非api的文档，确实是可以单开一个showdoc项目，方便网页编辑。但一个项目的东西，分开放两个地方，不方便管理。
而且，runapi的md编辑功能，与showdoc网页相比也简单很多(产品重心不一样，我能理解)，图片粘贴上传都不行，只能插入图片链接。

**Comment by star7th** [comment]
要在showdoc上编辑runapi的md文档，技术上是可以的，但是产品逻辑上有点绕，容易搞混用户。两种项目耦合也可能为以后的扩展带来麻烦。
我觉得比较好的方式依然是使用runapi来编辑md文档，只是说runapi的md编辑器需要完善，比如支持插入模板和上传图片。
这个后面完善下runapi的编辑md功能。

**Comment by star7th** [comment]
已更新，重新下载安装即可 https://www.showdoc.com.cn/runapi
