### ISSUE TITLE
showdoc v3.3.0 无法搜索问题

### ISSUE THREAD

**Issue by Initarts** [star7th/showdoc#2286]
升级最新版showdoc v3.3.0后，无法搜索，查看日志报500错误
![image](https://github.com/user-attachments/assets/bf4dfc02-5835-4e34-a2a7-67db0b50ef7c)

![image](https://github.com/user-attachments/assets/9c634ed9-6980-4565-a660-d53a45b48912)

**Comment by star7th** [comment]
看看浏览器的网络请求返回了什么报错

**Comment by Initarts** [comment]
后台升级的时候没有提示php版本兼容问题，修改代码后正常了。

![image](https://github.com/user-attachments/assets/09eb9238-cf8e-4f4b-9478-2fe1e056dc7d)

**Comment by star7th** [comment]
ok，我晚些改下代码兼容再提交，确实没考虑到旧版兼容语法。
