### ISSUE TITLE
后台站点设置-网站首页-[跳转到登录页面]无效

### ISSUE THREAD

**Issue by PickX33** [star7th/showdoc#2295]
经测试，在打开网站的时候，会请求这样的地址。
> https://11x.xxx.xxx/server/index.php?s=https://11x.xxx.xxx/web/../server/index.php?s=/api/common/homePageSetting

对应返回:
```json
{
  "error_code": 999,
  "error_message": "无法加载模块:Https: 。错误位置：/var/www/html/server/ThinkPHP/Library/Think/Dispatcher.class.php  178"
}
```

是否是请求地址，附带了原始地址，导致错误。

版本为 Docker 版本 latest
Digest: sha256:36201b6751d2511143df665c1daa05931b469d1933fbe6acee8ed5cc5b6cecdd

**Comment by star7th** [comment]
我知道问题在哪里了。晚点改下

**Comment by yejiuxing** [comment]
我还以为是我手动安装的包有问题，结果大伙都这样，现在没有报错了，但是同样无法跳转

**Comment by star7th** [comment]
推送代码更新了，应该没问题了
