### ISSUE TITLE
填写注册页面post后返回404

### ISSUE THREAD

**Issue by avyou** [star7th/showdoc#23]
填写注册页面post后返回404，无论nginx ，还是apache, 都是404

**Comment by star7th** [comment]
截图看下？尤其是看看地址栏的url
试着开启apache的htaccess支持

**Comment by avyou** [comment]
你好，我是下载最新的源码，登陆和注册都是返回404
![image](https://cloud.githubusercontent.com/assets/4991219/12407423/2733a6bc-be92-11e5-9b57-1f203fee041d.png)

![image](https://cloud.githubusercontent.com/assets/4991219/12407441/51e0129c-be92-11e5-8cc5-701e0ae2fd33.png)

**Comment by avyou** [comment]
nginx 虚拟主机的配置：
server {
    listen       80;
    server_name  showdoc.mytest.cc;

    charset utf8;

    location / {
        root   /data/www/showdoc;
        index  index.php index.html index.htm;
        if (!-e $request_filename) {
           rewrite  ^/(.*)$  /index.php/$1  last;
           break;
        }
    }

    location ~ .php {

                    root   /data/www/showdoc;
                    fastcgi_pass   127.0.0.1:9000;
                    fastcgi_index  index.php;
                    fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
                    include        fastcgi_params;
                    set $path_info "";
                    set $real_script_name $fastcgi_script_name;
                    if ($fastcgi_script_name ~ "^(.+?\.php)(/.+)$") {
                            set $real_script_name $1;
                            set $path_info $2;
                    }
                    fastcgi_param SCRIPT_FILENAME $document_root$real_script_name;
                    fastcgi_param SCRIPT_NAME $real_script_name;
                    fastcgi_param PATH_INFO $path_info;
    }


    access_log  /var/log/nginx/doc.access.log  main;
}

**Comment by star7th** [comment]
看下Application\Runtime\Logs\Home\的日志文件

**Comment by avyou** [comment]
可以了，日志提示数据库连接出错，但实际没有错，缓存引起的，我清了cache/* 和 common~runtime.php 就好了，谢谢！

**Comment by star7th** [comment]
新增了支持三级目录的功能；升级安装请参考部署手册中“升级安装”部分。http://blog.star7th.com/2016/05/2007.html
此外我新建了一个ShowDoc使用交流qq群（群号：564671853），欢迎探讨问题
