### ISSUE TITLE
 升级了新的版本,在markdown里直接贴图片报错

### ISSUE THREAD

**Issue by DevilMayCrySamsara** [star7th/showdoc#230]
有两个问题：
1.这是用docker部署的,看firebug貌似前台也报错了，页面提示框一片空白,然后我到官网尝试了一下贴图，发现也给了个提示框，但是是有问题提示的
“你尚未绑定邮箱，不能上传图片。请保存页面内容后，返回到项目列表页面，点击右上方的“更多”-“个人设置”进行邮箱的绑定与验证”
我想，应该也是报这个错,但是不知道为何页面挂了，然后关闭提示框，要关闭很多次才能关闭掉

2.原先也是docker部署,没升级之前,在markdown里面写链接，会新打开浏览器标签页,现在貌似不会新打开标签页,而是直接修改当前标签页的地址,但是修改也就修改了,页面没有刷新,会不会是新的版本升级以后，url发生了变化，多了一层web的contextpath,然后还多#的锚点，然后我markdown里面全部用html的a标签来实现链接了，这次的升级，感觉页面上的向下兼容性需要再多多关注

![default](https://user-images.githubusercontent.com/20835804/37088113-3c1fa462-2237-11e8-9103-b55a1acd61b2.png)

**Comment by star7th** [comment]
1、实测粘贴图片的功能没问题。自己仔细看网络请求返回的报错。
2、超链接的问题已经修复
