### ISSUE TITLE
新版本markdown实时预览的问题

### ISSUE THREAD

**Issue by mazechi** [star7th/showdoc#231]
打开文章并添加如图，实时预览没问题。
![qq 20180307224259](https://user-images.githubusercontent.com/3959927/37098468-e5e18760-2258-11e8-9d1c-cd8050987df8.png)

保存后，重新打开文章，右边的就不显示了，进行增删操作，会重新展示。
![qq 20180307224303](https://user-images.githubusercontent.com/3959927/37098479-eaace55a-2258-11e8-98f9-2114da676789.png)

**Comment by star7th** [comment]
重现不了此问题。建议贴上文本内容我重现下

**Comment by mazechi** [comment]
使用的是官网的文章内容，难道是我浏览器的问题，用的是遨游5，我换chrome试试先。

**Comment by mazechi** [comment]
我换了chrome，还是有这个问题，我对官网的所有文章进行操作，都有这个问题。

**Comment by star7th** [comment]
嗯，我现在重现问题了。先看下

**Comment by mazechi** [comment]
辛苦了，thx

**Comment by star7th** [comment]
想了下，没有明显思路。可能跟js执行顺序有关。
鉴于此点没有多影响操作，先放下。想到了再更新

**Comment by star7th** [comment]
已发布v2.2.1版，修复了此问题
