### ISSUE TITLE
有没有arch可装的runapi客户端呢？

### ISSUE THREAD

**Issue by xmlijian** [star7th/showdoc#2310]
官网只提供了deb包。我使用debtap和alien转包工具，都无法使用。

**Comment by star7th** [comment]
并没有，不是很想专门搭建环境去打一个arch的包。因为要增加维护人力成本。以后每次更新都要切换各种平台去打包，

看看后面有没有更多用户反馈有这方面的需求再决定是否要支持。

**Comment by lehkost16** [comment]
我是用detab成功转包成功了，手动删除了一些依赖，目前我的pkginfo是这样的
```
pkgname = runapi
pkgver = 3.1.0-1
pkgdesc = Runapi
url = https://www.showdoc.com.cn/runapi
builddate = 1735263509
packager = runapi
arch = x86_64
size = 285111246
license = 

depend = desktop-file-utils
depend = hicolor-icon-theme
depend = libnotify
depend = libsecret
depend = libxss
depend = libxtst
depend = nss
depend = util-linux-libs
optdepend = libappindicator-gtk3
```

**Comment by star7th** [comment]
非常好，动手能力强

**Comment by xmlijian** [comment]
> 我在基于arch的endevouros下，使用detab转包成功了，手动删除了一些依赖，目前我的pkginfo是这样的，使用下来除了一个样式的问题外，也没有发现其他的影响
> 
> ```
> pkgname = runapi
> pkgver = 3.1.0-1
> pkgdesc = Runapi
> url = https://www.showdoc.com.cn/runapi
> builddate = 1735263509
> packager = runapi
> arch = x86_64
> size = 285111246
> license = 
> 
> depend = desktop-file-utils
> depend = hicolor-icon-theme
> depend = libnotify
> depend = libsecret
> depend = libxss
> depend = libxtst
> depend = nss
> depend = util-linux-libs
> optdepend = libappindicator-gtk3
> ```

666 。我回去验证下。 之前没用过liunx系统， arch流畅度感觉比ubuntu好一些。 但是ubuntu包比较完善。。。 自己还对这块东西搞不明白。。。
