### ISSUE TITLE
新版本内容中表格适配不好

### ISSUE THREAD

**Issue by jagtu** [star7th/showdoc#232]
新版本内容的里的表格比较宽时会左右滚动，体验不好。

**Comment by star7th** [comment]
旧版的也会

**Comment by star7th** [comment]
实际上表格过宽的时候是应该滚动，否则没法看到更长的内容

**Comment by jagtu** [comment]
比如某个列固定宽带，然后高度自适应。事实上，我觉得这样可能体验更好。

旧版本是会这样的，除非表格真的太长太长

**Comment by star7th** [comment]
高度是自适应的。
某个列固定，效果跟现在差不多，都是会有滚动条
