### ISSUE TITLE
表格里面含子对象，能把子对象的单元格合并吗

### ISSUE THREAD

**Issue by park001** [star7th/showdoc#235]
想把子对象的样式设置的跟常规表格内容的值不一样，最好能把子对象的对齐方式改成独立于整列，且可以合并单元格，可以实现吗

**Comment by star7th** [comment]
你搜索一下markdown的表格语法。它支持的，showdoc都支持。不支持的只能自己写原生html实现

**Comment by park001** [comment]
@star7th 找到了，但是发现一个新问题，如果我插入<table>的html代码，查看元素时，发现自带出现5-6个<br>标签。。。。

**Comment by star7th** [comment]
插入的html不要有换行，会被转为p标签
