### ISSUE TITLE
api key token 不匹配

### ISSUE THREAD

**Issue by kongdeju** [star7th/showdoc#238]
你好，

     我们在本地搭建了一个showdoc , 想通过api的形式添加文档，安装文档调用接口，但是返回信息一直是

     error_message api_key 或 api_token 不匹配 error_code 10306

     但我是从showdoc上面直接复制的key与token, 不知道什么原因，特来请教。

**Comment by star7th** [comment]
确保参数正确，用表单的方式提交。
