### ISSUE TITLE
忘记密码了怎么办？

### ISSUE THREAD

**Issue by bolen** [star7th/showdoc#239]
隔了几天忘记密码，有什么办法吗

**Comment by star7th** [comment]
常见问题  https://www.showdoc.cc/web/#/help?page_id=16118

**Comment by bolen** [comment]
我部署在本地的，我看本地mysql没有这个数据库，使用的sqlite还是什么的，请帮助

**Comment by star7th** [comment]
好好看常见问题

**Comment by bolen** [comment]
OK，非常感谢，我看到了，初始化的密码值是多少，是用md5的吗

**Comment by bolen** [comment]
自己找吧，非常感谢

**Comment by star7th** [comment]
再好好看常见问题。别再重复问了

**Comment by bolen** [comment]
不好意思，打扰了
