### ISSUE TITLE
A bug about to click the left content

### ISSUE THREAD

**Issue by lsqswl** [star7th/showdoc#240]
If we click the left content twice quickly, the left content will not be clicked again.

Can you confirm and fix it?

**Comment by lsqswl** [comment]
I don't find it appear on the example web. but my website  appear the problem. I don't know why.

**Comment by lsqswl** [comment]
http://www.yyxx100.com/showdoc/web/#/2?page_id=20

**Comment by star7th** [comment]
I'm sorry that I forget to update the code on github. Now it has been fixed in the latest code
