### ISSUE TITLE
Markdown超链不能跳转问题

### ISSUE THREAD

**Issue by yuxingxin** [star7th/showdoc#241]
同一个目录下面的不同文档，彼此添加对方为超链接，发现不能跳转，跨目录的文档则可以跳转成功

**Comment by star7th** [comment]
现在新版的策略是统一在新窗口打开超链接。检测是否使用新版代码。

**Comment by yuxingxin** [comment]
使用的是2.0.5这个版本的代码

**Comment by star7th** [comment]
试试https://www.showdoc.cc 有没有问题。没有就是版本问题了。用2.6

**Comment by yuxingxin** [comment]
OK，更新了2.0.6解决了这个问题
