### ISSUE TITLE
用户注册 验证码一直提示无效

### ISSUE THREAD

**Issue by tivonheng** [star7th/showdoc#244]
用户注册 验证码一直提示无效
![image](https://user-images.githubusercontent.com/287240/37888303-3de5daac-30f9-11e8-976d-c52a8959800f.png)

**Comment by star7th** [comment]
先到php.ini文件下找找session的保存目录，然后检查安装session目录有没有写入权限，或者可不可能是磁盘空间满了的问题

**Comment by never615** [comment]
你解决了吗?
我的php.ini  session.save_path = "/tmp"
这个目录777权限,磁盘空间也有.
还是不行
