### ISSUE TITLE
表格预览与实际显示效果不一样

### ISSUE THREAD

**Issue by tianqi0072600** [star7th/showdoc#246]
表格预览与实际效果不一样
表格在预览是，可以根据字符长度自动调整
而实际页面却是接近均分的显示，显示效果奇丑，希望能够改进
另外整个页面宽度太窄，影响显示效果

**Comment by star7th** [comment]
以实际效果为准。
关于效果的问题，请截图说明。因为示例项目并没有难看。https://www.showdoc.cc/web/#/demo?page_id=14980701

**Comment by isegon** [comment]
某一列中的内容如果长一点，表格行就会自动变宽，比较难看
