### ISSUE TITLE
请问本地部署的showdoc怎么取消上传图片的数量限制？

### ISSUE THREAD

**Issue by Morgan279** [star7th/showdoc#247]
本地部署的showdoc怎么取消上传图片的数量限制？

**Comment by star7th** [comment]
开源版的没有做数量限制

**Comment by Morgan279** [comment]
奇怪了，难道我下的不是开源版?不作限制的开源版是直接在github上下吗？

**Comment by star7th** [comment]
是在github下载

**Comment by Morgan279** [comment]
thanks

**Comment by Morgan279** [comment]
![default](https://user-images.githubusercontent.com/25718373/38593378-9c2e48c0-3d73-11e8-8181-63313d3254e5.png)
使用github上的代码也不行，上传图片超过10张时，会弹出以上弹框3次

**Comment by star7th** [comment]
开源版跟进就没集成检测数量的代码，怎么可能会限制数量呢。
先看下网络返回是什么信息
