### ISSUE TITLE
本地部署后，在搜索框输入文字后回车，出空白错误框

### ISSUE THREAD

**Issue by cisdu** [star7th/showdoc#249]
如图：
![searcherror](https://user-images.githubusercontent.com/5415710/38712733-27ac6d40-3f00-11e8-8b84-a33bd49e5677.png)

**Comment by star7th** [comment]
看下网络请返回啥内容

**Comment by cisdu** [comment]
sqlite3 not found ，这个怎么解决？
![sqlite3notfound](https://user-images.githubusercontent.com/5415710/38713061-e3bdc7ee-3f01-11e8-9cc0-069b200a789a.png)

**Comment by star7th** [comment]
把这句话网络搜索一下就有答案了

**Comment by cisdu** [comment]
找到了，谢谢。
在php.ini里面把”extension=php_sqlite.dll”和”extension=php_pdo_sqlite.dll”启用以便开启对SQlite的支持；也启用php_mbstring.dll；Linux服务器则不需要此操作。
