### ISSUE TITLE
模板不存在:./Application/Home/View/Item/Show.html

### ISSUE THREAD

**Issue by Sanae1513** [star7th/showdoc#25]
错误位置
FILE: /var/www/html/showdoc-master/ThinkPHP/Library/Think/View.class.php 　LINE: 110
TRACE
#0 /var/www/html/showdoc-master/ThinkPHP/Library/Think/View.class.php(110): E('\xE6\xA8\xA1\xE6\x9D\xBF\xE4\xB8\x8D\xE5\xAD\x98\xE5\x9C\xA8...')
#1 /var/www/html/showdoc-master/ThinkPHP/Library/Think/View.class.php(72): Think\View->fetch('', '', '')
#2 /var/www/html/showdoc-master/ThinkPHP/Library/Think/Controller.class.php(56): Think\View->display('', '', '', '', '')
#3 /var/www/html/showdoc-master/Application/Home/Controller/ItemController.class.php(102): Think\Controller->display()
#4 [internal function]: Home\Controller\ItemController->show()
#5 /var/www/html/showdoc-master/ThinkPHP/Library/Think/App.class.php(173): ReflectionMethod->invoke(Object(Home\Controller\ItemController))
#6 /var/www/html/showdoc-master/ThinkPHP/Library/Think/App.class.php(110): Think\App::invokeAction(Object(Home\Controller\ItemController), 'Show')
#7 /var/www/html/showdoc-master/ThinkPHP/Library/Think/App.class.php(204): Think\App::exec()
#8 /var/www/html/showdoc-master/ThinkPHP/Library/Think/Think.class.php(120): Think\App::run()
#9 /var/www/html/showdoc-master/ThinkPHP/ThinkPHP.php(97): Think\Think::start()
#10 /var/www/html/showdoc-master/index.php(24): require('/var/www/html/s...')
#11 {main}

**Comment by star7th** [comment]
尝试清理下缓存 Application/runtime；如果你开启了degub模式，请在配置文件关闭之；

**Comment by Sanae1513** [comment]
ok了，关闭了调试，thinks
