### ISSUE TITLE
Reload page at resize event versus hmtl5 video full screen mode

### ISSUE THREAD

**Issue by githubvvcao** [star7th/showdoc#251]
same problem as https://stackoverflow.com/questions/24712415/reload-page-at-resize-event-versus-hmtl5-video-full-screen-mode

Public/js/item/show.js

`
$(window).resize(function(){
    if( isMobile()){
        AdaptToMobile();
    }

    else if($(window).width() < 1000){
        AdaptToMobile();
    }else{
        window.location.reload();
    }
  });
`

**Comment by star7th** [comment]
It is designed to be so.When the page width changes ,it will reload
