### ISSUE TITLE
新建页面会有个无权限弹框提示

### ISSUE THREAD

**Issue by hutaoseven** [star7th/showdoc#254]
**本地测试（v2.1.1）会出现，如下图所示的权限提示，点击确认也能正常使用**
![image](https://user-images.githubusercontent.com/7609067/39115261-c61f4bc6-4713-11e8-8936-f0ffe0b71a52.png)

**Comment by star7th** [comment]
看看网络请求是哪一个链接返回此提示

**Comment by hutaoseven** [comment]
http://sd.test/server/index.php?s=/api/catalog/getDefaultCat

**Comment by star7th** [comment]
截图看下其传递的参数是什么

**Comment by hutaoseven** [comment]
![image](https://user-images.githubusercontent.com/7609067/39116180-54e60122-4716-11e8-9eac-763b6c325e91.png)

**Comment by star7th** [comment]
我刚修改了下，应该修复了此问题
