### ISSUE TITLE
执行sh showdoc_db.sh 报错File not found

### ISSUE THREAD

**Issue by wuwu20048** [star7th/showdoc#255]
部署开源版showdoc，url已修改成http://xx.com/server/index.php?s=/api/open/updateDbItem 。其中xx.com已改成自己域名。执行这几curl -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -d "from=shell&table_info=${table_info}&table_detail=${table_detail}&api_key=${api_key}&api_token=${api_token}&cat_name=${cat_name}" "${url}"   
会返回 File not found.

**Comment by star7th** [comment]
那你直接浏览器访问以下那个链接试试

**Comment by wuwu20048** [comment]
直接访问也是返回File not found.

**Comment by star7th** [comment]
那就跟脚本没关系。是你没安装部署好php环境。完整截图看下

**Comment by wuwu20048** [comment]
是截哪个图

**Comment by star7th** [comment]
forget it 。你搜索下"File not found."，有很多文章。

**Comment by wuwu20048** [comment]
其他功能都是能正常使用的，是环境安装问题吗

**Comment by star7th** [comment]
你去确保命令行能访问那个地址。尤其是本地host有没有要注意的地方

**Comment by wuwu20048** [comment]
可以了。是路径写错了。域名后面少了个 showdoc;  http://xx.com/showdoc/server/index.php?s=/api/open/updateDbItem  😢
