### ISSUE TITLE
前端上传图片有问题，不支持chrome，火狐支持

### ISSUE THREAD

**Issue by yuxing1994** [star7th/showdoc#256]
![qq 20180425105847](https://user-images.githubusercontent.com/19182789/39224057-bee45666-4877-11e8-886e-4db6d8ce4dbb.png)
![qq 20180425105831](https://user-images.githubusercontent.com/19182789/39224059-c04fad84-4877-11e8-9fb8-8fa372d49997.png)

**Comment by star7th** [comment]
完整的返回内容是什么，怎么会报错误。我是在chrome下开发的，从来没出现此问题

**Comment by star7th** [comment]
截图下完整的网络请求的返回字符。
我刚试了下，没问题。我的chrome版本是   65.0.3325.181（正式版本） （32 位）

**Comment by star7th** [comment]
不用截图了。既然是插件问题，那无解了。因为插件的问题我也无能为力

**Comment by star7th** [comment]
你可以排除法来看下是哪个插件的问题然后把它禁用

**Comment by yuxing1994** [comment]
![qq 20180425112809](https://user-images.githubusercontent.com/19182789/39224876-f2fd2500-487b-11e8-86a9-6fd804e4f4bc.png)
![Uploading QQ图片20180425112915.png…]()

**Comment by star7th** [comment]
图上来看返回格式没毛病。

**Comment by yuxing1994** [comment]
上传成功了，里面都看到了，都能直接访问，就是js 运行错了，不知道是插件还是哪里有问题

**Comment by yuxing1994** [comment]
![qq 20180425113421](https://user-images.githubusercontent.com/19182789/39224996-a07a61c0-487c-11e8-96de-2a916889c826.png)

**Comment by yuxing1994** [comment]
不知道哪个插件有问题

**Comment by star7th** [comment]
你只能一个个地禁用试试看看有没有问题。

**Comment by yuxing1994** [comment]
是油猴插件，测试出来了

**Comment by yuxing1994** [comment]
并且是弹窗阻止脚本拦截了，卧槽了
