### ISSUE TITLE
更新新版2.1后，项目里面新建文档弹出无权限

### ISSUE THREAD

**Issue by mazechi** [star7th/showdoc#257]
![qq 20180425110459](https://user-images.githubusercontent.com/3959927/39224191-8f1d987e-4878-11e8-85cc-82b6e531ca48.png)

实际是可以新建文档，也可以保存。
项目的所有人是我，权限应该没问题。
重新登录后，还是有这个问题。

**Comment by star7th** [comment]
v2.1.2 才是最新的

**Comment by mazechi** [comment]
恩恩，就是这个2.1.2

**Comment by star7th** [comment]
刷新浏览器js缓存？

**Comment by mazechi** [comment]
我清了缓存，不行

**Comment by star7th** [comment]
我下载了v2.1.2 全新安装测试了下，没发现你说的问题

**Comment by star7th** [comment]
严格按照部署手册说的步骤来

**Comment by mazechi** [comment]
不是，我的意思是，我就是按照你这个操作来的，我之前升级了好几次了的。
我重新升级一次看看有没有问题。

**Comment by star7th** [comment]
还有检查会不会是服务器端缓存了静态文件

**Comment by mazechi** [comment]
我重新升级一次，没问题了，打扰大佬了。
