### ISSUE TITLE
文档图片展示有问题，点击图片后，图片不会展示窗口当前位置，而是会展示在最上方

### ISSUE THREAD

**Issue by waitig** [star7th/showdoc#259]
文档图片展示有问题，点击图片后，图片会展示在页面最上方。
比如文档最低端有图片，那么点击图片后，图片的预览层会将图片显示在文档的最开始位置，需要将页面滚动到最上方才能看到。
示例：
https://www.showdoc.cc/web/#/59021223799393?page_id=332304501391930

**Comment by star7th** [comment]
已修复此问题
