### ISSUE TITLE
自动生成数据字典，如果数据库表结构过多，则curl脚本会执行失败

### ISSUE THREAD

**Issue by wuwu20048** [star7th/showdoc#260]
./showdoc_db.sh: line 27: /usr/bin/curl: Argument list too long
我猜测是通过表单提交的方式对内容长度有限制？

**Comment by star7th** [comment]
已经改好了。重新下载脚本：wget https://www.showdoc.cc/script/showdoc_db.sh

**Comment by star7th** [comment]
不知道是否是特殊字符导致切分失败。
但我这边没有这样的数据源供我测试，所以我是找不到原因的。我这边测试都没问题

**Comment by han8gui** [comment]
遇到的同样的问题，表近2000张

**Comment by han8gui** [comment]
接收的table_detail被截断了

**Comment by star7th** [comment]
@han8gui 具体哪里被截断？断点的符号是啥？

**Comment by han8gui** [comment]
@star7th 
本来因为是服务端配置问题，发现是字段注释乱码，被服务器截断了。
内容见下：
``` 
 &#xxx;∑&#xxx;π&#xxx;&#xxx;&#xxx;∑÷≈‰ //数字被替换成了x
```
解决方法：
去除即可

- - - 
不建议用shell脚本走HTTP请求生成，一方面是配置原因，另一方面不容易排查。

**Comment by star7th** [comment]
@han8gui 我突然意识到，如果注释中含有换行符，确实会截断。这个可能暂时无解。
另外，不走http，有其他方式推荐？如果说让用户输入账号密码。php程序去读，这样是不好的。php这边需要多一套管理体制去管理各种数据库配置和密码等信息，还会带来潜在的安全问题。
