### ISSUE TITLE
建议在线测试api添加参数可传file

### ISSUE THREAD

**Issue by hu-qi** [star7th/showdoc#264]
![image](https://user-images.githubusercontent.com/17986122/39393270-d0ab6efe-4af5-11e8-94b3-7a2a5bbbfe07.png)

希望能添加文件，类似于postman那样
![image](https://user-images.githubusercontent.com/17986122/39393282-f44b1b84-4af5-11e8-9ec5-78ccadc24a66.png)

小众需求，权当知会，适当忽略。
感谢这样方便的工具，前端也能写标准的接口文档了！感谢！

**Comment by star7th** [comment]
runapi只是为了解决简单的接口测试的，复杂的还是用postman吧
