### ISSUE TITLE
Sqlite数据库问题

### ISSUE THREAD

**Issue by wei772** [star7th/showdoc#265]
1. 在ubuntu14使用php5-sqlite读写的数据库无法用SQLiteStudio等工具打开
![image](https://user-images.githubusercontent.com/10583650/39610979-993981dc-4f86-11e8-8e27-3def49d4b6fe.png)
2. 在ubuntu16使用php7,php5-sqlite无法登陆，提示SQLSTATE[HY000]: General error: 11 database disk image is malformed
![image](https://user-images.githubusercontent.com/10583650/39611002-c4d45fec-4f86-11e8-9bc5-d54414d0ec41.png)

感觉sqlite问题比较多，建议提供其他数据库，并且提供数据迁移功能

**Comment by star7th** [comment]
我这边之前试过没问题

**Comment by wei772** [comment]
php5-sqlite的文件使用 sqlite3_analyzer分析提示：
 sqlite3_analyzer .\showdoc.db12.php
ERROR: database disk image is malformed
database disk image is malformed
    while executing
"db exists {SELECT 1 FROM pragma_compile_options
                WHERE compile_options='ENABLE_DBSTAT_VTAB'}"

我现在确实遇到这些 问题，感觉sqlite很不靠谱

**Comment by star7th** [comment]
你试着全新用github下载的数据库文件看能不能打开。因为我不知道是否是你的环境改写了数据库文件导致格式有异常

**Comment by wei772** [comment]
@star7th 
在github下载的全新数据库文件能打开。在ubuntu14使用php5-sqlite后写入数据就打不开了，但是在站点还是可以录入markdown文件。

**Comment by star7th** [comment]
那应该是ubuntu14的php5-sqlite不太兼容吧

**Comment by Ecareyu** [comment]
大佬，要不我们折中一下，同时支持sqlite和mysql，sqlite维护起来真鸡儿麻烦

**Comment by star7th** [comment]
@Ecareyu 不可能再支持mysql https://www.showdoc.cc/web/#/help?page_id=31990

**Comment by conanliuhuan** [comment]
阿里云虚拟云主机无法使用sqlite数据库。需要启用某个PHP组件才可以，然而虚拟云主机无法手动配置。

**Comment by euui** [comment]
Sqlite/showdoc.db.php文件不可写 虚拟主机无法配置 只能听天由命
