### ISSUE TITLE
本地部署后无法注册登录

### ISSUE THREAD

**Issue by zhangjpn** [star7th/showdoc#266]
ubuntu14.04上部署后在登录界面无法登录使用初始的账号密码(showdoc/123456)登录，提示"账号用户名或密码不正确"，在注册界面注册时提示“register fail”。

**Comment by star7th** [comment]
常见问题https://www.showdoc.cc/web/#/help?page_id=16118

**Comment by zhangjpn** [comment]
谢谢！
