### ISSUE TITLE
我根据API文档，通过API接口添加文档，无法支持markdown格式的文本或者html源码

### ISSUE THREAD

**Issue by bbqtk** [star7th/showdoc#267]
![image](https://user-images.githubusercontent.com/19991733/39748114-d7cbf8ea-52e1-11e8-998a-a410f0fbe9fd.png)

我想通过接口新增的文档内容是下面这个，请帮忙看一下:

<a name="applycompany"></a>
#### 注册公司
```
POST /company/apply
```

##### Body参数
新增公司请求对象

*名称* : data  
*标志* : 必填  
*类型* : [CompanyInfo](#companyinfo)

##### 响应

|HTTP代码|说明|类型|
|---|---|---|
|**200**|通用的回复格式|[Response](#response)|

###### 请求 path
```
/company/apply
```

###### 请求 body
```
json :
{
  "applyType" : "string",
  "tenantNo" : "string",
  "companyNo" : "string",
  "companyTaxNo" : "string",
  "companyName" : "string",
  "companyAddr" : "string",
  "companyTel" : "string",
  "taxpayerType" : "string",
  "companyBankName" : "string",
  "companyBankAccount" : "string",
  "invoiceType" : "string",
  "invoiceLimitAmountC" : "string",
  "invoiceLimitAmountCE" : "string",
  "invoiceLimitAmountS" : "string",
  "applyUserTel" : "string",
  "applyUserName" : "string",
  "applyUserEmail" : "string",
  "userType" : "string",
  "idNumber" : "string",
  "clientDeadline" : "string",
  "auditFileUrlBCC" : "string",
  "auditFileUrlTRC" : "string"
}
```

###### 响应 200
```
json :
{
  "code" : 0,
  "message" : "string",
  "result" : "object"
}
```

最后就会变成这样：
![image](https://user-images.githubusercontent.com/19991733/39748697-52ffffba-52e3-11e8-82ea-89d96933166c.png)

**Comment by star7th** [comment]
把以上内容复制到编辑框，然后保存。这个时候看下浏览器网络请求发送的数据体是怎样的，对比一下你发送就知道答案了。
主要是你没有传送相应的空行符号和换行符

**Comment by bbqtk** [comment]
谢谢，我最后发现了问题是因为空行符号和换行符没有的原因，已经解决了，在使用postman或者在线测试的工具的时候，这些工具会自动的帮我把空行符号和换行符去除掉，我后来直接使用代码来测试，没有问题了。
