### ISSUE TITLE
建议有个保存草稿的功能

### ISSUE THREAD

**Issue by JeryZeng** [star7th/showdoc#269]
建议有个保存草稿的功能，不然编辑的时候有时候经常忘了保存，重新打开就丢了，但是普通的保存就跳转去页面展示了，或者只保存不跳转都可以

**Comment by star7th** [comment]
本来做了。可是机制不完善，体验不好，所以又注释掉了。后面看重启下此功能

**Comment by han8gui** [comment]
没必要手写，成本还是很高。
可以做个小工具：输入表名，连接数据，直接生成markdown，已经实现，很简单的。

**Comment by star7th** [comment]
@han8gui 你是不是回复错地方了。好像你说的话跟保存草稿功能无关。

**Comment by han8gui** [comment]
@star7th 抱歉，已删

**Comment by star7th** [comment]
新版已支持草稿功能
