### ISSUE TITLE
mac下部署问题

### ISSUE THREAD

**Issue by ZaggerWang** [star7th/showdoc#27]
**在mac osx10.11下用系统自带`Apache(2.4.16)`+`PHP(5.5.27)`，再安装`mysql(5.7.11)`
，将showdoc数据库导入后，修改数据库配置文件，访问出错如下：**

![qq20160218-0 2x](https://cloud.githubusercontent.com/assets/11342795/13136009/b634ee36-d650-11e5-8079-11c8f218a3e3.png)

**Comment by star7th** [comment]
请先清空Application\Runtime下的文件，如果再不行则看Application\Runtime\logs错误日志来排查错误

**Comment by ZaggerWang** [comment]
清空`Runtime`目录后，还是如此，而`Runtime`目录下不会再有文件生成。

**Comment by star7th** [comment]
如果你浏览器访问时它不会有文件生成的话，请给这个目录可写权限

**Comment by ZaggerWang** [comment]
搞定，thks

**Comment by ZaggerWang** [comment]
用了一下，很不错，建议加一个**调整页面和目录**顺序的功能。

**Comment by star7th** [comment]
在编辑页面或目录的时候，可输入顺序号。用顺序号来调整顺序

**Comment by star7th** [comment]
新增了支持三级目录的功能；升级安装请参考部署手册中“升级安装”部分。http://blog.star7th.com/2016/05/2007.html
此外我新建了一个ShowDoc使用交流qq群（群号：564671853），欢迎探讨问题
