### ISSUE TITLE
Microsoft Edge 42.17134 编辑时回车丢失问题

### ISSUE THREAD

**Issue by DigitalPlatform** [star7th/showdoc#271]
Windows 10 1803 家庭中文版的 Edge 浏览器，在 Markdown 编辑器里面修改一个文档以后，保存，重新载入编辑，发现回车全部丢失，原来多行的文字挤成一行了。

我用另外一台还没有来得及升级的 Windows 10 (1803)电脑的 Edge 浏览器做同样操作，就没有回车丢失的问题。

**Comment by conanliuhuan** [comment]
建议使用Chrome/Firefox等真正的浏览器

**Comment by DigitalPlatform** [comment]
@conanliuhuan Edge 是 Windows 操作系统安装时候就带上的浏览器，没有特殊情况一般不会去安装 Chrome。而且国内有墙，Chrome 不是那么容易安装的；有些提供二手下载 Chrome 的网站，你又会不放心。并且 Edge 浏览器这个 showdoc 原本是支持的，只是最近 Windows 升级以后可能出现了一点兼容性问题。我们用 showdoc 不是玩的，是要用于工作的。希望开发者尽快解决这个兼容性问题。

**Comment by star7th** [comment]
Edge 浏览器是什么版本

**Comment by DigitalPlatform** [comment]
Microsoft Edge 42.17134.1.0

**Comment by star7th** [comment]
我去看了下，这浏览器还强制要求win10才能安装。
抱歉我没有win10环境。所以此浏览器的兼容性问题暂时不考虑。
建议使用Chrome

**Comment by DigitalPlatform** [comment]
@star7th 那就非常遗憾了。
我们是经过挑选，选中了 showdoc 这个软件，打算用于公司内部管理业务。没有给你们提 issue 以前，抱有一些美好的想象。但接触下来觉得你们这种维护和改进不是很得力啊。

我本人也是一个开源软件作者，用户一旦决定压上业务用这个软件，那期望值是很高的。不可能频繁更换软件。所以通常开发者需要踮起脚尖够一够用户的要求。开源本身是一种很大的提升。当你还是一个业余爱好者的时候，你觉得能编一个程序牛逼得不得了，很有自豪感，那时候所谓用户也少，对你赞誉有加；但用户越来越多，开始变成专业软件以后，用户的要求会突然拔高，一般开发者会猝不及防。

但这里面其实有很多缘分，缘分到了人家才会用你的软件。把你当专业软件开发者，是一种极大的信任。

本来 MarkDown 编辑界面很简单，弄个树状的文档管理系统也不是很难，我们实在是为了省事不想什么都自己开发才选来选去希望用个好的开源软件。但看来这个目标还达不到。算了我们自己后面抽空自己开发吧。

顺便提点意见：除了 SQLite 原始的数据库文件格式外，你们这个软件最好提供一个比较中立的导出和备份格式，以便数据可以交换和长期保存。直接保存 SQLite 数据库文件总不算个事儿。而且大备份不方便天天做，可能每天只需要拷贝日志增量部分即可。对了，你们最好提供日志模块，像一个成熟一点的系统，这样一旦系统被损坏的时候，先用大备份恢复，然后用此后的多个日备份恢复，尽可能恢复到出事儿以前的状态。

我看有人也提出希望支持 MySQL。如果开发的时候把数据库接口抽象一下，支持多种数据库不难。话说 SQLite 是寒酸了一点，如果有点规模的公司全部文档压上去还是有点够呛。

好，言尽于此，辛苦了，谢谢。

**Comment by DigitalPlatform** [comment]
@star7th 
> 如果说为了兼容小量浏览器而花太多精力，对开源开发者来说是不必要的

**Comment by DigitalPlatform** [comment]
> SQLite 是文件型数据库，而且纯文字信息不会很大。建议起一个定时任务，每天备份一个zip包即可满足备份需求

**Comment by star7th** [comment]
“如果有点规模的公司全部文档压上去还是有点够呛”——其实这点是对sq;ite的一点误解。
关于用sqlite的原因：

PHP环境默认支持Sqlite，所以只需要安装好PHP环境，即可使用ShowDoc，无须再安装mysql。这对于不懂mysql的开发者（如App开发者）来说会更容易一些。同时方便官方维护ShowDoc，不用维护和测试两个数据库版本

Sqlite的性能并不差，对于总项目数在一万以内的情况，基本不用考虑性能问题。所以完全足够普通公司或者团队的使用。

Sqlite数据库文件放在/Sqlite目录下，迁移和备份都十分简单，直接复制/转移该目录即可

**Comment by DigitalPlatform** [comment]
> Sqlite数据库文件放在/Sqlite目录下，迁移和备份都十分简单，直接复制/转移该目录即可

**Comment by star7th** [comment]
其实用mac的开发者很多；
sqlite的并发能力是不强，但真的完全够用。它会利用内存缓存的。中小公司中小团队，远远达不到它的并发上限。
数据库大小方面，其实不可能会有类似1G那么大的情况出现。实际上在小公司内部使用的话，其大小很大可能不足50M 。所以能增量备份会更好，但先不支持也没什么问题。

**Comment by star7th** [comment]
有机会的话跟同事借一下win10来做下浏览器兼容测试。
不过奇怪的是之前有Edge 使用者跟我反馈过说可以正常使用。

**Comment by renyh** [comment]
我是Win10，Edge版本是 41.16299.402.0，可以正常在Markdown 编辑器编写文本，没有丢失回车。
![image](https://user-images.githubusercontent.com/13568719/40299619-743056a4-5d19-11e8-9ec5-c23b3c641936.png)
![image](https://user-images.githubusercontent.com/13568719/40299670-975b0c8c-5d19-11e8-8514-269e99122dc5.png)

**Comment by DigitalPlatform** [comment]
@renyh

你是还没有升级到 redstone 的版本。我这个版本是刚升级一两个星期。

**Comment by DigitalPlatform** [comment]
@star7th 

> 有机会的话跟同事借一下win10来做下浏览器兼容测试。
> 不过奇怪的是之前有Edge 使用者跟我反馈过说可以正常使用。

Windows 10 redstone 以前的版本 Edge 是可以用的。我是最近一个周突然发现新版不能用的。我还有一台没有升级 redstone 的 Windows 10 的机器也是可以用的。

**Comment by renyh** [comment]
Windows 10安装更新之后，Microsoft Edge 42.17134.1.0
![image](https://user-images.githubusercontent.com/13568719/40570577-d147fa10-60be-11e8-96ea-34f25680d2c6.png)
showdoc编辑器丢失换行符
![image](https://user-images.githubusercontent.com/13568719/40570565-bde845b0-60be-11e8-9cb6-80413ef6e7a2.png)

**Comment by star7th** [comment]
我现在安装了虚拟机，确实发现了此问题。
看了一下网络请求的数据，它传输之前的换行符就已经不对了。所以后端是没问题的。问题是在前端。
前端编辑器上，showdoc使用的是开源编辑器https://github.com/pandao/editor.md 。我也暂时无解。目前这个问题只存在edge 42.17134这个版本上，其他版本和其它浏览器都没这个问题。

**Comment by SilasGao** [comment]
是win10更新之后，edge才出现这个问题的，更新之前一直都没问题

**Comment by DigitalPlatform** [comment]
# @star7th 

> 问题是在前端。前端编辑器上，showdoc使用的是开源编辑器https://github.com/pandao/editor.md 。我也暂时无解

您用了开源的组件其实反而就好办了，您直接给这个组件的作者提个 issue，就像我们给您提 issue 一样。怎么能说无解呢？难道假定天底下的开源组件作者都不理会别人的 issue？

**Comment by star7th** [comment]
@DigitalPlatform 你去那个项目看看就知道了，那个作者很少管issue

**Comment by DigitalPlatform** [comment]
@star7th 

您把他那个编辑器 fork 过来自己改，也是一个做法吧。然后给他提个 PR。可能我想得太简单了。

**Comment by star7th** [comment]
@DigitalPlatform 

要照顾小白。需要预览功能。

**Comment by star7th** [comment]
@DigitalPlatform  简单的话我早搞了。比较复杂，主要是需要熟悉代码的人才知道哪部分的代码转换出问题

**Comment by cloudwu** [comment]
@DigitalPlatform  我认为你应该去 Microsoft 那里给 Edge 提 Issue 啊，Edge 那边有更专业的团队。

**Comment by raindylong** [comment]
有一种快来讨好老子的即视感，既然用的是开源的产品，换个chrome/firefox有那么难么。
star已经证明是某个版本的Edge的问题了，为何还要去兼容这种错误的客户端行为？

感觉楼主可以去$M提一个BUG。

**Comment by DigitalPlatform** [comment]
@cloudwu 

> 我认为你应该去 Microsoft 那里给 Edge 提 Issue 啊，Edge 那边有更专业的团队

**Comment by DigitalPlatform** [comment]
@raindylong 

> 有一种快来讨好老子的即视感，既然用的是开源的产品，换个chrome/firefox有那么难么。
> star已经证明是某个版本的Edge的问题了，为何还要去兼容这种错误的客户端行为？
> 感觉楼主可以去$M提一个BUG。

开源的产品为啥要换浏览器来用？微软的 Edge 浏览器不是浏览器？我觉得您是不是有些什么潜台词，是不是有些厌恶微软的浏览器？您这么有开源精神，还用 GitHub 干什么？它不是已经被微软买了么。

“为何还要去兼容这种错误的客户端”，那以前那么多人各种产品做出的兼容各种浏览器行为的努力，都因为您这一句话白费了，还有害了？您这三观貌似比较邪乎。

**Comment by conanliuhuan** [comment]
@DigitalPlatform 
觉得这个工具好用就用，不好用就换其他的。作者本人既然认为你提出的BUG不属于应该被修复的BUG，那么：1、你要么换其他的用，2、要么就下载代码来自己改。
嫌它不好用又偏要用，这是自虐吗？不喜欢就换其他你喜欢的用，没必要在这里吵

**Comment by DigitalPlatform** [comment]
@cloudwu 

我上面说得很清楚了，这个软件的作者自己去提比较合适。我就不掠美了。我只负责给这个软件的作者提一点力所能及的意见。

> 开源的意义在于让用户理解软件的工作机理，让用户有能力能自己解决问题。在自己解决不了的前提下，帮助作者解决问题。开源可以让用户给作者提供更多的细节。

您这个调门有点高啊。开源项目的用户有很多，参与者也有很多，您说的这种只是其中一小部分而已。就算是项目直接参与者，也有写文档和测试的角色，这些人也有可能看不懂源代码，不甚了解软件的内部机理。更别说广大用户了。

如果我以后有空，或者有相关需求能看看这个项目的源代码，我可以尝试定位一下问题，但我现在没有空。您上面说的一点很好：提 issue 的人有可能变成项目参与者。正因为这一点，大家多客气一点，互相留个台阶更好。谁知道对方是什么实际水平的呢，您说是不是。

**Comment by DigitalPlatform** [comment]
@conanliuhuan 

首先是我在提这个 issue，不是您在提。发现 bug 是好事是不是？您有功夫也发现一个 bug，要不别在这儿瞎 BB。

> 嫌它不好用又偏要用，这是自虐吗？不喜欢就换其他你喜欢的用，没必要在这里吵

我没有嫌什么，是您在嫌。什么换浏览器也是您的“观点”。按照您这个逻辑，您怎么还在用 $M 的 GitHub？您这不是自虐么？

**Comment by DigitalPlatform** [comment]
补充一句，我提交 issue 时用的就是 Edge 浏览器。我觉得没有任何问题。

**Comment by jingsam** [comment]
> 如果我以后有空，或者有相关需求能看看这个项目的源代码，我可以尝试定位一下问题，但我现在没有空。

你很忙，作者也很忙，大家的时间都很宝贵，要不你付费请作者或者其他开发者帮你解决一下？

记住，开源≠免费，作者没有义务帮你解决问题。或许，你的态度好一点，不那么咄咄逼人，作者可能心情好一点，顺手帮你解决了。

做开源不易，请多给予作者支持和理解。

**Comment by DigitalPlatform** [comment]
@cloudwu 

> 不在于是不是必须具备能力才能用，而是你有没有能力定位于bug . 有能力定位就没资格指责维护者， pr 才是正途。没时间这个理由不觉得可笑吗？你咋有时间发牢骚呢？反馈问题如果是用户的义务，那么向微软反馈更是你的义务：显然作者并不是edge 的用户，为什么要帮你向 edge 反馈。

您别回避这个问题：您说 Edge 不遵守标准协议，这个需要您拿出证据。最好别告诉我您是靠猜的。

“显然作者并不是edge 的用户，为什么要帮你向 edge 反馈”，给微软反馈这个点子是您提出来的吧？您可真会自己给自己加戏。

“没时间这个理由不觉得可笑吗？你咋有时间发牢骚呢？”，我回复您这点文字的时间，足够定位这个 bug? 心疼一下这个软件的作者。

**Comment by DigitalPlatform** [comment]
@jingsam 

> 你很忙，作者也很忙，大家的时间都很宝贵，要不你付费请作者或者其他开发者帮你解决一下？

我好长一段没有搭理这个 issue 了，今天要不是上面两个发牢骚的，我没必要回复。您注意看看这几个 comment 里面的时间。

这个 bug 已经不需要解决了，我想了其他办法。

做开源是不容易，我本人也是做开源的，我有这方面的体会。issue 里面不解决问题，扯一些乱七八糟的什么微软浏览器不行啊之类的，一般都是没有价值的参与者。

**Comment by cloudwu** [comment]
我没有说一定是 Edge 在这个问题上不符合标准，只是说根据反馈，特定版本有问题，所以很有可能是因为某个位置不符合标准。我就是猜的。但是，问题是你碰到的，你自承有能力，那么你就有责任去确定这点。

你是 Edge 的用户，你在用 Edge 的时候发现了问题，当然应该是由你向 Edge 反馈问题。这不是天经地义的么？我不明白你的脑回路为啥没能理解这点。你不会觉得 Edge 不可能存在 bug 或是认为必须先确定 bug 存在于浏览器，才能够反馈问题吧？如果按这个逻辑，你在未确定 bug 到底是存在于这个项目还是 Edge 项目之前，是不是也不应该在这个项目提 issue 呢？

**Comment by DigitalPlatform** [comment]
@cloudwu 

您如果愿意讨论这些问题，我乐于奉陪，但不是说我时间多到可以浪费。请谅解。

关于 Edge 是否符合标准，需要调查一下，也就是说看看代码，到底是什么地方出了问题，浏览器行为是否违反了 RFC 标准，哪一条标准。焦点在于解决问题，而不是瞎扯一堆什么 Edge 不是好浏览器之类的，那是浪费时间。

在到这个“找到确凿证据的”程度之前，可以含蓄一点说“出现了兼容性问题”。无论是哪方面的问题，即便是浏览器出现了不符合标准的情况，那也去故意兼容的，太常见了，汗牛充栋，这个没有必要争论什么政治正确，实用为上。这是我的看法。

"你是 Edge 的用户，你在用 Edge 的时候发现了问题，当然应该是由你向 Edge 反馈问题"，您的脑回路够奇特的，您确认么？有这个能力确认么？别翻来覆去给我说是您猜的。

**Comment by jingsam** [comment]
@cloudwu 云风大哥，我觉得你不必要浪费时间跟@DigitalPlatform 争了，你好歹是一个大公司的CEO，跟他争即损失金钱，又影响心情。
我觉得当前的讨论已经不是针对对问题本身了，而是关乎于更深层次的问题，包括对开源的理解、提问的技巧和礼仪。做开源也有好几年了，经常碰到所谓的`伸手党`，一遇到问题就来兴师问罪，改慢了还不行，例如`项目要上线哪，赶快给老子改好`，一副上辈子欠他的模样。据我的观察，主要有两类人是这样的，一类是在生活中性格就是这样的，不知道什么叫感恩，觉得世界都欠他的，这种人以后可能需要经过人生挫折才能明白人生道理。另外一种是刚入门的新手，为什么新手会这样呢？因为新手基础不牢，只能使用现有的库做一些应用，底层出问题了他也不知道怎么改。并且，新手从思维上，会认为已有的库或软件不会出问题，但是当库的行为不符合他的预期时候，他会觉得他被所信任的东西背叛了，这会导致他在issue上说一些很不尊重人的话。这种人，可能需要经过多年的开发历练，才会明白没有什么软件是百分之百可靠的，遇到问题才能心平气和地解决。

**Comment by DigitalPlatform** [comment]
> 但是，问题是你碰到的，你自承有能力，那么你就有责任去确定这点

**Comment by jingsam** [comment]
@DigitalPlatform 你再仔细品味下我在说谁？

**Comment by DigitalPlatform** [comment]
@jingsam 

> 你再仔细品味下我在说谁？

你写出来的文字，是给别人理解的。开源的参与者和角色很多，其中说话不合适了，一杆子打翻一船人的，也不少见。

嘴下多积德，提醒您一下。无论是大公司的 CEO，还是小开源软件作者，还是一般用户，都是平等的。态度上不要先入为主。有精力先搞好产品和技术，有余力再多看看各种书，做一点人文的积累。

要承认很多事情您未必了解，多保持一点敬畏之心。

**Comment by raindylong** [comment]
@DigitalPlatform ，真心希望你能仔细体味一下你在这个issue里面发的前几个回复，我确实只看到了你对作者的蔑视和无理，真心的寻求帮助不会是用这些口吻来行文的。

共勉。

**Comment by DigitalPlatform** [comment]
@raindylong 

我回复您是出于基本的礼貌。先声明一下，免得有啥误会。

> 真心希望你能仔细体味一下你在这个issue里面发的前几个回复，我确实只看到了你对作者的蔑视和无理，真心的寻求帮助不会是用这些口吻来行文的

我觉得这里面主要是我们对“平等”这个概念理解不同。很多人习惯两种状态：不是用户求着作者；就是用户压着作者。其实还有第三种状态，就是不卑不亢。有可能因为您不熟悉这种平等的状态，会误认为是其他两种状态。

比如这个“寻求帮助”。我确实不是来寻求帮助的，因为这个 bug 首先应该是作者更在乎，不是用户在乎。一般说这种开源的系统，由于维护者这样那样的难处，问题的解决不一定那么利索。如果用户很在乎，就不会用这种开源的系统，能理解么？上面也有人提到付费，部分印证了我的这种感觉。

不是别人不付费，而是万一付费以后作者是否能承担一个商品化软件的责任。当然开源不一定不可以商品化，我是说很多开源的同时也是免费的，没有太多机会体验商品化的感觉。

对于我来说，我找另外一个文档管理系统就可以了，或者我以后有精力了自己写一个。我在这里提出的一些建议，不是“逼着这个作者实现”，而是同时也可以理解为我对这类软件的看法(将来有机会我可以按照自己的喜好来设计产品)，是一种中立的立场。我上面提到过几次，我也是一个软件开发者。之所以分享给作者，或者其他朋友，我是善意的，没有蔑视和无礼。我这里解释一下。

如果以后我写这种系统，我也希望有人能把想法倾囊相授，我不会嫌弃人家。当然这只是随便说说一种可能性而已，换位思考的习惯。

这里也赞扬本软件作者：这个系统很朴实，功能很简洁，发展势头是很好的。如果开发团队能纳入更多有力量的成员则更好。团队文化建设也很重要，有些东西是互相传染的。

另外，我打字速度快，不费什么时间精力。我是尽力回复别人的 at。我再前调一下，今天这些讨论不是我发起的。

**Comment by asthman666** [comment]
@DigitalPlatform bug也提了，你自己也找到解决问题的办法了，结局是完美的

**Comment by cupen** [comment]
嘿，我倒有丁点儿理解这位兄台的一点心理。有时我也会烦手头开源软件的瑕疵 ，而工作的进度压力又不容许我花太多时间去做“间接工作”，这时会莫名的把责任归于作者。但老实说，作者仅仅只是分享了劳动成果给我而已，并没有义务为我做什么，他唯一需要负责的仅仅是他自己认为值得付出劳动的需求。

很多开源项目说不做就不做，说废弃就废弃，原因就一个 —— 作者不想做了，而这也是天经地义的，没人能指责作者什么。有需要的人 or 公司（受益方）一般会去 fork 一份自己维护，非常健康的开源哲学，即——每个人都只为自己认为有价值的需求负责。

P.S. 这位兄台之前的言语透露出小情绪了，有点傲慢哦。后边一系列的掐架都因这股傲慢而起。
P.S. 抱歉多嘴，周末闲了点……

**Comment by DigitalPlatform** [comment]
@cupen 

不是“莫名把责任归于作者”，而是责任实实在在就是作者的。

上面针对我的情绪，讨论得比较充分了。我们来讨论一下这个文档管理系统 showdoc 的角度。他基本上定位到他所用的另一个开源的所见即所得 Web 编辑器，那么剩下的可能就有，需要给那个项目提 issue，要那个作者来检查和修改这个项目所用到的一个组件。

之所以说开源是一个生态，就是很多很多开源项目是依赖其他开源项目的，一荣俱荣一损俱损。所以探讨这个相互依赖关系也应该是本次讨论的题中之义。

那么 showdoc 作者面对这个可能性，展现出来是怎么个“情绪”呢？明显有畏难情绪。楼上有文字可以看看，这个作者觉得那个组件的 issue 里面不怎么解决问题。当然这种“生态”情况我们也是常见的，想必大家没有异议。按照你们比较统一的某种观点，这个 showdoc 的作者就应该自己改那个组件代码，不应该要求那个组件作者？这是“非常健康的开源哲学，即——每个人都只为自己认为有价值的需求负责”，showdoc 的作者也不要因此抱怨什么，是吧。

是的，这个 showdoc 的作者显得没有太抱怨那个组件。但奇怪得是，半推半就也好，跟着这里几个参与 issue 的用户观点差不多也好，令人惊奇地找到另外一个角度“Edge 不是常用浏览器，甚至不是正规浏览器”，扯到了另外一种“开源文化”，我用“恶习”来命名之恐怕也不为过(有兴趣可以展开另外一个大话题)，这样对自己的自责就减少了么，也不失为一个好的自我安慰办法。弄不好也许 showdoc 的作者以前有给别人提 issue 然后被嘲讽的经历，造成了这种畏难情绪？

这是不是另外一种更大的“傲慢”呢？也可以说“一系列的掐架都因这股傲慢而起”，不信我们从头看看这个 issue。其实这是一种扭曲的意识或者说“文化”，带来的结果很明显，对开源的产品非常不利。说一千道一万，产品行不行，一种所谓好的生态对产品开发的作用是什么。值得反思反思。

这里很多话儿，将心比心，所有有求于别人的“作者”，当自己是另外一个组件的“用户”的时候，也用手指着自己好好想想，看看能不能讲通，认同。

showdoc 作者性格看来是很温和，在问答交流方面也非常尽心，有问必答，我觉得至少这一点是很多作者做不到的，值得赞扬和鼓励。我上面探讨的问题，不是单纯责备他的意思，而是试图换位思考。由于他说得多，介绍的情况多，所以我才能有感而发，我本意不想去惩罚他这种好意(哪怕是连锁反应引起)。如果我说得有什么不合适的，在这里提前抱歉了。

**Comment by cloudwu** [comment]
那么作为一个 edge 的用户，在遇到只存在edge 的问题，不去向开发团队微软反应，反而要求非 edge 用户主动替你担责又是怎样的心态呢？

**Comment by DigitalPlatform** [comment]
@cloudwu 

> 那么作为一个 edge 的用户，在遇到只存在edge 的问题，不去向开发团队微软反应，反而要求非 edge 用户主动替你担责又是怎样的心态呢？

您这车轱辘话又是什么心态？不如说点有新意话题吧。

**Comment by cloudwu** [comment]
我只是反复强调你作为一个用户，不肯承担你能力范围内的责任的心态。而你从未意识到这是你自己的问题。

**Comment by DigitalPlatform** [comment]
@cloudwu 

您可真有耐心。

我作为 Edge 浏览器用户，而且是一个程序员，理论上确实有可能我参与进来协助修改这个软件。貌似这个 showdoc 是 php 语言的，我不会这个语言，因此搭建调试环境有较大困难。而且我现在时间不够。

到底是谁的责任和问题，我们各自保留意见吧。多做一些力所能及的事情，少争论“主义”也许是可取的。

**Comment by star7th** [comment]
@DigitalPlatform  showdoc后端是使用php，但本问题不出在后端。是纯前端编辑器的问题。你既然使用了开源showdoc，那就肯定已经安装好了php环境。所以，不需要再额外搭建调试环境。在这种情况下，只要有浏览器和文本编辑器，就可以随时调试。
有空的时候，自己看下吧。

**Comment by star7th** [comment]
@DigitalPlatform 不用假设了。我在上面已经说过了是编辑器问题。这我已验证。你只需要调试js。

**Comment by DigitalPlatform** [comment]
@star7th 

您是怎么确定是编辑器问题的，不妨在这里说一下。

**Comment by cupen** [comment]
> 按照你们比较统一的某种观点，这个 showdoc 的作者就应该自己改那个组件代码，不应该要求那个组件作者？这是“非常健康的开源哲学，即——每个人都只为自己认为有价值的需求负责”，showdoc 的作者也不要因此抱怨什么，是吧。

不，别误会我的意思。你举例的 case 里， showdoc 作者当然优先把问题反馈给原作者，但如果原作者未按他的想法处理的话，也不能说原作者不对 or 不尽责，对吧？ 这里一切正常！唯一不正常的仅仅是我上面说的： `后边一系列的掐架都因这股傲慢而起。`

@DigitalPlatform  哈哈，您就费点心帮忙定位一下这个问题吧。即便掐赢了几个人，你也说不动作者，除非拿把杀猪刀架住他脖子。理论上任何一个环节都有可能出问题，包括 Edge 本身。既然作者不干，那不妨定位一下问题再同步给作者吧，我相信任何一个作者都会接受 “问题在此，你改改”  而不是 “问题在哪，你找找” 的 issue。

**Comment by DigitalPlatform** [comment]
@cupen 

我是说这种傲慢的成分比较复杂。

这个讨论没有输赢问题。我也没有任何功利的目的。甚至解决这个 bug 也不是我的目标。特别是开源的环境，您能要求别人什么呢？我觉得这个过程本身就有意义，不一定是要达到什么具体的目的。可能这恰恰容易被理解为一种“傲慢”吧。我真不是太在乎一些“传统”的观念和评价。

至于调试甚至解决问题，这个需要我有这个能力才行，也不能因为好面子就逞强。我后面如果有时候试试吧。希望这个“如果”不会被误解。其实我也提到过自己想开发一个文档系统，原因很简单，可能这样自己用着比较爽，满足自己的需求比较容易。不客气说现在这个 showdoc 还没有让我觉得值得托付太多希望。当然，这样说实话恐怕又要得罪人了。

**Comment by star7th** [comment]
其实我之前就解决此问题了。只是不更新上来。本来想看看这个傲慢的伸手党有没有能力自己解决问题。我都明说了问题代码从前端编辑器定位，他都没能力再深入定位下。真让人失望。
edge这个版本的内置对象URLSearchParams对参数进行转义时候有bug。绕过这个bug的方法是，自己先提前进行encodeURIComponent后再传参进它的内置对象。然后再在接受参数的地方转回来。
我不想为这点小事重新打包一遍前端代码或者发布一个版本。等以后发大版本时再统一更新。你自己在你自己的版本上改吧。
话都说到这个点上了，如果你还想做个伸手党，还不愿意花时间去解决问题，那就没办法了

**Comment by DigitalPlatform** [comment]
@star7th 

您还有功夫考虑这些啊，不觉得自己小鸡肚肠么。

我不会给你修改的，我也不会为我自己修改你这个软件，因为我不用这个软件了。我会开发一个自己的文档管理系统。

你改了 bug 我也不会用了。感谢您的这些作为，也是对我自己软件开发的一种促进。
