### ISSUE TITLE
【建议】首页 登录 / 注册 分开

### ISSUE THREAD

**Issue by han8gui** [star7th/showdoc#276]
注册完账号之后，点击“登录 / 注册”，再点击登录才可以登录。
建议点登录 => 登录, 点击注册 => 注册。

![_15270658739272](https://user-images.githubusercontent.com/12422762/40414428-ba2dde3c-5eaa-11e8-85e1-47371f41a87d.png)

**Comment by han8gui** [comment]
注册本身是比较低频的行为

**Comment by star7th** [comment]
现在面临的主要是新用户，所以注册优先没啥问题。而且登录后会记住登录一段时间，对用户来说无太多感知

**Comment by han8gui** [comment]
@star7th 
明白了，我自己这边需要这样，我这边单独处理了。
