### ISSUE TITLE
centos7 docker构建错误

### ISSUE THREAD

**Issue by fengzhibo294** [star7th/showdoc#281]
[root@localhost showdoc]# docker build -t showdoc ./

Sending build context to Docker daemon 25.33 MB
Step 1/5 : FROM php:5.6-apache
 ---> cb4e3365d949
Step 2/5 : COPY ./ /var/www/html/
 ---> Using cache
 ---> 56260d7a06e0
Step 3/5 : RUN sed -i  's#http[:]//deb[^/ ]\+#http://ftp.cn.debian.org#g' /etc/apt/sources.list  &&             apt-get update && apt-get install -y         libfreetype6-dev         libjpeg62-turbo-dev         libmcrypt-dev         libpng12-dev    && docker-php-ext-install -j$(nproc) gd mcrypt
 ---> Running in 784042957aab

Get:1 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Ign:2 http://mirrors.ustc.edu.cn/debian stretch InRelease
Get:3 http://mirrors.ustc.edu.cn/debian stretch-updates InRelease [91.0 kB]
Get:4 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [440 kB]
Get:5 http://mirrors.ustc.edu.cn/debian stretch Release [118 kB]
Get:6 http://mirrors.ustc.edu.cn/debian stretch-updates/main amd64 Packages [12.1 kB]
Get:7 http://mirrors.ustc.edu.cn/debian stretch Release.gpg [2434 B]
Get:8 http://mirrors.ustc.edu.cn/debian stretch/main amd64 Packages [9530 kB]
Fetched 10.3 MB in 7s (1375 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Package 'libpng12-dev' has no installation candidate
Package libpng12-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

The command '/bin/sh -c sed -i  's#http[:]//deb[^/ ]\+#http://ftp.cn.debian.org#g' /etc/apt/sources.list  &&            apt-get update && apt-get install -y         libfreetype6-dev         libjpeg62-turbo-dev         libmcrypt-dev         libpng12-dev    && docker-php-ext-install -j$(nproc) gd mcrypt' returned a non-zero code: 100

**Comment by star7th** [comment]
你的源问题吧。很多人安装过都没问题

**Comment by wdd668** [comment]
阿里云centos 6.8 会报这个错 没有apt-get命令

**Comment by star7th** [comment]
环境有点特殊，我没那个机器，不好测试。
但就长期的反馈来看，一般人是可以安装的

**Comment by clyquan** [comment]
打开Dockerfile，修改libpng12-dev为libpng-dev

**Comment by zhuanli555** [comment]
@clyquan 你真是帮了我大忙了
