### ISSUE TITLE
Microsoft Edge 42.17134.1.0，showdoc编辑器丢失回车符

### ISSUE THREAD

**Issue by renyh** [star7th/showdoc#282]
Windows 10升级之后，Microsoft Edge 42.17134.1.0，showdoc编辑器丢失回车符
![image](https://user-images.githubusercontent.com/13568719/40570625-3a522bfc-60bf-11e8-8b6f-0696b484568e.png)

**Comment by star7th** [comment]
https://github.com/star7th/showdoc/issues/271
