### ISSUE TITLE
关于删除页面恢复的问题

### ISSUE THREAD

**Issue by qishibo** [star7th/showdoc#283]
手误，删除了页面，看了sql文件，page表中已经没数据了【是真删除么】，但是页面的编辑历史表中有数据，page_content字段没解出来，不知道啥编码，所以不知道这个页面还能恢复不

**Comment by star7th** [comment]
真删除了

**Comment by star7th** [comment]
历史编辑数据也会一并删除

**Comment by qishibo** [comment]
Is's a sad story......

**Comment by star7th** [comment]
后面可以考虑做回收站功能吧

**Comment by im-zhangxi** [comment]
> 后面可以考虑做回收站功能吧

想问下 回收站 做了吗?  我误删除了一个项目?>

**Comment by star7th** [comment]
项目是很少有误删除的说法的。因为它需要输入密码强校验。所以回收站功能并不紧迫。而且一个回收站，不能只是项目回收站。还要回收删除的目录和页面。回收的页面放在哪里，如果上级目录也删除了怎么办。等等。各个机制神烦，我还没想好，一直懒得去想。可能需要找时间专门构思。

Zach <notifications@github.com> 于2019年11月1日周五 下午2:44写道：

**Comment by im-zhangxi** [comment]
@star7th 
那想问下 数据 做定时备份了吗?  删除  有办法 恢复吗?

**Comment by star7th** [comment]
自己写个定时任务把安装目录复制就是备份。

Zach <notifications@github.com> 于2019年11月1日周五 下午3:04写道：
