### ISSUE TITLE
sqlite数据库迁移问题

### ISSUE THREAD

**Issue by Joeyechang** [star7th/showdoc#284]
如果在一台服务器（old one）部署安装并写入了数据，这时想迁移到另一台服务器 (new one)，在新服务器部署安装后，将 old one 上面的 showdoc.db.php 直接覆盖 new one 上面对应文件，这时登录注册不可用，也没有报错提示，请问这个问题怎么解决？或者说数据库文件怎么迁移？

**Comment by star7th** [comment]
直接复制过去理论上是可以的。
你需要关注新服务器上的php环境和权限是否跟原来服务器保持一致。
