### ISSUE TITLE
可否有导入json的功能

### ISSUE THREAD

**Issue by Varorbc** [star7th/showdoc#29]
导入json后就会生成一个返回参数的表格

**Comment by star7th** [comment]
没有呢。建议只对必要字段进行解释即可，返回参数表格不一定写上所有返回参数

**Comment by Varorbc** [comment]
@star7th 能不能实现像http://www.easyapi.com/上导入json,就可以自动生成返回参数表格的功能

**Comment by star7th** [comment]
理论上是可以写的，根据编辑器的文档https://github.com/pandao/editor.md 写个编辑器插件。但个人觉得这是个很小众的需求，所以不打算花时间去做。如果你懂得写代码的话可以试试。其实我建议你直接使用插入表格功能就好，然后填上字段和说明。并不会麻烦很多

**Comment by Varorbc** [comment]
@star7th 我今天早了很多api管理的系统,发现都有这个功能,找到目前发现你的是最好的,就是缺少了导入json的功能

**Comment by star7th** [comment]
个人感觉，Showdoc本身插入api模板后，只需要在“返回参数说明”那里依样画葫芦一行行复制然后填写说明就好了。导入json只是导入字段名字而已，写文字描述的时候依然需要动手写。复杂度差不多的。

**Comment by Varorbc** [comment]
@star7th 相对一个个去复制字段名,填类型,填备注,会省很多事情,导入后只要去改下备注就可以了.

**Comment by star7th** [comment]
我大概想到了一种方式能解决你说的这种需求。类似rap那里，做个API接口表单生成按钮，点击后弹出表单。填写url、请求参数、返回格式等，提交后就自动生成markdown格式文本。生成过程中也根据添加的返回json格式生成返回参数列表。
完整功能需求流程应该就是这样子吧。
实现这个功能需求写编辑器插件，稍微繁琐点，我往后有时间再去研究下如何写编辑器插件吧

**Comment by Varorbc** [comment]
@star7th 对,就是这么一个流程,你上面的2个按钮不是已经实现插入到编辑器里的功能了吗?

**Comment by star7th** [comment]
现有的按钮直接插入的是文本。插入文本后，你还需要更改的；我上面说的是一个表单生成器，让用户填写个表单，然后自动生成文本再插入编辑器

**Comment by Varorbc** [comment]
恩,对,就是这样,简单点直接把json字符串复制进去就可以了

**Comment by star7th** [comment]
想了想，要根据json来生成参数列表还是会遇到格式的问题。因为大家返回格式不一样。有人是json，有人是xml。在json的情况下，有人喜欢把真正的业务数据封装早data字段，有人封装在resule字段。还有，某些接口，例如获取微博列表，是返回一大堆非常长的重复字段返回数据，生成字段列表的话需要去重，并且大部分字段其实是不需要重复解析了的（例如在首页便声明了通用字段释义）。综上所述，你说的这个功能，是有用，但不适合所有人的所有情况，故要做成一个通用功能的话还需要再考虑。
此外，我增加了一个接口复制功能。查看某个接口时，点击复制按钮，便可以新建接口并复制原接口的内容在编辑器中。这样，对于类似接口，就不用改动那么多数据了。一定程度上缓解了每个接口都需要手动改写同样的参数格式列表的问题

**Comment by Varorbc** [comment]
你说的json,xml的为问题,应该json的会更多的吧,字段的问题是不管有没有封装都解析好了,我已经把你的下载过来,自己实现了这个功能.

**Comment by laohuangsk8** [comment]
这个问题已经解决 其实过程很简单
思路就是 在【插入数据字典模板】右侧（或者自己喜欢的地方）加一个按钮
我写按钮叫【插入JSON】 点击后 弹出div层 直接复制借用【插入API接口模板】的div

然后直接粘贴进 目标JSON 字符串 点击确认 插入 编辑后的根据JSON 拼接成字典模板 也就是 表格

点击确认 触发的js 过程就是 获取用户的输入 转JSON 然后 递归获取JSON对象的元素 拼接到 定义好的一个全局js变量上 最后 插入编辑区 就ok 此功能本人已与楼上Varorbc 测试ok

**Comment by star7th** [comment]
@laohuangsk8 的代码挺好的，我已经合并了，并对文字提示和生成的格式做了些很小的改动。新功能命名为“JSON转参数表格”，在编辑页面会看到此按钮。
本人原计划做API表单生成器，即用填表单的方式生成api文本。表单生成器到时会把“JSON转参数表格“”功能合并进来，在填写返回结果的时候会自动生成返回参数列表。API表单生成器已经完成了一半，今早看到@laohuangsk8 有pull请求我就先合并。表单生成器我再思考下有没有必要做

**Comment by laohuangsk8** [comment]
这个系统 简洁明了 很实用
