### ISSUE TITLE
公有云平台考虑增加一下数据导入和导出的功能吧?

### ISSUE THREAD

**Issue by 5UFKEFU** [star7th/showdoc#290]
为了数据安全吧,否则辛苦写的文章没有了,非常可怕.

**Comment by star7th** [comment]
可以导出为word。官方会有自身的数据库备份机制。
如果有私有化需求或者不相信在线服务的，建议一开始部署开源版。


Jeff Cheng <notifications@github.com>于2018年6月1日 周五下午10:15写道：
