### ISSUE TITLE
一直登录不上，windows正常，mac登录见鬼

### ISSUE THREAD

**Issue by WGinit** [star7th/showdoc#292]
登录成功显示一个空白弹窗，
之后任何操作都是空白弹窗，，
问该如何解决，
之前都能正常登录，最近几天见鬼了

**Comment by star7th** [comment]
看一下网络请求返回什么，或者有没有可能是浏览器插件导致的

**Comment by WGinit** [comment]
请求返回正常的哦，文档列表都有返回，插件什么的应该不会，我换了3个浏览器都是一样的，都会弹出空白提示，很奇怪

**Comment by WGinit** [comment]
已查明，是我本地WiFi可能引起冲突了，连接其他网络可以正常打开，但这个空白提示就让我很懵逼
