### ISSUE TITLE
充值未到账

### ISSUE THREAD

**Issue by luffyanson** [star7th/showdoc#293]
连续冲了两次15元，支付宝支付，均未到账。有联系方式或者解决方法吗？

**Comment by star7th** [comment]
showdoc官方不收费。谁收你费用的你就找谁。

luffyanson <notifications@github.com>于2018年6月8日 周五下午10:00写道：

**Comment by luffyanson** [comment]
行吧...因为是扫码支付所以不太可能找回了，乘云计划网页也没有联系方式啥的。




发自网易邮箱大师
在2018年06月08日 22:02，star7th 写道：
showdoc官方不收费。谁收你费用的你就找谁。

luffyanson <notifications@github.com>于2018年6月8日 周五下午10:00写道：
