### ISSUE TITLE
Fail to write config file

### ISSUE THREAD

**Issue by Cyrus414** [star7th/showdoc#294]
安装时显示Fail to write config file。检查过了所有文件都有读写权限。包括Application/Common/Conf/config.php

**Comment by star7th** [comment]
为何不试试整个文件夹递归给777权限

**Comment by Cyrus414** [comment]
我就是整个文件夹递归给777权限的，还是有这个问题

**Comment by star7th** [comment]
截图下提示信息

**Comment by Cyrus414** [comment]
问题像是出在Application/Common/Conf/config.php这个文件上。我在执行install前后检查了这个文件，发现执行之后文件的修改时间确实变了，但是文件大小始终是0 byte。

**Comment by star7th** [comment]
如果是共性问题的话肯定会很多反馈。但目前我只听到你反馈过这种情况，所以我只能猜测跟你的环境有关

**Comment by Cyrus414** [comment]
确实是我的环境问题。换一个环境就好了，原本的环境的问题可能是磁盘空间耗尽导致的。多谢！
