### ISSUE TITLE
建议增加管理员修改密码功能和文章隐藏功能

### ISSUE THREAD

**Issue by yeriwei** [star7th/showdoc#299]
1、修改用户密码太麻烦了，每次都得去服务器上找数据库。
2、文章隐藏功能或草稿功能，只有创建者才能编辑 ，这样可以先写，再实现。
3、建立项目增加成员的时候，可以浏览列出所有的用户列表。填用户名添加太麻烦了，还得找用户名。

**Comment by star7th** [comment]
1、以后做个简单的管理后台吧
2、太小众，不考虑这个需求
3、后面更新时候考虑

**Comment by star7th** [comment]
已发布带有管理后台的showdoc版本
