### ISSUE TITLE
您好  我本地 你能运行三个界面  ，其他报错

### ISSUE THREAD

**Issue by zhangjinling** [star7th/showdoc#3]
我本地只能 看到 登陆  注册   首页   点其他的链接报错  也不能注册登陆。是不是对其他的环境配置什么的有问题？
数据库配置已经修改。
我配置了vhost。
错误信息:
页面错误！请稍后再试～

这个项目非常好  ！谢谢。。。

**Comment by star7th** [comment]
可能是环境问题。你看看Application\Runtime\Logs\Home目录的错误日志，顺着错误日志应该会有线索

**Comment by star7th** [comment]
如果连日志都没看到则注意给Runtime目录可写权限，顺便清空一下Runtime目录再试

**Comment by zhangjinling** [comment]
配置文件：
\Application\Common\Conf

<?php
return array(
	//'配置项'=>'配置值'
	'DB_TYPE'   => 'mysql', // 数据库类型
	'DB_HOST'   => '127.0.0.1',
	'DB_NAME'   => 'shoswdoc', 
	'DB_USER'   => 'root', 
	'DB_PWD'    => 'root',
	'DB_PORT'   => 3306, // 端口
	'DB_PREFIX' => '', // 数据库表前缀
	'DB_CHARSET'=> 'utf8', // 字符集
	'DB_DEBUG'  =>  TRUE, // 数据库调试模式 开启后可以记录SQL日志
	"URL_HTML_SUFFIX" => '',//url伪静态后缀
	'URL_ROUTER_ON'   => true, 
	'URL_ROUTE_RULES'=>array(
	    ':id\d'               => 'Home/Item/Show?item_id=:1',
	),
);



错误信息：
[ 2015-12-07T09:23:34+08:00 ] 127.0.0.1 /index.php/home/user/login
ERR: SQLSTATE[HY000] [1045] Access denied for user 'showdoc'@'localhost' (using password: YES)


我已经把用户名改了，怎么还是这个？还有其他配置的地方吗？
这个应该是密码不对！
谢谢。。。

**Comment by star7th** [comment]
清空一下Runtime目录再试。
另外数据库名是showdoc，不是shoswdoc

**Comment by zhangjinling** [comment]
一直也没敢删Runtiime文件夹！就是那个文件夹的问题，我觉得下次你提交的时候就别提交那个文件夹里的东西了，项目非常好，谢谢，辛苦了。

**Comment by star7th** [comment]
我没有提交那个文件夹的东西的。可能是你下载下来后，尚未改掉配置就运行了，运行后就生成了Runtiime缓存。所以当你改掉配置，你则需求把之前生成的缓存清理掉

**Comment by star7th** [comment]
新增了支持三级目录的功能；升级安装请参考部署手册中“升级安装”部分。http://blog.star7th.com/2016/05/2007.html
此外我新建了一个ShowDoc使用交流qq群（群号：564671853），欢迎探讨问题
