### ISSUE TITLE
建议添加编辑模板的功能

### ISSUE THREAD

**Issue by JaryLee** [star7th/showdoc#300]
模板有问题的时候，还得找到之前的模板，改完之后还得删除旧的模板，然后再添加一次。最好能出个修改模板的功能。

**Comment by star7th** [comment]
没必要找到之前的模板。新建个页面把模板插入后修改就好了。这是低频需求，所以就没必要专门编辑了

**Comment by JaryLee** [comment]
但是保存之后之前的模板还是存在的，以后可以加一个菜单来管理模板。

**Comment by star7th** [comment]
不为低频需求增加额外的功能

**Comment by star7th** [comment]
会让软件以后越来越复杂
