### ISSUE TITLE
自己搭的showdoc除了chrome其他浏览器一直报strict 模式下不允许一个属性有多个定义

### ISSUE THREAD

**Issue by yz1024** [star7th/showdoc#301]
自己搭的showdoc除了chrome其他浏览器一直报strict 模式下不允许一个属性有多个定义，不方便大家查阅，求帮忙解决下。

**Comment by star7th** [comment]
火狐浏览器美誉哦这个提示吧？
提示的是什么浏览器

yz1024 <notifications@github.com> 于2018年7月5日周四 上午9:38写道：

**Comment by yz1024** [comment]
我试的ie ，qq 和360浏览器，不行

**Comment by star7th** [comment]
qq 和360浏览器 本质是使用IE内核。换其他吧

yz1024 <notifications@github.com> 于2018年7月5日周四 上午9:41写道：

**Comment by yz1024** [comment]
但是我看你们官方的在线文档是能在这些浏览器上访问的呢，我能私聊你，把地址发你看下吗

**Comment by star7th** [comment]
在这里发地址来

yz1024 <notifications@github.com> 于2018年7月5日周四 上午9:44写道：

**Comment by yz1024** [comment]
我们公司的文档，不能发在公共的地方

**Comment by yz1024** [comment]
你是showdoc2群里的第七星尘吗？

**Comment by star7th** [comment]
为了测试这个问题还专门下载了下360浏览器。结果发现没问题。这里用win10系统来做测试。
浏览器兼容问题不管了。showdoc只负责兼容谷歌和火狐，其他浏览器的兼容性的话，能兼容就兼容，不能兼容就算了。毕竟本身开发者群体绝大部分用高级浏览器

yz1024 <notifications@github.com> 于2018年7月5日周四 上午9:48写道：

**Comment by yz1024** [comment]
我试了你们在线的是没这个问题的，我们搭的就会报这个错，而这个错是因为js不允许一个属性有多个定义。我们大概是三周前从git上拉的代码。是不是你们已经修复过这个问题，而我们拉取的代码不是最新的。

**Comment by star7th** [comment]
刚刚改了下master版本，指定360浏览器使用极速内核渲染。
你更新下吧。另外官方并不考虑这些浏览器的兼容问题，下次有问题不管了。

**Comment by yz1024** [comment]
好的，谢谢
