### ISSUE TITLE
页面内锚点跳转的问题

### ISSUE THREAD

**Issue by xjw1990** [star7th/showdoc#302]
http://doc.xxxx.com/web/#/4?page_id=5新版showdoc页面链接是这样的，编辑的markdown页面无法使用锚点实现页内跳转，锚点链接被解析成http://doc.xxxx.com/web/#/mymaodian，希望官方能够解决下这个问题

**Comment by star7th** [comment]
你试试整这个页面 https://www.showdoc.cc/web/#/page/14853979

**Comment by zheking1** [comment]
@star7th 这个页面的锚点链接的跳转连接被改成跳转到黄色网站了。建议你们修复一下

**Comment by star7th** [comment]
> [@star7th](https://github.com/star7th) 这个页面的锚点链接的跳转连接被改成跳转到黄色网站了。建议你们修复一下

什么意思，哪个链接
