### ISSUE TITLE
可能是一个小bug

### ISSUE THREAD

**Issue by JaryLee** [star7th/showdoc#303]
当我什么都不写点击保存的时候，再进去就不能编辑了。
![image](https://user-images.githubusercontent.com/26730886/42359750-8b995ff4-8116-11e8-9296-6d5b2f50012e.png)

![image](https://user-images.githubusercontent.com/26730886/42359763-b0dec8ee-8116-11e8-8342-f88a92d37540.png)

**Comment by star7th** [comment]
https://www.showdoc.cc 没发现这个问题。
此外这个问题也无关紧要。没有谁会这样操作。真这样操作了就删除这个页面吧

JaryLee <notifications@github.com> 于2018年7月6日周五 下午12:18写道：

**Comment by JaryLee** [comment]
ok
