### ISSUE TITLE
建议提供关闭注册的配置

### ISSUE THREAD

**Issue by Varorbc** [star7th/showdoc#305]
建议提供关闭注册的配置

**Comment by star7th** [comment]
https://www.showdoc.cc/web/#/help?page_id=16118

编辑文件 server/Application/Api/Controller/UserController.class.php，
在register()里面，这个方法的开头处加上两行代码：

$this->sendError(10101,'不开放注册');
return ;

**Comment by Varorbc** [comment]
好的谢谢
