### ISSUE TITLE
获取我的项目接口报错

### ISSUE THREAD

**Issue by hi500** [star7th/showdoc#306]
访问 http://localhost:98/showdoc/web/#/item/index
下面这个请求是404
http://localhost:98/showdoc/server/index.php?s=/api/item/myList

**Comment by star7th** [comment]
看一下具体返回的网页内容是什么

yuanwu.min <notifications@github.com>于2018年7月7日 周六下午3:17写道：

**Comment by hi500** [comment]
执行升级数据库的脚本？  请明示，没有找到要执行什么脚本，数据库sqlite我是直接老的覆盖新的。

**Comment by star7th** [comment]
马虎到这种程度有饭吃么？都提醒看文档了。还不肯去看
https://www.showdoc.cc/web/#/help?page_id=13732

![image](https://user-images.githubusercontent.com/2200494/42503775-280dd344-846c-11e8-95a1-5d7a24a96f9d.png)

**Comment by hi500** [comment]
就服你
