### ISSUE TITLE
建议支持查看所有项目列表

### ISSUE THREAD

**Issue by hi500** [star7th/showdoc#307]
部署在本地，团队每个人都注册有自己的账号。目前是自己登录后能看到自己的项目。希望登录或者不登录，也能看到所有人的项目列表和项目所属人。

**Comment by star7th** [comment]
这种需求基本上只有你自己才会有。自己改一下自己的版本吧，官方仓库就不改了

**Comment by hi500** [comment]
是的，谢谢回复！你们的vue用的很666
