### ISSUE TITLE
布局上希望是左栏固定右侧自适应

### ISSUE THREAD

**Issue by hi500** [star7th/showdoc#308]
目前右侧正文区域 .page_content_main[data-v-1a671763]这个div的 width: 800px;窄窄的很浪费空间，我的表格都出现横向滚动条了。

**Comment by star7th** [comment]
不解释这个宽度设置了。要改在自己版本改吧。现在的宽度是照顾了不同分辨率下的一致性体验。

yuanwu.min <notifications@github.com>于2018年7月10日 周二下午6:28写道：

**Comment by Skqing** [comment]
style="width: 800px;" 是在哪里设置的 是用JS设置的吗？
