### ISSUE TITLE
无访问的情况下，内存不断上涨，直到100%，卡死

### ISSUE THREAD

**Issue by tonychenl** [star7th/showdoc#311]
无访问的情况下，内存不断上涨，直到100%，卡死
[https://adyx-static.oss-cn-hangzhou.aliyuncs.com/tmp/20180716134937.png](url)

**Comment by star7th** [comment]
showdoc消耗资源很小的。你这种情况是docker本身在消耗资源。建议检查docker。或者使用原生php环境

**Comment by tonychenl** [comment]
之前没有健康检查没有这个问题，现在前端加了个代理，有了健康检查，所以就稳定的内存上升了

**Comment by star7th** [comment]
所以这跟showdoc无关，看你自己新增的检测机制。

**Comment by tonychenl** [comment]
只是定期访问一下showdoc端口，只要有返回，就认为是活着的，这个跟正常访问理论上讲应该是一样的，不应该造成内存不释放吧？
