### ISSUE TITLE
请问如何支持php7？

### ISSUE THREAD

**Issue by 1049451037** [star7th/showdoc#315]
比如在Ubuntu 16.04以及Ubuntu mate上只能装php7无法装php5，该如何搭建呢？

**Comment by star7th** [comment]
本来就能在php7运行。

Qingsong Lv <notifications@github.com>于2018年7月22日 周日下午12:38写道：

**Comment by 1049451037** [comment]
果然可以，谢谢！之前有几个库apt-get找不到，把php7改成php就好了。
