### ISSUE TITLE
增加复制源码

### ISSUE THREAD

**Issue by fank243** [star7th/showdoc#316]
1.可以考虑增加复制源代码的小功能，这个还是挺实用的，有写代码片段挺长一块的。
2.可以考虑根据#等级增加标题导航，方面快速定位，这也是很常用的功能吧。
希望作者能考虑下我的建议，感谢你为开源做出的贡献！

**Comment by star7th** [comment]
第二点，使用markdown的TOC语法树。
第一点考虑下吧

**Comment by star7th** [comment]
现在想了想，觉得复制源码功能没必要。比如github就不用

**Comment by fank243** [comment]
好吧
