### ISSUE TITLE
升级后老版本链接地址失效

### ISSUE THREAD

**Issue by hi500** [star7th/showdoc#319]
php的老版本，和VUE的新版本对于同一个页面的URL不一样了，如果在升级后，做到访问老版本URL可以跳转的新版本页面，做到老版本URL兼容新版本。

**Comment by star7th** [comment]
如果你没有做过二次开发的话，是会自动跳转的。

**Comment by hi500** [comment]
是吗，我没有试过，只是有这个想法，那我就试试再说吧！您有先见之明！
