### ISSUE TITLE
editor.md对TeX/LaTeX,FlowChart,SequenceDiagram的支持

### ISSUE THREAD

**Issue by kdpun** [star7th/showdoc#32]
editor.md的本身有支持TeX/LaTeX,FlowChart,SequenceDiagram语法的，不知在showdoc是失效了还是故意屏蔽调的？

**Comment by star7th** [comment]
在编辑器的时候可用这些语法，但展示文档页面则不可用。展示文档的时候是采用bootstrap，放弃了editor.md的样式；而编辑器的样式依然是editor.md的样式。这样做主要是在展示页面集成editor.md样式的时候，发现对移动端不太友好，所以解决采用更友好的bootstrap样式。
不知需要这些特殊语法的人群多不多，如果多人有需求，我则再看看要不要把展示页面的样式改回editor.md样式
