### ISSUE TITLE
无法生成表格

### ISSUE THREAD

**Issue by peng2597758** [star7th/showdoc#323]
生成表格失败

![Uploading 微信图片_20180728160955.png…]()

**Comment by peng2597758** [comment]
还有啊，反馈个问题都这么麻烦，以后谁还想给你反馈问题？

**Comment by star7th** [comment]
没有能力用github的人，不应该使用开源版showdoc而是使用开箱即用的官网服务。开源版就是给有技术追求的人的。不再解释你的问题，自己解决去
