### ISSUE TITLE
管理员创建的项目文档，普通账户可以将其删除！

### ISSUE THREAD

**Issue by AmazingJamesLee** [star7th/showdoc#328]
版本：部署在我们自己服务器上的。
管理员创建的项目文档，普通账户首次点击删除的时候被提示 “不是项目的创建者”，但是当这个普通用户对这个文档进行编辑保存一次之后，点击删除就能顺利的将其删除。
需要我协助的地方可以联系我的邮箱：apache_lee@outlook.com/lix_jamesblunt@163.com,

**Comment by star7th** [comment]
逻辑是这样的，谁编辑了那个页面，那个页面的作者就是谁。不想别人有权限，添加成员的时候设置只读。

AmazingJamesLee <notifications@github.com>于2018年8月1日 周三下午5:52写道：

**Comment by AmazingJamesLee** [comment]
谢谢，知晓了。产品很棒！按个赞！
