### ISSUE TITLE
Nginx 访问重定向规则

### ISSUE THREAD

**Issue by luxixing** [star7th/showdoc#33]
安装完毕之后，不清楚Nginx的访问重定向规则，请在文档里面补充一下

**Comment by star7th** [comment]
nginx下的重定向规则 请参考：http://blog.star7th.com/2016/03/1969.html

**Comment by star7th** [comment]
新增了支持三级目录的功能；升级安装请参考部署手册中“升级安装”部分。http://blog.star7th.com/2016/05/2007.html
此外我新建了一个ShowDoc使用交流qq群（群号：564671853），欢迎探讨问题
