### ISSUE TITLE
关于markdown的collapse样式

### ISSUE THREAD

**Issue by 1049451037** [star7th/showdoc#331]
<details>
showdoc里只能显示“详细信息”
</details>
<details><summary>Click Me</summary>
但是我想让“详细信息”变成“Click Me”，在showdoc里面不行
</details>

**Comment by star7th** [comment]
这个不是markdown语法，这是html5原生标签。
showdoc对html仅是部分支持，并不保证全部支持。

**Comment by 1049451037** [comment]
好吧，谢谢~
