### ISSUE TITLE
老是提示验证码错误

### ISSUE THREAD

**Issue by rowbone** [star7th/showdoc#34]
老是提示验证码错误

**Comment by star7th** [comment]
试着打印session看看值是否一致

**Comment by rowbone** [comment]
session的 值是空的

**Comment by star7th** [comment]
试着 搜索下 “THinkPHP SESSION 空” 看能否找到一些解决方法

**Comment by star7th** [comment]
新增了支持三级目录的功能；升级安装请参考部署手册中“升级安装”部分。http://blog.star7th.com/2016/05/2007.html
此外我新建了一个ShowDoc使用交流qq群（群号：564671853），欢迎探讨问题

**Comment by auto007** [comment]
看看session目录php是否有权限
/var/lib/php/session  例如看看这个目录php是否有权限写入，我的就是这个问题
