### ISSUE TITLE
Index

### ISSUE THREAD

**Issue by siwen1017** [star7th/showdoc#340]
# Index for Project

As i know now showdoc only have placed at the top option for project 
Can we make a index like context page ,to sorting Project

**Comment by star7th** [comment]
Perhaps it is a good idea to allow dragging and sorting items .But I don't know if it is a public demand .Is it necessary ?How many items do you have ?

**Comment by star7th** [comment]
If there are not many items, it seems that 'set top function' is enough

**Comment by siwen1017** [comment]
@star7th  I am a IT In company ,so I have creat more DOC For much of different group / department.
as i rights is a doc manager & author ,It meas I have more Item to maintenance
I think ,when item creasing to many sort & filter will be helpful to manintenance

**Comment by star7th** [comment]
ok , I will do that when  I am free

**Comment by star7th** [comment]
Now that the item list can be sorted

**Comment by siwen1017** [comment]
It looks good !
