### ISSUE TITLE
建议增加访问计数器功能

### ISSUE THREAD

**Issue by 1049451037** [star7th/showdoc#343]
如标题，有时候想了解有多少人访问，或者在文档里展示访问量。

**Comment by star7th** [comment]
showdoc定位是团队内部使用，不太需要统计访问量。你是用于什么场景才需要统计访问量

Qingsong Lv <notifications@github.com>于2018年8月23日 周四下午10:00写道：

**Comment by 1049451037** [comment]
那或者是类似于团队内部打卡的？已阅就标记一下。

**Comment by 1049451037** [comment]
好吧，个人写的文档，类似于代码手册之类的。
