### ISSUE TITLE
有没有方法让网页对爬虫友好呢？

### ISSUE THREAD

**Issue by 1049451037** [star7th/showdoc#344]
看到链接里有井号，导致网页没法抓取到，有什么简便的配置方法可以把井号去掉吗？

**Comment by star7th** [comment]
很复杂都未必处理得好。没有简单的处理方案。

Qingsong Lv <notifications@github.com>于2018年8月26日 周日上午10:44写道：

**Comment by qianmengnet** [comment]
我前一段时间看了代码，主要是使用了vue，效果好了，但是对搜索的支持就不好了。
可能这个程序本来也没考虑对外，所以首页没有做出所有项目的列表，直接用vue也没有考虑爬虫。

**Comment by star7th** [comment]
VUE只有服务端渲染这种方式才能比较好解决SEO问题。而showdoc除了VUE还引用了其他东西，无法服务端渲染，所以基本没戏。
