### ISSUE TITLE
对首页和后台的一些建议

### ISSUE THREAD

**Issue by qianmengnet** [star7th/showdoc#345]
1、后台对用户的管理增加“封禁”功能，可以停用用户，以后有需要的话可以再启用。

2、后台对项目的管理增加“私有”和“屏蔽”功能，私有的话，强制设置它的状态，除了作者之外其他人不能看到。  屏蔽就是让所有人不能看到，类似于放入回收站，这样可以避免管理员不小心删除东西。

3、后台增加站点选项，比如标题、是否开放注册，是否直接显示项目列表（建议首页有这个功能，可以直接现实列表）

4、建议首页可以直接显示项目列表，如果后台不允许显示的话，显示默认的几个页面。

**Comment by star7th** [comment]
没明白为何要用户封禁功能，什么场景下需要它；
项目者不添加成员且设置密码就是私有项目，只有他能看，没必要再强制设置什么；
增加站点选项后面考虑下。

**Comment by star7th** [comment]
我整理下历史上的问题。
现在管理后台增加了是否开放注册的选项。
不打算增加让用户自定义显示项目列表页的情况。因为项目现在都是不设置图标的。用项目列表来做首页很难看。当前全屏首页会好些。
