### ISSUE TITLE
老版本升级后，无管理后台权限

### ISSUE THREAD

**Issue by wangmb** [star7th/showdoc#348]
老版本升级后，无管理后台权限，使用账号showdoc登录后，可以进入管理后台，操作时提示无管理后台权限

**Comment by star7th** [comment]
有执行最后一步，升级数据库吗？

**Comment by star7th** [comment]
描述一下你升级的步骤，这样才好看出哪里出问题

**Comment by wangmb** [comment]
谢谢回复，我重新有执行了update，再重启，现在无问题了。

**Comment by zuohl** [comment]
我没有执行update,然后手动注册了showdoc这个账号,,之后再update也没有出现管理后台权限,我需要怎么调整表数据来修复这个问题呢

**Comment by star7th** [comment]
@zuohl 进入表里把user表里showdoc那行记录删除后在update

**Comment by star7th** [comment]
@zuohl 我只能说官方给出了升级步骤。不按步骤弄出来的异常。我也没法解决，因为我也不知道你的数据表和代码做了什么调整。

**Comment by star7th** [comment]
@zuohl 自己试着把数据和代码还原到修改之前的状态，然后update，然后重新登录

**Comment by zuohl** [comment]
@star7th 嗯嗯,能不能提供下能正确显示管理后台权限依赖的数据,我能参照自己核对下

**Comment by star7th** [comment]
@zuohl 下载个新showdoc来看

**Comment by zuohl** [comment]
搞定了,翻代码才搞定的,,任意找一个用户update user set groupid = 1 where uid = 2就好了....谢谢@star7th
