### ISSUE TITLE
英文版下出现多处中文

### ISSUE THREAD

**Issue by tinydever** [star7th/showdoc#352]
![image](https://user-images.githubusercontent.com/8706577/45411930-1782a900-b6a8-11e8-9936-3b7c80e8e3d6.png)
![image](https://user-images.githubusercontent.com/8706577/45411945-24070180-b6a8-11e8-83c5-465f6009daec.png)
![image](https://user-images.githubusercontent.com/8706577/45411973-31bc8700-b6a8-11e8-982b-c28dc03c97ac.png)

**Comment by star7th** [comment]
翻译不彻底。新增功能的时候，每次都要对新功能的菜单都要进行翻译，没翻译得过来。有时间再修正。

**Comment by star7th** [comment]
关于翻译，很难做到全英。就比如说”我要自动生成文档“，这句话翻译成英文可以，但链接到的哪些文档，那么长都翻译的话会比较吐血。
关于多语言，我原来的想法是做一个基本支持英文的版本，看是否多点外国人用。如果用的外国人多了，自然会有人跟我提翻译的事，我也有动力去完善。现在暂时情况来看外国用户占的比例不超过百分之一，且他们少跟我反馈。所以我觉得暂时就放放了。如果有外国人反馈看不懂再完善。

**Comment by tinydever** [comment]
没读源代码，建议采用语言包方式，这样更方便添加其他语种
这个需求不重要

**Comment by star7th** [comment]
是语言包的方式。只是语言包也会有维护成本。

tinydever <notifications@github.com> 于2018年12月3日周一 下午3:45写道：

**Comment by tinydever** [comment]
close
