### ISSUE TITLE
项目列表页面不能区分哪些是自己创建的项目，哪些是别人分享给自己的项目

### ISSUE THREAD

**Issue by sleep651** [star7th/showdoc#354]
项目列表页面不能区分哪些是自己创建的项目，哪些是别人分享给自己的项目。点击项目设置按钮，如果不是自己创建的，会多次弹出“不是项目创建者”的对话框

**Comment by star7th** [comment]
正常使用情况下，不是自己创建的应该自己心里有数吧。而且项目不会很多。

sleep651 <notifications@github.com>于2018年9月17日 周一下午5:30写道：
