### ISSUE TITLE
项目页面的权限分配

### ISSUE THREAD

**Issue by instooo** [star7th/showdoc#355]
同一个项目，指定不通的人看到不通的页面文档，这个功能有的话，会很棒

**Comment by star7th** [comment]
会增加项目管理的麻烦度。比如说要一个个文档地西选择。而此功能一般用不到但要展示出来占位置

instooo <notifications@github.com> 于2018年9月19日周三 下午4:05写道：

**Comment by instooo** [comment]
整体来说还是很棒的，谢谢奉献
