### ISSUE TITLE
管理员密码可无原密码修改

### ISSUE THREAD

**Issue by Hyz8970** [star7th/showdoc#358]
管理员用户情况下，通过页面上的“个人设置”来重新设置密码是需要原密码的校验，而通过“管理后台”的“用户管理”对管理员自身密码修改，就不需要原密码的情况下修改。

**Comment by star7th** [comment]
管理后台拥有最高权限，基本上不再做验证。而外面的功能是面向普通用户的

Hyz8970 <notifications@github.com> 于2018年9月25日周二 上午11:39写道：
