### ISSUE TITLE
虚拟主机sql错误

### ISSUE THREAD

**Issue by fei11** [star7th/showdoc#359]
在本地可以运行，ftp到虚拟主机后报错

SQLSTATE[HY000]: General error: 11 database disk image is malformed
错误位置
FILE: /home/ftp/n/wwwroot/server/ThinkPHP/Library/Think/Db/Driver.class.php 　LINE: 156

**Comment by star7th** [comment]
不支持虚拟主机

fei11 <notifications@github.com>于2018年9月28日 周五下午6:02写道：
