### ISSUE TITLE
网站升级之后，新增的管理后台功能打开提示没有权限

### ISSUE THREAD

**Issue by Rsyncy** [star7th/showdoc#360]
showdoc网站进行升级，点击平台新增的 管理后台 功能，提示 没有权限，这个是哪里没有设置还是哪个文件权限不够？

**Comment by star7th** [comment]
1,回头看升级文档，自己是否执行了升级数据库脚本
2，重新登录试试

**Comment by Rsyncy** [comment]
好了，退出登录，然后重新执行升级操作，重新登录就好了，谢谢。
