### ISSUE TITLE
docker 安装 访问出现403

### ISSUE THREAD

**Issue by kevinye-2017** [star7th/showdoc#361]
参照https://www.showdoc.cc/help?page_id=65610

docker logs showdoc 出现的问题
   chown: /var/www/html: Permission denied
images没测过就放到dockerhub？？？

**Comment by star7th** [comment]
我觉得可能是目录没挂载成功

Kevin sw <notifications@github.com> 于2018年10月10日周三 下午4:36写道：

**Comment by star7th** [comment]
或者目录全新没有。
你看看宿主机的/showdoc_data/html下有没有数据

Chen Xing <xing7th@gmail.com> 于2018年10月10日周三 下午5:05写道：

**Comment by star7th** [comment]
如果是报这个错误的花，基本能肯定是/showdoc_data/html没有全新

**Comment by star7th** [comment]
没有权限

**Comment by star7th** [comment]
你这种情况应该是由于启动docker服务的用户无权限导致
为了应付这种特殊情况，我改了下文档。在 mkdir /showdoc_data/html 命令后面增加命令chmod 777 -R /showdoc_data

**Comment by zhwq** [comment]
推荐通过在主机创建同gid和uid的show账户,设置给showdoc_data
```
groupadd -g 101 showdoc
useradd -u 100 -g 101 -M showdoc
chown -R showdoc:showdoc /showdoc_data
```

**Comment by xujihua** [comment]
> 你这种情况应该是由于启动docker服务的用户无权限导致
> 为了应付这种特殊情况，我改了下文档。在 mkdir /showdoc_data/html 命令后面增加命令chmod 777 -R /showdoc_data

同403, 目录权限加过, 使用root用户操作的

**Comment by star7th** [comment]
root用户操作不代表docker进程有权限。
你自己进入容器里看看，目录挂载是否成功了，里面是不是有文件了

xujihua <notifications@github.com> 于2019年10月16日周三 上午10:52写道：

**Comment by xujihua** [comment]
docker run  --privileged=true

**Comment by star7th** [comment]
不要相信命令，直接容器里看有没有文件就知道挂载是否成功了。/var/www/html
