### ISSUE TITLE
本地服务器下，项目自定义二级目录如何实现

### ISSUE THREAD

**Issue by ubuff** [star7th/showdoc#365]
作者你好，我修改了webpack生产环境目录名，将web目录替换成了hidoc，然后我将
`\WWW\server\Application\Home\Controller\ `目录下**IndexController、ItemController、PageController**这几个文件里的web字样 也修改成了  `header("location:./hidoc/#/")`
重启apache 提示 项目不存在或已删除，没弄过tp，请问我该如何才能替换url里 web 为我想要的目录名？望方便之余帮我解答下，谢谢!

**Comment by star7th** [comment]
我没试过，想不起来那些地方需要改了。不建议修改，好像很多地方都引用。

Jan <notifications@github.com> 于2018年10月12日周五 下午4:52写道：

**Comment by ubuff** [comment]
好尴尬，可能是缓存，我webpack编译了一下，重启服务可以用了。好的那我还是改回去吧
