### ISSUE TITLE
showdoc用户名应该要受保护

### ISSUE THREAD

**Issue by mstaryi** [star7th/showdoc#366]
showdoc用户看起来像是一个管理员账户，但在用户管理里面可以把它删除。这个操作应该受保护，不能删除才对

**Comment by star7th** [comment]
假如有人要添加多个管理员，就允许删除吧。
这个更主要靠人为约束，无缘无故删除唯一的管理员账户干嘛。

**Comment by mstaryi** [comment]
问题是新增用户没有管理员选项。实际上我现在碰到的问题是把showdoc用户删了，现在系统里面没得管理员用户了，如何处理才能把管理员用户加进来呢

**Comment by star7th** [comment]
你为何要删呢，我没有考虑过这种明显的人为情况。下次加个约束吧。
你现在选择升级安装。升级时候发现没有管理员会添加进去的。看升级安装的文档来操作。
