### ISSUE TITLE
关于编辑及阅读界面问题

### ISSUE THREAD

**Issue by CZFork** [star7th/showdoc#367]
1.编写的时候能不能像gitbook类似那样，可以同时编写目录，每次都要预先写好目录以及选择目录方式太繁琐
2.阅读在原有基础上能像gitbook一样有< 和>翻页按钮，以及电脑版有悬浮按钮显示小标题（单页文件目录）
3能不能直接复制多图文章的粘贴
4.导出的时候图片全部丢失了（这个最好能导出pdf,含目录最好😊）

**Comment by CZFork** [comment]
谢谢你能够看我的需求!
第三点能做最好啦，比较定位是API说明文档；
这里我修改一下一点想法，有目录显示的时候可以借鉴Gitbook，但在这个显示模式下不要< 和 >切换按钮，而在单页全屏下可以显示< 和 >
导出pdf的话，之前看到过leanote使用的是Wkhtmltopdf

**Comment by hugbox** [comment]
![9150e4e5ly1frtqw8sqg3j2074074748](https://user-images.githubusercontent.com/15120875/48934237-27d3c180-ef3e-11e8-900b-5b425d09f9ff.jpg)

**Comment by dongsong** [comment]
希望浏览页面时插入的表格能够自动伸缩长度，宽屏显示时，目前插入的代码端长度能自适应，但表格明显很短，看起来很别扭

**Comment by star7th** [comment]
@dongsong 截图

**Comment by dongsong** [comment]
![image](https://user-images.githubusercontent.com/1272308/50000240-e2059880-ffd3-11e8-80ce-f9533bfb099b.png)

**Comment by star7th** [comment]
@dongsong 实际上把表格宽度弄长了，也只是解决当前这种场景而已。宽屏模式下难免随着电脑分辨率的大小而变形，决定了这个问题也会有下个问题。所以为什么showdoc固定死了页面展示宽度，就是为了保证在不同分辨率下的一致性阅读体验

**Comment by star7th** [comment]
当前官方增加了一个更新：你在编辑的时候使用markddown的TOC标签，保存后，你在项目页面就可以看到右边有个导航（相当于单页文件目录）

**Comment by star7th** [comment]
经多次思考，觉得没必要把页面编辑和目录编辑放在一起，不够简洁。目录编辑本身是个低频行为。页面编辑才会多一些。这两种功能还是分开编辑比较号。
