### ISSUE TITLE
挂载外部目录不能正常修改文档

### ISSUE THREAD

**Issue by spxx12138** [star7th/showdoc#368]
将机器A上的/var/www/html打包,删除镜像,重新运行,再将刚才的压缩包cp至容器内解压,数据恢复,操作正常.

在机器B上运行镜像,挂载本地目录,再将压缩包解压至宿主机的目录,文档都可以正常显示,修改也显示了保存,但是退出重进 发现修改并未生效;修改用户密码,添加用户等操作会提示发生未知错误

**Comment by star7th** [comment]
本地目录递归777权限

**Comment by spxx12138** [comment]
嗯,是这个问题,我是在解压前赋予的权限
回的好快,哈哈哈
