### ISSUE TITLE
想了很久提出来的意见

### ISSUE THREAD

**Issue by caijh0316** [star7th/showdoc#369]
可否在创建的项目中增加全文搜索的功能？现在的搜索只能搜索标题，在做项目开发时，想到一个接口字段内容不能直接在搜索中搜索。我认为增加项目的全文搜索会提高效率，同时，这个也比全局搜索要安全，保证了权限的独立。

**Comment by star7th** [comment]
搜索的时候会模糊匹配内容。只是没有高亮显示而已。

caijh0316 <notifications@github.com> 于2018年10月18日周四 下午5:12写道：

**Comment by caijh0316** [comment]
辛苦啦！那在升级的时候，可否增加这样的功能呢？如果可以有专门的搜索结果页或者结果弹框，标明路径就更好了！
