### ISSUE TITLE
自动生成API文档,点击为空

### ISSUE THREAD

**Issue by howess** [star7th/showdoc#373]
https://www.showdoc.cc/script/api_demo.test 用测试例子生成的api点击进去为空，目录和文件都生成了
![image](https://user-images.githubusercontent.com/10075418/47416425-47919180-d7a8-11e8-9378-0ab48e6a5e9a.png)

**Comment by star7th** [comment]
没遇到过这种情况。你可以试下https://www.showdoc.cc 有没有这个问题

**Comment by howess** [comment]
开源版有这个问题~请问有遇到过吗？还是需要特殊配置？已经按照文档来设置了

**Comment by howess** [comment]
![image](https://user-images.githubusercontent.com/10075418/47419232-524f2500-d7ae-11e8-922a-743266538ee3.png)
应该是生成的时候这两个字段导致乱码，显示不出来，但是可以导出

**Comment by star7th** [comment]
就算是开源版也只是你反馈过这个问题。
我觉得跟你本机的环境有关，例如编码什么的

**Comment by howess** [comment]
我改成name的注释，就生成成功了~
![image](https://user-images.githubusercontent.com/10075418/47419671-457f0100-d7af-11e8-9077-8cbc0ff0b412.png)

**Comment by star7th** [comment]
什么叫  ”改成name的注释“

**Comment by howess** [comment]
继续测试了一下，用“必选”就生成不了，只能写“可选"

**Comment by star7th** [comment]
官方就有必选可选的例子。尝试不做任何改动的前提下用官方测试例子。没遇到过你这样的情况

howess <notifications@github.com> 于2018年10月25日周四 下午12:50写道：
