### ISSUE TITLE
表格内容中带有‘|’无法正常显示

### ISSUE THREAD

**Issue by tongyi121** [star7th/showdoc#377]
如果表内容中带有‘|’符号，会被认为多1个列，我尝试将其转为&#124;，实施预览时能够正常显示，保存后查看页面还是存在问题，这个问题如何解决？

**Comment by star7th** [comment]
搜索 markdown 表格 特殊字符

Tong <notifications@github.com> 于2018年10月31日周三 上午10:27写道：

**Comment by tongyi121** [comment]
已经转成‘& #124;’，但是还是有问题

**Comment by star7th** [comment]
我建议在业务中避免输入这个符号。没有什么文字描述是不能换个说法去表达的

Tong <notifications@github.com> 于2018年10月31日周三 上午10:35写道：

**Comment by tongyi121** [comment]
实时预览时候是正常的，保存后在查看文档时会出现问题。我们写的是api文档，有个参数需要用到这个字符进行连接，如果换了字符就表达不清楚了。我是想提1个bug，实时预览如果也显示不正常，这个还是能理解的，可是实时预览没问题，查看文档时又出现了问题，就应该是个bug了。

**Comment by star7th** [comment]
精力有效，不想在这种极端情形下消耗过多精力。极少人会遇到这种情况。
建议不使用表格形式来展示参数。比如可以改为用代码块的形式，普通文本描述的形式，等等


Tong <notifications@github.com> 于2018年10月31日周三 上午10:43写道：
