### ISSUE TITLE
API自动生成 @return 过长生成失败

### ISSUE THREAD

**Issue by howess** [star7th/showdoc#378]
![image](https://user-images.githubusercontent.com/10075418/47977109-50139180-e0f1-11e8-98ab-33e846dd22b7.png)
API自动生成 @return 过长生成失败

**Comment by star7th** [comment]
请不要换行，不要包含换行符空格tab，如果要包含请转义。

howess <notifications@github.com>于2018年11月5日 周一上午11:53写道：
