### ISSUE TITLE
使用几天的一些感受

### ISSUE THREAD

**Issue by yangypDeveloper** [star7th/showdoc#380]
1. 历史记录界面记录着差异,但是变化太多了,我想把旧版本的完全复制出来是做不到的,能不能提供一个一键复制旧版本的按钮
2. 删除操作太可怕了,能不能提供回收站的功能,或者像版本管理一样,只增不删,还有没有草稿箱功能,出现过几次覆盖和丢失的情况,没有找到具体原因
3. 最后感谢开源的行为,希望越来越好,致谢!

**Comment by star7th** [comment]
1，我觉得是人为操作规范的问题。你不需要每改动一下就提交一个版本，这样会产生很多记录。就算用git，大量提交也会产生很多版本。跟工具没关系。在编辑页面打开“历史版本”，就能看到“恢复"按钮。
2，我还是觉得人为操作规范的问题。如果你不改善这种习惯，以后还可以出乱子。为什么没想清楚就随随便便删除文档呢？而且删除前是有确认过程的，也还是确认删除了。“出现过覆盖和丢失的情况”，没发现showdoc有这种情形。
工具是可以限制规范你的行为，回收站功能后面会做，但是我还是建议你先把行为规范好。
