### ISSUE TITLE
自动生成API文档的脚本 遇到&符号，获取的内容不完整

### ISSUE THREAD

**Issue by howess** [star7th/showdoc#383]
自动生成API文档的脚本 遇到&符号，获取的内容不完整
![image](https://user-images.githubusercontent.com/10075418/48104699-8d059280-e26f-11e8-92ef-765db30b8ab0.png)
![image](https://user-images.githubusercontent.com/10075418/48104726-a0186280-e26f-11e8-82a5-1cf3a88ce32d.png)

**Comment by star7th** [comment]
文档鼓励url和参数分离。
把参数单独写。

**Comment by howess** [comment]
就是想在url上给个示例，然后在param 上再做详细描述，请问可以做到吗？

**Comment by star7th** [comment]
数据是要post给showdoc的api的，而你含有&字符会冲突。解决方式是转义和解转义。我暂时不想为这种特殊需求开绿色通道了。建议url和参数分离
