### ISSUE TITLE
关于团队管理功能建议

### ISSUE THREAD

**Issue by magicjva** [star7th/showdoc#386]
团队管理功能建议：
1. 总团队，也就是说一个公司开发人员都在里面
2. 项目团队， 当要创建一个项目团队时，就不用再一一输入一遍，只要把总团队中的成员列出来选择等，这样操作就方便了，也清析。

**Comment by star7th** [comment]
其实不需要这样子。后面做个模糊搜索功能就好了。

magicjva <notifications@github.com> 于2018年11月12日周一 下午1:51写道：

**Comment by star7th** [comment]
忘记提了，最新版代码已经支持模糊搜索成员
