### ISSUE TITLE
添加成员返回出现未知错误

### ISSUE THREAD

**Issue by lizhuowei** [star7th/showdoc#387]
返回信息如下：
error_code: 10101
error_message: "未知错误"

**Comment by star7th** [comment]
这是个统一的错误码，表示发生了非预期结果。单纯看这个是不知道为什么的。建议你把上下文使用场景都说一遍。

**Comment by star7th** [comment]
另外从来没遇到过添加成员时候提示这个的情况。

**Comment by lizhuowei** [comment]
刚刚试了一下，已经添加上去了，我还是描述一下场景吧！
具体的业务场景是添加成员界面
https://user-images.githubusercontent.com/22720841/48458684-5517c580-e802-11e8-97ae-16bde22df15d.png
出现问题的时间上是昨天下午到今天上午，谢谢关注！
