### ISSUE TITLE
文档查看页面不显示编辑按钮

### ISSUE THREAD

**Issue by eddyree** [star7th/showdoc#391]
2018年11月21日升级到最新版后，文档查看页面看不到编辑按钮，有编辑权限的用户也看不到。查看源码，编辑按钮的悬浮层的样式被设定为 display: none; 没有找到任何设定选项可以关闭编辑按钮隐藏处理。

**Comment by star7th** [comment]
关闭浏览器后重启试试

Eddy Ree <notifications@github.com> 于2018年11月22日周四 上午9:13写道：

**Comment by eddyree** [comment]
试过，没效果。用同一个浏览器访问官网演示网站，可以看到编辑按钮。应该不是浏览器加你荣问题。

**Comment by eddyree** [comment]
试过，没效果。用同一个浏览器访问官网演示网站，可以看到编辑按钮。应该不是浏览器加你荣问题。

**Comment by star7th** [comment]
亲测无此问题。
我觉得你很大概率是因为设置了只读成员。只读成员是没有编辑权限的。在添加成员的时候，对成员权限描述得很清楚。这种细节操作问题就尽量别浪费大家时间了吧

Eddy Ree <notifications@github.com> 于2018年11月22日周四 上午9:43写道：

**Comment by eddyree** [comment]
肯定不是只读成员，所有用户都是从旧版数据库执行数据库升级脚本升级上来的。看看数据库升级脚本是否存在问题。新建项目，新建会员给编辑权限，一切都试过，没效果。“只读成员是没有编辑权限”这种低级错误怎么会到这里发问题...............

**Comment by star7th** [comment]
把旧版本打包发到xing7th@gmail.com，我升级下看有没有问题

Eddy Ree <notifications@github.com>于2018年11月22日 周四上午11:31写道：
