### ISSUE TITLE
你好，部分中文内容修改

### ISSUE THREAD

**Issue by FTsong** [star7th/showdoc#394]
你好，部分中文内容修改问题，我尝试在 
showdoc/server/Application/Home/Lang
showdoc/server/Application/Api/Lang
showdoc/server/ThinkPHP/Lang
3个地方修改“登录/注册” 为“管理员登录/注册” 后，重启服务，依然没有办法生效，希望能得到帮忙，非常感谢。

**Comment by FTsong** [comment]
我使用的是 php的 部署方法

**Comment by star7th** [comment]
前端源文件在web_src目录
用wepack打包到web目录

**Comment by star7th** [comment]
跟TP无关，不再用TP生成前端文件。

**Comment by FTsong** [comment]
> 跟TP无关，不再用TP生成前端文件。

好的，非常感谢！
