### ISSUE TITLE
本地部署showdoc，首次登陆后，退出登陆，再次登陆请求会pending？

### ISSUE THREAD

**Issue by 00feng00** [star7th/showdoc#395]
本地linux系统使用docker部署项目，登陆后，点击退出登陆，再次登陆请求pending,该怎么解决？

**Comment by 00feng00** [comment]
我修改了vue项目，然后重新打包，之后请求就会pending,是哪里的问题？

**Comment by star7th** [comment]
你修改出来的问题我也不知道啊。我不知道你改了什么。

**Comment by 00feng00** [comment]
我修改了web_src里面的东西，然后打包覆盖web这个文件，那些请求就会pending

**Comment by star7th** [comment]
你这话说了等于没说一样。具体修改了什么，列出来

啊锋 <notifications@github.com> 于2018年11月27日周二 上午11:08写道：

**Comment by star7th** [comment]
另外，pending表示在发送中，但未得到后台响应

Chen Xing <xing7th@gmail.com> 于2018年11月27日周二 上午11:09写道：

**Comment by 00feng00** [comment]
改了web_src一些css，还有一些文字说明。没改其他的了

**Comment by star7th** [comment]
建议重新安装showdoc看看有没有这个问题。在新showdoc的基础上再改

啊锋 <notifications@github.com> 于2018年11月27日周二 上午11:19写道：

**Comment by 00feng00** [comment]
重装了，然后运行，首次请求可以，之后的请求就都pending。这个是什么问题导致的。使用docker安装

**Comment by 00feng00** [comment]
![1543286611 1](https://user-images.githubusercontent.com/18207644/49057766-032c6200-f23c-11e8-83b7-02c26da0c2ad.jpg)

**Comment by star7th** [comment]
我大概知道原因了。已修复问题。你更新代码吧。

**Comment by 00feng00** [comment]
按照更新升级的步骤，重新下了github上面的代码，还是不行。

**Comment by star7th** [comment]
实际上测试无此问题。
推荐使用官方自动脚本进行安装和升级：https://www.showdoc.cc/help?page_id=828455960655160

**Comment by 00feng00** [comment]
我使用的是Docke方式安装

**Comment by star7th** [comment]
推荐使用官方自动脚本

啊锋 <notifications@github.com> 于2018年11月27日周二 下午3:07写道：

**Comment by 00feng00** [comment]
更新了版本，过了一伙，好像好了，看起来应该是解决了，我修改下web_src试试看
