### ISSUE TITLE
编辑页面和API测试页面的建议

### ISSUE THREAD

**Issue by lilacseeking** [star7th/showdoc#399]
详细描述：

1. 在线测试API输入参数建议添加raw格式数据，可以上传text、json文本类型，测试用例建议保存，直接引用已保存实例测试。

2. 建议编辑页面md源代码和md预览界面都实现修改，只显示预览界面进行编辑，实现参照Typora。

3. md预览界面若实现可编辑，建议表格下方添加按钮"新增一行"。

**Comment by star7th** [comment]
1，在线api测试只是个简单的工具，不打算用来解决复杂场景的问题。复杂场景可用postman
2，我暂时没发现这样有这样的开源编辑器实现。自己实现一个编辑器会很困难，所以暂时不考虑。
3，同上

lilacseeking <notifications@github.com> 于2018年11月30日周五 下午12:50写道：

**Comment by lilacseeking** [comment]
好的，我了解下可以解决这个问题的开源的md编辑器，到时候联系你
