### ISSUE TITLE
只能显示一个第一个页面  其他都不显示  Runtime是可写的  是不是vhost的原因？

### ISSUE THREAD

**Issue by zhangjinling** [star7th/showdoc#4]
我觉得应该是url没有解析：http://xxx.xxxx.com/index.php/Home/item/show?item_id=3

只能显示一个第一个页面  其他都不显示  Runtime是可写的  是不是vhost的原因？我去掉url重写也不行，帮我看一下  ， 谢谢
只有首页可以，其他都是url变化了，但是页面没有变化！
//**********Log 日志
[ 2015-12-07T21:19:50+08:00 ] 124.207.72.242 /index.php/Home/item/show?item_id=2
INFO: [ app_init ] --START--
INFO: Run Behavior\BuildLiteBehavior [ RunTime:0.000013s ]
INFO: [ app_init ] --END-- [ RunTime:0.000267s ]
INFO: [ app_begin ] --START--
INFO: Run Behavior\ReadHtmlCacheBehavior [ RunTime:0.000350s ]
INFO: [ app_begin ] --END-- [ RunTime:0.000400s ]
INFO: [ view_parse ] --START--
INFO: [ template_filter ] --START--
INFO: Run Behavior\ContentReplaceBehavior [ RunTime:0.000049s ]
INFO: [ template_filter ] --END-- [ RunTime:0.000102s ]
INFO: Run Behavior\ParseTemplateBehavior [ RunTime:0.005679s ]
INFO: [ view_parse ] --END-- [ RunTime:0.005716s ]
INFO: [ view_filter ] --START--
INFO: Run Behavior\WriteHtmlCacheBehavior [ RunTime:0.000098s ]
INFO: [ view_filter ] --END-- [ RunTime:0.000130s ]
INFO: [ app_end ] --START--
INFO: Run Behavior\ShowPageTraceBehavior [ RunTime:0.000431s ]
INFO: [ app_end ] --END-- [ RunTime:0.000468s ]

//*************vhost
server { 
  listen 80;
  client_max_body_size 100M;
  server_name xxxx.xxxx.com;
  charset utf-8;
  index index.php;
  root /home/nccwiki; 
  access_log /usr/local/nginx/log/access.log access;

 # if ($request_uri !~* "^.*\.(ico|pdf|flv|jpe?g|js|gif|png|html|shtml|zip|xml|gz|rar|swf|txt|apk|bmp|css|m4a|ogg|mp3|mp4|ipa)(\?v=.*)?$") {
  #  rewrite ^/(.*)$  /index.php/$1/$is_args$query_string last;
  #}

  error_page 404 /404.html;
  location = /40x.html {
    root /home/nccwiki;
  }

  error_page 500 502 503 504 /50x.html;
  location = /50x.html {
    root /home/nccwiki;
  }

  location ~ "^/index.php" {
    fastcgi_pass 127.0.0.1:9000;
    fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
    fastcgi_index  index.php;     include /etc/nginx/fastcgi_params;
  }
    
}

**Comment by star7th** [comment]
我看不出详细原因，只能提供一些思路去查错。
试试清空runtime文件夹；
URL可能区分大小写？试试访问index.php/Home/Item/Show?item_id=3
再次去掉任何重定向相关代码，并且清空runtime再试
