### ISSUE TITLE
历史版本和更多模板问题

### ISSUE THREAD

**Issue by lilacseeking** [star7th/showdoc#401]
1. 用户user新建一个项目，将2个小伙伴添加到团队中，权限设置为编辑，user操作文档查看某个页面的历史版本和另存为模板，没有问题，其他小伙伴查看页面的历史版本和更多模板<el-dialog>显示的内容为空。
前端控制台有个error：vendor.d388884….js:12 TypeError: Cannot read property 'slice' of undefined(…)

**Comment by star7th** [comment]
历史版本是共享的，每个人可以看到。
自定义模板是每个账户只能看到自己的
