### ISSUE TITLE
我的项目 item_domain 跳转问题

### ISSUE THREAD

**Issue by zhangxiaoman** [star7th/showdoc#403]
当老项目设置了 item_domain 是 我的项目首页项目的 url 会优取 item_domain, 
点到项目首页. 这个时候 item_id 的值是 item_domain 导致查不到项目信息.

**Comment by star7th** [comment]
升级吧。新版showdoc已经去掉item_domain这个功能，不考虑兼容支持。

zhangxiaoman <notifications@github.com> 于2018年12月3日周一 下午10:47写道：

**Comment by zhangxiaoman** [comment]
升级之后的问题..最新版

**Comment by zhangxiaoman** [comment]
/var/www/html/server/Application/Api/Controller/ItemController.class.php
$item_domain = I("item_domain/s");
        $current_page_id = I("page_id/d");
        if (! is_numeric($item_id)) {
            $item_domain = $item_id ;
        }
        //判断个性域名
        if ($item_domain) {
            $item = D("Item")->where("item_domain = '%s'",array($item_domain))->find();
            if ($item['item_id']) {
                $item_id = $item['item_id'] ;
            }
        }

算是升级遗留问题

**Comment by star7th** [comment]
你的设置的item_domain是什么

**Comment by zhangxiaoman** [comment]
一般是字符串..

**Comment by star7th** [comment]
从代码上看其实应该是兼容的。可能后来更改太多引入了不兼容的成分。建议直接编辑去掉item_domain吧，打算支持item_domain了

**Comment by zhangxiaoman** [comment]
$item_id = I("item_id/d");
改成可兼容
$item_id = I("item_id/s");

**Comment by zhangxiaoman** [comment]
嗯 我看新版建项目已经没有 个性域名了.. 老数据里面有设置, 还是尽量兼容下好点..

**Comment by star7th** [comment]
已改 https://github.com/star7th/showdoc/commit/51668f810fd1a42543630311c621a4e44357f3bb

**Comment by zhangxiaoman** [comment]
nice
