### ISSUE TITLE
SQLSTATE[HY000]: General error: 11 database disk image is malformed

### ISSUE THREAD

**Issue by xuping123** [star7th/showdoc#404]
SQLSTATE[HY000]: General error: 11 database disk image is malformed

**Comment by star7th** [comment]
有没有用什么东西编辑过db文件
是否在window环境下安装过
是否安装了sqlit3扩展？
是否尝试过使用官方脚本或者docker方式后还有此问题

**Comment by xuping123** [comment]
在window下安装过在同步到linux上的。 是这个问题吗？ 拓展已经装过的，db文件没有编辑过，只是打开看过

**Comment by star7th** [comment]
我也不知道。有人反馈过windows迁移的问题。但我不清楚这个问题是windows更改了文件格式引起，还是你的linux环境本身没装好环境引起。
要验证的话，尝试这个教程的”从手动方式升级到自动脚本方式“部分   https://www.showdoc.cc/help?page_id=828455960655160

**Comment by star7th** [comment]
如果装了官方推荐的环境都还是不行，则是win环境更改了文件格式引起。

**Comment by xuping123** [comment]
嗯， 好的， 我先重新下载一个干净的版本同步到服务器上看下，，，我确定不是环境的问题，

**Comment by xuping123** [comment]
在github上下载的版本直接同步到服务上，也是报了同样的错误， 环境我也对比了，也就是一个sqlite3拓展，其他的没有特殊情况啊， 会是什么问题呢，之前有人反应在linux上安装的问题吗?

**Comment by star7th** [comment]
用官方dockers安装吧。每一种系统环境不一样，很难讲。

**Comment by xuping123** [comment]
没有ssh的账号哦， 只有一个ftp的，

**Comment by star7th** [comment]
那就没办法了

xuping <notifications@github.com> 于2018年12月6日周四 下午5:21写道：

**Comment by star7th** [comment]
没有办法。连ssh都不能访问，那就什么事都做不了。

xuping <notifications@github.com>于2018年12月6日 周四下午5:27写道：
