### ISSUE TITLE
QQ登陆这个功能有不有用勒？

### ISSUE THREAD

**Issue by tomcwj** [star7th/showdoc#405]
首先感谢作者提供这么优秀的开源软件。非常不错。
QQ登陆这个功能有不有用勒？

**Comment by star7th** [comment]
有用。然后呢？

tomcwj <notifications@github.com>于2018年12月6日 周四下午5:29写道：

**Comment by star7th** [comment]
如果你是想showdoc集成qq登录，那么，在www.showdoc.cc 可能会考虑，而开源版showdoc不做考虑。
支持qq登录要跟腾讯申请资质，设置回调地址等麻烦。并不适合企业内部使用

Chen Xing <xing7th@gmail.com>于2018年12月6日 周四下午5:35写道：

**Comment by tomcwj** [comment]
好的，感谢大龙回复，开源版让需要QQ登陆的人自己申请就完了。

**Comment by star7th** [comment]
这种需求太小众，不花那个精力去支持了。绝大部分的企业都用不到，徒增麻烦。

tomcwj <notifications@github.com> 于2018年12月7日周五 上午10:30写道：
