### ISSUE TITLE
General error: 11 database disk image is malformed

### ISSUE THREAD

**Issue by xuping123** [star7th/showdoc#406]
General error: 11 database disk image is malformed

我在google上搜了下， 之前也有人遇到这问题， 麻烦问下之前有人解决过吗，

**Comment by star7th** [comment]
很少人会遇到这个问题。遇到了也是环境的问题。
我记得你之前问过此问题了https://github.com/star7th/showdoc/issues/404
你连ssh账户都没有，证明无法安装环境，所以没有任何办法，不要试图在没有ssh账户的前提下还解决得了这个问题。
去跟人申请权限，安装docker，或者用自动脚本

**Comment by star7th** [comment]
这是个通用性错误，说明读不了数据库。不安装环境是不行的，不要再试图做无用功。
