### ISSUE TITLE
使用docker自动安装，访问502

### ISSUE THREAD

**Issue by yexiaoyu** [star7th/showdoc#407]
系统环境：CentOS release 6.10 (Final)
使用 wget https://www.showdoc.cc/script/showdoc;chmod +x showdoc; 自动安装最后出现
![image](https://user-images.githubusercontent.com/5335425/49624226-99fed880-fa0b-11e8-98e2-f9aefe6ffc35.png)
查看端口起来了
![image](https://user-images.githubusercontent.com/5335425/49624393-36c17600-fa0c-11e8-9185-fcf89536d8b0.png)

![image](https://user-images.githubusercontent.com/5335425/49624272-cdd9fe00-fa0b-11e8-8af6-fc766b9e7953.png)

![image](https://user-images.githubusercontent.com/5335425/49624557-dbdc4e80-fa0c-11e8-8eb8-5fbb4162f4bf.png)

**Comment by star7th** [comment]
看一下/showdoc_data/html 有没有数据

**Comment by yexiaoyu** [comment]
有数据的
![image](https://user-images.githubusercontent.com/5335425/49625397-50fd5300-fa10-11e8-8ba5-c3fe21326071.png)

**Comment by star7th** [comment]
是宿主机里的该目录，不是docker里，确定？

顾宇 <notifications@github.com> 于2018年12月7日周五 上午11:07写道：

**Comment by star7th** [comment]
我就当你截图是宿主机吧。
如果这样，就代表服务起来了，并且数据也正常。这算是安装好了。
现在的问题是访问不了。我猜你的什么安全策略限制禁止了端口映射或者访问之类的

**Comment by yexiaoyu** [comment]
截图是宿主机的。我在docker容器里，netstat看不到80端口有起来呢？

**Comment by star7th** [comment]
我刚在centos6.6的虚拟机上测试，是正常的。镜像本身没问题。
应该是你的服务器环境对docker进程本身做了什么限制。
现在，只能建议你手动执行docker安装，看看具体哪一个命令出错了https://www.showdoc.cc/help?page_id=65610

**Comment by yexiaoyu** [comment]
好的。
