### ISSUE TITLE
可否支持保存模板功能

### ISSUE THREAD

**Issue by ephen** [star7th/showdoc#41]
编写好内容后保存成模板，方便下次直接调用

**Comment by star7th** [comment]
没有。建议使用接口复制功能

**Comment by CinderellaCiCi** [comment]
我知道没有保存模板的功能，所以才建议下的。
刚想搞个存放工作周报的项目，发现写起来不太方便，要是能自己整个模板保存下，大家都能直接调用就很爽了。
可以由项目所有者有创建当前项目模板的权限。

**Comment by star7th** [comment]
如果做此功能的话，干脆将它做成模板库的功能。有公开模版和私有模板的区别；
现在暂时不打算做。你新建个模版文件，告诉大家如果需要则复制。暂时先这样解决吧。有空再构思下模板库

**Comment by star7th** [comment]
到了现在，发现需要模板库需求的人很少，所以此功能不再考虑。对于部分小需求可以采用复制页面的方法解决。

**Comment by star7th** [comment]
本来是不想做模板功能的，后来觉得还是有会方便点。现在github上已经提交了更新，新增自定义模板功能，允许用户将自己的页面设置为模板
