### ISSUE TITLE
阿里云服务器使用自动脚本安装出错

### ISSUE THREAD

**Issue by xixigou** [star7th/showdoc#410]
作者，你好，非常感谢开源这么好用的文档工具。在阿里云服务器使用自动脚本安装时，出现些异常，详情见下面，这样的异常是怎样解决？谢谢
--2018-12-14 11:41:41--  (try:18)  http://localhost:4999/install/install.lock
Connecting to localhost|127.0.0.1|:4999... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2018-12-14 11:41:51--  (try:19)  http://localhost:4999/install/install.lock
Connecting to localhost|127.0.0.1|:4999... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2018-12-14 11:42:01--  (try:20)  http://localhost:4999/install/install.lock
Connecting to localhost|127.0.0.1|:4999... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Giving up.

**Comment by star7th** [comment]
手动一行一行执行命令看下 https://www.showdoc.cc/help?page_id=65610
