### ISSUE TITLE
使用showdoc账号登录一直提示账号未登录，注册账号也一直显示验证码错误，进入showdoc容器，不能执行sqlite3指令

### ISSUE THREAD

**Issue by zhangjin2294** [star7th/showdoc#411]

**Comment by star7th** [comment]
检查宿主机/showdoc/html下是否有文件，以及是否有权限

**Comment by star7th** [comment]
是/showdoc_data/html

**Comment by zhangjin2294** [comment]
有权限，也有文件，html文件夹里面的文件好像都是容器内部的文件

**Comment by zhangjin2294** [comment]
感觉就像是没保存session一样

**Comment by star7th** [comment]
你是根据哪个教程安装的，给链接看下

**Comment by zhangjin2294** [comment]
我一直使用的命令都是加了sudo的

**Comment by star7th** [comment]
进docker里面，看看它目录的/var/www/html能否新建文件。这个目录就是映射到宿主机的

**Comment by zhangjin2294** [comment]
可以创建，而且在主机上的对应文件夹上也能够看到

**Comment by star7th** [comment]
截图说明吧。
我印象中showdoc是没有账号未登录这个提示的

**Comment by zhangjin2294** [comment]
![Uploading QQ图片20181218163749.png…]()

**Comment by star7th** [comment]
图片看不到

**Comment by zhangjin2294** [comment]
![2](https://user-images.githubusercontent.com/43107865/50141920-b17b7280-02e3-11e9-8fa7-0e92878e7629.png)
![3](https://user-images.githubusercontent.com/43107865/50141921-b17b7280-02e3-11e9-9ad6-52f750743bad.png)

**Comment by zhangjin2294** [comment]
![qq 20181218163749](https://user-images.githubusercontent.com/43107865/50141949-c48e4280-02e3-11e9-8cc3-90f1ffee104a.png)

**Comment by star7th** [comment]
单从这几个图看不出什么。
不浪费时间了，你用服务器安装吧。本地环境不知道做了什么限制

**Comment by zhangjin2294** [comment]
前面两张是验证码的问题，后面一张是用showdoc登录出现的问题

**Comment by zhangjin2294** [comment]
我就是用服务器安装的，还不是本机的虚拟机

**Comment by star7th** [comment]
提供下访问地址我去看看

**Comment by zhangjin2294** [comment]
就是不知道服务器做了什么限制，诡异得很，还有，在容器内部应该也启动了sqlite的进程的吧，但是我没有找到，也不能运行sqlite3的命令

**Comment by star7th** [comment]
sqlite没有单独进程。sqlite命令行工具没有安装。这是正常现象。由php进程调用sqlite

**Comment by zhangjin2294** [comment]
你那边不能访问的

**Comment by star7th** [comment]
我只能说信息不足无法判断问题。
showdoc被很多人在不同服务器上安装过，不会存在普通性的安装失败问题。

**Comment by zhangjin2294** [comment]
这个我也不知道了，查看运行日志，也没看到什么报错或者有用的信息

**Comment by 2xx4ever** [comment]
> 这个我也不知道了，查看运行日志，也没看到什么报错或者有用的信息

我也遇到过验证码一直报错的问题，当时原因是修改了`php-fpm`的默认`user`和`group`，改回默认的`apache`，并将代码目录授权给`apache`即可，检查一下是否这个原因。

**Comment by yangwen7983** [comment]
这个问题我遇到，我也是docker部署的，系统空间用光了会出现此种现象
