### ISSUE TITLE
源码里边的数据库应该有损坏

### ISSUE THREAD

**Issue by cntlis** [star7th/showdoc#412]
SQLSTATE[HY000]: General error: 11 database disk image is malformed
很多涉及到数据库的接口，都提示这个错误

**Comment by star7th** [comment]
1，确保服务器的环境没问题，尽量使用官方docker环境。其他环境需要自己去解决。
2，如果是用ftp传输文件，请使用二进制模式上传以免损坏数据库

EchoYu <notifications@github.com>于2018年12月18日 周二下午5:25写道：

**Comment by cntlis** [comment]
还真的是上传问题，万分感谢啊
