### ISSUE TITLE
建议新增一个浮动目录

### ISSUE THREAD

**Issue by cntlis** [star7th/showdoc#413]
类似
https://www.layui.com/doc/base/infrastructure.html
这个页面，右侧里边，有针对当前的标题，设置的浮动目录层，可以快速的跳转，感觉很方便

**Comment by star7th** [comment]
以后看下

EchoYu <notifications@github.com> 于2018年12月19日周三 下午9:29写道：

**Comment by cntlis** [comment]
> 当前官方增加了一个更新：你在编辑的时候使用markddown的TOC标签，保存后，你在项目页面就可以看到右边有个导航

使用了TOC标签，但是只在头部有标题，没有显示浮动标签，然后看了一下github，最近没有提交代码的记录，是不是还没有提交

**Comment by star7th** [comment]
我忘记编译打包代码了。现在好了

EchoYu <notifications@github.com> 于2019年4月9日周二 下午11:39写道：
