### ISSUE TITLE
在线版和开源版能不能互相迁移

### ISSUE THREAD

**Issue by yangypDeveloper** [star7th/showdoc#417]
有些项目在线版里面,如果要迁移到开源版需要怎么做?
是导出word 然后用开放 API 更新吗? 还是一个一个新建复制粘贴?
> 突然发现我怎么老是有奇奇怪怪的问题,是我的打开方式不对吗?主流的接口管理是在线编辑呢?还是自动API生成呢?用来写非API的多不多?

**Comment by star7th** [comment]
只能手动复制，其他的办法都是更费劲的方式。

yangyanpeng <notifications@github.com>于2018年12月25日 周二下午12:01写道：
