### ISSUE TITLE
项目迁移问题，项目内图片无法显示

### ISSUE THREAD

**Issue by zc2953787433** [star7th/showdoc#418]
按照官方的帮助文档迁移之后，发现图片展示不了，该复制的文件夹啊权限啊也都做了，进到文档里一看，发现图片地址用的绝对地址，所以只是建议，在编辑文档的时候，里面的地址能不能改成相对地址，这样就可以完美迁移了

**Comment by star7th** [comment]
1，showdoc所用的开源编辑器https://pandao.github.io/editor.md/ 对相对路径不够友好。它必须是相对根目录的路径，而不是相对当前目录。这样的功能还不如直接来绝对路径。
2，绝对路径方便导出word后还可以查看图片。
