### ISSUE TITLE
[建议] 可以考虑增加移动端体验友好度

### ISSUE THREAD

**Issue by elinxer** [star7th/showdoc#419]
[建议] 可以考虑增加移动端体验友好度, 目前在手机下查看发现可以看,但体验不是很多,隐藏了部分

**Comment by star7th** [comment]
注意是发现移动端的编辑需求比较少，所以只做阅读功能。
以后如果支持移动端的话，可能不是修改原有，而是新起一个独立的小程序

zhiteer <notifications@github.com> 于2018年12月25日周二 下午5:10写道：

**Comment by elinxer** [comment]
good!
