### ISSUE TITLE
JSON转参数表格 怎么不能点击

### ISSUE THREAD

**Issue by CinderellaCiCi** [star7th/showdoc#42]
更新了下文件，多出了【JSON转参数表格】的按钮，点击没反应；
是掉了什么东西呢？
文件刚全部替换了一遍，是数据库加了内容么，麻烦指点下

**Comment by star7th** [comment]
数据库没改；尝试更新缓存；浏览器缓存也是缓存

**Comment by CinderellaCiCi** [comment]
OK了，搞糊涂了，我还以为我已经更新过缓存了。

**Comment by xlf531533465** [comment]
![Uploading QQ截图20160711184713.png…]()
建议增加对象折叠功能，如图，导入json后，1,2,3级关系出来了。不过最后那几个字段是输入整个json串的，而不是属于steps对象的。最后能加个折叠按钮以区分。
