### ISSUE TITLE
不登录也可以看，权限有控制有严重漏洞

### ISSUE THREAD

**Issue by jorny001** [star7th/showdoc#421]
比如我分享一个项目的连接地址给其他人，不用登录就可以查看，权限控制不对

**Comment by star7th** [comment]
设计本如此。不想公开就设置访问密码。

jorny <notifications@github.com>于2018年12月29日 周六下午2:47写道：

**Comment by jorny001** [comment]
我设置了访问密码，也没有让我输入密码

**Comment by star7th** [comment]
你换个电脑换个浏览器访问试试

jorny <notifications@github.com>于2018年12月29日 周六下午2:53写道：

**Comment by star7th** [comment]
他注册的时候会提示不能注册的

jorny <notifications@github.com>于2018年12月29日 周六下午3:22写道：
