### ISSUE TITLE
ldap 报错

### ISSUE THREAD

**Issue by ZuoGuocai** [star7th/showdoc#424]
公司使用的微软AD ，站点设置填写ldap,保存报错Can't bind to LDAP server，ldap bind dn 填的CN=IT,OU=Public,OU=mycompany,DC=mycompany,DC=work

**Comment by star7th** [comment]
因为是在你内网，我是无法调试的。所以我也难知道原因。目前官方在表单输入框给出了示例。同时留一下ip和showdoc服务器之间的网络是否真的能连接上。
目前来看，没有听过连接不上的反馈，所以代码应该没问题。

Even <notifications@github.com> 于2019年1月3日周四 下午4:48写道：
