### ISSUE TITLE
手动升级后，原数据项目丢失

### ISSUE THREAD

**Issue by xuzhibin** [star7th/showdoc#425]
手动升级后，按文档说，数据库覆盖，打开升级链接，显示٩(•̤̀ᵕ•̤́๑)ᵒᵏᵎᵎᵎᵎ，但是登录后原数据项目丢失，完全就是全新的。

**Comment by star7th** [comment]
截图说明下


xuzhibin <notifications@github.com>于2019年1月7日 周一下午12:44写道：

**Comment by xuzhibin** [comment]
<img width="795" alt="showdoc1" src="https://user-images.githubusercontent.com/1763232/50749830-91a0f400-127c-11e9-83e0-395bc51bb4da.png">
升级前有这些项目，升级后全部都没了。但是升级后原来的用户倒是可以登录，就是项目数据全都没了

**Comment by star7th** [comment]
升级脚本再执行一遍，截图

xuzhibin <notifications@github.com>于2019年1月7日 周一下午1:04写道：

**Comment by star7th** [comment]
同时确认数据库文件可以被写入

Chen Xing <xing7th@gmail.com>于2019年1月7日 周一下午1:05写道：

**Comment by xuzhibin** [comment]
之前试过几次都不行，刚才再试了一次，又可以了，可以看到以前的项目
