### ISSUE TITLE
ldap 用户名唯一性

### ISSUE THREAD

**Issue by dadasu** [star7th/showdoc#428]
目前LDAP 接入读取显示的用户名是 LDAP 的"sn"、"givenName"字段拼接，建议可以加上 "User Name"的字段显示，然后使用 "User Name"作为登录的唯一ID ，姓名("sn"、"givenName"字段)可能存在同名的情况；

**Comment by star7th** [comment]
ldap只作为一个简单的附属功能存在，不打算解决极端情况下存在的问题。因为已经覆盖大部分场景。
像你说的情况，我要搭建环境做各种测试，更改后还要考虑如何做向后兼容。时间有限，就不为小众需求这样折腾了。
