### ISSUE TITLE
图片上传出现异常

### ISSUE THREAD

**Issue by CinderellaCiCi** [star7th/showdoc#43]
我今天更新了代码，发现图片上传坏掉了，没有生成链接，点击确定窗口就关闭了，不知道什么原因，能帮看下不？
![](http://ww2.sinaimg.cn/large/5ebd877egw1f215hyvu18g20ul0jbe1e.gif)

看了你的网站是可以的，但是我这没发现是什么情况，文件全部赋权了，缓存也刷新了。。

**Comment by star7th** [comment]
右键审核原素，看看js报错什么

**Comment by CinderellaCiCi** [comment]
报错如下：
![](http://ww2.sinaimg.cn/large/5ebd877egw1f2ce2xj66lj20j804cmxi.jpg)

**Comment by CinderellaCiCi** [comment]
Uncaught TypeError: Cannot set property 'imageDialog' of undefinedfactory
@ image-dialog.js:18(anonymous function) 
@ image-dialog.js:215(anonymous function) 
@ image-dialog.js:218

**Comment by CinderellaCiCi** [comment]
Uncaught SyntaxError: Unexpected token : 
uploadIframe.onload @ image-dialog.js:161

**Comment by CinderellaCiCi** [comment]
我把这个文件找出来单独和github上的文件比了下，是一模一样的。
Public/editor.md/plugins/image-dialog/image-dialog.js

**Comment by star7th** [comment]
更新代码、更新缓存、重启服务器

**Comment by CinderellaCiCi** [comment]
已  更新代码、更新缓存和重启服务器，还是这样。。
:100:

**Comment by star7th** [comment]
存放图片文件的Public/Uploads 有可写权限吗

**Comment by CinderellaCiCi** [comment]
好像上传图片是用的另外的用户名呢，我之前权限赋的755，改成777就可以成功上传了。(-__-)b

**Comment by phpyii** [comment]
@CinderellaCiCi 你这个gif图片怎么录制的

**Comment by CinderellaCiCi** [comment]
@phpyii http://www.chinatesters.com/?p=217

**Comment by never615** [comment]
同样的错和表现,
是填写了七牛配置后会出现这个问题,不用七牛正常.
七牛配置:(这个七牛空间在其他项目中使用正常),不知道配置有没有问题
```
 'UPLOAD_SITEIMG_QINIU' => array(
                    'maxSize' => 5 * 1024 * 1024,//文件大小
                    'rootPath' => './wiki',
                    'saveName' => array ('uniqid', ''),
                    'driver' => 'Qiniu',
                    'driverConfig' => array (
                            'secrectKey' => 'xxx',
                            'accessKey' => 'xxx',
                            'domain' => 'https://file.mall.mall-to.com',
                            'bucket' => 'mall',
                        )
                    ),
```

**Comment by star7th** [comment]
@never615 更新缓存

**Comment by never615** [comment]
@star7th 
![screen shot 2017-06-07 at 6 56 16 pm](https://user-images.githubusercontent.com/9959927/26911000-29cff292-4c3d-11e7-96be-df2821b4938b.png)
控制台一直报这个但是不影响使用.
然后找到七牛不能使用的原因了....
因为七牛不同区域不同空间的上传地址不一样,建议上传地址改成可配置的...
https://developer.qiniu.com/kodo/manual/1671/region-endpoint
还有代码中默认会给七牛的访问域名前拼接http://,如下`$url = "http://{$this->domain}/{$key}"`(QiniuStorage类中).但是domain的访问域名可能是https的,建议在domain上填写,或者代码中判断一下,已经存在协议头就不要拼接了.
