### ISSUE TITLE
关于在页面编辑的表格中使用管道符的问题

### ISSUE THREAD

**Issue by 2xx4ever** [star7th/showdoc#430]
尝试在页面编辑器中插入表格，表格内容存在管道符`|`，
![tim 20190117172953](https://user-images.githubusercontent.com/13996151/51308879-1f02f600-1a7e-11e9-8e35-bf8c6e6cc131.jpg)

转义成 `&#124;`后预览显示正常，
![tim 20190117173009](https://user-images.githubusercontent.com/13996151/51308884-24604080-1a7e-11e9-9ea2-65ccb07eeb37.jpg)

但实际页面依然会做为分隔符。
![tim 20190117173024](https://user-images.githubusercontent.com/13996151/51308893-27f3c780-1a7e-11e9-8545-a6e9787eebd1.jpg)

**Comment by star7th** [comment]
表格中不支持此符号。

404NotFound <notifications@github.com>于2019年1月17日 周四下午5:35写道：
