### ISSUE TITLE
page_content字段不支持换行

### ISSUE THREAD

**Issue by asingoro** [star7th/showdoc#432]
使用开放api创建数据字典时，page_content字段不支持换行，使用<br/>后，没有预览功能

**Comment by star7th** [comment]
要用转义字符。

asingoro <notifications@github.com>于2019年1月19日 周六下午1:17写道：

**Comment by asingoro** [comment]
您好，请问具体的转义字符是 “ &#10;  ”吗，还是其他的了。
非常感谢！

**Comment by star7th** [comment]
自己在编辑器编辑一下，然后提交，然后看一下网络请求发送的是什么内容。

asingoro <notifications@github.com> 于2019年1月22日周二 上午11:59写道：

> 您好，请问具体的转义字符是 “ &#10; ”吗，还是其他的了。
> 非常感谢！
>
