### ISSUE TITLE
文档访问权限

### ISSUE THREAD

**Issue by xixigou** [star7th/showdoc#433]
作者，你好。
请问showdoc目前是否有权限管理，即：若不是该项目中的成员是不能查看文档的？
现在的情况是：项目设置了团队成员，但是若直接访问文档接口地址也是可以不要登录就可以查看，设置了项目密码也无效果

**Comment by star7th** [comment]
设置了访问密码是有效的。不信换一台电脑试试。

万军 <notifications@github.com>于2019年1月20日 周日下午3:19写道：
