### ISSUE TITLE
[BUG]when i add the member at second  time,it will be happen

### ISSUE THREAD

**Issue by yehaia1** [star7th/showdoc#434]
## Version
star7th/showdoc:latest
## Environment
Docker version 18.09.0, build 4d60db4
## Steps to reproduce
* when i add the member at second  time,dialog will cover up dropdown
当我添加成员的时候，添加第二个就会出现dialog把dropdown挡住，如下图
![step](https://vgy.me/z5KOCA.gif)

**Comment by star7th** [comment]
The latest edition has solved this problem.
