### ISSUE TITLE
部署后加载部分资源文件失败

### ISSUE THREAD

**Issue by formzs** [star7th/showdoc#435]
GET http://translate.google.com/gen204?nca=te_li&client=te_lib&logld=vTE_20181015_01 net::ERR_CONNECTION_TIMED_OUT

**Comment by formzs** [comment]
> 我没有印象showdoc什么时候加载过这个链接。检查下是不是自己装的浏览器扩展发起的请求。

是浏览器扩展得锅没错了，感谢大佬及时回复，鞠躬！

**Comment by xiuxiuyifan** [comment]
那这个错误不用管吗？？？怎么解决的？

**Comment by star7th** [comment]
@xiuxiuyifan 你让我很无语啊。都已经说了是浏览器扩展发起的请求了。怎么解决这个不是很显然的吗？要么不管，要么关掉浏览器扩展
