### ISSUE TITLE
编辑时，勾选无法保存

### ISSUE THREAD

**Issue by Sun-FreePort** [star7th/showdoc#437]
- [ ] 嘤嘤嘤

上述，在编辑页面的视图中勾选，不会保存勾选。

这算 BUG 吗？不算的话，不太理解这种操作的行为。

~推荐感受一下这个编辑器：[StackEdit](https://stackedit.io/app#)~ Github 本身就可以保存

**Comment by star7th** [comment]
正常的mardown语法是不会保存的。githun做了定制化处理但这个不是业界通用的解决方式
