### ISSUE TITLE
这个bug也太大了吧？最新的都不能直接访问项目？一片空白

### ISSUE THREAD

**Issue by woytu** [star7th/showdoc#438]
![image](https://user-images.githubusercontent.com/30252550/51803367-4aac8a00-228f-11e9-804a-cd23e5387a1b.png)

**Comment by star7th** [comment]
自己安装的环境问题就别觉得总是别人的责任别人的bug。
尝试通过官方定制脚本安装https://www.showdoc.cc/help?page_id=828455960655160
其他方式的安装，自己要为自己的安装步骤负责任。

**Comment by woytu** [comment]
> 自己安装的环境问题就别觉得总是别人的责任别人的bug。
> 尝试通过官方定制脚本安装https://www.showdoc.cc/help?page_id=828455960655160
> 其他方式的安装，自己要为自己的安装步骤负责任。

## 哈，您在没有确认的情况下就这样回复吗？就这样的关闭了bug？
## 本人在没有任何不能确认的情况下是不会提交bug的，本人也是程序员深知bug追溯的重要性！
## 本人提交该bug有以下条件：
### 1、我不是小白，我尝试了自动安装脚本、docker手动安装、Nginx+PHP环境搭建安装都有此问题！
### 2、在这次弄showdoc之前我线上服务器一直都是好好的，在2019.1.28上午突然自己出现打开项目文档出现白屏无任何报错！且是自动脚本安装的！然后我就尝试备份重新安装，最后就出现此bug！
### 3、在尝试重新安装出现问题后，我首先就考虑环境问题！然后就用另一台的全新服务器重试安装也出现bug，我就查找重现问题，最终原因可能是在安装最新版本后把原来的sqllite文件和Uploads文件夹中的文件覆盖到新安装的文件夹中出现此问题！

**Comment by star7th** [comment]
我自己安装过，没发现此问题。且以前也没发现过此问题，且那么多人安装也没反馈此问题。

“突然出现问题且无任何报错”，这个是极度可能是有人改动了服务器环境，或者其他软件引起环境变动。showdoc不会通过网络来改什么。

重新安装的那个出问题，检查下你的文件权限。特别是sqlite的权限。

如果是手动升级，是需要自己手动访问升级url以升级数据库结构。用浏览器访问http://xxx.com/showdoc/index.php?s=/home/update/db （请将网址更改为你服务器域名或ip）

**Comment by woytu** [comment]
> 我自己安装过，没发现此问题。且以前也没发现过此问题，且那么多人安装也没反馈此问题。
> 
> “突然出现问题且无任何报错”，这个是极度可能是有人改动了服务器环境，或者其他软件引起环境变动。showdoc不会通过网络来改什么。
> 
> 重新安装的那个出问题，检查下你的文件权限。特别是sqlite的权限。
> 
> 如果是手动升级，是需要自己手动访问升级url以升级数据库结构。用浏览器访问http://xxx.com/showdoc/index.php?s=/home/update/db （请将网址更改为你服务器域名或ip）

### 我都尝试过，服务器中没有其他软件，因为服务器配置只有1h1g配置，而且也没有其他人有权限修改！
### 现在可以用，我现在的解决方法是直接安装的Nginx+PHP环境然后把以前用自动脚本安装的showdoc_doc文件夹复制到网站的目录下就没问题了！但是如果用最新版本就会出问题，这是昨晚我弄了好几个小时重现出来的结果！

**Comment by star7th** [comment]
我感觉很可能是数据库结构没有升级的缘故。提供下项目链接看下吧

**Comment by woytu** [comment]
> 我感觉很可能是数据库结构没有升级的缘故。提供下项目链接看下吧

https://doc.woetu.com

**Comment by star7th** [comment]
你这个是正常的版本，看不出什么的。
要那个异常的版本才能看出

**Comment by woytu** [comment]
如果数据库结构修改过，那么很有可能是数据库的结构问题，因为我Nginx+PHP环境下安装最新的版本后把原来的sqllite文件和Uploads文件夹中的文件覆盖到新安装的文件夹中出现此问题

**Comment by woytu** [comment]
### 已经重现出来这是其中一个项目https://doc.zd966.com/web/#/3

**Comment by star7th** [comment]
检查下为何https://doc.zd966.com/server/index.php?s=/api/item/info 这个url无法访问
我自己安装的是可以访问的

**Comment by star7th** [comment]
真是浪费时间，自己都没看准文档，而且我上面还专门讲了一次，都还是没做。
都叫了访问 /index.php?s=/home/update/db  执行数据结构的升级，就是不听。
现在我访问了该url，已经可以了
![image](https://user-images.githubusercontent.com/2200494/51815911-0a84f000-22ff-11e9-9ca6-32b737591411.png)
