### ISSUE TITLE
导出的doc文件中图片不展示

### ISSUE THREAD

**Issue by jzhw** [star7th/showdoc#440]
不知道是不是因为图片比较多的原因？选择导出其中一个小目录（只包含几个页面，每个页面中几个图片）也有问题。

**Comment by star7th** [comment]
导出的图片只是个url，如果无法访问网络则不显示。
暂时未能做到把图片数据全压在一起，太大。

jzhw <notifications@github.com>于2019年1月28日 周一下午5:27写道：
