### ISSUE TITLE
showdoc有考虑oauth授权登录吗

### ISSUE THREAD

**Issue by wuwu20048** [star7th/showdoc#442]
想做一个公司gitlab账号授权直接登陆showdoc的功能，不知道是否支持？有什么方案不

**Comment by star7th** [comment]
官方不支持也没有方案。可以自行看代码。第三方的话目前只支持ladp登录

xfgg <notifications@github.com> 于2019年1月29日周二 下午3:34写道：

**Comment by wadegoit** [comment]
@star7th 后续有考虑第三方认证授权么

**Comment by mengdodo** [comment]
讲道理这个很有必要

**Comment by star7th** [comment]
新版可以支持自己配置oauth2登录。在管理后台的集成登录菜单可以看到。

**Comment by wuwu20048** [comment]
你好，是从哪个版本开始支持的？

**Comment by star7th** [comment]
忘记是从哪个版本开始的了。反正升级到最新版就行
