### ISSUE TITLE
showdoc_db.sh 在哪里执行

### ISSUE THREAD

**Issue by ancientelves** [star7th/showdoc#444]
我在任意服务器上执行：wget https://www.showdoc.cc/script/showdoc_db.sh 
下载了showdoc_db.sh  。修改里面的配置参数，但是执行结果失败，原因：mysql: command not found

想知道这个脚本必须要mysql所在服务器执行吗？

**Comment by star7th** [comment]
脚本是调用mysql服务的。
在执行的机器上安装下mysql.之后它可以链接远程机器

**Comment by ancientelves** [comment]
@star7th thanks
