### ISSUE TITLE
请问下附件上传功能在哪里体现

### ISSUE THREAD

**Issue by howess** [star7th/showdoc#446]
请问下附件上传功能在哪里体现

**Comment by star7th** [comment]
![image](https://user-images.githubusercontent.com/2200494/52624797-84fe6400-2eea-11e9-87cf-25a71a0f74de.png)

**Comment by howess** [comment]
![image](https://user-images.githubusercontent.com/10075418/52624852-aa8b6d80-2eea-11e9-8095-037748dec57c.png)

**Comment by star7th** [comment]
开源版的支持了附件上传。
官方由于担心资源滥用暂时没开放此功能。后面会视情况而定

**Comment by howess** [comment]
好的，谢谢
