### ISSUE TITLE
文档默认存放位置在哪里？

### ISSUE THREAD

**Issue by tzkang** [star7th/showdoc#447]
你好，我是通过`Nginx+PHP`的方式在自己的Centos6.8服务器上部署showdoc，但是目前有个疑问就是，我在前端创建的各种目录、文档等文件是存放来服务器的哪个目录下的呢？
我需要了解这个，方便实际应用中，对重要的项目文档做备份。

**Comment by star7th** [comment]
-

   showdoc使用sqlite数据库。数据库文件是安装目录下的Sqlite/showdoc.db.php。你可以网络搜索如何在命令行中使用
   sqlite数据库.或者使用SQLiteStudio等可视化工具


   -


tzkang <notifications@github.com> 于2019年2月14日周四 下午3:04写道：

**Comment by star7th** [comment]
粗暴点的方式就是把整个目录复制一遍就是备份了

Chen Xing <xing7th@gmail.com> 于2019年2月14日周四 下午3:05写道：

**Comment by tzkang** [comment]
好的，谢谢。 刚才我再后台尝试把默认的管理用户`showdoc`删除了，删除成功，但是遇到的问题是，我如何再创建新的管理用户呢？

**Comment by star7th** [comment]
自己注册一个showdoc用户。然后进数据把groupid字段提升为1 .
尽量不做这种匪夷所思的事。我也不想说了。

tzkang <notifications@github.com> 于2019年2月14日周四 下午5:24写道：

**Comment by tzkang** [comment]
解释一下：尝试这样做的一个需求是，我需要将管理账户名从showdoc变成其他的，比如公司或者个人习惯的用户名，也不是毫无缘由的一个操作。
另外groupid字段升级为1是后台哪里修改？还是前端页面哪个板块呢？

**Comment by star7th** [comment]
如果我是你，我肯定是先想办法新增一个管理员用户然后再删除原有默认管理员。
看来下次要禁止用户这种自杀式操作才行。

全部重新安装来过吧。

tzkang <notifications@github.com>于2019年2月14日 周四下午6:50写道：

**Comment by tzkang** [comment]
当时的一个“自以为是”的认知是，我先新建一个普通用户，然后我再删除了showdoc管理用户，我以为我可以后台将新建的那个普通用户升级为管理用户，或者不能的话，我删除管理用户的时候，会提示我该操作的后果。 但是删除的时候没有这种提示，就“自然”的以为风险可控。

**Comment by tzkang** [comment]
你开始说的将数据的groupid升级为1，就能将一个用户变为管理用户？  你最近说的“全部重新安装来过吧”意思是我现在得重新安装部署一下吗？

**Comment by star7th** [comment]
进数据库，把你新增的那个用户权限改为1
怎么操作数据库，自己探索下

tzkang <notifications@github.com>于2019年2月14日 周四下午7:03写道：

**Comment by tzkang** [comment]
嗯嗯，好的。

**Comment by tzkang** [comment]
现在还遇到一点问题，重新部署showdoc后有了默认的showdoc管理员账户，但是该管理员的注册时间似乎是有问题的，如图：
![image](https://user-images.githubusercontent.com/22320884/52795888-b07d7c00-30ad-11e9-8487-d7ab194ce6a3.png)
而查看服务器端时间是正常的，请问这个是哪里设置有问题吗？

**Comment by star7th** [comment]
设计如此

tzkang <notifications@github.com> 于2019年2月14日周四 下午11:10写道：

**Comment by tzkang** [comment]
哦，好吧。

**Comment by tzkang** [comment]
今早再次输入IP地址的时候，web页面没有正常显示showdoc的页面，而是apache的页面，通过重新部署（将showdoc文件导入/var/www/html下），然后在浏览器端输入`IP/install`也没能进入正常的安装页面。
![image](https://user-images.githubusercontent.com/22320884/52827606-7b4e4980-3100-11e9-93ff-a49883bfa622.png)
请问如何解决？

**Comment by star7th** [comment]
建议使用官方推荐的安装方式，其他方式，由于服务器环境差异很大，可能需要自己多动手排查问题。
https://www.showdoc.cc/help?page_id=828455960655160

tzkang <notifications@github.com> 于2019年2月15日周五 上午9:03写道：

**Comment by tzkang** [comment]
由于我的是内网环境，无法连接互联网，所以自动脚本安装是没法顺利安装的。  只能通过手动

**Comment by star7th** [comment]
服务器环境差异太大了，没办法一一排查环境。对这种非showdoc自身的问题，我一般建议用户自行解决。

tzkang <notifications@github.com> 于2019年2月15日周五 上午9:08写道：

**Comment by tzkang** [comment]
嗯嗯，好的，谢谢。
