### ISSUE TITLE
数据库变成0kb

### ISSUE THREAD

**Issue by CZFork** [star7th/showdoc#453]
有时候莫名的数据库变成0kb，上次是打开电脑的时候，今天电脑没电时，浏览器卡了一下，然后数据库就变成0kb了，

**Comment by star7th** [comment]
这个跟showdoc完全没关系，跟你的电脑环境有关系。不建议安装在你的电脑本地，找台服务器吧

CZFork <notifications@github.com>于2019年2月24日 周日下午8:58写道：

**Comment by CZFork** [comment]
Ծ‸Ծ，这样啊，谢谢
