### ISSUE TITLE
Redirect to porn site (in guide)

### ISSUE THREAD

**Issue by svliantiss** [star7th/showdoc#454]
https://www.showdoc.cc/help-en?page_id=32344
Obviously, it's not meant to be clicked but the hyperlinks that include https://xxx.com/* redirect to a porn site. Not very user-friendly and NSFW.

Instead, use something like https://your-domain.com/* or https://foo.com/*.

I also found the guide in its entirety not to be really beginner-friendly.

**Comment by star7th** [comment]
It has been corrected.Thank you for reminding me.
