### ISSUE TITLE
Please install php-gd

### ISSUE THREAD

**Issue by svliantiss** [star7th/showdoc#455]
I have php-gd installed but it won't recognize it.

I even reinstalled it and tested it on another machine (Raspberian Jessie) and it gave the same error.

**Comment by star7th** [comment]
Do you restart your php or apache ?
If nginx .please try 'service php-frm restart'
If apache ,please try 'service httpd restart'
And you can run 'php -m ' to check if the php-gd installed

**Comment by svliantiss** [comment]
It does not seem to be in there, but I am sure I installed it.
I even reinstalled it but it does not seem to get added.
------------------------------------------------------------------------------------------------------------------------------------------------
[svl@svlmanjaro http]$ sudo pacman -S php-gd
resolving dependencies...
error: could not open file /var/lib/pacman/local/bolt-0.7-2/desc: No such file or directory
looking for conflicting packages...

Packages (1) php-gd-7.3.2-1

Total Installed Size:  0,10 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                             [####################################################] 100%
(1/1) checking package integrity                                                           [####################################################] 100%
(1/1) loading package files                                                                [####################################################] 100%
(1/1) checking for file conflicts                                                          [####################################################] 100%
(1/1) checking available disk space                                                        [####################################################] 100%
:: Processing package changes...
(1/1) installing php-gd                                                                    [####################################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
[svl@svlmanjaro http]$ systemctl restart httpd
[svl@svlmanjaro http]$ systemctl restart http
Failed to restart http.service: Unit http.service not found.
[svl@svlmanjaro http]$ php -m
[PHP Modules]
bz2
Core
ctype
curl
date
dom
fileinfo
filter
hash
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
Phar
posix
readline
Reflection
session
SimpleXML
SPL
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]

[svl@svlmanjaro http]$ 
------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by star7th** [comment]
I don't know if you need to add php-gd extension in php.ini

**Comment by star7th** [comment]
If it does not  work ,you can try docker https://www.showdoc.cc/help?page_id=65610  .But it was Chinese becase I am too busy to translation .You can read it with Google translation and just focus on those commands

**Comment by svliantiss** [comment]
For now, I just deployed it on a free google cloud server. I have no idea why it's not installing. It's probably more my pc's fault than anyone else's. 

Sorry for the disturbance.
