### ISSUE TITLE
English login portal typo

### ISSUE THREAD

**Issue by svliantiss** [star7th/showdoc#457]
In the English login portal it says Passwod instead of Password.

++ Where does Showdoc generate these pages I would be happy to solve these typo's myself but I can't find it.

**Comment by star7th** [comment]
It has been repaired now

**Comment by star7th** [comment]
Showdoc frontend uses Vue  https://github.com/vuejs/vue
And the lan js is web_src/static/lang/en.js

**Comment by svliantiss** [comment]
Oke, I will start contributing to Translations for you.


________________________________
