### ISSUE TITLE
Feature Request: Exporting to PDF

### ISSUE THREAD

**Issue by svliantiss** [star7th/showdoc#458]
We would like a feature to directly export the page to PDF, or to .docx correctly.

**Comment by star7th** [comment]
Showdoc now supports exporting word documents, which you can convert into PDF documents using other tools. Exporting PDF from PHP requires a lot of code. Showdoc does not intend to support PDF for the time being.

If you want .docx ，just change the file name .It can be opened compatibly

**Comment by svliantiss** [comment]
Our team will just publish all our feature requests and ideas. If we truly feel the need something is being overlooked we will create a merge with the added functionality ourselves.
