### ISSUE TITLE
Feature Request: oauth2 support

### ISSUE THREAD

**Issue by svliantiss** [star7th/showdoc#459]
oauth2 support for users to verify themselves without creating a user directly, this will save space on the local server when dealing with a lot of users and it will be more secure.

**Comment by star7th** [comment]
Many companies deploy showdoc to their internal network, and they don't need oauth2 very much. So I don't think this function is necessary. Showdoc supports LDAP login on enterprise support

**Comment by svliantiss** [comment]
Our team will just publish all our feature requests and ideas. If we truly feel the need something is being overlooked we will create a merge with the added functionality ourselves.
