### ISSUE TITLE
Feature Request: Universal "Home/Dasboard" button

### ISSUE THREAD

**Issue by svliantiss** [star7th/showdoc#462]
Right now to go back to "Home/Dashboard" you have to remove the last part of the URL, it would be nice to add a universal "Home/Dashboard" button to make the workflow better.

**Comment by star7th** [comment]
The "item/index" play the roles of "Home/Dashboard" . I don't see what you mean

**Comment by star7th** [comment]
I once wrote a Chinese redevelopment document .  https://www.showdoc.cc/help?page_id=1385576954326448
If you want to contribute ,it will be helpful.

**Comment by svliantiss** [comment]
The back button should be to go back one document or back to the last action and a home button should be a simple button always placed in the top left corner to go back to .../showdoc/index AKA "Home/Dashboard". We feel like this would improve the workflow a lot.

**Comment by star7th** [comment]
You can click the left side to switch docs , or click the btn on the top right to go back 

![image](https://user-images.githubusercontent.com/2200494/53930125-1e283100-40cb-11e9-98ca-920f87b1a2fe.png)
