### ISSUE TITLE
关于数据库文件showdoc.db.php的问题

### ISSUE THREAD

**Issue by bluesky335** [star7th/showdoc#465]
为什么数据库文件的后缀名要用.php呢。
在使用FileZilla作为FTP客户端上传下载文件的时候，FileZilla的默认设置，后缀名为php的文件会被当做普通的文本文件处理，导致数据库损坏。
我使用的FileZilla版本：3.41.1

**Comment by star7th** [comment]
如果不这样做的话，用户通过网址访问的时候会把数据库当作附近下载。而命名为php的话会经过服务器解析从而不被下载。

**Comment by bluesky335** [comment]
> 如果不这样做的话，用户通过网址访问的时候会把数据库当作附件下载。而命名为PHP的话会经过服务器解析从而不被下载。

谢谢回复，另外，当一个项目不是由我创建，而是别人创建之后将我加入到团队的，这时候在项目列表里点击项目卡片右上角的设置按钮会连续弹出5次提示框提示“不是项目创建者”

**Comment by star7th** [comment]
非创建者是不能设置项目的。
大概疏忽或者懒而没有屏蔽掉进入项目管理的按钮

**Comment by jagerzhang** [comment]
@star7th 其实也可以不用php后缀的，比如用 .db 后缀，然后nginx规则加上禁止.db的访问即可。
```
location ~* *\.db {
      deny all;
}
```

**Comment by star7th** [comment]
showdoc不能依赖nignx配置。卡住一堆新手。越简单安装越好。

Jager <notifications@github.com> 于2019年4月10日周三 上午10:13写道：

**Comment by jagerzhang** [comment]
@star7th 也是，用什么后缀，对我这边也没任何影响。

**Comment by jagerzhang** [comment]
文档内容这个宽度默认好像很窄，建议弄成百分比自适应的，比如我这边改成了70%：
![image](https://user-images.githubusercontent.com/9711651/55847101-a2fae480-5b7a-11e9-82da-32baae2301cc.png)

![image](https://user-images.githubusercontent.com/9711651/55847048-81016200-5b7a-11e9-9982-716177550941.png)

**Comment by star7th** [comment]
这个问题探讨过很多次了。当前的方式是最能适应各种分辨率的。你的百分比方案，在其它分辨率上阅读体验不一定好

Jager <notifications@github.com>于2019年4月10日 周三上午10:23写道：

**Comment by jagerzhang** [comment]
所以，可以预留一个自定义css的功能，或者更直白的选项方便用户选择平铺铺满还是默认的窄屏啥的，我觉得在办公电脑上看这个内档内容确实太窄了：
![image](https://user-images.githubusercontent.com/9711651/55847355-89a66800-5b7b-11e9-9280-2e468de4ff6a.png)

**Comment by star7th** [comment]
不能。统一宽度有利于保持一致性体验。不统一的话，以后修改样式会很麻烦，要照顾N种不同宽度的情况。

Jager <notifications@github.com> 于2019年4月10日周三 上午10:29写道：

**Comment by jagerzhang** [comment]
![image](https://user-images.githubusercontent.com/9711651/55847466-f883c100-5b7b-11e9-81ba-c0f3b9f0f6c0.png)
貌似没有用到CSS3 @media自适应的写法

**Comment by jagerzhang** [comment]
可以加上@media 几种常见宽度的判断，范围之外的就用你现在这个默认的，范围匹配到了可以用最合适的宽度，这个可以用谷歌浏览器有个自适应调试插件来取得最佳宽度。。。
好吧，我只是建议，反正我也可以自己修改。。。

**Comment by star7th** [comment]
总之这个问题不想讨论了。历史上探讨过很多次，最后折腾还是发现现在的好。
除非你提出一种方案并且自己全面测试过各种分辨率情况，再来说现在的不足吧

Jager <notifications@github.com> 于2019年4月10日周三 上午10:33写道：

**Comment by star7th** [comment]
当前的情况是测试过各种分辨率情况的。你可以按照你的想法改了之后再测试各种分辨率下的情形

Chen Xing <xing7th@gmail.com> 于2019年4月10日周三 上午10:35写道：

**Comment by jagerzhang** [comment]
内容模块貌似是一直固定800px宽度，并没有自适应变化。
回头我写个css3的demo再看看吧。
