### ISSUE TITLE
导入导出问题

### ISSUE THREAD

**Issue by yanqibin** [star7th/showdoc#466]
有没有必要做 直接导出MD 格式的数据？，按项目的目录的结构导出
支持直接通过 MD 导入？ 

还有就是快速修改排序问题？ 

如有觉得有必要的话，我可以提PR

**Comment by star7th** [comment]
个人感觉没必要。本身开源产品，数据库都在自己手里，导出md没什么意义。毕竟md是一个中间产物，不面向最终用户。面向最终用户还是需要一个渲染引擎之类的东西

Joseph <notifications@github.com> 于2019年3月8日周五 上午11:04写道：
