### ISSUE TITLE
代码块不支持空行显示了

### ISSUE THREAD

**Issue by siwen1017** [star7th/showdoc#467]
1、早期的代码块部分，在前端页面好像是可以显示空行的。
2、目前editor.md预览中也是可以显示空行，但在前端页面看起来空行给直接移除了，这样显示的代码块不友好了。

**Comment by star7th** [comment]
截图说明下

siwen1017 <notifications@github.com>于2019年3月9日 周六上午8:48写道：

**Comment by siwen1017** [comment]
![image](https://user-images.githubusercontent.com/13879187/54065214-89ebd480-4258-11e9-9607-20ab5eedf609.png)
![image](https://user-images.githubusercontent.com/13879187/54065217-9a03b400-4258-11e9-89d4-a00628529a34.png)
如上面所示

**Comment by star7th** [comment]
刚上传代码修复了此问题

**Comment by siwen1017** [comment]
愿Showdoc 越来越棒！

**Comment by wixb50** [comment]
您好，该问题好像再次出现了，在官网https://www.showdoc.cc/ 也有？

**Comment by star7th** [comment]
因为隐藏掉行号后空格也去掉了。如果要保留空格行号又出来了。真是两难。有空再看下。

wixb50 <notifications@github.com>于2020年3月17日 周二上午8:51写道：

**Comment by wixb50** [comment]
好的多谢，是否有可以打开行号显示的开关？个人觉得显示行号也关系不大

**Comment by star7th** [comment]
不会专门为此设置个开关。后面再看怎么处理吧

wixb50 <notifications@github.com> 于2020年3月17日周二 上午9:12写道：

**Comment by wixb50** [comment]
好的，多谢，愿Showdoc 越来越好！
