### ISSUE TITLE
Feature Request: Drag and Drop Upload

### ISSUE THREAD

**Issue by svliantiss** [star7th/showdoc#468]
Drag and Drop uploading of other files for downloading, currently we're swapping all our old document over to markdown but it would be much easier if you could upload .pdf .excel and .doc(x) files and maybe even preview them via the browser (or just downloading the files would be fine as well.

**Comment by star7th** [comment]
Thank you for your contribution.
You can see attachment button when you edit a page  , where you can upload file .
And I will make a drag and drop area later
