### ISSUE TITLE
希望可以增加查看某用户的所有项目的功能

### ISSUE THREAD

**Issue by SmallerPig** [star7th/showdoc#47]
自己写的话也可以，但还是希望原作者提供该功能。
这样在同一个人编写多个项目的时候就不需要分享多个url给其他用户，只需要将自己的主页分享出去就可以。

**Comment by star7th** [comment]
但如果这个用户有些项目是不打算分享出去的，那主页岂不是暴露了所有项目？如果不是非常多项目，还是建议分享几个链接比较好

**Comment by star7th** [comment]
也许我可以考虑增加一个分享，分享该用户的所有公开项目

**Comment by star7th** [comment]
再认真思考了下，如果做“该用户的所有公开项目”功能，则容易被人枚举uid来获取所有用户的项目信息。有些人他设置项目为公开是为了方便部分点击链接就可以看，但他并不想被暴露。至少不想暴露项目跟所有者之间的对应关系。

**Comment by SmallerPig** [comment]
不同意你的观点。
---
- 如果怕被使用遍历uid的方法被穷举的所有公开项目的话，那么即使现在也可以遍历整个“项目”的id来把所有公开项目给遍历出来。
- 至于不想暴露项目所有者跟项目的对应的关系这点就更不是问题了，一般我们在网上写博客或者写的开源代码都会标上作者，为了的就是希望别人知道这是我写的，怕就怕别人不知道原作者是谁。现在度娘上搜出来的很多复制粘贴的文章对原作者来说是多么希望能给他们一个原文链接啊。

**Comment by star7th** [comment]
已经增加了分享个人主页功能。访客可在用户个人主页看到该用户的所有公开项目。
在你自己的用户主页，点击右上角的按钮便可以看到“分享主页”按钮

**Comment by CinderellaCiCi** [comment]
新代码部署后，网站首页thinkphp报错，分享个人主页时链接出不来，不知道是哪出了问题呢？
![](http://ww4.sinaimg.cn/large/5ebd877egw1f2slf39i9ej216j0hzac4.jpg)
![](http://ww2.sinaimg.cn/large/5ebd877egw1f2slfzhc9xj20md0c53z8.jpg)

**Comment by SmallerPig** [comment]
@CinderellaCiCi 打开调试模式，看看具体报错原因！

**Comment by star7th** [comment]
配置文件也要更新的

**Comment by CinderellaCiCi** [comment]
搞定了。但是分享的主页地址打开又出错了。。。〒_〒
![](http://ww4.sinaimg.cn/large/5ebd877egw1f2sw1f3fzrj216c0gjac0.jpg)

**Comment by CinderellaCiCi** [comment]
ok了。。。
把runtime整个删除更新了下就好了。。
