### ISSUE TITLE
关于显示页面和导出Word格式的一些建议

### ISSUE THREAD

**Issue by xingdaos** [star7th/showdoc#474]
1. 建议为显示页面添加导航栏→【这样对于长文档而言方便快速的定位到需要的章节】；
   * 现在显示情况：
![image](https://user-images.githubusercontent.com/33388842/54080306-c803f980-4327-11e9-9b7f-d08dbd62b723.png)
   * 建议显示情况：
![image](https://user-images.githubusercontent.com/33388842/54080295-9c810f00-4327-11e9-9f4c-bf252f7b7c17.png)
2. 建议为显示页面添加序号→【因为单纯的标题只是有大小上的差别，不易区分】；
   * 现在显示情况：
![image](https://user-images.githubusercontent.com/33388842/54080180-48752b00-4325-11e9-8b4b-52575ee529ef.png)
   * 建议显示情况：
![image](https://user-images.githubusercontent.com/33388842/54080268-f9c89080-4326-11e9-80f2-26d7c694f925.png) 
3. 建议导出的word，以页面名称为主标题，然后H1为一级标题，H2为二级标题→【这样更符合正规文档格式】
   * 测试页面：
![image](https://user-images.githubusercontent.com/33388842/54080200-a99cfe80-4325-11e9-97eb-ac119f57106b.png)
   * 现在导出情况：
![image](https://user-images.githubusercontent.com/33388842/54080206-d3eebc00-4325-11e9-9304-2b13d6d4bf61.png)
   * 建议导出情况：
![image](https://user-images.githubusercontent.com/33388842/54080246-7eff7580-4326-11e9-9df8-24c45d698461.png)

**Comment by star7th** [comment]
我后面有时间再优化下

**Comment by windsgone** [comment]
第一个建议很实用。

**Comment by xingdaos** [comment]
> 我后面有时间再优化下

好的，非常感谢

**Comment by star7th** [comment]
1，当前官方增加个一个更新：你在编辑的时候使用markddown的TOC标签，保存后，你在项目页面就可以看到右边有个导航
2，你说的序号问题，最好人为添加序号或者使用markdown自身的列表语法。showdoc不宜强行加序号。
3，我认真研究了下导出的word的格式。其实像你这种是很难做好的。你在页面内容中指定标题层级关系，对单层页面来说可能还好。但多层目录的文档来讲，你这种层级关系会跟项目目录层级关系搞乱。
。所以暂时就不考虑更改word导出了。

**Comment by xingdaos** [comment]
收到,多谢反馈.
________________________________
发件人: star7th <notifications@github.com>
发送时间: 2019年4月15日 9:32
收件人: star7th/showdoc
抄送: xingdaosource; Author
主题: Re: [star7th/showdoc] 关于显示页面和导出Word格式的一些建议 (#474)


Closed #474<https://github.com/star7th/showdoc/issues/474>.

―
