### ISSUE TITLE
Proposal: All future documentation and comments in English

### ISSUE THREAD

**Issue by svliantiss** [star7th/showdoc#476]
We have contributed a lot of our time translating ShowDoc and we will happily continue to do so, but it would be better for ShowDoc to make it more accesible for the rest of the world if all future documentation and especially code comments could be done in English.

This would only improve ShowDoc making it more accesible for the rest of the world to come in and use and improve it. It would also remove the community effort to translate everything.

We will contribute more by also translating code comments for all current code.

**Comment by star7th** [comment]
Thanks a lot . I will maintain both Chinese and English versions when I add any new functions ,documentation or comments
