### ISSUE TITLE
数据库文件无法挂载到宿主机

### ISSUE THREAD

**Issue by leighyu1983** [star7th/showdoc#477]
执行如下操作后，容器内的数据库文件，没有挂载到宿主机，使用最新版的showdoc 官方镜像(docker hub)

docker pull  star7th/showdoc
chmod -R 777 /my/data/showdoc
docker run  -d  -v  /my/data/showdoc:/var/www/html  --name showdoc   -p 4999:900  star7th/showdoc
ll /my/data/showdoc/   ==> 输出什么都没有

通过查询  docker exec -it showdoc find / -name *.db.php 发现
数据库文件在 /showdoc_data/html/Sqlite/showdoc.db.php 中。

如果同时把/showdoc_data/html/ 和 /var/www/html/ 挂载到宿主机， 则运行命令 docker exec -it showdoc find / -name *.db.php 在容器中找不到任何数据库文件。

@star7th

**Comment by star7th** [comment]
我建议你执行完整官方文档所提到的命令，尤其是docker run之后还要执行的命令。

leighyu1983 <notifications@github.com>于2019年3月11日 周一下午9:42写道：

**Comment by leighyu1983** [comment]
@star7th 感谢回复，完全按照官方文档执行，的确可以。 但是有个问题。如下命令仅仅是做了拷贝 docker exec showdoc \cp -fr /showdoc_data/html/ /var/www/， 后续的数据会写入/showdoc_data/html/中的数据库文件吗？

**Comment by star7th** [comment]
会写到宿主机的 /showdoc_data/html/

leighyu1983 <notifications@github.com> 于2019年3月11日周一 下午9:58写道：

**Comment by leighyu1983** [comment]
@
