### ISSUE TITLE
Proposal: Community templates

### ISSUE THREAD

**Issue by svliantiss** [star7th/showdoc#478]
A separate folder or repo where users can share templates, for documents so other users can use them as well.

**Comment by star7th** [comment]
I've thought about it before. But it is not clear whether it should be shared with members of the same project, team members or users of the whole site.

**Comment by svliantiss** [comment]
I meant in the GitHub repository, so for example I have a Invoice template and a Document template. If you would make a folder community I could add them to there, so other users can take the markdown and Use it themselves to create their own template.

And indeed maybe later this folder can be added to the API as default and community templates, like Word and Google Docs have.

**Comment by star7th** [comment]
But there are many different templates, and often a template only uses a specific scenario, not very common. In this case, I prefer to store these templates in the database. Opening a folder directly in GitHub means placing the template in the code base. I haven't figured out whether it's necessary to do that.

**Comment by star7th** [comment]
“And indeed maybe later this folder can be added to the API as default and community templates” , it maybe a good idea . I will think about it later
