### ISSUE TITLE
Issue: Composer outdated

### ISSUE THREAD

**Issue by svliantiss** [star7th/showdoc#479]
When upgrading via composer it upgrades it with the old en.js files. And none of the new features have been added yet.

**Comment by star7th** [comment]
A relase version needs to be released for composer to take effect. Now is done . Subsequent official documents will recommend docker installation, which will not have this problem.

**Comment by svliantiss** [comment]
I just updated it via composer again, and I removed my cookies and cache but the English translation is still not working.

**Comment by star7th** [comment]
When you update by composer ,you can see the version number . The newest version is v2.4.6 . Or you just download from github

**Comment by svliantiss** [comment]
For some reason my composer just wouldn't update. I did the update manually and it worked perfectly.
