### ISSUE TITLE
[feature] 建议新增json参数转表格功能

### ISSUE THREAD

**Issue by elinxer** [star7th/showdoc#481]
很常见的功能，参数少的时候，直接插入一个表格加，但参数多的时候实在是浪费时间去添加参数，复制到吐，建议新增直接导入的json结构，帮忙解释格式可以统一，这样可以快速用代码生成规范的json,快速导入，非常省事：
```
[
    {
        "key":"device_resolution",
        "description":"设备的dpi",
        "require": "否",
        "type":"text"
    },
    {
        "key":"disp",
        "description":"手机运营商 中国网通， 中国移动",
        "require": "是",
        "type":"text"
    }
]
```

**Comment by star7th** [comment]
试一下用这个？
![image](https://user-images.githubusercontent.com/2200494/54338294-6e276a80-466c-11e9-9659-f9f6ca16c46f.png)

**Comment by elinxer** [comment]
格式不符合，缺少了是否必填和说明

**Comment by star7th** [comment]
你说的这种方式不通用，很少人会专门编程写个东西来生成这种特定数据格式的json。有这个能力编程去实现，为何不直接生成markdown格式更方便呢。
“必填和说明”字段是肯定需要人写的，区别在于写在代码上还是showdoc上。所以个人觉得此需求不是很必要。

**Comment by elinxer** [comment]
哈，或许，主要我经常用showdoc，在新增参数这块用的多，还都是大量参数的，特麻烦，在使用postman直接导出一个json然后用代码稍微编辑即可直接在json工具下直接生成，会方便许多，不过确实可以自己写一个生成markdown的方法，下次直接生成，这点倒是差点自闭了。
