### ISSUE TITLE
建议：新增动态展示功能

### ISSUE THREAD

**Issue by XmYhkj** [star7th/showdoc#493]
目前showdoc已经对每一次修改都有历史版本记录了，但是需要进入编辑页面才能查看到具体页面的历史版本。

如果能够将这个历史版本记录，衍生成项目动态，那么有人修改了项目中的某一个文档，将会在项目动态中体现，这对于文档维护以交流应该是很有帮助的，能够大大较少编写者与查看者之间交流，提高效率。
show me the doc , and Tell me what has changed.
like
动态可以是这样: 
某某某  修改了 《文档名称1》  上午10:00
某某某  新增了 《文档名称2》  上午10:10
某某某  删除了 《文档名称3》  上午10:22

**Comment by star7th** [comment]
后续会做此考虑。
之前不做这个是担心太多修改记录。因为很多人的编辑习惯是写一点就保存一下，生成大量修改记录。

XmYhkj <notifications@github.com> 于2019年3月26日周二 上午10:03写道：

**Comment by XmYhkj** [comment]
嗯，短时间内多次编辑形成太多修改记录确实不太好。
是否可以这样？
方案一：由编辑者主动触发生成记录，类似于打tag；
方案二：从需求出发，动态的细粒度并不需要太细，如果同一个人在一定时间内(比如说30分钟内)多次修改同一文档，就只记录最新操作记录即可。

**Comment by star7th** [comment]
方案一基本不可行。试水过，大部分人很懒，不会保存文档的时候另外写自己修改注释。
方案二是可以考虑的。只是像这样的必要性有吗？线上运行的话，基本上清一色的动态是“xxxx修改了文档xxxx”

XmYhkj <notifications@github.com> 于2019年3月26日周二 上午10:23写道：

**Comment by XmYhkj** [comment]
目前最大的痛点在于，API编写者修改了某几个文档之后，API对接者(查看API文档的人)即使打开了showdoc也无法知晓具体哪几个文档已经做了修改，只得咨询编写者或者一个个打开来查看。（当然也可以新增一个修改记录来维护！但是，大部分人是比较懒的，一旦修改的文档多了，而登记的位置有需要重新打开编写，大部分人就变得不愿意记录）

增加动态是从文档编写用户的角度思考，反过来如果可以站在查看文档的用户来看，可以增加一个未读状态来标记出这些新修改过的文档，看看是否好实现？ 😊

**Comment by star7th** [comment]
不是实现的问题是需求的问题。
这种功能是要谨慎的，因为这个规则默认所有新文档都有标志。会给用户造成视觉干扰。我觉得比较好的方式是自行建立个页面，自己写个表格放修改记录

XmYhkj <notifications@github.com>于2019年3月26日 周二下午2:54写道：

**Comment by XmYhkj** [comment]
嗯仅供参考，那把最近修改时间显示出来呢，跟文档标题同一行

![image](https://user-images.githubusercontent.com/33344180/54978918-a7e96100-4fdc-11e9-8ced-a1373bc4f77f.png)

**Comment by XmYhkj** [comment]
<img width="776" alt="687E65E6-4226-4B2B-9CB7-2C3D2101B9EA" src="https://user-images.githubusercontent.com/33344180/54979949-73c36f80-4fdf-11e9-84b2-271902357704.png">


类似我们在用的另一个工具，有一个动态还是挺有用的，虽然是清一色的动态是“xxxx修改了文档xxxx   03:55”，但是已经包含了修改者、文档名(带链接可直接点击跳转)、修改时间

**Comment by star7th** [comment]
点击右边的按钮试试，会看到一些其它的功能

XmYhkj <notifications@github.com>于2019年3月26日 周二下午3:56写道：

**Comment by star7th** [comment]
右边栏的展开按钮那里

Chen Xing <xing7th@gmail.com>于2019年3月26日 周二下午3:58写道：

**Comment by star7th** [comment]
项目动态功能后面会考虑。只是短期内此需求不紧急。

Chen Xing <xing7th@gmail.com>于2019年3月26日 周二下午3:59写道：

**Comment by XmYhkj** [comment]
嗯嗯额，修改者、文档名(带链接可直接点击跳转)、修改时间，就够用了

**Comment by star7th** [comment]
新版已经支持项目变更日志。入口在某个项目主页的右侧栏按钮，展开更多。
