### ISSUE TITLE
导出功能建议支持导出html文件格式

### ISSUE THREAD

**Issue by guanxingfeng** [star7th/showdoc#494]
目前导出功能支持word格式，不支持html格式，这是在线markdown编辑工具常有的功能，建议能支持。

**Comment by star7th** [comment]
html格式不就是网页吗，为什么不能直接发个url地址给对方

guanxingfeng <notifications@github.com>于2019年3月26日 周二上午11:40写道：

**Comment by 1Gbps** [comment]
Cent browser ctrl+S can save web pages as a single html file, this feature may help you.
