### ISSUE TITLE
建议：关于项目分类管理的建议

### ISSUE THREAD

**Issue by XmYhkj** [star7th/showdoc#495]
随着项目越来越多(😭我们的项目有20几个)，希望有对项目进行分组的功能，这样首页就可以分组显示，便于找到对应项目

**Comment by star7th** [comment]
一般来讲查找网页上的东西，如果很多的话我会用浏览器的ctrl + F 查找功能。
像你说的项目分类确实也是一个需求。可是一般人又用不上，总不能不需要分组的情况下占用人家的视觉空间。怎么平衡一般人的需要和多项目的需要，是个需要考虑的问题。

XmYhkj <notifications@github.com> 于2019年3月26日周二 下午4:41写道：

**Comment by XmYhkj** [comment]
可以考虑这样实现，默认所有项目在同一个默认分类下，项目列表界面展示还是不变，而如果设置了多个分类，则可以在项目列表页面中切换到不同分类，默认还是展示全部项目。

**Comment by star7th** [comment]
我不清楚你设想中的“设置多个分类”这个入口是放在哪里。个人觉得无论放在哪里似乎都占据空间

XmYhkj <notifications@github.com> 于2019年4月9日周二 上午9:55写道：

**Comment by star7th** [comment]
我刚更新，支持项目列表的拖动排序。你把类似的项目拖放在相邻一起，也算是简单的分类了。
