### ISSUE TITLE
支持单页导出，可否加入对应打印单页的支持

### ISSUE THREAD

**Issue by bin20060407** [star7th/showdoc#496]
打印样式参见：
https://cdc.tencent.com/2014/08/19/print-%E8%A2%AB%E5%9F%8B%E6%B2%A1%E7%9A%84media-type/

单独定义 css，只在打印的时候生效，例如打印的时候，隐藏掉左边栏等不需要的元素，就可以通过打印功能，另存为PDF啦

**Comment by star7th** [comment]
这个需求可能很多人用不上，就先不考虑了。
另外你本身就可以访问单页。点击分享，访问那个单页地址就看到效果

Binbin Ma <notifications@github.com>于2019年3月27日 周三上午11:53写道：

**Comment by bin20060407** [comment]
这个其实是一个变通（简单）的方式实现了两个需求
1、单页导出
2、生成PDF（单页）
实际情况，内网部署，网络受限，没法分享给其他人。提之前，特意搜了下 issue，还是有人也有单页导出的需求的

star7th <notifications@github.com> 于2019年3月27日周三 下午12:35写道：

**Comment by star7th** [comment]
你访问单页，然后用谷歌浏览器打印成pdf

Binbin Ma <notifications@github.com> 于2019年3月27日周三 下午12:39写道：

**Comment by star7th** [comment]
不需要导出

Chen Xing <xing7th@gmail.com> 于2019年3月27日周三 下午1:28写道：

**Comment by bin20060407** [comment]
明白了，解决了我的困惑，谢谢你
