### ISSUE TITLE
中文文档纠正：Docker 方式安装

### ISSUE THREAD

**Issue by extending** [star7th/showdoc#499]
https://www.showdoc.cc/help?page_id=65610
按照上述文档 **MacOS** 下尝试 Docker 方式安装 showdoc，

**What happened：**
`sudo chmod 777 -R showdoc_data`
`chmod: -R: No such file or directory`

**Solution：**
`sudo chmod -R 777  showdoc_data`

期望及时纠正文档内容

**Comment by star7th** [comment]
已改

**Comment by extending** [comment]
已确认，辛苦，谢谢
