### ISSUE TITLE
登陆提示页面错误

### ISSUE THREAD

**Issue by onlonely** [star7th/showdoc#5]
http://blog.csdn.net/tde007/article/details/50212001
我是用这个里面描述的部署的
部署是成功的
但是注册或者登陆提交后提示页面错误
下面是页面内容,有没有更详细的部署文档呢
ThinkPHP3.2.3 { Fast & Simple OOP PHP Framework } -- [ WE CAN DO IT JUST THINK ]

**Comment by star7th** [comment]
你看看Application\Runtime\Logs\Home目录的错误日志，顺着错误日志应该会有线索

**Comment by star7th** [comment]
新增了支持三级目录的功能；升级安装请参考部署手册中“升级安装”部分。http://blog.star7th.com/2016/05/2007.html
此外我新建了一个ShowDoc使用交流qq群（群号：564671853），欢迎探讨问题
