### ISSUE TITLE
项目成员无法离开项目

### ISSUE THREAD

**Issue by DZSDevelop** [star7th/showdoc#504]
用户成员无法离开或者退出项目。

**Comment by star7th** [comment]
偷懒没有放这个按钮。因为觉得低频操作很少用却长期占用按钮位置。后面再想怎么处理吧
当前找创建者删除成员

DZSDevelop <notifications@github.com> 于2019年4月2日周二 下午6:37写道：

**Comment by star7th** [comment]
现在加上这个功能了
