### ISSUE TITLE
[feature] 建议新增单页导出html/pdf功能

### ISSUE THREAD

**Issue by elinxer** [star7th/showdoc#510]
建议新增单页导出html/pdf功能，
![image](https://user-images.githubusercontent.com/7327251/55855160-4529c500-5b99-11e9-9986-f2b2a6746d00.png)
目前只有整个项目的导出，项目内容很多，经常要拿独立一个文档出来给对接方，很麻烦，单页就方便多了。

**Comment by star7th** [comment]
直接打开单页地址(分享按钮里显示的单页地址），然后用浏览器的打印功能打印当前页面为pdf
