### ISSUE TITLE
请问如何备份数据呢？

### ISSUE THREAD

**Issue by zhangyl52** [star7th/showdoc#511]

**Comment by star7th** [comment]
先说明自己是怎么安装的

kira <notifications@github.com> 于2019年4月10日周三 下午4:23写道：

**Comment by star7th** [comment]
如果是自动脚本或者docker安装，则把/showdoc_data/html 目录复制一份即是备份。
如果是自己手动php安装，则把整个代码目录复制一份即是备份。

**Comment by zhangyl52** [comment]
docker安装的
