### ISSUE TITLE
希望在开放接口里面增加删除的接口

### ISSUE THREAD

**Issue by 515445681** [star7th/showdoc#512]
rt

**Comment by star7th** [comment]
一开始就不计划提供删除接口。数据安全的考虑。而且这种低频操作手动就可以。

zhangbowen <notifications@github.com>于2019年4月11日 周四下午5:35写道：

**Comment by 515445681** [comment]
我这边现在要存在多个版本的文档。目前看来是想代码都提到git上，每次push都同步到showdoc。
这样高版本发现的文档bug，修改后可以直接cherry到低版本，会比较方便。
但是目前不支持删除文档的功能，所以想问问是否可以增加。

**Comment by star7th** [comment]
此需求毕竟少众。暂时不考虑。如果多人有需要的话则可以考虑。

zhangbowen <notifications@github.com> 于2019年4月11日周四 下午7:04写道：
