### ISSUE TITLE
功能缺失

### ISSUE THREAD

**Issue by diagowang** [star7th/showdoc#514]
您好，用户管理的用户角色不可以修改，项目管理的私密性也不可以修改，请问这是未完成的功能吗？

**Comment by star7th** [comment]
不打算做。
管理员有且只有showdoc这个账号。其他人的角色不需要改。
项目的私密性由创建者进入项目设置里处理。不是在管理员后台处理。

diagowang <notifications@github.com>于2019年4月13日 周六下午12:43写道：
