### ISSUE TITLE
建议：我的项目列表页，增加搜索功能

### ISSUE THREAD

**Issue by XmYhkj** [star7th/showdoc#515]
建议我的项目首页https://www.showdoc.cc/item/index 可以增加一个搜索框，根据项目名进行检索。
我们推荐一直用showdoc，然后项目变多了，不好找啊

**Comment by star7th** [comment]
我刚更新，给项目列表增加了拖动排序功能，你可以把常用的拖到前面。（如果看不到此功能，则把浏览器缓存清理下）
至于搜索框，我后面考虑下放在哪里好。当前我建议你使用浏览器的自带查找功能ctrl + F5

**Comment by star7th** [comment]
新版已支持此功能
