### ISSUE TITLE
团队成员添加支持CTRL/SHIFT连选

### ISSUE THREAD

**Issue by siwen1017** [star7th/showdoc#516]
目前团队成员超过100个，
因为目前showdoc暂不支持ldap group识别，使用的是用户自定义的团队成员组概念。
每个用户来维护自己的团 队成员时需要一个一个点，特别繁琐，希望下接菜单上可以支持CTRL/SHIFT连选。
目前删除人员，比添加人员方便很多。

**Comment by star7th** [comment]
添加团队成员只需要添加一次就好，应该还算好吧。对于超过100人的团队，假如没有ldap的情况下，其实也是要一个个点击的。而且，由于人太多，如果还要做细分权限控制的话，也是需要点击的。所以说，人就有那么多的情况下，很多事其实是省不了的

siwen1017 <notifications@github.com>于2019年4月13日 周六下午7:19写道：

**Comment by siwen1017** [comment]
一个一个 点本来是可以接受的，但目前看起来添加过的成员还在备选菜单中，这样对添加人员造成了一定的困扰。

**Comment by star7th** [comment]
我再想了一下，其实是可以多远的。我迟点尝试把它做成多选看看如何。

Chen Xing <xing7th@gmail.com>于2019年4月13日 周六下午7:23写道：

**Comment by star7th** [comment]
我现在增加了一个供，你更新到最新代码。当一个用户已经是成员的时候，不再重复出现在选项里。

**Comment by star7th** [comment]
同时讲一下，你不一定要选择。如果觉得找到选项比较麻烦的话，可以直接输入用户名来添加。

Chen Xing <xing7th@gmail.com>于2019年4月13日 周六下午7:32写道：
