### ISSUE TITLE
docker部署失败

### ISSUE THREAD

**Issue by CodeDome** [star7th/showdoc#517]
![image](https://user-images.githubusercontent.com/16448830/56124299-ea350b00-5fa8-11e9-9431-d2d9c8b6a291.png)

**Comment by star7th** [comment]
我不是很理解你的逻辑。为什么不按照官方教程，而是要自己build。如果是自己build，那你要保证自己的网络可用。你还是上官网重新根据官方教程来吧，不要看第三方教程

quchengchun <notifications@github.com>于2019年4月15日 周一下午6:04写道：
