### ISSUE TITLE
使用showdoc一年多，有几点建议

### ISSUE THREAD

**Issue by Luckylewin** [star7th/showdoc#518]
一：建议分享文档时不要以page_id 作为 id 这样别人改个数字就能看到其他的文档了
二：分享分档时，左侧菜单可以不出现吗，有时候只想分享某几篇文档。建议增强权限控制，因为有时候需要开放某一部分文档给别人，但不是全部。
三：左侧原生的滚动条不好看

**Comment by Luckylewin** [comment]
http://xxxxxxx/showdoc/web/#/5?page_id=65 类似这样的 换了page_id 就能看其他文档了

**Comment by star7th** [comment]
要私密的话，除了加上访问密码，其他都没有意义。我只要看一下接口返回数据就能知道其他page_id了，无论你的数字是多少。
你可以分享单页出去。点击右边侧栏的分享按钮看看。
原生滚动条还算可以接受吧。目前你有其他交互方式推荐的可以说下
