### ISSUE TITLE
插入链接没有做显示判断，再查看页不应该有插入按钮

### ISSUE THREAD

**Issue by xhmshine** [star7th/showdoc#520]
![image](https://user-images.githubusercontent.com/17609953/56332274-3a3aea00-61c2-11e9-8a66-07d4a26e25a7.png)

如图所示，插入链接没有做显示判断，在查看页不应该有插入按钮

**Comment by star7th** [comment]
晚点改正

**Comment by star7th** [comment]
已经更新。
