### ISSUE TITLE
建议分享的文档页面可以加入文档保存时间

### ISSUE THREAD

**Issue by try3** [star7th/showdoc#522]
如题，这样方便浏览的人，知道说明时候更新文档的

**Comment by star7th** [comment]
不知道这个需求是好是坏。
好处如你所说。
坏处就是它会永久性地占据一定的视觉空间。可能大部分人不需要时间显示，只想精简一些

try3 <notifications@github.com> 于2019年4月19日周五 下午1:37写道：

**Comment by 1Gbps** [comment]
I think it's a good idea to add the last save time of the document on the share page.

**Comment by hzliangbin** [comment]
加上文档的创建时间/创建者，以及文档的最新修改时间/修改者。有时候需要知道文档是不是最新的，是否及时反映了团队更新的需求、接口、方案等，有作者方便找对接人。

**Comment by star7th** [comment]
我最后决定在分享出去的项目页面的右边展示一个详情按钮，点击后可以显示修改时间和修改人。你们可以看官网例子https://www.showdoc.cc/help?page_id=1385767280275683
