### ISSUE TITLE
建议上传的图片和附件连接设置为相对路径

### ISSUE THREAD

**Issue by xhmshine** [star7th/showdoc#525]
建议上传的图片和附件连接设置为相对路径
现在上传完图片的格式位绝对路径：http://192.168.40.90/server/....../*.png
建议修改为绝对路径：/server/....../*.png
这样方便后期迁移网站，不需要考虑域名的问题

**Comment by star7th** [comment]
绝对路径在其他方面有好处。相对路径可能有问题。
我建议迁移网站后就执行sql然后把网址改过来。同时更建议运行在一个稳定的服务器上，而不是随便的本地机器等。

xhmshine <notifications@github.com> 于2019年4月23日周二 上午9:17写道：
