### ISSUE TITLE
showdoc升级遇到的问题

### ISSUE THREAD

**Issue by liyif09** [star7th/showdoc#526]
手动php安装的showdoc，然后进行php安装升级。升级完成后，Sqlite/showdoc.db.php、Public/Uploads/下的所有文件已经拷贝过去。但是升级之后，发现之前的用户名密码登录不了。重新注册也显示register fail.那个升级验证的链接是显示OK的。

**Comment by star7th** [comment]
确保环境ok，确保权限ok

liyif09 <notifications@github.com> 于2019年4月23日周二 上午10:05写道：

**Comment by liyif09** [comment]
环境应该是没问题，我全新部署的没问题，就是全新部署的，然后把老的数据库拷过去覆盖，然后用老系统的账号登录不进去，注册报register fail.

**Comment by star7th** [comment]
覆盖了之后，给可写权限了吗

liyif09 <notifications@github.com> 于2019年4月23日周二 上午10:43写道：

**Comment by star7th** [comment]
还有就是，上传旧数据库文件，不要用ftp上传

Chen Xing <xing7th@gmail.com> 于2019年4月23日周二 上午10:44写道：

**Comment by liyif09** [comment]
我已经给Users用户全部控制权限了，是在服务器上直接拷贝的，我用的阿里云。

**Comment by star7th** [comment]
什么user控制权限，不需要这个。
直接给那个数据库文件777权限，覆盖后，文件权限会变的。要重新给。


liyif09 <notifications@github.com> 于2019年4月23日周二 上午10:48写道：

**Comment by liyif09** [comment]
我是windows服务器。

**Comment by star7th** [comment]
我没用win服务器，不保证win服务器上的兼容性

liyif09 <notifications@github.com> 于2019年4月23日周二 上午10:52写道：

**Comment by liyif09** [comment]
windows服务器貌似是不支持升级。因为我用最新的数据库文件来覆盖也不行，貌似数据库文件不能迁移。

**Comment by star7th** [comment]
我觉得可能win服务器本身对数据库文件格式进行了修改。但这种情况我也没办法。

liyif09 <notifications@github.com> 于2019年4月23日周二 上午11:16写道：

**Comment by liyif09** [comment]
好的，谢谢了

**Comment by xzplays** [comment]
如果你是iis+php。要给web目录添加IIS APPPOOL\应用池名称 的读写权限。

**Comment by liyif09** [comment]
试了，不行算了。

**Comment by hinory** [comment]
在Linux 宝塔面板里新建了一个站点，全新安装，上传了WIN服务器的数据库和附件，升级成功了。
