### ISSUE TITLE
请问线上的文档怎么导出到本地服务器呢？

### ISSUE THREAD

**Issue by BigBigBIgMan** [star7th/showdoc#527]
之前一直用的线上的showdoc ，现在公司搭建了本地的服务器，请问怎么将线上的导出到本地呢？

**Comment by star7th** [comment]
线上是为在线托管而开发的。所有没有这样的导出工具。且线上版本与开源版数据库不兼容。除了手动把文本复制过去，你没有其他办法。

BigBigBIgMan <notifications@github.com> 于2019年4月23日周二 上午10:48写道：

**Comment by BigBigBIgMan** [comment]
好吧，这项目的可移植性，后期是否考虑增加呢?

**Comment by star7th** [comment]
后面看看吧。主要是没考虑过这种小需求的移植性。如果是开源版迁移服务器，则直接考虑代码过去就好。

BigBigBIgMan <notifications@github.com> 于2019年4月23日周二 上午11:16写道：

**Comment by zhangqingwen** [comment]
线上编辑的内容，在服务器上以什么格式保存的呢？

**Comment by star7th** [comment]
加密压缩后存放redis加mysql

zhangqingwen <notifications@github.com>于2019年4月28日 周日下午2:28写道：
