### ISSUE TITLE
分享单页面提示没有权限

### ISSUE THREAD

**Issue by derekzhan** [star7th/showdoc#529]
![image](https://user-images.githubusercontent.com/2375460/56780326-6b926600-6811-11e9-8e4f-034e7be54050.png)
如上图，我分享单页面出去后，别人打开没有权限，请问这个应该如何处理，谢谢！

**Comment by star7th** [comment]
提供下地址

chunge <notifications@github.com> 于2019年4月26日周五 上午10:53写道：

**Comment by star7th** [comment]
对了，如果你要分享单页，那就不要设置项目密码

Chen Xing <xing7th@gmail.com> 于2019年4月26日周五 上午10:59写道：

**Comment by derekzhan** [comment]
但是不设置项目密码感觉又不安全呀

**Comment by star7th** [comment]
加密项目分享的话会分享整个项目，不支持分享单页。

chunge <notifications@github.com> 于2019年4月26日周五 上午11:04写道：

**Comment by derekzhan** [comment]
了解，那如果我要改成加密项目也能分享单页面的话，我应该如何操作？

**Comment by star7th** [comment]
没办法操作

chunge <notifications@github.com> 于2019年4月26日周五 上午11:09写道：

**Comment by derekzhan** [comment]
修改源码也不行吗？

**Comment by star7th** [comment]
你可以去试下

chunge <notifications@github.com> 于2019年4月26日周五 上午11:12写道：

**Comment by derekzhan** [comment]
好好。
