### ISSUE TITLE
你好，提示验证码校验失败，这个是什么原因？

### ISSUE THREAD

**Issue by Sk464036801** [star7th/showdoc#53]
@star7th

**Comment by star7th** [comment]
在你的站点我注册并新建了个test项目，一切没问题。http://doc.welinkio.com/showdoc/index.php/11

**Comment by vaward** [comment]
我遇到的问题，看日志觉得问题在于  /var/lib/php/   下面没有session 目录，新建并赋予 apache 组权限应该可以解决。

**Comment by star7th** [comment]
新增了支持三级目录的功能；升级安装请参考部署手册中“升级安装”部分。http://blog.star7th.com/2016/05/2007.html
此外我新建了一个ShowDoc使用交流qq群（群号：564671853），欢迎探讨问题
