### ISSUE TITLE
 我尝试在树莓派上安装showdoc发现提示docker镜像缺失

### ISSUE THREAD

**Issue by yoyojacky** [star7th/showdoc#530]
Error response from daemon: Get https://registry.docker-cn.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Error response from daemon: No such image: registry.docker-cn.com/star7th/showdoc:latest

**Comment by yoyojacky** [comment]
Unable to find image 'star7th/showdoc:latest' locally
latest: Pulling from star7th/showdoc
ff3a5c916c92: Pull complete
2ca736d3a2d3: Pull complete
ed01bffbd8ba: Pull complete
86a241b7142f: Pull complete
2ffa2200859b: Pull complete
bba89656402e: Pull complete
3f9869615113: Downloading [===================================>               ]  12.26MB/17.49MB
3f9869615113: Pull complete
ca6f4c22bb7e: Pull complete
c6e670a03139: Pull complete
d68194d4a919: Pull complete
3886fecfffe3: Pull complete
72d73c916ca2: Pull complete
66c290981af1: Pull complete
ae984e1cd476: Downloading [============================>                      ]  35.91MB/62.72MB
4f5c98e97881: Download complete
7a5c8005874f: Download complete
d0e5afcf9ed6: Download complete
a77fddbcccce: Download complete
29fbff2beeff: Download complete
6acbe516593c: Download complete
b2e0f8f06f86: Download complete
a3982ad6ae6d: Download complete
53fe85e64f8b: Download complete
401d987fb2cd: Download complete
955b2c3c2280: Download complete
b7957d06df75: Download complete
fce749939a8f: Download complete
747e227b8897: Download complete
8eea7612ac50: Download complete
fc16400d9d1c: Download complete
eade3616d021: Downloading [==>                                                ]    650kB/12.28MB
25606b0972ac: Downloading [==>                                                ]  94.22kB/1.763MB
f463a250aa57: Waiting
0e5953241d63: Waiting
4f2a4377205d: Waiting
54c6c023e808: Waiting
c321cbb12d9e: Waiting

**Comment by star7th** [comment]
看着像是网络问题。那就按照教程手动安装吧

yoyojacky <notifications@github.com>于2019年4月26日 周五下午5:38写道：
