### ISSUE TITLE
根据showdoc_db写了一个最新版api的脚本

### ISSUE THREAD

**Issue by sdtzyb** [star7th/showdoc#532]
写的不好，还请海涵。
小遗憾：page_content里面换行<br>不能达到想换的目的，后续额外文本处理了，

showdoc_newTable.sh

#!/bin/bash
#
#
#
host="localhost"				#数据库所在地址。默认是localhost
port=3306						#数据库所在端口。默认是3306
user="root"   	 			#数据库的用户名
password="123456" 			#密码
db="test" 					#要同步的数据库名。要同步多个db可以将本脚本复制多份
api_key="***" 			#api_key
api_token="***" 	#api_token
cat_name="账户" 	#可选。如果想把生成的文档都放在项目的子目录下，则这里填写子目录名。
url="http://**:9090/showdoc/server/index.php?s=/api/item/updateByApi" #可选。同步到的url。如果是使用www.showdoc.cc ，则不需要再改此项。如果是部署开源版showdoc，请改此项为http://xx.com/server/index.php?s=/api/open/updateDbItem 。其中xx.com为你的部署域名
#
#
#
#
export MYSQL_PWD=${password} 
COMMAND="set names utf8;select TABLE_NAME ,TABLE_COMMENT from tables where TABLE_SCHEMA ='${db}'  " 
declare table_info=`mysql -h${host} -P${port} -u${user}  --show-warnings=false -D information_schema -e "${COMMAND}" `
info_array=(${table_info//\ / })
info=
for i in "${!info_array[@]}"; do
	if [[ $i -eq 0 || $i -eq 1 ]];then
		continue
	fi
	b=$(( $i % 2 ))
    if [ $b -eq 0 ];then
    	info=$info${info_array[i]},
    else
    	info=$info${info_array[i]}!
    fi
done
infoA_array=(${info//\!/ })
for j in "${!infoA_array[@]}"; do
	detail=(${infoA_array[j]//\,/ })
	table_name=${detail[0]}
	table_desc=${detail[1]}
	COMMAND="set names utf8;select COLUMN_NAME ,IS_NULLABLE ,COLUMN_TYPE ,COLUMN_COMMENT from COLUMNS where TABLE_SCHEMA ='${db}'  and TABLE_NAME = '${table_name}' " 
	declare table_detail=`mysql -h${host} -P${port} -u${user}  --show-warnings=false -D information_schema -e "${COMMAND}" `
	v1="-  "
	page_content=$v1$table_name$table_desc
	v0=" "
	page_content=$page_content$v0
	v2="<br>|字段|空|类型|注释|<br>"
	page_content=$page_content$v2
	v3="|:---- |:--- |:---|------      "
    page_content=$page_content$v3
    v6="|"
    detail_array=(${table_detail//\ / })
    
	for i in "${!detail_array[@]}"; do
		if [[ $i -eq 0 || $i -eq 1  || $i -eq 2 || $i -eq 3 ]];then
			continue
		fi
		b=$(( $i % 4 ))
	    if [ $b -eq 0 ];then
	    	v4="<br>"
	    	page_content=$page_content$v6$v4$v6${detail_array[i]}
	    else
	    	page_content=$page_content$v6${detail_array[i]}
	    fi
	done
	page_content=$page_content$v6
curl -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8'  "${url}" --data-binary @- <<CURL_DATA
from=shell&page_title=${table_desc}&page_content=${page_content}&api_key=${api_key}&api_token=${api_token}&cat_name=${cat_name}
CURL_DATA

done
#echo $table_info

export MYSQL_PWD=""

**Comment by star7th** [comment]
你改写的目的是什么?

**Comment by sdtzyb** [comment]
可以按照数据库批量生成表结构说明文档 俞斌 邮箱yubin66@gmail.com 签名由 网易邮箱大师 定制 在2019年04月28日 22:47，star7th 写道： 你改写的目的是什么? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by star7th** [comment]
我还是不明白你这样做的意思是什么？跟原来生成的文档有什么不一样吗

**Comment by star7th** [comment]
还有你说的最新版api 我也不明白是啥。我已经有一段时间没动过api相关的代码了。
原来的脚本本身就兼容api接口，为什么要写一个然后说兼容最新api

**Comment by sdtzyb** [comment]
发现问题我这里版本不是最新的导致不能使用http://xx.com/server/index.php?s=/api/open/updateDbItem 接口
