### ISSUE TITLE
centos上手动升级提示错误

### ISSUE THREAD

**Issue by xulingfeng931027** [star7th/showdoc#533]
从git上下载的源码文件 部署到/var/www/html下 再把原来的showdoc.db.php从本机拷贝过去  访问时数据库错误,提示user_token表找不到.

**Comment by star7th** [comment]
我觉得你是没有执行教程里所说的最后一步升级数据库

**Comment by xulingfeng931027** [comment]
额 照您的方法update了数据库  但是老的项目都没了 原来的用户名也不能用了  看了服务器上的db文件又是原来的那个 挺奇怪的

**Comment by star7th** [comment]
其实我想说的是，总遇到在低级问题上犯错的人，我也是很烦的。“db又是原来的那个”，证明你没有好好按照教程升级。

徐凌峰 <notifications@github.com> 于2019年5月6日周一 下午10:16写道：

**Comment by star7th** [comment]
确保每一步完全按照教程来

Chen Xing <xing7th@gmail.com> 于2019年5月6日周一 下午10:19写道：

**Comment by xulingfeng931027** [comment]
我意思是我把原来的db文件拷贝到新部署的项目下并执行了update的操作，但是访问时提示找不到原项目并且用户也不见了

**Comment by star7th** [comment]
给执行权限再执行它几次看一下

徐凌峰 <notifications@github.com> 于2019年5月6日周一 下午10:25写道：

**Comment by star7th** [comment]
新文件拷贝过来你有给权限吧？

Chen Xing <xing7th@gmail.com> 于2019年5月6日周一 下午10:27写道：

**Comment by xulingfeng931027** [comment]
showdoc -r给的777

**Comment by star7th** [comment]
你原谅的showdoc是什么版本

徐凌峰 <notifications@github.com> 于2019年5月6日周一 下午10:30写道：

**Comment by star7th** [comment]
原来的

Chen Xing <xing7th@gmail.com> 于2019年5月6日周一 下午10:31写道：

**Comment by xulingfeng931027** [comment]
这个怎么看，之前别人部署的，我不清楚

**Comment by xulingfeng931027** [comment]
如何迁移
备份所有代码和数据库

下载新代码：https://github.com/star7th/showdoc

将新代码中的/Sqlite/ 复制到旧目录(如果已存在/Sqlite则覆盖之)，并赋予/Sqlite/showdoc.db.php可写权限

复制新代码中的/Application/Home/Controller/UpdateController.class.php 覆盖原来旧的相应文件。


关于最后一点  现在的新代码里已经没有Application文件夹了呀  在哪里找这个controller呢

**Comment by star7th** [comment]
看官网的教程：https://www.showdoc.cc/help?page_id=13732 ，不要相信第三方网站的

**Comment by star7th** [comment]
问题已经很明显了，是因为没有按照官网教程操作。

**Comment by xulingfeng931027** [comment]
我想问你的教程中从mysql迁移数据库那一步中   复制新代码中的/Application/Home/Controller/UpdateController.class.php 覆盖原来旧的相应文件。

从哪儿复制呢,下载下来的新代码中压根没这玩意

**Comment by star7th** [comment]
mysql版本是两年前的版本，已经放弃维护了。不保证能升级。
这个文件后来已经移动到 server/Application/Home/Controller/UpdateController.class.php

徐凌峰 <notifications@github.com> 于2019年5月7日周二 上午12:20写道：

**Comment by xulingfeng931027** [comment]
好的，我试试哈


 
---原始邮件---
发件人: "star7th"<notifications@github.com>
发送时间: 2019年5月7日(星期二) 凌晨0:24
收件人: "star7th/showdoc"<showdoc@noreply.github.com>;
抄送: "徐凌峰"<840683378@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [star7th/showdoc] centos上手动升级提示错误 (#533)


mysql版本是两年前的版本，已经放弃维护了。不保证能升级。 
 这个文件后来已经移动到 server/Application/Home/Controller/UpdateController.class.php 
 
 徐凌峰 <notifications@github.com> 于2019年5月7日周二 上午12:20写道：
