### ISSUE TITLE
希望添加禁用用户功能

### ISSUE THREAD

**Issue by abowu** [star7th/showdoc#534]
由于项目是公司内部用的，当员工离职后需要 禁止其登录

**Comment by star7th** [comment]
改掉密码不就好了？

abowu <notifications@github.com> 于2019年5月9日周四 下午3:41写道：

**Comment by star7th** [comment]
或者删除用户

Chen Xing <xing7th@gmail.com> 于2019年5月9日周四 下午3:42写道：

**Comment by abowu** [comment]
好吧，现在就是这样做的，改密码
