### ISSUE TITLE
通过密码打开项目时，输入密码无法Enter键提交，需要鼠标点击提交

### ISSUE THREAD

**Issue by hinory** [star7th/showdoc#536]
通过密码打开项目时，输入密码无法Enter键提交，需要鼠标点击提交

只是个小细节问题，不过遇到的概率蛮大的，好几次被询问密码是否不正确，提交了没反应，后来发现是输入密码后，鼠标点击提交才行，不是大家习惯的  输入密码后 回车就提交的。

希望作者可以适当调整这里，非常感谢！

**Comment by star7th** [comment]
你先尝试更新到新版

hinory <notifications@github.com> 于2019年5月13日周一 上午10:09写道：

**Comment by hinory** [comment]
谢谢~

**Comment by hinory** [comment]
已经升级了最新版2.4.11，发现通过密码访问项目时，第一次输入密码访问还是不行（自动刷新密码登录页面），第二次就可以了。测试了很多遍。

**Comment by star7th** [comment]
这种小细节我就不专门处理了。每处理一次都需要编译打包上传。留着下次如果更新版本就顺便处理吧

**Comment by hinory** [comment]
嗯，谢谢！ 这个本身并不算是问题·~ 只是遇到了就提出来，感谢提供了这么好的产品，已经跟伙伴们都用起来了，非常细化， 也大大提高了我们的生产效率！
