### ISSUE TITLE
showdoc兼容性问题

### ISSUE THREAD

**Issue by liyif09** [star7th/showdoc#538]
showdoc在firefox下能正常访问，但是在IE下不能正常访问。
![image](https://user-images.githubusercontent.com/49890096/57611209-e47d1600-75a4-11e9-9cb4-3ea7c249f8e4.png)

**Comment by star7th** [comment]
IE不在支持范围内，官方不对ie的兼容性负责。
实际使用中Ie 11以及edge应该可以兼容。但不保证，也不会做官方测试。

liyif09 <notifications@github.com>于2019年5月13日 周一下午5:31写道：
