### ISSUE TITLE
自动生成数据字典,字段注释莫名多出 \n

### ISSUE THREAD

**Issue by qq940390** [star7th/showdoc#539]
使用 https://www.showdoc.cc 的自动化生成数据字典工具时,表字段的注释会莫名有 \n ,这导致生成的文档位于注释后的 "|" 会折行.
本地自建showdoc项目,当我添加了 "$value2['column_comment'] = trim($value2['column_comment']);" 一行后,该问题解决.
期待 能解决此问题.

**Comment by star7th** [comment]
没明白你的描述，请截图说明

**Comment by star7th** [comment]
特别是这个描述 —— 生成的文档位于注释后的 "|" 会折行.

**Comment by qq940390** [comment]
请看图



其中mark源码中的最后一个"|"折行了,这导致六表格显示多出了一行,我不知道这个问题是mysql的字段注释问题还是其他什么,不过在增加六trim去掉多余空格换行后,自动生成后的数据字典显示就正常了.





------------------ 原始邮件 ------------------
发件人: "star7th"<notifications@github.com>;
发送时间: 2019年5月14日(星期二) 下午5:50
收件人: "star7th/showdoc"<showdoc@noreply.github.com>;
抄送: "五行缺風"<940390@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [star7th/showdoc] 自动生成数据字典,字段注释莫名多出 \n (#539)




特别是这个描述 —— 生成的文档位于注释后的 "|" 会折行.

**Comment by star7th** [comment]
没看到图片

**Comment by qq940390** [comment]
图片这个问题，我不知道是怎么回事，确实是加入了图片。
我遇到的问题是，用自动导出数据字典那个工具导出的mysql的字段注释，后面会有换行符，这导致了数据字典表格显示不正常，我不知道其他人是否也是这样的，也许有可能是我一个人或者是mysql的问题了，打扰了


 
---原始邮件---
发件人: "star7th"<notifications@github.com>
发送时间: 2019年5月14日(星期二) 晚上6:06
收件人: "star7th/showdoc"<showdoc@noreply.github.com>;
抄送: "jinhai"<940390@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [star7th/showdoc] 自动生成数据字典,字段注释莫名多出 \n (#539)



没看到图片

**Comment by star7th** [comment]
后面的换行符是特意添加上去的。
因为在实际的展示中，展示完注释后就应该换行，然后显示表格。

**Comment by star7th** [comment]
所有我不明白你说的不正常现象是什么

**Comment by qq940390** [comment]
就是表格的数据不是一行接一行，而是一行数据，一行空行，看起来比较怪异，最后的换行符代码里看见了那是应该有的，不过是多了一个不可见的换行符，来源就是字段注释


 
---原始邮件---
发件人: "star7th"<notifications@github.com>
发送时间: 2019年5月14日(星期二) 晚上6:23
收件人: "star7th/showdoc"<showdoc@noreply.github.com>;
抄送: "jinhai"<940390@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [star7th/showdoc] 自动生成数据字典,字段注释莫名多出 \n (#539)



所有我不明白你说的不正常现象是什么

**Comment by star7th** [comment]
没有图片说明我不知道你在说什么

jinhai <notifications@github.com> 于2019年5月14日周二 下午6:27写道：
