### ISSUE TITLE
分享页面的地址安全性问题

### ISSUE THREAD

**Issue by try3** [star7th/showdoc#541]
建议不要用id，使用md5类似的加密参数。

可以加强安全性，分享给第三方后，第三方不能根据修改id来达到查看其它接口文档
      （可能有很多接口，但只要给第三方某几个接口）

**Comment by star7th** [comment]
没有意义。不加密意味着公开，任何人可读。你就算怎么加密参数，我总有办法拿到。
不想其他文档被查看的唯一保护方法是给项目加上访问密码

**Comment by star7th** [comment]
只要不设置访问密码，我可以通过抓接口等方式马上就知道你的项目id以及旗下的页面id。加密id就跟掩耳盗铃一样，防不住人的。
唯有加上访问密码

**Comment by try3** [comment]
web/#/page/25  =>  web/#/page/D34F8DCF68924619A669723395D5DE3E
变成guid这种格式的，你猜的难度有多大？有多少人愿意去尝试？
而如果 是25这种的，随便哪个人修改下 数字接口

**Comment by star7th** [comment]
我跟你讲怎么做。
右键查看元素，在浏览器请求中找到那个获取页面内容的接口。找到项目id 。新开窗口，立马根据项目id访问该项目。

**Comment by star7th** [comment]
总之我一开始设置showdoc就没想过要通过隐藏地址来实现安全性。隐藏的地址早晚被找出来。

**Comment by try3** [comment]
其实这个需求不是加密id，而是程序本身分享出来的就是无规律的参数，不是说转换下

**Comment by star7th** [comment]
要保证安全唯一办法是增加访问密码。这是showdoc一开始的设计思想。

**Comment by star7th** [comment]
暂时不考虑更改这个设计思想

**Comment by star7th** [comment]
如果做了你认为的这个加密，反而迷惑了用户，觉得分享出去的页面就是加密的，别人不可能访问你其他页面，从而降低了警惕。从而没把项目加访问密码。这是很不恰当的行为。你提出这个问题，无非也是想偷懒不给项目加上访问密码。这种取巧的方法会导致你可能泄露重要数据。

**Comment by star7th** [comment]
官方推荐的唯一加密方式是设置访问密码。其他方式都是公开行为。

**Comment by enyusmile** [comment]
只想分享一个项目中的某个单页的内容,但是密码是针对项目的.这样如果别人分享

**Comment by enyusmile** [comment]
只想分享一个项目中的某个单页的内容,但是密码是针对一整个项目的.所以提供的分享链接时一并给出的密码能看到这个项目的所有内容.

怎样让其只看到这个单页的分享内容(不能看到整个项目未分享的内容)?

**Comment by try3** [comment]
不是密码的问题，这个需求的重点是：
一个项目里有很多文档，但只想分享一部分给别人，如果是密码也是无法解决这问题的

**Comment by star7th** [comment]
当前的设计没办法做到这样子。我比较建议把要分享的单独成一个项目（单页项目也行）。
如果要实现这个需求，单纯的加密ID是不能解决了。当然有其他办法，但我后面再看下这种需求多不多

**Comment by 1Gbps** [comment]
Endorsed the author's point of view

**Comment by hinory** [comment]
为了避免某些人“太懒”或者”不习惯加密码“这种操作方式，是否可以在创建项目的时候 选择项目是公开或者不公开的，如果不公开，可选填访问密码。 这样估计会解决很多人对”安全性“ 的非必要猜测

**Comment by star7th** [comment]
@hinory 我已经更新，增加了“公开项目”和“私密项目”类型让用户选择
