### ISSUE TITLE
分享项目中的单页,但不能让其看到项目未分享的其他页

### ISSUE THREAD

**Issue by enyusmile** [star7th/showdoc#542]
只想分享一个项目(私有项目,项目有加密)中的某个单页的内容,但是密码是针对一整个项目的.所以提供的分享链接时一并给出的密码能看到这个项目的所有内容.

怎样让其只看到这个单页的分享内容(不能看到整个项目未分享的内容)?

**Comment by star7th** [comment]
单页项目就是为这种场景设置的。另外起一个单页项目，专门分享出去

**Comment by enyusmile** [comment]
一个项目由很多页面组成,其中相当部分页面会涉及多个单位,但也有些私有页面不想共享出去.
所以就分享单页,如果建立成单页项目,那项目数会级数增长且不好管理(和其他常规项目混在一起)

建议:可以和项目密码一样,项目>目录>页面,也有层级的密码.
原来的项目密码,可以看到项目的任何内容,如果分享出去的是项目中某个单页,也有个单页密码,目录也有密码.不同层级的密码分管不同的分享内容范围.

**Comment by star7th** [comment]
因为这个会增加用户操作复杂度，且需求的人不多，我需要做下考虑。尽量让showdoc保持简单是我之前的原则之一

**Comment by enyusmile** [comment]
嗯,
我的建议也是兼容之前的用户使用习惯(项目的密码依旧可以看到项目内的所有内容).对原用户可以是无感的.

目录以及项目里单页的分享密码可以在目录和页面的编辑区域新增个密码输入框,就单页而言,也可以看到页面的密码修改历史.也满足了层级分享.

**Comment by star7th** [comment]
新版刚新增了功能。分享页面的时候，将允许创建加密页面地址。任何得知该单页地址的用户都可以公开访问到此页面内容，且ta无法倒推原项目内容。

**Comment by enyusmile** [comment]
(我还没有尝试新版本功能,也在评(you)估(yu)要不要升级)如果如作者所述新增的功能,好像还是不能满足关于一个项目有多个文件夹,一个文件夹有多个子文件夹或页面时要分享文件夹级别时的场景.
很多时候暴露出的项目,3级文件夹,页面都有分享场景.
希望作者能多多考虑,谢谢

**Comment by star7th** [comment]
不再考虑分享单个子目录的场景。
要分享子目录的话，更建议新建一个公开项目专门放置公开内容
