### ISSUE TITLE
是否可以添加一项请求参数参数示例的配置

### ISSUE THREAD

**Issue by breakXML** [star7th/showdoc#545]
比如新增一个注解来写入请求参数示例，部分参数是List对象型的，可能还是多级的，有一个请求参数示例将会更加直观

**Comment by star7th** [comment]
如果你说的是生成api文档的脚本的话，目前官方提供的脚本只能解决常规需求。特殊需求还是得自己写脚本调用自由开放api实现吧。除非说这种需求很大众很多人用得上

**Comment by breakXML** [comment]
好的，谢谢，个人感觉请求参数示例，还是蛮大众的，所以才提，像&字符转义的问题，我这边已经处理了

**Comment by star7th** [comment]
我自己是很少用你说的这种情形的。
我不知道你说的参数示例是不是指传参是一段json的意思

**Comment by star7th** [comment]
你先手写个例子，截图看下

**Comment by breakXML** [comment]
哈，我已经改好了。。。对，就是请求示例的一个json，改是简单，就是怕后续升级，冲突啥的，麻烦
![image](https://user-images.githubusercontent.com/30281995/58079772-5e844f00-7be4-11e9-9128-95bd868e648a.png)

**Comment by star7th** [comment]
我个人觉得，表单方式提交比json格式提交要广泛得多。而一旦支持了你说的这种方式，我很明显得增加在文档说明，增加demo说明。说实话我不确定增加一个这样的语法是不是显得多余。先把issue放在这，看一段时间有没有其他人有需求。

**Comment by bin20060407** [comment]
前后端分离项目，提交 json 格式数据的项目挺多的，尤其是使用了 `axios`，默认就是发送 json

**Comment by star7th** [comment]
我已经增加。新的语法标签是“@json_param” ，文档里的语法关键字表格添加了此描述 https://www.showdoc.cc/page/741656402509783
