### ISSUE TITLE
希望添加文章变更提醒功能？

### ISSUE THREAD

**Issue by nazhr** [star7th/showdoc#546]
在文章变更时有提醒通知的能力，在本地部署后，在指定提醒功能配置上添加提醒方法。
建议预留入口添加邮箱服务器配置或者企微接入入口。

**Comment by star7th** [comment]
建议你搜索下历史提问来了解下大家的想法，然后再针对性地提出你的建议

nazhongrui <notifications@github.com>于2019年5月27日 周一下午4:01写道：

**Comment by star7th** [comment]
https://github.com/star7th/showdoc/issues/107
https://github.com/star7th/showdoc/issues/173

**Comment by nazhr** [comment]
上面这个帖子之前看过了，其中#173中提出的几个通知方案，不清楚在showdoc中哪里可以关联邮件服务器，自己搭建了邮件服务器，需要和showdoc关联上，showdoc变更后可以通知相关同学。

**Comment by star7th** [comment]
现在的问题一是通知方式的问题，第二个是修改记录太多的问题。尤其是修改记录太多的问题。很多人习惯写一点保存一下。
没有太好的方式解决。所以干脆不支持这个功能了，

nazhongrui <notifications@github.com>于2019年5月29日 周三上午10:47写道：
