### ISSUE TITLE
可以通过开放API接口一次提交多个页面吗?

### ISSUE THREAD

**Issue by NastasyaObertas** [star7th/showdoc#547]
首先非常感谢,团队协作建立文档非常方便.目前我们团队准备把之前的项目文档内容都部署进来,
最近在根据团队代码内部标准doc注释格式 使用现有开放API接口直接上传排好版的MD文档
会有一次提交多个页面的需求
但是目前API接口每次POST提交只能传一个页面,
代码分析得到多个页面的文档内容,只能够每个页面依次建立POST连接提交吗?
如果目前确实只能一次POST提交一个页面,之后会有可能加上在一次请求提交多个页面吗?
因为目前的"自动生成API文档"这个接口是可以在一次提交时传递多个页面的,但是这个API接口貌似格式是固定的,没法依据自己期望的格式直接传递MD文档内容
谢谢

**Comment by star7th** [comment]
个人觉得这个问题很好解决。在生成文档的那个程序里执行个for循环之类的调用多次就好了。对程序来讲没啥性能损耗。高级api目前保持简单，不打算支持多页面。

Nastasya Vasilievna Obertas <notifications@github.com> 于2019年5月29日周三
上午10:05写道：

**Comment by NastasyaObertas** [comment]
好的 谢谢
