### ISSUE TITLE
【BUG】本地安装方式升级成功，项目前台界面消失

### ISSUE THREAD

**Issue by szkzn** [star7th/showdoc#548]
环境：CentOS 7.6 x64
PHP: 7.3.1
webserver：nginx 1.15.10
Browser：Chromium  75.0.3743.0（开发者内部版本） （64 位）
Android: Chrome 66.0.3359.126
伪静态：从没开过

部署方式：全新安装包本地解压
详情：
升级前，我是通过下载全新安装包方式部署的（去年4月份），期间升级过2次，都是成功的。流程都是备份Sqlite/showdoc.db.php，解压新版覆盖安装，再把之前备份的showdoc.db.php覆盖回去，接着访问http://x.com/index.php?s=/home/update/db，看到提示ok后，重新访问文档首页，提示让我选择语言，选择完点击下一步，页面提示我已经安装，此时这个页面我无论如何都绕不过去，只好去 /install 下面删了 install.lock，接着安装成功了。再次重新登录，发现 点击右上角我的项目，显示一片空白
![image](https://user-images.githubusercontent.com/30108874/58687784-34d1e180-83b5-11e9-97ed-4525ca0b1cd6.png)

进入管理后台——项目管理，可以看到数据都在，并且可以通过连接访问。
![image](https://user-images.githubusercontent.com/30108874/58687940-a578fe00-83b5-11e9-88e5-db318610711b.png)

也就是前台界面不显示存在的项目，我已经尝试Ctrl+ F5 刷新界面，注销登录重新登录，更换浏览器，使用手机访问，重启nginx，php，依旧无效，现在不知道咋整

**Comment by star7th** [comment]
感觉是没更新好数据库。
确定给了文件写的权限后，再执行http://x.com/index.php?s=/home/update/db

**Comment by szkzn** [comment]
莫名其妙解决了，重新执行一次https://xxx.xxx/index.php?s=/home/update/db,前台界面恢复正常了
