### ISSUE TITLE
需要帮忙手动安装

### ISSUE THREAD

**Issue by greendragon70** [star7th/showdoc#549]
你好，通过手动安装得了这 个bug
![Screenshot 2019-06-01 at 00 41 32](https://user-images.githubusercontent.com/13272013/58721156-cae22800-8406-11e9-9df5-3f4019ff46f9.png)

我安装在 /technical, 访问 technical/server/index.php?s=/api/user/login 的到这。自己对 ThinkPHP 不熟。花了几天还是不能debug.

Centos 78.0.24
Apache 2.4
PHP 5.6

**Comment by star7th** [comment]
请先查看常见问题以及搜索下历史issue。如果那些方式搞不定的话也没办法。

greendragon70 <notifications@github.com>于2019年6月1日 周六上午12:54写道：

**Comment by star7th** [comment]
建议使用docker安装

Chen Xing <xing7th@gmail.com>于2019年6月1日 周六下午1:36写道：
