### ISSUE TITLE
 建议提供项目查询 api, 方便项目自定义导出

### ISSUE THREAD

**Issue by gudqs7** [star7th/showdoc#551]

**Comment by star7th** [comment]
有这个编程能力了为何不直接读取数据库。就是执行sql的问题，各大语言都可以访问sqlite

心累 <notifications@github.com>于2019年6月4日 周二上午10:56写道：

**Comment by gudqs7** [comment]
@star7th  我想把 showdoc.cc 里面的项目导出来.... 倒不是自己服务器里面的.....

**Comment by star7th** [comment]
showdoc.cc一开始就是为在线服务设计的。不会为私有化做考虑。既然有私有化需求一开始就应该用开源版，又干嘛占用官方服务器资源。现在，手机复制文档过去是你的唯一办法。

心累 <notifications@github.com>于2019年6月4日 周二上午10:59写道：
