### ISSUE TITLE
编辑权限范围

### ISSUE THREAD

**Issue by heimao0307** [star7th/showdoc#552]
前置条件:成员A和B都有编辑权限
操作步骤:
1.成员A创建页面
2.成员B直接点删除,提示没权限(正常)
3.成员B点击编辑,随便改一下,点击保存,然后就可以删除这个页面了,所有记录都没有了.

实际结果:用户A辛辛苦苦编辑创建的页面存在被用户B修改和误删的可能性.
期望结果:用户B在编辑之后,只能删除自己编辑的部分;或者删除后留下删除记录,便于留下"犯罪证据";或者管理员拥有恢复删除页面的选项.

多谢~

**Comment by star7th** [comment]
其实编辑权限就是删除权限了。比如把文档编辑为空，那跟删除有什么区别呢。
所以说，只要有编辑权限，其实就等同于删除权限。真不想删除的话，只能设置只读成员了

许杰辉 <notifications@github.com> 于2019年6月4日周二 下午3:08写道：

**Comment by heimao0307** [comment]
了解了~感谢~
