### ISSUE TITLE
评论功能||Issue功能

### ISSUE THREAD

**Issue by suveng** [star7th/showdoc#553]
增加评论||提issue的功能,可以让团队之间更好的维护好文档

**Comment by star7th** [comment]
团队一般都有自己惯用的即时聊天工具吧。即时聊天工具不是更快吗。
说实话我对评论需求并不是很明晰，不清楚多少人会有这样的需求。

**Comment by suveng** [comment]
> 团队一般都有自己惯用的即时聊天工具吧。即时聊天工具不是更快吗。
> 说实话我对评论需求并不是很明晰，不清楚多少人会有这样的需求。

emm...公司分部门,部门分团队,部门和部门间....你懂得

**Comment by star7th** [comment]
不是单做一个评论功能就可以了的。按你的说法，想解决跨团队跨部门的沟通，实际上评论了也未必能通知到他们。后面要配套做邮件通知短信通知等一系列动作。

**Comment by 1Gbps** [comment]
Showdoc should be as concise as possible, it is a pure online document writing tool rather than a team collaboration tool. I think adding comments is superfluous.

**Comment by conanliuhuan** [comment]
楼主需要的其实是GitLab吧？

**Comment by mengdodo** [comment]
@suveng  我觉得需求并不强

**Comment by douyaolai** [comment]
预期这样的话，还不如提供对接 钉钉或者 企业微信的接口，类似禅道（钉钉）
