### ISSUE TITLE
关于一个符号问题

### ISSUE THREAD

**Issue by zhiwen-chen** [star7th/showdoc#554]
’在这个符号会多处空白了，比如I'm就变成了I'  m这种情况，不适合阅读习惯，如果方便更改，麻烦解决一下，谢谢

**Comment by star7th** [comment]
看了一下，没有办法。请规避使用这种情况。
showdoc使用这个开源编辑器，是编辑器本身的特性或者说bug https://pandao.github.io/editor.md/

**Comment by zhiwen-chen** [comment]
好的，谢谢
