### ISSUE TITLE
关于Ldap的使用咨询

### ISSUE THREAD

**Issue by xb191799981** [star7th/showdoc#555]
我能找到这个位置，但是每个文本框写的是啥意思呢？
ladp host: 请求认证的URL。
ladp port:  认证URL的端口
接下来那些是个啥，我就不明白了。

![图片](https://user-images.githubusercontent.com/6196072/59477867-ac117600-8e89-11e9-853e-dff97e0d4e26.png)

**Comment by star7th** [comment]
问你的Ldap管理员或者负责人。Ldap的字段有哪些都不知道还用什么Ldap
