### ISSUE TITLE
SQL转数字字典问题

### ISSUE THREAD

**Issue by qungoo** [star7th/showdoc#557]
我以前用过showdoc，有个“SQL转数字字典”功能，刚部署了新版，好像没了这个功能。是移到其他地方？还是已经去掉了？
请看以下截图
![image](https://user-images.githubusercontent.com/22866270/59501422-13e9b000-8ece-11e9-81ae-2f949db664eb.png)

**Comment by star7th** [comment]
好像这个不是官方功能。我不知道你是用谁改写过的版本。

qungoo <notifications@github.com>于2019年6月14日 周五下午5:59写道：

**Comment by qungoo** [comment]
好的，谢谢。建议加上这个功能，挺好用的。

**Comment by star7th** [comment]
不打算加上这样的功能。不是所有人都需要用到。

qungoo <notifications@github.com> 于2019年6月14日周五 下午6:18写道：
