### ISSUE TITLE
[BUG] 分享页面时修改项目访问密码要重新进入链接

### ISSUE THREAD

**Issue by elinxer** [star7th/showdoc#558]
分享一个页面出去的时候，因为是私密项目，使用方提示需要密码，这边给与了错误的密码，提示密码错误，同时项目修改了密码重新给使用方，使用方需要按链接重新进入，否则都是密码错误。

**Comment by star7th** [comment]
暂时不管这种参杂了人为错误的问题。

zhiteer <notifications@github.com>于2019年6月15日 周六下午3:26写道：
