### ISSUE TITLE
[feature] 建议提供一个私密项目单页分享到外部的功能

### ISSUE THREAD

**Issue by elinxer** [star7th/showdoc#559]
由于内部文档项目以及对外对接过多，经常需要发出文档，但又不能加别人进入项目，如果有可以分享一条单独的链接可以直接公开访问的就好了。

**Comment by star7th** [comment]
这种又要私密又要公开的需求比较复杂。
为什么不能把要分享的项目单独一个公开项目给别人访问。

zhiteer <notifications@github.com>于2019年6月15日 周六下午3:28写道：

**Comment by enyusmile** [comment]
和#542的需求大概是一样的

**Comment by star7th** [comment]
新版刚新增了此功能。分享页面的时候，将允许创建加密页面地址。任何得知该单页地址的用户都可以公开访问到此页面内容。
