### ISSUE TITLE
修改脚本规则

### ISSUE THREAD

**Issue by EchoYoung2019** [star7th/showdoc#560]

**Comment by EchoYoung2019** [comment]
showdoc_api.sh这个脚本提交文件中的解释文件，网页服务端根据脚本提交的内容，解析并修改后端数据。如何修改这个规则，如去掉@url https://www.showdoc.cc/home/user/login这条的解析。

**Comment by Peter756729890** [comment]
同问

**Comment by star7th** [comment]
规则是写在server/Application/Api/Controller/FromCommentsController.class.php

**Comment by Peter756729890** [comment]
多谢，刚grep到，正在脑壳疼，怎么修改规则。

**Comment by star7th** [comment]
没必要用官方的这个接口改写。自己独立写个脚本调用高级api更自由一些。
