### ISSUE TITLE
升级后部分html代码显示为文本

### ISSUE THREAD

**Issue by zhanxijin** [star7th/showdoc#561]
以前用有点旧的showdoc版本，php手动安装的，跑在公司站点上。
以前可以直接在文档里面写个form表单，做提交测试，可以直接正常解析出来。
升级后显示成了文本，非常多的文档里面都有这个测试表单，不知道应该如何处理。
![image](https://user-images.githubusercontent.com/16527309/59593390-6fad7680-9124-11e9-8267-5680dd8867d8.png)

**Comment by star7th** [comment]
本来就不应该支持写form表单，没有几个写作平台支持这么搞的。你一开始就不应该这样写。
两年前的旧版，官方放弃维护了。

zhanxijin <notifications@github.com>于2019年6月17日 周一下午5:23写道：

**Comment by zhanxijin** [comment]
好的谢谢。
showdoc用了超过三年了，写了无数的文档，感谢你们开源这么好的东西。
那关于表单这个问题我自己想办法处理。
