### ISSUE TITLE
showdoc超管角色

### ISSUE THREAD

**Issue by hansedong** [star7th/showdoc#562]
请问，showdoc 中有没有超管角色？
项目的创建者，貌似具备项目的绝对管理，包括添加成员等操作。但是如果项目的创建者离职，有没有超管可以看到所有的项目，并接受项目的管理？

**Comment by star7th** [comment]
新版showdoc有超管。showdoc/123456
不先做好交接就跑路这是属于人为责任。我估计这些账户你都没有。

**Comment by star7th** [comment]
你先全新安装一个showdoc，安装完毕会提醒你的

**Comment by enyusmile** [comment]
针对此场景,功能上:角色showDoc可以先把项目转让给自己,然后项目不就可以继续操作了?

**Comment by hansedong** [comment]
> 新版showdoc有超管。showdoc/123456
> 不先做好交接就跑路这是属于人为责任。我估计这些账户你都没有。

的确，是存在不交接就跑路的，不过小团队一多，不同团队内部没有把控的话，是属于人为责任。
不过，现在showdoc用的人有点多，内容也多。全新安装一个是可以，但如果完全做数据库迁移，showdoc用户是不是会被覆盖掉？有没有相关的迁移工具？既可以保留showdoc超管，数据同步也能安全的转义？

**Comment by star7th** [comment]
我实在理解不了你说的"保留showdoc超管"和“数据同步也能安全的转义”是什么意思，我也不明白你要做什么。
如果你要升级程序的话，根据部署手册来。https://www.showdoc.cc/help?page_id=13732
