### ISSUE TITLE
安装离线版，进入后台后样式错乱

### ISSUE THREAD

**Issue by pz9042** [star7th/showdoc#565]
centos7.6+php7.2.19
![image](https://user-images.githubusercontent.com/5012019/59913541-e6ab7d80-944a-11e9-9710-074ebb2632f1.png)

php没有报错，浏览器console也没有报错

**Comment by star7th** [comment]
单凭这个截图无法看出什么问题。
showdoc被那么多人安装过了，这个问题应该只会你自己的安装方式不对而已。建议使用官方自动脚本安装，其他方式的，自己就要多动手了

**Comment by star7th** [comment]
我个人感觉你可能使用了nginx重定向。如果是那样，自己确保规则写好。

**Comment by pz9042** [comment]
> 我个人感觉你可能使用了nginx重定向。如果是那样，自己确保规则写好。

找到原因了，include mine.types这个文件没加载，搞得css请求响应里的content-type 还是text/plain，include后就好了
