### ISSUE TITLE
API多次修改下搜索会返回多条重复记录

### ISSUE THREAD

**Issue by jackeylu** [star7th/showdoc#567]
安装了Showdoc后，我们利用/api/open/fromComments向自建的内部ShowDoc服务器添加API。
在测试过程中发现，如果通过该API多次添加了后，在搜索时会返回最新和历史的结果。

是否可以只返回最新的结果？

showdoc的版本和安装方式：
通过./showdoc 安装的最新版本
[jack@local ~]$ docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
star7th/showdoc               latest              f6c7a183a1e3        9 days ago          383MB

示例的检索结果

![image](https://user-images.githubusercontent.com/1175396/60240029-4047f800-98e2-11e9-98f6-a8431283a17a.png)

查看每篇文章的详情：

![image](https://user-images.githubusercontent.com/1175396/60240078-6a99b580-98e2-11e9-8b02-73c0c519f029.png)

![image](https://user-images.githubusercontent.com/1175396/60240065-5eadf380-98e2-11e9-8945-56090f8d88d4.png)

![image](https://user-images.githubusercontent.com/1175396/60240098-78e7d180-98e2-11e9-9454-7ed3b6450583.png)

**Comment by jackeylu** [comment]
不懂PHP和PHP开发框架，只找到关键词在vue文件中是 input_keyword，但后面是怎么处理的，没找到相关的代码，不知道怎么改进或者是定制调整。

**Comment by star7th** [comment]
把搜索前的目录菜单截图说明下

Lin Lyu <notifications@github.com> 于2019年6月27日周四 下午1:52写道：

**Comment by jackeylu** [comment]
@star7th 目录太长，我就收起其他目录，截取了包含“股价小于10的股票”的目录，如下

![image](https://user-images.githubusercontent.com/1175396/60556142-7ff36180-9d72-11e9-915c-c72fbdae2910.png)

检索以“股价”为关键词，在我的环境中，会搜索出三条结果（见一楼），今天复现时发现，三个结果的URL链接有不一样，分别是
page_id=78
page_id=158
page_id=238

另外，完整的目录（仅仅文件夹）如下：

![image](https://user-images.githubusercontent.com/1175396/60556220-dc568100-9d72-11e9-83bb-4183a2fd8c7a.png)

**Comment by star7th** [comment]
我觉得你有可能把页面也生成到其他目录去了吧，所以有重复页面。我让你截图目录菜单主要是想确认是不是有重复页面在不同目录。但这个截图看不到。你每个目录都确认下看是否重复。

**Comment by jackeylu** [comment]
sqlite数据库中page表中能够查到 page_title 符合检索条件的记录是三条。

![image](https://user-images.githubusercontent.com/1175396/60556445-e75de100-9d73-11e9-8fdb-7f5f4ba45985.png)


需要把sqlite数据库文件发给您吗？ @star7th

**Comment by star7th** [comment]
这些页面的目录id不一样啊。果然是因为在不同目录的缘故。

**Comment by jackeylu** [comment]
> 我觉得你有可能把页面也生成到其他目录去了吧，所以有重复页面。我让你截图目录菜单主要是想确认是不是有重复页面在不同目录。但这个截图看不到。你每个目录都确认下看是否重复。

从展现出来的页面上看，只有1个目录里面有这个页面。。。

> 这些页面的目录id不一样啊。果然是因为在不同目录的缘故。

**Comment by jackeylu** [comment]
> 这些页面的目录id不一样啊。果然是因为在不同目录的缘故。

我用Showdoc的导出功能，将整个项目导出成一个doc，检索“股价小于10”，记录只有一条

**Comment by star7th** [comment]
查看下那几个页面所在的目录id，然后根据id去catalog表查下这些目录是什么。
一种可能的情况是，这些也许是被删除了的目录

**Comment by star7th** [comment]
另外为了防止旧版影响，更新到新版。你原来的showdoc是什么时候安装的

**Comment by jackeylu** [comment]
> 另外为了防止旧版影响，更新到新版。你原来的showdoc是什么时候安装的

12 天前通过您的安装脚本安装的，用的是docker镜像

**Comment by star7th** [comment]
12天前应该还是比较新的。你先看下这些目录是什么吧

**Comment by jackeylu** [comment]
> 查看下那几个页面所在的目录id，然后根据id去catalog表查下这些目录是什么。
> 一种可能的情况是，这些也许是被删除了的目录

sqlite> select cat_id, cat_name, item_id, s_number, addtime from catalog where cat_id in (24,33,41);
24|新选股|1|99|1561611498
33|新选股|1|99|1561611908
41|新选股|1|99|1561611949

**Comment by star7th** [comment]
我搞不懂你的情况。我觉得可能是因为这些数据乱了引起，不是普遍的api接口问题。你测试其他页面看能否修改。
如果其他页面正常，证明这个只是特例，就把这些多余数据删除掉吧

Lin Lyu <notifications@github.com>于2019年7月3日 周三上午9:39写道：

**Comment by jackeylu** [comment]
OK，我也不清楚这些脏数据是怎么产生的。我把数据库中 page_id 不需要的删除就好了。
