### ISSUE TITLE
网站 404 

### ISSUE THREAD

**Issue by zhuochengs** [star7th/showdoc#569]
网站打不开了，nginx404  请教大神，你们的服务器挂了吗？还是在升级？

**Comment by zhuochengs** [comment]
https://www.showdoc.cc/

**Comment by rexen-rdc** [comment]
首页还是无法打开那

**Comment by star7th** [comment]
由于showdoc受到一些流量攻击，导致后台有些服务因负荷过大而挂掉。现在重装服务器以及做了限流设置，已经恢复正常访问。

lq <notifications@github.com> 于2019年7月2日周二 下午2:14写道：
