### ISSUE TITLE
Multilanguage version

### ISSUE THREAD

**Issue by mambax7** [star7th/showdoc#57]
do you plan a multi-language version?

**Comment by star7th** [comment]
Oh , I used to think ShowDoc is only used by Chinese. I will provide an English version after a few days or weeks

**Comment by mambax7** [comment]
Great! Thank you!

**Comment by star7th** [comment]
English version:https://github.com/star7th/showdoc

**Comment by mambax7** [comment]
Awesome!!! Thank you very much!
