### ISSUE TITLE
如果按照官方文档对showdoc进行版本升级，已有的数据会丢失么？

### ISSUE THREAD

**Issue by shenhaichangmian** [star7th/showdoc#570]

**Comment by star7th** [comment]
不会

shenhaichangmian <notifications@github.com> 于2019年7月3日周三 下午3:52写道：

**Comment by liwenchao1984** [comment]
可以用navicat打开sqllite数据库，
新版的数据库 添加了三张新表， 原来的表结构不变。
快速升级三步骤，
1. 可以用docker拉一个新镜像。
2. 然后把旧版数据库，加上三张新表，
3. 再把Public/Uploads目录复制过来就行了。

**Comment by star7th** [comment]
别听第三方的做法。严格按照官网文档来。

liwenchao1984 <notifications@github.com> 于2019年7月10日周三 上午10:51写道：

**Comment by star7th** [comment]
@liwenchao1984 你说的办法并不是通用的方法，某些情况下会导致升级错乱。比如说我对原有的表结构更改的时候（而不只是新增表结构）

**Comment by rpmdeb** [comment]
docker方式 升级有没有更简单的方式？ 建议把数据表结构升级单独弄个升级脚本，这样的话，更新方式可以简化：
1. 备份原数据表和上传的文件
2. 直接拉取最新的镜像
3. 然后执行数据表 升级(每次对上一个版本进行升级，比如 upgrade-1.1.0-to-1.1.1.sql  upgrade-1.1.1-to-1.1.2.sql  ，不管用户在哪一个版本，只要按照这个步骤来，肯定能升级到最新的版本  )
4. 启动新的镜像，挂载原来的数据目录

**Comment by star7th** [comment]
最简单的方式我已经做成脚本了，使用官方脚本安装的话执行./showdoc update
就可以升级。其他方式，默认就是需要多动手的。就不优化其他方式了。官方一直推荐使用自动脚本

rpmdeb <notifications@github.com> 于2019年10月17日周四 下午2:52写道：
