### ISSUE TITLE
目前免费版本的showdoc上传附件只能是4m以内的附件，上传附件大小的限制如何调大一些呢？

### ISSUE THREAD

**Issue by shenhaichangmian** [star7th/showdoc#571]

**Comment by star7th** [comment]
要先说一下自己是怎么部署的

**Comment by star7th** [comment]
即采用什么部署方式。附件上传大小跟showdoc没关系，只是要修改你的安装环境配置

**Comment by liwenchao1984** [comment]
作者你好， 我使用docker安装的showdoc,  尝试上传10M的zip文件，失败。

请问修改哪个配置，可以设置最大上传文件的大小。

**Comment by star7th** [comment]
@liwenchao1984 我之前只是改了上传图片的大小限制。附件的限制没去掉。现在也去掉了。更新下。
如果是使用官方脚本或者docker安装的，应该就可以上传大一点的文件了。其他安装方式的话需要自行修改nginx

**Comment by liwenchao1984** [comment]
感谢。docker重新拉取镜像后试了一下，可以上传10M以上的文件了。
感谢。

**Comment by xyufs** [comment]
> @liwenchao1984 我之前只是改了上传图片的大小限制。附件的限制没去掉。现在也去掉了。更新下。
> 如果是使用官方脚本或者docker安装的，应该就可以上传大一点的文件了。其他安装方式的话需要自行修改nginx

你好，我今天新升级了系统，但是上传附件还是限制4M，我是手动安装和手动升级的，请问改怎么修改限制4m的问题

**Comment by star7th** [comment]
@xyufs 其他安装方式需要自行修改nginx和php的允许最大上传文件大小。自己去搜索下。默认情况下，会手动安装的人就是动手能力强，我不会手把手教你怎么做。我只是会把官方docker镜像做到开箱即可用。

**Comment by xyufs** [comment]
> @xyufs 其他安装方式需要自行修改nginx和php的允许最大上传文件大小。自己去搜索下。默认情况下，会手动安装的人就是动手能力强，我不会手把手教你怎么做。我只是会把官方docker镜像做到开箱即可用。

嗯。修改了nginx的配置，没有修改php的配置，已解决，多谢了！

**Comment by lixiaodao01** [comment]
> 
> 
> > @xyufs 其他安装方式需要自行修改nginx和php的允许最大上传文件大小。自己去搜索下。默认情况下，会手动安装的人就是动手能力强，我不会手把手教你怎么做。我只是会把官方docker镜像做到开箱即可用。
> 
> 嗯。修改了nginx的配置，没有修改php的配置，已解决，多谢了！

您好，请问您修改的是哪个路径下的配置文件？我用docker自动脚本安装的，搜了一下nginx.conf文件，只搜到了docker下的，修改了/var/lib/docker/overlay2/6beacb27c308714fbc98f2b9d73ffb79452ffefd1793fb1adf70ad879937e6b6/diff/etc/nginx/nginx.conf中的client_max_body_size 100m为4096m，但仍然不能上传大于100m的文件，进度条可以上传完成，但最后没法保存成功。

**Comment by Musicminion** [comment]
> 

我是手动安装的，修改的是php.ini文件，里面之前的大小好像限制为4M，适当增加即可，我的目录在 `etc/php/7.2/apache/php.ini`
好像还有内存什么的，也可以改大一点
