### ISSUE TITLE
在api_key api_token 输入正确的情况下,请求上传接口返回api_key 或 api_token 不匹配

### ISSUE THREAD

**Issue by llongtao** [star7th/showdoc#577]
不知道会有哪些原因导致的

{"error_code":10306,"error_message":"api_key 或 api_token 不匹配"}

api_key api_token绝对没问题

**Comment by star7th** [comment]
别说什么绝对没问题的事情。
绝对有问题。程序逻辑被很多人验证过了，没问题。

**Comment by star7th** [comment]
留意url是不是正确的url

**Comment by star7th** [comment]
如果自己排查不了问题请仔细描述自己使用的过程以及出现的现象。

**Comment by llongtao** [comment]
> 如果自己排查不了问题请仔细描述自己使用的过程以及出现的现象。

问题找到了,谢谢

公网的showdoc支持json的body,而部署在本地的仅支持表单(可能是版本问题),
希望在 https://www.showdoc.cc/page/102098
增加详细描述,避免有人再跳坑
