### ISSUE TITLE
宝塔面板搭建的无法上传图片

### ISSUE THREAD

**Issue by jasonfanjun** [star7th/showdoc#578]
宝塔面板搭建的无法上传图片
直接上传图片无反应噢。

**Comment by star7th** [comment]
查看网络请求返回什么内容

**Comment by jasonfanjun** [comment]
Request URL: https://book.shuohui.cn/server/index.php?s=/api/page/uploadImg&guid=1563258334732
Request Method: POST
Status Code: 404 Not Found

Failed to load resource: the server responded with a status of 404 (Not Found)
/web/#/page/edit/3/0:3 Uncaught SyntaxError: Unexpected token : in JSON at position 2
    at JSON.parse (<anonymous>)
    at HTMLIFrameElement.uploadIframe.onload (image-dialog.js:161)
index.php:1 Failed to load resource: the server responded with a status of 404 (Not Found)
/web/#/page/edit/3/0:3 Uncaught SyntaxError: Unexpected token : in JSON at position 2
    at JSON.parse (<anonymous>)
    at HTMLIFrameElement.uploadIframe.onload (image-dialog.js:161)
/server/index.php?s=/api/page/upload:1 Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.min.js:3 POST https://book.shuohui.cn/server/index.php?s=/api/page/uploadImg&guid=1563258334732 404 (Not Found)
trigger @ jquery.min.js:3
(anonymous) @ jquery.min.js:3
each @ jquery.min.js:2
each @ jquery.min.js:2
trigger @ jquery.min.js:3
(anonymous) @ image-dialog.js:176
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
VM36:3 Uncaught SyntaxError: Unexpected token : in JSON at position 2
    at JSON.parse (<anonymous>)
    at HTMLIFrameElement.uploadIframe.onload (image-dialog.js:161)

**Comment by jasonfanjun** [comment]
:(

Call to a member function assign() on null
错误位置
FILE: /www/wwwroot/book.shuohui.cn/showdoc-master/server/ThinkPHP/Library/Think/Controller.class.php 　LINE: 122

TRACE
#0 /www/wwwroot/book.shuohui.cn/showdoc-master/server/ThinkPHP/Library/Think/Controller.class.php(272): Think\Controller->assign('msgTitle', '\xE6\x93\x8D\xE4\xBD\x9C\xE5\xA4\xB1\xE8\xB4\xA5\xEF\xBC\x81')
#1 /www/wwwroot/book.shuohui.cn/showdoc-master/server/ThinkPHP/Library/Think/Controller.class.php(187): Think\Controller->dispatchJump('\xE4\xB8\x8A\xE4\xBC\xA0\xE6\xA0\xB9\xE7\x9B\xAE\xE5\xBD\x95...', 0, '', false)
#2 /www/wwwroot/book.shuohui.cn/showdoc-master/server/Application/Api/Controller/PageController.class.php(243): Think\Controller->error('\xE4\xB8\x8A\xE4\xBC\xA0\xE6\xA0\xB9\xE7\x9B\xAE\xE5\xBD\x95...')
#3 [internal function]: Api\Controller\PageController->uploadImg()
#4 /www/wwwroot/book.shuohui.cn/showdoc-master/server/ThinkPHP/Library/Think/App.class.php(173): ReflectionMethod->invoke(Object(Api\Controller\PageController))
#5 /www/wwwroot/book.shuohui.cn/showdoc-master/server/ThinkPHP/Library/Think/App.class.php(110): Think\App::invokeAction(Object(Api\Controller\PageController), 'uploadImg')
#6 /www/wwwroot/book.shuohui.cn/showdoc-master/server/ThinkPHP/Library/Think/App.class.php(204): Think\App::exec()
#7 /www/wwwroot/book.shuohui.cn/showdoc-master/server/ThinkPHP/Library/Think/Think.class.php(120): Think\App::run()
#8 /www/wwwroot/book.shuohui.cn/showdoc-master/server/ThinkPHP/ThinkPHP.php(97): Think\Think::start()
#9 /www/wwwroot/book.shuohui.cn/showdoc-master/server/index.php(24): require('/www/wwwroot/bo...')
#10 {main}

ThinkPHP3.2.3 { Fast & Simple OOP PHP Framework } -- [ WE CAN DO IT JUST THINK ]

**Comment by star7th** [comment]
先尝试给整个代码目录777权限

jasonfanjun <notifications@github.com> 于2019年7月16日周二 下午2:52写道：

**Comment by star7th** [comment]
另外我推荐官方自动脚本安装。

Chen Xing <xing7th@gmail.com> 于2019年7月16日周二 下午2:53写道：

**Comment by jasonfanjun** [comment]
目录已经全部给到777权限。应该不是权限问题

**Comment by star7th** [comment]
程序是没问题的，毕竟这么多人安装过都可以上传图片和附件。应该是你安装的环境不对。 只能说推荐使用官方脚本安装了

jasonfanjun <notifications@github.com> 于2019年7月16日周二 下午2:56写道：
