### ISSUE TITLE
是否有部署https的教程

### ISSUE THREAD

**Issue by MegatronKing** [star7th/showdoc#580]
默认的是http，如果二次开发部署https，想请教下有哪些部分是需要修改的？

**Comment by star7th** [comment]
跟showdoc完完全全没关系。建议去了解nginx怎么配置https，以及怎么转发到4999端口

Megatron King <notifications@github.com> 于2019年7月18日周四 下午3:35写道：

**Comment by MegatronKing** [comment]
谢谢，我犯二了，可以直接用nginx反向代理
