### ISSUE TITLE
请问密码加密方式和用户名有关吗？

### ISSUE THREAD

**Issue by jasonfanjun** [star7th/showdoc#581]
我需要知道加密方式，因为我把用户名进行修改后   单纯的将密码md5加密是不行的

**Comment by star7th** [comment]
1，加密方式不是手动就可以做到。不建议通过手动改数据库的方式改密码。
2，改用户名不会导致密码变化。但是该用户名引起的逻辑混乱是难说的，因为程序一开始的设定就是基于用户名唯一。
3，改密码请通过管理后台进行。如果没看到管理后台，请升级新版

jasonfanjun <notifications@github.com> 于2019年7月19日周五 下午5:13写道：

**Comment by jasonfanjun** [comment]
换域名会导致无法登录吗？因为我刚才将同样的源码 复制到另一台服务器上 绑定了其他域名就不行了

**Comment by star7th** [comment]
你这样会搞得我不耐烦的。你就没想过新服务器的环境真的跟原来的一模一样吗。我不花时间帮你排查服务器本身的问题。源码一样却无法运行，这明显是环境问题。不信你再把新源码再次复制回旧旧环境再给可写权限。
另外，官方推荐使用自动脚本安装。

jasonfanjun <notifications@github.com>于2019年7月19日 周五下午5:38写道：

**Comment by jasonfanjun** [comment]
感谢你回复，让你感觉不耐烦很抱歉。
环境完全一样直接镜像。我只是在排查，希望你提供线索而已。
如果没有技术能力提供支持，请回复拒绝。没必要吹胡子瞪眼的。
提供平台进行交流，本来就是你情我愿。

**Comment by star7th** [comment]
建议按照这个方式迁移服务器：https://www.showdoc.cc/help?page_id=2511252204165611

**Comment by star7th** [comment]
如果原有文档里已经有上传的图片和附件，换新的域名的时候也许访问不了。可参考这里修改其路径：https://github.com/star7th/showdoc/issues/102
