### ISSUE TITLE
文档保存失败，上传图片失败

### ISSUE THREAD

**Issue by daimon-d** [star7th/showdoc#582]
项目是从另外一台服务器直接整个迁移过来的，现环境nginx1.14.2+php5.6.2，问题是，新建文档保存没问题，重新编辑再保存会弹出空白提示框，并且文档不保存；另外修改目录、粘贴截图、上传图片也是同样的现象，在迁移之前是没有问题的

**Comment by star7th** [comment]
参考这个教程迁移。其他方式的话，出了问题很难排查 https://www.showdoc.cc/help?page_id=2511252204165611

**Comment by daimon-d** [comment]
还有，之前的服务器版本是centos7.2，nginx1.12.2+PHP 7.1.10，现在是centos6.8，nginx1.14.2+PHP 5.6.2

**Comment by star7th** [comment]
跟着教程，首先全新安装，然后再升级

**Comment by daimon-d** [comment]
这个已经解决了，是少装了php-zlib模块，感谢大佬
