### ISSUE TITLE
求给个详细的后端API接口文档

### ISSUE THREAD

**Issue by conanliuhuan** [star7th/showdoc#584]
想重构ShowDoc的前端部分，希望能在官方说明里面提供一下详细的后端API接口，包括提交和返回数据示例等。

**Comment by star7th** [comment]
基本上很少人有这种需求。单单为小量需求而写大量的文档是不太建议的事情。
我更建议你查看浏览器的网络请求。看看提交了什么参数以及相应的返回结果

conanliuhuan <notifications@github.com> 于2019年7月25日周四 下午4:32写道：
