### ISSUE TITLE
升级后旧项目分享页提示没有权限，需要重新分享链接出去才行

### ISSUE THREAD

**Issue by gtcfla** [star7th/showdoc#585]
![image](https://user-images.githubusercontent.com/12646335/62017990-5d2a6080-b1eb-11e9-9017-e520b735d838.png)
![image](https://user-images.githubusercontent.com/12646335/62018009-6f0c0380-b1eb-11e9-9af6-57c236ca50e7.png)
升级后访问旧项目分享链接提示上面的提示。
旧项目分享出去的页面链接格式：http://域名/index.php?s=/page/187
需要重新分享项目页面链接地址，升级后的链接地址：http://域名/web/#/17?page_id=187
影响点：旧项目分享出去的链接的访问和使用。

另外提个小需求：新项目分享单页面出去后是整个项目目录是可见，如果保持跟旧项目只可见单个页面就好了。

**Comment by star7th** [comment]
http://域名/index.php?s=/page/187 <http://xn--eqrt2g/index.php?s=/page/187>
 是旧版单页面链接
 http://域名/web/#/17?page_id=187 <http://xn--eqrt2g/web/#/17?page_id=187>
是项目页面链接。

新版的单页链接形式是 http://域名/index.php?s=/p
<http://xn--eqrt2g/index.php?s=/page/187>/{md5} ，同时向后兼容。

我不是很理解你这些问题是怎么冒出来的。提供项目地址看下。

zen <notifications@github.com> 于2019年7月29日周一 上午10:35写道：

**Comment by gtcfla** [comment]
这个是我旧项目的分享页地址：http://showdoc.devp.play800.cn/index.php?s=/page/187
升级后的项目地址（需要绑hosts没解析：120.26.161.248 test.showdoc.devp.play800.cn）：http://test.showdoc.devp.play800.cn/index.php?s=/page/187

**Comment by star7th** [comment]
好像原有的模式不支持加密项目的单页分享。把项目密码去掉就可以。或者用新的分享链接

zen <notifications@github.com> 于2019年7月29日周一 上午10:48写道：

**Comment by gtcfla** [comment]
嗯，但是旧项目是允许这样的啊，如果我升级之后，之前给出去的链接地址就访问不了，需要重新给链接出去（有点蛋疼）

**Comment by star7th** [comment]
去掉访问密码就行

zen <notifications@github.com> 于2019年7月29日周一 上午11:01写道：

**Comment by gtcfla** [comment]
问题是要保留这个访问密码不能去掉)-p
