### ISSUE TITLE
docker安装失败，有镜像pull下拉但是没有生成源代码

### ISSUE THREAD

**Issue by gtcfla** [star7th/showdoc#586]
安装手册是根据：https://www.showdoc.cc/help?page_id=65610
镜像是已经pull下来了，但是执行下面命令：
docker run -d --name showdoc -p 4999:80 -v /showdoc_data/html:/var/www/html/      star7th/showdo
在/showdoc_data/html下看不到源代码，已给777权限. 容器已成功启动，但是没有源代码。

在macbook（docker版本没细看）、centos6.5（Docker version 1.7.1, build 786b29d）、windows10（Docker version 18.09.2, build 6247962）下都没有showdoc的源代码。

**Comment by star7th** [comment]
有执行了文档里说的命令？
![image](https://user-images.githubusercontent.com/2200494/62018708-6832c000-b1ee-11e9-9b75-deab0105b515.png)

**Comment by gtcfla** [comment]
嗯嗯，现在可以了，感谢!!!!我记得之前好像有执行这个.....

**Comment by gtcfla** [comment]
docker exec showdoc \cp -fr /data/www/showdoc_data/html /var/www/
cp: can't stat '/data/www/showdoc_data/html': No such file or directory
对了，就是报这个错。当我的目录不是用/showdoc_data/html时，就会报这个错误，我是放在/data/www/showdoc_data/html目录下了，showdoc_data是777权限的
