### ISSUE TITLE
是否会背和谐

### ISSUE THREAD

**Issue by wming126** [star7th/showdoc#587]
现在好多可以分享连接的工具都被和谐了，showdoc是否应该考虑分享链接时对内容进行审核？

**Comment by star7th** [comment]
你是指开源版还是指官网

王明 <notifications@github.com> 于2019年7月29日周一 上午11:14写道：

**Comment by star7th** [comment]
另外你举几个例子，哪个被和谐了

Chen Xing <xing7th@gmail.com> 于2019年7月29日周一 上午11:15写道：
