### ISSUE TITLE
后台管理问题

### ISSUE THREAD

**Issue by 1712825001** [star7th/showdoc#588]
使用的是老版本的 showdoc ，使用默认用户登录没有后台管理，是版本问题吗

**Comment by star7th** [comment]
是

1712825001 <notifications@github.com> 于2019年7月29日周一 下午3:56写道：

**Comment by 1712825001** [comment]
升级会解决吗？

**Comment by star7th** [comment]
会。升级后刷新浏览器js缓存

1712825001 <notifications@github.com> 于2019年7月29日周一 下午4:07写道：

**Comment by 1712825001** [comment]
好的，多谢
