### ISSUE TITLE
能否在每个文档下增加个文档路径功能

### ISSUE THREAD

**Issue by qq15870939565** [star7th/showdoc#590]
![image](https://user-images.githubusercontent.com/37894759/62112424-4700cb00-b2e5-11e9-9474-1d586988531c.png)

**Comment by qq15870939565** [comment]
如果不是大众要求的话，可否能提供方法，自己增加下，谢谢！

**Comment by star7th** [comment]
不打算这么做。根据左侧栏一眼就看出路径了。

qq15870939565 <notifications@github.com> 于2019年7月30日周二 下午4:16写道：

**Comment by qq15870939565** [comment]
![image](https://user-images.githubusercontent.com/37894759/62112661-b7a7e780-b2e5-11e9-9452-dff61b379bf3.png)

**Comment by star7th** [comment]
没有暴露出方法或者设置让人去做到这个

qq15870939565 <notifications@github.com> 于2019年7月30日周二 下午4:18写道：

**Comment by qq15870939565** [comment]
提供点思路，我自己写下。。哈全

**Comment by star7th** [comment]
二次开发请参考文档： https://www.showdoc.cc/help?page_id=1385576954326448

qq15870939565 <notifications@github.com> 于2019年7月30日周二 下午4:21写道：

**Comment by qq15870939565** [comment]
大神，感觉你跟机器人一样！！！
