### ISSUE TITLE
linux以docker方式安装后找不到端口映射关系

### ISSUE THREAD

**Issue by saysmy** [star7th/showdoc#591]
按照官方教程一步步来安装，可以启动正常，但是找不到端口映射关系，宿主机就无法访问4999端口，报502，请问这是为什么？该怎么解决呢？
![image](https://user-images.githubusercontent.com/5068961/62117440-82ec5e00-b2ee-11e9-8006-172a932afc82.png)
![image](https://user-images.githubusercontent.com/5068961/62117469-926ba700-b2ee-11e9-80ad-832951063fc1.png)
![image](https://user-images.githubusercontent.com/5068961/62117568-bf1fbe80-b2ee-11e9-8167-ae1652f7199b.png)

**Comment by star7th** [comment]
我觉得你可以更详细地讲下你是怎么做的，执行了什么

**Comment by star7th** [comment]
尤其是docker run 那一步，端口映射有没有正常，返回什么提示

**Comment by star7th** [comment]
手动docker安装的教程是https://www.showdoc.cc/help?page_id=65610
请勿改动任何文档上的命令，原封不动地做一遍。

**Comment by saysmy** [comment]
@star7th 你好，照着官方的运行的 docker run -d --name showdoc -p 4999:80 -v /showdoc_data/html:/var/www/html/      star7th/showdoc
运行后出现一个hash值，运行正常。
但docker ps后就是看不到ports映射关系

**Comment by star7th** [comment]
出现了
hash值应该就是成功了。不能成功映射，应该是你本身地系统问题。比如说docker没有改防火墙端口的权限，或者什么权限。是系统对docker存在限制，showdoc本身做不了什么


sunmaoyu <notifications@github.com> 于2019年7月30日周二 下午5:39写道：

**Comment by saysmy** [comment]
@star7th 我又用脚本自动安装了一遍，出现这个错误，，，，，
![image](https://user-images.githubusercontent.com/5068961/62119518-5b979000-b2f2-11e9-9858-ba0ec686717a.png)

**Comment by star7th** [comment]
不是showdoc的问题，是上层系统对docker做了限制。至于做了什么限制，你要问那个一开始安装docker的人。自动脚本也是利用docker安装的。

sunmaoyu <notifications@github.com>于2019年7月30日 周二下午5:49写道：

**Comment by saysmy** [comment]
@star7th docker是我今天刚装的，直接用的yum install docker-io

**Comment by star7th** [comment]
不如尝试下全部卸载。然后在root下，重新跑一遍自动脚本让它自动安装docker。

sunmaoyu <notifications@github.com>于2019年7月30日 周二下午6:01写道：

**Comment by star7th** [comment]
这个是docker本身被系统限制，跟系统配置有关。比如说selinux限制了。等等。环境千差万别，我可能没办法帮你穷举每种可能性了

Chen Xing <xing7th@gmail.com>于2019年7月30日 周二下午6:18写道：

**Comment by saysmy** [comment]
@star7th 自动安装docker失败，必须手动安装。手动安装后，再运行脚本，依然报错。
![image](https://user-images.githubusercontent.com/5068961/62138204-d88a3000-b319-11e9-9253-08de4cebcd75.png)
我发现我的docker版本是不是很低？？是不是因为这个原因导致它没有映射的端口号

**Comment by star7th** [comment]
既然是用云服务器，那就用个新一点的系统安装个新版本的docker

sunmaoyu <notifications@github.com>于2019年7月30日 周二下午10:32写道：

**Comment by saysmy** [comment]
@star7th 你好，我的docker环境升级后配置好了，showdoc也安装成功了。但访问的时候 出现这个页面，请问这个是showdoc的错误页面么？
![image](https://user-images.githubusercontent.com/5068961/62194529-9f4ed000-b3ac-11e9-92c7-47bcbeffae3b.png)

**Comment by star7th** [comment]
不是，看英文看url。

sunmaoyu <notifications@github.com> 于2019年7月31日周三 下午4:03写道：

**Comment by saysmy** [comment]
@star7th 我在宿主机上有一个nginx，然后在这个机器又部署了showdoc的docker服务，已经做了端口映射，但访问这个宿主机的时候，访问不到docker服务，这是怎么回事呢？
![image](https://user-images.githubusercontent.com/5068961/62194878-4cc1e380-b3ad-11e9-9bf9-72c130ebc322.png)
![image](https://user-images.githubusercontent.com/5068961/62194991-98748d00-b3ad-11e9-916e-7b1dd99a5565.png)

想访问xxx.com/doc的时候就访问到showdoc

**Comment by star7th** [comment]
这个东西是配置nginx的问题，是一个通用性问题，跟showdoc没什么关系。建议多搜索网络。你问我我也只能搜索网络回答你。

sunmaoyu <notifications@github.com> 于2019年7月31日周三 下午4:10写道：

**Comment by star7th** [comment]
个人觉得，流量没走到4999端口。可能上层就被引到什么地方去了

Chen Xing <xing7th@gmail.com> 于2019年7月31日周三 下午4:38写道：
