### ISSUE TITLE
docker 运行showdoc就挂掉，什么原因

### ISSUE THREAD

**Issue by hiddendeer** [star7th/showdoc#594]
前两天运行的没问题，今天发现容器挂掉了，docker start container_id后运行一小会又挂掉，端口也没有被别的占用，还有其它的容器运行没什么问题，请问什么原因呢？ PS:日记也没有看出什么

**Comment by star7th** [comment]
尝试重新拉镜像；
检查服务器空间还够不够；
检查docker进程有没有映射端口的权限；
试着用其他镜像映射端口是否成功;
尝试使用官方自动脚本试试

陈帅元 <notifications@github.com>于2019年8月2日 周五下午5:28写道：
