### ISSUE TITLE
你好，页面删除的时候能不能加个确认功能，避免手误。

### ISSUE THREAD

**Issue by chenyf119** [star7th/showdoc#6]

**Comment by star7th** [comment]
好的，此功能已经加好了。

**Comment by star7th** [comment]
新增了支持三级目录的功能；升级安装请参考部署手册中“升级安装”部分。http://blog.star7th.com/2016/05/2007.html
此外我新建了一个ShowDoc使用交流qq群（群号：564671853），欢迎探讨问题
