### ISSUE TITLE
请问网页后缀www.xxx.com/web可以修改吗？

### ISSUE THREAD

**Issue by ma3252788** [star7th/showdoc#601]
我测试了一下，新建项目之后，都会默认到web下，而且项目的路径是数字，比如我新建了一个项目，则项目路径为：`http://www.xxx.com/web/#/2`，请问这个路径可以自定义吗？

**Comment by star7th** [comment]
开源版不支持自定义

arvin <notifications@github.com>于2019年8月10日 周六下午3:41写道：

**Comment by ma3252788** [comment]
请问是有收费版吗？

**Comment by star7th** [comment]
没有。有官网的在线版。

arvin <notifications@github.com>于2019年8月10日 周六下午7:49写道：

**Comment by yidaoqingcheng** [comment]
可以修改的，网站运行目录设置为web目录即可，后缀带#需要添加伪静态

**Comment by yidaoqingcheng** [comment]
不过去掉后缀的#号。伪静态怎么写呢？

**Comment by star7th** [comment]
官方不支持开源版这么做，硬要这么做的可以自行探索。

**Comment by ma3252788** [comment]
> 官方不支持开源版这么做，硬要这么做的可以自行探索。

喔喔，好吧~~
