### ISSUE TITLE
管理员账号无法登陆

### ISSUE THREAD

**Issue by qingchuwudi** [star7th/showdoc#602]
全新安装最新的release版本，安装以后默认的管理员账号无法登陆，提示用户名密码错误。

**Comment by star7th** [comment]
最好能使用官方脚本安装，其他的安装方式我会很难猜用户做了什么，尤其是你没描述你是怎么安装的。而且就算描述了也未必全面，我也不一定能判断什么。能确定的是，这个不是通用问题，因为很多人安装成功了。
还是建议使用官方推荐方式安装

qingchuwudi <notifications@github.com> 于2019年8月11日周日 下午10:50写道：

**Comment by qingchuwudi** [comment]
- 1、下载的release tar包
- 2、在服务器解压到指定目录
- 3、安装php环境、配置nginx
- 4、配置https证书，nginx reload

网站可以正常访问，但是：

* 1、管理员不能登录
* 2、注册帐号验证码一直错误，刷新后还是提示错误

**Comment by star7th** [comment]
安装php-sqlite扩展，以及整个文件夹都给777权限试试

qingchuwudi <notifications@github.com> 于2019年8月12日周一 下午6:47写道：

**Comment by qingchuwudi** [comment]
和之前的情况一样，有日志可以看吗？

**Comment by star7th** [comment]
日志应该不会记录你这样的情况。我没遇到过这种情况。推荐使用官方方式安装。

qingchuwudi <notifications@github.com>于2019年8月13日 周二上午11:35写道：

**Comment by qingchuwudi** [comment]
用docker安装解决了，应该是依赖的问题，建议后面把web目录直接访问所需要的依赖和对应的版本能列出来。

非常感谢！

**Comment by estalent** [comment]
我也遇到同样的问题，安装php7.0-sqlite库好了
