### ISSUE TITLE
写好文档后保存退出，浏览的时候可否改变页面大小？

### ISSUE THREAD

**Issue by huanghailiang** [star7th/showdoc#607]
我在showdoc中制作了一个表格，可能因为表格太长的原因，这时底部会出现一个向右滑动的滚轮，但是此时的浏览界面只占用了电脑屏幕的一半，是否可以改变它，让它一次性全部显示出来？

谢谢！

**Comment by star7th** [comment]
你只能点击右上角的全屏展示按钮。默认情况下，为了保持各个分辨率屏幕的一致性视觉效果，是固定大小的

huanghailiang <notifications@github.com> 于2019年8月19日周一 下午1:59写道：

**Comment by huanghailiang** [comment]
@star7th谢谢您的回复，不过我这边好像并没有全屏展示按钮； 对了我是在本地用自动安装代码配置的showdoc;

如果是单页项目：在我编辑完成以后，退出了编辑界面后，右上角只有分享，编辑和项目三个按钮，并没有全屏展示按钮；
同样如果是常规项目：在我编辑完成以后，退出编辑界面后，右上角只有返回和项目两个按钮，也没有全屏展示按钮；

谢谢！

**Comment by star7th** [comment]
我说的全屏按钮指的是左边的按钮，把左侧栏收起来

huanghailiang <notifications@github.com> 于2019年8月19日周一 下午2:08写道：

**Comment by star7th** [comment]
左上角

Chen Xing <xing7th@gmail.com> 于2019年8月19日周一 下午2:14写道：

**Comment by huanghailiang** [comment]
@star7th OK，在常规项目中这是好使的，在单页项目中好像没有这个功能，不过谢谢啦！十分感谢
