### ISSUE TITLE
官方开发的showdoc里已经写了个文档可否迁移私有showdoc服务中

### ISSUE THREAD

**Issue by qilvxiedaima** [star7th/showdoc#609]
在官方开发的showdoc里已经写了一部分文档，这些文档如何迁移到自己在本地搭建的showdoc中

**Comment by star7th** [comment]
官网在线服务为数据托管服务而生，并没有考虑过私有化的需求。有私有化需求的应该一开始部署开源版showdoc。官网的数据库结构和开源版的完全不一样，没法直接导入导出。你当前只能手动复制内容过去。


qilvxiedaima <notifications@github.com> 于2019年8月20日周二 下午4:35写道：

**Comment by qilvxiedaima** [comment]
好的，谢谢
