### ISSUE TITLE
什么时候能支持php7呢？

### ISSUE THREAD

**Issue by walkonthemarz** [star7th/showdoc#61]
使用mysql数据库时，安装脚本代码中数据库链接用的是mysql库，但是php7已经完全不支持mysql库了，只支持mysqli或者pdo，你们有计划什么时候修改吗？谢谢！

**Comment by walkonthemarz** [comment]
额。-_-我还是自己改一下安装脚本算了

**Comment by cnhuzi** [comment]
附议

**Comment by star7th** [comment]
oh，那时候没考虑太多，使用mysql库了。晚上有空再改。
如果你赶用可以先自己改改。欢迎改好后pull requests上来哈，我就可以偷懒了
