### ISSUE TITLE
自动保存

### ISSUE THREAD

**Issue by jackidsheep** [star7th/showdoc#614]
我使用docker自动安装，但是编辑的时候不会自动保存，有时候忘记保存了，结果全部数据都没了，我看到issue里面都是有自动保存的功能，是不是我版本的问题？

**Comment by star7th** [comment]
确保使用新代码。
目前机制是一分钟保存一次当前编辑器内容到浏览器。

jackid <notifications@github.com>于2019年8月26日 周一上午11:17写道：

**Comment by taylor21lele** [comment]
我想知道怎么去找自动保存的文件呢？也遇到同样的问题

**Comment by star7th** [comment]
自动保存是保存在浏览器的locastorge里。怎么查看自己网络搜索下。不是以文件的形式。
