### ISSUE TITLE
如何在文档添加头部样式

### ISSUE THREAD

**Issue by yansu482346** [star7th/showdoc#615]
我想将我的文档链接添加到我的网站导航中去，并且文档的头部能和网站头部保持一致  不知道能否修改 
请指点下 谢谢

**Comment by star7th** [comment]
不支持此设置

yansu482346 <notifications@github.com> 于2019年8月26日周一 下午2:11写道：

**Comment by yansu482346** [comment]
但是 我在一个网站上看到了这种样式  能不能帮我看看 这是怎么实现的呢  我觉得文档 + 网站 这样组合 很符合我们公司的一些项目需求  这个就是我看到的 页面链接  麻烦你看看呢
https://help.amingtool.com/web/#/3?page_id=18

**Comment by star7th** [comment]
你可以去问下他们。showdoc官方不提供此设置

yansu482346 <notifications@github.com> 于2019年8月26日周一 下午2:17写道：

**Comment by yansu482346** [comment]
哦 好的  谢谢
