### ISSUE TITLE
设置项目为私密项目后，输入密码无法登陆

### ISSUE THREAD

**Issue by starjoe** [star7th/showdoc#617]
![image](https://user-images.githubusercontent.com/28501688/63770422-b62f0680-c907-11e9-9cb3-33d483c49d99.png)

设置为私密项目后，无法使用访问密码进行访问，点击访问后会有两个POST请求，两个请求返回的内容是
请求1  `index.php?s=/api/item/pwd` 
响应1、`{"error_code":0,"data":{"refer_url":""}}`

请求2 `index.php?s=/api/item/info` 
响应2、`{"error_code":10303,"error_message":"\u4e0d\u662f\u9879\u76ee\u521b\u5efa\u8005"}`

**Comment by star7th** [comment]
刚测试了下，没发现有种问题。我觉得这个不是程序问题。
请确保自己使用最新代码，以及确保自己操作问题。你设置密码后，最好能用一台全新的没访问过showdoc的电脑试试访问

**Comment by starjoe** [comment]
> 刚测试了下，没发现有种问题。我觉得这个不是程序问题。
> 请确保自己使用最新代码，以及确保自己操作问题。你设置密码后，最好能用一台全新的没访问过showdoc的电脑试试访问

php问题，重新安装php后正常了。
