### ISSUE TITLE
新建/管理目录模块的权限问题？

### ISSUE THREAD

**Issue by fuzhilin** [star7th/showdoc#618]
系统中对页面的权限进行了限制，即不是本人创建的不能进行删除，但是没有对新建/管理目录的权限进行区分，我试了一下如果不是自己新建的目录，但是我依然可以进行删除，即使下面的有很多页面，理论上应该是删除目录的时候也判断一下该目录是不是本人创建的，不是的话不能进行删除，不知道是不是我没找到地方进行设置还是就是这样设计的？

**Comment by star7th** [comment]
真想删除东西，只要把页面内容都设置为空即可。所以说编辑权限约等于删除权限了。真想限制，一开始就分配只读权限。其他的限制都没什么效果。

fuzhilin <notifications@github.com> 于2019年8月29日周四 上午11:16写道：

**Comment by yansu482346** [comment]
大神 你好  我最近在本地搭建了一个showdoc  本来是好好的 但是突然我的管理员账号无法登陆了  我重新安装了一个 还是无法使用默认的账号密码 登陆 这是什么情况呀

**Comment by star7th** [comment]
@yansu482346 推荐在服务器上使用自动脚本安装。本地安装是十分不推荐的做法。另外此话题下讨论这个问题不合适，不再回复。

**Comment by fuzhilin** [comment]
我的意思是如果是编辑权限的时候是不是删除目录的时候也应判断一下不是本人创建的不能进行删除。因为下面还有好多页面呢，页面中判断有内容的情况下不是自己创建的不能删除 。

**Comment by star7th** [comment]
没有去记录谁创建的目录；而且你这样防止不了对方删除。我说了，只要有编辑权限，他想删除总有办法。

fuzl <notifications@github.com> 于2019年8月30日周五 下午2:06写道：

**Comment by fuzhilin** [comment]
好的，谢谢了。
