### ISSUE TITLE
表格分隔符|预览有效，但正式页面中无效

### ISSUE THREAD

**Issue by qinqoushui** [star7th/showdoc#619]
如果单元格中内容出现|，使用&#124;进行转义，在实时预览时正常，但保存后在正式页面中，仍然为形成多个单元格。一种方法是使用<table>去描述表格，这种方式可以兼顾预览与正式页面。
另一种方法是再次转义&，即&#38;#124;这样正式页面是OK的，但预览时的效果单元格的内容就不太好理解了。

实际写法

| **参数名称** | **类型**           | **说明**                |
|--|--|
| **qr**   | string            | 加密二维码内容串，以文本形式生成二维码                    |
| **sign** | string            | orderno&#38;#124;sum |

期望的写法（预览时正常）

| **参数名称** | **类型**           | **说明**                |
|--|--|
| **qr**   | string            | 加密二维码内容串，以文本形式生成二维码                    |
| **sign** | string            | orderno&#124;sum|

**Comment by qinqoushui** [comment]
提交的时候，已经被这个编辑器自动转义了 
`
| **参数名称** | **类型**           | **说明**                |
|--|--|
| **qr**   | string            | 加密二维码内容串，以文本形式生成二维码                    |
| **sign** | string            | orderno&#38;#124;sum |

`

| **参数名称** | **类型**           | **说明**                |
|--|--|
| **qr**   | string            | 加密二维码内容串，以文本形式生成二维码                    |
| **sign** | string            | orderno&#124;sum |

**Comment by star7th** [comment]
保存的时候会进行安全转义。
表格里不打算支持这种特殊符号，它本身跟表格冲突的

qinqoushui <notifications@github.com> 于2019年8月31日周六 下午5:45写道：
