### ISSUE TITLE
LDAP验证配sAMAccountName，无法同步用户

### ISSUE THREAD

**Issue by szwangjd2010** [star7th/showdoc#620]
LDAP验证配sAMAccountName，无法同步用户

**Comment by szwangjd2010** [comment]
配cn的时候可以同步到用户，但我们用的windows AD，实际是sAMAccountName匹配的用户名，所以配cn的话只能保证cn和sAMAccountName都是同样的英文的这些用户登录，明显不对

**Comment by star7th** [comment]
ldap的相关功能我都需要搭建环境、配置数据等进行测试。这个环境在我开发完后就撤掉了。实测已经能解决大部分情况下的问题。因为重新搭建环境、测试各种情况挺麻烦的，同时ldap只是showdoc的小功能，所以就不解决小的问题了。除非说是大部分人都会遇到的普通性问题。

**Comment by wattwyx** [comment]
> ldap的相关功能我都需要搭建环境、配置数据等进行测试。这个环境在我开发完后就撤掉了。实测已经能解决大部分情况下的问题。因为重新搭建环境、测试各种情况挺麻烦的，同时ldap只是showdoc的小功能，所以就不解决小的问题了。除非说是大部分人都会遇到的普通性问题。

我也遇到这个问题。我的是配置成功了，但是ldap只同步了前1000条数据。我不是专业搞PHP的，所以也不知道在哪里查原因。。。

**Comment by XuJinzhu-wnote** [comment]
@star7th 
我是通过./showdoc 脚本安装，我也碰到了这个问题连接WINDOW AD域账号无法获取数据问题，以前从来没整过php，通过分析发现以下修改以下几个地方可以搞定

1）/showdoc_data/html/server/Applicaiton/Api/Controller/AdminSettingController.class.php
ldap_set_option($ldap_conn, LDAP_OPT_PROTOCOL_VERSION, $ldap_form['version']);
ldap_set_option($ldap_conn, LDAP_OPT_REFERRALS, 0); //增加此条语句

$result = ldap_search($ldap_conn,$ldap_form['base_dn'],"(cn=*)");
此句中的【cn=*】要修改，否则还是拿不到数据，而且是拉1000条用户过来，我个人认为配置时没必要拉用户信息，只需要拉一个测试账号，把【cn=*】改为【sAMAccountName=测试账号】

ldap_close($ldap_conn); //增加释放连接语句，否则出错就需要重启docker
D("Options")->set("ldap_form" , json_encode( $ldap_form)) ;

还有最关键的一点，返回数据中的字段是小写，所以如果配置sAMAccountName遍历不到任何数据，页面配置时，一定要改为全部小写，即：samaccountname

到此，页面保存LDAP配置时，不会出错，页面提示信息为Success，点击用户管理，可以看到测试账号被拉过来【确保测试账号在LDAP服务器存在账号】

2）上面修复的是保存配置时拉取LDAP用户，还没修复登录时的问题，修复登录不成功的问题在文件
/showdoc_data/html/server/Application/Api/Model/UserModel.class.php中的checkLDAPLogin

改法基本一致，要增加ldap_set_option，【cn=*】改为【sAMAccountName=".$username.】注意php拼字符串不是+而是.，不要忘记在最后增加ldap_close($ldap_conn);

改完这两处之后，冒似也不需要重启就直接生效了，由于只验证了我们自己的ldap服务器，通用性不知道怎么样，有疑问大家可以在交流群③：667194478里讨论，我只是新手，完全不会php

**Comment by star7th** [comment]
@XuJinzhu-wnote 我找时间验证下

**Comment by star7th** [comment]
如果改成 @XuJinzhu-wnote 这种方式的话，linux下的open ldap 验证不通过。
我在想你们是不是没配置好ldap里的ldap user filed 这一项（如果看不到这个设置项请更新代码）。按道理讲，ldap user filed这一项设置为sAMAccountName就能解决你们说的问题。

**Comment by star7th** [comment]
楼上几位都可以试下将ldap user filed这一项设置为sAMAccountName 。默认情况下它会提示你设置为cn，但你不用管，根据实际情况设置为sAMAccountName
