### ISSUE TITLE
相同标题的目录无法跳转

### ISSUE THREAD

**Issue by 217heidai** [star7th/showdoc#625]
如建立的标题如下
```
# 一级标题1
## 二级标题1
# 一级标题2
## 二级标题1
```
两个二级标题的内容一样，生成的目录无法跳转到“一级标题2”下的“二级标题1”

**Comment by star7th** [comment]
建议使用不同的标题吧，加一个序号也好。

217heidai <notifications@github.com> 于2019年9月16日周一 下午2:30写道：
