### ISSUE TITLE
return参数导致生成文档失败

### ISSUE THREAD

**Issue by SeanMine** [star7th/showdoc#627]
请问 这种json格式为什么会生成失败？
{
  "errorCode": 0,
  "statusCode": 200,
  "msg": "",
  "data": 
    {
      "status": 1,
      "total": 4,
      "title": "我的",
      "list": [
        {
          "coupon_id": 20180723148,
          "name": "测试",
          "type": 1,
          "threshold_val": "0.00",
          "coupon_content": 1,
          "coupon_content_val": "0.01",
          "start_time": "2018-07-23 13:47:00",
          "end_time": "2018-07-24 06:47:00",
          "category_id": "0",
          "sid": "bfcf054cb9b8f5c5e83ba41b6318a116",
          "shareCode": "bfcf054cb9b8f5c5e83ba41b6318a116",
          "condition": "无金额门槛",
          "money": "0",
          "txt": "全平台通用",
          "shareUrl": "https://m.cc.cn?shareCode=bfcf054cb9b8f5c5e83ba41b6318a116&coupon_id=20180723148"
        }
      ]
    }
  
}

**Comment by star7th** [comment]
不要包含&符号

SeanMine <notifications@github.com> 于2019年9月19日周四 下午1:35写道：

**Comment by SeanMine** [comment]
哦哦 成功了  感谢
