### ISSUE TITLE
centOS6.5+php7.0.28安装后一直提示找不到扩展库

### ISSUE THREAD

**Issue by wattwyx** [star7th/showdoc#629]
服务器环境为 centOS6.5+php7.0.28，扩展也都安装过了，install下一步的时候，提示“请安装php-gd、php-mbstring、php-pdo” ？

**Comment by star7th** [comment]
提示则说明没安装或者说没生效。可以自己检查phpinfo
推荐使用官方自动脚本或者docekr安装https://www.showdoc.cc/help?page_id=828455960655160
