### ISSUE TITLE
文件标记已对接功能

### ISSUE THREAD

**Issue by cinaofdai** [star7th/showdoc#631]
建议对文件进行标记，是否已经对接、阅读等标签。利用团队接口过多混乱

**Comment by cinaofdai** [comment]
这个我试过了，我让移动端在标题后面打钩。然后通过脚本自动生成文档的时候会出现重复的文档。由于有上百个接口，所以后端一个个去编辑接口不太现实。如果在编辑旁边的按钮，加一个按钮标记已对接。感觉相当完美。

**Comment by star7th** [comment]
先把需求挂着吧，看看还没有人有这样的需求。我个人觉得这种需求比较少。

dh2y <notifications@github.com>于2019年9月25日 周三上午9:40写道：

**Comment by star7th** [comment]
感觉需求还是少，所以不打算实现这个功能了。
