### ISSUE TITLE
ldap不会同步用户信息

### ISSUE THREAD

**Issue by luckberry** [star7th/showdoc#632]
配置好ladp服务器开启该功能后，后续ldap中新添加的用户就无法登陆，提示找不到该用户。

**Comment by star7th** [comment]
我记得这个功能测试过且没问题的。而且这么久你是第一个反馈这个问题的。我不确定这是不是程序本身的问题。
ldap的相关功能我都需要搭建环境、配置数据等进行测试。这个环境在我开发完后就撤掉了。现在重新搭建环境、测试各种情况挺麻烦的，我希望你能确定这个是showdoc自身的问题而不是你们的ldap本身的连接/配置问题。

**Comment by star7th** [comment]
你到后台去重新配置一遍看看

**Comment by luckberry** [comment]
感谢作者回复，第一次配置好之后，是会同步到showdoc中的，后面就不会同步了，在showdoc中查找不到其他用户。密码也是对的。建议作者可以抽空搭个环境试试，这个功能是非常重要且非常方便大家使用的，当然由于开源，作者会很累。

**Comment by star7th** [comment]
第一次同步的时候会把用户都拿过来。
其后不会同步用户过来。但是当登录失败后将尝试登录ldap服务。按道理是能兼容新用户的。自己搭建的开源ldap没问题。应该是你们公司的配置特殊，导致登录不成功。但是我也没法调试。
