### ISSUE TITLE
Nginx启动项目 报install 目录以可写权限

### ISSUE THREAD

**Issue by githuming** [star7th/showdoc#635]
请赋予 install 目录以可写权限！
请赋予 Public/Uploads/ 目录以可写权限！
请赋予 server/Application/Runtime 目录以可写权限！
请赋予 server/Application/Common/Conf/config.php 文件以可写权限！
请赋予 server/Application/Home/Conf/config.php 文件以可写权限！
(如果你确定赋予了文件权限但却一直看到此信息，则可考虑关闭selinux试试)
这几个文件也已经配置有权限
selinux已经关闭了

**Comment by star7th** [comment]
这个问题我也无解。程序没有办法写文件所以报错。至于为什么不能写文件，权限分配，安全设置等都有可能且这个只跟你的服务器配置有关。建议使用官方自动脚本安装。

githuming <notifications@github.com> 于2019年9月30日周一 下午2:40写道：
