### ISSUE TITLE
执行./showdoc update 之后数据全没了，自动备份的数据中数据库数据也没有备份上，图片倒是备份上

### ISSUE THREAD

**Issue by hellolgml** [star7th/showdoc#640]
# 请教我的数据该怎么恢复，感谢！！！！
---
* <img width="376" alt="image" src="https://user-images.githubusercontent.com/23045371/66536809-ca923000-eb50-11e9-9c6e-a2b3b0a4558e.png">
# 数据用sqlite3 去打开是空的，
---
# 只有/Public/Uploads图片数据还在
* <img width="469" alt="image" src="https://user-images.githubusercontent.com/23045371/66536875-1218bc00-eb51-11e9-9a15-a374b5518078.png">

**Comment by star7th** [comment]
建议你仔细看一下sqlite3命令打开数据库的时候需要什么参数。我估计你就是没指定数据库文件

hellolgml <notifications@github.com> 于2019年10月10日周四 上午11:29写道：

**Comment by hellolgml** [comment]
> 建议你仔细看一下sqlite3命令打开数据库的时候需要什么参数。我估计你就是没指定数据库文件
> 
> hellolgml <notifications@github.com> 于2019年10月10日周四 上午11:29写道：
> …

感谢回复。
我尝试过了的，见图：
<img width="453" alt="image" src="https://user-images.githubusercontent.com/23045371/66537125-fbbf3000-eb51-11e9-8b00-a5aa719b5f23.png">

**Comment by hellolgml** [comment]
@star7th 在线等，挺急的

**Comment by star7th** [comment]
看每个html备份文件夹下的该文件，看看哪个是有数据的。只能一个个看了。

**Comment by star7th** [comment]
/showdoc_data/html_bak**************

**Comment by hellolgml** [comment]
@star7th 

---
![image](https://user-images.githubusercontent.com/23045371/66538267-375bf900-eb56-11e9-8264-12cbead6ba0a.png)

哎，只有一个有，但是太久远了

**Comment by hellolgml** [comment]
请教下，哪些场景才会触发数据自动备份

**Comment by star7th** [comment]
执行 ./showdoc update的时候

hellolgml <notifications@github.com> 于2019年10月10日周四 下午12:06写道：

**Comment by hellolgml** [comment]
@star7th 
---
查看了记录，是执行了命令“./showdoc -version”导致的数据丢失，
这个命令执行怎么没报错
![image](https://user-images.githubusercontent.com/23045371/66538822-9b7fbc80-eb58-11e9-98fb-6d31f59f1268.png)

**Comment by star7th** [comment]
我不知道，这个不是系统预设的命令。总不可能对啥都要做一次判断。我觉得应该执行无效

hellolgml <notifications@github.com> 于2019年10月10日周四 下午12:22写道：
