### ISSUE TITLE
一个项目里面的部分页面可以分享给其他项目一起使用吗

### ISSUE THREAD

**Issue by githuming** [star7th/showdoc#642]
一个项目里面的部分页面可以分享给其他项目一起使用吗，或者是可以导入其他项目部分的页面到我这个项目的目录下吗

**Comment by star7th** [comment]
不能。手动复制内容过来吧

githuming <notifications@github.com> 于2019年10月11日周五 下午4:03写道：

**Comment by githuming** [comment]
这个功能后续会考虑完善吗

**Comment by star7th** [comment]
这种需求比较少，不打算。除非很多人有这样的需求

githuming <notifications@github.com> 于2019年10月11日周五 下午4:11写道：
