### ISSUE TITLE
为什么为登录的用户也能访问文档呢

### ISSUE THREAD

**Issue by rgonerao** [star7th/showdoc#643]
为什么为登录的用户也能访问文档呢，这个是产品设计就是这样的吗？

**Comment by star7th** [comment]
创建项目的时候设置密码的话，非登录用户就访问不到了

rgonerao <notifications@github.com> 于2019年10月16日周三 下午4:39写道：

**Comment by rgonerao** [comment]
能像石墨协作文档那样吗：A同事修改文档页面，B同事如果在这个文档页面，也能实时看到A同事的修改内容。这样就完美了。

**Comment by star7th** [comment]
这是性价比的问题。实时编辑的代价比较高，目前看不到明显需要这么做的必要。

rgonerao <notifications@github.com> 于2019年10月16日周三 下午11:00写道：

**Comment by rgonerao** [comment]
很需要要，大佬。 特别是部门内或者部门间，开会的时候，所有的同事都能同时编辑一个文档，然后大家相互之间又能看到对方的修改情况。

**Comment by star7th** [comment]
一份文档允许部门所有人编辑，这是什么情况？我不清楚你是用于怎样的场景。IT文档一般情况下不需要这么做

rgonerao <notifications@github.com> 于2019年10月17日周四 上午10:43写道：

**Comment by rgonerao** [comment]
比如我们在开会的时候，我们多位同事需要一起来编辑这个会议纪要。 然后我们大家都能看到这个编辑情况。类似这样的：https://teakki.com/

**Comment by star7th** [comment]
如果你是想收集各人信息，需要实时协同，不如先用腾讯文档或者石墨吧。showdoc现在还没进入实时协作这个市场。有没有必要进去，是个问题。我看到的情况下，需要实时编辑的团队很少。或者说等足够多人反馈的时候可能我就需要考虑了

Chen Xing <xing7th@gmail.com> 于2019年10月17日周四 上午10:46写道：

**Comment by rgonerao** [comment]
谢谢大佬，希望能引入这个功能。 我们一直在石墨文档上写，但是石墨内网部署成本太高了。 希望能找到一个可以实时协作的而且可以内网部署的系统。  

大佬：文档的评价功能能否添加一个呢。

**Comment by star7th** [comment]
尽量不要只问某个功能能不能加。详细描述清楚应用场景后，如果觉得有必要的就会加。

rgonerao <notifications@github.com> 于2019年10月17日周四 上午10:52写道：

**Comment by star7th** [comment]
https://github.com/star7th/showdoc/issues/553

https://github.com/star7th/showdoc/issues/118

**Comment by rgonerao** [comment]
好吧。 希望能show doc，能进入实时协作哈。 的确很喜欢你们产品，也的确公司内部需要个实时协作的功能。
