### ISSUE TITLE
希望在保存文档的时候可以加个tag字段，以便在查看历史版本列表的时候进行区分

### ISSUE THREAD

**Issue by laisanxin** [star7th/showdoc#644]
![image](https://user-images.githubusercontent.com/37370731/66983451-39d8c880-f0eb-11e9-9397-49577b7e826e.png)

**Comment by star7th** [comment]
其实之前有这个功能的。后来我统计了一下，使用showdoc的用户中极少用到此功能，所以就去掉了。
这个“极少”，是基于官方托管服务得出的结论。使用率都不到千分之一。

laisanxin <notifications@github.com> 于2019年10月17日周四 下午2:36写道：
