### ISSUE TITLE
移动端好像无法编辑文档啊？

### ISSUE THREAD

**Issue by huabin123** [star7th/showdoc#645]

**Comment by star7th** [comment]
暂不支持移动端编辑。

huabin123 <notifications@github.com>于2019年10月17日 周四下午6:20写道：

**Comment by huabin123** [comment]
请问什么时候可以支持呢？

**Comment by star7th** [comment]
以后可能有移动app。时间待定。

huabin123 <notifications@github.com>于2019年10月22日 周二下午6:51写道：
