### ISSUE TITLE
能否集成接口测试？

### ISSUE THREAD

**Issue by zk3151463** [star7th/showdoc#646]
能否集成接口测试

**Comment by star7th** [comment]
接口测试请使用 http://runapi.showdoc.cc/#/
两者定位不一样。showdoc当前的定位是文档功能为主，不打算在api测试这件事上花过重力气。以后再看情况要不要把runapi做得更丰富些，但即使做也是把runapi当成一个独立产品来做。

zk3151463 <notifications@github.com> 于2019年10月21日周一 上午10:59写道：

**Comment by zk3151463** [comment]
showdoc 如何修改管理员账号密码，如何添加多管理员，如何修改首页另外可否修改版权

**Comment by star7th** [comment]
修改密码看这里https://www.showdoc.cc/help?page_id=16118 其他你说的点都不支持

zk3151463 <notifications@github.com> 于2019年10月22日周二 上午9:46写道：

**Comment by star7th** [comment]
runapi 已经支持完善的接口测试功能 https://www.showdoc.com.cn/runapi?page_id=30291
