### ISSUE TITLE
如何让首页自动转跳到某个项目

### ISSUE THREAD

**Issue by mzhou2018** [star7th/showdoc#647]
谢谢

**Comment by star7th** [comment]
没有这个设置

mzhou2018 <notifications@github.com> 于2019年10月21日周一 下午12:17写道：

**Comment by star7th** [comment]
https://www.showdoc.cc/help?page_id=1385576954326448

mzhou2018 <notifications@github.com> 于2019年10月21日周一 下午3:40写道：
