### ISSUE TITLE
Uncaught SyntaxError： Unexpected token 用 in JSON

### ISSUE THREAD

**Issue by eternalstop** [star7th/showdoc#648]
编写文档插入图片无法插入，console中出现的错误
Uncaught SyntaxError： Unexpected token 用 in JSON at postion 124
    at JSON.parse(<anonymous>)
    at HTMLFrameElement.uploadIframe.onload(image-dialog.js:161)

**Comment by star7th** [comment]
看看网络请求返回什么内容。说不定是上传失败。比如说图片目录没有可写权限

Alan <notifications@github.com> 于2019年10月21日周一 下午1:27写道：

**Comment by eternalstop** [comment]
网络请求返回看没什么异常，目录有权限的，实际文件也已经上传成功了，在服务器Public/Uploads/能找到要上传的图片。

**Comment by star7th** [comment]
那我不清楚了。如果有外网访问地址，则提供来看下。

Alan <notifications@github.com> 于2019年10月21日周一 下午1:49写道：

**Comment by eternalstop** [comment]
用户您好，您的访问过于频繁，为确认本次访问为正常用户行为，需要您协助验证。
      
        验证码:
        
          
          
          换一张
           验证码错误，请重新输入
        
        提交后没解决问题？欢迎反馈
      
      
        提交

json那里有问题，这是什么？可以关掉吗？

**Comment by star7th** [comment]
这个东西跟showdoc没什么关系。看是有什么截断了你的网络访问。多半是你所用网络的安全限制

Alan <notifications@github.com> 于2019年10月21日周一 下午2:12写道：

**Comment by star7th** [comment]
如果你无法提供外网地址，我觉得我没办法帮你看是什么问题。无能为力。

Chen Xing <xing7th@gmail.com> 于2019年10月21日周一 下午2:14写道：

**Comment by eternalstop** [comment]
知道什么问题了，服务器上的问题，谢谢谢谢。
