### ISSUE TITLE
修改之后别的同事打开有小红点提醒哪个进行修改就好了

### ISSUE THREAD

**Issue by HelloZhu** [star7th/showdoc#65]
希望能增加这个功能

**Comment by star7th** [comment]
那就等于说所有项目的所有参与者都必须点开每个人的修改才能消掉小红点。这太大干扰了。建议通过其他沟通工具提醒对方你的修改

**Comment by ephen** [comment]
可以是最新的一条进行标记
或者是自上次打开后被修改的条数。

不过感觉确实不太重要

**Comment by aManSunny** [comment]
分享后还需要密码，但这个密码是啥呢

**Comment by star7th** [comment]
这个密码是你当初创建项目时设置的密码。如忘记，可以去掉。方式是，项目-修改信息，把密码置空
