### ISSUE TITLE
Windows server2008R2环境下搭建，不现实验证码的问题

### ISSUE THREAD

**Issue by jzhaozhe** [star7th/showdoc#653]
在server 2008R2的系统上搭建的，IIS7+PHP5.5 ，正常的完成后，在登陆的时候使用默认账户密码showdoc+123456进行登陆的时候弹出提示框，提示框无文字，且验证码不显示。见图：
![image](https://user-images.githubusercontent.com/47917314/67463952-01019c00-f675-11e9-93bb-cac36eb9bf5d.png)
![image](https://user-images.githubusercontent.com/47917314/67463964-07901380-f675-11e9-838f-f3ac5fbec8ba.png)

**Comment by star7th** [comment]
从你的截图来看我没看到你有输入账户。先看常见问题看能否解决 https://www.showdoc.cc/help?page_id=16118

赵哲 <notifications@github.com> 于2019年10月24日周四 下午3:43写道：
