### ISSUE TITLE
Markdown 渲染时有序列表不能嵌套无序列表

### ISSUE THREAD

**Issue by jiaxingzack** [star7th/showdoc#655]
如:
```
* List A
    1. List 1
    2. List 2
* List B
* List C
---
1. List 1
    * List A
    * List B
2. List 2
3. List 3
```
![image.png](https://i.loli.net/2019/10/30/LsWfl8HS1FQDokB.png)

中的有序列表下的 无序列表 都被渲染成 有序列表 了.

**Comment by jiaxingzack** [comment]
```
* List A
    1. List 1
    2. List 2
* List B
* List C
---
1. List 1
    * List A
    * List B
2. List 2
3. List 3
```

GitHub 是支持这样写的

* List A
    1. List 1
    2. List 2
* List B
* List C
---
1. List 1
    * List A
    * List B
2. List 2
3. List 3

**Comment by star7th** [comment]
这个问题相当棘手。showdoc使用的是一个第三方markdown解析库https://pandao.github.io/editor.md/ ，小问题的话我可以自行修改之。而现在这个兼容问题可能需很深入解析库才能修改。鉴于此问题带来影响很小，可能我先不花精力深入了解了。也许你可以直接反馈给markdown解析库的作者。

**Comment by jiaxingzack** [comment]
我猜应该是第三方解析库的问题, 很偶然的情况下发现的这个问题, 一般人也不会这么嵌套用.
这边没法处理那可以关掉这个 issue 了, 我向上游反馈下.

**Comment by mazileon** [comment]
预览页面，无序列表前面的小黑点，没有渲染出来，请问是缺什么css么
