### ISSUE TITLE
由showdoc.cc迁移到自己服务器

### ISSUE THREAD

**Issue by chaoxiaodi** [star7th/showdoc#656]
请教下，有提供把在showdoc.cc写的迁移到自己部署的服务器的方法么？

**Comment by star7th** [comment]
官网在线服务为数据托管服务而生，并没有考虑过私有化的需求。有私有化需求的应该一开始部署开源版showdoc。官网的数据库结构和开源版的完全不一样，没法直接导入导出。你当前只能手动复制内容过去。

chaoxiaodi <notifications@github.com> 于2019年10月30日周三 下午5:23写道：

**Comment by chaoxiaodi** [comment]
谢谢回复！
