### ISSUE TITLE
如何在showDoc中设置path参数

### ISSUE THREAD

**Issue by pangyuworld** [star7th/showdoc#657]
请问如何在showDoc中设置path参数呢？
比如我的spring mvc控制器是如下定义的
`@RequestMapping(value = "/week/{userId}", method = RequestMethod.GET)`
它在postman中的接口可以写成`http://localhost:18887/week/:userId`
类似这种，如何在showDoc中实现呢？

**Comment by star7th** [comment]
直接写url不就好了吗，后面加备注说明说这个是可变参数。

小胖儿 <notifications@github.com> 于2019年10月30日周三 下午8:45写道：
