### ISSUE TITLE
插入的代码会自动转义

### ISSUE THREAD

**Issue by wykings** [star7th/showdoc#66]
插入页面中，```代码```，之间的代码中，如果存在引号，在保存的时候会被自动转义成\"
![image](https://cloud.githubusercontent.com/assets/15644256/16035851/d97c9842-324b-11e6-9002-679f7a0b4910.png)

**Comment by star7th** [comment]
经测试，http://doc.star7th.com/ 没有发现转义的问题 ``` 符号尝试换行，不要太紧贴

**Comment by wykings** [comment]
http://doc.star7th.com/  在这个上面我也进行了测试，没有转义的情况。但是我克隆的github到我的网站下就有这种情况，地址 www.wykings.com/doc/ 有可能是最新的版本出现的问题，也有可能是php版本的问题，我的php版本为5.3.29

**Comment by star7th** [comment]
理论上跟php版本没关系。但按你这情况，我也猜不出是什么原因，因为我无法重现你的情况。
你可以试着用最新代码重新安装一遍

**Comment by star7th** [comment]
无意中发现了这个问题的真正原因。记录下。
如果开启magic_quotes_gpc，则会存在转义的问题。
实际上，从php5.3开始，magic_quotes_gpc就已经默认关闭。php5.4直接去掉了这个过时的配置项。如果你出现了这个问题，请注意php版本是应该使用5.3以上，同时不要开启magic_quotes_gpc
