### ISSUE TITLE
在阿里云上部署了项目，不能登陆不能注册，默认账号密码也不行

### ISSUE THREAD

**Issue by xmjharry** [star7th/showdoc#661]
在阿里云上部署了项目，不能登陆不能注册，默认账号密码也不行

**Comment by star7th** [comment]
应该是php没安装php-sqlite扩展。既然是使用阿里云，有外网环境，为什么不用官方一键脚本呢，多省心，又不会出错。
https://www.showdoc.cc/help?page_id=828455960655160

xmjharry <notifications@github.com> 于2019年11月2日周六 上午11:14写道：
