### ISSUE TITLE
文章保存报错，长度限制？

### ISSUE THREAD

**Issue by DevilMafia** [star7th/showdoc#662]
app.9fde579a816759082003.js:1 Uncaught TypeError: Cannot read property 'getMarkdown' of undefined

![image](https://user-images.githubusercontent.com/41660452/68116562-1bb9f780-ff36-11e9-97b1-276897a9c273.png)

**Comment by star7th** [comment]
点击网络，看看请求错误的那个返回什么信息

**Comment by star7th** [comment]
我现在更新了下master的代码。有错误信息会直接弹窗显示。这样更容易发现问题所在。

**Comment by DevilMafia** [comment]
谢谢您，之前没关注到您这么及时给回复。
 我们这边是用Docker容器进行部署的，在线上环境运行了几个月之长，但是现在在保存很长的一遍文章中，就会提示那个问题，可是我刚刚又在测试了一边发现已经可以，但是下班之前我在公司也编辑保存还是不可以，现在在家就正常。那个异常信息现在也无法提供给您，明早我将会在下面留言发图。

**Comment by star7th** [comment]
更新到最新代码后再反馈。

**Comment by DevilMafia** [comment]
好的
