### ISSUE TITLE
docker 部署成功后，无法访问，已排除网络 ，防火墙 因素。

### ISSUE THREAD

**Issue by wmsJackWang** [star7th/showdoc#663]
![image](https://user-images.githubusercontent.com/19822486/68277489-43ca6780-00aa-11ea-8b99-513d4d81a1fc.png)
![image](https://user-images.githubusercontent.com/19822486/68277526-593f9180-00aa-11ea-8d1b-9bd3c4a7bef9.png)
![image](https://user-images.githubusercontent.com/19822486/68277544-60669f80-00aa-11ea-83c3-85aec116fb71.png)
![image](https://user-images.githubusercontent.com/19822486/68277560-69577100-00aa-11ea-8991-0f4911216ac2.png)

**Comment by star7th** [comment]
能ping通不代表端口就通了啊。服务器防火墙关闭了不代表网络就没有其他层的限制啊，比如说有些公司就禁止员工访问所有IP的4999端口。
先在服务器执行curl http://127.0.0.1:4999
，看看是否有网页源码返回。有的话就证明服务起来了。从你上面的截图上看，docker容器有起来了，我倾向于认为服务没问题的。只是外网访问不了你这个4999端口而已。本地127.0.0.1应该能访问。试试就知道。

wmsJackWang <notifications@github.com> 于2019年11月6日周三 下午3:31写道：

**Comment by believezzd** [comment]
同上问题，查看docker 容器日志，Nginx 没起来
2019/11/27 14:03:14 [emerg] 22#22: socket() 0.0.0.0:80 failed (13: Permission denied)
nginx: [emerg] socket() 0.0.0.0:80 failed (13: Permission denied)
