### ISSUE TITLE
希望增加一个项目搜索功能

### ISSUE THREAD

**Issue by jasonfanjun** [star7th/showdoc#664]
作者您好，
我们将您的产品用于日常项目，非常方便。
我们希望能增加一个项目标题搜索功能，进行项目的快速定位。
我们产生的项目相对较多，目前已有一千多个单页项目，因此如果需要查询会非常困难。
希望可以进行支撑，期待您更多的作品。
感谢。

**Comment by star7th** [comment]
我记得这个功能很早之前就更新了。超过10个项目的时候就会自动出现搜索栏。你更新到最新代码看看。

jasonfanjun <notifications@github.com> 于2019年11月6日周三 下午4:49写道：
