### ISSUE TITLE
showdoc.sql在哪里 

### ISSUE THREAD

**Issue by a13571359** [star7th/showdoc#666]
showdoc.sql在哪里  没有找到

**Comment by star7th** [comment]
参考官网来安装，不要相信其他滞后的教程  https://www.showdoc.cc/help?page_id=13732

a13571359 <notifications@github.com> 于2019年11月8日周五 上午11:05写道：

**Comment by star7th** [comment]
官网两年前就不支持mysql 了 https://www.showdoc.cc/help?page_id=31990

Chen Xing <xing7th@gmail.com> 于2019年11月8日周五 上午11:06写道：

**Comment by a13571359** [comment]
好的
