### ISSUE TITLE
找不到sqlite下面是数据库

### ISSUE THREAD

**Issue by H-pinke** [star7th/showdoc#667]
成功安装showdoc之后，在服务器上面输入 sqlite3 之后 输入 .database无法查看到我安装的数据库。
输入 .tables 也无法查看到我的用户表

**Comment by star7th** [comment]
你都不带参数，它怎么知道你要打开哪个文件。多去查查 sqlite3 命令的用法

H-pinke <notifications@github.com> 于2019年11月8日周五 下午4:07写道：
