### ISSUE TITLE
docker 安装showdoc

### ISSUE THREAD

**Issue by awanganddong** [star7th/showdoc#669]
运行一段时间，docker ps 显示状态正常，但是浏览器访问地址没反应

**Comment by awanganddong** [comment]
重启后，过一会正常

**Comment by star7th** [comment]
那就是docker服务一开始没起来吧

awanganddong <notifications@github.com>于2019年11月8日 周五下午7:38写道：

**Comment by awanganddong** [comment]
也就是工作一段时间，访问showdoc就无反应，这时候重启docker就可以了

**Comment by star7th** [comment]
应该是服务器运行异常把showdoc停了吧。这么久以来没听人有反馈过这样的问题。

awanganddong <notifications@github.com>于2019年11月8日 周五下午7:44写道：

**Comment by awanganddong** [comment]
![image](https://user-images.githubusercontent.com/25174075/68474601-d14fb800-0260-11ea-94bb-4e633f0b2bd9.png)
这是日志

**Comment by star7th** [comment]
单单这日志看不出有什么。我觉得这可能只是特殊情况。再用一阵子看看。

awanganddong <notifications@github.com>于2019年11月8日 周五下午7:49写道：

**Comment by awanganddong** [comment]
谢谢了
