### ISSUE TITLE
二次开发问题

### ISSUE THREAD

**Issue by itq5** [star7th/showdoc#670]
尝试二次开发，使用npm run dev，但是打开8080端口后，登录不了，http://xxxxx:8080/server/index.php?s=/api/common/verify 提示404，是不是我哪个地方没修改哦，望望解答

**Comment by star7th** [comment]
自己使用代理，把对后端的请求代理到php
如果你既不是前端开发者也不是php开发者，我劝你不要二次开发。

itq5 <notifications@github.com>于2019年11月10日 周日下午10:13写道：

**Comment by star7th** [comment]
这个不是取决于我而是取决于你啊。取决于你自己的学习能力以及想改到怎样的程度。我对你的能力和你想改的东西一无所知，你让我怎么回答。

Da-wukong <notifications@github.com> 于2019年11月25日周一 上午8:58写道：

**Comment by Da-wukong** [comment]
我先看看吧。我只想知道你们的系统构架是怎么样的。你们的二次开发文档有点简洁。没写构架介绍，我自己看吧。不用回复了，谢了。：）
