### ISSUE TITLE
开放API，一些建议

### ISSUE THREAD

**Issue by wzhymxz** [star7th/showdoc#672]
1.查询接口，根据唯一编码获取一篇文件内容，方便获取后再新增内容
2.排异接口，根据文字名称，查询是否存在。方便存在的话不修改
3.文章列表接口，可获取名称，唯一编号

有了这些接口方便集成

**Comment by star7th** [comment]
暂时还没发现这个必要性。看看其他人是否有需求。

无夜 <notifications@github.com> 于2019年11月11日周一 下午8:54写道：

**Comment by wzhymxz** [comment]
我有篇文章，需要实时更新，我需要获取到原先内容，然后再自动添加新的内容，我发现调用/server/index.php?s=/api/page/info 这个接口，无法使用

**Comment by star7th** [comment]
这个接口是覆盖式的，不是追加式。

无夜 <notifications@github.com> 于2019年11月11日周一 下午8:59写道：

**Comment by star7th** [comment]
这个接口主要是为了api场景写。在api场景，一般都是覆盖式，很少追加式

Chen Xing <xing7th@gmail.com> 于2019年11月11日周一 下午9:00写道：

**Comment by wzhymxz** [comment]
是啊，所以我很苦恼，我是想有一个文档，是记录，调用开发api的新增记录，不用手动来记录谁新增了那个数据库表的文章

**Comment by wzhymxz** [comment]
https://hellosean1025.github.io/yapi/openapi.html 这是yapi的一些接口，我利用他的开发api就可以做一些集成开发，因为我是net，php不太会，所以无法做集成开发。我希望这个能做成一个脱离语言，可集成的一个系统

**Comment by star7th** [comment]
showdoc开源三年了，开放api的需求很少，比较少人用。如果专门为此开发一套接口，不知道是否值得。就你上面的情况来看，其实你只是无法做新增记录而已，其他还是可以的。有空我考虑要不要把后台接口封装出来。目前偏向于需求动力不足。

无夜 <notifications@github.com> 于2019年11月11日周一 下午9:08写道：

**Comment by GabrielCHEN1** [comment]
通过注释代码自动更新API文档之后,没有历史版本,,这个功能还是挺希望能推出的

**Comment by star7th** [comment]
@GabrielCHEN1  不打算支持.代码生成的次数太不可控了,生成太多无效数据 .

**Comment by GabrielCHEN1** [comment]
> @GabrielCHEN1 不打算支持.代码生成的次数太不可控了,生成太多无效数据 .

当后端开发修改了老接口的文档时,需要把每一处修改记录下来,然后汇总给前端.这种的场景下,前端会希望能够点击历史记录,然后看看在当前的开发版本中接口做了哪些修改,(因为我看到showdoc现在的版本中是支持历史版本高亮显示修改行的) 😀

**Comment by star7th** [comment]
这种事最好用沟通软件跟前端说吧. 或者自己新建一个单独页面,按日期列举每次改了什么

Gabriel Chen <notifications@github.com> 于2020年7月10日周五 下午3:36写道：
