### ISSUE TITLE
安装后再次运行脚本会删掉原来的数据库

### ISSUE THREAD

**Issue by seahurt** [star7th/showdoc#673]
我只是想改一下绑定的端口，把container删掉了，改了脚本，然后运行./showdoc start来启动，可是出错了，应该是container不存在了。我想着直接运行./showdoc可能是会重新创建一个container, 毕竟是刚安装的，不会再重新下载了吧。。。谁知道竟然重新安装了一遍，还把数据库给弄没了

我觉得脚本的默认动作不应该是重新下载程序这种危险动作，如果是，至少给个提示，让用户有个反应时间
如果有可能的话，把安装脚本和管理脚本分开，安装时直接向/usr/local/bin中写入一个管理脚本

**Comment by star7th** [comment]
进入/showdoc_data/文件夹，代码被删掉之前会备份，以html_xxx的形式命名

seahurt <notifications@github.com> 于2019年11月13日周三 下午3:59写道：

**Comment by star7th** [comment]
另外，执行多一次脚本是不会删除用户数据的。我不知道你怎么改的。

Chen Xing <xing7th@gmail.com> 于2019年11月13日周三 下午4:03写道：

**Comment by seahurt** [comment]
我只是把docker run 后边的4999端口改了成了80

然后运行了
```
docker stop showdoc
docker rm showdoc
./showdoc start # 出错
./showdoc # 重新开始安装了
```

现在我再运行./showdoc就不会重新安装了，就算我把showdoc的container删掉也不会

第一次安装时，是出错了的，我看了一下出错信息，大概是我的用户没有docker组权限，我拿`sudo docker ps`后，看到容器运行起来了，我就没当回事，直接访问网址去了。添加了一个项目，写了一个md，想把端口换成80的，就是上边的操作了。


给您添麻烦了，对不住

**Comment by seahurt** [comment]
我从头看了一下showdoc脚本的代码，判定是否安装检查的是镜像存在与否。这样的话，确实不会出现我之前的情况。

应该是我在改脚本的时候动到了哪个地方吧。

脚本中有两个地方（160行，168行）没有加sudo, 这个应该是我第一次安装提示出错的原因吧。

**Comment by star7th** [comment]
现在加上了。

seahurt <notifications@github.com> 于2019年11月13日周三 下午5:04写道：
