### ISSUE TITLE
保存页面的时候偶尔个别页面一直转圈，保存不上。

### ISSUE THREAD

**Issue by fengyunher** [star7th/showdoc#675]
这个不是网络问题，而且有个解决办法就是多加一些空格，或者删除一些空格，就可以保存上。这个bug非常奇怪，并不是页面过长的问题，有的很长的页面也可以保存。感觉好像上传的内容被后台直接拒收，连接直接断开，没有返回提示。我用的是Nginx+php-fpm，不知道是不是哪设置不对的原因，特来请教。

**Comment by star7th** [comment]
个人感觉不是网络问题就是你的服务器问题。试看官网有没有这个问题 https://www.showdoc.cc/

fengyunher <notifications@github.com> 于2019年11月14日周四 下午2:33写道：

**Comment by fengyunher** [comment]
不是网络问题，就是多加一些空格，或者删除一些空格，就可以保存，否则一直保存不上。服务器是直接断开连接，没任何返回。

**Comment by star7th** [comment]
我还是建议你先试一下官网有没有问题。暂时没听过其他人反馈你说的问题，应该不是普遍行为

fengyunher <notifications@github.com> 于2019年11月14日周四 下午2:40写道：

**Comment by fengyunher** [comment]
官网没有问题，我就是从官网直接复制过来，出现的问题。

**Comment by star7th** [comment]
额，如果说一个问题，官网没问题，其他人部署的版本也没问题——在无法重现的情况下，我也提供不了什么解决办法。

fengyunher <notifications@github.com> 于2019年11月14日周四 下午2:43写道：

**Comment by fengyunher** [comment]
嗯，谢谢，不知道其他弟兄有没有知道的，有可能是Nginx的问题

**Comment by fengyunher** [comment]
经过几天的问题查找，我发现只要清空浏览器缓存，然后刷新页面，就可以提交成功。然后过一段时间又得清空缓存才能保存成功。postman模拟提交，一直没问题。这个只针对某一个页面，其它页面没这个问题。

**Comment by star7th** [comment]
出错的时候，打开浏览器审查元素，看看控制台报错

fengyunher <notifications@github.com> 于2019年11月18日周一 下午1:08写道：

**Comment by fengyunher** [comment]
ERR_CONNECTION_RESET

**Comment by fengyunher** [comment]
Uncaught (in promise) TypeError: Cannot read property 'data' of undefined

**Comment by star7th** [comment]
单单看这个也看不出什么。建议就不用管了吧。就特殊情况导致。其他方式不受影响。

fengyunher <notifications@github.com> 于2019年11月18日周一 下午1:24写道：
