### ISSUE TITLE
不太懂vue方面的技术，但是想用showdoc搭建一个活动设计协作平台

### ISSUE THREAD

**Issue by zimiyu** [star7th/showdoc#676]
你好，我是一个公益从业者，不太懂vue方面的技术，但是想用showdoc搭建一个开放的活动设计平台，在修改一些内容后前端不发生变化，通过网络了解到可能是打包的问题，但是在打包的时候老师报错，请问怎么操作？

**Comment by star7th** [comment]
这里有个二次开发文档 https://www.showdoc.cc/help?page_id=1385576954326448

zimiyu <notifications@github.com> 于2019年11月15日周五 上午10:04写道：

**Comment by zimiyu** [comment]
对我来说理解有点困难~
