### ISSUE TITLE
开放端口，手机客户端无法访问。

### ISSUE THREAD

**Issue by zhangxuan1340** [star7th/showdoc#678]
最新测试结果，目前内部服务器使用的特殊端口 http段非HTTPS，使用端口8068.
未使用80端口，因为外网需要访问，手机端提示报错，无法访问。
完整链接。

**Comment by star7th** [comment]
填入类似这样：
http://showdoc.com:8068

**Comment by star7th** [comment]
我没看到你写的完整链接。请提供链接看看

**Comment by zhangxuan1340** [comment]
http://doc.vilicom.top:8068，链接填写完整，我稍后手机截图上传下

**Comment by star7th** [comment]
我在浏览器打开这个网址也打不开啊http://doc.vilicom.top:8068

**Comment by star7th** [comment]
你提供下你们平时在浏览器打开的项目链接

**Comment by zhangxuan1340** [comment]
刚刚您说的这个外网无法连通的问题，我特意切换4G查看了一下，可以打开，我再找找看是不是我的设置部分有问题，项目是刚搭建的准备做内部文档管理系统，因为涉及多家门店所以，这边我在调试下看看，是否有遗漏，目前外网访问是：http://doc.vilicom.top:8068，即可访问的

**Comment by star7th** [comment]
我现在试了，可以浏览器打开。但app里确实访问不了。
估计是app自身的安全限制了。可能苹果商店禁止app发起非https的请求。
解决这个问题的方法就是使用https。哎，我一开始也没考虑到有这个硬性限制。
或许我可以提供另一种方案，就是官方提供一个https中转代理，对于用户来讲是透明的。当用户指定了私有版服务器，那么，实际的访问路径是App——官方https代理——用户服务器。还不确定要不要这么做。
目前是直连用户服务器，所以它会要求https协议

**Comment by zhangxuan1340** [comment]
明白原理了，我转变下服务器的协议，确实HTTP不合适了，谢谢大佬

**Comment by star7th** [comment]
我误会了。原来不是http的问题。是可以支持http的。
我用官方一键脚本安装showdoc后，是可以连接app的，直连到4999端口。
你这样的情况应该是由于经过了nginx或者其他转发层，导致header丢失。
建议想办法保证所有header均能正常转发过来，或者不用转发，直接访问showdoc的端口。

**Comment by douyaolai** [comment]
你好，已升级到最新版，IOS app上手动指定服务器，输入域名 （https://doc.ronghuashuzi.com）后提示”该网址无法正常链接“。

**Comment by star7th** [comment]
@douyaolai 你这样的情况应该是由于经过了nginx或者其他转发层，导致header丢失。
建议想办法保证所有header均能正常转发过来，或者不用转发，直接访问showdoc的端口。

**Comment by douyaolai** [comment]
我是用是宝塔的lamp环境，  ”直接访问showdoc的端口“ ？，端口是 ？

**Comment by star7th** [comment]
宝塔的lamp环境会默认改掉showdoc的响应hedaer，导致ios客户端请求异常。
建议使用官方推荐的一键脚本安装。

yuyanke <notifications@github.com> 于2019年11月19日周二 下午3:27写道：

**Comment by star7th** [comment]
鉴于app跟服务器的通讯依赖header会给一些人安装带来麻烦，所以我已经去掉这个设定。现在更新服务器代码、同时下载新的apphttps://www.showdoc.cc/app 便可以使用，不再依赖安装环境的header。
