### ISSUE TITLE
是否不支持mysql5.7

### ISSUE THREAD

**Issue by Veado** [star7th/showdoc#68]
我本地安装了一遍，然后推荐给同事使用，安装比较仓促。他本地和云上是mysql5.7，报连接数据库失败。我帮他了解一下。

**Comment by star7th** [comment]
showdoc的安装脚本就是使用mysqli的，而安装后则使用PDO访问。有人反馈说是可以在PHP7下成功的，你具体什么报错

**Comment by star7th** [comment]
不支持mysql5.6以上版本。短期内不会做这个兼容处理，因为是底层框架不支持，换框架的话不好弄。
