### ISSUE TITLE
请问可以把文档导出为json或者yaml格式吗？

### ISSUE THREAD

**Issue by cooper1x** [star7th/showdoc#680]
![image](https://user-images.githubusercontent.com/9080789/69132690-826f1180-0aef-11ea-9a97-50a7adfadd89.png)
我想迁移到coding上去，不知道怎么操作。貌似只能导出为doc，doc感觉不太实用，还不如pdf。

**Comment by star7th** [comment]
不支持这种操作。建议手动复制过去。

linkstar <notifications@github.com> 于2019年11月19日周二 下午5:11写道：

**Comment by cooper1x** [comment]
也就是说，这个目前除了手动复制粘贴，没有其他办法做数据迁移是吗？

**Comment by star7th** [comment]
你可以自己编程实现，因为数据库在你服务器。showdoc官方不提供这样的设置。

linkstar <notifications@github.com> 于2019年11月19日周二 下午5:15写道：

**Comment by star7th** [comment]
二次开发文档： https://www.showdoc.cc/help?page_id=1385576954326448

Chen Xing <xing7th@gmail.com> 于2019年11月19日周二 下午5:17写道：

**Comment by cooper1x** [comment]
@star7th 好吧，服务器不是我的，我没有权限，只能拿导出文件导入。
