### ISSUE TITLE
自动脚本安装

### ISSUE THREAD

**Issue by Nick233333** [star7th/showdoc#681]
请问一下文档中的自动脚本安装，下载的是一个二进制可执行文件，是通过 `phar` 实现的吗？

**Comment by star7th** [comment]
就是一个文本文件。shell脚本。

Nick <notifications@github.com>于2019年11月19日 周二下午9:56写道：

**Comment by Nick233333** [comment]
看了下内容确实是普通 `shell` 脚本，没有 `.sh` 后缀还以为是二进制文件，`showdoc` 很好用，感谢开源。
