### ISSUE TITLE
验证码的问题，为什么我docker安装的showdoc，新注册账号验证码老是报错

### ISSUE THREAD

**Issue by 84067176** [star7th/showdoc#682]
验证码的问题，为什么我docker安装的showdoc，新注册账号验证码老是报错，我应该怎么办！

**Comment by star7th** [comment]
提供下外网访问地址

84067176 <notifications@github.com> 于2019年11月20日周三 上午11:05写道：

**Comment by 84067176** [comment]
我的内网使用docker 安装的showdoc,之前注册没什么问题的，后面不知道为什么注册不了了，老是提示验证码错误，我机器上面磁盘没有满，权限也是开启的777

**Comment by star7th** [comment]
内网你是怎么把docker镜像拿进去的

84067176 <notifications@github.com> 于2019年11月20日周三 上午11:10写道：

**Comment by 84067176** [comment]
是安装官网文档那样安装的，docker run -d --name showdoc -p 4999:80 -v /showdoc_data/html:/var/www/html/      star7th/showdoc

**Comment by star7th** [comment]
内网怎么拉取官方镜像呢，官方镜像在外网

84067176 <notifications@github.com> 于2019年11月20日周三 上午11:14写道：

**Comment by star7th** [comment]
在现在地情况下，我既不知道你的操作（ 我总不能一步步地问你操作了什么），也不能访问项目，同时也没有其他有用的报错信息，我也无能为力。

Chen Xing <xing7th@gmail.com> 于2019年11月20日周三 上午11:15写道：

**Comment by 84067176** [comment]
我是部署在内网服务器上面的，可以上网。也是从外网拉取镜像的，验证码老是错误，有日志提示吗，我可以发错误日志给你看看。

**Comment by star7th** [comment]
验证码错误不是系统级错误，应该是没有日志的。纯属是业务级别的错误。

84067176 <notifications@github.com> 于2019年11月20日周三 上午11:19写道：

**Comment by star7th** [comment]
既然可以上网就用官方一键脚本

Chen Xing <xing7th@gmail.com> 于2019年11月20日周三 上午11:20写道：

**Comment by 84067176** [comment]
好吧。
