### ISSUE TITLE
编辑权限范围

### ISSUE THREAD

**Issue by qinqoushui** [star7th/showdoc#683]
此前有其它人讨论过这问题。解释是说编辑权限和删除权限差不多，把内容删空和删除文件是一样的。我觉得还是有所不同的，页面在，就能看历史，通过历史找回（当然，故意反复破坏刷历史不在此列），我们希望的功能仍然是为了防止误删除。而不是恶意删除。目前删除后没有找回，也不能阻止删除。希望后续能考虑下这方面的功能，实际就是改下代码，标记创建者和最后修改者。

**Comment by star7th** [comment]
这也就引出另一个问题了。某个目录是A创建的。目录下有B创建的页面，那么能不能删除目录呢？可是我删除目录的时候，旗下的文件都会被删除的。那么我是否就可以通过把文章转到我创建的目录下，然后就可以删除文章了。
我是不想考虑这些问题所以才不这么做。有编辑权限的情况下，要作恶始终没办法。只读是最好的。

qinqoushui <notifications@github.com>于2019年11月20日 周三下午6:40写道：
