### ISSUE TITLE
代码块标签在编辑的时候显示正常，在阅读模式显示异常

### ISSUE THREAD

**Issue by xxdhxx** [star7th/showdoc#684]
编辑模式下
![image](https://user-images.githubusercontent.com/40158172/69291983-c4a76880-0c3f-11ea-8f51-d4ab4f3f5692.png)
阅读模式下
![image](https://user-images.githubusercontent.com/40158172/69292009-da1c9280-0c3f-11ea-8d9e-5b088e3d9c7b.png)
不显示代码行号，不做奇偶行变色。
我的安装方式，使用docker一键部署，并执行了./showdoc update 然后重启了。

**Comment by star7th** [comment]
设计本如此。阅读模式下干净的样式更好一些。

xxdhxx <notifications@github.com> 于2019年11月21日周四 上午9:19写道：
