### ISSUE TITLE
数据字典自动生成脚本问题

### ISSUE THREAD

**Issue by KJohn2q** [star7th/showdoc#685]
自动生成脚本只生成了数据库中部分表的表名，注释，及字段详细信息。

**Comment by star7th** [comment]
一般是由于注释中含有&符号引起

John.W <notifications@github.com> 于2019年11月21日周四 下午6:35写道：

**Comment by KJohn2q** [comment]
那怎样可以解决这个问题啊。

**Comment by star7th** [comment]
去掉注释中的&符号

John.W <notifications@github.com> 于2019年11月21日周四 下午6:37写道：

**Comment by KJohn2q** [comment]
你好，谢谢你。暂时解决了这个问题，有没有治本的办法，比如，通过程序转义的方式。谢谢

**Comment by star7th** [comment]
暂时没有，后面有空我再看看

John.W <notifications@github.com>于2019年11月21日 周四下午6:48写道：

**Comment by KJohn2q** [comment]
好的，谢谢你

**Comment by star7th** [comment]
新版已修复此问题，不再受&符号影响。
