### ISSUE TITLE
showdoc安装版断电后登陆不上

### ISSUE THREAD

**Issue by gdggfb** [star7th/showdoc#687]
- 我的showdoc安装版在断电后登陆不上了，安装是按照教程手动安装
- 断电后登陆出现以下提示

![image](https://user-images.githubusercontent.com/30901219/69392799-2e904280-0d12-11ea-9923-f54b84c01e0d.png)

请问如何解决这个问题！

**Comment by star7th** [comment]
就是不可写的意思啊。登录命令行去给文件可写权限。

gdggfb <notifications@github.com> 于2019年11月22日周五 上午10:24写道：

**Comment by star7th** [comment]
如果你给文件赋权的基本知识还没有，我建议你去找懂技术的人帮忙

Chen Xing <xing7th@gmail.com> 于2019年11月22日周五 上午10:27写道：

**Comment by gdggfb** [comment]
![image](https://user-images.githubusercontent.com/30901219/69392968-cf7efd80-0d12-11ea-847f-f7efaab561e1.png)

**Comment by star7th** [comment]
检查下是不是selinux等安全设置禁止了写文件

gdggfb <notifications@github.com> 于2019年11月22日周五 上午10:28写道：

**Comment by gdggfb** [comment]
问题解决了，是selinux 设置的问题
