### ISSUE TITLE
某些CSS样式无法显示

### ISSUE THREAD

**Issue by JasmineXiaozzz** [star7th/showdoc#688]
比如表格中背景颜色,单元格颜色等,是无法显示的
但如合并单元格等又可使用.
请问是否有不支持的CSS样式?或是有独特的写法?望告知!
```
<table bgcolor=yellow>
	<tr bgcolor=yellow><td bgcolor=yellow>参数名</td><td>类型</td><td>说明</td></tr>
	<tr >
		<td colspan="3">============== 状态 ===============</td>
	</tr>
<table bgcolor=yellow>
```
上述效果图代码

**Comment by star7th** [comment]
我印象中markdown语法本身就不支持颜色的

小贼贼子_Jasmine <notifications@github.com> 于2019年11月25日周一 上午9:30写道：

**Comment by JasmineXiaozzz** [comment]
可能我没有表述清楚,markdown是兼容html的
所以我想实现复杂的表格,是用html写的,但某些样式并不生效
但同样的在如atom,idea等编辑器中样式是生效的
```
<table bgcolor=yellow>
        <!-- 背景色不生效 -->
	<tr bgcolor=yellow><td bgcolor=yellow>参数名</td><td>类型</td><td>说明</td></tr>
        
	<tr >
                <!-- 合并单元格生效 -->
		<td colspan="3">============== 状态 ===============</td>
	</tr>
<table bgcolor=yellow>
```

**Comment by star7th** [comment]
好像表格的背景色是我在代码里限制死了白色。你就当作是设计如此吧。

小贼贼子_Jasmine <notifications@github.com> 于2019年11月25日周一 上午9:35写道：

**Comment by JasmineXiaozzz** [comment]
嗯...好吧,那我清楚了.
还有个类似BUG,我在写使用<table>标签的时候,会造成此表格与上一内容之间间隔很大一片空白
比如代码:
```
 ##返回参数说明**

// 在实际显示中,上面标题与下面表格之间会空出一大片空白,大概八九百像素的样子,占据了屏幕的三分之二还多.

<table >
	<thead>
		<tr><td>参数名</td><td>类型</td><td>说明</td></tr>
	</thead>
</table >
```

**Comment by star7th** [comment]
如果用html标签写，就不能留有空格和换行。压缩到同一行去。换行和空白会被当做mardown解析

小贼贼子_Jasmine <notifications@github.com> 于2019年11月25日周一 上午9:45写道：

**Comment by JasmineXiaozzz** [comment]
OK,解决了,感谢作者回复!
