### ISSUE TITLE
更新后原来的项目没了

### ISSUE THREAD

**Issue by huzhonglan** [star7th/showdoc#691]
为什么更新之后什么都没有了

**Comment by star7th** [comment]
请详细描述自己是怎么更新的

lan <notifications@github.com> 于2019年11月27日周三 下午3:09写道：

**Comment by huzhonglan** [comment]
./showdoc update

**Comment by star7th** [comment]
没遇到这种情况。建议你把命令行截图放出来

lan <notifications@github.com> 于2019年11月27日周三 下午3:12写道：

**Comment by huzhonglan** [comment]
![image](https://user-images.githubusercontent.com/42115674/69701834-d64dac00-1128-11ea-9ed5-89f813caee55.png)
![image](https://user-images.githubusercontent.com/42115674/69701877-e9f91280-1128-11ea-9cec-c84b8d6e73ca.png)
完了之后再打开看原来的项目都没了

**Comment by huzhonglan** [comment]
能恢复数据吗

**Comment by star7th** [comment]
进入/showdoc_data目录下，有很多类似html_xxx 之类的备份文件。将之重命名为html就是恢复备份了。你自己试下哪个才是正确的。恢复后，再重新执行一遍升级命令。

**Comment by huzhonglan** [comment]
不行呀，改了还是没有

**Comment by star7th** [comment]
如果一个个都试过，都没数据，就证明你本身没数据

lan <notifications@github.com> 于2019年11月27日周三 下午3:37写道：

**Comment by huzhonglan** [comment]
改名之后还需要什么操作吗

**Comment by star7th** [comment]
就改名替换掉原来的html文件夹就行

lan <notifications@github.com> 于2019年11月27日周三 下午3:39写道：

**Comment by huzhonglan** [comment]
我恢复了，感谢。
你们执行./showdoc update 之后都是正常的吗

**Comment by star7th** [comment]
都正常

lan <notifications@github.com> 于2019年11月27日周三 下午3:43写道：

**Comment by wxtanker** [comment]
我这也遇到这问题了，而且最终也没找到
