### ISSUE TITLE
后台管理添加用户，同时并添加用户真实姓名。

### ISSUE THREAD

**Issue by zhangxuan1340** [star7th/showdoc#692]
开发组你们好，目前有新的需求，在后台添加用户的同时，添加用户真实姓名。
因为：
公司内部文档存储，希望在增加用户的同时，可以录入用户真实姓名，无需用户登陆后在个人信息中进行添加用户名，但是改了Index.vue页面，添加了一行
``` html
<el-form-item label=" " >
    <el-input type="text" :placeholder="$t('name_tips')" v-model="addForm.name"></el-input>
</el-form-item>
```
并在Add UserControl中也添加了name_tips，页面并没有生效，不太明白Think PHP的工作，希望开发组能够提供下支持，感谢感谢

**Comment by star7th** [comment]
https://www.showdoc.cc/help?page_id=1385576954326448

zhang1340 <notifications@github.com> 于2019年11月30日周六 下午12:08写道：

**Comment by zhangxuan1340** [comment]
界面是修改成功了，参照开发组里面的写法，数据没有写入到SQLite中，我在学习下开发吧，感谢开发组
