### ISSUE TITLE
按照docker安裝教程無法訪問指定端口

### ISSUE THREAD

**Issue by SWC-BrianLu** [star7th/showdoc#697]
![螢幕快照 2019-12-04 上午11 59 15](https://user-images.githubusercontent.com/14371571/70111568-9ee18100-168d-11ea-9a67-6d9492f498a8.png)

附上容器內的logs

![螢幕快照 2019-12-04 下午12 12 31](https://user-images.githubusercontent.com/14371571/70112114-63e04d00-168f-11ea-9280-e4723ab0ad9b.png)
訪問本地端

**Comment by star7th** [comment]
看不到第一个截图那里说缺少权限吗。
你挂在的那个目录，docker进城没有写那个目录的权限。通常是什么安全限制。看自己服务器怎么配置了，为什么要禁止docker写文件

BrianLu <notifications@github.com>于2019年12月4日 周三下午12:00写道：

**Comment by star7th** [comment]
挂载的目录，docker进程无法往里面写文件。

Chen Xing <xing7th@gmail.com>于2019年12月4日 周三下午12:59写道：

**Comment by SWC-BrianLu** [comment]
@star7th 
非常感謝你，我接觸這塊不久

註解一下，docker安裝教程裡

#启动showdoc容器
docker run -d --name showdoc -p 4999:80 -v /showdoc_data/html:/var/www/html/ star7th/showdoc

/showdoc_data/html:/var/www/html/ 
這塊的意思應該是將工作目錄安裝到指定目錄
由於我對於/var/www/html/ 這裡沒有權限寫入
所以導致上面問題產生
增加寫入權限或者更改你可以寫入的權限路徑後
即可運行正常

@star7th 經人提醒之後反而通了，非常謝謝你
