### ISSUE TITLE
希望能够把个性域名添加上

### ISSUE THREAD

**Issue by isouu** [star7th/showdoc#699]
希望能够把个性域名添加上，这个使用比较方便，能够快速访问到某个项目文档

**Comment by star7th** [comment]
开源版不支持。只有官网支持。

isouu <notifications@github.com> 于2019年12月6日周五 下午2:06写道：

**Comment by star7th** [comment]
个性域名需要开启静态化，需要后端配合。凡是增加部署难度的东西同时又少用的功能被我砍掉了

Chen Xing <xing7th@gmail.com> 于2019年12月6日周五 下午4:09写道：

**Comment by isouu** [comment]
自己部署内部使用，觉得个性域名用途还蛮大得，项目多，文档多，可以通过个性域名快速访问，直达项目文档，快捷方便，觉得还是蛮实用得，或者可以提供一下带个性域名版本得源码吗

**Comment by star7th** [comment]
不提供，没有。

isouu <notifications@github.com> 于2019年12月6日周五 下午4:22写道：

**Comment by isouu** [comment]
好的，谢谢

**Comment by BingyuanXie** [comment]
好吧，看到这个问题了，看来作者大大已经堵死了这个需求
