### ISSUE TITLE
开源版首页底部内容增加

### ISSUE THREAD

**Issue by yuanzhuofeng** [star7th/showdoc#700]
如增加备案号那些，底部文件是引用哪个的？

**Comment by star7th** [comment]
没有预留这样的设置。因为团队内部使用工具没考虑备案的事情

yuanzhuofeng <notifications@github.com> 于2019年12月9日周一 下午2:57写道：

**Comment by yuanzhuofeng** [comment]
那可以指引引导下吗？目前都使用你们工具有段时间了
 
发件人： star7th
发送时间： 2019-12-09 14:59
收件人： star7th/showdoc
抄送： yuanzhuofeng; Author
主题： Re: [star7th/showdoc] 开源版首页底部内容增加 (#700)
没有预留这样的设置。因为团队内部使用工具没考虑备案的事情 

yuanzhuofeng <notifications@github.com> 于2019年12月9日周一 下午2:57写道：

**Comment by star7th** [comment]
它不是简单改一下文件就可以了的。
这个是二次开发的文档 https://www.showdoc.cc/help?page_id=1385576954326448
然后你找首页web_src\src\components/Index.vue来修改，在底部增加代码后，重新打包。


yuanzhuofeng <notifications@github.com> 于2019年12月9日周一 下午3:02写道：

**Comment by yuanzhuofeng** [comment]
好的

 
发件人： star7th
发送时间： 2019-12-09 15:06
收件人： star7th/showdoc
抄送： yuanzhuofeng; Author
主题： Re: [star7th/showdoc] 开源版首页底部内容增加 (#700)
它不是简单改一下文件就可以了的。 
这个是二次开发的文档 https://www.showdoc.cc/help?page_id=1385576954326448 
然后你找首页web_src\src\components/Index.vue来修改，在底部增加代码后，重新打包。 


yuanzhuofeng <notifications@github.com> 于2019年12月9日周一 下午3:02写道：

**Comment by yuanzhuofeng** [comment]
目前新版不能直接备份目录直接迁移吗？那要安装前修改代码吗？



1264678665@qq.com
 
发件人： star7th
发送时间： 2019-12-09 15:06
收件人： star7th/showdoc
抄送： yuanzhuofeng; Author
主题： Re: [star7th/showdoc] 开源版首页底部内容增加 (#700)
它不是简单改一下文件就可以了的。 
这个是二次开发的文档 https://www.showdoc.cc/help?page_id=1385576954326448 
然后你找首页web_src\src\components/Index.vue来修改，在底部增加代码后，重新打包。 


yuanzhuofeng <notifications@github.com> 于2019年12月9日周一 下午3:02写道：

**Comment by star7th** [comment]
我不明白你在说什么

yuanzhuofeng <notifications@github.com> 于2019年12月9日周一 下午4:49写道：

**Comment by yuanzhuofeng** [comment]
没事了



1264678665@qq.com
 
发件人： star7th
发送时间： 2019-12-09 16:50
收件人： star7th/showdoc
抄送： yuanzhuofeng; Author
主题： Re: [star7th/showdoc] 开源版首页底部内容增加 (#700)
我不明白你在说什么 

yuanzhuofeng <notifications@github.com> 于2019年12月9日周一 下午4:49写道：
