### ISSUE TITLE
开源版iosapp无法正常连接

### ISSUE THREAD

**Issue by jasonfanjun** [star7th/showdoc#701]
已更新至最新版，手动安装。WEB使用正常，下载IOS版app 指定https://域名  后 提示”该网址无法正常连接“

**Comment by star7th** [comment]
你如果使用了nginx之类的转发层，转发层切勿修改showdoc的响应header，要原样返回响应header，app要用到。

jasonfanjun <notifications@github.com> 于2019年12月11日周三 下午8:34写道：

**Comment by star7th** [comment]
web不需要用到所以正常。但app需要。

Chen Xing <xing7th@gmail.com> 于2019年12月11日周三 下午8:38写道：

**Comment by jasonfanjun** [comment]
用宝塔面板做的环境，之前在做其他项目开发时，响应header都是正常返回，没有被修改。因此是否会是其他问题。或者有什么方法可以获取 响应报文，我贴上来供您分析

**Comment by star7th** [comment]
宝塔默认会修改响应header。这是已知问题。https://github.com/star7th/showdoc/issues/678

jasonfanjun <notifications@github.com> 于2019年12月11日周三 下午8:43写道：

**Comment by jasonfanjun** [comment]
谢谢明白。

**Comment by star7th** [comment]
宝塔的lamp环境会默认改掉showdoc的响应hedaer，导致ios客户端请求异常。 建议使用官方推荐的一键脚本安装

Chen Xing <xing7th@gmail.com> 于2019年12月11日周三 下午8:45写道：

**Comment by star7th** [comment]
鉴于app跟服务器的通讯依赖header会给一些人安装带来麻烦，所以我已经去掉这个设定。现在更新服务器代码、同时下载新的apphttps://www.showdoc.cc/app 便可以使用，不再依赖安装环境的header。
