### ISSUE TITLE
迁移服务器，数据未及时更新

### ISSUE THREAD

**Issue by zwwjava** [star7th/showdoc#702]
我尝试的把原来的服务迁移，但是发现 /showdoc_data/html/Sqlite/showdoc.db.php 文件最近修改时间是一周以前（但是前两天还有新增内容），所以新服务中的数据有缺失。所以我想问一下，怎么可以同步 docker 容器内的数据，到挂载的 showdoc_data/html 文件下。谢谢。

**Comment by star7th** [comment]
你是怎么安装的

zww <notifications@github.com> 于2019年12月16日周一 下午4:46写道：

**Comment by zwwjava** [comment]
解决了，可能是我改了文件夹的权限，导致项目无法自动更新挂载的目录。所以我直接从旧服务的容器中把 showdoc.db.php 文件复制出来了，数据就是最新的了。
