### ISSUE TITLE
建议：文档，可以显示下文档的最新编辑日期时间吗？

### ISSUE THREAD

**Issue by XmYhkj** [star7th/showdoc#703]
文档除了标题、内容，应该是有最近编辑时间、编辑者吧。可以显示出来吗，不然都不知道谁改了。。😂

**Comment by star7th** [comment]
有按钮
![image](https://user-images.githubusercontent.com/2200494/70986914-d58db180-20f9-11ea-8a90-a8cf399a381c.png)

**Comment by star7th** [comment]
项目展示页面的右边
