### ISSUE TITLE
有计划支持plantuml吗

### ISSUE THREAD

**Issue by squallliu** [star7th/showdoc#705]
虽然说可以上传图片，但是图片参与不了版本管理

**Comment by star7th** [comment]
showdoc支持一些简单的流程图时序图。 https://www.showdoc.cc/1615954?page_id=14853979


squall <notifications@github.com> 于2019年12月19日周四 上午7:43写道：

**Comment by star7th** [comment]
![image](https://user-images.githubusercontent.com/2200494/71135905-05de6880-223e-11ea-8bc1-4a56fd1332f2.png)

**Comment by star7th** [comment]
新版已经支持plantuml
