### ISSUE TITLE
Docker安装法本地图片上传问题

### ISSUE THREAD

**Issue by OliverDaDa** [star7th/showdoc#706]
Docker安装法，本地图片上传路径问题，get_domain()函数获取到的域名是localhost:4999，而不是实际访问的域名

**Comment by star7th** [comment]
不是showdoc问题，是nginx转发不对。看这个问题https://github.com/star7th/showdoc/issues/573

**Comment by OliverDaDa** [comment]
好的，已解决，感谢！
