### ISSUE TITLE
长标题显示不全

### ISSUE THREAD

**Issue by sqlkrad** [star7th/showdoc#707]
例如：https://www.showdoc.cc/leetcode?page_id=3628819032873194

完整的标题应该是1269. Number of Ways to Stay in the Same Place After Some Steps（左侧边栏是显示全的）

**Comment by star7th** [comment]
你再重新编辑下。可能是缓存。编辑后更新应该就好吧

sqlkrad <notifications@github.com> 于2019年12月21日周六 下午9:21写道：

**Comment by star7th** [comment]
可能是你触发了低概率的缓存不生效问题。极度少可能遇到这个问题。

Chen Xing <xing7th@gmail.com> 于2019年12月21日周六 下午9:42写道：

**Comment by star7th** [comment]
我看了一下，是因为数据库的标题字段长度限定为50个字符，所以其实完整标题是没有保存到数据库的。
而左侧栏是因为采用redis缓存，所以不受长度限制，它就保存成功。但24小时后redis缓存失效。最终还是以数据库为准。
我思考了下，很少会有标题超过50个字符的情况，暂就不为这特殊情况而改数据库了。

Chen Xing <xing7th@gmail.com> 于2019年12月21日周六 下午9:43写道：

**Comment by sqlkrad** [comment]
好的，明白了，多谢！
