### ISSUE TITLE
使用自动安装脚本安装，打开页面出现空白页

### ISSUE THREAD

**Issue by MicroCountry** [star7th/showdoc#709]
无法正常打开页面
![image](https://user-images.githubusercontent.com/16758768/71401983-7df5c580-2666-11ea-9c81-c6a74835d7f4.png)

**Comment by star7th** [comment]
感觉是文件不全。你重现安装或者升级下

hannea <notifications@github.com> 于2019年12月24日周二 下午4:00写道：
