### ISSUE TITLE
有一个小请求

### ISSUE THREAD

**Issue by JHeLiu** [star7th/showdoc#710]
就是看文档右边位置 可以增加一个直接请求示例吗？

在一定的规范中，自动获取左边的请求参数 开始请求

**Comment by star7th** [comment]
showdoc是文档工具，不仅仅是api文档。不能为api专门做一个只有api文档才能用的功能。这样没法放其他文档了。

missliu <notifications@github.com> 于2019年12月25日周三 上午8:39写道：

**Comment by star7th** [comment]
而且左边的格式是很自由的，有些人写成这种那种格式，很难统一获取到参数

Chen Xing <xing7th@gmail.com> 于2019年12月25日周三 上午8:52写道：

**Comment by JHeLiu** [comment]
好吧，看来只能自己魔改了
