### ISSUE TITLE
docker部署，服务无法访问，docker日志，发现权限问题

### ISSUE THREAD

**Issue by believezzd** [star7th/showdoc#711]
查看docker 容器日志，Nginx 没起来
2019/11/27 14:03:14 [emerg] 22#22: socket() 0.0.0.0:80 failed (13: Permission denied)
nginx: [emerg] socket() 0.0.0.0:80 failed (13: Permission denied)

**Comment by star7th** [comment]
docker run 的时候有报错吗

believezzd <notifications@github.com> 于2019年12月26日周四 下午1:51写道：

**Comment by believezzd** [comment]
容器正常启动

**Comment by star7th** [comment]
我不清楚你的服务器都docker进程做了什么限制。可能是selinux限制。

believezzd <notifications@github.com> 于2019年12月26日周四 下午1:54写道：

**Comment by star7th** [comment]
镜像是没问题的。或者你可以重现安装下。

Chen Xing <xing7th@gmail.com> 于2019年12月26日周四 下午1:56写道：

**Comment by believezzd** [comment]
* 对，镜像是没有问题的，我也很纳闷，用的是deepin笔记本部署的，后面改用centos系统，部署是正常使用的；
* 1个月前的事了，我今晚回去再试一次看看，当时提issue是放在其他人的问题下，刚刚发现被关闭了的
* 应该不是selinux的问题，关闭了的，这个当时确认过
