### ISSUE TITLE
docker部署上传图片后不显示

### ISSUE THREAD

**Issue by yunjie-li** [star7th/showdoc#712]
上传图片后返回的地址是
http://showdoc/server/../Public/Uploads/2019-12-30/5e09689524fd8.jpg。。
修改为 http://showdoc.wwmm.site/Public/Uploads/2019-12-30/5e09689524fd8.jpg 可以正常显示。目前仅仅配置了http 的代理。请问还需要配置啥？

upstream showdoc {
  server 127.0.0.1:9003;
}
server {
    listen 80;
    server_name showdoc.wwmm.site;
    index index.html index.htm index.php;
    root /www/server/phpmyadmin;
    location / {
       proxy_pass http://showdoc;
    }

    access_log /www/wwwlogs/access.log;
}

**Comment by star7th** [comment]
尝试看看这个问题https://github.com/star7th/showdoc/issues/638

**Comment by star7th** [comment]
我觉得主要是nignx要带header过去

**Comment by yunjie-li** [comment]
> 我觉得主要是nignx要带header过去

确实是这个问题，建议在安装说明里面添加下nginx配置说明。不然这个问题可能还会继续报...

upstream showdoc {
  server 127.0.0.1:9003;
}
server {
    listen 80;
    server_name showdoc.wwmm.site;
    index index.html index.htm index.php;
    root /www/server/phpmyadmin;
    location / {
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header Host $host;
       proxy_pass http://showdoc;
    }

    access_log /www/wwwlogs/access.log;
}
