### ISSUE TITLE
自动生成数据字典脚本是否支持Oracle数据库

### ISSUE THREAD

**Issue by aliwangwang** [star7th/showdoc#713]

**Comment by star7th** [comment]
如果是文档的话，本身是可以自由编辑的。所有数据库都支持。如果说是自动生成数据字典脚本的话，你说的是支持哪些数据库

aliwangwang <notifications@github.com> 于2019年12月31日周二 下午2:37写道：

**Comment by aliwangwang** [comment]
自动生成数据字典的脚本，支不支持oracle数据库

**Comment by star7th** [comment]
目前是不支持的。要做的话，花一点功夫才行。先把需求挂在这里看看有没有其他用户提出也有这个需求。

aliwangwang <notifications@github.com> 于2019年12月31日周二 下午2:56写道：

**Comment by aliwangwang** [comment]
ok，thanks

**Comment by yanghe1117** [comment]
望支持oracle 自动生成数据字典，3q

**Comment by star7th** [comment]
在明确支持该功能之前，可以先从oracle数据库导出sql到mysql，然后再用mysql生成。其实这个需求反馈还是不多，再挂一阵子吧。

**Comment by star7th** [comment]
现在已经有了一个第三方开发者做了项目，支持自动生成Oracle数据库数据字典到showdoc https://github.com/whaios/showdocdb

**Comment by aliwangwang** [comment]
领导我的被子生病了，我必须躺在床上好好照顾它.有事请电话联系我
