### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS错误

### ISSUE THREAD

**Issue by simonguan2018** [star7th/showdoc#715]
当在showdoc前面部署nginx时，访问时会提示“ERR_TOO_MANY_REDIRECTS”，如果直接访问正常

**Comment by star7th** [comment]
跟showdoc没有关系。你自己nginx规则没写好。去掉所有rwrite规则，只转发数据到4999端口。

simonguan2018 <notifications@github.com> 于2019年12月31日周二 下午11:28写道：
