### ISSUE TITLE
showdoc.cc的文档保存问题

### ISSUE THREAD

**Issue by BingyuanXie** [star7th/showdoc#716]
不知道是我的特例还是什么情况，在文档内容丢失好多次之后我才发现，写好的文档，必须要保存两遍，跳出两遍保存成功之后的提示之后，才会在历史版本中看到被正常保存了。建议加入自动保存的功能，每隔5分钟就保存一次，不然太有挫败感了。

**Comment by star7th** [comment]
经实际测试，点击一次保存就可以保存了。我不知道你不是装了什么浏览器插件更改了网页行为。
每分钟会自动保存到浏览器本地。丢失的话重新编辑该网页会提示是否恢复草稿。
