### ISSUE TITLE
数据字典导入失败

### ISSUE THREAD

**Issue by kalsolio** [star7th/showdoc#717]
`备注里面有 &gt; &lt; 就会解析失败了`

**Comment by kalsolio** [comment]
···
备注里面有 &gt; &lt; 就会解析失败了
···

**Comment by star7th** [comment]
不支持特殊符号。

kalsolio <notifications@github.com> 于2020年1月2日周四 下午2:39写道：

**Comment by kalsolio** [comment]
其实就是大于号 小于号 导出自动转码成这个样了 然后就导入失败了

**Comment by star7th** [comment]
如果要支持特殊符号的话没有尽头的，总有另类。干脆直接不支持特殊符号好了。数据表的注释我相信并不是一定要使用特殊符号的。

kalsolio <notifications@github.com> 于2020年1月2日周四 下午9:03写道：
