### ISSUE TITLE
网页卡死问题

### ISSUE THREAD

**Issue by zooah212** [star7th/showdoc#718]
在项目中，点击“新建/管理目录”添加目录的时候，页面会卡死，试了在线的showdoc也这样；试了chrome浏览器、firefox浏览器、360安全浏览器无痕模式都不行；团队管理页面偶尔也会出现卡死的现象。点击新建页面按钮则正常。

**Comment by star7th** [comment]
这是个谜团吗。有人这个可以有人那个不可以。https://github.com/star7th/showdoc/issues/714
有些人谷歌浏览器可以有些人360浏览器可以。我也是相当迷惑。
找时间再看下

**Comment by zooah212** [comment]
> 这是个谜团吗。有人这个可以有人那个不可以。#714
> 有些人谷歌浏览器可以有些人360浏览器可以。我也是相当迷惑。
> 找时间再看下

刚在线测试了一下，如果项目中没有任何东西，一个空项目点击“新建/管理目录”的时候是没问题的，但是一旦项目中新建了页面，在点击这个“新建/管理目录”按钮的时候页面就会卡死，卡死之前console截图如下：
![微信截图_20200102165337](https://user-images.githubusercontent.com/33769054/71658968-be4cf600-2d80-11ea-83eb-a9684bd13b89.png)

**Comment by star7th** [comment]
已重写了目录管理功能，增加拖动排序和转移层级功能。

**Comment by zooah212** [comment]
> 已重写了目录管理功能，增加拖动排序和转移层级功能。

在线测试了更改后的，之前的问题已经不存在了，多谢帮忙处理。
但是发现了一个新的问题，在自己新建的项目中返回主页面之后，点击顶部的“团队管理”链接按钮，浏览器页面会出现卡死的现象，但是如果登进来直接点击“团队管理”是没有问题的。console报错稍后上传到附件，此问题只出现在360安全浏览器中，试了下chrome没有出现此问题，但是大多数时间还是用360的，所以看看能否麻烦看看此问题。
![111](https://user-images.githubusercontent.com/33769054/71967783-c7393e00-323e-11ea-8594-b35ab96b5195.png)

**Comment by star7th** [comment]
似乎旧版的360模式有问题。你用最新版试试

zooah212 <notifications@github.com> 于2020年1月8日周三 下午5:47写道：

**Comment by star7th** [comment]
这个是兼容问题。我修改某js依赖的版本，你更新后，重新清理浏览器缓存试试。

**Comment by zooah212** [comment]
> 这个是兼容问题。我修改某js依赖的版本，你更新后，重新清理浏览器缓存试试。

嗯，在线将浏览器更新到最新版，清了浏览器缓存后确实没有问题了，多谢。
