### ISSUE TITLE
建议 新增发布功能

### ISSUE THREAD

**Issue by jeffxjh** [star7th/showdoc#719]
有个需求：
  对于未完成的文档我需要保存，但是还不想同组人员看到，所以需要发布功能，到文档完成时，才对外可见。
 谢谢！

**Comment by star7th** [comment]
我更建议自己新建一个自己专用的草稿项目。专门写未完成的文档。等确认后再添加进正式项目里。
当前如果引入草稿机制会更改整个文档编辑流程，会影响到所有人。除非这个是大众需求，不然我先建议你按照上面做法使用。

jeffxjh <notifications@github.com> 于2020年1月3日周五 下午2:59写道：

**Comment by jeffxjh** [comment]
感谢你的建议！
