### ISSUE TITLE
TOC Bug

### ISSUE THREAD

**Issue by siwen1017** [star7th/showdoc#720]
TOC 目录窗体在点击时有机率消失，
只能刷新页面才能重新显示；
或者切换页面才能重新显示；

**Comment by siwen1017** [comment]
![111](https://user-images.githubusercontent.com/13879187/71759307-40a2fa80-2ee6-11ea-9536-fe3ef6c46104.gif)

**Comment by star7th** [comment]
我好像不能复现。你尝试更新代码后看有没有问题。还有问题的话提供你的链接我去看看

**Comment by siwen1017** [comment]
https://www.showdoc.cc/test011?page_id=258347450574372
点红窗区域多次点击必复现，应该不会是浏览器的问题。
![image](https://user-images.githubusercontent.com/13879187/71759374-1d2c7f80-2ee7-11ea-9d62-bf665cecfb22.png)

**Comment by siwen1017** [comment]
![image](https://user-images.githubusercontent.com/13879187/71759381-38978a80-2ee7-11ea-9acf-6e2c9830224a.png)

**Comment by star7th** [comment]
确实是个问题。有空再看

siwen1017 <notifications@github.com> 于2020年1月4日周六 上午11:42写道：

**Comment by star7th** [comment]
我看了下，这个不算是bug。是你加了html标签的strong的缘故。请用markdown的原生语法去建议大标题。比如说二级标题就够大了。

**Comment by siwen1017** [comment]
已确认，使用原生语法没有问题，如果对标题再增加  加粗，加斜，语法会导致该问题。
