### ISSUE TITLE
执行./showdocls 时八报错

### ISSUE THREAD

**Issue by bibex** [star7th/showdoc#722]
--2020-01-06 18:06:07--  (try: 4)  http://localhost:4999/install/install.lock
Connecting to localhost|127.0.0.1|:4999... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2020-01-06 18:06:11--  (try: 5)  http://localhost:4999/install/install.lock
Connecting to localhost|127.0.0.1|:4999... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2020-01-06 18:06:16--  (try: 6)  http://localhost:4999/install/install.lock
Connecting to localhost|127.0.0.1|:4999... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2020-01-06 18:06:22--  (try: 7)  http://localhost:4999/install/install.lock
Connecting to localhost|127.0.0.1|:4999... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2020-01-06 18:06:29--  (try: 8)  http://localhost:4999/install/install.lock
Connecting to localhost|127.0.0.1|:4999... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

**Comment by star7th** [comment]
可能你的环境有什么安全限制了docker的运行 。可以参考这个文档一步步地安装
https://www.showdoc.cc/help?page_id=65610  ，留意是哪一步出错。

bibex <notifications@github.com> 于2020年1月6日周一 下午6:08写道：

**Comment by bibex** [comment]
解决了，   是因为nginx中  [::]:80 default ipv6only=on; ## listen for ipv6   这个配置导致

**Comment by dingpf264** [comment]
> 解决了， 是因为nginx中 [::]:80 default ipv6only=on; ## listen for ipv6 这个配置导致

我的本机也是，docker之前就已经安装了，我本机也没装nginx

**Comment by whyour** [comment]
> > 解决了， 是因为nginx中 [::]:80 default ipv6only=on; ## listen for ipv6 这个配置导致
> 
> 我的本机也是，docker之前就已经安装了，我本机也没装nginx

没有nginx这个怎么解决。
