### ISSUE TITLE
部署成功后无法访问

### ISSUE THREAD

**Issue by jiananai** [star7th/showdoc#723]
虚拟机上启动成功了，wget localhost:4999 可以得到index.html ,但是本机无法访问，防火墙已经关闭。   
 注：开始启动后可以正常访问，但是第二天就出现这个问题了

**Comment by star7th** [comment]
跟showdoc没什么关系，你的docker可能缺乏权限导致无法端口映射。wget
49990能成功就证明showdoc服务起来了。外部不能访问是服务器本身限制，至于是防火墙还是其他限制，就不知道你服务器怎么配置的了

jiananai <notifications@github.com>于2020年1月7日 周二上午11:16写道：

**Comment by jiananai** [comment]
将容器删除后重启，看到一条警告，IPv4 forwarding is disabled。就是这个原因，不知到怎么出现的，昨天还是好的
