### ISSUE TITLE
自己部署的服务器，自动生成文档的过程中，报错

### ISSUE THREAD

**Issue by jiananai** [star7th/showdoc#724]
curl: (35) SSL received a record that exceeded the maximum permissible length.

**Comment by star7th** [comment]
哪里看到的错误提示？showdoc没有用ssl

jiananai <notifications@github.com>于2020年1月7日 周二下午12:03写道：

**Comment by star7th** [comment]
另外提供下你在脚本里填写的url

Chen Xing <xing7th@gmail.com>于2020年1月7日 周二下午12:20写道：

**Comment by jiananai** [comment]
https://192.168.1.126:4999/server/index.php?s=/api/open/fromComments

**Comment by jiananai** [comment]
jenkins 执行脚本

**Comment by jiananai** [comment]
执行 curl 这行报错，我网上查，这个错误似乎是nginx 配置的问题

**Comment by star7th** [comment]
url前面部分从https改为http

jiananai <notifications@github.com> 于2020年1月7日周二 下午12:25写道：

**Comment by jiananai** [comment]
谢谢，傻了
