### ISSUE TITLE
官网自适应目录键消失，无法返回内容页面

### ISSUE THREAD

**Issue by doanys** [star7th/showdoc#725]
官网和开源版本都存在这样的现象，不只是bug还是设计就是这样的，在app上是正常的，只有手机浏览器上和PC浏览器开发模式出现过这样的情况
![Snipaste_2020-01-08_15-27-11](https://user-images.githubusercontent.com/41234678/71958584-9996c980-322b-11ea-9c46-62a0c023d853.png)

**Comment by star7th** [comment]
请说下：
你的电脑系统
屏幕分辨率
浏览器版本
整个界面完整截图

doanys <notifications@github.com> 于2020年1月8日周三 下午4:03写道：

**Comment by doanys** [comment]
以下环境测试移动端自适应：1）文档页均不出现目录四方格按键；2）文档列表与app有写出入，移动端为一行个文档

使用环境
PC：mac10.13版chrome，虚拟机win7版360极速浏览器均为最新版本1080分辨率
移动：小米手机9自带浏览器，最新版chrome

1）目录按键消失

- 图：Mac版chrome

![Snipaste_2020-01-08_17-25-16](https://user-images.githubusercontent.com/41234678/71966618-e505a380-323c-11ea-8ea7-206b32646360.png)

- 图：win7版360浏览器

![Snipaste_2020-01-08_17-31-50](https://user-images.githubusercontent.com/41234678/71966673-fbabfa80-323c-11ea-8d5e-a582b888d381.png)

- 图：小米9 Chrome浏览器

![WechatIMG37 1](https://user-images.githubusercontent.com/41234678/71966690-04043580-323d-11ea-91ec-c9c8d3883ad8.jpeg)


2）移动端文档列表与app有写出入
- 图：Mac版chrome
![Snipaste_2020-01-08_17-40-14](https://user-images.githubusercontent.com/41234678/71967252-031fd380-323e-11ea-8380-96a4bea8da9f.png)


图：小米9 Chrome浏览器
![WechatIMG38](https://user-images.githubusercontent.com/41234678/71967230-f8653e80-323d-11ea-9e14-61bc669209eb.jpeg)

**Comment by star7th** [comment]
官网网页不打算完全适配手机，项目主页能供移动端浏览查看就好。移动端的编辑建议用app。
左侧栏展开后，是打算隐藏按钮的。 要选择某个页面才行，点一下某个页面就好。


doanys <notifications@github.com> 于2020年1月8日周三 下午5:41写道：

**Comment by doanys** [comment]
好的，谢谢，请关闭工单
