### ISSUE TITLE
ldap配置成功，登录报用户名密码错误

### ISSUE THREAD

**Issue by fxl201007** [star7th/showdoc#727]
hello。ldap配置已经成功，但是登录报用户名密码错误，同样账号登录邮箱没有问题。

**Comment by fxl201007** [comment]
> hello。ldap配置已经成功，但是登录报用户名密码错误，同样账号登录邮箱没有问题。



![Uploading image.png…]()

**Comment by star7th** [comment]
检查 ldap user filed 这一项是否配置正确

fxl201007 <notifications@github.com> 于2020年1月9日周四 下午2:15写道：

**Comment by fxl201007** [comment]
我配置的是： sAMAccountName

**Comment by fxl201007** [comment]
我有个测试脚本，写的是这个，脚本测试没有问题

**Comment by star7th** [comment]
cn 和  sAMAccountName 都试一下

fxl201007 <notifications@github.com> 于2020年1月9日周四 下午2:21写道：

**Comment by fxl201007** [comment]
cn 也不行，报用户名或密码错误

**Comment by star7th** [comment]
关于ldap的反馈，我也挺无奈的。因为我测试都没问题。而反馈的环境，我无法测试和重现，没办法得知什么问题

fxl201007 <notifications@github.com> 于2020年1月9日周四 下午2:22写道：

**Comment by fxl201007** [comment]
好的，谢谢

**Comment by Jean-Jacques-Nuoan** [comment]
> 好的，谢谢

这个问题解决了么，我这边配置好之后也出现这个问题
