### ISSUE TITLE
希望能够优化多人协作文档功能

### ISSUE THREAD

**Issue by lovegames** [star7th/showdoc#729]
多个人编辑文档时可能会发生覆盖的情况,是否能加个提示,或者冲突的时候直接让用户合并类似svn的功能,急需改功能,希望能够尽快得到改善

**Comment by star7th** [comment]
在团队里比较少遇到同一个页面或者同一个接口有人同时改的情况，所以对此需求并不强烈。后面可以看下怎么完善。建议你把你的使用场景说一下，为什么需要多人同时编辑同一个文档

少年别回头 <notifications@github.com> 于2020年1月9日周四 下午5:54写道：

**Comment by lovegames** [comment]
我们公司现在为了方便管理项目的进度,让每个开发人员在一个文档表格中填写项目的进度,12个人偶尔刚下达任务,就会出现几个人把别人的进度删除了,这个时候我只能在版本管理中去恢复被误删除的进度,希望提交时候给个提示也行,一般同一个人修改应该不会出现误覆盖的问题,怎么设计能够保证不覆盖或者更好的合并文档

**Comment by star7th** [comment]
了解。后面看下怎么优化才比较好

少年别回头 <notifications@github.com> 于2020年1月9日周四 下午6:02写道：

**Comment by lovegames** [comment]
好的,谢谢,希望能看到后续的优化

**Comment by star7th** [comment]
这个需求有简单的做法有复杂的做法。最简单的就是加锁，已经有人在编辑了就不再允许编辑。其次就是智能合并解决冲突，不过后者不好处理。再看看吧。
目前来讲，如果别人覆盖了你的进度，至少你还是可以在历史版本中找回来的。

Chen Xing <xing7th@gmail.com> 于2020年1月9日周四 下午6:04写道：

**Comment by lovegames** [comment]
目前来说不会出现丢失问题是好的,就是需要有个人去翻历史记录手动合并,不够方便,稍微只能一点会方便点。

**Comment by qiujianzhong** [comment]
up up up
1.  最简单的就是加锁，已经有人在编辑了就不再允许编辑。（推荐，因为实现比较快）
2.  智能合并解决冲突
3. 使用websocket实时同步大家的修改（目前新版的confluence就是这么实现）

**Comment by star7th** [comment]
已更新新版，当用户编辑页面的时候将自动锁定，防止其他人修改覆盖
