### ISSUE TITLE
桌面屏幕宽度在617-999的时候,显示格式有问题

### ISSUE THREAD

**Issue by skefer** [star7th/showdoc#73]
使用Chrome,Opera,Edge测试之后,都有这个问题,在桌面屏幕宽度处于617-999像素之间,会出现内容下移到菜单栏下面的情况.

平板以及手机测试未出现这个问题

**Comment by star7th** [comment]
暂时不考虑这个分辨率的屏幕

**Comment by skefer** [comment]
很多时候文档打开做调试的时候,一半文档一半代码编辑界面,这样不太方便

**Comment by star7th** [comment]
刚修改了一下。当桌面屏幕宽度在617-999的时候，会自动以移动端的样式显示
