### ISSUE TITLE
页面建立table时，table列数>=6时，table总宽度变小

### ISSUE THREAD

**Issue by langpf1** [star7th/showdoc#735]
| 字段           | 类型          |  空           |  默认        | 主键          |  注释       |
| ------------   | ------------  | ------------  | ------------ | ------------ | ------------ |
| rule_type_id   |  int(4)       | 否            |              |  √           | 规则类型 ID  |
| rule_type_name |  varchar(20)  | 否            |              |              | 规则名称     |

**Comment by star7th** [comment]
当列数不足6的时候，将自动平均铺满整个宽度。当大于等于6的时候，将自动根据文字宽度适应。

**Comment by langpf1** [comment]
但这样做table很难看

**Comment by langpf1** [comment]
> 当列数不足6的时候，将自动平均铺满整个宽度。当大于等于6的时候，将自动根据文字宽度适应。

但这样做table很难看

**Comment by star7th** [comment]
大部分情况不会难看的。你这个是比较特殊的情况，设计之初没考虑的。6列这么多的情况下，依然这么少文字的情况很少见。当时是觉得，既然6列了，那么它本身的文字宽度应该撑起来了。

**Comment by langpf1** [comment]
> 大部分情况不会难看的。你这个是比较特殊的情况，设计之初没考虑的。6列这么多的情况下，依然这么少文字的情况很少见。当时是觉得，既然6列了，那么它本身的文字宽度应该撑起来了。

列数和文字能否撑得起列宽完全是两码事，看下常见的excel表就知道，即使10列能依靠文字宽度本身撑起table宽度就不错了。而且，依靠 “本身的文字宽度撑起table” 是个错误的策略。

**Comment by star7th** [comment]
我建议你上面的表格可能省略”是否主键“这一列。

Chen Xing <xing7th@gmail.com> 于2020年1月15日周三 下午4:04写道：

**Comment by star7th** [comment]
这是在api文档中实践出来的道理。如果有更多人反馈的话会尝试修正此问题。目前来看没有更多反馈。

langpf1 <notifications@github.com> 于2020年1月15日周三 下午4:02写道：

**Comment by langpf1** [comment]
> tifications@github.com> 于2020年1月15日周三

好吧。。。
