### ISSUE TITLE
切换tab时,页面会抖动

### ISSUE THREAD

**Issue by liuyangjike** [star7th/showdoc#737]
1个tab内容少,没有滚动条;
1个tab内容都,有滚动条;
来回切换会出现抖动

**Comment by star7th** [comment]
建议截图说明

liuyangjike <notifications@github.com> 于2020年1月15日周三 下午5:18写道：

**Comment by liuyangjike** [comment]
用户登录与用户注册来回切换, 会出现抖动, 切换时滚动条消失造成的
![1](https://user-images.githubusercontent.com/33151591/72426674-2a8a1980-37c5-11ea-8a78-08fd84bc2a29.png)

![屏幕快照 2020-01-15 下午6 24 29](https://user-images.githubusercontent.com/33151591/72426725-3ece1680-37c5-11ea-8eae-35a46bd0b128.png)

**Comment by star7th** [comment]
嗯，发现问题了。有空解决下

liuyangjike <notifications@github.com> 于2020年1月15日周三 下午6:33写道：

**Comment by star7th** [comment]
这个问题我再思考了下。左侧栏如果做成固定定位时可以避免抖动问题的。但是这样做会失去一些元素的自适应效果，如果改则需要大改。鉴于此问题很小，我觉得可以忽略当前这个问题吧。
