### ISSUE TITLE
建议：编辑页面时，在全屏状态下编辑时，仍然显示“保存”按钮

### ISSUE THREAD

**Issue by langpf1** [star7th/showdoc#739]
建议：编辑页面时，在全屏状态下编辑时，仍然显示“保存”按钮，否则每次都要退出全屏才能保存，体验不佳。

**Comment by star7th** [comment]
编辑器全屏不代表切换到全部东西全屏。不然会有下一个人问，全屏状态下为什么不能选择目录/改标题。
但你可以使用快捷键ctrl + s 来保存内容。

langpf1 <notifications@github.com> 于2020年1月15日周三 下午5:33写道：
