### ISSUE TITLE
sqlite 与 mysql 的数据库存储问题

### ISSUE THREAD

**Issue by 1123311314** [star7th/showdoc#74]
为什么要从mysql换到 sqlite数据库啊？ 
http://www.showdoc.cc/help?page_id=31990
这也不足以要更改数据库啊~
我个人觉得用mysql来存储还是有必要的， 毕竟mysql在存储方面的优势还是挺多的。对于已录入的数据来讲，其安全性是非常重要的。比如数据备份，数据迁移等方面。 
希望版主可以重新考虑一下，或者两种都支持 ，亦可？

**Comment by star7th** [comment]
谈到数据备份和迁移都不如Sqlite。Sqlite数据库文件就在/Sqlite这个目录，备份和迁移都直接复制走即可，跟代码文件一样。比mysql简单多了。

**Comment by star7th** [comment]
我在那个迁移页面加上这个说明。sqlite无论是备份、迁移都更简单

**Comment by 1123311314** [comment]
好吧，那我如果想查询数据库呢， sqlite应该没有远程访问方式吧？ 
sqlite毕竟只是一个数据文件，不知道该如何实现定时备份等功能...

**Comment by star7th** [comment]
去搜索下如何查看sqlite数据库，有软件的。看你是不同的服务器。我想应该是没有远程的，自己登录服务器看吧。
定时备份还不简单，直接跑个定时任务crontab复制文件。话说难道mysql备份还比这个更简单么。
鉴于showdoc的情况，需要查看数据库的情形不是很多，大部分直接网站使用即可。

**Comment by 1123311314** [comment]
你这样改了数据存储方式，我都不敢升级，毕竟我这里都录入了真实的数据， 都用了快半年了

**Comment by star7th** [comment]
备份后再升级。失败了就重新用回备份，没什么好怕的。

**Comment by vus520** [comment]
thinkphp的跨数据库类型还是比较完善的，只要严格按model操作，不直接写sql，能直接从sqlite迁到mysql上。
