### ISSUE TITLE
建议：在“团队管理”中，“添加成员”时，改为批量添加成员的方式，否则一个一个添加太麻烦了。

### ISSUE THREAD

**Issue by langpf1** [star7th/showdoc#740]

**Comment by star7th** [comment]
添加成员只麻烦在第一次，应该是可接受的。不然下拉列表很长的情况下多选也麻烦。

langpf1 <notifications@github.com> 于2020年1月15日周三 下午5:34写道：

**Comment by star7th** [comment]
但是确实如果可以批量的话可以体验会好些。我后面找时间改改

Chen Xing <xing7th@gmail.com> 于2020年1月15日周三 下午6:30写道：

**Comment by star7th** [comment]
已更新新版支持批量添加成员。

**Comment by NAIXIL** [comment]
您好，请问 v2.10.4的批量导入用户功能在哪里？

**Comment by star7th** [comment]
> 您好，请问 v2.10.4的批量导入用户功能在哪里？

这个问题下没有人说过有批量导入用户功能。我们之前说的是多选用户来添加成员的额问题。

**Comment by NAIXIL** [comment]
> > 您好，请问 v2.10.4的批量导入用户功能在哪里？
> 
> 这个问题下没有人说过有批量导入用户功能。我们之前说的是多选用户来添加成员的额问题。

好吧，不好意思，看错了。新建用户只能一个个的新增吗？

**Comment by star7th** [comment]
新建用户只能一个个的新增
