### ISSUE TITLE
在线版希望增加图片放大功能

### ISSUE THREAD

**Issue by ylg58** [star7th/showdoc#742]
https://www.showdoc.cc/ 受到在线版本页面篇幅所限；有些较大的截图 上传后缩小就不清晰了；
 希望增加个鼠标hover后图片放大功能，方便清晰查看图片

**Comment by star7th** [comment]
点击会全屏放大图片的。如果说全屏放大图片的看不清，那可能你需要优化一下你的图片了

ylg-github <notifications@github.com> 于2020年1月16日周四 上午10:41写道：

**Comment by star7th** [comment]
或者你提供项目链接我去看下

Chen Xing <xing7th@gmail.com> 于2020年1月16日周四 上午10:44写道：

**Comment by ylg58** [comment]
感谢作者；以前使用gitbook记录项目文档；但是需要编译次；这个更方便
