### ISSUE TITLE
文档链接能否选择本项目相对路径

### ISSUE THREAD

**Issue by ylg58** [star7th/showdoc#743]
类似以下这种索引；否则项目内的文档 索引到本项目其它页面时只能去 页面复制地址后才能 索引
1.  [企业NDA认证流程](\ht\ye_wu_guan_li_shi_yong\qi_ye_nda_ren_zheng_shen_he.md)
-- /project/1.md
2.  [客户产品包发放流程](\ht\ye_wu_guan_li_shi_yong\qi_ye_chan_pin_bao_fa_fang.md)
3.  [新SDK发布流程](\ht\ji_zhu_jing_74065c_kai_fa_gong_cheng_shi_shi_yong\chan_pin_bao_fa_bu_liu_cheng\README.md)

**Comment by star7th** [comment]
代码实现倒没什么的。只是感觉会引进额外的复杂度。例如需要制定一套语法，告诉用户这样写可以行内跳转。不是很想复杂化

**Comment by Priezt** [comment]
有没有办法实现站内链接？
如果直接用URL链接，在APP里会打开浏览器访问，

**Comment by star7th** [comment]
后续看下怎么做吧。可能会这么做——写的时候还是直链，只是程序判断如果是同一个项目就当前页面展开



Priezt <notifications@github.com>于2020年2月4日 周二上午10:08写道：

**Comment by star7th** [comment]
已更新新版。使用页面的绝对路径就好。它自动判断是当前项目链接，而在当前窗口展开。
