### ISSUE TITLE
编写文档的时候插入本地图片，模态框的图片地址为空，jq以下报错

### ISSUE THREAD

**Issue by cbbtop** [star7th/showdoc#744]
VM209:3 Uncaught SyntaxError: Unexpected token : in JSON at position 2
    at JSON.parse (<anonymous>)
    at HTMLIFrameElement.<anonymous> (image-dialog.js:161)

**Comment by star7th** [comment]
你不如看一下网络请求的返回结果就知道为什么报错了

Wilkins <notifications@github.com>于2020年1月16日 周四下午12:04写道：
