### ISSUE TITLE
用户密码明文被安全小组检查出来，让停止使用了

### ISSUE THREAD

**Issue by RobinsChens** [star7th/showdoc#746]
大哥们，账号搞一下加密吧

**Comment by RobinsChens** [comment]
你f12看一下，登录的时候，密码是直接明文传输了。

**Comment by RobinsChens** [comment]
你f12看一下，登录的时候，密码是直接明文传输了。

**Comment by RobinsChens** [comment]
![image](https://user-images.githubusercontent.com/11987492/72693418-b1dfe000-3b6b-11ea-92ca-1568535680d6.png)

**Comment by star7th** [comment]
原来你是说传输的过程。传输的过程showdoc本身是没有做加密的。因为我想着传输层加密是https做的事情。所以showdoc官网是https加密的。后面看一下怎么改吧。

vpclub <notifications@github.com> 于2020年1月20日周一 上午9:59写道：

**Comment by star7th** [comment]
你截图的这个是showdoc官网，已经https加密传输了的，别人截获不了。至于开源版，不一定用上https，确实要想一下。

Chen Xing <xing7th@gmail.com> 于2020年1月20日周一 上午10:02写道：

**Comment by lgh06** [comment]
前端cryptojs后加密再传输 ，只对比加密后的字符串是否一致，不进行原始密码的对比。

**Comment by star7th** [comment]
@lgh06 考虑到兼容性，加密算法已经固定了的，只能按照旧的算法在前端实现一遍。不然的话历史密码就登录不了的。
能实现倒是能实现，折腾几下总可以的。只是把全部加密都放在前端，还没考虑清楚必要性。

**Comment by huadong** [comment]
传输加密的问题交给https处理就好了，这个不需要折腾它吧。

**Comment by star7th** [comment]
加密的问题留给https处理，showdoc就不处理这个问题了。
