### ISSUE TITLE
Thinkphp版本

### ISSUE THREAD

**Issue by fxl201007** [star7th/showdoc#747]
请问最新的代码用的是Thinkphp 什么版本

**Comment by star7th** [comment]
showdoc是个重前端轻后端的产品，后端比较简单。为了兼容性，兼容低版本的php和老服务器，使用的是保守的tp3.2

fxl201007 <notifications@github.com> 于2020年1月17日周五 下午4:39写道：

**Comment by fxl201007** [comment]
🙏 谢谢

**Comment by fxl201007** [comment]
请问 ：接口除了在server目录下，还可能在哪个目录下面

**Comment by star7th** [comment]
好像都在了

fxl201007 <notifications@github.com> 于2020年1月17日周五 下午4:55写道：
