### ISSUE TITLE
部分栏目鼠标移入显示移出隐藏显示为空白

### ISSUE THREAD

**Issue by KJohn2q** [star7th/showdoc#748]
部分栏目鼠标移入显示移出隐藏显示为空白
![](https://raw.githubusercontent.com/KJohn2q/John-s-figure-bed/master/image/20200118151652.gif)

**Comment by star7th** [comment]
好像对超长标题才会这样子。有空看下

John.W <notifications@github.com> 于2020年1月18日周六 下午3:17写道：

**Comment by vilisper** [comment]
在浏览器定位到分类节点的li里面测试了一下。把下面那个css去掉可以正常。
```css
.hide-scrollbar li {
    /* white-space: normal; */
    /* overflow: hidden; */
    /* text-overflow: ellipsis;*/
}
```

**Comment by star7th** [comment]
@vilisper 你这是为了解决特殊问题而引入了更大的问题。比如你这样会导致滚动条默认都出来了。UI会难看

**Comment by KJohn2q** [comment]
只去掉 `white-space: normal;` 使得鼠标移入显示正常，鼠标移出多余部分显示`...`，会不会好一点

**Comment by star7th** [comment]
新版已解决了此问题。
