### ISSUE TITLE
关于APP

### ISSUE THREAD

**Issue by mewchen** [star7th/showdoc#750]
我用手动安装（php安装）的方式安装的最新版的ShowDoc，在使用APP的时候，一直提示 连接失败。该如何处理？

**Comment by star7th** [comment]
历史issue和场景问题都说了。 https://github.com/star7th/showdoc/issues/701 
常见问题：https://www.showdoc.cc/help?page_id=16118

**Comment by mewchen** [comment]
> 历史issue和常见问题都说了。 #701
> 常见问题：https://www.showdoc.cc/help?page_id=16118

我看过这两个，我的安卓和iOS都不行，不仅仅是iOS不行；不过我确实是宝塔面板；
我尝试下用脚本安装吧。谢谢！

**Comment by star7th** [comment]
鉴于app跟服务器的通讯依赖header会给一些人安装带来麻烦，所以我已经去掉这个设定。现在更新服务器代码、同时下载新的apphttps://www.showdoc.cc/app 便可以使用，不再依赖安装环境的header。
