### ISSUE TITLE
本地调用服务器API数据库无法访问

### ISSUE THREAD

**Issue by qdhonker** [star7th/showdoc#754]
本地启动VUE项目，调用服务器API数据库无法访问，启动代理访问
经过排查发现是本地调用API数据库文件相对路径访问时文件不存在，改成绝对路径后可以访问到文件，但是用户登陆时一直是提示用户名密码不正确，因为项目在线上也部署了，相同的账号密码线上访问是没有问题的，但是本地调用登陆接口就不行了
$ret = D("User")->checkLogin($username,$password);
$ret返回false，不知道是啥原因，求救

**Comment by star7th** [comment]
本地没装好php-sqlite环境吧。你那个路径问题我也不知道怎么。我没遇到过你说的问题。

qdhonker <notifications@github.com>于2020年2月1日 周六下午1:29写道：

**Comment by qdhonker** [comment]
如果环境有问题的话，线上的版本是不是也无法访问的，但是线上又能正常使用的

**Comment by star7th** [comment]
本地管理跟线上环境怎么可能一模一样呢，肯定有差异的，除非你是用同一个docker镜像。

qdhonker <notifications@github.com>于2020年2月1日 周六下午1:53写道：

**Comment by qdhonker** [comment]
我没有用docker，我是手动的用php环境的

**Comment by star7th** [comment]
那就本地和线上更加没关系了。线上环境ok不代表本地ok


qdhonker <notifications@github.com>于2020年2月1日 周六下午1:55写道：

**Comment by qdhonker** [comment]
呃，可能我没描述清楚线上是搭建的是完整的项目，所有功能都正常使用，我想试试看二次开发，本地没有搭建PHP环境只启动了web_src，调用服务器的API接口，出现了这样的问题

**Comment by star7th** [comment]
查看一下网络请求的url，检查两次请求的url和参数是否一模一样

qdhonker <notifications@github.com>于2020年2月1日 周六下午2:01写道：

**Comment by qdhonker** [comment]
这个都确认过了，一样的没问题的

**Comment by star7th** [comment]
不应该一样的。如果一样，那你就会遇到跨域问题。

qdhonker <notifications@github.com>于2020年2月1日 周六下午2:05写道：

**Comment by qdhonker** [comment]
服务器：
http://showdoc.hzjuym.com/server/index.php?s=/api/user/login
参数如下
username: yzl
password: 19880520
v_code: 

本地：
http://localhost:8080/server/index.php?s=/api/user/login
参数如下
username: yzl
password: 19880520
v_code: 5237

**Comment by star7th** [comment]
问题应该出现在代理上。检查下。

qdhonker <notifications@github.com>于2020年2月1日 周六下午2:23写道：

**Comment by qdhonker** [comment]
原代理设置
proxyTable: {
        '/server': {  
        target: 'http://showdoc.xxx.com', //源地址
        changeOrigin: true, //改变源
        pathRewrite: {
          '^/server': '' //路径重写
        }
      }
    },

--------------------------------------------
修改后代理
proxyTable: {
        '/server': {  
        target: 'http://showdoc.xxx.com', //源地址
        changeOrigin: true, //改变源
        pathRewrite: {
          **'^/api': 'api' //路径重写**
        }
      }
    },
修改了pathRewrite参数，这个是什么原理？
