### ISSUE TITLE
数据字典自动生成只有mysql版本吗

### ISSUE THREAD

**Issue by qdhonker** [star7th/showdoc#755]
数据字典自动生成只有mysql版本吗，现在新版本系统只有sqlite的数据

**Comment by star7th** [comment]
我不理解你这两句话的联系，第一句和第二句有什么逻辑关系。

qdhonker <notifications@github.com>于2020年2月3日 周一下午4:06写道：

**Comment by qdhonker** [comment]
https://www.showdoc.cc/script/showdoc_db.sh
现在的数据字典自动生成脚本是不是只支持mysql，sqlite数据库不支持

**Comment by star7th** [comment]
是的。sqlite生成的需求比较少

qdhonker <notifications@github.com>于2020年2月3日 周一下午4:17写道：

**Comment by qdhonker** [comment]
抱歉，搞错了
