### ISSUE TITLE
数据字典目录多访问会变慢

### ISSUE THREAD

**Issue by fxl201007** [star7th/showdoc#756]
请问：
我的数据字典是每天定时创建，时间久了，目录越来越多，感觉访问没有目录少时快，请问是否存在目录多访问会变慢的情况

**Comment by star7th** [comment]
虽然我没试过，但我觉得会。不只是因为目录多，还因为页面多。每个目录下都很多页面。它读取菜单数据应该会慢。

fxl201007 <notifications@github.com>于2020年2月3日 周一下午5:42写道：

**Comment by fxl201007** [comment]
谢谢
