### ISSUE TITLE
用户批量删除

### ISSUE THREAD

**Issue by 1141330133** [star7th/showdoc#759]
1.用户做的同步 ad域，一开始不知道怎么写格式，导致同步了1000多个计算机名，而不是真正的用户名，请问这些该怎么批量删除？或者再不行就是有什么能恢复出厂设置也行
2.还是同步ad域账号，用户存在于多个不同的目录ou（ldap base dn ）下，而不是一个ldap base dn ，这个可以填写多个吗，格式怎么写，回车隔开还是分号，逗号，空格？
3.刚把ldap version改成了2，用户那里就什么都没了，showdoc都没了，就有一个空白弹窗，但是新建用户showdoc提示已存在
![image](https://user-images.githubusercontent.com/58717677/73836671-cf3eca80-484a-11ea-9685-b024f3eb691d.png)

**Comment by star7th** [comment]
1，没有批量删除的功能。也没有恢复出厂设置。如果没有数据。你可以选择全新安装。
2，只有一个，没有考虑多个的情况。你尝试下填上一层目录看是否有效。

1141330133 <notifications@github.com>于2020年2月5日 周三下午6:58写道：

**Comment by 1141330133** [comment]
第3个问题现在怎么解决，什么都没了

**Comment by star7th** [comment]
用户表都被弄乱了，所以报错。我也不知道怎么弄了。重新装一个吧。希望你在做这样的操作前有备份。把代码目录复制一份就是备份。

1141330133 <notifications@github.com>于2020年2月5日 周三下午9:26写道：
