### ISSUE TITLE
webp图片上传出错

### ISSUE THREAD

**Issue by doanys** [star7th/showdoc#760]
官方的测试如下：
https://www.showdoc.cc/p/8c92a2fd76bdb5fc09eb787d3e2a8eeb

开源版测试：
内网部署了开源版的，在复制粘贴方式方式上传的图片，格式都会变成png。
通过编辑器组件上传的，和官方的一样都是正常显示

**Comment by star7th** [comment]
可能是复制粘贴的方式不兼容webp格式。我有时间再看下

doanys <notifications@github.com>于2020年2月8日 周六上午11:07写道：

**Comment by star7th** [comment]
我这边了解下，复制粘贴方式上传确实不支持动图，只支持静态图片。
目前我觉得需求很少，基本上很少人用到复制粘贴方式上传webp格式动图，所以可能不打算处理此问题。

**Comment by doanys** [comment]
webp格式的动图也是第一图遇到，能直接调用Markdown的话最好，额外开发的话先放下，毕竟是小众去求这种图也不是经常有手动处理一下就好。

希望可以处以一下仅在开源版的复制粘贴问题：jpg格式的图片复制粘贴后会变成png格式，图片文件会变大。

**Comment by star7th** [comment]
我调试了下，好像php本身把图片识别为png了。估计系统剪贴板复制图片的时候就是png格式的。

**Comment by doanys** [comment]
嗯，官方版没有出现这个情况，jpg复制还是jpg。开源版更在2月8日更新是有这个问题存在，后面版本的暂时没更新过

**Comment by star7th** [comment]
官方版由于是面对大量用户，所以图片使用的是云储存，和开源版的不太一样。估计是php框架本身对本地图片文件的处理机制不太一样。建议如果很介意文件体积的话使用点击上传方式吧。
