### ISSUE TITLE
迁移showdoc除了创建人外其他人员无法编辑 查看接口

### ISSUE THREAD

**Issue by luzh-link** [star7th/showdoc#763]
从一个机器将showdoc迁移到另一个机器后
项目设置-成员管理无法添加人员
无法编辑查看其他人编辑的接口
查看浏览器返回结果为500

**Comment by star7th** [comment]
500是服务器内部错误，应该是新机器的环境有问题。

luzh-link <notifications@github.com> 于2020年2月11日周二 下午2:21写道：

**Comment by star7th** [comment]
确保安装的环境一模一样，确保文件权限可写。

Chen Xing <xing7th@gmail.com> 于2020年2月11日周二 下午2:22写道：
