### ISSUE TITLE
自动安装后怎么改成自己的域名和端口

### ISSUE THREAD

**Issue by breeve** [star7th/showdoc#764]
执行的自动安装，最终是以docker形式跑起来的，是通过ip访问的 ，怎么改成域名？

**Comment by star7th** [comment]
常见问题里有 https://www.showdoc.cc/help?page_id=16118

breeve <notifications@github.com> 于2020年2月11日周二 下午3:13写道：

**Comment by breeve** [comment]
多谢  建议还是原生支持的好，做一次代理比较麻烦 0-0
