### ISSUE TITLE
备案号如何增加？

### ISSUE THREAD

**Issue by liulipengju** [star7th/showdoc#765]
项目已部署在docker里面，如何添加备案号呢

**Comment by star7th** [comment]
没有这样的设置，因为没做过这样的考虑。
安装showdoc通常是在子域名下，不填写备案号不会有人查的。你的主域名的网站填写了就好。

liulipengju <notifications@github.com> 于2020年2月13日周四 上午11:51写道：

**Comment by liulipengju** [comment]
阿里云要求子域名也要填写

**Comment by liulipengju** [comment]
![image](https://user-images.githubusercontent.com/10510950/74400387-b640a580-4e58-11ea-9f27-a1013ee66f24.png)

**Comment by star7th** [comment]
没事的，忽略这个信息。我用阿里云几年了，从没有在子域名添加备案号。你的子域名不是用来做广泛的公众服务就好，只是自己团队用不会有问题。

liulipengju <notifications@github.com>于2020年2月13日 周四下午12:02写道：

**Comment by liulipengju** [comment]
好的
