### ISSUE TITLE
建议：导出多种格式的文件，比如md，pdf

### ISSUE THREAD

**Issue by Bugatti100Peagle** [star7th/showdoc#766]
现状：只有Word一种导出文件，Word导出格式会走样，而且Word非程序猿常用
需求：希望能导出带目录带标签的pdf，至少能导出.md的文件压缩包，这样我可以自己手动导出pdf

**Comment by star7th** [comment]
这个是可以考虑的。不过想问下，showdoc本是主打在线文档分享的，为何这么重度依赖导出的pdf

张婧琦 <notifications@github.com> 于2020年2月15日周六 上午11:11写道：

**Comment by Bugatti100Peagle** [comment]
因为pdf要打印出来交领导，交申请材料之类，还有申请软件著作权做软件的配套手册用。虽然这些都可以人工复制搬运，但是如果能从在线文档直接导出就更方便了。不过我好奇的是，为什么会最先支持Word？网页的编辑是用Markdown，而居然没有.md文件可以导出？

**Comment by qdhonker** [comment]
+1

**Comment by jimmyleeking** [comment]
+1

**Comment by star7th** [comment]
新版已经支持导出markdown压缩包，可以逆向重新导入showdoc

**Comment by jack80342** [comment]
> 新版已经支持导出markdown压缩包，可以逆向重新导入showdoc

太棒了。感谢

**Comment by xgdgsc** [comment]
建议增加一个pdf导出，这样直接一点，word pdf md应该能覆盖大多数人的需求了。

**Comment by GLTSC** [comment]
+1
