### ISSUE TITLE
告警: showdoc.cc 官网挂了

### ISSUE THREAD

**Issue by cliveyuan** [star7th/showdoc#768]
告警: showdoc.cc 官网挂了

**Comment by star7th** [comment]
好像是挂了一下，恢复了。原因在找。

cliveyuan <notifications@github.com> 于2020年2月17日周一 下午8:19写道：

**Comment by star7th** [comment]
没事，有个接口没做限制，被人大量扫描导致服务器超负荷。现在已经恢复并做限制了。

**Comment by gaohuixx** [comment]
> 没事，有个接口没做限制，被人大量扫描导致服务器超负荷。现在已经恢复并做限制了。

还有这种人，也太坏了吧
