### ISSUE TITLE
为什么项目没有做分类管理呢 ？强烈建议做项目集，即分类管理或叫标签之类

### ISSUE THREAD

**Issue by nan100** [star7th/showdoc#770]
为什么项目没有做分类管理呢 ，项目一多一个大页面显示好难查找？
1、强烈建议做项目集；
2、即分类管理或叫标签之类

**Comment by star7th** [comment]
目前项目有拖动排序和搜索功能。把类似的拖到一起就是简单的分类了。不过showdoc一开始是没考虑过太多项目的情形的。你现在大概有多少项目，多少种类型，需要这样的功能

yinan-tech <notifications@github.com> 于2020年2月19日周三 下午9:18写道：

**Comment by nan100** [comment]
你这个项目，是我见过最好用，最简单、简洁、而且更方便的是【直接用sqlitecopy 到那里都可以】 的文档工具。
场景：
1、团队协作 使用的；
2、个人整理学习、备忘等；
分类 ：
我有40个项目，有需求的，有接口，有设计的，规划等，还有一些知识积累等 

真的建议做个标签，这样简单实用

**Comment by star7th** [comment]
这个交互得好好想。主要是我不想那些项目少的用户被分类功能打扰，因为他们还不需要分类功能，挂在网页上很显得多余、不够简单。
或许我做一个跟归类或者标签类似的功能，然后只有项目超过20个的用户才能看到。
如果你有好的交互建议也可以说下。

yinan-tech <notifications@github.com> 于2020年2月19日周三 下午9:29写道：

**Comment by star7th** [comment]
现在刚给showdoc加了全局搜索功能，在我的项目列表里可以看到搜索框。这种情况下，检索会很方便。不知道项目分组或者标签是否还有必要。你可以说说你的想法。

**Comment by star7th** [comment]
已发布新版，支持了项目分组功能。

**Comment by chuancyzhang** [comment]
你好，作者。我们的项目太多了，不同类型的文档散落在不同的项目里，所以希望能有一个标签的功能，可以对文档进行标签，从而在项目之上进行再一次分类，方便查找。 @star7th

**Comment by star7th** [comment]
@chuancyzhang 缩搜索功能是可以全局文档搜索的。
