### ISSUE TITLE
showdoc绘制流程图, 最下面一部分无法显示

### ISSUE THREAD

**Issue by huenrong** [star7th/showdoc#771]
使用showdoc绘制流程图时, 生成的文档, 最后一部分显示异常, 如下图所示, 红色标注部分无法显示
![image](https://user-images.githubusercontent.com/47348530/74907898-4e0d3900-53ef-11ea-8f90-5ca436465259.png)

**Comment by star7th** [comment]
印象中是历史问题。你到新版看看有没有这个毛病。没有的话证明已经修复了

**Comment by huenrong** [comment]
我之前截图是使用的在线版, 目前下载了windows客户端(showdoc1.0.0.exe), 仍旧有这个问题

**Comment by star7th** [comment]
提供下在线链接

huenrong <notifications@github.com> 于2020年2月20日周四 下午4:59写道：

**Comment by huenrong** [comment]
https://www.showdoc.cc/huenrong?page_id=3918966628405050

**Comment by star7th** [comment]
可能判断高度有点问题。你在流程图的下方写一句话看看。即不要用流程图结尾。

huenrong <notifications@github.com> 于2020年2月20日周四 下午5:04写道：

**Comment by huenrong** [comment]
您看一下, 我已经增加了
![image](https://user-images.githubusercontent.com/47348530/74918255-c8e04f00-5403-11ea-91ac-5a660cb1a655.png)
另外增加后预览那边也有问题
![image](https://user-images.githubusercontent.com/47348530/74918306-dc8bb580-5403-11ea-8f4f-829e233ab378.png)

**Comment by star7th** [comment]
把原文内容发出来下

**Comment by huenrong** [comment]
原文内容很长. 您提供一下您的showdoc用户名, 我把您加到加到成员里面, 您应该就可以编辑吧

**Comment by star7th** [comment]
showdoc12356

huenrong <notifications@github.com> 于2020年2月20日周四 下午5:14写道：

**Comment by huenrong** [comment]
已经添加, 您看一下

**Comment by star7th** [comment]
一时间找不到思路。等有空的时候再细细看吧。

huenrong <notifications@github.com> 于2020年2月20日周四 下午5:17写道：

**Comment by huenrong** [comment]
好的, 麻烦您了, 成员里面我继续保留了您, 您可以随意编辑, 测试

**Comment by star7th** [comment]
发现这里增加一个换行就可以了。我也搞不清除为什么。
![image](https://user-images.githubusercontent.com/2200494/77225370-6a94c080-6ba9-11ea-8a52-3a056959c56a.png)

**Comment by huenrong** [comment]
我这边看您的截图发现最下面一个判断框的yes分支仍旧不能看到呢？

**Comment by star7th** [comment]
这个问题比较麻烦，可能我解决不了或者说解决的成本过高。showdoc是依赖其他开源组件来实现这个图的。这个图是那个组件自身的问题。而那个组件的作者不好联系。我也不好改这个组件。
我觉得你这种应该是比较特殊的情况下的bug吧。一般情况下应该没问题的

**Comment by huenrong** [comment]
是的，我之前也尝试过使用其它的markdown编辑器，同样的代码也遇到过这种情况。辛苦您忙了这么久！
