### ISSUE TITLE
文档url项目id是自增数字，内容容易被别人爬取

### ISSUE THREAD

**Issue by wuwu20048** [star7th/showdoc#774]
目前项目文档的链接是下面这种方式,随意改变文档id即可访问。但有时我们只是想让对方访问特定的页面，也不用输入密码。
http://域名/#/2

建议将文档id，改成随机字符串的方式。

**Comment by star7th** [comment]
出于兼容历史的考虑，不打算改这个。要加密的请分享单页面加密地址或者加上项目访问密码。showdoc一开始的设计就不打算用url来实现文档的隐蔽性


xfgg <notifications@github.com> 于2020年2月25日周二 下午1:54写道：
