### ISSUE TITLE
求换一个现代点的editor.md样式,或暴露出来支持自定义.

### ISSUE THREAD

**Issue by mrimeg** [star7th/showdoc#777]
如题,现在的样式json实在太不敏感了,key和value一个颜色.API感官不是很好

**Comment by star7th** [comment]
你可以提供一个好的现代化的例子来参考一下怎么样才算现代化

mrimeg <notifications@github.com>于2020年2月29日 周六上午1:14写道：

**Comment by star7th** [comment]
我简单地优化了下代码块的UI，不求漂亮，但求和文档其他内容地风格比较搭，走简洁风。
