### ISSUE TITLE
从这里下载的包，电脑管家提示木马呢？

### ISSUE THREAD

**Issue by wuyahui** [star7th/showdoc#778]
![image](https://user-images.githubusercontent.com/10398980/75618572-67f70a80-5bab-11ea-8208-61274099a61e.png)

**Comment by star7th** [comment]
误报吧。你把它解压后，再扫描下，看一下是哪个文件

**Comment by wuyahui** [comment]
嗯，应该是误报，我解压之后再扫描就没了
