### ISSUE TITLE
不觉得这个JS太大了吗

### ISSUE THREAD

**Issue by cwjhome** [star7th/showdoc#779]
js/vendor.e142ae298b8919d4a6df.js

1MB的服务器 居然 下载用了7秒第一次打开没缓存的情况下

**Comment by star7th** [comment]
框架本身这么大。部署的时候自己启用nginx的zip压缩吧

cwjhome <notifications@github.com> 于2020年3月3日周二 下午1:22写道：

**Comment by Ecareyu** [comment]
@star7th 可以用路由懒加载切割一下路由

**Comment by star7th** [comment]
@star7th 用处不是很大。而且showdoc暂时不考虑为1M的未开启压缩的外网服务器增加开发成本。多数情况下是为内网团队使用考虑。假如开启了zip压缩，体积至少降低一半。
