### ISSUE TITLE
建议增加docker方式部署

### ISSUE THREAD

**Issue by cyntcl** [star7th/showdoc#78]
现在很多公司都使用docker方式安装应用，开发人员很多都没有直接访问服务器的权限。

**Comment by star7th** [comment]
后续会作考虑

**Comment by star7th** [comment]
已经支持Docker，详情参考：http://www.showdoc.cc/help?page_id=65610

**Comment by isnotnull** [comment]
Docker 方式部署建议增加一个 Context Path 的设置。
