### ISSUE TITLE
新的服务器安装新的showdoc  如何 使用旧账号，或者访问以前的文件

### ISSUE THREAD

**Issue by wskkhn-hezhong** [star7th/showdoc#781]
我按照官网 迁移服务器  的方式 迁移了服务器，用浏览器访问http://x.com/index.php?s=/home/update/db （请将网址更改为你服务器域名或ip）。看到OK字样。但是我如何访问 以前的文档，或则使用旧账号的登录

**Comment by star7th** [comment]
直接用旧账户登录即可

he zhong <notifications@github.com> 于2020年3月4日周三 下午3:14写道：

**Comment by wskkhn-hezhong** [comment]
但是提示用户名或密码错误

**Comment by star7th** [comment]
单凭这个信息不能知道什么问题。如果严格按照教程每一步来是可以无缝迁移的。确保新服务器的环境安装好，文件权限都有。

he zhong <notifications@github.com> 于2020年3月4日周三 下午3:18写道：

**Comment by wskkhn-hezhong** [comment]
有可能，我原有的数据被覆盖了。算了，不搞了
