### ISSUE TITLE
v2.5.5版本到当前版本页面无法删除

### ISSUE THREAD

**Issue by kang1024** [star7th/showdoc#782]
描述：v2.5.5版本到当前版本页面无法删除
提示信息：
![image](https://user-images.githubusercontent.com/13195373/75861179-fbdd0680-5e37-11ea-91dc-4ea2c17b3ec7.png)
![image](https://user-images.githubusercontent.com/13195373/75861316-2fb82c00-5e38-11ea-8692-1a1d5d1f67d7.png)
 
备注：win+wamp安装，回退至v2.5.3可以正常删除

**Comment by star7th** [comment]
升级的时候执行过升级数据库脚本了吗？另外要按照教程来，千万别简简单单把程序覆盖就当作升级了。

yang.jiankang <notifications@github.com> 于2020年3月4日周三 下午4:50写道：

**Comment by kang1024** [comment]
没有看到有windows相关的升级说明和数据库脚本的操作
我是备份原有的www，然后删除，将新的代码拷贝到空的www目录下，然后将showdoc.db.php和Public\Uploads覆盖

**Comment by star7th** [comment]
https://www.showdoc.cc/help?page_id=13732

![image](https://user-images.githubusercontent.com/2200494/75863448-75c2bf00-5e3b-11ea-9c52-11602858b557.png)

**Comment by kang1024** [comment]
嗯嗯，看了这里的说明 
![image](https://user-images.githubusercontent.com/13195373/75870801-80368600-5e46-11ea-802c-e9eb90361102.png)
