### ISSUE TITLE
能否设置关掉浏览器后再打开需要重新登录

### ISSUE THREAD

**Issue by vilisper** [star7th/showdoc#783]
或者说超过多少个小时后就自动cookie失效了session失效了。现在不拖动退出登录的话，默认的好久都不会失效，打开浏览器就可以直接上了。
php不熟悉，请教一下。

**Comment by star7th** [comment]
没有这样的设置。几个月后会失效。

vilisper <notifications@github.com> 于2020年3月5日周四 上午10:52写道：
