### ISSUE TITLE
转让功能可否支持转让给多个人（转让给团队也可以）

### ISSUE THREAD

**Issue by suiriass** [star7th/showdoc#784]
一个项目可能需要多人一起进行管理，如果可以让管理权限多人，就更棒了。

**Comment by star7th** [comment]
转让功能是没必要支持转给多个人的。只是说，添加成员的时候，可以考虑给这个成员管理员权限。关于这点，我还没想清楚有没有必要

suiriass <notifications@github.com> 于2020年3月6日周五 上午9:53写道：

**Comment by suiriass** [comment]
好的，关于这点，我会继续保持关注，支持你们。 -，-
