### ISSUE TITLE
希望能在当前页面跳转的支持，不要在新窗口打开

### ISSUE THREAD

**Issue by yujindong** [star7th/showdoc#785]
1. 能否支持url的规则，比如使用path来管理，不使用hash
如 
http://location/web/#/item/index
展示成
http://location/web/item/index

2. 希望能在本页面打开新的链接的支持，目前链接都在新页面打开
如
`
[链接标题](http://location/web/#/item/index?_self)
`
目前这种a链接的target会被强制变成_blank
`
<a href="http://location/web/#/item/index" target="_self">链接</a>
`

**Comment by star7th** [comment]
第1个问题，开源版本的showdoc不支持。
第2个问题，会想一下怎么处理比较好

yujindong <notifications@github.com> 于2020年3月6日周五 下午6:51写道：

**Comment by star7th** [comment]
已更新新版。使用页面的绝对路径就好。它自动判断是当前项目链接，而在当前窗口展开。
