### ISSUE TITLE
怎么把官方的数据库同步到本地环境

### ISSUE THREAD

**Issue by liucysun** [star7th/showdoc#787]
新搭建了本地代码，但是之前的接口都在官网https://www.showdoc.cc里面，现在想把官网的接口同步到迁移到新搭建的本地环境，怎么处理

**Comment by star7th** [comment]
官网在线服务为数据托管服务而生，并没有考虑过私有化的需求。有私有化需求的应该一开始部署开源版showdoc。官网的数据库结构和开源版的完全不一样，没法直接导入导出。你当前只能手动复制内容过去。


liucysun <notifications@github.com> 于2020年3月10日周二 上午11:29写道：
