### ISSUE TITLE
可否支持导入Postman的JSON

### ISSUE THREAD

**Issue by wwhai** [star7th/showdoc#789]
可否支持导入Postman的JSON,目前大部分接口都是postman保存的

**Comment by star7th** [comment]
这个功能在规划中。后面会实现。

wangwenhai <notifications@github.com> 于2020年3月11日周三 上午9:47写道：

**Comment by star7th** [comment]
新版已经支持导入postman

**Comment by jiang1988tao1** [comment]
> 新版已经支持导入postman

请问下，导入postman和导入swagger是在哪个页面操作呢，已更新版本没找到使用方法呢

**Comment by star7th** [comment]
更新新版并刷新浏览器缓存。新建项目——文件导入

jiang1988tao1 <notifications@github.com>于2020年3月21日 周六下午3:58写道：

**Comment by wwhai** [comment]
> 新版已经支持导入postman

目前还是有些问题：
我本地Postman：
![image](https://user-images.githubusercontent.com/20577297/77223582-de7a9d00-6b98-11ea-9a10-eaa87aea9dac.png)
导入进来：
![image](https://user-images.githubusercontent.com/20577297/77223592-ef2b1300-6b98-11ea-929a-f83a8babef92.png)
貌似参数丢失了，解析的应该不太完善

**Comment by star7th** [comment]
你是导入整个postman吗。按照收藏夹一个个来。一个收藏夹一个项目。

wangwenhai <notifications@github.com>于2020年3月21日 周六下午5:25写道：

**Comment by star7th** [comment]
后面做下兼容提醒

Chen Xing <xing7th@gmail.com>于2020年3月21日 周六下午5:28写道：

**Comment by star7th** [comment]
可能确实有些兼容问题。我现在更新了。你更新到master版本看看

**Comment by jiang1988tao1** [comment]
> 
> 
> 可能确实有些兼容问题。我现在更新了。你更新到master版本看看

只能建项目的时候导入一次，没法新增或更新，意义不大，可以考虑下支持更新及部分新增，swagger过于侵入式我才选择的showdoc，相比mock，showdoc更简洁清晰，如果可以按规范写文档，能够导回mock或者postman更好了，或者能像mock那样简单的支持mock接口服务就完美了

**Comment by star7th** [comment]
如果你要做那种支持更新的操作，可能你自己要程序利用showdoc的api去实现了。https://www.showdoc.cc/page/102098 如果是非常大众的需求，官方会把这个功能集成进来。但我目测是比较小众的需求，所以可能要用户自行扩展了。

**Comment by wwhai** [comment]
> 如果你要做那种支持更新的操作，可能你自己要程序利用showdoc的api去实现了。https://www.showdoc.cc/page/102098 如果是非常大众的需求，官方会把这个功能集成进来。但我目测是比较小众的需求，所以可能要用户自行扩展了。

Postman应该是比较普遍的工具吧

**Comment by gitlsl** [comment]
swagger  用的人比 postman 要多哦

**Comment by star7th** [comment]
@gitlsl 已经支持导入swagger了的

**Comment by star7th** [comment]
已经推出了一个专门调试api的客户端 https://www.showdoc.cc/runapi?page_id=30291  ,可以初始化从postman导入. 后续变动会自动同步到文档中.  基本可以替代postman . 鉴于此,不再提供postman的动态更新功能.
