### ISSUE TITLE
数据字典自动生成，只有前面的几张表是正常的，剩下的全部只有表名称和表注释

### ISSUE THREAD

**Issue by 15083500070** [star7th/showdoc#791]
表中的字段注释也没有特殊是特殊符号的，有最多的符号是 _ 和 :   

![1583995172(1)](https://user-images.githubusercontent.com/49858189/76494410-c061be00-646f-11ea-9eb9-6ff6cb2b2de2.jpg)

**Comment by 15083500070** [comment]
![1583995172(1)](https://user-images.githubusercontent.com/49858189/76495026-08cdab80-6471-11ea-9175-44ad4050586d.jpg)

**Comment by star7th** [comment]
目前已知的问题是 & 符号会切割字符串从而不完整。如果没有&符号，目前我没有遇到也没有听过反馈说会截断字符串。

15083500070 <notifications@github.com> 于2020年3月12日周四 下午2:52写道：

**Comment by 15083500070** [comment]
好的，谢谢
