### ISSUE TITLE
对markdown的支持不是特别友好

### ISSUE THREAD

**Issue by zyq11223** [star7th/showdoc#793]
![image](https://user-images.githubusercontent.com/22373016/76609139-d942a000-6551-11ea-8206-e74ac0d22023.png)

![image](https://user-images.githubusercontent.com/22373016/76609108-caf48400-6551-11ea-83fd-8a59dda98cfd.png)

**Comment by star7th** [comment]
其实这算是markdown的扩展语法吧，不属于markdown原有的功能里面的。你不妨发一下原文给我试下

**Comment by zyq11223** [comment]
这个就是原文$$score_{t} = score _{t-1} + score_{t-2}e^{-\alpha (T-t)}$$，不知道上传的图片为啥不显示了，图片中就有原文的

**Comment by zyq11223** [comment]
> 其实这算是markdown的扩展语法吧，不属于markdown原有的功能里面的。你不妨发一下原文给我试下

这个就是原文$$score_{t} = score _{t-1} + score_{t-2}e^{-\alpha (T-t)}$$，不知道上传的图片为啥不显示了，图片中就有原文的

**Comment by star7th** [comment]
我这里挺正常的 https://www.showdoc.cc/ 

![image](https://user-images.githubusercontent.com/2200494/77272673-b603b780-6cec-11ea-9899-288f15cae8c8.png)

![image](https://user-images.githubusercontent.com/2200494/77272695-bf8d1f80-6cec-11ea-923e-020fb265f6d8.png)
