### ISSUE TITLE
提示访问密码错误

### ISSUE THREAD

**Issue by ksyson** [star7th/showdoc#794]
新建项目 => 复制已存在项目 => 私密项目 => 设置密码
按照这样创建项目后，修改了多次密码，还是提示“访问密码不正确”。

**Comment by star7th** [comment]
设置密码功能被很多人试过，目前为止我并没有听过过功能有问题的反馈。我倾向于你检查输入的密码是不是真的对。或者你提供能被外网访问的地址我看看。

ksyson <notifications@github.com>于2020年3月13日 周五下午10:07写道：

**Comment by ksyson** [comment]
抱歉...找到问题所在了，不是密码的问题，是我个人的操作问题。
我创建完项目后，先打开了项目，跳到了 https://www.showdoc.cc/item/password/XXX 的访问密码界面。
之后又修改了个性域名，先前打开的页面没有关闭，导致一直在先前个性域名的链接输入密码，一直提示“访问密码不正确”。

非常抱歉，Showdoc还是非常好用的~
