### ISSUE TITLE
升级到最新版本后，无法进行页面之间（相对路径）的跳转了

### ISSUE THREAD

**Issue by jzhw** [star7th/showdoc#797]

**Comment by star7th** [comment]
页面之间的跳转是什么意思

jzhw <notifications@github.com>于2020年3月15日 周日下午12:45写道：

**Comment by star7th** [comment]
是不支持相对路径的。后面再看看怎么优化

**Comment by jzhw** [comment]
恩，就是形如`[站内链接1](#/page/edit/1/3 "站内链接1")`这样的跳转。
升级前的上一个版本大概是2019年1月份的，是可以跳转的。升级到最新版（2020-02）后，这样的链接点击后是无效的，必须写绝对路径，另外绝对路径会在新窗口而不是当前页面打开。

**Comment by star7th** [comment]
已更新新版。使用页面的绝对路径就好。它自动判断是当前项目链接，而在当前窗口展开。

**Comment by XinNoil** [comment]
> 已更新新版。使用页面的绝对路径就好。它自动判断是当前项目链接，而在当前窗口展开。

可惜，我部署的showdoc用户访问的域名是不同的，其他人部署时域名也有可能在使用时变化。支持相对路径还是很有必要的。

现在的相对路径不是不能跳转，而是需要手动刷新一下才行。
