### ISSUE TITLE
开源版有新增https加密传输的计划吗？

### ISSUE THREAD

**Issue by Vinery** [star7th/showdoc#798]
由于本地部署的要放到公网上，开源版目前只支持http传输，不知后期开发是否有ssl加密传输的考虑，谢谢！

**Comment by star7th** [comment]
跟showdoc没什么关系。自己装个nginx，支持https访问。然后再转发到showdoc服务端口。

Vinery <notifications@github.com>于2020年3月15日 周日下午6:16写道：
