### ISSUE TITLE
样式问题

### ISSUE THREAD

**Issue by cjhuaxin** [star7th/showdoc#80]
编辑预览的时候是正常的，但是保存以后样式就不对了
![image](https://cloud.githubusercontent.com/assets/3345975/18948548/1eb5d0a0-866a-11e6-9246-59525ff35884.png)
![image](https://cloud.githubusercontent.com/assets/3345975/18948644/7b715c1a-866a-11e6-90a4-a1033dd8d561.png)
另外有个问题，就是如果某一些太长了，保存后就会导致服务器宕机，这是两个使用过程中遇到比较头疼的问题

**Comment by star7th** [comment]
你语法写错了吧，表格都没有用 | 闭合。自己检查下是否符合markdown语法吧。
对于某些页面太长的情况，可能超过了2M大小，post 不了数据过去。你检查下在线showdco是否有这个问题http://www.showdoc.cc/ 如果不是showdoc的问题，则可能你服务器允许上传的文件大小有限制。搜索下网络，如何修改php的最大上传大小

**Comment by star7th** [comment]
原来你是指这个问题https://github.com/star7th/showdoc/issues/87
有人贡献了代码帮忙解决此问题了
