### ISSUE TITLE
左侧目录不能隐藏，字体无法调整大小

### ISSUE THREAD

**Issue by ABAPer-Hah** [star7th/showdoc#800]
网页版左侧的目录不能隐藏，导致文档正文的表格无限全部显示。
并且字体无法调整大小，正文表格列数过多的时候，文档的显示一点不友好。

**Comment by star7th** [comment]
个人觉得这个问题可能无解。因为即使隐藏目录，表格列数再多一点也还是会存在这样的问题

ABAPer-Hah <notifications@github.com> 于2020年3月18日周三 上午9:33写道：

**Comment by CodeBoy975** [comment]
隐藏目录我感觉可以提高用户体验，左侧是用户导航需要，当找到对应文档，则隐藏目录这样的话我觉得更好。我看例如极客时间专栏那些，就有一个纯净模式就是隐藏目录的作用。虽然页面也没放大，但这点感觉体验会更好哈。提个小小建议哈

**Comment by star7th** [comment]
由于showdoc比较简洁，且两边是灰色色调，这种情况纯净模式没有太多作用。所以不打算改了
