### ISSUE TITLE
手机端查看信息为什么都转到这个代理服务器了？ 信息岂不是泄露了。。

### ISSUE THREAD

**Issue by zhengfenwei** [star7th/showdoc#801]
https://ali.star7th.com/http_agent.php

**Comment by zhengfenwei** [comment]
手机端查看信息为什么都转到这个代理服务器了？ 信息岂不是泄露了，希望可以提前说一声这种设置啊
https://ali.star7th.com/http_agent.php

**Comment by star7th** [comment]
这是官方的代理。原因：
1，大多数开源showdoc都不用https，而应用商店要求https，所以干脆加了一层https代理。
2，手机app对返回的header有要求。很多人部署开源版的时候都改了header导致用不了。你可以搜索很多历史issue。现在加一层代理，不再依赖用户安装情况。


fenwei.zhengfw <notifications@github.com>于2020年3月19日 周四上午8:49写道：

**Comment by star7th** [comment]
假如不加这代理，有一半开源版用户用不了app，所以我在后来就加代理了。目前来看我觉得这是一个较好的选择。

Chen Xing <xing7th@gmail.com>于2020年3月19日 周四上午8:56写道：

**Comment by zhengfenwei** [comment]
感谢为小白用户的周到考虑。

**Comment by zhengfenwei** [comment]
是否方便提供app端的源代码，因为公司网络安全审核比较严格。内网部署的产品，内网无法使用手机查看信息。

**Comment by star7th** [comment]
手机端不打算开源，太麻烦了。部署、编译起来比网页端复杂好多倍。按照经验必定惹来一堆小白来问各种奇怪的问题。

fenwei.zhengfw <notifications@github.com>于2020年3月19日 周四下午6:55写道：

**Comment by zhengfenwei** [comment]
😄😺😁
