### ISSUE TITLE
请问应如何做到向官网一样的链接

### ISSUE THREAD

**Issue by lovebai** [star7th/showdoc#802]
自己安装的会在链接上带有/web/#/，而官网的不带着

**Comment by star7th** [comment]
开源版不支持这样。

xiaobai <notifications@github.com> 于2020年3月19日周四 下午2:41写道：

**Comment by lovebai** [comment]
那商业版可用购买吗

**Comment by star7th** [comment]
不开放此功能。你可以说明下为什么一定要这个功能。

xiaobai <notifications@github.com> 于2020年3月19日周四 下午5:45写道：
