### ISSUE TITLE
请问一下数据迁移问题

### ISSUE THREAD

**Issue by PPQiao** [star7th/showdoc#803]
+ 我想请问一下: 

1.我是在另一台服务器上重新部署了新的showdoc
2.用xftp二进制模式把showdoc.db.php传输到新的服务器上, 覆盖了原来的文件, 
3.使用http://x.com/index.php?s=/home/update/db 得到 OK!
4.重启新服务器上的showdoc.  采用管理员账号登录后, 没有任何备份过来的数据, 也没有以前的用户账号,

+ 备注 : 我原来的账户也是默认的showdoc账户, 改了密码

**Comment by star7th** [comment]
感觉还没覆盖文件。你可以比较一下文件大小来判断文件到底有没有覆盖了。

PPQiao <notifications@github.com> 于2020年3月20日周五 上午10:16写道：

**Comment by PPQiao** [comment]
非常感谢你的及时回复, 是我自己放错地方了,
现在账号已经回来了,  但是数据还是有问题,
我用的是xftp 二进制模式.传输的呀.
我看了浏览器控制台, `showdoc`后台接口报了一个错
```
{"error_code":999,"error_message":"SQLSTATE[HY000]: General error: 1 no such table: single_page \u3002\u9519\u8bef\u4f4d\u7f6e\uff1a\/var\/www\/html\/server\/ThinkPHP\/Library\/Think\/Db\/Driver.class.php  156"}
```

**Comment by star7th** [comment]
重新执行你上面说的第3步

PPQiao <notifications@github.com> 于2020年3月20日周五 上午10:32写道：

**Comment by PPQiao** [comment]
重新执行, 还是得到 OK! , 重新访问showdoc提示重置了账户密码,  
进入后还是 数据不完整, **文档列表已经出来了**, 但是**右侧文档内容**还是空的, 后台报错
```
{"error_code":999,"error_message":"SQLSTATE[HY000]: General error: 1 no such table: single_page \u3002\u9519\u8bef\u4f4d\u7f6e\uff1a\/var\/www\/html\/server\/ThinkPHP\/Library\/Think\/Db\/Driver.class.php  156"}
```

**Comment by star7th** [comment]
执行多几次。另外确保文件有可写权限

PPQiao <notifications@github.com> 于2020年3月20日周五 上午10:42写道：

**Comment by PPQiao** [comment]
非常感谢, 多执行几次,我的问题解决了, 
虽然我还是不太清楚为什么
