### ISSUE TITLE
一点小小的建议

### ISSUE THREAD

**Issue by keepthinkingit** [star7th/showdoc#805]
官网 [docker 手动安装](https://www.showdoc.cc/help?page_id=65610)教程中:
```
mkdir /showdoc_data
mkdir /showdoc_data/html
```

可以合并为 : mkdir -p /showdoc_data/html
这是我在看**自动脚本安装**章节中,下载的官网脚本发现的 , 在脚本 133 行的判断可以优化一下 . 
当然不改也是没问题的 .

**Comment by star7th** [comment]
哎呀，用了那么久我还真不知道p参数。去查了下才知道。脚本还是保留现状吧，但docker教程我会更正下

keepthinkingit <notifications@github.com> 于2020年3月21日周六 下午8:58写道：
