### ISSUE TITLE
Mac系统一打开showdoc.cc CPU就疯狂跑高

### ISSUE THREAD

**Issue by yeliheng** [star7th/showdoc#807]
在mac系统打开showdoc CPU疯狂占用，i9可以吃掉一半左右，然后温度飙升，风扇就开始转。已经使用多台Mac测试过，都存在这个问题。 **在Windows下没有这个问题。**
希望能够得到解决。
机型: MacBookPro 2019 15''
系统版本 macOS Catalina 10.15.4

**Comment by star7th** [comment]
比较难搞。可能是showdoc引用的某个开源组件存在兼容问题。有时间再看看吧。

DroidYe <notifications@github.com> 于2020年3月22日周日 下午5:23写道：

**Comment by star7th** [comment]
我刚在我虚拟机上尝试过了， 没发现问题。是win上的虚拟机，虚拟的是macos 10.13系统。然后我盯着cpu使用率，全程没超过50%
。我个人认为这可能不是showdoc问题

Chen Xing <xing7th@gmail.com> 于2020年3月22日周日 下午6:26写道：

**Comment by yeliheng** [comment]
好的 感谢！这个问题可能会比较棘手，因为它仅在macos平台上出现，用同事的电脑测试也是同样的结果，可能是平台兼容性的问题。你们可以尝试用mac复现看看，辛苦了！

**Comment by yeliheng** [comment]
我测试了一下，在Mac的Google Chrome上会有上述问题，而在内置的Safari浏览器打开showdoc没有问题。

**Comment by star7th** [comment]
我确实是用 Safari浏览器测试的，没问题。然后，对于MAC用户，应该是用 Safari浏览器居多，所以我可能暂时没精力折腾这个问题。

DroidYe <notifications@github.com> 于2020年3月23日周一 上午11:08写道：

**Comment by yeliheng** [comment]
好的

**Comment by d1313113** [comment]
同 mac + chrome,这个问题大概半年前就一直有, showdoc.cc 打开 cpu 会飙升,但自建的 showdoc 并不会
