### ISSUE TITLE
能不能支持无限级的目录，至少也5级吧，3级不够用，求大佬满足

### ISSUE THREAD

**Issue by lyjaizyq** [star7th/showdoc#808]

**Comment by star7th** [comment]
以后再考虑吧；当前最好把大型复杂项目切分成几个小项目，别把一个项目弄得太复杂。

lyjaizyq <notifications@github.com> 于2020年3月23日周一 下午12:04写道：

**Comment by sinjonxi** [comment]
有同样的需求，请支持扩展5级或无限极目录

**Comment by star7th** [comment]
原来这个issue我还没回应。前段时间已经支持无限层级目录了。更新新版吧。
