### ISSUE TITLE
请问后期是否会考虑增加复制项目的功能?

### ISSUE THREAD

**Issue by skefer** [star7th/showdoc#81]
觉得这个在线版文档分享工具很好用.但目前发现一些问题:
1.很多时候json在格式化的时候,会将参数说明放入对应值中,能否提供转参数表格的时候直接将json的值放入参数表格中.
2.很多时候文档对应的是一个系统的发布版本.比如代码发布V1.2版本时,有对应的在线版文档.然后这个文档给一个地方用了.但后期代码发布新分支的时候如V1.3.这个时候需要保留原来的版本文档,增加一个新的文档.所以能否提供一个复制当前项目的功能,也就是将当前项目打包复制到一个新项目中.然后只用在新项目中修改文档就行了.

再次感谢star7th提供的在线版文档

**Comment by star7th** [comment]
直接将json的值放入参数表格中先不考虑，主要因为json太多格式了，比如嵌套的json，就有好几个值。很难做统一。

复制文档功能会做考虑。

**Comment by star7th** [comment]
刚刚加上了复制项目功能。在新建项目的时候可以选择从已有项目中复制
