### ISSUE TITLE
本地使用docker安装，下载markdown类型的压缩包不成功

### ISSUE THREAD

**Issue by kongh** [star7th/showdoc#811]
本地使用docker安装，下载markdown类型的压缩包不成功，压缩包大小为0

**Comment by star7th** [comment]
发现这个问题了。有空找下原因

孔航 <notifications@github.com> 于2020年3月23日周一 下午10:45写道：

**Comment by star7th** [comment]
已修复。请更新代码到最新master版本

Chen Xing <xing7th@gmail.com> 于2020年3月24日周二 上午11:31写道：
