### ISSUE TITLE
想学习大佬的Dockerfile配置php

### ISSUE THREAD

**Issue by lyjaizyq** [star7th/showdoc#812]
大佬能教一下Dockerfile怎么配置php吗，百度都找不到能正常运行的教程，把你的Dockerfile拿过来用也不行，求大佬不吝赐教

**Comment by star7th** [comment]
我觉得这几行命令已经非常简单了。如果你这都不懂，可能基础有点缺。这不是我一两句话就能教懂。你还是先去补一下功课，Dockerfile的运行机制吧
