### ISSUE TITLE
建议json格式化的工具位置优化

### ISSUE THREAD

**Issue by gpqhl0071** [star7th/showdoc#813]
编辑的时候，多了一个 json格式化的工具，工具非常实用，但是每次使用的时候，都要向上划才能点击该功能，操作不是很友好。感觉作者，可以放在方便点击的地方。

**Comment by star7th** [comment]
有空会优化此问题

高鹏 <notifications@github.com> 于2020年3月24日周二 下午5:15写道：

**Comment by star7th** [comment]
我目前发了新版，做的改动是，默认一进入页面的时候，这个保持在顶部（原来的是会一进入页面就滚动到底部）。
不过倒没有做一直保留在顶部功能，因为想给编辑器更大一点的编辑控件。

**Comment by gpqhl0071** [comment]
> 我目前发了新版，做的改动是，默认一进入页面的时候，这个保持在顶部（原来的是会一进入页面就滚动到底部）。
> 不过倒没有做一直保留在顶部功能，因为想给编辑器更大一点的编辑控件。

好的，明天我更新下版本，体验下，感谢作者。软件很好用，已经推广公司组内使用。
