### ISSUE TITLE
&#124; 竖线被转义了，不能正常显示

### ISSUE THREAD

**Issue by Feng-YunFei** [star7th/showdoc#815]
&#124; 在编辑页面可以正常显示，保存成文档就被转义了

**Comment by star7th** [comment]
实测没有被转义。另外请不要在表格中放置竖线，会跟markdown本身的东西冲突。

**Comment by Feng-YunFei** [comment]
@star7th 你应该没有在表格中试，我在表格中输入（& # 1 2 4;）保存后是不能正常显示成竖线的，被当成表格的语法解析了，之前老版本的文档可以显示成竖线。

**Comment by star7th** [comment]
表格中不支持任何形式的竖线

Felix <notifications@github.com> 于2020年3月26日周四 下午1:47写道：

**Comment by Feng-YunFei** [comment]
好的，谢谢。

**Comment by star7th** [comment]
已发布新版。使用转义字符 `&#124; `  即可
