### ISSUE TITLE
导出单个文件

### ISSUE THREAD

**Issue by lehman-china** [star7th/showdoc#816]
导出功能很好用,现在只能导出 全部或某个目录; 
  因为这边每个文档都是一个独立项目的文档,请问可以帮忙支持一下,导出指定某个文件的功能吗?

**Comment by star7th** [comment]
单个文档的情况你就直接手动复制到word里面吧，这种情况总体来讲比较少

雷建军 <notifications@github.com> 于2020年3月26日周四 上午8:41写道：

**Comment by Delena1988** [comment]
手动复制到word布局不太对

**Comment by star7th** [comment]
你利用浏览器的打印功能打印成pdf看看

Delena1988 <notifications@github.com> 于2020年3月26日周四 下午2:51写道：
