### ISSUE TITLE
文章链接里面的ID建议调整为无序

### ISSUE THREAD

**Issue by RyanSuen** [star7th/showdoc#818]
您好：

	我们目前使用的是showDoc开源版本， 我发现了一个安全性的问题。希望showDoc官方能够优化，以使产品变得更好。

https://doc.xxx.yyy/web/#/20?page_id=388   其中的两个ID都是有规律可循的，期望官方有优化。

如果我曾经有过某一项目的权限， 即使后面即便文档被删除，我还是可以通过爬虫设置一定的规律爬回不少数据。

**Comment by star7th** [comment]
你进入项目设置-回收站就可以看到提示。删除后三天失效。此外showdoc的设定就是，只有加访问密码才能防止爬虫。不会试图想从url上防爬虫。

RyanSuen <notifications@github.com> 于2020年3月27日周五 上午10:14写道：

**Comment by star7th** [comment]
想一次性永久删除，用showdoc账户登录管理后台删除项目。

Chen Xing <xing7th@gmail.com> 于2020年3月27日周五 上午10:15写道：
