### ISSUE TITLE
建议导出文件时能将流程图转为图片

### ISSUE THREAD

**Issue by longbull007** [star7th/showdoc#819]
在文档里面写了流程图，页面上显示正常，但是导出为文件用word打开只看到一堆代码，建议导出时将流程图转为gif图片插入到文件中

**Comment by star7th** [comment]
word里面不打算处理流程图，太麻烦了。目前我没看到有很好的后端渲染markdown流程图方案。且消耗性能/导出的文件体积不可控，可能很大导致导出失败。

Long Guohua <notifications@github.com> 于2020年3月27日周五 上午11:34写道：
