### ISSUE TITLE
导出功能

### ISSUE THREAD

**Issue by oceanbaby715** [star7th/showdoc#82]
是否可以加入单页面导出，并且导出的word不带样式非常很丑

**Comment by star7th** [comment]
单页面的话，直接手动复制到word就好了。
word带样式的问题，其实我也想。但技术上有难度同时也比较繁琐。没有找到比较省力的方案，如果你有方案的话欢迎提供思路

**Comment by efmoe** [comment]
为何不支持导出为PDF呢？ @star7th

**Comment by star7th** [comment]
@efmoe PDF导出的样式比word好不到哪里去。同样是技术繁琐的同时带不来太大的使用效率提升，吃力不太讨好。
如果给文档对方看，还是直接发个链接好了
