### ISSUE TITLE
服务非正常关闭时数据丢失的疑问？

### ISSUE THREAD

**Issue by 1989zj** [star7th/showdoc#820]
本人使用宿主机安装了KVM虚拟机，然后在KVM上安装了docker，当我直接关闭宿主机后，重新启动后，内部数据都不见了，貌似被还原了，请问是否有什么地方的数据或者配置需要修改？

**Comment by star7th** [comment]
不懂docker的人切换擅自自作聪明违反官方教程来安装。docker自身的特性就是重启后还原数据。需要做目录映射把数据持久化到/showdoc_data
/html 。如果是参照官方教程，严格每一步都按照教程来的话，是做了持久化的。建议使用官方一键脚本安装
https://www.showdoc.cc/help?page_id=828455960655160

 1989zj <notifications@github.com> 于2020年3月27日周五 下午9:10写道：

**Comment by 1989zj** [comment]
好的，谢谢。  这个没有注意到。
