### ISSUE TITLE
建议文件夹可以分享

### ISSUE THREAD

**Issue by Alina0753** [star7th/showdoc#821]
现在文件夹是分享不了的，建议作出可分享。

**Comment by star7th** [comment]
请说使用场景。

Alina0753 <notifications@github.com>于2020年3月30日 周一上午7:32写道：

**Comment by Alina0753** [comment]
一个项目里面有多个文件夹，每个文件夹下面很多的文件，想把这个文件夹里面的所有内容分享给队员，但是不想分享项目的全部文件，一个文件一个文件分享又费时费力。。。。

**Comment by star7th** [comment]
目前看不到有这个必要性。看看其他用户是否反馈有这个需求。

Alina0753 <notifications@github.com>于2020年3月30日 周一下午11:49写道：

**Comment by duoni** [comment]
同求 文件夹可以分享
