### ISSUE TITLE
搜索功能用不了

### ISSUE THREAD

**Issue by Alina0753** [star7th/showdoc#822]
2020-03-29下载的showdoc，部署在windows上。搜索功能用不了。
1、进入项目左上角，在搜索框输入关键字，点击enter按钮，一直转圈圈，搜索结果出不来。
url：http://localhost/web/#/3?page_id=10
2、用户管理和项目管理，点击查询按钮，，一直转圈圈，搜索结果出不来。
url: http://localhost/web/#/admin/index

**Comment by star7th** [comment]
win下要开启php-sqlite3.dll

Alina0753 <notifications@github.com>于2020年3月30日 周一上午7:37写道：

**Comment by Alina0753** [comment]
怎么开启php-sqlite3.dll ？

**Comment by star7th** [comment]
网络搜索下


Alina0753 <notifications@github.com> 于2020年3月30日周一 上午9:14写道：

**Comment by Alina0753** [comment]
①把以下代码保存到文档，并保存名称为test.php

    <?php
        phpinfo();    
    ?>
②把test.php复制到服务根目录，我这里的目录是：D:\phpstudy_pro\WWW
③重启服务，访问http://localhost/test.php ，得到服务使用的php.ini配置文件的路径，我这里是：D:\phpstudy_pro\Extensions\php\php7.3.4nts\php.ini
④查看D:\phpstudy_pro\Extensions\php\php7.3.4nts\ext文件夹下的dll，应该有php_sqlite3.dll和php_pdo_sqlite.dll
⑤修改php.ini配置文件，添加以下2行。
    extension=php_pdo_sqlite.dll
    extension=php_sqlite3.dll
⑥重启服务，搜索功能正常了。

问题解决了。谢谢~

**Comment by Alina0753** [comment]
搜索功能正常了，非常感谢~
