### ISSUE TITLE
选择中文安装后还是英文

### ISSUE THREAD

**Issue by whuxxie** [star7th/showdoc#823]
选择中文安装后还是英文。怎么更改

**Comment by star7th** [comment]
没有提供更改。请重装

whuxxie <notifications@github.com> 于2020年3月30日周一 上午9:47写道：

**Comment by star7th** [comment]
选择中文后还是英文，我从没讲过这样的事情。

Chen Xing <xing7th@gmail.com> 于2020年3月30日周一 上午9:48写道：

**Comment by star7th** [comment]
见过

Chen Xing <xing7th@gmail.com> 于2020年3月30日周一 上午9:48写道：

**Comment by whuxxie** [comment]
#执行安装。默认安装中文版。如果想安装英文版，将下面参数中的zh改为en
curl http://localhost:4999/install/non_interactive.php?lang=zh
这是是选择的zh，但还是英文界面

**Comment by whuxxie** [comment]
参考 https://www.showdoc.cc/help?page_id=65610

**Comment by star7th** [comment]
你这是升级安装。之前安装的是中文还是英文

whuxxie <notifications@github.com> 于2020年3月30日周一 上午9:53写道：

**Comment by star7th** [comment]
我刚才安装教程操作了一遍。没有问题。

**Comment by whuxxie** [comment]
问题已经解决，按照自动脚本安装显示中文，很奇怪，昨天也是这么安装的显示英文，也有可能是安装完以后，还没进入网站看就先升级了，升级后的就是英文。刚才按照自动脚本安装后就进入网站看，中文显示。但是安装完以后，显示了几条没有response的消息
