### ISSUE TITLE
建议优化添加菜单

### ISSUE THREAD

**Issue by jiang1988tao1** [star7th/showdoc#826]
建议在添加菜单时，可直接在父级菜单右侧增加加号，直接用加号添加子级别目录，否则每次添加目录还要再去找父级菜单。

**Comment by star7th** [comment]
嗯，后面会加上这个功能

jiang1988tao1 <notifications@github.com> 于2020年3月31日周二 下午1:46写道：

**Comment by star7th** [comment]
已经在新版支持
