### ISSUE TITLE
团队中又大量的doc文档 ，doc格式下导入进来要先转换成markdown吗 ， 还是说这块内容需要自己去定制化

### ISSUE THREAD

**Issue by xufeifeiWHU** [star7th/showdoc#827]

**Comment by star7th** [comment]
mardown文档可以转换成很多种格式，doc，pdf，html等等，有相应工具都可以转。但是，doc格式很难转成doc，因为没有一个通用的格式标准。你可以用什么工具或者自己编程把doc转成markdown后再调用api写入showdoc  https://www.showdoc.cc/page/102098

**Comment by xufeifeiWHU** [comment]
okok , 了解 ， 感谢答复
