### ISSUE TITLE
执行 自动生成 api文档时报错 api_key 或者api_token不匹配 但是我检查是一样的？？？

### ISSUE THREAD

**Issue by yangcc001** [star7th/showdoc#830]
执行 自动生成 api文档时
![image](https://user-images.githubusercontent.com/52573000/78089677-b2fa7c80-73fa-11ea-88f6-b7cb2c04726b.png)

报错 api_key 或者api_token不匹配 但是我检查是一样的？？？

是否是因为url 的问题
![image](https://user-images.githubusercontent.com/52573000/78089775-ef2ddd00-73fa-11ea-9ee8-6c5062e67179.png)

**Comment by star7th** [comment]
url没问题。只能是api_key 或者api_token不匹配
