### ISSUE TITLE
团队=》编辑团队名只能删除不能修改

### ISSUE THREAD

**Issue by BBDooooog** [star7th/showdoc#831]
编辑团队名的时候只能够删除，不能增加  需要删除团队再新增

**Comment by star7th** [comment]
已发现问题。晚点改下。

BBDog <notifications@github.com> 于2020年4月3日周五 下午2:14写道：

**Comment by star7th** [comment]
已在新版修复

Chen Xing <xing7th@gmail.com> 于2020年4月3日周五 下午3:51写道：
