### ISSUE TITLE
使用腾讯云centos7+Nginx+PHP部署应用，一直访问不到

### ISSUE THREAD

**Issue by 15562401205** [star7th/showdoc#833]
https://www.showdoc.cc/php?page_id=14595
我参考这篇教程进行的部署，都比较顺利，但部署完后一直访问不到页面。
`server {
        listen       80;
        server_name  localhost;
        root         /var/www/html;
        index index.php index.html;
        error_page  404              /404.html;
        location = /40x.html {
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
        }
        location ~ \.php$ {
            #root           /var/www/html;
            fastcgi_pass   localhost:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            include        fastcgi_params;
        }
        location ~ /\.ht {
            deny  all;
        }
        
    }`

nginx的配置是这样的，但是每次访问ip都是：
Welcome to CentOS
The Community ENTerprise Operating System

欢迎页面，因没有学习过PHP，不知道是部署哪里有问题，还请大佬帮忙查看一下。

**Comment by star7th** [comment]
有外网的linux系统都建议使用官方一脚脚本，就简单执行命令就好，不需要折腾
https://www.showdoc.cc/help?page_id=828455960655160

15562401205 <notifications@github.com> 于2020年4月3日周五 下午3:50写道：

**Comment by 15562401205** [comment]
你好，目前我是在外网环境上做测试，最终需要部署到公司内网主机上，所以还是希望采用Nginx+PHP的形式部署

**Comment by 15562401205** [comment]
你好，目前我是在外网环境上做测试，最终需要部署到公司内网主机上，所以还是希望采用Nginx+PHP的形式部署

**Comment by star7th** [comment]
重启nginx，删除/conf.d目录下的其他干扰配置文件。 /var/www/html目录下确保放置了代码

15562401205 <notifications@github.com> 于2020年4月3日周五 下午3:56写道：

**Comment by 15562401205** [comment]
/var/www/html目录下目前放的是：

total 70992
-rwxrwxrwx  1 root root      564 Apr  2 14:35 composer.json
-rwxrwxrwx  1 root root      385 Apr  2 14:35 Dockerfile
drwxrwxrwx  4 root root     4096 Apr  2 14:35 documentation
-rwxrwxrwx  1 root root     4286 Apr  2 14:35 favicon.ico
-rwxrwxrwx  1 root root 72614038 Apr  3 11:09 html.tar.gz
-rwxrwxrwx  1 root root     5953 Apr  3 15:16 index.html
-rwxrwxrwx  1 root root     1023 Apr  2 14:35 index.php
drwxrwxrwx  2 root root     4096 Apr  2 16:12 install
-rwxrwxrwx  1 root root     1743 Apr  2 14:35 LICENSE.txt
drwxrwxrwx 14 root root     4096 Apr  2 16:18 phpMyAdmin4.8.5
drwxrwxrwx 15 root root     4096 Apr  2 14:35 Public
-rwxrwxrwx  1 root root     4221 Apr  2 14:35 README.md
-rwxrwxrwx  1 root root       30 Apr  2 14:35 robots.txt
drwxrwxrwx  4 root root     4096 Apr  2 14:35 server
drwxrwxrwx  2 root root     4096 Apr  2 16:36 Sqlite
drwxrwxrwx  3 root root     4096 Apr  3 10:31 web
drwxrwxrwx  8 root root     4096 Apr  2 16:50 web_src

/conf.d目录下只有自己加的一个conf配置文件,我试了一下将listen 80 端口改为8080 ，直接变成了无法访问此网站。

**Comment by star7th** [comment]
查看一下nginx日志应该有头绪。一般放在/var/log/nginx

15562401205 <notifications@github.com> 于2020年4月3日周五 下午4:05写道：

**Comment by star7th** [comment]
其实公司内网也可以考虑用docker’的。docker镜像外网下载后再导入就行了

Chen Xing <xing7th@gmail.com> 于2020年4月3日周五 下午4:14写道：
