### ISSUE TITLE
建议支持页面宽度调整

### ISSUE THREAD

**Issue by q1045243113** [star7th/showdoc#835]
如果markdown表格宽度比较宽的话,会自动出现横向滚动条.
需要来回不停拖动浏览, 十分麻烦.
希望能支持页面宽度调整.
![image](https://user-images.githubusercontent.com/25606194/78638381-c916aa00-78de-11ea-82fe-2ade06b1425d.png)

**Comment by star7th** [comment]
当前可能不太倾向调整宽度。主要是照顾不同分辨率下的阅读一致性。不然在你这里显示正常了，在另一个分辨率下则变形难看。
后面会探索下有没有更好的解决方法

**Comment by q1045243113** [comment]
那能否支持宽度调整仅本次有效, 至少允许我在自己阅读的时候可以调整宽度.
不然一直拖动滚动条确实操作太繁琐了

**Comment by star7th** [comment]
这个后面会再考虑下

qgyoung <notifications@github.com> 于2020年4月7日周二 下午3:53写道：

**Comment by situchen** [comment]
需求+1，这样太累了，明明页面足够大，却居中显示，导致显示不全。很难受，希望能考虑下加入此功能。

**Comment by star7th** [comment]
这个问题挂在这里很久了。考虑到拖动宽度太麻烦，这个事情不再处理。markdown大表格始终只是很少数的场景，专门为此场景做那么大改变不值得。
