### ISSUE TITLE
ui优化建议，内容建议

### ISSUE THREAD

**Issue by asdf3309** [star7th/showdoc#837]
1.左侧目录现在比较小巧了，搜索框还是很大，，
2.能不能再单页内支持锚点目录，现在写a标签比较累

**Comment by star7th** [comment]
原来这个问题我没有回复。你可以使用markdown的TOC标签来自动生成标题目录，不用自己写描点。

**Comment by asdf3309** [comment]
原来是这样，我都是直接在上面写 。。
