### ISSUE TITLE
不显示“登陆页”

### ISSUE THREAD

**Issue by xusongtao** [star7th/showdoc#839]
可能上周修改过配置文件（不确定），docker安装的showdoc不显示登陆页了，右上角也没有登陆按钮，清空缓存也没用。现在不能编辑文章了，请问是什么原因呢？

**Comment by star7th** [comment]
按照教程升级吧，代码会还原的  https://www.showdoc.cc/help?page_id=65610

xusongtao <notifications@github.com> 于2020年4月10日周五 上午9:41写道：
