### ISSUE TITLE
如何引入资源文件

### ISSUE THREAD

**Issue by masquevil** [star7th/showdoc#84]
你好，我想找一套文档管理系统，用来管理前端的组件文档，展示效果类似 bootstrap 的文档。于是找到了 showdoc，感觉非常棒！

不过在用于前端组件文档时，必须要引入每个前端项目自己的 css 和 js 文件。目前我可以通过修改`/Application/Home/View/Common`的源码实现，但是在对于多项目分别引入不同的文件时，这就会很吃力。
请问有没有便捷的方法实现这一需求？

此外，所有的 Controller 和 View 都是一般的 ThinkPHP 文件吗？因为之前没用过 ThinkPHP，所以想确认一下。如果是的话，我可以去学习一下 ThinkPHP，然后自己花点功夫实现自己的需求……

**Comment by star7th** [comment]
前端组件文档其实不太适合用现成的文档管理系统去做，而是适合用这些前端组件去开发html页面展示。

如果真的要用的话，只能文档和演示分离。在showdoc上写文档，然后demo链接到一个新的页面展示。在showdoc的项目上引用组件本身是不好的
