### ISSUE TITLE
局域网问题

### ISSUE THREAD

**Issue by fanjialing** [star7th/showdoc#841]
你好作者,我们在使用局域网搭建好了之后,浏览器和windows客户端都可以正常访问,但是Android端和IOS端在填写我局域网的ip端口后提示无法正常连接,但是在我另外一台公网ip的服务器上是可以的。

**Comment by star7th** [comment]
手机端访问必须经过外网。

fanjialing <notifications@github.com>于2020年4月11日 周六下午2:26写道：
