### ISSUE TITLE
按照docker安装流程下来后无法访问showdoc

### ISSUE THREAD

**Issue by MetaGalaxy-star** [star7th/showdoc#844]
安装到最后一步是这样子的：
![image](https://user-images.githubusercontent.com/45158961/79180759-5907a700-7e3d-11ea-8ba3-192d4cc4e608.png)
然后根据自己的云主机ip和域名：http://metagalaxy.top:4999 ，还是无法访问showdoc：
![image](https://user-images.githubusercontent.com/45158961/79180891-adab2200-7e3d-11ea-81da-21df3ce619b4.png)
![image](https://user-images.githubusercontent.com/45158961/79180920-bb60a780-7e3d-11ea-8867-9e7e0d195c66.png)

谢谢你！

**Comment by star7th** [comment]
如果 curl http:127.0.0.1:4999 有结果，则证明是外网的防火墙或者安全组限制了

**Comment by MetaGalaxy-star** [comment]
执行 curl http://127.0.0.1:4999 没结果耶，请问这是什么原因呢？
![image](https://user-images.githubusercontent.com/45158961/79183336-c4547780-7e43-11ea-8605-a61b0f4e2da8.png)

**Comment by MetaGalaxy-star** [comment]
执行 curl http://127.0.0.1:4999 没结果耶，请问这是什么原因呢？
[root@iz2ze4h5335buh06q5rjkjz wwwroot]# curl http://127.0.0.1:4999
[root@iz2ze4h5335buh06q5rjkjz wwwroot]# 

![image](https://user-images.githubusercontent.com/45158961/79183404-f9f96080-7e43-11ea-86bf-4cd066c10af3.png)

**Comment by star7th** [comment]
没报错应该就是端口通了。检查防火墙和安全组吧

柘月十七 <notifications@github.com> 于2020年4月14日周二 上午11:34写道：

**Comment by MetaGalaxy-star** [comment]
感谢大佬的指教！目前已经解决。
总结：问题出在防火墙端口没有开放，并注意安全组里端口问题。
