### ISSUE TITLE
使用video标签插入视频，没有换行但未能正常加载

### ISSUE THREAD

**Issue by Cyrus-Jiang** [star7th/showdoc#845]
现插入代码如下：
`<video style="width: 100%; height: 100%;" controls="controls" preload="true"><source id="mp4" src="http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4" type="video/mp4"></video>`

效果如下，视频无法播放：
![image](https://user-images.githubusercontent.com/12857599/79227594-ba0d9a00-7e92-11ea-994e-f82274e4a2ce.png)

数据库page表存储：
```
72|3|xxAdmin|4|22|默认页面|<video style="width: 100%; height: 100%;" controls="controls" preload="true"><source id="mp4" src="http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4" type="video/mp4"></video>|99|1586867212||0
```

没有搜到类似的问题，麻烦大佬帮忙抽空看下，可能是什么情况？多谢了，安装方式是docker

**Comment by star7th** [comment]
我就算直接浏览器打开http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4 也用不了。你不如先尝试用一个真正能播放的视频链接看看。

**Comment by star7th** [comment]
好像刚才是出现了一个画面。然后又黑屏了。我不知道这是不是网络服务器比较慢的问题。另外就是插入视频是原生html标签的问题，你问我我也只能搜索html标签语法的

**Comment by Cyrus-Jiang** [comment]
> 我就算直接浏览器打开http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4也用不了。你不如先尝试用一个真正能播放的视频链接看看。

![image](https://user-images.githubusercontent.com/12857599/79228793-9fd4bb80-7e94-11ea-8449-08d40aa14eb3.png)
不是的，可能这个视频连接比较慢，但是我搜了个别的在线编辑试了下，相同代码内容是可以加载出来的
![image](https://user-images.githubusercontent.com/12857599/79228870-bed34d80-7e94-11ea-950f-20660f6726e0.png)

**Comment by star7th** [comment]
我尝试用这个代码的时候，视频链接的网络请求出错。我觉得就是视频源的兼容问题。你换个视频源试试。
```
<video style="width: 100%; height: 100%;" controls="controls"src="http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4" type="video/mp4"></video>
```

**Comment by Cyrus-Jiang** [comment]
> 我尝试用这个代码的时候，视频链接的网络请求出错。我觉得就是视频源的兼容问题。你换个视频源试试。
> 
> ```
> <video style="width: 100%; height: 100%;" controls="controls"src="http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4" type="video/mp4"></video>
> ```

试了下七牛的还有淘宝的，目前还是无法播放`https://cloud.video.taobao.com//play/u/1811495788/p/1/e/6/t/1/253552879598.mp4`

**Comment by Cyrus-Jiang** [comment]
showdoc这边用video标签后，source两边被包裹了双引号，所以是有视频框但不能识别url，所以无法展示视频内容。但是数据表中存储却没有双引号，感觉问题可能在于js前台这边处理的问题？

**Comment by star7th** [comment]
我用这段代码播放成功了。
```

<video style="width: 100%; height: 100%;" controls="controls" src="https://tbm-auth.alicdn.com/e99361edd833010b/HE5OQ9lgpgEs76Vl8Cs/KUKuv41TztlB70tAmVm_253552879598_hd_hq.mp4?auth_key=1586875071-0-0-d06dde619bf256a8d4c0707bdbde51f0" type="video/mp4"></video>

```

**Comment by star7th** [comment]
尝试只用video 标签，不用socurce

**Comment by Cyrus-Jiang** [comment]
> 尝试只用video 标签，不用socurce

解决了，非常感谢
