### ISSUE TITLE
怎么修改管理员showdoc的用户名？

### ISSUE THREAD

**Issue by libo0528** [star7th/showdoc#846]
是直接操作数据库么？具体命令是什么？sqlite小白，谢谢

**Comment by star7th** [comment]
官方不提倡修改。

libo0528 <notifications@github.com> 于2020年4月15日周三 下午4:14写道：

**Comment by libo0528** [comment]
二开修改了登录功能，需要指定用户为管理员，这么实现？

**Comment by star7th** [comment]
这是二次开发文档  https://www.showdoc.cc/help?page_id=1385576954326448

libo0528 <notifications@github.com> 于2020年4月15日周三 下午4:17写道：

**Comment by hesunfly** [comment]
如果需要修改默认管理员用户名或者填写一个用户为管理员用户的话，可以直接修改sqlite数据库中的数据

**Comment by wx5123** [comment]
> 是直接操作数据库么？具体命令是什么？sqlite小白，谢谢
update user set username='admin' where uid=1;

**Comment by wx5123** [comment]
> 二开修改了登录功能，需要指定用户为管理员，这么实现？

修改user表中的groupid，1是管理员，2是普通用户。
