### ISSUE TITLE
显示的代码格式和编辑的格式不一致

### ISSUE THREAD

**Issue by LeiZhiMin1** [star7th/showdoc#847]
### 这个是编辑模式下的格式

![image](https://user-images.githubusercontent.com/32741993/79340735-5a2ff580-7f5d-11ea-9137-0340936918f8.png)

### 这个是显示模式下的格式

![image](https://user-images.githubusercontent.com/32741993/79340853-7fbcff00-7f5d-11ea-9632-5b95123faa55.png)

在编辑模式下json的格式已经调整好了，同时也填写了json格式，但是最终显示的样式却完全不一致，希望能够修改一下这个问题。

**Comment by LeiZhiMin1** [comment]
使用的是官方部署项目，也就是<https://www.showdoc.cc/>网址

**Comment by star7th** [comment]
你尝试用鼠标选择代码块，然后tab一下？不要那么贴边

**Comment by LeiZhiMin1** [comment]
下面那个截图是展示模式下，不是编辑模式，如何点击tab

**Comment by star7th** [comment]
那就在编辑框里选中代码，然后键盘tab

**Comment by LeiZhiMin1** [comment]
好的，解决了，没想到还有这种操作。。。
