### ISSUE TITLE
Swagger

### ISSUE THREAD

**Issue by NBTim** [star7th/showdoc#849]

**Comment by star7th** [comment]
你的问题是什么?导入sg到showdoc，请“新建项目”-“文件导入”

NBTim <notifications@github.com> 于2020年4月17日周五 下午2:34写道：

**Comment by qyd159** [comment]
可以从showdoc导出swagger文档吗？

**Comment by star7th** [comment]
@qyd159 不能。这个功能麻烦而对showdoc没什么帮助，不想花时间去做。
