### ISSUE TITLE
页面样式问题

### ISSUE THREAD

**Issue by chenyf119** [star7th/showdoc#85]
昨天官网更新后，页面内容“```  ```”之间的内容CSS样式有些问题，行高变大了，空白行显示了行号。
图1：
![image](https://cloud.githubusercontent.com/assets/6840584/19543692/f8612db2-96ab-11e6-85fb-9edd282080c1.png)
图2：
![image](https://cloud.githubusercontent.com/assets/6840584/19543686/e40a2f62-96ab-11e6-9bdb-970553a2865d.png)

**Comment by star7th** [comment]
有没有链接看下。行高确实是高了一些，但是我没有发现空白行出现行号的问题

**Comment by star7th** [comment]
行高的问题我解决了

**Comment by star7th** [comment]
空行显示行号的问题也解决了

**Comment by chenyf119** [comment]
Thanks
