### ISSUE TITLE
Swagger的json导入，返回示例显示有问题

### ISSUE THREAD

**Issue by NBTim** [star7th/showdoc#850]
环境：https://www.showdoc.cc
示例页面：https://www.showdoc.cc/770624711159771?page_id=4276723077928062
问题：
通过swagger导出的json文件，导入至showdoc新建项目，若接口返回的对象则显示不佳，截图如下：
![图片](https://user-images.githubusercontent.com/32887039/79539473-f9b5cb00-80b8-11ea-8e61-be1b380e811a.png)
期待效果：
想YAPI那样，能解析对象结构，想过入截图：
![图片](https://user-images.githubusercontent.com/32887039/79539561-2bc72d00-80b9-11ea-8604-dfc822bd9230.png)
导入所用的json文件：

[swagger导入.txt](https://github.com/star7th/showdoc/files/4491305/swagger.txt)

**Comment by star7th** [comment]
我看了下那个txt文件，sg还有这种格式啊。一开始确实是没考虑对象类的格式，只考虑纯文本。我有空再更新下。

NBTim <notifications@github.com> 于2020年4月17日周五 下午2:41写道：

**Comment by NBTim** [comment]
多谢支持

**Comment by star7th** [comment]
我在研究你给的这个txt的时候，发现所有接口的返回都是“响应信息主体”这个对象结构。那我只能把这个对象简单解析为表格然后展示出来了。
只是有点感觉这种笼统信息意义不大。这个功能是开发预览，下次发版就上线。
![image](https://user-images.githubusercontent.com/2200494/82297123-c7afc580-99e4-11ea-8349-de38aaf7d0b0.png)

**Comment by star7th** [comment]
已经把上面说的改动发新版了。

**Comment by phpitgo** [comment]
swagger3 是不支持吗？导入swagger.json之后是空白的。

**Comment by star7th** [comment]
@phpitgo 提供一个文件示例

**Comment by phpitgo** [comment]
[swagger.txt](https://github.com/star7th/showdoc/files/5235922/swagger.txt)

**Comment by star7th** [comment]
@phpitgo 新版已修复此问题
