### ISSUE TITLE
多用户

### ISSUE THREAD

**Issue by zhanghui0228** [star7th/showdoc#851]
没有多用户同时登录的功能吗？
打开新的页面登录时显示的还是上次登录用户，还得先退出来，在登录其它用户，这样很不安全

**Comment by star7th** [comment]
一般的系统都没有这个功能吧。有的反而是少数。因为很少人有这样的需求。

test <notifications@github.com> 于2020年4月17日周五 下午4:17写道：

**Comment by zhanghui0228** [comment]
嗯嗯，但是我使用新页面重新登录时显示的还是上次的登录用户，这样存在一定的风险，可以设置一个超时机制吗，该用户多长时间没有操作用户就自动退出

**Comment by star7th** [comment]
几个月才会超时。一直都会自动登录。这是普遍做法。你登录网页版微博或者网页版github的时候，它也是很久才超时。

test <notifications@github.com> 于2020年4月17日周五 下午4:24写道：

**Comment by star7th** [comment]
要提前退出只能手动点击退出。

Chen Xing <xing7th@gmail.com> 于2020年4月17日周五 下午4:26写道：

**Comment by zhanghui0228** [comment]
嗯嗯，好吧
