### ISSUE TITLE
提个建议: 文件目录支持能够隐藏功能

### ISSUE THREAD

**Issue by CodeBoy975** [star7th/showdoc#852]
隐藏目录我感觉可以提高用户体验，左侧是用户导航需要，当找到对应文档，则隐藏目录这样的话我觉得更好。我看例如：极客时间专栏，就有一个纯净模式就是隐藏目录的作用。虽然页面也没放大，但这点感觉体验会更好哈。直接中间为文档，可以更集中精力阅读，提个小小建议哈

**Comment by star7th** [comment]
感觉意义不是很大。因为showdoc本身就是让目录灰色，本意就淡化了目录的。而且showdoc本来就比较纯净。比极客专栏纯净很多。再隐藏的作用似乎比较小？

pengjie_yao <notifications@github.com>于2020年4月18日 周六下午5:58写道：
