### ISSUE TITLE
编辑页面的时候，页面排序，目录下页面无法拖动

### ISSUE THREAD

**Issue by Bjorne1** [star7th/showdoc#853]
选定了特定的目录后，下面的页面都是灰的，无法拖动排序。已脚本更新到最新版本

**Comment by star7th** [comment]
我不理解你的意思，我没有做禁用拖动的功能，不可能有出现了页面却无法拖动的情况。除非是发生了错误。看网络返回内容吧。

WenXiaoTian <notifications@github.com>于2020年4月19日 周日下午5:04写道：

**Comment by star7th** [comment]
建议试一试showdoc官网先。

Chen Xing <xing7th@gmail.com>于2020年4月19日 周日下午5:44写道：

**Comment by Bjorne1** [comment]
好的，感谢！！可以了。昨天下午和今天早上用谷歌浏览器怎么拖动都不行，然后刚换了火狐就可以拖动，再换回谷歌也变得能拖动了。。
