### ISSUE TITLE
左侧菜单名过长的情况下，鼠标焦点在右侧，菜单名消失，回到左侧，才能正常显示

### ISSUE THREAD

**Issue by suiriass** [star7th/showdoc#857]
![微信截图_20200423145443](https://user-images.githubusercontent.com/49109065/80069482-fec0c180-8573-11ea-9c26-1db026bd021d.png)

期望，菜单名不管长度如何，都能正确显示

**Comment by star7th** [comment]
是某些英文或者中英文标题才会出现这种被隐藏的情况。这个bug之前发现了，那时一时没找到原因。如果简单地显示的话会带来其他问题。这个等有空再详细看看吧。

suiriass <notifications@github.com> 于2020年4月23日周四 下午3:07写道：

**Comment by star7th** [comment]
已经在新版解决了此问题
