### ISSUE TITLE
输入访问密码敲回车键无效，点击提交按钮可以进入的问题

### ISSUE THREAD

**Issue by LeiZhiMin1** [star7th/showdoc#858]
### 打开私密项目分享链接输入密码点击回车按钮无效且清除密码问题
打开分享的链接显示
![image](https://user-images.githubusercontent.com/32741993/80167213-5f064080-8612-11ea-87a2-85c6d4b78734.png)这个页面，输入这个项目的私密，点击回车键，没有跳转至展示页面，而是清空密码，但是输入密码点击提交按钮就可以进入展示页面。

**Comment by star7th** [comment]
本意设计是点击按钮的。对快捷键的支持不是很好。我有空改善下。

leizhimin <notifications@github.com> 于2020年4月24日周五 上午10:02写道：

**Comment by star7th** [comment]
已经在新版解决了此问题

**Comment by LeiZhiMin1** [comment]
官方搭建的网站也更新了吗？

**Comment by star7th** [comment]
我记得是更新了。刷新浏览器缓存试下

leizhimin <notifications@github.com> 于2020年5月23日周六 下午2:44写道：

**Comment by LeiZhiMin1** [comment]
感谢
