### ISSUE TITLE
返回按钮能否一直保持在顶部

### ISSUE THREAD

**Issue by hellhker** [star7th/showdoc#859]
作者你好，每次修改文档页面的时候，需要退出，都要拖进度条，比较麻烦，返回按钮能否一直保持在顶部。
![image](https://user-images.githubusercontent.com/14212220/80173093-59642700-8621-11ea-879b-7c09da6a23d2.png)
![image](https://user-images.githubusercontent.com/14212220/80173116-6b45ca00-8621-11ea-9a8a-76ea93cc7f34.png)

**Comment by star7th** [comment]
这个有时间会改一下。

hellhker <notifications@github.com>于2020年4月24日 周五上午11:48写道：

**Comment by star7th** [comment]
我目前做的改动是，默认一进入页面的时候，这个保持在顶部（原来的是会一进入页面就滚动到底部）。
不过倒没有做一直保留在顶部功能，因为想给编辑器更大一点的编辑控件。
