### ISSUE TITLE
如果字段生成数据仓库Hive的表结构信息，你们有这一块的支持吗？

### ISSUE THREAD

**Issue by al1020119** [star7th/showdoc#860]

**Comment by star7th** [comment]
这个就不打算在官方脚本里支持了。你可以自己写程序读取然后调用官方开放api写进去。

iCocos <notifications@github.com>于2020年4月24日 周五上午11:52写道：

**Comment by al1020119** [comment]
你说的调用官方API是只文档里面的二次开发吗？
> https://www.showdoc.cc/help?page_id=1385576954326448
有没有相应的地方有案例，或者文档的？

**Comment by star7th** [comment]
点击新建项目——自动生成，你会看到showdoc有哪些api

iCocos <notifications@github.com> 于2020年4月24日周五 下午1:06写道：

**Comment by al1020119** [comment]
你说的这个看过了
https://www.showdoc.cc/page/312209902620725

Hive的表结构信息虽然也是存储MySQL，但是他和业务MySQL表的表结构信息的完全不同的
Hive的表结构信息是存在MySQL中的一条条真实的记录

**Comment by star7th** [comment]
如果你更自由地生成自己所需要的格式，则可参考开放API <https://www.showdoc.cc/page/102098>
https://www.showdoc.cc/page/102098

iCocos <notifications@github.com> 于2020年4月24日周五 下午1:30写道：

**Comment by al1020119** [comment]
export MYSQL_PWD=${password} 
COMMAND="set names utf8;select TABLE_NAME ,TABLE_COMMENT from tables where TABLE_SCHEMA ='${db}'  " 
declare table_info=`mysql -h${host} -P${port} -u${user}  --show-warnings=false -D information_schema -e "${COMMAND}" `
#echo $table_info
COMMAND="set names utf8;select TABLE_NAME ,COLUMN_NAME, COLUMN_DEFAULT ,IS_NULLABLE ,COLUMN_TYPE ,COLUMN_COMMENT from COLUMNS where TABLE_SCHEMA ='${db}'  " 
declare table_detail=`mysql -h${host} -P${port} -u${user}  --show-warnings=false -D information_schema -e "${COMMAND}" `
#echo $table_detail
table_info2=${table_info//&/_this_and_change_}
table_detail2=${table_detail//&/_this_and_change_}
curl -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8'  "${url}" --data-binary @- <<CURL_DATA
from=shell&table_info=${table_info2}&table_detail=${table_detail2}&api_key=${api_key}&api_token=${api_token}&cat_name=${cat_name}
CURL_DATA
export MYSQL_PWD=""

我主要想了解你们这一段具体是怎么把数据给写到你们的Show-Doc中的，
如果我按照你这种模式是否只要将table_info2和table_detail2的变量按照你们的格式，使用我自己拼接好的数据传进去，那么你们的table_info2和table_detail2和格式规范又是怎么样的？

**Comment by star7th** [comment]
有点难解释。你拿个真实mysql数据库查询出来一下就知道了。从mysql查询出来然后打印下那两个变量

iCocos <notifications@github.com> 于2020年4月24日周五 下午1:37写道：

**Comment by al1020119** [comment]
https://www.showdoc.cc/page/102098
因为这个开放API也更多的是针对API接口这一块的，
我们的核心问题处理还是数仓这一块的数据字典，关于业务MySQL的数据字段的话，是没有问题的
看过综合yapi和你们之后，最终选择你们的，就是因为上面支持数据字段，但是我这边的数仓开发，所以更倾向Hive的数据字典

> 或者你们有没有技术支持，和相关的群，还望指教！

**Comment by star7th** [comment]
解释下 table_info2=${table_info//&/*this_and_change*}  这句话。这句话意思是把字符串“&”改为字符串“
*this_and_change* ” 。后台逻辑会自动再把字符串转回来。这是为了防止&符号传送中断

Chen Xing <xing7th@gmail.com> 于2020年4月24日周五 下午1:39写道：

**Comment by star7th** [comment]
目前就只是这几个api，可以考虑兼容mysql数据规范，也可以自己全新写，利用高级api

iCocos <notifications@github.com> 于2020年4月24日周五 下午1:41写道：

**Comment by star7th** [comment]
https://www.showdoc.cc/page/102098 这个api是不限制任何内容的。只是说需要你花费点心思自己组装格式而已。

Chen Xing <xing7th@gmail.com> 于2020年4月24日周五 下午1:43写道：
