### ISSUE TITLE
导出时，如果列有空值，会导致表格错位

### ISSUE THREAD

**Issue by yunyongzhang** [star7th/showdoc#862]
导出时，如果列有空值，会导致表格错位。能否保留占位，与显示的效果一致。
![image](https://user-images.githubusercontent.com/58257917/80304510-f4f3c400-87e8-11ea-96cb-9d71844ade91.png)

**Comment by star7th** [comment]
哎，这个还真没试过。程序上对内容判空不好做到，我建议你这边尽量不要留空，写个单词none或者一个点号也行

yunyongzhang <notifications@github.com> 于2020年4月26日周日 下午6:09写道：
