### ISSUE TITLE
您好，showdoc导出的word 中的图片只能在局域网内查看

### ISSUE THREAD

**Issue by onemoretwice** [star7th/showdoc#864]
您好，showdoc导出的word 中的图片只能在局域网内查看

**Comment by star7th** [comment]
导出的图片只是个地址。不会导出全部图片数据。

onemoretwice <notifications@github.com> 于2020年4月29日周三 下午6:59写道：

**Comment by onemoretwice** [comment]
之前的版本还会将图片存储到同一目录下的文件夹内，咋砍掉这个功能了呢

**Comment by star7th** [comment]
我没有印象曾经开发过你说的功能。

onemoretwice <notifications@github.com> 于2020年4月29日周三 下午7:23写道：

**Comment by ejzhang** [comment]
> 导出的图片只是个地址。不会导出全部图片数据。 onemoretwice <notifications@github.com> 于2020年4月29日周三 下午6:59写道：
请问是否有实现直接导出图片数据的计划？

**Comment by star7th** [comment]
设计如此。只会导出图片url。要分享出去必须用外网

ejzhang <notifications@github.com> 于2020年9月7日周一 下午2:04写道：

**Comment by ejzhang** [comment]
> 设计如此。只会导出图片url。要分享出去必须用外网

好的，多谢！
