### ISSUE TITLE
点击登录无反应

### ISSUE THREAD

**Issue by xgdz** [star7th/showdoc#865]
ubuntu 安装showdoc后，进入登录页，输入初始用户名密码没反应,始终是这个页面
![1588206054(1)](https://user-images.githubusercontent.com/63387957/80659313-34593380-8abb-11ea-8585-961db39e17ee.jpg)

**Comment by star7th** [comment]
看一下网络请求返回的报错信息就知道什么错误了。

xgdz <notifications@github.com>于2020年4月30日 周四上午8:19写道：

**Comment by xgdz** [comment]
![1588206873(1)](https://user-images.githubusercontent.com/63387957/80660013-1d1b4580-8abd-11ea-8e9a-b03a1d3d5c98.jpg)
这是啥情况

**Comment by star7th** [comment]
把错误信息搜索一下网络就有答案

xgdz <notifications@github.com>于2020年4月30日 周四上午8:33写道：

**Comment by xgdz** [comment]
解决了，谢谢
执行以下命令
sudo apt-get install php7.2-zip
sudo service apache2 restart
