### ISSUE TITLE
一个项目有点大就打不开了

### ISSUE THREAD

**Issue by RobinsChens** [star7th/showdoc#866]
有办法优化么

**Comment by star7th** [comment]
提供下链接，看看项目有多大。

vpclub <notifications@github.com>于2020年4月30日 周四下午5:37写道：

**Comment by RobinsChens** [comment]
已经发你邮件，这个地址不太时候暴露

**Comment by star7th** [comment]
读取不出来，我不知道是为什么。我没有遇到过项目能大到完全打不开的程度。估计跟你的安装方式有关。比如说内存设置，nginx转发层的资源限制等。尝试用官方一键脚本安装然后把旧数据迁移过去

vpclub <notifications@github.com> 于2020年4月30日周四 下午5:54写道：

**Comment by star7th** [comment]
官网 https://www.showdoc.cc/
 测试过单项目7000个页面的情况，那样会比较卡但不至于打不开。我不知道现实里怎样的项目才会多到打不开的程度。

Chen Xing <xing7th@gmail.com> 于2020年4月30日周四 下午6:11写道：

**Comment by RobinsChens** [comment]
我放在k8s里面

**Comment by RobinsChens** [comment]
那目前的docker 模式如何调优showdoc的php 程序呢

**Comment by star7th** [comment]
我觉得这不是普遍的docker镜像问题，可能跟k8s本身有关。你尝试在普通服务器上使用docker命令安装。

vpclub <notifications@github.com>于2020年5月1日 周五下午9:58写道：

**Comment by RobinsChens** [comment]
hao

**Comment by RobinsChens** [comment]
我试了单机部署，是真的快了，k8s的限制，多谢了
