### ISSUE TITLE
普通用户是不是可以删除管理员创建的目录？

### ISSUE THREAD

**Issue by wx5123** [star7th/showdoc#867]
普通用户是不是可以删除管理员创建的目录？

**Comment by star7th** [comment]
只要你给予对方编辑权限，那么就是的。你想想，假如对方把目录下的页面全部编辑到其他目录去，或者置空，那跟删除了有什么区别。所以，有编辑权限就等于有删除权限。

wx5123 <notifications@github.com>于2020年5月1日 周五下午3:02写道：

**Comment by wx5123** [comment]
目录就像一个开发商建造的房子，可以随意改变里面的布局，但不能拆除房子，目录应该等同于页面，可编辑不可随意删除。

**Comment by star7th** [comment]
我上面说过了，编辑权限就等于删除权限。别谈什么应该不应该，而是两者就几乎等价，没办法做限制。

wx5123 <notifications@github.com>于2020年5月8日 周五上午8:40写道：

**Comment by star7th** [comment]
只要有编辑权限我就可以把你的所有内容包括目录名都置空，和删除没有太多区别。所以两者几乎等价的。别谈应不应该区分两者，而是你根本区分不了两者。

Chen Xing <xing7th@gmail.com>于2020年5月8日 周五上午8:44写道：

**Comment by star7th** [comment]
现在的缓冲策略是，目录被删除后，旗下的页面会进入回收站。可以进去项目设置里恢复。

Chen Xing <xing7th@gmail.com>于2020年5月8日 周五上午8:50写道：
