### ISSUE TITLE
被别人添加到团队之后，自己退不了

### ISSUE THREAD

**Issue by Unikind** [star7th/showdoc#869]
被别人添加到团队之后，自己却退不了。希望自己可以操作退出，之前是前公司的团队，现在自己想退却退不了，太不方便了。
![image](https://user-images.githubusercontent.com/44963935/81247944-d5149980-904d-11ea-82cd-0620b4f92d21.png)

**Comment by star7th** [comment]
后面加上。

Unikind <notifications@github.com> 于2020年5月7日周四 上午10:31写道：

**Comment by star7th** [comment]
已经在新版加上此功能。退出的时候会自动退出团队以及团队下的其他项目
