### ISSUE TITLE
当表格列多的情况时，能否考虑添加滚动条或者冻结表头的处理，目前表格列多会导致显示完整，部分列会被遮住

### ISSUE THREAD

**Issue by PeteLuo** [star7th/showdoc#87]
![image](https://cloud.githubusercontent.com/assets/18900661/19548862/8881fd14-96d3-11e6-8010-853e7dd62521.png)
当表格列多的情况时，能否考虑添加滚动条或者冻结表头的处理，目前表格列多会导致显示完整，部分列会被遮住

**Comment by star7th** [comment]
这是个问题。
如果给table加上css属性

```

    display: block;
     width: 100%; 
    overflow: auto;
    word-break: keep-all;
    overflow-x: auto;

```
是可以解决你上面的问题的。可如果加上后，当长度很短的时候，有带出了另一个问题。

所以问题先放一放，看看我比较有空的再看看，或者哪个懂前段的帮解决下
