### ISSUE TITLE
内存泄露？

### ISSUE THREAD

**Issue by stylehuan** [star7th/showdoc#870]
只有chrome浏览器有这个问题。

不管是官方自己的，还是自己搭建的，chrome浏览器打开一段时间后风扇就呼呼响，看进程Chrome的渲染进程内存有点高。关闭后正常。麻烦看下是什么原因

**Comment by star7th** [comment]
目前收到过其他用户反馈，只有MAC上的谷歌浏览器有这个问题。MAC &&
谷歌浏览器同时成立才有问题，其他都没问题。我觉得这个问题有点难找且比较小众，所以暂时没管了。

misar <notifications@github.com> 于2020年5月7日周四 上午11:36写道：

**Comment by star7th** [comment]
mac上可以使用苹果默认浏览器。

Chen Xing <xing7th@gmail.com> 于2020年5月7日周四 上午11:38写道：
