### ISSUE TITLE
首页能增加列出所有项目及可以搜索所有内容功能

### ISSUE THREAD

**Issue by zctv521** [star7th/showdoc#871]
我清楚作者开发这个软件的功能是用于团队协作.

我下载后发现这个程序真适合于内容分类存档.

比如,我分别学习了jq/tp/css/等不同的,平时把它们的一些方法做记录,用这套程序就非常合适.

若有陌生人注册了网站,就需要搜索所有内容的功能.

-----------------

首页打开也希望是显示不同的项目功能.

-----------------

目前大多数都是什么内容管理系统,但我感觉它们缺少灵活性;博客吧,又不适合多方面记录.
像作者开发的这个程序,灵活性十足,真的非常适合做另类内容管理系统,或者说做成共同爱好编辑网站,或者其它类似功能的网站.

-----------------

希望能考虑一下.

**Comment by star7th** [comment]
你的需求可能是想用作一个教程站点。这种场景可能不是非常适合showdoc。
当前来讲，由于已经支持无限目录，所以你其实可以把所有内容都放到一个项目的不同目录里，然后，再在管理后台设置首页跳转到该项目。
我现在会偏向于不支持这个需求，但是我也不说绝对，主要是看有没有更多用户有此类需求。

zctv521 <notifications@github.com> 于2020年5月7日周四 下午1:54写道：

**Comment by zctv521** [comment]
我的需求是类似于这个
https://www.kancloud.cn/

我也是搜类似功能的网站时,有人在TP里提供了你的地址.

-----------------

我自己创立了网站,和几个朋友以前的朋友在里面记录感兴趣的东西，不过后来慢慢就我自己在用了。

http://www.xiuyuanxi.com/
用标签功能对所写的内容进行分类
http://www.xiuyuanxi.com/tags.php?/406/1/

可这个依然不方便，每次写作东西时需要去填写标签名。
用栏目的方式也不切实际，每个人想创建不同的内容，栏目选择会乱。

-----------------

所以我看了你的这个程序，感觉特别符合我心里面想要的程序。

>可建立不同项目，每个项目下分不同的栏目。
>可多人协作来完成喜欢的内容，但也可以自己创立。

我主要是认为目前的内容管理系统太老式化了，不利于小型兴趣中心使用。
像知乎、简书这类的更适合使用，在我眼里，你的这个和它们有着形的相似。

**Comment by star7th** [comment]
再看看其他人是否有这样的需求吧。

zctv521 <notifications@github.com> 于2020年5月7日周四 下午3:35写道：

**Comment by wx5123** [comment]
首页增加全局搜索这个功能可以有，很实用！

**Comment by zctv521** [comment]
@wx5123 
全局搜索这个功能其实自己可以改
ItemController.class.php文件中的66行左右，item_id = '$item_id' and这段去掉就可以全局搜索。

作者没完全用TP开发，用了VUe的框架，导致我没学过那个框架，改不了。他要是完全用TP，我都能自己写个首页和随便改后台相关了。

除了自己开发，找套真合适的东西真是太难了感觉。

**Comment by star7th** [comment]
TP的开发模式过时了的。若不是为了兼容性，我连后台都不用TP，改用其他重写了。

zctv521 <notifications@github.com> 于2020年5月12日周二 上午9:38写道：

**Comment by zctv521** [comment]
@star7th 
亲，我现在如果学的话，应该学哪些呢？
我也想更新下自己的技术，让自己跟上。

我VUE也学了一点，但是所学到的东西，总感觉用不出来，感觉自己学的方向不对，希望能指点所学方向。

**Comment by star7th** [comment]
@zctv521 我不知道你想学什么。php的话，建议使用lararel 。js框架的话vue会好入门一点。做一个真正的项目产品就会用了。

**Comment by zctv521** [comment]
@star7th 
那看来还得从VUE入手，PHP框架目前会一点TP我就够用的了。

可是，我VUE好像卡住了，根本不会使用。

再就是我读了一下你的代码，想问一下，你前台用VUE等这些所写的代码，在后期更改时方便吗？
还有一点想问一下：
你用VUE等开发的前端，如果和直接用平时的div方式(TP的)开发前端，两者相对哪个快一些？会快多少？

因为我一直整不明白VUE怎么用，所以也不会开发页面，这也导致不知道它们之间的这些问题存在。

实在是太打扰了，光回答这些问题，就要浪费很多时间，这也算是最后一个外部问题了。

**Comment by star7th** [comment]
vue相比传统的div开放方式来讲，需要一定的入门门槛，但熟悉了之后要比传统方式要开快，越复杂的应用效率提高越明显。

zctv521 <notifications@github.com> 于2020年5月15日周五 下午8:12写道：

**Comment by star7th** [comment]
后期更改轻松多了。

Chen Xing <xing7th@gmail.com> 于2020年5月15日周五 下午8:14写道：

**Comment by star7th** [comment]
如果是纯div的话，标签和dom操作会显得非常乱。

Chen Xing <xing7th@gmail.com> 于2020年5月15日周五 下午8:16写道：

**Comment by zctv521** [comment]
非常感谢，那我后期主要提升下VUE。

**Comment by ht4266394** [comment]
这个建议其实需要的人挺多的，有很多的时候只是需要一目了然的看到所有的知识库，然后进行检索。目前这样的强化了登陆与团队概念，忽略了一些常识性技术与知识的管理功能，不需要登陆就无法查看项目列表，只能一个个单独分享链接，使用起来反而比较复杂。

**Comment by star7th** [comment]
已在最新master分支实现全局搜索功能。可以在自己的项目内容联合全局搜索。
