### ISSUE TITLE
关于转发，用户体验不好的地方

### ISSUE THREAD

**Issue by lpf479** [star7th/showdoc#872]
转发不会分享标题而是只会分享总栏目，这样分享出去具体内容就看不到，只有总标题，页面标题应该作为分享的title这样会更容易理解分享的内容主题是什么，showdoc非常好用，继续支持。

**Comment by star7th** [comment]
我没理解你的意思，建议截图说明

lpf479 <notifications@github.com>于2020年5月8日 周五上午8:41写道：

**Comment by lpf479** [comment]
![20200508085534](https://user-images.githubusercontent.com/61074477/81358779-0783cc80-910a-11ea-99a3-abd4bb68dfb5.jpg)
![WechatIMG2171](https://user-images.githubusercontent.com/61074477/81358846-2bdfa900-910a-11ea-9a0b-0c59bbc1ac2f.jpeg)

**Comment by lpf479** [comment]
![20200508090523](https://user-images.githubusercontent.com/61074477/81359291-4fefba00-910b-11ea-915d-fdc107a283e4.jpg)
云雀文档会geng更直观

**Comment by lpf479** [comment]
![20200508090921](https://user-images.githubusercontent.com/61074477/81359400-a0ffae00-910b-11ea-9cf2-8143f87ce5e8.jpg)

**Comment by star7th** [comment]
后面会优化下

**Comment by star7th** [comment]
已经在新版解决了此问题
