### ISSUE TITLE
添加成员是否有bug？

### ISSUE THREAD

**Issue by pingqiang806796422** [star7th/showdoc#873]
添加成员一直转圈，实际是有这个成员的

**Comment by star7th** [comment]
查看网络请求返回什么错误内容

pingqiang806796422 <notifications@github.com> 于2020年5月9日周六 上午11:12写道：

**Comment by pingqiang806796422** [comment]
不好意思， 我这边sqlite 3 not found

**Comment by star7th** [comment]
根据错误信息查找网上的解决方法就好

pingqiang806796422 <notifications@github.com> 于2020年5月9日周六 上午11:24写道：

**Comment by pingqiang806796422** [comment]
已经解决，谢谢
