### ISSUE TITLE
显示不完成

### ISSUE THREAD

**Issue by xiaojing66** [star7th/showdoc#878]
重新按编辑打开，显示不完成，markdown编辑框没有出来，需要另外刷新才会显示

**Comment by star7th** [comment]
这种情况很可能是网络问题。你清空浏览器缓存刷新看下

xiaojing66 <notifications@github.com> 于2020年5月11日周一 下午3:13写道：

**Comment by xiaojing66** [comment]
清空了缓存，还是一样，编辑的哪些选项是一片空白
要重新刷新，才会显示

**Comment by star7th** [comment]
提供下访问地址。

xiaojing66 <notifications@github.com> 于2020年5月11日周一 下午3:34写道：

**Comment by xiaojing66** [comment]
抱歉哈，我们是内网，外部访问不了

**Comment by star7th** [comment]
那我可能无能为力了。目前没有收过有其他用户反馈，有类似反馈的也只是网络问题

xiaojing66 <notifications@github.com> 于2020年5月11日周一 下午3:35写道：

**Comment by xiaojing66** [comment]
好的，谢谢

**Comment by xiaojing66** [comment]
你好，我查看了浏览器中错误，是在katex.min.css failed  editormd.js:4156 出错

**Comment by star7th** [comment]
这个是渲染公式的东西，加载不到应该不会有影响

xiaojing66 <notifications@github.com> 于2020年5月11日周一 下午4:11写道：
