### ISSUE TITLE
数据字典能否多加几列

### ISSUE THREAD

**Issue by fxl201007** [star7th/showdoc#879]
请问数据字典是否可以增加几列，别入是否是主键或索引

**Comment by star7th** [comment]
如果是自己编写的话，可以自己加的

fxl201007 <notifications@github.com> 于2020年5月11日周一 下午6:07写道：

**Comment by star7th** [comment]
如果是自动生成的，暂时是没有的。但你可以在注释里写明。

Chen Xing <xing7th@gmail.com> 于2020年5月11日周一 下午6:09写道：

**Comment by fxl201007** [comment]
请问，自己编写是什么意思，需要修改代码？

**Comment by star7th** [comment]
自己编写指的是使用showdoc在线编辑。

fxl201007 <notifications@github.com> 于2020年5月11日周一 下午6:16写道：

**Comment by fxl201007** [comment]
谢谢
