### ISSUE TITLE
使用docker部署后，怎样统一增加页面底部效果（如备案）

### ISSUE THREAD

**Issue by hy5424** [star7th/showdoc#880]
使用docker部署后，怎样同一增加页面底部效果（如备案），修改了footer.vue没有效果

**Comment by star7th** [comment]
https://github.com/star7th/showdoc/issues/765

**Comment by hy5424** [comment]
如果我这个作为主域名来使用，怎么增加备案号呢？

**Comment by star7th** [comment]
没有预留这样的位置。你可以二次开发  https://www.showdoc.cc/help?page_id=1385576954326448

hy5424 <notifications@github.com> 于2020年5月12日周二 上午11:04写道：

**Comment by hy5424** [comment]
好的，谢谢
