### ISSUE TITLE
二次开发增加了内容，本地跑没问题，打包成镜像后不显示

### ISSUE THREAD

**Issue by hy5424** [star7th/showdoc#881]
使用 npm run dev   查看新增的内容显示
使用npm run build 打包
回到Dockerfile 的目录  使用docker build -t showdoc -f Dockerfile .  生成镜像
运行镜像新增内容没有显示

**Comment by star7th** [comment]
也许只是浏览器缓存。清空下看看。另外尝试不用镜像打开看看。

hy5424 <notifications@github.com> 于2020年5月12日周二 下午6:17写道：

**Comment by hy5424** [comment]
看了一下  容器中的/var/www/html/  没有新加的内容，但是容器中的/showdoc_data/html/src有新增的内容，初步判断是Dockerfile或者start.sh导致

**Comment by star7th** [comment]
挂载的目录要是空目录。如果非空。则不会用新文件覆盖。

hy5424 <notifications@github.com>于2020年5月12日 周二下午9:09写道：

**Comment by hy5424** [comment]
谢谢 问题解决了
