### ISSUE TITLE
离线docker安装showDoc，plantuml不能正常显示

### ISSUE THREAD

**Issue by SamuelfeiW** [star7th/showdoc#882]
你好，首先我觉得showDoc是一个很好用的工具，我现在想在公司内网环境用一下，但是我发现plantuml无法访问，请问有什么办法解决吗？

**Comment by star7th** [comment]
plantuml 必须能访问外网。

SamuelfeiW <notifications@github.com> 于2020年5月13日周三 上午10:16写道：

**Comment by SamuelfeiW** [comment]
我看到plantuml有docker镜像，我也在内网环境安装好了，你能告诉我一下我在showdoc哪里修改调用链接吗？

**Comment by star7th** [comment]
js里面吧。你全局代码搜索相应的url改掉就好

SamuelfeiW <notifications@github.com> 于2020年5月13日周三 上午11:19写道：

**Comment by SamuelfeiW** [comment]
好的，我来试一下

**Comment by xddai1201** [comment]
> 好的，我来试一下

请问最后怎么解决的？
