### ISSUE TITLE
建议项目列表主页能显示更多信息

### ISSUE THREAD

**Issue by lanboss** [star7th/showdoc#883]
![image](https://user-images.githubusercontent.com/38710496/81765260-eb1ad200-9505-11ea-8b18-789c87cad789.png)
目前主页仅有项目名，希望能再显示一下信息能更多提醒用户注意，
哪些项目是公开的，哪些是私有的，公开的项目与私有的项目背景色区分显示，不然一不小心什么时候变公开的也不知道，或自己建立的项目忘记设置为私有的，也一直啪啪啪往里面放不想公开的信息；
哪些项目没设置可浏览权限在项目右下角显示“仅自己”，项目多了也不知道哪个忘记设置权限给别人看了，得挨个点开看

**Comment by star7th** [comment]
直接展示出来可能不太好。可能会采用鼠标放上去就悬浮展示的那种形式。

fighting <notifications@github.com> 于2020年5月13日周三 上午10:43写道：

**Comment by star7th** [comment]
已更新新版。鼠标悬浮会显示私密项目的标识按钮
