### ISSUE TITLE
showdoc如何限制上传文件类型

### ISSUE THREAD

**Issue by sevck** [star7th/showdoc#884]
我目前使用的是官方提供的docker版本，上传附件，上传的php文件被解析了
如果上传的一句话木马，那么网站直接GG了，如何限制或者阻止上传的文件类型？

**Comment by star7th** [comment]
更新到最新版。

sevck <notifications@github.com> 于2020年5月13日周三 下午5:24写道：

**Comment by sevck** [comment]
另外看项目用的thinkphp,老版本存在很多安全漏洞，例如框架getshell，SQL注入等等。
建议更新TP的框架版本，目前3.2.3
https://github.com/star7th/showdoc/blob/master/server/ThinkPHP/ThinkPHP.php

**Comment by star7th** [comment]
我继续用这个框架的原因是兼容性。升级框架的话，必须要求php7，这个对老服务器不友好。若真的要升级，我可能选择换laveral
。另外我自己也有能力改写框架，有问题自己解决就好，目前已完善原生框架sql注入问题。至于你说的其他问题，如果存在的话，你可以反馈一下。

sevck <notifications@github.com> 于2020年5月13日周三 下午5:30写道：

**Comment by sevck** [comment]
OK
http://docs.javasec.cn/Public/Uploads/2020-05-13/5ebbbf6ad3086.php
另外我更新了最新版，docker镜像部署，上传php还是会被解析。这个哪里有配置或者修改的地方吗？

**Comment by sevck** [comment]
http://docs.javasec.cn/Public/Uploads/2020-05-13/5ebbc058ace7c.php

**Comment by sevck** [comment]
![image](https://user-images.githubusercontent.com/11308052/81797068-e0316300-9540-11ea-8319-d8fd4c820b0b.png)

**Comment by star7th** [comment]
哎，我明明在新版做了过滤。我自己搭建个环境测试下

sevck <notifications@github.com> 于2020年5月13日周三 下午5:40写道：

**Comment by sevck** [comment]
嗯，楼主也需要考虑不仅仅是php
php3,php4,php5,phtml....之类文件后缀

**Comment by star7th** [comment]
这个问题在很久之前修复了。然后几个月前为了过滤一些特殊字符而做了变动，那次变动改了上传图片的地方，然后直接复制代码到上传附件的地方去。复制的时候忘记改变量名字。所以引起此问题。已经修复了。你按照教程升级到最新版master的代码

sevck <notifications@github.com> 于2020年5月13日周三 下午5:41写道：

**Comment by sevck** [comment]
fix,感谢楼主及时响应。
