### ISSUE TITLE
提点建议，分享页面是否可以提供多种宽度

### ISSUE THREAD

**Issue by BingyuanXie** [star7th/showdoc#885]
现在的页面宽度设置的是800，对于绝大多数PC浏览器来说，都是很窄的，作者是否可以考虑下，对于分享出去的单页，在浏览器端，是否可以手动设置不同的宽度，通过F12调试改宽度虽然可行，而且感觉展示效果也没什么问题，但毕竟有点麻烦了。另外，感谢作者的贡献~

**Comment by star7th** [comment]
为了保持不同屏幕下的样式一致，统一采用固定宽度。

Bingyuan <notifications@github.com> 于2020年5月14日周四 上午10:13写道：
