### ISSUE TITLE
迁移新服务器原服务器已分享的页面，分享页显示的地址不能访问

### ISSUE THREAD

**Issue by versionchen** [star7th/showdoc#886]
从原来使用的服务器迁移到新服务器，分享点击出来的原服务器已分享过【单页面地址 】地址访问不了
![image](https://user-images.githubusercontent.com/43264181/82174094-20f2f880-9902-11ea-8599-f3893ddac132.png)
例如：
原服务器的访问地址是http://10.1.0.81:4999/web/#/p/806bcfae45a62a18794f848b05b95a0d
新服务器的分享页显示的地址是：http://http://10.1.0.82:4999/web//p/806bcfae45a62a18794f848b05b95a0d

**Comment by star7th** [comment]
从URL上看，少了 # 符号。我不知道你对url做了什么改动。

versionchen <notifications@github.com> 于2020年5月14日周四 上午10:27写道：

**Comment by versionchen** [comment]
是否下面这两个地方的问题？

**Comment by versionchen** [comment]
是否下面这两个地方的问题？
![image](https://user-images.githubusercontent.com/43264181/81886890-6f398c00-95d0-11ea-9869-377880a8a77a.png)
![image](https://user-images.githubusercontent.com/43264181/81886890-6f398c00-95d0-11ea-9869-377880a8a77a.png)

**Comment by star7th** [comment]
我发现问题了。是getRootPath函数获取到的url有问题。正常来讲应该是包含#符号的。
此问题只是显示的问题，不影响url的实际访问。你先手动加上#号来访问单页。

**Comment by star7th** [comment]
如果手动取消单页分享，后再点击分享，此时生成的新url就是对了的。可能对历史的url需要做一些兼容处理。

**Comment by versionchen** [comment]
有计划什么时候发版吗？

**Comment by star7th** [comment]
已经改好。你按照教程升级到最新版代码。
