### ISSUE TITLE
表格标记后不显示表格

### ISSUE THREAD

**Issue by lgp593555946** [star7th/showdoc#887]
表格标记后还是原来样式，没有变成表格样式

**Comment by star7th** [comment]
请截图说明

lgp593555946 <notifications@github.com> 于2020年5月14日周四 上午10:35写道：

**Comment by lgp593555946** [comment]
![image](https://user-images.githubusercontent.com/49109329/81886597-ad827b80-95cf-11ea-8363-464f4ab551d7.png)

**Comment by star7th** [comment]
在第一行文字的后面，不要紧接着就是表格了。要加个空格或者换行。

lgp593555946 <notifications@github.com> 于2020年5月14日周四 上午10:43写道：

**Comment by lgp593555946** [comment]
好的
