### ISSUE TITLE
苹果app不能使用吗？

### ISSUE THREAD

**Issue by lgp593555946** [star7th/showdoc#889]
图形验证码出不来，地址修改没反应，windows客户端正常

**Comment by star7th** [comment]
没修改过地址之前图形验证码可以出来不

lgp593555946 <notifications@github.com> 于2020年5月14日周四 下午12:38写道：

**Comment by star7th** [comment]
换个网络试试，看是不i是网络问题。我这边使用正常

Chen Xing <xing7th@gmail.com> 于2020年5月14日周四 下午2:04写道：

**Comment by lgp593555946** [comment]
![image](https://user-images.githubusercontent.com/49109329/81898950-4de69900-95ec-11ea-94b6-27563f490c74.png)
出不来

**Comment by star7th** [comment]
如果没修改过地址，那应该就是网络问题吧

lgp593555946 <notifications@github.com> 于2020年5月14日周四 下午2:08写道：

**Comment by toxufe** [comment]
我这报错是：该网址无法正常链接
![88064d2a83a015901b7a4b58b03ab98](https://user-images.githubusercontent.com/7663543/82000375-bd12ca80-968a-11ea-8bcf-b80892507f5c.png)

**Comment by toxufe** [comment]
用4G和无线网都试过，也用过自己搭建的项目地址，都有问题。

**Comment by lgp593555946** [comment]
都是这样，等官方修复吧。

**Comment by star7th** [comment]
我把苹果app卸载重装了下。一路使用没问题。我觉得你们很大概率是网络问题。另外确保自己赋予了网络访问权限。建议卸载重装下。

lgp593555946 <notifications@github.com> 于2020年5月15日周五 上午9:08写道：

**Comment by lgp593555946** [comment]
是iphone11吗，还是，是不是手机型号问题。4G满格信号，看视频一点不卡
![image](https://user-images.githubusercontent.com/49109329/82001874-d0279980-968e-11ea-8aaf-59df95e0f9ce.png)

**Comment by star7th** [comment]
网络问题并不一定指你的手机访问不了网络，而是跟showdoc服务器通讯有问题。比如说没有赋予网络访问权限。卸载重装试试

lgp593555946 <notifications@github.com> 于2020年5月15日周五 上午9:31写道：

**Comment by star7th** [comment]
从截图来讲似乎是有了访问权限。这是个谜，我无法重现，不知道如何解决。

Chen Xing <xing7th@gmail.com> 于2020年5月15日周五 上午9:33写道：

**Comment by toxufe** [comment]
能够确定赋予了网络权限 安卓手机没有问题。苹果手机：该网址无法正常连接。是不是手机的锅~~~

**Comment by lgp593555946** [comment]
我卸载后重新安装好了，第一次安装估计有问题，你试下

**Comment by toxufe** [comment]
打开监听 可以正常使用。
