### ISSUE TITLE
转让项目输入登录密码一直错误，检查过密码是没问题的

### ISSUE THREAD

**Issue by IT513** [star7th/showdoc#890]
docker 安装的最新版本 2020-05-13

**Comment by star7th** [comment]
这么久以来很多人转让都没问题。我倾向于认为真的输入错密码了。重置密码试试。

IT513 <notifications@github.com> 于2020年5月15日周五 上午11:41写道：

**Comment by star7th** [comment]
是输入当前登录账户的密码以验证。文字提示有说。

Chen Xing <xing7th@gmail.com> 于2020年5月15日周五 上午11:56写道：

**Comment by IT513** [comment]
@star7th  我是输入当前的账号的密码的，我找到问题了：
我转让的是 系统生成的三个项目到新建的用户上，提示密码错误
![image](https://user-images.githubusercontent.com/18183932/82078769-45897d80-9714-11ea-80ed-3be3f7bf1cf7.png)
如果是该用户主动创建的项目就可以转让成功

**Comment by IT513** [comment]
另外我是修改了  默认的系统用户名称showdoc    但是提示这三个项目的onwer 名称还是  showdoc
没事了 我在管理后台直接转让
