### ISSUE TITLE
Nginx做代理部署方式上传图片或附件突然报error_code:999

### ISSUE THREAD

**Issue by jiaojohn** [star7th/showdoc#891]
上传本地图片/server/index.php?s=/api/page/uploadImg&guid=1589538474979
Request Method: POST
错误返回{
    "error_code":999,
    "error_message":"Call to a member function assign() on a non-object 。错误位置：/var/www/html/showdoc/server/ThinkPHP/Library/Think/Controller.class.php  122"
}
之前是好的，突然这样，在issues里搜了一下，只有一个docker部署的跟我这个一样，一样检查了权限和磁盘空间都是OK的，又尝试重新拉取最新代码部署，报一样的错误

**Comment by star7th** [comment]
换一个图片试试？

jiaowenhui <notifications@github.com> 于2020年5月15日周五 下午6:33写道：

**Comment by star7th** [comment]
另外不知道大小有没有影响，先用小图片试下

Chen Xing <xing7th@gmail.com> 于2020年5月15日周五 下午6:34写道：

**Comment by jiaojohn** [comment]
您好，感谢回复！都尝试过，图片的命名是简单的英文字母，大小只有几十k，都不行

**Comment by star7th** [comment]
你这个不是最新版且经过了二次开发。我无法知道你改过什么。请尝试使用官方原版且不经过nignx试下。另外要用nginx的时候你可以启动静态文件压缩，不然访问有点慢。

jiaowenhui <notifications@github.com> 于2020年5月15日周五 下午6:39写道：
