### ISSUE TITLE
关于分享遇到的问题

### ISSUE THREAD

**Issue by jinyuchen** [star7th/showdoc#892]
您好，请问我将整个项目设置为私密，并且设置了密码，我将整个项目的文档分享给了某人，然后我发现我更换私密的密码后，他仍然可以通过之前分享的连接查看，请问这个是什么问题？怎样才能禁止之前分享过的人查看？

**Comment by star7th** [comment]
因为是记住在session里面的，所以他下次重启浏览器就会刷新权限了

jinyuchen <notifications@github.com> 于2020年5月19日周二 下午4:22写道：
