### ISSUE TITLE
v2.7 语言怎么切换，没有找到设置项啊

### ISSUE THREAD

**Issue by hutaoseven** [star7th/showdoc#896]
v2.7 语言怎么切换，没有找到设置项啊

**Comment by star7th** [comment]
没有做语言切换功能，它是在第一次初始化。你可以重新安装一个中文版，参考类似迁移教程迁移过去
https://www.showdoc.cc/help?page_id=2511252204165611

Seven <notifications@github.com> 于2020年5月20日周三 下午1:45写道：

**Comment by FancierCoder** [comment]
我是升级版本之后语言就变成了英文，不知道是什么情况😂

**Comment by star7th** [comment]
不管了。装个中文版然后把数据库文件移动过去就行了。

FancierCoder <notifications@github.com> 于2020年5月20日周三 下午2:03写道：

**Comment by hutaoseven** [comment]
脚本安装跑不起来，是我的操作有问题吗

**Comment by star7th** [comment]
我不清楚你是怎么做的。

Seven <notifications@github.com> 于2020年5月20日周三 下午2:06写道：

**Comment by hutaoseven** [comment]
我把原来安装的show_data 重命名了一下，打算重装。

**Comment by star7th** [comment]
重命名后执行./showdoc uninstall 。这个操作会删除所有数据，自己备份好。

Seven <notifications@github.com> 于2020年5月20日周三 下午2:13写道：
