### ISSUE TITLE
新增文档出问题了

### ISSUE THREAD

**Issue by hutaoseven** [star7th/showdoc#899]
![image](https://user-images.githubusercontent.com/7609067/82536329-de882080-9b7a-11ea-99ad-b1a13bcdb9c0.png)

**Comment by star7th** [comment]
有些报错只是因为内网加载不了一些渲染markdown公式的东西，并不会影响使用。如果不影响使用就暂时不用管

Seven <notifications@github.com> 于2020年5月21日周四 下午3:51写道：

**Comment by hutaoseven** [comment]
新增内容报错：request fail

**Comment by star7th** [comment]
提供下网址我看下，这样看不出什么问题。另外你先刷新浏览器缓存试试。

Seven <notifications@github.com> 于2020年5月21日周四 下午3:55写道：

**Comment by hutaoseven** [comment]
Sqlite文件夹不可写，造成的

**Comment by star7th** [comment]
那就看一下为何不可写，是权限问题还是磁盘满了。

Seven <notifications@github.com> 于2020年5月21日周四 下午4:09写道：

**Comment by hutaoseven** [comment]
起初 showdoc.db.php 给了可写权限了，但是Sqlite文件夹没给可写权限；
日志报错 `ERR: 14:unable to open database file`
后来加上可写权限就好了
