### ISSUE TITLE
切换分组和页面的时候url没有变化

### ISSUE THREAD

**Issue by CinderellaCiCi** [star7th/showdoc#9]
page_id没切换

例如：
在页面
http://doc.star7th.com/index.php/home/item/show?item_id=2
切换左边分支进入到页面
http://doc.star7th.com/index.php/home/item/show?page_id=10&item_id=2

浏览器上的url没变化，还是显示不带page参数的url

**Comment by star7th** [comment]
页面内容是通过iframe加载的，page_id确实不会变化的，这个不算bug吧，在预料的范围内

**Comment by CinderellaCiCi** [comment]
我是从使用的角度来提哒。（表示不懂技术，所以非技术角度
如果可以，何不把变化改掉呢？
比如一个项目里面有很多页面，分享给项目成员参考，如果链接不正确，项目成员还是得去找这篇。

**Comment by star7th** [comment]
我在页面删除按钮的旁边增加了个页面“分享”按钮，点击即可弹出该页面的访问地址，直接复制给好友即可

**Comment by CinderellaCiCi** [comment]
感觉这个地方还是有点问题。

在切换页面的时候，原页面A如果很长的内容切换到只有一点点内容的页面B，右边的滚动条缩短得很厉害，并且下拉时有大片的空白。。
