### ISSUE TITLE
样式问题

### ISSUE THREAD

**Issue by renakeji** [star7th/showdoc#90]
代码样式，编辑预览的时候效果看起来很爽，但是保存以后前台预览的话
1.行号没有了
2.色彩高亮颜色也变了

**Comment by star7th** [comment]
前端使用bootstrap，和编辑器的样式有稍微的区别，特别是代码颜色上。
另外，我觉得不应该显示行号的。对于代码编辑器来讲行号很必要。但对于展示性质的文档来说，显示行号不是很必要，尤其是显示中文文字块的时候。所以我刚更新，把编辑器的行号也去掉了，让编辑器尽量靠近前端显示。
