### ISSUE TITLE
请问项目是前后端完全分离么?

### ISSUE THREAD

**Issue by thinkgos** [star7th/showdoc#900]
rt,项目是采用模板直接渲染,还是完全分离采用json进行通信.

**Comment by star7th** [comment]
完全分离

jiang <notifications@github.com> 于2020年5月22日周五 下午5:18写道：

**Comment by star7th** [comment]
https://www.showdoc.cc/help?page_id=1385576954326448

Chen Xing <xing7th@gmail.com> 于2020年5月22日周五 下午5:18写道：

**Comment by thinkgos** [comment]
非常感谢,想采用golang的gin框架实现一版,当成学习使用.
