### ISSUE TITLE
Markdown支持的details标签不完善

### ISSUE THREAD

**Issue by kezhan-tech** [star7th/showdoc#901]
```
<details open>
<summary>展开查看</summary>
	<table>
		<thead>
			<tr>
				<th>1</th>
			</tr>
		</thead>
	</table>
</details>
```
该段内容在`showdoc`解析的时候`<summary>展开查看</summary>`未能正确的解析。
我在官网[https://pandao.github.io/editor.md/](https://pandao.github.io/editor.md/)测试的时候是正常的，是不是我们的editor.md没有升级呢？

最近部署的，采用自动脚本安装的，麻烦大佬有空时可以看下哈

**Comment by star7th** [comment]
由于我对 editor.md 做过不少改动，基本不敢直接升级新版。所以这个问题先遗留吧。可能空闲的时候我再对应 editor.md把功能移植过来。

kezhan-tech <notifications@github.com> 于2020年5月22日周五 下午6:12写道：
