### ISSUE TITLE
项目文档权限控制增加团队内可见

### ISSUE THREAD

**Issue by lazzicat** [star7th/showdoc#905]
现在的文档权限，有么公开，要么通过一个密码来限制访问。对于需要在项目组内共享的文档，把密码在团队成员间进行分享的方式，既不方便也不安全。希望能够增加一个选择团队成员内可见或者指定人员可见的选项。

**Comment by star7th** [comment]
进入项目设置，分配团队。如果不想其有编辑权限，可以再一个个设置只读权限

foolfox <notifications@github.com> 于2020年5月25日周一 下午2:23写道：

**Comment by lazzicat** [comment]
这个我试了，如果项目是公开的，任何人都可以通过在浏览器输入文档的网址打开，修改项目和文档的参数就能访问别的公开项目的文档了。如果设计的初衷是只允许团队内成员可见的，那这里就有越权访问的漏洞了。

**Comment by star7th** [comment]
”
修改项目和文档的参数就能访问别的公开项目的文档了“，这是”别的公开项目文档“的问题。showdoc一开始的设计，默认公开文档就是完全公开的。不想公开的请设置访问密码。我建议不要试图隐藏url的方式来实现项目的私密性，迟早泄密。

foolfox <notifications@github.com> 于2020年5月25日周一 下午2:36写道：

**Comment by star7th** [comment]
想做到”
只允许团队内成员可见的“，那么，先给项目设置一个访问密码，谁都不知道。这样避免了公开访问。然后，分配团队到该项目。团队里的人自然能进入这个项目，不需要访问密码。

Chen Xing <xing7th@gmail.com> 于2020年5月25日周一 下午2:39写道：

**Comment by lazzicat** [comment]
懂了，想做到团队成员可见，也必须设置密码。设置了密码并不会导致只有做到密码的人才能访问。这个密码的逻辑原来是这样的。多谢指教。
