### ISSUE TITLE
建议：单文档和目录可以混排

### ISSUE THREAD

**Issue by diaomina** [star7th/showdoc#907]
现在是单文档一定会出现在目录前面，可能有些单文档需要放到最后，就无法实现

**Comment by star7th** [comment]
这个短期内不好解决，因为设计最初的时候是这样设置的。以后再看看。

UTF-8 <notifications@github.com> 于2020年5月26日周二 上午11:30写道：

**Comment by star7th** [comment]
短期内可能不打算解决混排问题,要改的地方很多.以后再说吧.
