### ISSUE TITLE
HTTP request sent, awaiting response... 404 Not Found

### ISSUE THREAD

**Issue by daizhichao** [star7th/showdoc#908]
用脚本安装的时候出现
install.lock
HTTP request sent, awaiting response... 404 Not Found
![Uploading image.png…]()

**Comment by star7th** [comment]
尝试自己使用docker一步步安装  https://www.showdoc.cc/help?page_id=65610

daizhichao <notifications@github.com> 于2020年5月26日周二 下午5:18写道：

**Comment by daizhichao** [comment]
已经装好了，谢谢，另外问下，能不能改默认端口

**Comment by star7th** [comment]
官方只提供这个推荐配置，自定义的话自己看着改吧。

daizhichao <notifications@github.com> 于2020年5月26日周二 下午5:59写道：
