### ISSUE TITLE
用户A创建了公开项目  新注册用户B怎么看不到呢

### ISSUE THREAD

**Issue by yjihqi** [star7th/showdoc#912]
用户A创建了公开项目  新注册用户B怎么看不到呢
本地PHP部署模式

并且注册了新用户，自带官方的3个项目，每次注册新用户都有。怎么删除呢

**Comment by star7th** [comment]
公开项目的意思是，所有人都可以通过项目链接来访问。要出现在他自己的列表，他应该被添加为项目成员

yjihqi <notifications@github.com> 于2020年5月28日周四 上午6:02写道：

**Comment by star7th** [comment]
示例项目是系统生成/后面再开放设置是否自动生成。我觉得你可能不是把showdoc用于IT团队文档。showdoc注重IT团队文档，其他需求可能不会被满足。

Chen Xing <xing7th@gmail.com> 于2020年5月28日周四 上午9:21写道：

**Comment by yjihqi** [comment]
请问在哪里关闭 示例项目自动生成呢？  后台里没看到有开关啊

**Comment by star7th** [comment]
以后可能加这个功能。现在没有。另外麻烦你说明下你的使用场景，为什么需要这个功能

yjihqi <notifications@github.com> 于2020年5月28日周四 上午9:34写道：

**Comment by yjihqi** [comment]
我是想通过您这项目 搭建一个学习的平台。 我们几个人自己就能分享各自的心得。

**Comment by star7th** [comment]
现在的机制是,当用户没有原创项目也没有协作项目,则会在登录的时候生成示例项目.  想不生产的话,就给新用户分配一个协作项目 .鉴于此需求比较少,官方程序不改了.
