### ISSUE TITLE
接口文档返回结果示例代码块内容为xml格式，导出word后代码块中的内容为空

### ISSUE THREAD

**Issue by hansongll** [star7th/showdoc#913]
谢谢，如题

**Comment by star7th** [comment]
导出的word文件是html来的，会跟xml语法冲突。所以导出的word最好别有xml。暂时没找到好的方法。

hansongll <notifications@github.com> 于2020年5月28日周四 上午10:05写道：

**Comment by hansongll** [comment]
好的，谢谢
