### ISSUE TITLE
要是能在项目下面设置子目录的权限就完美了

### ISSUE THREAD

**Issue by kussatom** [star7th/showdoc#914]
想对单页面设置权限 ，又只能针对整个项目。

**Comment by star7th** [comment]
暂时不打算做这样精细的权限设置。会增加使用复杂度。大部分人用不上这功能

kussatom <notifications@github.com> 于2020年5月28日周四 上午11:40写道：

**Comment by kussatom** [comment]
嗯，小公司可能是。大公司就用得上了，人多了团队就多了又不想分成那么多项目，不然查找 起来就麻烦了。我们几百人的配置文档 分成项目的话就不好找了。

**Comment by star7th** [comment]
后面我再好好调研下这个功能的必要性

**Comment by kussatom** [comment]
期待中

**Comment by kussatom** [comment]
能有项目子目录就很OK了

**Comment by star7th** [comment]
已更新新版，可以给成员只授权项目的某个目录，适合更精细化的权限控制。

**Comment by kussatom** [comment]
NICE！！！  感谢

**Comment by kussatom** [comment]
等会试一下
