### ISSUE TITLE
无法关闭注册

### ISSUE THREAD

**Issue by lsweicheng** [star7th/showdoc#915]
已经在后台关闭了开放注册,但是登陆页还是可以注册,求修复或解决办法?

**Comment by star7th** [comment]
能进入注册页面，但是用户注册就会提示说关闭注册的。再有问题的话提供下链接。

sun <notifications@github.com> 于2020年5月29日周五 下午8:42写道：

**Comment by lsweicheng** [comment]
不好意思，没往下走流程
