### ISSUE TITLE
数据库文件错误: General error: 11 database disk image is malformed

### ISSUE THREAD

**Issue by fred-rt** [star7th/showdoc#917]
今天突然报这个错误
General error: 11 database disk image is malformed
难道是因为我是用phpstorm打开showdoc.db.php的问题吗?
还能修复吗

**Comment by star7th** [comment]
被编辑器编辑过后，如果保存了，则修改了源文件格式，会损坏且无法修复。无论哪种数据库源文件被文本编辑器保存过之后都会损坏。

Fred <notifications@github.com> 于2020年5月31日周日 下午7:16写道：
