### ISSUE TITLE
公开项目希望所有人可见

### ISSUE THREAD

**Issue by laozhou333** [star7th/showdoc#918]
hi ,很高兴使用showdoc，他解决了我们和游戏第三方公司的很多问题，但目前遇到一个麻烦，showdoc公开项目也需要添加成员，才可访问，而且不支持批量添加，我们已经集成了ldap，可成员有3 400之多，要挨个加入项目是个大麻烦，所以希望把公开项目设为所有人可见，能支持的话就太棒了，谢谢！

**Comment by star7th** [comment]
如果项目不设置访问密码的话，直接发项目链接给对方，对方就可以公开看到。

laozhou333 <notifications@github.com> 于2020年6月1日周一 下午9:59写道：

**Comment by laozhou333** [comment]
我试了下确实可以，但还有一个场景，就是需要收集第三方信息，这部分得让成员自己填写，有什么好的办法吗？

**Comment by star7th** [comment]
只有成员才有编辑权限。showdoc适合IT协作的场景，确实不适合收集游客信息。

laozhou333 <notifications@github.com> 于2020年6月1日周一 下午10:12写道：

**Comment by laozhou333** [comment]
感谢您的回复，还是希望公开项目对可登陆showdoc所有人可见，或者支持批量添加成员，希望showdoc越来越好~

**Comment by star7th** [comment]
你用的不是新版吗，新版可以批量添加成员。

laozhou333 <notifications@github.com> 于2020年6月1日周一 下午10:26写道：
