### ISSUE TITLE
关于换行

### ISSUE THREAD

**Issue by renakeji** [star7th/showdoc#92]
在编辑时，写<br>不好使，发布以后是好使的，不知道编辑器实时展示的时候能不能做到<br>换行，或者其他能让编辑器和展示同时生效的标签

**Comment by renakeji** [comment]
表格有宽度限制吗，我在一段话后写的《br》，结果在半句话的时候换行了

**Comment by star7th** [comment]
markdown它自己根据网页宽度自动换行的。如果需要自己主动换行，可以考虑br标签或者p标签
