### ISSUE TITLE
无法添加团队成员

### ISSUE THREAD

**Issue by snowyyj001** [star7th/showdoc#922]
新建了一个项目，无法添加团队成员。
![QQ截图20200602182450](https://user-images.githubusercontent.com/60057619/83509774-8cda8100-a4fe-11ea-9b0b-e8d8cbf9e548.png)

**Comment by star7th** [comment]
看看网络返回什么错误提示。还有就是今天收到一个类似反馈  https://github.com/star7th/showdoc/issues/921

snowyyj001 <notifications@github.com> 于2020年6月2日周二 下午6:26写道：
