### ISSUE TITLE
配置图片附件储存到云后图片无法上传，提示undefined

### ISSUE THREAD

**Issue by dowan1995** [star7th/showdoc#923]
可以详细描述一下具体的key对应的value应该填什么吗
我在配置好key、secret、endpoint、bucket、oss绑定域名(选填)后，在文档内插入图片提示undefined
具体的endpoint和bucket应该填什么内容，有没有示例

**Comment by star7th** [comment]
endpoint是一个url ，  bucket是一个单词，建议你阅读阿里云得界面提示，以 endpoint和 bucket为关键字搜索一下页面

Dowan <notifications@github.com> 于2020年6月3日周三 下午5:21写道：
