### ISSUE TITLE
前端项目的eslint规则

### ISSUE THREAD

**Issue by mudoo** [star7th/showdoc#925]
额...web_src下的eslintrc.js配置了standard规则，然而项目并没有按照standard规范...
运行lint后一堆的报错...

**Comment by star7th** [comment]
其实是写得比较随意，没有考虑到兼容标准。尤其是一些命名，以前的想法和现在的想法不一样，维护久了就采用不一致的风格写各种组件。有时间再慢慢完善吧。

踩着单车载着猪 <notifications@github.com> 于2020年6月3日周三 下午6:24写道：

**Comment by mudoo** [comment]
@star7th 我看项目都有editorConfig跟eslint配置，可是项目并没有按照配置的规范
建议IDE安装插件，可以保持风格统一，PR也会比较友好

**Comment by star7th** [comment]
已更新新版，优化了代码规范。
