### ISSUE TITLE
数据丢失

### ISSUE THREAD

**Issue by chen7370** [star7th/showdoc#926]
2020-06-03 下午编辑的，然后2020-06-04 早上来没了

**Comment by star7th** [comment]
请提供访问链接

chen7370 <notifications@github.com> 于2020年6月4日周四 上午9:21写道：

**Comment by star7th** [comment]
最好也能截图说明下详细情况

Chen Xing <xing7th@gmail.com> 于2020年6月4日周四 上午9:22写道：

**Comment by chen7370** [comment]
http://doc.hostx9d9f9c9b7.jiexi.88ming.com/web/#/29?page_id=720 
情况大致是下午新加的目录及文档消失，改过的文件恢复，感觉像回档

**Comment by star7th** [comment]
你是怎么安装的

chen7370 <notifications@github.com> 于2020年6月4日周四 上午9:56写道：

**Comment by chen7370** [comment]
直接网页访问的

**Comment by star7th** [comment]
showdoc唯一官网地址是 https://www.showdoc.cc/
如果你使用的不是官网，则可能是别人部署的开源版代码。这个时候，别人还原数据也是有可能的。如果你使用的是自己公司部署的，则找自己公司部署showdoc的人

chen7370 <notifications@github.com> 于2020年6月4日周四 上午10:00写道：

**Comment by chen7370** [comment]
oo 谢谢
