### ISSUE TITLE
表格不能调整列的宽度

### ISSUE THREAD

**Issue by dongzhengshang** [star7th/showdoc#927]

**Comment by star7th** [comment]
设计如此，不让调整宽度。

DZSDevelop <notifications@github.com> 于2020年6月4日周四 下午6:41写道：

**Comment by DZSDevelop** [comment]
![image](https://user-images.githubusercontent.com/9377875/83827267-76a40f00-a710-11ea-8bf5-412f1e2560f5.png)
如果不能调整单列的宽度,整个表格呈现出来的效果非常差,很多数据都会挤到一块。

**Comment by star7th** [comment]
五列以及五列之内会平均等分宽度。五列之后就根据字数来分配宽度。

DZSDevelop <notifications@github.com> 于2020年6月5日周五 上午9:41写道：

**Comment by star7th** [comment]
这是为了照顾大部分情况下的阅读体验。少数情况确实是不友好了。

Chen Xing <xing7th@gmail.com> 于2020年6月5日周五 上午9:42写道：
