### ISSUE TITLE
希望文档查看增加一种权限：仅登录可看

### ISSUE THREAD

**Issue by aweihaitun** [star7th/showdoc#928]
目前只有两种模式，公开项目与私密项目
前者是所有人知道文档地址都能看到，后者是需要访问密码;
但是对于团队而言，如果文档地址泄露就不太安全了，同时又不想每个项目都加独立密码，所以希望根据成员的项目权限来限制文档访问，未登录的人禁止查看任何文档

**Comment by star7th** [comment]
项目成员访问项目是不需要访问密码的。加密码只是为了防止非项目成员。

aweihaitun <notifications@github.com>于2020年6月5日 周五下午12:07写道：

**Comment by star7th** [comment]
上面的意思也就是说，你将项目设置私密。然后添加成员。成员就可以访问你的项目，同时保证了游客不能看你的。
