### ISSUE TITLE
mac最新客户端没有针对项目目录权限设置，web端有

### ISSUE THREAD

**Issue by rboleynl** [star7th/showdoc#929]
web端有对目录的设置：
![image](https://user-images.githubusercontent.com/10266095/83996465-d871ac80-a98e-11ea-9f37-31a772802596.png)
mac端没有：
![image](https://user-images.githubusercontent.com/10266095/83996479-e1fb1480-a98e-11ea-873c-a360917fe16a.png)

**Comment by star7th** [comment]
应该有的。你尝试点击左上角的窗口进行刷新

boleyn <notifications@github.com> 于2020年6月8日周一 下午1:50写道：

**Comment by rboleynl** [comment]
刷新之后就有了，多谢~
