### ISSUE TITLE
提个目录列表分类的需求... T T 

### ISSUE THREAD

**Issue by xfxq1154** [star7th/showdoc#93]
添加目录的页面里, 下面有个目录列表,  那里的目录一多就感觉特别的乱 , 能根据子目录分类么?

**Comment by star7th** [comment]
我记得之前看了你的问题来着，后来因为做其他事忘记回复了。现在才看回历史。
子目录分类，我看看怎么处理

**Comment by wingmeng** [comment]
目录的管理感觉很不方便，下面的目录列表是全部水平显示出来的，无法区分目录等级和从属关系。建议用zTree，然后左侧加个编辑按钮，点击后处于编辑模式（页面无跳转、弹窗），可对目录直接进行增删改操作，也可以拖动排序、更改从属关系等。

**Comment by star7th** [comment]
囧，子目录分类一直没什么时间弄。
有机会按照 @wingmeng 说的用ztree试试

**Comment by star7th** [comment]
当前我做了一个简单的更新，添加目录的页面，展示目录将按照二级目录、三级目录两种分类来展示。
![image](https://user-images.githubusercontent.com/2200494/27768141-06042026-5f3f-11e7-865b-671472c0933d.png)

用ztree的方式需要改很多东西，整个目录和页面管理的交互方式。当前没时间先不研究之。
