### ISSUE TITLE
APP无法连接私有服务器

### ISSUE THREAD

**Issue by LuYinhao** [star7th/showdoc#930]
一直提示该网址无法正常连接

**Comment by star7th** [comment]
发地址出来看看

Lucas <notifications@github.com> 于2020年6月8日周一 下午3:41写道：

**Comment by star7th** [comment]
你的网址证书过期了，浏览器都访问不了

Lucas <notifications@github.com> 于2020年6月8日周一 下午3:47写道：

**Comment by star7th** [comment]
如果说这是你自己制作的证书，那么，自己搜索下网络加上系统信任证书里面

Chen Xing <xing7th@gmail.com> 于2020年6月8日周一 下午3:55写道：

**Comment by LuYinhao** [comment]
不好意思，写错了，http://doc.luyinhao.top  您试一下

**Comment by star7th** [comment]
我苹果手机，在showdoc客户端输入这个地址没问题。要输入Http的。

Lucas <notifications@github.com> 于2020年6月8日周一 下午3:57写道：

**Comment by LuYinhao** [comment]
我也是苹果手机，新下载的客户端，好像都无法连接网络
![image](https://user-images.githubusercontent.com/12684992/84006648-af0e4c00-a9a1-11ea-9dff-079e7c870153.png)

**Comment by star7th** [comment]
尝试用官网地址 http://www.showdoc.cc/ ，尝试卸载重装

Lucas <notifications@github.com> 于2020年6月8日周一 下午4:04写道：

**Comment by LuYinhao** [comment]
可能正好是我手机的问题吧，官网的地址都无法连接，已经重新安装了这个APP，换4G或者WiFi都不可以。是一样的错误

**Comment by rboleynl** [comment]
这明显网络问题啊,我私有的可以正常连接

**Comment by Thomas-YangHT** [comment]
我也连不上， 用的内网IP，http/https都不行，浏览器访问正常；  必须用域名吗？

**Comment by Thomas-YangHT** [comment]
内网不能连接， 换成外网， 还不能限制IP， 我限了IP就会提示无法连接，不限IP安全性存疑

**Comment by star7th** [comment]
连app必须经过外网。纯内网无法连接。
