### ISSUE TITLE
外网无法访问，nginx，mysql访问都好好的

### ISSUE THREAD

**Issue by lihua123569** [star7th/showdoc#932]
**外网无法访问**
centos8 按照官网的教程执行 https://www.showdoc.cc/help?page_id=65610

下面是我的命令
docker run -d --name showdoc --user=root --privileged=true -p 4999:4999 
-v /homework/showdoc/showdoc_data/html:/var/www/html/ star7th/showdoc

firewall，iptables都没开

使用命令curl localhost:4999访问报错信息：
curl: (56) Recv failure: Connection reset by peer

**Comment by star7th** [comment]
尝试yum update 全部软件

李健华 <notifications@github.com>于2020年6月8日 周一下午5:56写道：

**Comment by star7th** [comment]
另外也尝试用下自动脚本

Chen Xing <xing7th@gmail.com>于2020年6月8日 周一下午6:06写道：

**Comment by lihua123569** [comment]
自动脚本centos7 我之前安装没有问题的，yum update 然后要重新安装吗？

**Comment by star7th** [comment]
我一时没看清楚，好像是你端口映射不对。请不要改动官方命令

Chen Xing <xing7th@gmail.com>于2020年6月8日 周一下午6:07写道：

**Comment by star7th** [comment]
去对照文档，确保每个命令都不要改。

Chen Xing <xing7th@gmail.com>于2020年6月8日 周一下午6:08写道：

**Comment by lihua123569** [comment]
但是80端口，这个不能用吧，我的nginx用的80

**Comment by lihua123569** [comment]
严格按照命令执行是可以的。

**Comment by star7th** [comment]
你就按照官方教程来就行。它不会跟nginx冲突。你就这样就好了。

李健华 <notifications@github.com>于2020年6月8日 周一下午6:18写道：

**Comment by lihua123569** [comment]
docker run -d --name showdoc --user=root --privileged=true -p 4999:80 \
> -v /homework/showdoc/showdoc_data/html:/var/www/html/ star7th/showdoc
这样也行，80端口不能改。

**Comment by star7th** [comment]
这里80是容器里的专用的的端口，不会占用原来的80端口。

李健华 <notifications@github.com>于2020年6月8日 周一下午6:20写道：

**Comment by lihua123569** [comment]
容器里的端口也不能重复吧，比如nginx已经使用了80，其他的不能占用对吧，再有可能就是一开始没用国内镜像安装，然后有安装残余导致的。。我本次安装是把以前安装的都删了，重新安装的。后面在遇到类似问题再反馈。感谢群主
