### ISSUE TITLE
排序问题

### ISSUE THREAD

**Issue by DD384789980** [star7th/showdoc#934]
在编辑页面排序时，由于文档过多，拖动排序不方便，而且拖动时容易页面卡死，服务挂掉

**Comment by star7th** [comment]
建议按目录划分页面，避免一个目录下太多页面。若太多的话，不仅是调整顺序，平时找也很难找。showdoc现在已经支持新建无限层级子目录了。

DD384789980 <notifications@github.com> 于2020年6月9日周二 下午2:56写道：

**Comment by DD384789980** [comment]
对于已经是多层级的子目录，这种情况有解决方案么？譬如能否兼容之前的按序号排序，都感觉之前的排序挺好用的

**Comment by star7th** [comment]
之前的填数字的方式其实不适合新手理解。现在的拖动排序才是正解。你这个问题可以需要更好地划分项目以及目录结构。一个子目录下的页面多到连拖动都拖不了，这种程度太臃肿了。可以考虑切分几个不同项目或者再细分几个或者几层目录。

DD384789980 <notifications@github.com> 于2020年6月9日周二 下午3:05写道：

**Comment by DD384789980** [comment]
好的，感谢
