### ISSUE TITLE
针对html特殊字符的处理问题

### ISSUE THREAD

**Issue by Lession711** [star7th/showdoc#935]
使用版本: v2.7.1

当我在编辑为如下内容时
``` markdown
# table
| prop name | prop type        |
| list      | Array&lt;int&gt; | 
```

保存后`prop type`可以正常显示`Array<int>`

但当我再次编辑时,在编辑器中会显示为
``` markdown
# table
| prop name | prop type  |
| list      | Array<int& | 
```
再次保存将直接显示为`Array<int&`

**Comment by star7th** [comment]
你用括号吧，尽量不要用尖括号，太容易跟html标签冲突了

**Comment by Lession711** [comment]
> 你用括号吧，尽量不要用尖括号，太容易跟html标签冲突了

这是不错的方式, 但我觉得还是应该考虑一下, 因为不排除会在表格里会遇到编写大于/小于等运算符的时候, 就会有问题

**Comment by star7th** [comment]
暂时不考虑在表格里支持尖括号。
