### ISSUE TITLE
页面UI方面还是有待提升

### ISSUE THREAD

**Issue by stevqin** [star7th/showdoc#936]
1，VUE 页面代码写的太过“复杂”，代码逻辑非常不清晰。
2，页面CSS样式处理和使用存在问题，导致页面自适应存在严重问题。
3，后台管理页面风格太简陋

**Comment by star7th** [comment]
这个项目是维护了蛮长的一段时间，很多情况下是不断增加功能的，而不是一开始自上而下的规划。所以有些逻辑不会很好理解。我建议你可以针对性地指出优化思路，单纯说不好，可能没有太多帮助。

stevqin <notifications@github.com> 于2020年6月10日周三 下午5:46写道：
