### ISSUE TITLE
showdoc如何上传文件

### ISSUE THREAD

**Issue by weissxu** [star7th/showdoc#938]
showdoc如何上传文件，有这个功能吗？

**Comment by star7th** [comment]
在编辑页面可以看到附件按钮

weissxu <notifications@github.com> 于2020年6月11日周四 上午11:03写道：

**Comment by weissxu** [comment]
有图片，视频，链接，没有附件啊，能截图看下么？

**Comment by star7th** [comment]
1，使用官网版还是开源版showdoc
2，使用开源版的话，确保升级到最新版。
3，还不行的话提供编辑页面截图

weissxu <notifications@github.com> 于2020年6月16日周二 上午11:02写道：

**Comment by weissxu** [comment]
官网版

**Comment by star7th** [comment]
由于附件会给官网增加很大的流量和存储负担，暂时没开放。以后看机会开放。

weissxu <notifications@github.com> 于2020年6月16日周二 下午1:39写道：

**Comment by weissxu** [comment]
自己安装部署的版本也没有呢？  今年3月份最新的版本

**Comment by star7th** [comment]
自己部署的版本是有的。我不知道你为何说没有。

weissxu <notifications@github.com> 于2020年6月16日周二 下午5:29写道：

**Comment by star7th** [comment]
在编辑页面，插入模板的附件。

Chen Xing <xing7th@gmail.com> 于2020年6月16日周二 下午5:49写道：
