### ISSUE TITLE
导出功能

### ISSUE THREAD

**Issue by pscj** [star7th/showdoc#94]
比较了几个API文档工具，发现就这个最合适了。但是有个问题是，我们的API需要能离线查看，或者当做邮件附件发送。是否能增加导出到本地的html功能，类似javadoc那种，直接用chrome打开就能查看

**Comment by star7th** [comment]
关于这个需求，我也在评估着。可能以后会做吧。但就目前来看，showdoc的意义就在于在线文档，离线导出html有点多此一举。
对于发邮件的情况，直接发个地址给对方就好了，比如这样：http://www.showdoc.cc/demo

**Comment by pscj** [comment]
嗯，对于大部分场景来说，在线已经够用了。

**Comment by pscj** [comment]
如果能把word导出里那个表格解决了，也够用啦

**Comment by illidantao** [comment]
以静态html页文件的形式导出至本地，像gitbook那样；希望你们后续能支持。

**Comment by whsheng** [comment]
1. 通过发邮件，将文档地址给其它人，这也是个方法 [，但我发现页面样式兼容有问题。在firefox下，样式完全乱了，如下：
![image](https://user-images.githubusercontent.com/184431/28197944-da6299dc-688c-11e7-8ad7-1b719915845d.png)

**Comment by star7th** [comment]
@whsheng 这个样式是因为触发了程序转换到移动小屏幕场景下的样式。估计是屏幕分辨率比较低。
