### ISSUE TITLE
npm install 失败

### ISSUE THREAD

**Issue by 15615898763** [star7th/showdoc#940]
![8816262B31F601226B5667E12DBF01B2](https://user-images.githubusercontent.com/49017202/84359383-212d9d80-abfb-11ea-8432-715052585e5c.jpg)
<img width="1025" alt="WeChatb0d90f7b37dcfc431943838db7d91a8f" src="https://user-images.githubusercontent.com/49017202/84359463-44584d00-abfb-11ea-8563-72e58258a7ee.png">
<img width="901" alt="WeChat7f4c50c5224b1f3ef674e0d70a44f896" src="https://user-images.githubusercontent.com/49017202/84359526-59cd7700-abfb-11ea-8d5b-4a6db23d3ba7.png">

**Comment by star7th** [comment]
感觉是网络问题。删除node_moduls然后换国内npm源试一下。

15615898763 <notifications@github.com> 于2020年6月11日周四 下午3:51写道：
