### ISSUE TITLE
Sqlite/showdoc.db.php文件不可写

### ISSUE THREAD

**Issue by lanboss** [star7th/showdoc#941]
今天部署到新环境，一切准备就绪，点登录报错，搜了之前的提问，没什么有价值的信息，之前部署过2次都成功，这次怎么就这样，真奇怪，正式环境

**Comment by lanboss** [comment]
window，权限都给了

**Comment by star7th** [comment]
就是字面意思。为什么给与了权限却不可写，这得看下自己的服务器配置。比如一些其他安全限制。

fighting <notifications@github.com> 于2020年6月12日周五 下午2:31写道：

**Comment by lanboss** [comment]
问题文能解决，现发现更多线索，希望能帮锁定问题：
同一个数据库，放本地，开showdoc能跳过首页，直接进入登录页面，放生产用服务器不行；就是现实首页，
明明配了php-gd，点击注册也不显示验证码，session.save_path和extension_dir相关路径已经改好，不知道怎么到那台电脑这么多问题

**Comment by star7th** [comment]
linux服务器请使用docker  https://www.showdoc.cc/help?page_id=65610
win服务器请使用集成环境 https://www.showdoc.cc/help?page_id=4087044677189279
另外可以提供下外网连接看下。如果你坚持不使用官方推荐的部署方案，我只是爱莫能助了。

fighting <notifications@github.com> 于2020年6月12日周五 下午3:54写道：

**Comment by lanboss** [comment]
4月份的版本是不是做过什么修改，用IIS+PHP部署不了？改用phpstudy的nignx+php可以用

**Comment by star7th** [comment]
没有对环境依赖做过什么更改

fighting <notifications@github.com> 于2020年6月12日周五 下午4:55写道：

**Comment by lanboss** [comment]
解决问题了，分享一下，电脑加入域了，文件夹设置为everyone才行，虽不安全，但没更好的解决办法，不然就得用nginx
