### ISSUE TITLE
跪求API文档

### ISSUE THREAD

**Issue by hhm89106** [star7th/showdoc#943]
RT
需要通过接口传递用户名密码参数

**Comment by star7th** [comment]
没有。自己查看网络请求。

hhm89106 <notifications@github.com> 于2020年6月15日周一 下午5:33写道：

**Comment by hhm89106** [comment]
http://api.tequgroup.com:4999/server/index.php?s=/api/user/login
参数名是？

**Comment by star7th** [comment]
自己查看网络请求。如果不会就放弃二次开发吧，这是很基本的技能。连这个都不懂的话，你后面还会遇到很多麻烦的。

hhm89106 <notifications@github.com> 于2020年6月15日周一 下午5:45写道：

**Comment by hhm89106** [comment]
我们不进行二次开发，只是需要一个通用用户名密码来访问
