### ISSUE TITLE
登录用户显示

### ISSUE THREAD

**Issue by hhm89106** [star7th/showdoc#947]
能否考虑在页面左上角或右上角显示登录人员
现在需要点击三角符号才可以看到登录人员

**Comment by star7th** [comment]
zhge 不是常用操作，放出来占用视觉空间

hhm89106 <notifications@github.com> 于2020年6月16日周二 下午2:55写道：

**Comment by star7th** [comment]
这个不是常用操作，放出来占用视觉空间

Chen Xing <xing7th@gmail.com> 于2020年6月16日周二 下午2:56写道：

**Comment by hhm89106** [comment]
或者点击更多时能显示登录用户

**Comment by star7th** [comment]
请说明使用场景

hhm89106 <notifications@github.com> 于2020年6月16日周二 下午2:58写道：

**Comment by hhm89106** [comment]
主页面点击更多按钮，显示当前登录用户名
可参考Github 右上角

**Comment by star7th** [comment]
一定要这么做的理由是？

hhm89106 <notifications@github.com> 于2020年6月16日周二 下午3:01写道：

**Comment by hhm89106** [comment]
可以快速的知道现在是用哪个用户在操作系统

**Comment by star7th** [comment]
后面加一下

hhm89106 <notifications@github.com> 于2020年6月16日周二 下午3:07写道：

**Comment by star7th** [comment]
新版已经加了。
