### ISSUE TITLE
【BUG】无法使用vedio标签隐藏视频下载按钮

### ISSUE THREAD

**Issue by doanys** [star7th/showdoc#950]
vedio标签中加入controlslist="nodownload" 无法实现禁止下载，showdoc官网和开源版所使用的editormd均无效，使用editormd官方演示站点有效

```
<video src="http://media.w3.org/2010/05/sintel/trailer.mp4" type="video/mp4" controls="true" width="100%" controlslist="nodownload" data-vscid="49ddquy6v"></video>
```

editormd官方演示站点有效
![image](https://user-images.githubusercontent.com/41234678/84873025-313ef480-b0b5-11ea-8fe6-e04d180a8357.png)

showdoc的editormd编辑器无效

![image](https://user-images.githubusercontent.com/41234678/84872944-153b5300-b0b5-11ea-8626-8a58d5383902.png)

**Comment by star7th** [comment]
editormd官方就是支持的标签太多了，导致各种安全问题。看看issue就知道
。showdoc经过二次开发，过滤了很多html标签。你这个标签是没有考虑到。但考虑到这种需求太少，我可能倾向于不改了。其实隐藏不隐藏下载按钮差不多，人家一看地址，或者用下载软件嗅探一下还是能下载。


doanys <notifications@github.com> 于2020年6月17日周三 下午4:12写道：
