### ISSUE TITLE
建议增加半公开模式，即：只允许登录用户查看

### ISSUE THREAD

**Issue by joyexpr** [star7th/showdoc#951]
目前公开模式，未登录用户也能查看，而私密模式又要每个项目都要设置密码，建议能增加只允许登录用户查看的模式

我们的场景是希望文档能供我们公司内部访问，但项目较多，设置成私密模式还得记各个项目密码很不方便

**Comment by star7th** [comment]
设置一个大团队，把所有人加进去。然后批量分配项目。
其实限制内部访问的最好方式是使用内网吧。

joyexpr <notifications@github.com> 于2020年6月18日周四 上午10:59写道：

**Comment by joyexpr** [comment]
限制内部访问可能我没描述清楚，是指私有化部署只允许公司员工注册访问，至于访问方式我们是鼓励公网化能随时随地办公的

您说的设置团队方式我也有考虑过，比较灵活也能满足需求，只是感觉没有半公开模式简便些，因为我们限制注册其实就相当于设置了一个大团队。

特别对于私有化部署，公开模式安全感较弱，私密模式又要设密码比较麻烦，只允许登录用户访问还是有一定的需求，希望您后续可以考虑下

**Comment by star7th** [comment]
当前我建议你先用大团队的方式解决。至于要不要加上半公开访问模式这个功能，得看需求。再看看有没有用户反馈有这个需求。

joyexpr <notifications@github.com> 于2020年6月18日周四 上午11:27写道：

**Comment by joyexpr** [comment]
好的，谢谢
发issue前我有搜了一下，之前有一条类似issue，不过已经关闭了，我就只能再提了条

**Comment by xgdgsc** [comment]
这个我也觉得默认应该是半公开的模式，因为我看项目url是按数字排列的，不小心的话挺容易暴露在公网上任人看了
