### ISSUE TITLE
video标签的poster属性 不能用

### ISSUE THREAD

**Issue by muqiu-su** [star7th/showdoc#952]
![image](https://user-images.githubusercontent.com/67091955/84987116-3746db00-b172-11ea-8171-74f1b529c8b4.png)

**Comment by star7th** [comment]
https://github.com/star7th/showdoc/issues/950
跟这个同理，showdoc只支持部分常用标签。

**Comment by muqiu-su** [comment]
这个二次开发 可以支持么？

**Comment by star7th** [comment]
如果你懂二次开发是可以的。

muqiu-su <notifications@github.com> 于2020年6月18日周四 下午2:48写道：

**Comment by muqiu-su** [comment]
屏蔽的地方 方便 告知一下么？

**Comment by star7th** [comment]
我也一时不清楚，解决这个问题我也要去看源码的。

muqiu-su <notifications@github.com> 于2020年6月18日周四 下午2:51写道：

**Comment by muqiu-su** [comment]
恩恩，就是肯定有个地方屏蔽了，找到改一下就好了，谢谢啦
