### ISSUE TITLE
新版权限

### ISSUE THREAD

**Issue by kussatom** [star7th/showdoc#955]
新版权限功能不错 非常赞

**Comment by kussatom** [comment]
试了一下新版版下对某一个项目的子目录授权。单独添加成员时可以选择子目录，但是添加团队的时候没有这个选项啊。更多的时候还是对团队授权啊，大佬可以改进一下不啊

**Comment by star7th** [comment]
添加团队后，还要添加成员，指派项目。有了成员哟了项目，才能再指定目录

kussatom <notifications@github.com> 于2020年6月18日周四 下午11:06写道：

**Comment by star7th** [comment]
添加团队后，还要添加成员，指派项目。有了成员有了项目，才能再指定目录

Chen Xing <xing7th@gmail.com> 于2020年6月18日周四 下午11:09写道：

**Comment by kussatom** [comment]
嗯 发完我就看到了  你这反应也真是神速啊

**Comment by kussatom** [comment]
非常感谢 兄弟
