### ISSUE TITLE
新版添加成员和授权的小建议

### ISSUE THREAD

**Issue by kussatom** [star7th/showdoc#956]
1.添加团队成员的时候如果输入了会搜索输入的用户名，但是选择后已经输入的字符并没有被清除，还要手动删一下，以便搜索下一个。建议选择后自动清除啊
2.添加团队权限的时候一般都是认为这个团队的权限应该是一样的啊。现在还是需要继续在添加团队后单独对成员授权，这个好像有点点不合理呀。
产品越来越棒 ，期待。。。。。

**Comment by star7th** [comment]
第一个的话，后面优化下。
第二个其实没毛病。新添加的团队默认所有人继承了编辑权限。不需要你再单独授权。只有你设置限制某些人只读的时候，才需要单独设置

kussatom <notifications@github.com> 于2020年6月19日周五 下午1:29写道：

**Comment by kussatom** [comment]
第二个 因为是对一个项目下的文件夹授权，默认是继承了文档所有的权限，你说的也对，可能是我们这里的场景问题吧， 我们对同一个项目的子文件授权，默认应该是某个子目录而不是整个项目，现在这样就每一个成员都需要改了。比如一个团员可能有20个成员，需要授权N个子目录，那就是要操作N*20次授权了。下次要调整权限，又要来一次。这就尴尬啦。

**Comment by Aleyn123** [comment]
在showDoc 设置团队成员只有只读全都权限；但是该成员使用 RunApi 登录后依然可以修改文档内容

**Comment by star7th** [comment]
runapi默认只有编辑权限.只读的的不需要设置成员,把文档地址给对方看就行了

Aleyn123 <notifications@github.com> 于2020年7月9日周四 下午2:27写道：

**Comment by star7th** [comment]
调试接口的默认都是编辑成员,做只读成员没有意义

Chen Xing <xing7th@gmail.com> 于2020年7月9日周四 下午2:28写道：
