### ISSUE TITLE
Mac chrome打开文档详情 CPU 100%多 风扇狂转

### ISSUE THREAD

**Issue by liweiv** [star7th/showdoc#958]
Mac chrome打开文档详情 CPU 100%多 风扇狂转

**Comment by star7th** [comment]
这是个已知问题，我暂时也不知道什么，可能是浏览器跟系统有兼容问题而刚好被某些代码触发。win下没问题，mac下的其他浏览器也没问题。

李伟 <notifications@github.com>于2020年6月20日 周六上午11:04写道：

**Comment by star7th** [comment]
我现在觉得其实有可能是扩展问题。如果有后来人搜索到这个问题记得可以先用谷歌浏览器的隐私模式关闭所有扩展后排查下。我先关闭这个问题了。

**Comment by bjzhush** [comment]
我在Mac和Linux下都遇到这个问题，我一度怀疑是代码里面埋了挖矿程序

**Comment by star7th** [comment]
你们用排除法来确定下是哪个扩展的兼容问题。我试过不安装扩展的谷歌浏览器是没问题的

shawn ***@***.***>于2021年4月7日 周三上午11:58写道：

**Comment by puzzle9** [comment]
> 我在Mac和Linux下都遇到这个问题，我一度怀疑是代码里面埋了挖矿程序

我在 linux 遇到了

**Comment by star7th** [comment]
有两个用户反馈过这种情况，一个说是Vue.js devtools这个浏览器扩展引起，一个说是matamask扩展引起。我尝试重现了下，Vue.js devtools这个浏览器扩展似乎没有问题。但matamask扩展似乎是很占用cpu 。你们也帮忙定位下是哪个扩展的兼容问题，我们才好针对性定位。

**Comment by star7th** [comment]
matamask扩展是某个币的扩展，我挺怀疑它是不是利用了什么脚本挖矿。如果是那样的话，我似乎也不好定位具体哪个脚本被利用了。
你们先帮我定位是不是matamask扩展问题

**Comment by star7th** [comment]
我终于解决了这个困扰了很久的问题。用排除法定位到了是plantuml跟Metamask 扩展之间的有兼容问题。现在我改了下plantuml的js文件，把不兼容的那部分去掉了。
