### ISSUE TITLE
自己创建好的md文件，可以放进showdoc项目里面查看吗

### ISSUE THREAD

**Issue by suhuixiao** [star7th/showdoc#961]
场景是这样的，有时候一些现成的md文件，不是在线编辑的，可否放进showdoc里面

**Comment by star7th** [comment]
一般情况可能就自己复制过去吧。量太大了就写个脚本调用api写入   https://www.showdoc.cc/page/102098

suhuixiao <notifications@github.com> 于2020年6月24日周三 上午10:15写道：
