### ISSUE TITLE
runapi客户端的项目数据没办法和网页版互通吗

### ISSUE THREAD

**Issue by hsk-story** [star7th/showdoc#962]
在客户端创建的项目, 在网页上显示由undefined创建, 但网页端可以看到的项目列表, 在客户端内无法看到

**Comment by star7th** [comment]
runapi的数据可以生成markdown格式，但不可逆，markdown数据很难再转换回来runapi。所以它无法跟showdoc原有数据互相转换。只是它们可以共用文档浏览/团队协作等功能。后面如果要做数据共用，可能需要对showdoc编写格式有一定的规范约束，这个后面再探索下。


hhsskk <notifications@github.com> 于2020年6月24日周三 下午2:04写道：
