### ISSUE TITLE
支持每级标题的链接

### ISSUE THREAD

**Issue by RayMMond** [star7th/showdoc#963]
Showdoc支持生成Markdown的标题链接吗？

**Comment by star7th** [comment]
编辑栏上有按钮，鼠标放上去看一下提示。

Raymond Sun <notifications@github.com>于2020年6月25日 周四下午7:09写道：

**Comment by RayMMond** [comment]
是我没表达清楚，我的意思再查看的时候支持这样的链接
![image](https://user-images.githubusercontent.com/9551761/85713792-53bbb800-b71c-11ea-9540-4786db18bb56.png)

**Comment by star7th** [comment]
我没懂你的意思。但我觉得你多试一下就好，支持不支持实践下就知道。

Raymond Sun <notifications@github.com>于2020年6月25日 周四下午7:45写道：

**Comment by RayMMond** [comment]
我试了 😄 ，并没有，下图是我写好的文档，在查看模式的时候，标题的前后不像docker的文档，有个anchor，你可以复制这个anchor的地址，你可以打开docker的任何一个文档看一下就知道了。
![image](https://user-images.githubusercontent.com/9551761/85714745-4e12a200-b71d-11ea-9628-8d46cc68f1a7.png)

我之前图里`docker concepts` 对应的链接就是 https://docs.docker.com/get-started/#docker-concepts

**Comment by star7th** [comment]
那就是不支持了

Raymond Sun <notifications@github.com> 于2020年6月25日周四 下午7:56写道：
