### ISSUE TITLE
权限BUG来咯

### ISSUE THREAD

**Issue by kussatom** [star7th/showdoc#965]
今天发现如果一个人没有某个文档的权限  但是如果他知道这个文档的地址还是可以直接访问 。

**Comment by star7th** [comment]
showdoc只打算通过密码来加密项目。没有密码都是公开的。公开的只要知道地址就能访问。

kussatom <notifications@github.com>于2020年6月28日 周日上午10:24写道：

**Comment by kussatom** [comment]
这个密码在哪里设置啊

**Comment by star7th** [comment]
进入项目设置里。

kussatom <notifications@github.com>于2020年6月28日 周日上午10:31写道：

**Comment by kussatom** [comment]
这个看到的 ，但是只能对整个项目设置不能对单个文档或者子目录设置啊

**Comment by star7th** [comment]
不能对子目录设置密码。要就切分成不同项目。

kussatom <notifications@github.com>于2020年6月28日 周日上午10:32写道：
