### ISSUE TITLE
自动生成数据字典

### ISSUE THREAD

**Issue by wenhuaGit** [star7th/showdoc#969]
下载好脚本后并按照要求修改了参数，cat_name参数配置了一个中文目录后执行脚本，最后发现该目录下没有文档生成，数据库文档都放到了该目录得同级目录下面了。（没有按照预期，放置到指定得目录下）

**Comment by star7th** [comment]
建议截图说明，显示清楚自己是怎么配置的，生成的文档目录又是怎样的

wenhuaGit <notifications@github.com> 于2020年6月30日周二 下午6:49写道：

**Comment by wenhuaGit** [comment]
1. 在shoudow上新建了一个项目，用于存放数据库表结构
2. 下载脚本，修改了配置信息。app key token 接数据库信息
3. 保存并执行了脚本，显示执行成功了
4. 到showdoc上查看时，发现生成的表结构每放到了指定的目录中，而是在目录外。并且指定的目录为空

以下时操作及配置的截图
创建项目
![image](https://user-images.githubusercontent.com/22516487/86506780-58abf600-be05-11ea-9c31-11eafb2a7278.png)
配置脚本
![image](https://user-images.githubusercontent.com/22516487/86506785-66fa1200-be05-11ea-9bb7-17b476c5f4a2.png)
执行脚本
![image](https://user-images.githubusercontent.com/22516487/86506799-7c6f3c00-be05-11ea-8f49-d4e764ac5dc0.png)
生成的目录结构
![image](https://user-images.githubusercontent.com/22516487/86506802-7f6a2c80-be05-11ea-92ae-57f99607b873.png)

**Comment by star7th** [comment]
我本机的mysql环境出问题了。我现在暂时不好重现。这块很久没动过了，应该不至于无缘无故出问题吧。你尝试重新下载脚本然后换个数据库试下。

wenhuaGit <notifications@github.com> 于2020年7月4日周六 下午2:56写道：

**Comment by wenhuaGit** [comment]
我这边下载的是最新的脚本了，用了两个数据库测试，结果都是一样的，创建了几个项目反复测试了还是一样的，把目录改为多级或者用英文的就可以成功

**Comment by star7th** [comment]
我弄好环境试了下,没问题.我不知道你是不是改写了文件编码还是你的数据库有特殊字符或者你的系统不支持中文.至少我这边试过了是可以的

wenhuaGit <notifications@github.com> 于2020年7月6日周一 下午4:15写道：
