### ISSUE TITLE
runApi windows客户端，项目变量方便得建议

### ISSUE THREAD

**Issue by wenhuaGit** [star7th/showdoc#970]
1. 项目变量得值特别长得话页面布局就乱了
2. 变量不支持修改，不方便，希望可以支持修改功能。并且所有成员都有权限，不是只有创建者有权限
3. 如果可以支持想postman那样将登录后返回得token值设置为变量，方便其他接口调用就非常好了

**Comment by star7th** [comment]
1，变量名长的问题后面会修复下
2，修改变量的话直接删除重建就行了。项目变量目前是成员都有权限的，不只是创建者。
3，要支持这个话，得引入执行脚本功能。说实话这个功能我知道同类产品里有，但我觉得它上手门槛太高了，得各种说明才能让用户懂得如何写代码使用。用户还不一定懂得写js。先暂时不引入，我没想到一种更好的交互方式。

wenhuaGit <notifications@github.com> 于2020年6月30日周二 下午6:55写道：

**Comment by wenhuaGit** [comment]
这个项目是我们团队的另一个同事创建的，他把我们加入的他的团队，有了项目的权限。但是变量删除不了

![image](https://user-images.githubusercontent.com/22516487/86506535-b854d200-be02-11ea-91f5-7a89d59575ae.png)
![image](https://user-images.githubusercontent.com/22516487/86506537-bab72c00-be02-11ea-9e13-3dd45ee5974b.png)

**Comment by star7th** [comment]
已更新，修复了此问题。你需要更新showdoc服务端代码到最新master版

**Comment by wenhuaGit** [comment]
好的，非常感谢
