### ISSUE TITLE
大佬，给元素加overflow样式预览时样式就没了

### ISSUE THREAD

**Issue by fanaiai** [star7th/showdoc#971]
![image](https://user-images.githubusercontent.com/15922487/86120400-d53d8c80-bb06-11ea-96e3-639af9d86909.png)
像上图这样

**Comment by star7th** [comment]
换行符会转义成p标签，尝试不要包含换行符

fanaiai <notifications@github.com> 于2020年6月30日周二 下午7:21写道：

**Comment by fanaiai** [comment]
![image](https://user-images.githubusercontent.com/15922487/86121613-e1c2e480-bb08-11ea-8d3b-b161a4b13e21.png)
还是不行呢

**Comment by star7th** [comment]
那就是不支持了吧。我也忘记了过滤规则了，总之不支持html所有特性，只支持部分

fanaiai <notifications@github.com> 于2020年6月30日周二 下午7:36写道：

**Comment by fanaiai** [comment]
大佬还记得哪个文件里写的过滤吗？

**Comment by star7th** [comment]
一时间不记得了

fanaiai <notifications@github.com> 于2020年6月30日周二 下午7:51写道：
