### ISSUE TITLE
RunAPI在header添加cookie失效

### ISSUE THREAD

**Issue by Leytton** [star7th/showdoc#972]
RunAPI在header添加cookie失效，无法测试登录权限接口，postman在header添加的正常

**Comment by star7th** [comment]
这确实是个缺陷,暂时无法直接支持cookies.后面再看下怎么优化.

Leytton <notifications@github.com> 于2020年6月30日周二 下午8:32写道：

**Comment by star7th** [comment]
去重新下载runapi客户端，https://www.showdoc.com.cn/runapi  ， 已经支持cookie功能。在填写header参数的判断有个Cookies按钮。
