### ISSUE TITLE
希望增加OA系统整合showdoc实现单点登陆。

### ISSUE THREAD

**Issue by tanqin1989** [star7th/showdoc#973]
开放接口用于服务端构造url直接登陆某个账户的showdoc项目页面。
需要其他业务中判断该用户是否登陆。

**Comment by star7th** [comment]
oa登录有好多种。你不如详细说下你想要的开放接口是怎样的——入参是什么，出参是什么。

tanqin1989 <notifications@github.com>于2020年7月1日 周三上午11:05写道：

**Comment by tanqin1989** [comment]
类似这样

说明：该接口用于整合现有web系统，可以通过后端程序使某个登录状态的OA用户直接登陆showdoc，实现单点登陆;
请求地址：http://server/api/user/SsoLogin&username=XXX&password=XXX&link=XXX
参数：
name:           //用户名
passowrd:       //密码
link:           //可选。
//调用示例:
http://server/api/user/SsoLogin&username=admin&password=123&link=oa.xxx.com/xxx

**Comment by star7th** [comment]
你这个接口打算给什么调用? showdoc提供了这么一个接口,也无法实现你要的功能吧.
如果说要整合oauth2.0登录,也不是你说的这样.我不知道你这样能解决哪个程序的登录问题.我觉得解决不了任何登录问题

tanqin1989 <notifications@github.com> 于2020年7月1日周三 下午2:26写道：

**Comment by tanqin1989** [comment]
使用场景：OA平台单点登录第三方系统，
对我们而言，提供此接口即可实现单点登录（当然OA这边也要做一些配置）。 

另外，建议官方增加更多的API接口，使二次开发更完善、更便利。

**Comment by star7th** [comment]
这种方式不太可取,原因:1,在url中暴露密码,太不安全.2,不通用,无法被其他公司复用.
如果能整合企业本身的登录,这是好的.但目前没有一些很靠谱的方案,所以一直没做.showdoc管理后台就只是集成了ldap

tanqin1989 <notifications@github.com> 于2020年7月1日周三 下午4:03写道：

**Comment by rboleynl** [comment]
第三方后端可以用对称加密对用户名密码进行加密生成加密后的字符串，showdoc用对称加密解密验证登陆，至于秘钥showdoc可以提供一个单独的接口设置；

**Comment by star7th** [comment]
这种做法不通用呢,其他公司用不上.总不能showdoc官方仓库就出一个功能给你们公司专用. 感觉需要对方代码开发的事情都不好处理.
要整合企业登录得有一些通用的方案才做的了.这个是需要思考探索的

boleyn <notifications@github.com> 于2020年7月3日周五 上午11:32写道：

**Comment by rboleynl** [comment]
怎么说呢，这也不能说是专用功能，完全是一个通用的功能；可以用通用的对称加密算法对用户名密码进行加密以及解密，两边公用加密串作为加密和解密秘钥；至于公用的加密串秘钥，完全是可以showdoc提供一个接口进行设置，也就是这个加密串秘钥是完全动态的(showdoc后台可以设置)；再提供一个专门的加密验证的登陆接口即可；其实就是一般的第三方系统绑定showdoc账号，实现登陆第三方系统的时候一键登陆showdoc(至于涉及到跨域就需要showdoc可以放开限制),然后直接放一个连接打开showdoc实现免登陆，不用直接明文暴露用户名和密码;其实这种需求还是比较常用的，就是无需大搞特搞弄啥单点登录打通不同的系统；finereport报表也提供这种方式，不过是明文的(就是url明文的，不太好)，有些都是内部部署的不同系统，也无需过多考虑用户名和密码暴露问题；陆续接触过类似的简单账号绑定免登陆；

**Comment by rboleynl** [comment]
我是个人使用没有这个需求，但这个需求倒是碰到不少；
哥，都没弄个捐赠二维码啥的，oschina上也没有啊，请喝个咖啡都没法请啊

**Comment by star7th** [comment]
我后面规划下这个方案吧。
另外捐赠就没必要了。对showdoc的最好的支持是跟自己的朋友或者自己知道的IT社区宣传showdoc，建立showdoc生态。我以后可能会推出高级专业版盈利。

boleyn <notifications@github.com> 于2020年7月5日周日 上午1:22写道：

**Comment by wadegoit** [comment]
showdoc后续考虑支持下OAuth2.0么？与第三方认证平台对接

**Comment by star7th** [comment]
后面会思考下OAuth2.0

**Comment by alphaerp** [comment]
> 使用场景：OA平台单点登录第三方系统，
> 对我们而言，提供此接口即可实现单点登录（当然OA这边也要做一些配置）。
> 
> 另外，建议官方增加更多的API接口，使二次开发更完善、更便利。

我猜你应该是想要showdoc无缝集成到你的oa系统中，如果这样的话，你是属于第三方授权中心，而showdoc要对接你的auth2.0的鉴权中心。我估计showdoc很难做到，第三方规范对他而言属于未知。
要想做到无缝集成，我有一个简单方案：
1.每个注册showdoc的用户中心有个API授权码。
2.oa系统提供一个获取用户信息的接口，被showdoc通过携带授权码进行访问，返回一个accesstoken。
3.showdoc提供一个访问首页路径，格式 index?accesstoken=**&callbacklogin=oa系统登录页面被oa系统携带accesstoken进行访问

**Comment by star7th** [comment]
刚更新了下，后台增加了一个“集成登录”的菜单，支持Oauth2.0配置登录和通用接入登录。有问题可反馈。

**Comment by Zmtter** [comment]
有没有大神指导一下如何使用oauth2.0实现钉钉自动登录或扫码登陆，不胜感激

**Comment by star7th** [comment]
这几个用户都是成功配置过oauth2登录的，你可以问下他们。

https://github.com/star7th/showdoc/issues/1425
https://github.com/star7th/showdoc/issues/1399
https://github.com/star7th/showdoc/issues/1398
