### ISSUE TITLE
管理员账号应该可以修改处理密码之外的其他信息

### ISSUE THREAD

**Issue by rboleynl** [star7th/showdoc#974]
管理员应该可以修改用户全部信息，包括用户名、姓名、密码；开放注册很多账号自行注册，很多账号的用户名各种乱，管理员又没法修改，创建团队增加成员只能一个一个找，毫无规律;
后台新增用户也应该包含更多信息，如姓名

**Comment by star7th** [comment]
用户名是无法修改的。如果想统一管理，你可以禁止注册，然后只由你在后台增加账户。

boleyn <notifications@github.com>于2020年7月1日 周三上午11:56写道：

**Comment by rboleynl** [comment]
现在是已有的账号没法修改，很多用户没法区分了，也没法编辑用户的其他信息，比如姓名（只能用户自己编辑）；新增的时候也没有姓名这个字段；

**Comment by star7th** [comment]
修改姓名这个字段可以加一下.不过用户名本身是唯一不可修改的.

boleyn <notifications@github.com> 于2020年7月1日周三 下午2:39写道：

**Comment by star7th** [comment]
已更新新版，管理员可以修改用户姓名
