### ISSUE TITLE
是否考虑将来出一个能够带水印的版本？

### ISSUE THREAD

**Issue by aak1247** [star7th/showdoc#975]
是否考虑将来出一个能够显示水印的版本？
相关的功能可以有：

- 水印显示的开关
- 开关是否修改复制内容为水印
- 是否允许导出
- 导出是否包含水印

**Comment by star7th** [comment]
如果你不给对方编辑权限,对方是无法导出的.
另外那个复制内容为水印,这个比较难做到.因为复制的是纯文本,或者对方粘贴一下到记事本就变成纯文本了.
水印功能要考虑一下,看看其他用户有没有这个需求

Alex <notifications@github.com> 于2020年7月2日周四 下午3:14写道：

**Comment by aak1247** [comment]
复制的这个或者退而求其次禁止复制？f12比较难搞 但是普通用户还是能稍微防备一下的

**Comment by star7th** [comment]
先看看其他人有没有这个需求吧。

Alex <notifications@github.com>于2020年7月2日 周四下午5:01写道：

**Comment by dynhhz** [comment]
> 是否考虑将来出一个能够显示水印的版本？
> 相关的功能可以有：
> 
> * 水印显示的开关
> * 开关是否修改复制内容为水印
> * 是否允许导出
> * 导出是否包含水印

水印这个有需求+1～而且希望可以支持导出带水印的PDF

**Comment by star7th** [comment]
更新：showdoc新版管理管理后台可设置启用水印。但是目前并不计划导出的文件也支持水印
