### ISSUE TITLE
请问 如何将文档的page_id改成随机长字符

### ISSUE THREAD

**Issue by ailcc** [star7th/showdoc#979]
请问 如何将文档的page_id改成随机长字符，需要修改哪些地方才可以自动生成一串5-10位的随机ID

**Comment by star7th** [comment]
要改的地方太多了.不建议改. showdoc的设计初衷就是只有设置了密码的才是私密项目,不设置密码就代码是可访问的公开项目.

ailcc <notifications@github.com> 于2020年7月3日周五 上午9:48写道：

**Comment by ailcc** [comment]
明白了  谢谢
