### ISSUE TITLE
编辑后保存报错

### ISSUE THREAD

**Issue by zhang110912** [star7th/showdoc#98]
在centOS下部署的showDoc,在使用过程中出现，编辑完文档后保存报“http://xxx/index.php?s=home/page/save(404 NOT FOUND)”，而新建是可以保存的，在浏览器中访问index.php?s=home/page/save页面显示没有权限

**Comment by star7th** [comment]
不懂你的描述。centos6.6 实测没有问题。
页面显示没有权限的话，试着退出重新登录试试。

**Comment by zhang110912** [comment]
在red hat6.7也有同样的问题，具体操作流程如下：
新建页面->保存->编辑->修改内容->保存，页面没有反应，在google浏览器下打开控制台，发现如图所示：
![222](https://cloud.githubusercontent.com/assets/13568626/21560344/8d997b04-ce98-11e6-910f-882041e48d49.PNG)

具体发送的请求信息如下：
![333](https://cloud.githubusercontent.com/assets/13568626/21560350/aa42adfc-ce98-11e6-9cb5-80d384828cfd.PNG)

之后我是了一下在url中直接输入/indexphp?s=home/save,出现如下图所示：
![111](https://cloud.githubusercontent.com/assets/13568626/21560360/dab30f90-ce98-11e6-802b-95f6f7c66569.PNG)

**Comment by star7th** [comment]
如果你能看数据库的话，查看page表里相应的作者uid字段是否真的是你的uid

**Comment by zhang110912** [comment]
在数据库中查过了，page表中的uid跟自己的uid是一样的，还有什么原因会导致这个问题？我是在本地部署的，部署过程中有什么需要特别注意的吗？（系统是red hat6.7，使用源码方式安装了apache和php）
问题补充：保存时有时是可以保存的，但更多的时候是不行的

**Comment by star7th** [comment]
不知道会不会是你环境的session特别容易过期，导致失去登录态，所以就没权限了

**Comment by zhang110912** [comment]
抱歉，网络不太方便，未能及时回复。

应该不是session过期的问题，因为做别的操作都能正常进行，session过期的话，进行其它操作也会报错才对。

文件http://cdnjs.cloudflare.com/ajax/libs/KaTex/0.3.0katex.min.css找不到，是不是因为我的环境是无法连接外网导致的？项目是否可以在无法连接外网的环境中进行部署？是不是因为这个原因导致的？

**Comment by star7th** [comment]
这个文件是加载markdown公式插件的东西，很少使用到，离线是不会影响正常功能的。
如果不是session失效的话，我也暂时想不到有什么可能的情况了
