### ISSUE TITLE
怎么去掉右边登录和关于showdoc标识？

### ISSUE THREAD

**Issue by gaoyuliang123** [star7th/showdoc#980]
分享给别人的项目的页面，展示的时候右边登录和关于showdoc能否去掉，不想让别人看到多余的。在我下载下来后的源代码怎么去改动？

**Comment by star7th** [comment]
不支持这样的设置

gaoyuliang123 <notifications@github.com> 于2020年7月3日周五 下午11:33写道：

**Comment by gaoyuliang123** [comment]
已去掉，thanks！
