### ISSUE TITLE
runApi中提交json格式中存在空格的问题

### ISSUE THREAD

**Issue by fengyunher** [star7th/showdoc#981]
感谢作者提供了这么方便的一个工具。

**Comment by fengyunher** [comment]
我在使用中发现json格式的空格在提交后，自动去除了的bug问题，导致提交的时间字符串错误。
不知道是不是个例。

**Comment by star7th** [comment]
印象中这个问题是解决了的。你重启客户端再用看看。再不行提供下原文格式

fengyunher <notifications@github.com> 于2020年7月4日周六 上午9:27写道：

**Comment by fengyunher** [comment]
真的好了，好神奇。速度真快，不用更新软件的吗，感谢

**Comment by star7th** [comment]
有热更新机制。

fengyunher <notifications@github.com> 于2020年7月4日周六 上午9:33写道：
