### ISSUE TITLE
RunApi 响应数据快速生成参数，增加参数时没有反应

### ISSUE THREAD

**Issue by wenhuaGit** [star7th/showdoc#983]
操作截图
![image](https://user-images.githubusercontent.com/22516487/86507783-9f9de980-be0d-11ea-8e90-bf8abeebac48.png)

**Comment by star7th** [comment]
我试了下是可以的。你把客户端重启下看看。

**Comment by wenhuaGit** [comment]
我这边的客户端重启了也无法点击，我在其他同事的电脑试了一下也不行。是我的版本不对吗？需要更新？

**Comment by star7th** [comment]
对于非json数据,才会这样.会不会是数据格式不对.你贴一下原文.

wenhuaGit <notifications@github.com> 于2020年7月6日周一 下午4:12写道：

**Comment by star7th** [comment]
发现了一个bug，就是如果是postman或者sw导入的文件内容，确实是生成不了参数的。现在已经推出了一个补丁。你重启runapi应该就会热更新完毕。
