### ISSUE TITLE
请问怎么plantuml用不了了？

### ISSUE THREAD

**Issue by jinyuchen** [star7th/showdoc#984]
```plantuml后显示下面这样
![image](https://user-images.githubusercontent.com/2278493/86508393-408ea380-be12-11ea-9dc8-3843e43ad936.png)

**Comment by star7th** [comment]
看这个项目例子  https://www.showdoc.cc/1615954?page_id=3874838283960422

jinyuchen <notifications@github.com> 于2020年7月4日周六 下午4:20写道：

**Comment by star7th** [comment]
还有就是不知道是不是网络问题。你多刷新下

Chen Xing <xing7th@gmail.com> 于2020年7月4日周六 下午5:14写道：
