### ISSUE TITLE
希望增加全局搜索

### ISSUE THREAD

**Issue by cc8ci** [star7th/showdoc#985]
因为分的项目有点多后容易忘记具体写到那个项目里了，每次挨个都进项目里搜索。希望增加全局搜索。

**Comment by star7th** [comment]
全局搜索是个雷，因为假如项目很多的话也容易卡死。所以没有强制做这个功能出来。这个得好好考虑下要不要做。当前我建议你还是可以对项目规划一下吧。如果连内容都不知道放在哪个项目，可能是没有对项目进行好好的分类。

cc8ci <notifications@github.com>于2020年7月4日 周六下午7:49写道：

**Comment by cc8ci** [comment]
是的，并没做好分类。
但需求还是有的，可以做出来，但默认关闭，有需求的可配置文件中开启可能比较好。

**Comment by star7th** [comment]
看看有多少用户有这类需求吧

cc8ci <notifications@github.com> 于2020年7月4日周六 下午8:00写道：

**Comment by rboleynl** [comment]
需求肯定是有，不过php不熟...不然我都想用es搞起来`_`
项目真的很好，周边的需求估计会越来越多...

**Comment by star7th** [comment]
已在最新master分支上传了此功能代码。在我的项目列表页面上方的搜索框，可以在我的有权限的项目中全局内容搜索
