### ISSUE TITLE
关于页面与目录处于同一级下时如何排序问题

### ISSUE THREAD

**Issue by johnlhr** [star7th/showdoc#986]
现在只能针对同级下所有页面或是同级下所有录进行调整顺序，而不能将同级下的目录与页面一同进行顺序调整。是否有方法可以做到。

**Comment by star7th** [comment]
不支持页面和目录混排。页面固定显示在目录前面。

刘浩然 <notifications@github.com>于2020年7月5日 周日下午6:48写道：
