### ISSUE TITLE
是否有方法可以直接粘贴图片到文件中

### ISSUE THREAD

**Issue by johnlhr** [star7th/showdoc#987]
在写作过程中一般是载屏图象，现在只能只拉入图片文件名及链接，这样就需要再事先将图片存档后再拉入，比较麻烦，如果能够象一般的博客那样可以直接贴图就方便了

**Comment by star7th** [comment]
本来就支持。截图后，可以尝试ctrl v粘贴一下。

johnlhr <notifications@github.com>于2020年7月5日 周日下午7:39写道：
