### ISSUE TITLE
网站打不开了

### ISSUE THREAD

**Issue by 1195999342** [star7th/showdoc#989]
https://www.showdoc.cc/

**Comment by chenjingchun** [comment]
https://github.com/star7th/showdoc/issues/988#issue-651213475

**Comment by hsk-story** [comment]
目前的runapi客户端似乎是网页外包了一个exe的壳?showdoc.cc访问不了后, runapi也打不开了. 
如果真的是这样, 那这点还是挺危险的, 就变成了自建文档系统还要依赖官方服务了

**Comment by nickwu55555** [comment]
同样的问题，我服务器上保存的文档看不到了

**Comment by chenxiwangluo** [comment]
登陆不进去。。。

**Comment by 7ee3** [comment]
+1

**Comment by star7th** [comment]
runapi程序本身需要用官网拉脚本下来.其后数据会保存到私有版showdoc.
刚才是因为受到流量攻击。现在升级了防护，应该恢复了。会再继续观察一阵子。

7ee3 <notifications@github.com> 于2020年7月6日周一 上午11:54写道：

**Comment by hsk-story** [comment]
还是不行呀, 继续被打了?

**Comment by star7th** [comment]
@hsk-story 我这边全部访问正常了,你那边网络还是不行?

**Comment by 1195999342** [comment]
我这边已经可以了

**Comment by hsk-story** [comment]
@star7th 的确是我这边网络好像还是不行, 福建电信的, 手机网络可以, 可能还要一点时间

**Comment by hardy50574** [comment]
网站又打不开了。。
