### ISSUE TITLE
新增的runapi客户端问题

### ISSUE THREAD

**Issue by gx0803** [star7th/showdoc#991]
6月27号发布的runapi客户端功能很强大，比网页版提供了更丰富的功能，赞一个。但是有一个很可惜的地方。
虽然可以通过runapi调试接口直接同步到showdoc，但是却无法反向同步。
希望能够将showdoc里已经存在的项目，根据接口文档，自动同步接口数据到runapi客户端，以便于进行调试调用

**Comment by star7th** [comment]
runapi的数据可以生成markdown格式，但不可逆，markdown数据很难再转换回来runapi。所以它无法跟showdoc原有数据互相转换。只是它们可以共用文档浏览/团队协作等功能。后面如果要做数据共用，可能需要对showdoc编写格式有一定的规范约束，这个后面再探索下。


gx0803 <notifications@github.com> 于2020年7月7日周二 上午11:45写道：

**Comment by gx0803** [comment]
嗯嗯，其实现在我们生成文档主要是靠注释模板加脚本自动生成，调试接口之前用postman或者在线版的runapi，现在的runapi客户端只是多了一个选择。暂时无法实现的功能也不会影响使用，感谢您提供这么好的工具~

**Comment by hsk-story** [comment]
@star7th 我觉得这个机制可以写在官网上, 估计有挺多人一开始是会有这种疑问的

**Comment by star7th** [comment]
嗯,我在runapi 的介绍页面下方放了一些文字.

hhsskk <notifications@github.com> 于2020年7月8日周三 下午2:51写道：
