### ISSUE TITLE
上传图片或附件使用了默认的域名showdoc，应该怎么修改这配置

### ISSUE THREAD

**Issue by JUSTZWH** [star7th/showdoc#992]
![image](https://user-images.githubusercontent.com/29111739/86744863-7fb83100-c06c-11ea-8d64-eaf8f80af67a.png)

如图所示，无论是我直接在编辑文本的时候Ctrl + V还是用按钮上传或者用附件的形式，使用的都是默认的域名，如果我将域名改成我自己的就可以找到对应的资源了，我找了一下相关的文档没看到这方面的说明，或者我有看漏的地方，因此来寻求帮助

希望的是`http://showdoc`这部分能自己设置

showdoc安装方式：脚本一键安装
版本：已经更新到最新的了，脚本更新

**Comment by star7th** [comment]
绑定域名要参考这个  https://github.com/star7th/showdoc/issues/573

RLinux <notifications@github.com> 于2020年7月7日周二 下午4:15写道：

**Comment by JUSTZWH** [comment]
location / {
           proxy_pass http://showdoc;
           proxy_set_header    Host   $host;#保留代理之前的host
           proxy_set_header X-Real-IP $remote_addr;
        }
在nginx conf配置加上  `proxy_set_header    Host   $host;#保留代理之前的host`就行了

谢谢 star7th 你的解答
