### ISSUE TITLE
runapi功能建议

### ISSUE THREAD

**Issue by hsk-story** [star7th/showdoc#996]
1. 在新增接口的保存时, 能否直接将接口保存到左侧菜单栏当前点击的目录下, 这样就不用每次新增完还要手动将刚刚加的接口从个根目录拖到对应的目录下.

2. 在进行调试请求的时候, 能否将非200状态下的response也显示出来, 而不是在右上角弹框. 不然遇到一些有报错的请求时, 还要再复制请求参数到postman之类的工具上再请求一次.

**Comment by star7th** [comment]
对于第1点, 后面再优化下.
对于第2点,不建议用系统错误来替代业务级的错误 ,后面考虑要不要支持这个.

hhsskk <notifications@github.com> 于2020年7月8日周三 下午2:46写道：

**Comment by hsk-story** [comment]
@star7th 对于第二点, 我是这么想的. 如果说作为一款http请求工具, 展示完整的response信息应该是需要的.

**Comment by moobing** [comment]
@star7th 正是因为第二点来这边看下是否有解决方案，其实对接口开发人员来说，无论系统错误和业务错误，都需要详细展示出来，不然我们在做接口调试时如何发现问题和解决问题？postman正是做到这一点，希望能够原样展示response内容~这样我们可以在接口开发时只需要使用runapi了~（目前为了写文档方便开启runapi和postman两个api调试工具）

**Comment by star7th** [comment]
我想了下，确实有点后台框架是用http 状态码返回错误信息的。考虑到这个严重影响到了使用（获取不到返回内容），所以我紧急处理了下，现在已经可以获取非200状态码下的响应内容了。已经推送了补丁，你们重启runapi应该就可以热更新好。

**Comment by hsk-story** [comment]
@star7th 刚刚看了, 现在可以正常返回非200状态码的返回信息了. 谢谢, 这个issue我先关了
