### ISSUE TITLE
页面排序，触发浏览器搜索事件。2020.07.09

### ISSUE THREAD

**Issue by Zeng-QJ** [star7th/showdoc#997]
新版目录和页面排序功能，非常实用。但是不过有点小问题，能够改进一下就更好了。有如下问题或建议：
（1）如图（1-1），可以加两列向上或者向下的箭头，支持点击箭头排序。拖动的排序，偶尔会操作不准确本来想调整顺序解雇拖进了目录里。参考效果类似图（1-2）
（2）在Firefox浏览器上测试页面排序，拖动目录排序，如图（2-1）和（2-2），会触发浏览器的搜索功能，如图（2-3）。另外在Chrome上测试无问题（应该是跟浏览器提供的支持事件有关系）。
图（1-1）：
![图片](https://user-images.githubusercontent.com/60689366/86989717-9de97280-c1cd-11ea-810a-be4df8f7b926.png)
图（1-2）：
![图片](https://user-images.githubusercontent.com/60689366/86989893-f6b90b00-c1cd-11ea-9d62-df1e064da8dd.png)
图（2-1）：
![图片](https://user-images.githubusercontent.com/60689366/86990250-c3c34700-c1ce-11ea-8f05-d06797c064dd.png)
图（2-2）：
![图片](https://user-images.githubusercontent.com/60689366/86990296-ddfd2500-c1ce-11ea-8ade-6c4e56cfa9b9.png)
图（2-3）：
![图片](https://user-images.githubusercontent.com/60689366/86990327-ece3d780-c1ce-11ea-86a0-592b234c96a9.png)

**Comment by star7th** [comment]
后面优化下

**Comment by star7th** [comment]
我今天看了下那个页面排序点击跳到百度的问题。实测并无此问题。我觉得跟你的页面标题有关，可能浏览器或者浏览器扩展把日期识别为关键字了。
至于你说的那个添加箭头的问题，我个人觉得，在pc上如果操作错了，再拖回去就好，并不难操作。目前已经有几个按钮了，不想再增加按钮看起来乱乱的
