### ISSUE TITLE
开源版发现一个bug  个性域名私密项目密码错误

### ISSUE THREAD

**Issue by ailcc** [star7th/showdoc#998]
本地调试时，项目设置个性域名后，设置为私密项目，然后访问该项目。
如果是通过item_ID打开  如：127.0.0.1/1   输入密码则可以访问   
如果是通过item_domain打开 如127.0.0.1/test     则提示密码错误

**Comment by star7th** [comment]
开源版很久前不再支持个性域名,不承诺以后的功能兼容个性域名.

ailcc <notifications@github.com> 于2020年7月9日周四 上午11:21写道：

**Comment by ailcc** [comment]
明白了！
