### ISSUE TITLE
功能性建议

### ISSUE THREAD

**Issue by chiachan163** [star7th/showdoc#999]
一个Excel表格占一个项目，无法进行分类。项目多了就不好查了
建议添加一层可以管理表格的目录

**Comment by star7th** [comment]
怎么自己关闭了.我正想回复.  一个表格项目里面是可以添加多张表的 , 看左下角.  因此就没有再添加目录管理功能了.

chiachan163 <notifications@github.com> 于2020年7月9日周四 上午11:31写道：
